### PR TITLE
feat(Appbar) : integrate data table in app bar

### LINKED ISSUE #2127: [FEATURE] <Integrate Data Table in Appbar>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

_No response_

### User Story

Data table is used in footer tab, for enhansing the UI experience, we need to find a way to integrate Data Table in appbar.

Data table panel can have panel width of 100%, instead of 300px that has been assigned to other appbar options.

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Integrate data table in appbar

Fixes #2127 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/demos-navigator.html?config=./configs/navigator/07-basic-appbar.json

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2184)

### CODE REVIEW

**Review by ychoquet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2184)* status: 0 of 17 files reviewed, 1 unresolved discussion (waiting on @cphelefu, @jolevesq, and @kaminderpal)

___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2184#-NzDtHnbDdU9ey-IWRiP:-NzDtHnbDdU9ey-IWRiQ:b-5lhqe1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/230177829160025ce8f008f0d1e38b7d558db804/packages/geoview-core/src/api/config/types/config-validation-schema.json#L50)):*
> ```JSON
>         }
>       },
>       "required": ["map"]
> ```

Why do we change single line array definitions to multi line array definitions if the domain doesn't change. It is hard to find what realy changed.



_Code quote:_
```JSON
      "required": ["map"]
```

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 16 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2184)* status: 16 of 17 files reviewed, 2 unresolved discussions (waiting on @cphelefu, @kaminderpal, and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2184#-NzDtHnbDdU9ey-IWRiP:-NzDzuwy6-k420kEbRCi:b-hw9p92) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/230177829160025ce8f008f0d1e38b7d558db804/packages/geoview-core/src/api/config/types/config-validation-schema.json#L50)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Why do we change single line array definitions to multi line array definitions if the domain doesn't change. It is hard to find what realy changed.
</blockquote></details>

This is done automatically by vsCode settings. The weird this is we share these settings as it is in the repo... we will need to investigate why this is hapenning
___
*[`packages/geoview-core/src/ui/panel/panel-types.ts` line 24 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2184#-NzDfoQB6VsaoiyBm2r_:-NzDfoQB6VsaoiyBm2ra:b-w7x09r) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b8d582d0a909955c04a3a9f8491082e4759087cc/packages/geoview-core/src/ui/panel/panel-types.ts#L24)):*
> ```XML
>   panelId?: string;
>   /** Panel group name. */
>   panelGroupName?: string;
> ```

What is this groupName different then id?

**Review by ychoquet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2184)* status: 16 of 17 files reviewed, 2 unresolved discussions (waiting on @cphelefu, @jolevesq, and @kaminderpal)

___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2184#-NzDtHnbDdU9ey-IWRiP:-NzE0HFo1XpIgudSB2pM:b-ua74ec) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/230177829160025ce8f008f0d1e38b7d558db804/packages/geoview-core/src/api/config/types/config-validation-schema.json#L50)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This is done automatically by vsCode settings. The weird this is we share these settings as it is in the repo... we will need to investigate why this is hapenning
</blockquote></details>

This will increase the possibility of conflict.

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2184)* status: 16 of 17 files reviewed, 2 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/ui/panel/panel-types.ts` line 24 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2184#-NzDfoQB6VsaoiyBm2r_:-NzE0fg2AucHOQHoMQqB:b48efi4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b8d582d0a909955c04a3a9f8491082e4759087cc/packages/geoview-core/src/ui/panel/panel-types.ts#L24)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

What is this groupName different then id?
</blockquote></details>

both fields are different, like groupName is `legend` or `data-table`, where id is `AppbarPanelDatatable`

**Review by cphelefu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2184#-:-NzENvh-65CvLhhSkifv:bnfp4nl)* status: 16 of 17 files reviewed, 2 unresolved discussions (waiting on @jolevesq and @ychoquet)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2184)* status: all files reviewed, 1 unresolved discussion (waiting on @kaminderpal)

**Pull request merged**
