### PR TITLE
feat(dynamic-focus-btn): Remove all other focus buttons, and keep the…

### LINKED ISSUE #1448: [FEATURE] Refactor focus button for the best solution
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

_No response_

### User Story

We have added 3 focus buttons that we need to make a decision which one we need to keep on the page/map. 

image

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by amir-azma**
… dynamic one

# Description

We had added 3 focus buttons that we need to make a decision which one we need to keep on the page/map.
We will keep the dynamic focus button.
Fixes #1448 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Dynamic focus button will focus on either map, or footer based on the user selected. The icon and tooltip should be changed  dynamically.

https://amir-azma.github.io/geoview/raw-feature-info.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1602)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1602)* status: all files reviewed, 3 unresolved discussions (waiting on @amir-azma)

___
*[`packages/geoview-core/public/locales/fr/translation.json` line 150 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1602#-NlT8ECdD1XGJFX2PR_T:-NlT8ECdD1XGJFX2PR_U:b-z4vt67) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d5ea72556156cae6a4dfbfcd4a3f1868e4634be/packages/geoview-core/public/locales/fr/translation.json#L150)):*
> ```JSON
>   },
>   "footerTabs": {
>     "focusToMap": "Se concentrer sur la carte",
> ```

Aller à la carte
___
*[`packages/geoview-core/public/locales/fr/translation.json` line 151 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1602#-NlT8Lg--nZT1v58kaH3:-NlT8Lg--nZT1v58kaH4:b767yor) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d5ea72556156cae6a4dfbfcd4a3f1868e4634be/packages/geoview-core/public/locales/fr/translation.json#L151)):*
> ```JSON
>   "footerTabs": {
>     "focusToMap": "Se concentrer sur la carte",
>     "focusToFooter": "Focus sur le pied de page"
> ```

Aller au pied de page
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 96 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1602#-NlT8it55NF4M53-v2jw:-NlT8it55NF4M53-v2jx:b-a6uqc8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d5ea72556156cae6a4dfbfcd4a3f1868e4634be/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L96)):*
> ```XML
>   return (
>     /** TODO - KenChase Need to add styling for scenario when more buttons that can fit vertically occurs (or limit number of buttons that can be added) */
>     <Box id={`focusToMap${mapId}`} ref={navBarRef} sx={[sxClasses.navBarRef, { bottom: footerBarExpanded ? 80 : 40 }]}>
> ```

We should not have reference of focus here. Are you not able to use scrollIntoPage and use the HTML element?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/public/locales/en/translation.json` line 152 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1602#-NlTsVgZ4mwBH2AzWQz5:-NlTsVgZ4mwBH2AzWQz6:b-zhsgvo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/54301f709385d80f87fa0e8224e81cfcfd072ab8/packages/geoview-core/public/locales/en/translation.json#L152)):*
> ```JSON
>     "noChartAvailable": "Click on the map layer with chart"
>   },
>   "footerTabs": {
> ```

footerTabs kind of implies that its a footer tab title or something similar. Can we use a different name for this?

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 4 files at r2, 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1602)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/public/locales/en/translation.json` line 152 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1602#-NlTsVgZ4mwBH2AzWQz5:-NlUG7ziA0fO4HyVIq9b:b-u2naqb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/54301f709385d80f87fa0e8224e81cfcfd072ab8/packages/geoview-core/public/locales/en/translation.json#L152)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

footerTabs kind of implies that its a footer tab title or something similar. Can we use a different name for this?
</blockquote></details>

This is only for accessing, not use in display

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1602)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @cphelefu)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1602)* status: all files reviewed, 1 unresolved discussion (waiting on @cphelefu)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1602)* status: all files reviewed, 1 unresolved discussion (waiting on @cphelefu)

**Review by cphelefu — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1602#-:-NlU_CbCBfIrpswf7Xfe:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amir-azma)

**Pull request merged**
