### PR TITLE
Important layers to test

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

Created a demo page that allow to classify layers using three drop-down: group, sub group and service selectors

Fixes: The code allow us to test the services. It doesn't fix error detected. A new issue is created if a service fail and the issue is too complex to resole.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using Chrome Devtool to trace and debug the code.

__Deploy URL__: https://ychoquet.github.io/GeoView/demo-important-layers.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340)* status: all files reviewed, 9 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/public/templates/demos/demo-important-layers.html` line 6 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0tA6tr0Bcu88Z0Iv--:-O0tA6tr0Bcu88Z0Iv-0:b-y0w3d5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48e1892ef7d46438e2495876f33ed21804100e2d/packages/geoview-core/public/templates/demos/demo-important-layers.html#L6)):*
> ```HTML
>     <meta charset="UTF-8" />
>     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>     <title>Add Layers Panel - Canadian Geospatial Platform Viewer</title>
> ```

Maybe a name like the title: Important Layers Test Panel
___
*[`packages/geoview-core/public/templates/demos/demo-important-layers.html` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0tAQmjBVFMGlmM0vNz:-O0tAQmjBVFMGlmM0vO-:bp2sfv5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48e1892ef7d46438e2495876f33ed21804100e2d/packages/geoview-core/public/templates/demos/demo-important-layers.html#L37)):*
> ```HTML
>         display: flex;
>         flex-direction: row;
>         gap: 20px; /* Espacement entre les éléments */
> ```

Do we need comment^ If so, in English would be better
___
*[`packages/geoview-core/public/templates/demos/demo-important-layers.html` line 173 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0tB1950NVguaJ0oDk6:-O0tB1950NVguaJ0oDk7:b-g81296) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48e1892ef7d46438e2495876f33ed21804100e2d/packages/geoview-core/public/templates/demos/demo-important-layers.html#L173)):*
> ```HTML
> 
>     <script src="codedoc.js"></script>
>     <script>
> ```

Why each part of script is in its own script tag instead of a big one?
___
*[`packages/geoview-core/public/templates/demos/demo-important-layers.html` line 205 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0tAmbq-2k7MGM9UtKz:-O0tAmbuCA3oRY9SD5uO:b-3vvvmt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48e1892ef7d46438e2495876f33ed21804100e2d/packages/geoview-core/public/templates/demos/demo-important-layers.html#L205)):*
> ```HTML
>     </script>
>     <script>
>       function isValidUUID(uuid) {
> ```

This function shuld maybe be inside the api.utilities? May be useful somewhere else?
___
*[`packages/geoview-core/public/templates/demos/demo-important-layers.html` line 259 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0tBH3d4mf9MFiQcK4a:-O0tBH3d4mf9MFiQcK4b:b-2tq11c) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48e1892ef7d46438e2495876f33ed21804100e2d/packages/geoview-core/public/templates/demos/demo-important-layers.html#L259)):*
> ```HTML
>     </script>
>     <script>
>       var importantLayersData;
> ```

const or let
___
*[`packages/geoview-core/public/templates/demos/demo-important-layers.html` line 287 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0tBRZsCWNuxJRL6pFH:-O0tBRZsCWNuxJRL6pFI:b7zf2ir) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48e1892ef7d46438e2495876f33ed21804100e2d/packages/geoview-core/public/templates/demos/demo-important-layers.html#L287)):*
> ```HTML
>           initTableFields();
>         });
>         
> ```

Trailing white spaces
___
*[`packages/geoview-core/public/templates/demos/demos.html` line 44 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0tBaiX2HOVtdNyMKox:-O0tBaiX2HOVtdNyMKoy:b3wqxju) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48e1892ef7d46438e2495876f33ed21804100e2d/packages/geoview-core/public/templates/demos/demos.html#L44)):*
> ```HTML
>       <a href="./demo-gsc.html">GSC 46E</a>
>       <h4>Many Important Layers</h4>
>       <a href="./demo-important-layers.html">Layer Selector</a>
> ```

Should be: Important Layers Test Panel?
___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 75 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0tBwz2ByMogl3GUIMH:-O0tBwz2ByMogl3GUIMI:b-bvql81) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48e1892ef7d46438e2495876f33ed21804100e2d/packages/geoview-core/src/api/config/uuid-config-reader.ts#L75)):*
> ```XML
>             listOfGeoviewLayerConfig.push(geoviewLayerConfig);
>           } else if (isFeature) {
>             let layerEntriesToUse = layerEntries as TypeJsonArray;
> ```

Can you add a comment for this new section
___
*[`packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts` line 108 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0tCCp21goJKOOv7dDr:-O0tCCp38hF1NgDWheeo:b-bvql81) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48e1892ef7d46438e2495876f33ed21804100e2d/packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts#L108)):*
> ```XML
>             listOfGeoviewLayerConfig.push(geoviewLayerConfig);
>           } else if (isFeature) {
>             let layerEntriesToUse = layerEntries as TypeJsonArray;
> ```

Can you add a comment for this new section

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340)* status: all files reviewed, 9 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/demos/demo-important-layers.html` line 6 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0tA6tr0Bcu88Z0Iv--:-O0tDVuU4ies5hozZAZY:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48e1892ef7d46438e2495876f33ed21804100e2d/packages/geoview-core/public/templates/demos/demo-important-layers.html#L6)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Maybe a name like the title: Important Layers Test Panel
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/demos/demo-important-layers.html` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0tAQmjBVFMGlmM0vNz:-O0tDF-tBBuWkzwc7RUv:b3uzcgn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48e1892ef7d46438e2495876f33ed21804100e2d/packages/geoview-core/public/templates/demos/demo-important-layers.html#L37)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we need comment^ If so, in English would be better
</blockquote></details>

Done. removed the comment.
___
*[`packages/geoview-core/public/templates/demos/demo-important-layers.html` line 173 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0tB1950NVguaJ0oDk6:-O0xt6aV233PC3--9Rl2:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48e1892ef7d46438e2495876f33ed21804100e2d/packages/geoview-core/public/templates/demos/demo-important-layers.html#L173)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why each part of script is in its own script tag instead of a big one?
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/demos/demo-important-layers.html` line 205 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0tAmbq-2k7MGM9UtKz:-O0xtBGaB-FZ8cPkyOPO:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48e1892ef7d46438e2495876f33ed21804100e2d/packages/geoview-core/public/templates/demos/demo-important-layers.html#L205)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This function shuld maybe be inside the api.utilities? May be useful somewhere else?
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/demos/demo-important-layers.html` line 259 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0tBH3d4mf9MFiQcK4a:-O0xwk_ZD9f5ytB-6q_f:b-agf2z1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48e1892ef7d46438e2495876f33ed21804100e2d/packages/geoview-core/public/templates/demos/demo-important-layers.html#L259)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

const or let
</blockquote></details>

Done. Changed to let.
___
*[`packages/geoview-core/public/templates/demos/demo-important-layers.html` line 287 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0tBRZsCWNuxJRL6pFH:-O0xwzPJ3vdh6jnHW6zH:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48e1892ef7d46438e2495876f33ed21804100e2d/packages/geoview-core/public/templates/demos/demo-important-layers.html#L287)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white spaces
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/demos/demos.html` line 44 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0tBaiX2HOVtdNyMKox:-O0xxM2CEd1CVZiazIq3:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48e1892ef7d46438e2495876f33ed21804100e2d/packages/geoview-core/public/templates/demos/demos.html#L44)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should be: Important Layers Test Panel?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 75 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0tBwz2ByMogl3GUIMH:-O0y28mv3n8zVghLYGLh:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48e1892ef7d46438e2495876f33ed21804100e2d/packages/geoview-core/src/api/config/uuid-config-reader.ts#L75)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add a comment for this new section
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts` line 108 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0tCCp21goJKOOv7dDr:-O0y2A1FA22C_W6wCMgu:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48e1892ef7d46438e2495876f33ed21804100e2d/packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts#L108)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add a comment for this new section
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r2, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 80 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0yGelFBwtn5eD4ZDd6:-O0yGelFBwtn5eD4ZDd7:bss4dfg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edba4dc56a41616b2f4b64b1d093b4488c76fd09/packages/geoview-core/src/api/config/uuid-config-reader.ts#L80)):*
> ```XML
>           } else if (isFeature) {
>             // TODO:  Find the rcs specifications for esri feature layers. It seems not to have the same structure as esri dynamic
>             // TO.DO: For the moment, we inserted the following 6 lines as a work around to allow both structure to be supported.
> ```

For url like
https://services3.arcgis.com/4ctlIwTXTNrszdvn/arcgis/rest/services/CEMS\_PilotSites\_ECTM\_Regions\_Pilotes/FeatureServer and layerType esriFeature you know it is featureServeru because it is ini the url, if itis a mapServer esriFeature you will find mapServer in the url. You can implement this

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 80 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340#-O0yGelFBwtn5eD4ZDd6:-O0ydgKYAb4-KHIAV4PZ:b-ax6cz8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/edba4dc56a41616b2f4b64b1d093b4488c76fd09/packages/geoview-core/src/api/config/uuid-config-reader.ts#L80)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

For url like
https://services3.arcgis.com/4ctlIwTXTNrszdvn/arcgis/rest/services/CEMS\_PilotSites\_ECTM\_Regions\_Pilotes/FeatureServer and layerType esriFeature you know it is featureServeru because it is ini the url, if itis a mapServer esriFeature you will find mapServer in the url. You can implement this
</blockquote></details>

The code already performs this test 22 lines up. We'll assume that the esriFeature layers always return the information in the same format. The new code only supports this format, in which all information is contained in the URL

**Review by jolevesq — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2340)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
