### PR TITLE
refactor(store): Refactor clickMarker to use store

### LINKED ISSUE #1349: [REFACTOR] Click Marker show hide
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Click marker only use event

### Expected Behavior

Add store mechanism to manage the click marker show/hide. Store should also listen to the add event to create/manage state of the marker to be reuse in click-marker.tsx

Move ol animation/highlight to its own class in geo and clean marker. Use store to highlights feature instead of payload...

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1349

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Refactor click marker component
- Remove unused payload
- Refactor ui for useTheme import and component order
- Add doc on how to use store and component code order

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
- test many pages to see if they still works properly with basic controls (footer bar, nav bar, click marker, ...)

https://jolevesq.github.io/geoview

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471)

### CODE REVIEW

**Review by cphelefu — APPROVED** [review]
> Reviewed 54 of 54 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan, @amir-azma, @DamonU2, @kaminderpal, and @ychoquet)

**Review by kaminderpal — APPROVED** [review]

**Review by kaminderpal — APPROVED** [review]
> Reviewed 54 of 54 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan, @amir-azma, @DamonU2, and @ychoquet)

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 54 of 54 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471)* status: all files reviewed, 5 unresolved discussions (waiting on @amir-azma, @DamonU2, @jolevesq, and @ychoquet)

___
*[`docs/programming/best-practices.md` line 138 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471#-NieIInw7aG2aW0GH2hi:-NieIInw7aG2aW0GH2hj:b-cnpmyr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7e06cd6cd0215b7e15f4a9982a8755154853289f/docs/programming/best-practices.md#L138)):*
> ```Markdown
> 
> import View, { ViewOptions } from 'ol/View';
> ```
> ```

Agreed. And additionally, unless we have it already and I didn't see it, we should have some best-practice on the order of the functions in the class.
What works best for me atm is, after the aforementioned stuff:
- (The above order and useState, useStore calls)
- The core functions that are reusable *without dependencies*;
- The event handlers functions that may change the states and raise events/callbacks;
- The hooks section where we have the useEffect, useCallback methods grouped together (as the order that those are defined is actually important - best to group them)
- The rendering methods used for rendering the JSX
___
*[`packages/geoview-core/src/core/components/click-marker/click-marker.tsx` line 72 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471#-NieKWEq-N25oE9UJJGa:-NieKWEq-N25oE9UJJGb:b-qocohh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7e06cd6cd0215b7e15f4a9982a8755154853289f/packages/geoview-core/src/core/components/click-marker/click-marker.tsx#L72)):*
> ```XML
>    * Remove the marker icon
>    */
>   const removeIcon = useCallback(() => {
> ```

Not 100% certain, but I don't think a useCallback is necessary here?
___
*[`packages/geoview-core/src/ui/drawer/drawer.tsx` line 27 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471#-NieLTtw-AcWBChLYm-P:-NieLTtw-AcWBChLYm-Q:b-nbiaqd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7e06cd6cd0215b7e15f4a9982a8755154853289f/packages/geoview-core/src/ui/drawer/drawer.tsx#L27)):*
> ```XML
>  */
> export function Drawer(props: TypeDrawerProps): JSX.Element {
>   const { variant, status, className, style, children } = props;
> ```

Non-action comment.
Here, 'status' is the prop seen from outside and 'open' is the prop seen from inside. Suggestion to use the same prop name or is that intended to change the prop name?
___
*[`packages/geoview-core/src/ui/panel/panel.tsx` line 86 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471#-NieMVzLDbgY_FPagIkw:-NieMVzLDbgY_FPagIkx:b-s1msti) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7e06cd6cd0215b7e15f4a9982a8755154853289f/packages/geoview-core/src/ui/panel/panel.tsx#L86)):*
> ```XML
>    * function that causes rerender when changing panel content
>    */
>   const updateComponent = useCallback(() => {
> ```

Not 100% certain, but I don't think the useCallback() is necessary here?
___
*[`packages/geoview-core/src/ui/stepper/custom-stepper.tsx` line 87 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471#-NieNCGJ51ap0lmWKd82:-NieNCGJ51ap0lmWKd83:br54e92) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7e06cd6cd0215b7e15f4a9982a8755154853289f/packages/geoview-core/src/ui/stepper/custom-stepper.tsx#L87)):*
> ```XML
>   // internal state
>   const [activeStep, setActiveStep] = useState(0);
>   const [completed, setCompleted] = useState<any>({});
> ```

For this line and the next, should maybe type this something else than 'any', like 'boolean'?

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471)* status: all files reviewed, 6 unresolved discussions (waiting on @amir-azma, @jolevesq, and @ychoquet)

___
*[`docs/programming/using-store.md` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471#-NieHmiF7ALsQgNqT9Z9:-NieHmiF7ALsQgNqT9ZA:b-mp07b8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7e06cd6cd0215b7e15f4a9982a8755154853289f/docs/programming/using-store.md#L1)):*
> ```Markdown
> # Using Zusstand Store #
> ```

Zusstand > Zustand

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471)* status: 51 of 56 files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @kaminderpal, and @ychoquet)

___
*[`docs/programming/best-practices.md` line 138 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471#-NieIInw7aG2aW0GH2hi:-NieWk1e6Uqrg9WIhAaT:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7e06cd6cd0215b7e15f4a9982a8755154853289f/docs/programming/best-practices.md#L138)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Agreed. And additionally, unless we have it already and I didn't see it, we should have some best-practice on the order of the functions in the class.
What works best for me atm is, after the aforementioned stuff:
- (The above order and useState, useStore calls)
- The core functions that are reusable *without dependencies*;
- The event handlers functions that may change the states and raise events/callbacks;
- The hooks section where we have the useEffect, useCallback methods grouped together (as the other those are defined is actually important - best to group them)
- The rendering methods used for rendering the JSX
</blockquote></details>

Done.
___
*[`docs/programming/using-store.md` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471#-NieHmiF7ALsQgNqT9Z9:-NieWtBT9YLqRnnQF-H4:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7e06cd6cd0215b7e15f4a9982a8755154853289f/docs/programming/using-store.md#L1)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Zusstand > Zustand
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/click-marker/click-marker.tsx` line 72 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471#-NieKWEq-N25oE9UJJGa:-NieWvzO7sWjLfHebl7l:b-4n9hqe) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7e06cd6cd0215b7e15f4a9982a8755154853289f/packages/geoview-core/src/core/components/click-marker/click-marker.tsx#L72)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Not 100% certain, but I don't think a useCallback is necessary here?
</blockquote></details>

I think you are right and this function may be removed when we refactor highlight
___
*[`packages/geoview-core/src/ui/drawer/drawer.tsx` line 27 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471#-NieLTtw-AcWBChLYm-P:-NieYHCc5-M22rYvziuH:b4mqjvl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7e06cd6cd0215b7e15f4a9982a8755154853289f/packages/geoview-core/src/ui/drawer/drawer.tsx#L27)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Non-action comment.
Here, 'status' is the prop seen from outside and 'open' is the prop seen from inside. Suggestion to use the same prop name or is that intended to change the prop name?
</blockquote></details>

We should clean this later
___
*[`packages/geoview-core/src/ui/panel/panel.tsx` line 86 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471#-NieMVzLDbgY_FPagIkw:-NieYfqV9y8E0vKUS4vC:b3k7dzc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7e06cd6cd0215b7e15f4a9982a8755154853289f/packages/geoview-core/src/ui/panel/panel.tsx#L86)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Not 100% certain, but I don't think the useCallback() is necessary here?
</blockquote></details>

Will keep for ui cleanup later I think
___
*[`packages/geoview-core/src/ui/stepper/custom-stepper.tsx` line 87 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471#-NieNCGJ51ap0lmWKd82:-Nie_eD-4mKVGlmSbMGr:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7e06cd6cd0215b7e15f4a9982a8755154853289f/packages/geoview-core/src/ui/stepper/custom-stepper.tsx#L87)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

For this line and the next, should maybe type this something else than 'any', like 'boolean'?
</blockquote></details>

Done.

**Review by amir-azma — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1471)* status: all files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

**Pull request merged**
