### PR TITLE
797 - Implement zoom to layer in legend item

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
This PR covers the implementation of  zoom to layer capability of legend item.

Fixes # ([797](https://github.com/canadian-geospatial-platform/geoview/issues/797))

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
For disable state
image

Enabled state
image

# Checklist:

- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1006)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
For your geolocator zoom function (zoomToLocation), use the same as here: map(mapis)zoomToextent. Make it part of this PR.

The duration parameter should be on the zoomToExtent options function in the map.ts file. Please make the modification.

> Reviewed 2 of 8 files at r1, 4 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1006#-:-NV9i9yt2CtfPbzcCq6f:b-hpb141)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 488 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1006#-NV9dhGD-K28LBZzciR2:-NV9dhGD-K28LBZzciR3:bj5254v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1ea4d7639c3f96a2259d74443d9c48b51103019/packages/geoview-core/src/core/components/legend/legend-item.tsx#L488)):*
> ```XML
> 
>   useEffect(() => {
>     const bounds = api.map(mapId).layer?.geoviewLayers[layerId].getMetadataBounds() || undefined;
> ```

Function to use is: calculateBounds()

Like geoviewLayers['geojsonLYR1'].calculateBounds('geojsonLYR1/point-feature-group/points.json')

geoviewLayers[layerId].calculateBounds('layerpath to layer object')

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1006)* status: 6 of 10 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 488 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1006#-NV9dhGD-K28LBZzciR2:-NVAdKeV3Zs1dQsbpFOz:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1ea4d7639c3f96a2259d74443d9c48b51103019/packages/geoview-core/src/core/components/legend/legend-item.tsx#L488)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Function to use is: calculateBounds()

Like geoviewLayers['geojsonLYR1'].calculateBounds('geojsonLYR1/point-feature-group/points.json')

geoviewLayers[layerId].calculateBounds('layerpath to layer object')
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 6 files at r2, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1006)* status: 8 of 10 files reviewed, all discussions resolved

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1006)* status: 9 of 10 files reviewed, all discussions resolved

**Pull request merged**
