### PR TITLE
fix(schema): Merge appBar and appBarTabs into one property

### LINKED ISSUE #1713: [FEATURE] The config should use appBar/footer instead of appBar/appBarTabs/footerTabs
**Is there an existing issue for this?**
No

**Who request this Feature**
Johann

**User Story**
As a developer using the configurration, I would like the config to have appBar/footer properties instead of appBar/appBarTabs/footerTabs.

**Additional context**
See utils/config/config-validation.ts for a TODO.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1713

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # 1713

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Tested all pages with footer tabs and appBar setup
https://jolevesq.github.io/geoview/languages.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1748)

### CODE REVIEW

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 38 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1748)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 72 of 72 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1748)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 125 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1748#-NpfE-xm1x6dW6dlAJVd:-NpfE-xm1x6dW6dlAJVe:b-c0ozht) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7cf6975ca3b842e9b90937b35307c3fd570e3bf0/packages/geoview-core/src/ui/tabs/tabs.tsx#L125)):*
> ```XML
>     logger.logTraceUseEffect('TABS - Mouse Clicked On Map');
>     //  open details tab when clicked on layer on
>     if (activeFooterBarTabId === 'details') {
> ```

this was already there in the code?
I don't really like that we have 'GeoView related stuff' inside a generic UI component like that.. also, does changing the selected tab like bypass the selectedTab event?

**Review by jolevesq — COMMENTED** [review]
> Reviewed 16 of 38 files at r1, 72 of 72 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1748)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 125 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1748#-NpfE-xm1x6dW6dlAJVd:-NpfFqCQCufo3lwgJU1R:bjzfimk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7cf6975ca3b842e9b90937b35307c3fd570e3bf0/packages/geoview-core/src/ui/tabs/tabs.tsx#L125)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

this was already there in the code?
I don't really like that we have 'GeoView related stuff' inside a generic UI component like that.. also, does changing the selected tab like bypass the selectedTab event?
</blockquote></details>

You are right, this should be removed

**Review by Alex-NRCan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1748)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
