### PR TITLE
feat(add-geometries) Create functions to add geometries

### LINKED ISSUE #24: Create function to add vector to a map
We need the ability to add 
- [x] Polylines
- [x] Points (circle)
- [x] Polygons

Those geometries may be added in different projections ([projection issues](https://github.com/Canadian-Geospatial-Platform/GeoView/issues/25))
Those geometries needs to be added as [layer group](https://leafletjs.com/reference-1.7.1.html#layergroup) or [feature group](https://leafletjs.com/reference-1.7.1.html#featuregroup)

The functions needs to be part of the api so we can create from inside the viewer and also from the outside.

On the sample page, create a button with a text box where we can add geometry coordinates to add vector on the map

### PR DESCRIPTION
**Pull request by yass0016**
Closes #24

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55)* status: 0 of 9 files reviewed, 9 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[public/index.html, line 47 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZSU6tEFuOLmYWXuoR:-MSZSU6tEFuOLmYWXuoS:b-nydlw) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/public/index.html#L47)):*
> ```HTML
>             <h3>The Atlas of Canada - Clean Energy Resources and Projects (CERP)</h3>
>             <div class="toolbar">
>                 <button class="add-polyline-btn">Add Polyline</button>
> ```

If I add more then 1 polyline, I can't remove it with remove polylines. I have to use the remove geometries. Do we disable add polyline when click and re enable after delete polyline and delete geometries?
___
*[public/index.html, line 81 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZSrh7CPSJ_zn0wots:-MSZSrh7CPSJ_zn0wott:b-mc4oxu) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/public/index.html#L81)):*
> ```HTML
>             <div class="toolbar">
>                 <button class="add-polyline-btn">Add Polyline</button>
>                 <button class="add-polygon-btn">Add Polygon</button>
> ```


Add polygon and circle does nothing on LCC map. You can just remove the button.
___
*[src/common/vectors/circle.ts, line 37 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZTtIt183xbnu5nGZk:-MSZTtIt183xbnu5nGZl:bgt9fmm) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/circle.ts#L37)):*
> ```XML
>         const circle = L.circle([latitude, longitude], {
>             ...options,
>             radius: radius * 1000,
> ```

It is because the radius is calculated in meters. Can you update the comment to say so. {number} radius the radius of the circle (in kilometer). 

So when we multiply by 1000, we will have it in kilometer
___
*[src/common/vectors/polyline.ts, line 19 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZV85oDpy8MIVdnvP1:-MSZV85oDpy8MIVdnvP2:b33zkdw) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/polyline.ts#L19)):*
> ```XML
>      */
>     constructor() {
>         this.layers = new L.FeatureGroup();
> ```

I see each geometry type created his own FeatureGroup. Layer service like the one on ArcGIS server are geometry restricted (one geometry type by layer). I don't think we have this restriction in LeafLet. geoJSON is the same, we can mix the geometries inside I think. I would prefer the feature group is created a t the vector level and the add is applied to a created featureGroup. We should have a default feature group so if none is created/provided it goes to the default one. 
___
*[src/common/vectors/polyline.ts, line 32 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZWY7b2602OE7dfzhw:-MSZWY7b2602OE7dfzhx:bu4rqn1) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/polyline.ts#L32)):*
> ```XML
>      * @returns a geometry with the id and the created polyline layer
>      */
>     createPolyline = (
> ```

I think we should only have one function who takes an array of points to create the polyline. Is there a reason why you have both?
___
*[src/common/vectors/vector.ts, line 5 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZWllNDIaUpLFwazWo:-MSZWllNDIaUpLFwazWp:b-qxum3g) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/vector.ts#L5)):*
> ```XML
> 
> import { Polygon } from './polygon';
> ```

Remove blank line in the import, part of the same group.
___
*[src/common/vectors/vector.ts, line 80 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZX1hs8mxIMvFo9a3M:-MSZX1hs8mxIMvFo9a3N:b-ez3l3n) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/vector.ts#L80)):*
> ```XML
> 
>     /**
>      * Generate a unique id to use in a geometry if an id was not specified
> ```

Add return type to function jsdoc?
___
*[src/common/vectors/vector.ts, line 148 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZXGNI8PLO6KRIfQHq:-MSZXGNI8PLO6KRIfQHr:b-l6c01y) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/vector.ts#L148)):*
> ```XML
>      * @param {string} id an optional id to be used to manage this layer
>      *
>      * @returns a geometry containing the an id and the created layer
> ```

Is there a type the an id?
___
*[src/common/vectors/vector.ts, line 179 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZXRmf8Ojll8DQ_5PR:-MSZXRmf8Ojll8DQ_5PS:besnq6s) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/vector.ts#L179)):*
> ```XML
>      */
>     addCircle = (latitude: number, longitude: number, radius: number, options: Record<string, unknown>, id?: string): GeometryType => {
>         const lId = id !== null && id !== undefined && id.length > 0 ? id : this.generateGeometryId();
> ```

This piece is repeated in many function. Should it be in is own function to not duplicate the test? Maybe the id variable is pass to generateGeometryId

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55)* status: 0 of 9 files reviewed, 9 unresolved discussions (waiting on @jolevesq and @melzeiny1980)

___
*[public/index.html, line 47 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZSU6tEFuOLmYWXuoR:-MSZYMjQ8vvqHJfD1Hud:b-jnrnoc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/public/index.html#L47)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If I add more then 1 polyline, I can't remove it with remove polylines. I have to use the remove geometries. Do we disable add polyline when click and re enable after delete polyline and delete geometries?
</blockquote></details>

No, this is actually a sample of adding a polygon then removing it using the ID
___
*[public/index.html, line 81 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZSrh7CPSJ_zn0wots:-MSZYVly8sIiNgn4JhAD:b25k7y3) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/public/index.html#L81)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add polygon and circle does nothing on LCC map. You can just remove the button.
</blockquote></details>

Done. updated in the second revision
___
*[src/common/vectors/circle.ts, line 37 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZTtIt183xbnu5nGZk:-MSZYfynDYfJbJtrJIUJ:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/circle.ts#L37)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It is because the radius is calculated in meters. Can you update the comment to say so. {number} radius the radius of the circle (in kilometer). 

So when we multiply by 1000, we will have it in kilometer
</blockquote></details>

Done.
___
*[src/common/vectors/polyline.ts, line 19 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZV85oDpy8MIVdnvP1:-MSZZY70BVC3zuNd9j-t:b-xh21wa) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/polyline.ts#L19)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I see each geometry type created his own FeatureGroup. Layer service like the one on ArcGIS server are geometry restricted (one geometry type by layer). I don't think we have this restriction in LeafLet. geoJSON is the same, we can mix the geometries inside I think. I would prefer the feature group is created a t the vector level and the add is applied to a created featureGroup. We should have a default feature group so if none is created/provided it goes to the default one. 
</blockquote></details>

I wanted to actually have them managed by their own groups like later on we can remove all polygons but leave the other type
___
*[src/common/vectors/polyline.ts, line 32 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZWY7b2602OE7dfzhw:-MSZZAFi6l8BiPZ-ZLPk:b-d990qs) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/polyline.ts#L32)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think we should only have one function who takes an array of points to create the polyline. Is there a reason why you have both?
</blockquote></details>

giving the user more options, would you prefer to have it only the array way?
___
*[src/common/vectors/vector.ts, line 5 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZWllNDIaUpLFwazWo:-MSZZQI6BNUWSjTRkTNW:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/vector.ts#L5)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove blank line in the import, part of the same group.
</blockquote></details>

Done.
___
*[src/common/vectors/vector.ts, line 80 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZX1hs8mxIMvFo9a3M:-MSZZt-E3IYfkwCLO_SR:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/vector.ts#L80)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add return type to function jsdoc?
</blockquote></details>

Done.
___
*[src/common/vectors/vector.ts, line 148 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZXGNI8PLO6KRIfQHq:-MSZ_Ljv6H8LqvaJMTSX:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/vector.ts#L148)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is there a type the an id?
</blockquote></details>

Done.
___
*[src/common/vectors/vector.ts, line 179 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZXRmf8Ojll8DQ_5PR:-MSZa5-O3GibbpbcZXsO:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/vector.ts#L179)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This piece is repeated in many function. Should it be in is own function to not duplicate the test? Maybe the id variable is pass to generateGeometryId 
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[public/index.html, line 47 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZSU6tEFuOLmYWXuoR:-MSZacFh8qx7H_mHsgJJ:b-dowtq4) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/public/index.html#L47)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

No, this is actually a sample of adding a polygon then removing it using the ID
</blockquote></details>

Yep but it is for the polyline, not the polygon. Just tested again. Because we can more than one polyline, the delete by id doesn't work if we click more than once. Not a big deal but user may just think it is broken.
___
*[public/index.html, line 81 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZSrh7CPSJ_zn0wots:-MSZbi965IrvWeRac40T:b-i4kj4c) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/public/index.html#L81)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Done. updated in the second revision
</blockquote></details>

Delete group does not delete polyline because it is not part of the same group. Do we need to group the add poly, add circle and remove group together so we do not think it will also remove polyline? This is not top priority because for the moment samples are only for us. I have an issue to create bunch of meaningful issue based on use case.
___
*[src/common/vectors/circle.ts, line 37 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZTtIt183xbnu5nGZk:-MSZcEKQBVZfrESeP4aP:b-o8rao5) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/circle.ts#L37)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can add this to JSDOC on radius line (radius measure in kilometers). So when we generate the doc, user will see it right away.
___
*[src/common/vectors/polyline.ts, line 19 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZV85oDpy8MIVdnvP1:-MSZcYsJ0gZpc-2r6GnD:b-fpuqc5) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/polyline.ts#L19)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

I wanted to actually have them managed by their own groups like later on we can remove all polygons but leave the other type
</blockquote></details>

Yeah but i think we should be more open. If I want a group with only polygon in it I still can but if a need a group who mix line and polygon I also can. Non gis user always have hard time to understand why we can't mix geometry. This way we can create layer not based on group of geometry but meaning (e.g water palnt can be a point for small one, a line for medium one and a polygon for very huge one)
___
*[src/common/vectors/polyline.ts, line 32 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZWY7b2602OE7dfzhw:-MSZd6mO9b28dxaKYVtm:b-cl6i8x) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/polyline.ts#L32)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

giving the user more options, would you prefer to have it only the array way?
</blockquote></details>

I think so, it will be consistent with the other type.

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @jolevesq and @melzeiny1980)

___
*[public/index.html, line 47 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZSU6tEFuOLmYWXuoR:-MSZe3fq37jY1jmRo1-G:bezdzb9) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/public/index.html#L47)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Yep but it is for the polyline, not the polygon. Just tested again. Because we can more than one polyline, the delete by id doesn't work if we click more than once. Not a big deal but user may just think it is broken.
</blockquote></details>

It's true, whats happening is its creating a second polyline on top of the created one with same coordinates, and the delete will delete the last created one.
___
*[public/index.html, line 81 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZSrh7CPSJ_zn0wots:-MSZeo478BjaqjXxKUBE:bwr5u1y) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/public/index.html#L81)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Delete group does not delete polyline because it is not part of the same group. Do we need to group the add poly, add circle and remove group together so we do not think it will also remove polyline? This is not top priority because for the moment samples are only for us. I have an issue to create bunch of meaningful issue based on use case.
</blockquote></details>

Oh I forgot to add it to the same group, now its added
___
*[src/common/vectors/polyline.ts, line 19 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZV85oDpy8MIVdnvP1:-MSZiSq03tbFBJqXOwzD:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/polyline.ts#L19)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Yeah but i think we should be more open. If I want a group with only polygon in it I still can but if a need a group who mix line and polygon I also can. Non gis user always have hard time to understand why we can't mix geometry. This way we can create layer not based on group of geometry but meaning (e.g water palnt can be a point for small one, a line for medium one and a polygon for very huge one)
</blockquote></details>

Done.
___
*[src/common/vectors/polyline.ts, line 32 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSZWY7b2602OE7dfzhw:-MSZgUzj2bV6FU7Z0WFE:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/89e5b4cd94f13aa64e5eee8974cbc260879238ef/src/common/vectors/polyline.ts#L32)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think so, it will be consistent with the other type.
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 4 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55)* status: 5 of 12 files reviewed, 5 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[src/common/map-viewer.ts, line 33 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSby4C_4ZpuDZKKSR1F:-MSby4C_4ZpuDZKKSR1G:b-yhiy9n) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e1519b8d31c18f949ea3ea5436e40863ab502666/src/common/map-viewer.ts#L33)):*
> ```XML
>     constructor(mapInstance: MapInterface) {
>         this.mapInstance = mapInstance;
>         this.vector = new Vector(mapInstance.map);
> ```

Do we only manage vector here? Should we manage the layer at the same place?
___
*[src/common/vectors/vector.ts, line 78 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSc-k2-0TGv4tAY13aw:-MSc-k2036u9b7RKHH_T:b-membbw) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e1519b8d31c18f949ea3ea5436e40863ab502666/src/common/vectors/vector.ts#L78)):*
> ```XML
> 
>         // add feature group to the map
>         this.map.addLayer(this.featurGroup);
> ```

Do we have the capacity to add other layer or it is just one layer with multiple group? It may be good for now but we will need to be able to add many different layer. Those layer may need to be added to the legend later and user will be able to turn on and off the visibility. We can do it by group inside the layer as well but we will have to think about the best way.
___
*[src/common/vectors/vector.ts, line 157 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSc09vl6JfCpGzJRUdn:-MSc09vmD_moAF237LWT:ba5zurd) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e1519b8d31c18f949ea3ea5436e40863ab502666/src/common/vectors/vector.ts#L157)):*
> ```XML
>      * @returns a geometry containing the id and the created layer
>      */
>     addCircle = (latitude: number, longitude: number, radius: number, options: Record<string, unknown>, id?: string): GeometryType => {
> ```

I forgot one type. Can you add the circleMarker type. Does it goes inside circle but when you put no radius it becomes a marker?

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55)* status: 2 of 12 files reviewed, 5 unresolved discussions (waiting on @jolevesq and @melzeiny1980)

___
*[src/common/map-viewer.ts, line 33 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSby4C_4ZpuDZKKSR1F:-MScELIK0S3SrY1Th-gG:b-t3r5hv) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e1519b8d31c18f949ea3ea5436e40863ab502666/src/common/map-viewer.ts#L33)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we only manage vector here? Should we manage the layer at the same place?
</blockquote></details>

we will of course, it wasn't part of this issue this is why I didn't add it. a lot of code will be changed
___
*[src/common/vectors/vector.ts, line 78 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSc-k2-0TGv4tAY13aw:-MScEaWz1NmSSAMzpA0Z:b7im7eb) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e1519b8d31c18f949ea3ea5436e40863ab502666/src/common/vectors/vector.ts#L78)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we have the capacity to add other layer or it is just one layer with multiple group? It may be good for now but we will need to be able to add many different layer. Those layer may need to be added to the legend later and user will be able to turn on and off the visibility. We can do it by group inside the layer as well but we will have to think about the best way.
</blockquote></details>

Yes, before I was adding a layer per feature group per vector type so it's no problem
___
*[src/common/vectors/vector.ts, line 157 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSc09vl6JfCpGzJRUdn:-MScEsJsBi6leXSsCaKf:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e1519b8d31c18f949ea3ea5436e40863ab502666/src/common/vectors/vector.ts#L157)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I forgot one type. Can you add the circleMarker type. Does it goes inside circle but when you put no radius it becomes a marker?
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
:lgtm:

> Reviewed 2 of 8 files at r1, 4 of 9 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-:-MScGU1zAqTn3THoxvfT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @melzeiny1980 and @yass0016)

___
*[src/common/map-viewer.ts, line 33 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55#-MSby4C_4ZpuDZKKSR1F:-MScEvhe6PXunBLA3PdS:bvtw58m) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e1519b8d31c18f949ea3ea5436e40863ab502666/src/common/map-viewer.ts#L33)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

we will of course, it wasn't part of this issue this is why I didn't add it. a lot of code will be changed
</blockquote></details>

Good, can you create an issue or add this to an existing issue where it may fit so we do not lose track?

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @melzeiny1980)

**Pull request merged**
