### PR TITLE
bug(attribution-fix) Fix attribution position

### LINKED ISSUE #31: Attribution is getting too long
Attribution at the bottom of the map is getting too long when we add layers who add their attribution inside this room. The result is the coordinates and scale section is written over. Possible solution:

* Put a max width to the div so there is no overlap
* Remove attribution added by layers

### PR DESCRIPTION
**Pull request by yass0016**
Closes #31

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/42)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/42)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @yass0016)

___
*[src/components/appbar/app-bar.tsx, line 57 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/42#-MS-NjYN2dlDiiQbe9rS:-MS-NjYN2dlDiiQbe9rT:b-mmrx9i) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/24e238836d36864917374cf4310ecf0f79ee664e/src/components/appbar/app-bar.tsx#L57)):*
> ```XML
>     },
>     githubSection: {
>         // paddingBottom: theme.spacing(13),
> ```

We do not need this padding anymore. You can remove the whole section I think.
___
*[src/components/map/map.tsx, line 23 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/42#-MS-NsBr-Om5T1bewtPU:-MS-NsBr-Om5T1bewtPV:bo3u34y) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/24e238836d36864917374cf4310ecf0f79ee664e/src/components/map/map.tsx#L23)):*
> ```XML
> import { MousePosition } from '../mapctrl/mouse-position';
> import { OverviewMap } from '../mapctrl/overview-map';
> import Attribution from '../mapctrl/attribution';
> ```

We have { } around other import. Why do export default Attribution instead of the Attribution function?
___
*[src/components/mapctrl/attribution.tsx, line 26 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/42#-MS-OrNe-ngWo0s8m0gM:-MS-OrNe-ngWo0s8m0gN:b-ww8zom) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/24e238836d36864917374cf4310ecf0f79ee664e/src/components/mapctrl/attribution.tsx#L26)):*
> ```XML
> };
> 
> function Attribution(props: AttributionProps): JSX.Element {
> ```

Can you add JSDOC
___
*[src/components/mapctrl/attribution.tsx, line 33 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/42#-MS-P9oyCCcxKcHGXqmP:-MS-P9oyCCcxKcHGXqmQ:bd72kz3) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/24e238836d36864917374cf4310ecf0f79ee664e/src/components/mapctrl/attribution.tsx#L33)):*
> ```XML
>     const divRef = useRef(null);
> 
>     useEffect(() => {
> ```

I think we do not have to disable the click under this div because it is only to show text. For the moment, scale and mouse are not disable propagation. Should we have all them the same? Even more, should we have a bar all along the bottom that may hold mote info in the futur?

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/42)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @jolevesq)

___
*[src/components/appbar/app-bar.tsx, line 57 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/42#-MS-NjYN2dlDiiQbe9rS:-MS-SYbWBymbR8Yhyztj:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/24e238836d36864917374cf4310ecf0f79ee664e/src/components/appbar/app-bar.tsx#L57)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We do not need this padding anymore. You can remove the whole section I think.
</blockquote></details>

Done.
___
*[src/components/map/map.tsx, line 23 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/42#-MS-NsBr-Om5T1bewtPU:-MS-S_RWC5KzGSI3lTwt:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/24e238836d36864917374cf4310ecf0f79ee664e/src/components/map/map.tsx#L23)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We have { } around other import. Why do export default Attribution instead of the Attribution function?
</blockquote></details>

Done.
___
*[src/components/mapctrl/attribution.tsx, line 26 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/42#-MS-OrNe-ngWo0s8m0gM:-MS-Sait4NPN_T-MzXPz:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/24e238836d36864917374cf4310ecf0f79ee664e/src/components/mapctrl/attribution.tsx#L26)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add JSDOC
</blockquote></details>

Done.
___
*[src/components/mapctrl/attribution.tsx, line 33 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/42#-MS-P9oyCCcxKcHGXqmP:-MS-SbY765t-KCWY-XGW:b-tccnsg) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/24e238836d36864917374cf4310ecf0f79ee664e/src/components/mapctrl/attribution.tsx#L33)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think we do not have to disable the click under this div because it is only to show text. For the moment, scale and mouse are not disable propagation. Should we have all them the same? Even more, should we have a bar all along the bottom that may hold mote info in the futur?
</blockquote></details>

Done. Scale and drag doesn't need to be disabled, I just thought maybe someone wants to copy the attribution text, maybe we can add that bar later on if we need to add more info.

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/42)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @jolevesq)

___
*[src/components/mapctrl/attribution.tsx, line 33 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/42#-MS-P9oyCCcxKcHGXqmP:-MS-TjDK1kAwDlEPQttS:b6q3zjy) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/24e238836d36864917374cf4310ecf0f79ee664e/src/components/mapctrl/attribution.tsx#L33)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Done. Scale and drag doesn't need to be disabled, I just thought maybe someone wants to copy the attribution text, maybe we can add that bar later on if we need to add more info.
</blockquote></details>

Just checked, we can still copy the attribution if we double click it so it's fine if we don't disable propagation

**Review by jolevesq — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/42#-:-MS-Vo3xAiB1AEDjsSxf:bg7igkv)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/42)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
