### PR TITLE
1732 highlight animation options

### LINKED ISSUE #1732: [FEATURE] Turn on/off details animation
**Is there an existing issue for this?**
Please search to see if an issue already exists for this feature.
no

**Who request this Feature**
Individual, team, project, organization...
Hydro team

**User Story**
A concise description of what you expected to happen (one paragraph).
As a map creator, I would like to turn off details animation

**Implementation UI**
If needed, what user interface do you suggest, feel free to add mockups.
We should add an api function to turn on and off the details click animation
We should add a setting to configuration file to set it on and off automatically

**Additional context**

### PR DESCRIPTION
**Pull request by DamonU2**
# Description

Highlight colour can now be set in config or with an api call. Vector tiles style is applied properly. Visibility with group layers fixed. Feature highlighting removed form data table.

Fixes #1732 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

cgpv.api.maps.mapWM1.layer.featureHighlight.changeHighlightColor('black');

https://damonu2.github.io/geoview/raw-feature-info.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1912)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 16 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1912)* status: 16 of 18 files reviewed, 2 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 151 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1912#-NsmoWpR1ZogvIEBdbNq:-NsmoWpR1ZogvIEBdbNr:b-z9pzqe) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d83cf1525e24d49a4d55e0df5ef01728b58c01ca/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L151)):*
> ```XML
> 
>     const unsubMapHighlightColor = store.subscribe(
>       (state) => state.mapState.highlightColor,
> ```

Why do you have a subscribe. It can only be a function setHiglightColor on mapviewer.ts file that set the color like we did for setTheme or setProjection

The validation for new color can be set at the map-viewer.ts function.
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 139 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1912#-NsmtGiJDc1BrzzDR4f7:-NsmtGiKCdfpiIxrRqG8:b-z36mea) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d83cf1525e24d49a4d55e0df5ef01728b58c01ca/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L139)):*
> ```XML
> 
>               if (item.isVisible === 'yes' && MapEventProcessor.getMapVisibilityFromOrderedLayerInfo(get().mapId, layerPath)) {
>                 MapEventProcessor.setOrToggleMapVisibility(get().mapId, layerPath, true);
> ```

his seems to introduce a bug when all classification are turn off, they are still visible on the map

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1912)* status: 8 of 18 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 151 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1912#-NsmoWpR1ZogvIEBdbNq:-Nsn7Dw2DYlEBD-K8hUL:ba3dfob) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d83cf1525e24d49a4d55e0df5ef01728b58c01ca/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L151)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why do you have a subscribe. It can only be a function setHiglightColor on mapviewer.ts file that set the color like we did for setTheme or setProjection

The validation for new color can be set at the map-viewer.ts function.
</blockquote></details>

Removed
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 139 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1912#-NsmtGiJDc1BrzzDR4f7:-Nsn7Kzb7sYGrMUkUKN9:bxc6bd1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d83cf1525e24d49a4d55e0df5ef01728b58c01ca/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L139)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

his seems to introduce a bug when all classification are turn off, they are still visible on the map
</blockquote></details>

Was this the water quality issue?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 18 files at r1, 5 of 9 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1912)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @DamonU2)

___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 139 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1912#-NsmtGiJDc1BrzzDR4f7:-NsoBgX75En4Fm321Kre:b10zhd1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d83cf1525e24d49a4d55e0df5ef01728b58c01ca/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L139)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Was this the water quality issue?
</blockquote></details>

Yes... my bad
___
*[`packages/geoview-core/src/geo/utils/feature-highlight.ts` line 9 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1912#-NsoCRnY27nPYpLxQV3K:-NsoCRnY27nPYpLxQV3L:b-8q4rys) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d3810f2f6f4b2b73fc63d92fd515e73269cb0db1/packages/geoview-core/src/geo/utils/feature-highlight.ts#L9)):*
> ```XML
> import { getUid } from 'ol';
> import { fromExtent } from 'ol/geom/Polygon';
> import { Coordinate, TypeFeatureInfoEntry, TypeHighlightColors, api } from '@/app';
> ```

import from the right place from '@/geo/map/map-schema-types'

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1912)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/utils/feature-highlight.ts` line 9 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1912#-NsoCRnY27nPYpLxQV3K:-NsoDXTf8cuh1-30EkwJ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d3810f2f6f4b2b73fc63d92fd515e73269cb0db1/packages/geoview-core/src/geo/utils/feature-highlight.ts#L9)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

import from the right place from '@/geo/map/map-schema-types'
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1912)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
