### PR TITLE
refactor(utilities): Move utilities to clean them

### LINKED ISSUE #1964: {REFACTOR} Clean Utilities
There is 2 utilities section

api.utilities

api.maps[mapId].utilities

There is stand alone utilities that does not need a map to work and there is some that needs a map. For the moment they are all over the place... we need to move them in their proper place.

### PR DESCRIPTION
**Pull request by jolevesq**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Move utilities who needs map id to map viewer, notifications
Refactor utilities to remove map id and use needed parameters
Clean/encapsulated class/functions for cleaner access
Change Geo/utilities class to functions module

Fixes #1964

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Hosted April, 2 - 9:20: https://jolevesq.github.io/geoview

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977)

### CODE REVIEW

**Review by DamonU2 — APPROVED** [review]
> Reviewed 62 of 62 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan and @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 22 of 62 files at r1, 39 of 53 files at r2, 19 of 19 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan and @ychoquet)

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 22 of 62 files at r1, 53 of 53 files at r2, 19 of 19 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977)* status: all files reviewed, 11 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/public/templates/events.html` line 100 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuTyutBANVAVfK89XyO:-NuTyutBANVAVfK89XyP:byny9tu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/34651d3b9d5f66904396d75da0894dbc83f681ec/packages/geoview-core/public/templates/events.html#L100)):*
> ```HTML
> 
>           document.getElementById('success-notif-but').addEventListener('click', function (e) {
>             cgpv.api.maps['EVNT1'].addNotificationSuccess('this is a success notification title');
> ```

Cool stuff
___
*[`packages/geoview-core/src/api/api.ts` line 23 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuU6mxwETnxhQbWexeZ:-NuU6mxwETnxhQbWexe_:baiog26) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d167e88926e256780b526eef3ba7162f60342a4d/packages/geoview-core/src/api/api.ts#L23)):*
> ```XML
>  * @class API
>  */
> export class API {
> ```

Nice general cleanup
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 611 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuTzODc3edYWCMxh9PV:-NuTzODdEee0nKbafM0G:bhjscj7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/34651d3b9d5f66904396d75da0894dbc83f681ec/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L611)):*
> ```XML
>   // TODO: Delete this temporary functions when we pass the mapviewer/utilities object to all ts files
>   // TD.CONT we should have a utilities object attacht to all elements... for the moments, these functions
>   // TD.CONT are attached to map-viewer... they are utilities, theur shoudl be in their own class linked to map id
> ```

some typos like moment(no s) theur shoudl
___
*[`packages/geoview-core/src/core/containers/focus-trap.tsx` line 61 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuU89341p3CRdE4PsKg:-NuU89341p3CRdE4PsKh:b-jywvnf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d167e88926e256780b526eef3ba7162f60342a4d/packages/geoview-core/src/core/containers/focus-trap.tsx#L61)):*
> ```XML
>   if (mapElementRef.current !== undefined) mapHTMLElementRef.current = mapElementRef.current.getTargetElement();
> 
>   /**
> ```

Nice, I have similar work on preventing a page scroll when wheel scrolling over the map in my PR.
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts` line 223 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuU7tVe6DUXivQ_NFmq:-NuU7tVe6DUXivQ_NFmr:b-84xoby) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d167e88926e256780b526eef3ba7162f60342a4d/packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts#L223)):*
> ```XML
> 
>         // on map center coord change, update north arrow parameters
>         // TODO: this will be refactor by the work done by Alex
> ```

Indeed, conflicts inbound.
___
*[`packages/geoview-core/src/core/utils/notifications.ts` line 21 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuU-Fz03TQ_5sNbhrTZ:-NuU-Fz03TQ_5sNbhrT_:b-paa8c) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d167e88926e256780b526eef3ba7162f60342a4d/packages/geoview-core/src/core/utils/notifications.ts#L21)):*
> ```XML
>    * @param {string} message optional, the message string
>    */
>   // eslint-disable-next-line no-underscore-dangle, default-param-last
> ```

Maybe the `// eslint disable` is not necessary anymore, here?
Also, if message is optional, maybe explicit it with a message? or message: string | undefined.
If it's not optional, edit the comment and swap the parameters positions?
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 64 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuU-zAU9mkGeqZwsUN-:-NuU-zAU9mkGeqZwsUN0:buh6gh8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/34651d3b9d5f66904396d75da0894dbc83f681ec/packages/geoview-core/src/core/utils/utilities.ts#L64)):*
> ```XML
>  *
>  * @param {string[]} params array of parameters to replace, i.e. ['short']
>  * @param {string} message original message, i.e. "My strins is __param__"
> ```

strins --> string ? (3x)
___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 376 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuU0a_421DSXjCsoIO7:-NuU0a_421DSXjCsoIO8:bnnlif8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/34651d3b9d5f66904396d75da0894dbc83f681ec/packages/geoview-core/src/core/utils/config/config-validation.ts#L376)):*
> ```XML
>     }
> 
>     setTimeout(() => {
> ```

Can we add an explanation for the `setTimeout` of 2 seconds? (3x)
And possibly add TODOs to refactor them later?
___
*[`packages/geoview-core/src/core/utils/config/reader/url-config-reader.ts` line 150 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuU4JlHApJkIA-nchCF:-NuU4JlHApJkIA-nchCG:bd7nc3r) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d167e88926e256780b526eef3ba7162f60342a4d/packages/geoview-core/src/core/utils/config/reader/url-config-reader.ts#L150)):*
> ```XML
>           );
>           // TODO: config should not push message to map... only to console and as return value.. map will be responsible to throw notification
>           api.maps[mapId].notifications.showError(message);
> ```

Writing it here, but applies everywhere:
`showError` could use a string shortcut such as 'validation.layer.loadfailed' instead of receiving a full message?
That way, we're 'guaranteeing' that we do have translated messages for any/all errors that end up being shown to the user?
Internally, it could still show the shortcut if no translation was found, but we could logDebug it when not found so we can catch all the missing translated messages?
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 251 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuU0v7bCTOkpoozrmeC:-NuU0v7c9jKv-4TEygFA:bwry73f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/34651d3b9d5f66904396d75da0894dbc83f681ec/packages/geoview-core/src/geo/layer/layer.ts#L251)):*
> ```XML
>     const message = replaceParams(
>       [mapConfigLayerEntry.geoviewLayerId, this.mapId],
>       api.utilities.core.getLocalizedMessage('validation.layer.usedtwice', AppEventProcessor.getDisplayLanguage(this.mapId))
> ```

One might think this following comment is counter productive to the changes in this PR, but hear me out :)

I see this sort of call repeated often (and it's a bit lengthy). Maybe refactor it a bit further by adding a function in AppEventProcessor that goes like this:
AppEventProcessor.getMessage(mapId, 'validation.layer.usedTwice'); // mapId first, because that's the typical pattern over there.

Implemented like:
`return api.utilities.core.getLocalizedMessage(code_string, this.getDisplayLanguage(mapId))`

The calls would be lot more straightforward for the core/ui. It's also not going back to what it was, because it's essentially moving the code from utilities to AppEventProcessor (which makes sense to have a mapId there). It does couple the api.utilities with the AppEventProcessor, but that should be fine, seeing utilities is meant to be reused. It's better than having the api 'under' the utilities like it was originally in this PR :thumbsup: 

This pattern would also fit really nicely with another comment in this review about the notification.showError/Warning/Info()
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 173 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuU5w2U8bXXfPhxxckb:-NuU5w2U8bXXfPhxxckc:b-zh28li) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d167e88926e256780b526eef3ba7162f60342a4d/packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts#L173)):*
> ```XML
>       MapEventProcessor.getMapState(this.mapId).currentProjection !== this.metadata.tileInfo.spatialReference.wkid
>     ) {
>       // TODO: find a more centralized way to trap error and display message
> ```

Agreed with the comments about having this class (and any 'framework-class') raise an error instead of communicating with the notifications directly.
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 182 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuU6GMJDpNobfJZxlbG:-NuU6GMJDpNobfJZxlbH:bb70w76) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d167e88926e256780b526eef3ba7162f60342a4d/packages/geoview-core/src/geo/map/map-viewer.ts#L182)):*
> ```XML
>     this.navBarApi = new NavbarApi(this.mapId);
>     this.footerBarApi = new FooterBarApi(this.mapId);
>     this.notifications = new Notifications(this.mapId);
> ```

Nice

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977)* status: 65 of 80 files reviewed, 11 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 611 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuTzODc3edYWCMxh9PV:-NuUEqvO5HS2EgelN-Tq:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/34651d3b9d5f66904396d75da0894dbc83f681ec/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L611)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

some typos like moment(no s) theur shoudl
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/notifications.ts` line 21 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuU-Fz03TQ_5sNbhrTZ:-NuUBl9iCuiIiYQnxODQ:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d167e88926e256780b526eef3ba7162f60342a4d/packages/geoview-core/src/core/utils/notifications.ts#L21)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Maybe the `// eslint disable` is not necessary anymore, here?
Also, if message is optional, maybe explicit it with a message? or message: string | undefined.
If it's not optional, edit the comment and swap the parameters positions?
</blockquote></details>

Done
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 64 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuU-zAU9mkGeqZwsUN-:-NuUByH122HW3QYzgSiI:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/34651d3b9d5f66904396d75da0894dbc83f681ec/packages/geoview-core/src/core/utils/utilities.ts#L64)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

strins --> string ? (3x)
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 376 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuU0a_421DSXjCsoIO7:-NuUCWnn8FYrj-bsdF-U:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/34651d3b9d5f66904396d75da0894dbc83f681ec/packages/geoview-core/src/core/utils/config/config-validation.ts#L376)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Can we add an explanation for the `setTimeout` of 2 seconds? (3x)
And possibly add TODOs to refactor them later?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/config/reader/url-config-reader.ts` line 150 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuU4JlHApJkIA-nchCF:-NuUD3dA5_9N9NDtjGs2:b-njiud8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d167e88926e256780b526eef3ba7162f60342a4d/packages/geoview-core/src/core/utils/config/reader/url-config-reader.ts#L150)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Writing it here, but applies everywhere:
`showError` could use a string shortcut such as 'validation.layer.loadfailed' instead of receiving a full message?
That way, we're 'guaranteeing' that we do have translated messages for any/all errors that end up being shown to the user?
Internally, it could still show the shortcut if no translation was found, but we could logDebug it when not found so we can catch all the missing translated messages?
</blockquote></details>

The lines above used the replace param and the string from locales to create the translated message. Is it what you expect?

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 22 of 62 files at r1, 39 of 53 files at r2, 19 of 19 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977)* status: 65 of 80 files reviewed, 13 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 243 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuVMxTyCRv0N2rOPyMP:-NuVMxTz1OWI2GBrDeZX:b-utwx63) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d167e88926e256780b526eef3ba7162f60342a4d/packages/geoview-core/src/core/utils/utilities.ts#L243)):*
> ```XML
>  * @returns {any} cleaned and parsed config object
>  */
> // TODO: refactor - yves, move this function to config class
> ```

Ok, I'll keep this in mind.
___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 401 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuVNQ_B3K0_mRKkQO0x:-NuVNQ_B3K0_mRKkQO0y:b8zzlii) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d167e88926e256780b526eef3ba7162f60342a4d/packages/geoview-core/src/core/utils/config/config-validation.ts#L401)):*
> ```XML
>         );
>         logger.logWarning(`- Map ${this.mapId}: ${message}`);
>         // TODO: config should not push message to map... only to console and as return value.. map will be responsible to throw notification
> ```

Acknowledge!
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 251 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuU0v7bCTOkpoozrmeC:-NuVOuTY9SQSQCbqRyzE:bu3wd29) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/34651d3b9d5f66904396d75da0894dbc83f681ec/packages/geoview-core/src/geo/layer/layer.ts#L251)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

One might think this following comment is counter productive to the changes in this PR, but hear me out :)

I see this sort of call repeated often (and it's a bit lengthy). Maybe refactor it a bit further by adding a function in AppEventProcessor that goes like this:
AppEventProcessor.getMessage(mapId, 'validation.layer.usedTwice'); // mapId first, because that's the typical pattern over there.

Implemented like:
`return api.utilities.core.getLocalizedMessage(code_string, this.getDisplayLanguage(mapId))`

The calls would be lot more straightforward for the core/ui. It's also not going back to what it was, because it's essentially moving the code from utilities to AppEventProcessor (which makes sense to have a mapId there). It does couple the api.utilities with the AppEventProcessor, but that should be fine, seeing utilities is meant to be reused. It's better than having the api 'under' the utilities like it was originally in this PR :thumbsup: 

This pattern would also fit really nicely with another comment in this review about the notification.showError/Warning/Info()
</blockquote></details>

I like the idea! The concept of more concise calls could be applied elsewhere too.

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 15 of 15 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977)* status: all files reviewed, 8 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/utils/config/reader/url-config-reader.ts` line 150 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1977#-NuU4JlHApJkIA-nchCF:-NuVTewg8r9_7vaZbXXm:b-sch878) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d167e88926e256780b526eef3ba7162f60342a4d/packages/geoview-core/src/core/utils/config/reader/url-config-reader.ts#L150)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The lines above used the replace param and the string from locales to create the translated message. Is it what you expect?
</blockquote></details>

The new implementation is basically was I was trying to say :thumbsup:

**Comment by jolevesq** [comment]
Merged in another PR

**Pull request closed without merging**
