### PR TITLE
570 correction of the  get feature info bug

### PR DESCRIPTION
**Pull request by ychoquet**
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/571)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/571)* status: all files reviewed, 2 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 426 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/571#-NELq_Kc9AhaO5VmBdwX:-NELq_Kd4k7DrVQLvlbH:bf8pg3i) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c3ae7c7c4a352c346ede2d305e85e87b39d3ebae/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L426)):*
> ```XML
>    * @returns {Promise<TypeFeatureInfoResult>} The promised feature info table.
>    */
>   protected getFeatureInfoAtCoordinate(lnglat: Coordinate, layerConfig: TypeLayerEntryConfig): Promise<TypeFeatureInfoResult> {
> ```

Can we keep both and if we use coordinate, we project the latlng array. You did this for wms. Maybe it is already there...
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts` line 325 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/571#-NELqub-ErX9BI7GF13q:-NELqub-ErX9BI7GF13r:bfs2fgy) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ebd063221f9d1e4b96ea0387c91edaaf115bf77f/packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts#L325)):*
> ```XML
> 
>   /** ***************************************************************************************************************************
>    * Return feature information for all the features in the provided polygon.
> ```

Should we say in the description that this function will return null as it is not implemented?

**Review by jolevesq — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/571)* status: all files reviewed, 2 unresolved discussions (waiting on @ychoquet)

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/571)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 426 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/571#-NELq_Kc9AhaO5VmBdwX:-NEMVF6GAZOSvgALCYgn:b-dr312j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c3ae7c7c4a352c346ede2d305e85e87b39d3ebae/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L426)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we keep both and if we use coordinate, we project the latlng array. You did this for wms. Maybe it is already there...
</blockquote></details>

In my repo, both WMS and ESRI dynamic are doing things the same way. I made a correction to return null when getFeatureInfo is uded on a layer that is not visible.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts` line 325 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/571#-NELqub-ErX9BI7GF13q:-NEMXUfTCG1-ZgX8qNke:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ebd063221f9d1e4b96ea0387c91edaaf115bf77f/packages/geoview-core/src/geo/layer/geoview-layers/raster/xyz-tiles.ts#L325)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we say in the description that this function will return null as it is not implemented?
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/571)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 426 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/571#-NELq_Kc9AhaO5VmBdwX:-NEMXrJY5j_arNsP75iq:bv504u8) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c3ae7c7c4a352c346ede2d305e85e87b39d3ebae/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L426)):*
<details><summary><i>Previously, ychoquet wrote…</i></summary><blockquote>

In my repo, both WMS and ESRI dynamic are doing things the same way. I made a correction to return null when getFeatureInfo is uded on a layer that is not visible.
</blockquote></details>

The question was more we can use at pixel, at lat long and at coordinate with all of them and made the translation to get the proper value?

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/571)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 426 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/571#-NELq_Kc9AhaO5VmBdwX:-NEMb8Yb1gMzYFqArx3y:bw9eqmp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c3ae7c7c4a352c346ede2d305e85e87b39d3ebae/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L426)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The question was more we can use at pixel, at lat long and at coordinate with all of them and made the translation to get the proper value?
</blockquote></details>

Ok, I coded the three signature (at pixel, at lat long and at coordinate) for WMS and ESRI dynamic.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 3 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/571)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
