### PR TITLE
refactor(layers) - Part 11

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

This PR is part of a series of PR and has a dependency on PR https://github.com/Canadian-Geospatial-Platform/geoview/pull/1951

This PR focuses on rewriting code surrounding the `LAYER_SET.UPDATED` event and further clarifying the map init/ready(registered)/processed/loaded states.

- The layer_set.updated event was being emitted by the mother class and listened by the children classes. Rewrote the code to use an overridable method (the layer-set class still emits the event, but only for outside now, not listened by our own core);
- Removed the singletons in the layer-set children as it was causing issues when reloading a map (it'd be reusing the same singleton, because there were 2 layer-sets children that weren't being deleted, so got rid of all that so it doesn't happen again);
- cgpv.init() now receives 2 callbacks: (1) when the map is initialized and (2) when the layers are loaded. Updated all templates accordingly - fixing issues with 'allMaps' in the process, for now...

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Currently hosting the finally of the layers refactoring here: https://alex-nrcan.github.io/geoview

# Checklist:

- [ ] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1952)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 58 of 70 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1952)* status: 58 of 70 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/app.tsx` line 179 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1952#-NtSPk2hCY3gYfDLlZYK:-NtSPk2i7B-N6ymHZDJT:bob234y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/93c4d818b73a7dbfe9744cfc777b092fd23e4014/packages/geoview-core/src/app.tsx#L179)):*
> ```XML
>   await Promise.allSettled(promises);
> 
>   // TODO: REFACTOR - Petition to never callback with 'allMaps' and rethink this.
> ```

I agree, this behavior can be done by a user from outside the map by listening to all unique map loaded.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1952)* status: 58 of 70 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/app.tsx` line 220 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1952#-NtSQDPM4LDV2zpxHY0m:-NtSQDPM4LDV2zpxHY0n:b-pzibfp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/93c4d818b73a7dbfe9744cfc777b092fd23e4014/packages/geoview-core/src/app.tsx#L220)):*
> ```XML
>   });
> 
>   // Wait for all maps to have their layers loaded
> ```

The all map thing removal would make this much cleaner

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 70 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1952)* status: 63 of 70 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts` line 214 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1952#-NtSQlPT6va5Lt3nskq3:-NtSQlPT6va5Lt3nskq4:b-r6cr8r) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/93c4d818b73a7dbfe9744cfc777b092fd23e4014/packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts#L214)):*
> ```XML
>     // TO.DOCONT: for an 'Anonymous' group layer that never got 'loaded'. See if we can fix this elsewhere and remove this.
>     if (this.entryType !== CONST_LAYER_ENTRY_TYPES.GROUP)
>       (this.geoviewLayerInstance as AbstractGeoViewLayer).registerToLayerSets(Cast<AbstractBaseLayerEntryConfig>(this));
> ```

Would need to move because validation should not create layer anymore. It is only validation structure from metadata for different type and crating a standard structure for layer to use

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1952)* status: 63 of 70 files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts` line 221 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1952#-NtSR1RK5ILZpw2R4BiY:-NtSR1RK5ILZpw2R4BiZ:bojcgrz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/93c4d818b73a7dbfe9744cfc777b092fd23e4014/packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts#L221)):*
> ```XML
> 
>   // TODO: Check - Is this still used? Remove it and favor the homonymous method in `layer`? (which also should be deleted)
>   // TO.DOCONT: I'm commenting it in this big refactor (2024-03-17) to see if anything crashes and if so, where. Seems good to me without it so far.
> ```

No geoview layer in config validation

**Review by jolevesq — COMMENTED** [review]
> Reviewed 7 of 70 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1952)* status: all files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan)

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1952)* status: all files reviewed, 4 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/app.tsx` line 179 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1952#-NtSPk2hCY3gYfDLlZYK:-NtSRzSv0jcVvw5xV7nH:bf4dq19) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/93c4d818b73a7dbfe9744cfc777b092fd23e4014/packages/geoview-core/src/app.tsx#L179)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I agree, this behavior can be done by a user from outside the map by listening to all unique map loaded.
</blockquote></details>

Should I leave the TODO there for future refactor then or address it in PR13? My time is a bit limited maybe to address it (need to verify the code in all templates)
___
*[`packages/geoview-core/src/app.tsx` line 220 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1952#-NtSQDPM4LDV2zpxHY0m:-NtSRLRF-Ud6jS_jOUID:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/93c4d818b73a7dbfe9744cfc777b092fd23e4014/packages/geoview-core/src/app.tsx#L220)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The all map thing removal would make this much cleaner
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts` line 214 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1952#-NtSQlPT6va5Lt3nskq3:-NtSRSpA-NqXj3aqHZBG:b-hdc5wd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/93c4d818b73a7dbfe9744cfc777b092fd23e4014/packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts#L214)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Would need to move because validation should not create layer anymore. It is only validation structure from metadata for different type and crating a standard structure for layer to use
</blockquote></details>

I'll leave the TODO there and keep as is for this PR then. If you disagree, ping me.
___
*[`packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts` line 221 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1952#-NtSR1RK5ILZpw2R4BiY:-NtSRmKl6tzXfu2MICG1:bbltkt4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/93c4d818b73a7dbfe9744cfc777b092fd23e4014/packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts#L221)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

No geoview layer in config validation
</blockquote></details>

Yeah, hasn't caused any issues right? And my PR13 is one that's been tested in multiple template pages thus far..
Should I remove the dead code in PR13?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1952)* status: all files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/app.tsx` line 179 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1952#-NtSPk2hCY3gYfDLlZYK:-NtSTzPsD3a2Tmkgrwr1:b-xx24ij) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/93c4d818b73a7dbfe9744cfc777b092fd23e4014/packages/geoview-core/src/app.tsx#L179)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Should I leave the TODO there for future refactor then or address it in PR13? My time is a bit limited maybe to address it (need to verify the code in all templates)
</blockquote></details>

Yeah will impact code every html. Can be done in another PR if not enough time
___
*[`packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts` line 221 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1952#-NtSR1RK5ILZpw2R4BiY:-NtSTfpZ7fX33PwhopG8:b-duwyu2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/93c4d818b73a7dbfe9744cfc777b092fd23e4014/packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts#L221)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Yeah, hasn't caused any issues right? And my PR13 is one that's been tested in multiple template pages thus far..
Should I remove the dead code in PR13?
</blockquote></details>

Keep it as it should be dealt by Yves

**Pull request merged**
