### PR TITLE
making popper dissapear on esc click

### LINKED ISSUE #1870: [BUG] <Disable clicking layers when they are in loading mode.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Layers in loading mode are clickable in both the Datatable and details tab.
We want to make sure this is not the case. 

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

This PR does two things;
* Make Popper dissapear when user click ESC key.
* Disable clicking layers when they are in loading mode.

Fixes #1870

https://cphelefu.github.io/geoview

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [X] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [X] I have connected the issues(s) to this PR
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1869)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1869)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/src/ui/popper/popper.tsx` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1869#-NrkBfM_7b0oLlJWY5YP:-NrkBfM_7b0oLlJWY5YQ:bzfjjd9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/391628f410c147711561714a8de7fbc7fc4c9a30/packages/geoview-core/src/ui/popper/popper.tsx#L1)):*
> ```XML
> /* eslint-disable react/function-component-definition */
> ```

REmove global eslint comment and add a line disable
___
*[`packages/geoview-core/src/ui/popper/popper.tsx` line 19 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1869#-NrkBrmrBc94XRi_3-6m:-NrkBrmrBc94XRi_3-6n:b-vb4zy0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/391628f410c147711561714a8de7fbc7fc4c9a30/packages/geoview-core/src/ui/popper/popper.tsx#L19)):*
> ```XML
> 
>   useEffect(() => {
>     const handleEscapeKey = (event: KeyboardEvent) => {
> ```

Add a TODO: refactor... this process of escape - going back to caller should be implemented globally

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/ui/popper/popper.tsx` line 19 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1869#-NrkBrmrBc94XRi_3-6m:-NrkJNcC7KadtVSvCSrr:b-yp8wy4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/391628f410c147711561714a8de7fbc7fc4c9a30/packages/geoview-core/src/ui/popper/popper.tsx#L19)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add a TODO: refactor... this process of escape - going back to caller should be implemented globally
</blockquote></details>

Hmm, not sure if we want to do that. Its specific to this method. Where would we put it globally?

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1869)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/ui/popper/popper.tsx` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1869#-NrkBfM_7b0oLlJWY5YP:-NrkJI6a4o1p1XhVMwwj:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/391628f410c147711561714a8de7fbc7fc4c9a30/packages/geoview-core/src/ui/popper/popper.tsx#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

REmove global eslint comment and add a line disable
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1869)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

___
*[`packages/geoview-core/src/ui/popper/popper.tsx` line 19 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1869#-NrkBrmrBc94XRi_3-6m:-NrkK5At9d2L46Ga6EwF:b3jh1pr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/391628f410c147711561714a8de7fbc7fc4c9a30/packages/geoview-core/src/ui/popper/popper.tsx#L19)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Hmm, not sure if we want to do that. Its specific to this method. Where would we put it globally?
</blockquote></details>

The esc key should be dealt globally. UI should keep track of focus component. We will do this as part pf another issue.

**Pull request merged**
