### PR TITLE
feat(datatable): common enlarge and close btn  #1494

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Create reusable enlarge, close and layer list component.

Fixes # ([1494](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1494))

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__

1. https://kaminderpal.github.io/geoview/raw-data-table.html
2. https://kaminderpal.github.io/geoview/raw-feature-info-1.html
3. https://kaminderpal.github.io/geoview/package-time-slider.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 15 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500)* status: all files reviewed, 7 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/common/close-button.tsx` line 19 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500#-NjNFOEv19KxZsRjWDRd:-NjNFOEv19KxZsRjWDRe:b2si7xi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0646a81b03cb4d80a8516f0dc3f16a35aa714783/packages/geoview-core/src/core/components/common/close-button.tsx#L19)):*
> ```XML
>  */
> export function CloseButton({ isLayersPanelVisible, setIsLayersPanelVisible }: CloseButtonProps) {
>   const { t } = useTranslation();
> ```

Can you regroup like the best practice doc https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/docs/programming/best-practices.md

```ts
const { t } = useTranslation<string>();

const theme = useTheme();
const sxClasses = getSxClasses(theme);
```
___
*[`packages/geoview-core/src/core/components/common/enlarge-button.tsx` line 19 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500#-NjNFqTO8jIoY_ccU0ja:-NjNFqTO8jIoY_ccU0jb:b2si7xi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0646a81b03cb4d80a8516f0dc3f16a35aa714783/packages/geoview-core/src/core/components/common/enlarge-button.tsx#L19)):*
> ```XML
>  */
> export function EnlargeButton({ isEnlargeDataTable, setIsEnlargeDataTable }: EnlargeButtonProps) {
>   const { t } = useTranslation();
> ```

Can you regroup like the best practice doc https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/docs/programming/best-practices.md

```ts
const { t } = useTranslation<string>();

const theme = useTheme();
const sxClasses = getSxClasses(theme);
```
___
*[`packages/geoview-core/src/core/components/common/layer-list.tsx` line 34 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500#-NjNG6GWBqzjt58_wIlj:-NjNG6GWBqzjt58_wIlk:btvq7uk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0646a81b03cb4d80a8516f0dc3f16a35aa714783/packages/geoview-core/src/core/components/common/layer-list.tsx#L34)):*
> ```XML
> }
> 
> export function LayerList({
> ```

Can you add JSDOC comment for this function
___
*[`packages/geoview-core/src/core/components/common/layer-list.tsx` line 42 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500#-NjNGB2YAosAzCrLAO5L:-NjNGB2YAosAzCrLAO5M:b2si7xi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0646a81b03cb4d80a8516f0dc3f16a35aa714783/packages/geoview-core/src/core/components/common/layer-list.tsx#L42)):*
> ```XML
>   mapFiltered = {},
> }: LayerListProps) {
>   const { t } = useTranslation();
> ```

Can you regroup like the best practice doc https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/docs/programming/best-practices.md

```ts
const { t } = useTranslation<string>();

const theme = useTheme();
const sxClasses = getSxClasses(theme);
```
___
*[`packages/geoview-core/src/core/components/common/layer-list.tsx` line 62 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500#-NjNHc0WCNY4FLWTykcG:-NjNHc0WCNY4FLWTykcH:bxx17lx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0646a81b03cb4d80a8516f0dc3f16a35aa714783/packages/geoview-core/src/core/components/common/layer-list.tsx#L62)):*
> ```XML
>   const getFeaturesOfLayer = (layerPath: string, index: number): string => {
>     return rowsFiltered && rowsFiltered[layerPath]
>       ? `${rowsFiltered[layerPath]} ${t('dataTable.featureFiltered')}`
> ```

This is specific to datatable.... should it be set by the component itself (details, table, slider, ...) Maybe each component can set his own info in the store to be reuse by this component?
___
*[`packages/geoview-core/src/core/components/common/layer-list.tsx` line 104 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500#-NjNGW6e2kCT-XXWI-mu:-NjNGW6e2kCT-XXWI-mv:b-blyqse) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0646a81b03cb4d80a8516f0dc3f16a35aa714783/packages/geoview-core/src/core/components/common/layer-list.tsx#L104)):*
> ```XML
>                         </Typography>
> 
>                         {isMapFilteredSelectedForLayer(layer.layerPath) && <FilterAltIcon sx={{ color: theme.palette.grey['500'] }} />}
> ```

Is this specific to data table? Can we have generic placeholder here and in table set the icon and stuff. This way this component stay very generic 
___
*[`packages/geoview-core/src/core/components/common/responsive-grid.tsx` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500#-NjNI8cb2ppkce1FAwZm:-NjNI8ccCiifWbVrck9Q:bq179lo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0646a81b03cb4d80a8516f0dc3f16a35aa714783/packages/geoview-core/src/core/components/common/responsive-grid.tsx#L2)):*
> ```XML
> import { ReactNode } from 'react';
> import { GridProps, SxProps } from '@mui/material';
> ```

Should these 2 import came from the Grid element in UI. For the moment I think Grid is imported directly from Material. should we create the component and inject these import?

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500)* status: 11 of 19 files reviewed, 7 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/common/close-button.tsx` line 19 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500#-NjNFOEv19KxZsRjWDRd:-NjO92SE9CHph3yICLDe:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0646a81b03cb4d80a8516f0dc3f16a35aa714783/packages/geoview-core/src/core/components/common/close-button.tsx#L19)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you regroup like the best practice doc https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/docs/programming/best-practices.md

```ts
const { t } = useTranslation<string>();

const theme = useTheme();
const sxClasses = getSxClasses(theme);
```
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/common/enlarge-button.tsx` line 19 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500#-NjNFqTO8jIoY_ccU0ja:-NjO93T35gVloW6el-t1:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0646a81b03cb4d80a8516f0dc3f16a35aa714783/packages/geoview-core/src/core/components/common/enlarge-button.tsx#L19)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you regroup like the best practice doc https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/docs/programming/best-practices.md

```ts
const { t } = useTranslation<string>();

const theme = useTheme();
const sxClasses = getSxClasses(theme);
```
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/common/layer-list.tsx` line 34 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500#-NjNG6GWBqzjt58_wIlj:-NjOAZaW8lM4Okw1bDcO:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0646a81b03cb4d80a8516f0dc3f16a35aa714783/packages/geoview-core/src/core/components/common/layer-list.tsx#L34)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add JSDOC comment for this function
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/common/layer-list.tsx` line 42 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500#-NjNGB2YAosAzCrLAO5L:-NjOA_8f7Q_RjFz37leJ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0646a81b03cb4d80a8516f0dc3f16a35aa714783/packages/geoview-core/src/core/components/common/layer-list.tsx#L42)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you regroup like the best practice doc https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/docs/programming/best-practices.md

```ts
const { t } = useTranslation<string>();

const theme = useTheme();
const sxClasses = getSxClasses(theme);
```
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/common/layer-list.tsx` line 62 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500#-NjNHc0WCNY4FLWTykcG:-NjOAbx42OrEcNCZsW1g:bb7f2mf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0646a81b03cb4d80a8516f0dc3f16a35aa714783/packages/geoview-core/src/core/components/common/layer-list.tsx#L62)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This is specific to datatable.... should it be set by the component itself (details, table, slider, ...) Maybe each component can set his own info in the store to be reuse by this component?
</blockquote></details>

done
___
*[`packages/geoview-core/src/core/components/common/layer-list.tsx` line 104 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500#-NjNGW6e2kCT-XXWI-mu:-NjOXT1x8rHrMf7DX246:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0646a81b03cb4d80a8516f0dc3f16a35aa714783/packages/geoview-core/src/core/components/common/layer-list.tsx#L104)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this specific to data table? Can we have generic placeholder here and in table set the icon and stuff. This way this component stay very generic
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/common/responsive-grid.tsx` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500#-NjNI8cb2ppkce1FAwZm:-NjOBLRr5iddwUJuR8-P:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0646a81b03cb4d80a8516f0dc3f16a35aa714783/packages/geoview-core/src/core/components/common/responsive-grid.tsx#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should these 2 import came from the Grid element in UI. For the moment I think Grid is imported directly from Material. should we create the component and inject these import?
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 13 files at r2, 9 of 9 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 155 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500#-NjOhCVn3dpURxuDdCqZ:-NjOhCVn3dpURxuDdCq_:bsjyo1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5698db54efb126f865bd98ca085619dbd1b2abe4/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L155)):*
> ```XML
>         <ResponsiveGrid.Left
>           isLayersPanelVisible={isLayersPanelVisible}
>           xs={isLayersPanelVisible ? 12 : 0}
> ```

The break points are the smae in all component, dhould it be default in ResponsiveGrid.Right and optional to override if needed?

**Review by jolevesq — APPROVED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1500)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Pull request merged**
