### PR TITLE
1015 geolocation UI

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Implement new geolocator search ui.

Fixes # ([1015](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1015))

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Manually on local env.

# Checklist:

- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031)* status: 2 of 10 files reviewed, 9 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/public/configs/geolocator-config.json` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtWZxS6a26NXDvEROQ:-NTtWZxS6a26NXDvEROR:bl5e25w) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/public/configs/geolocator-config.json#L2)):*
> ```JSON
> {
>   "map": {
> ```

There is an error in the configuration, check the console.
___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 14 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtWyeR9q8ZuYaYOUip:-NTtWyeR9q8ZuYaYOUiq:b-kbk5zr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L14)):*
> ```XML
>     whiteSpace: 'nowrap',
>     overflow: 'hidden',
>     textOverflow: 'ellipsis',
> ```

tooltip does not appears on TAB with keyboard
___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 27 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtXHE78e9rOzdyauci:-NTtXHE78e9rOzdyaucj:b-oyvy9n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L27)):*
> ```XML
> type tooltipProp = Pick<GeoListItem, 'name' | 'tag' | 'province'>;
> 
> const getTooltipTitle = ({ name, tag, province }: tooltipProp): string => {
> ```

Add JSDOC documentation
___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 38 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtXLg-AWlsw_N8aWqe:-NTtXLg-AWlsw_N8aWqf:b-oyvy9n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L38)):*
> ```XML
> };
> 
> export default function GeoList({ geoListItems, zoomToLocation }: GeoListProps) {
> ```

Add JSDOC documentation
___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 42 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtXwPT4CcPak8Cz6Cs:-NTtXwPT4CcPak8Cz6Ct:bgiho41) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L42)):*
> ```XML
>     <>
>       {geoListItems.map((geoListItem, index) => (
>         // sometime when we search by `bay`,response have name and lat same, thats why index is used to distinguish
> ```

space after, 
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 15 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtYWm_DjE7aL8sLw6I:-NTtYWm_DjE7aL8sLw6J:bvgrrul) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L15)):*
> ```XML
> import { TypeWindow } from '../../types/cgpv-types';
> 
> const w = window as TypeWindow;
> ```

This is used when component are created outside the core. When from inside you do not need this
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 19 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtYcOeBL_M3mo7a3hJ:-NTtYcOeBL_M3mo7a3hK:bv9d9i0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L19)):*
> ```XML
> export function Geolocator() {
>   const { cgpv } = w;
>   const { api } = cgpv;
> ```

Same here, api is imported then you can access it
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 35 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtYrei0OYy240N8ZQD:-NTtYrej0DgLjATahpVG:b-jf4rz4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L35)):*
> ```XML
>   const updateUrl = useCallback(() => {
>     if (searchValue.length) {
>       const updatedUrl = `https://fr59c5usw4.execute-api.ca-central-1.amazonaws.com/dev?q=${searchValue}&lang=${i18n.language}&keys=geonames`;
> ```

Store the url value as default value in schema-default-config.json
  "serviceUrls": {
    "keys": "https://geocore.api.geo.ca"
    "geolocator:" your url
  },

Update the schema and validation accordingly
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 99 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtZqz7-CN7zZPpDUd3:-NTtZqz7-CN7zZPpDUd4:b64jjjn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L99)):*
> ```XML
>                       color="inherit"
>                       sx={{ mr: 2, ml: 4 }}
>                       onClick={() => {
> ```

Close button should not zoom to home, just reset the input box and close the search. Create a function to handle all the call. Add JSDOC for your function

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031)* status: 2 of 13 files reviewed, 9 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/configs/geolocator-config.json` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtWZxS6a26NXDvEROQ:-NTzNyA56eZo1DQmsy1V:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/public/configs/geolocator-config.json#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There is an error in the configuration, check the console.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 14 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtWyeR9q8ZuYaYOUip:-NTzPCyQ-c-UGpQR3L1O:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

tooltip does not appears on TAB with keyboard
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 27 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtXHE78e9rOzdyauci:-NTzPSKv8FIP1uuqd_Wr:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L27)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add JSDOC documentation
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 38 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtXLg-AWlsw_N8aWqe:-NTzPuJe6QsebVmhgI3E:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L38)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add JSDOC documentation
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 42 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtXwPT4CcPak8Cz6Cs:-NTzPwAJ77ZNan_Ex4xZ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L42)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

space after, 
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 15 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtYWm_DjE7aL8sLw6I:-NTzbngGDUcbZqfg_dyU:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L15)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This is used when component are created outside the core. When from inside you do not need this
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 19 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtYcOeBL_M3mo7a3hJ:-NTzbnxpEIjJOMOaHGiV:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L19)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same here, api is imported then you can access it
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 35 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtYrei0OYy240N8ZQD:-NTzXPQDDO2t5MvZiRu5:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L35)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Store the url value as default value in schema-default-config.json
  "serviceUrls": {
    "keys": "https://geocore.api.geo.ca"
    "geolocator:" your url
  },

Update the schema and validation accordingly
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 99 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtZqz7-CN7zZPpDUd3:-NTzYyAx8lEk6VQxyrti:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L99)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Close button should not zoom to home, just reset the input box and close the search. Create a function to handle all the call. Add JSDOC for your function
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r1, 3 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031)* status: 7 of 13 files reviewed, 8 unresolved discussions (waiting on @kaminderpal, @param, and @return)

___
*[`packages/geoview-core/schema.json` line 1858 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NU23q0M-NdIxG49sjOK:-NU23q0M-NdIxG49sjOL:b-eu36b9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b42331cf48686151302ba964e3f965b6b7b00732/packages/geoview-core/schema.json#L1858)):*
> ```JSON
>         "geolocator": {
>           "type": "string",
>           "default": "https://fr59c5usw4.execute-api.ca-central-1.amazonaws.com/dev?keys=geonames",
> ```

Do not put the the default value here, We only need it in the default schema config.
___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 14 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtWyeR9q8ZuYaYOUip:-NU20d_W-mAGNiT7-UrZ:b-6wvs70) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L14)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Tooltip just missing the last part of the item (tag)
___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 27 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtXHE78e9rOzdyauci:-NU1z_wv749QwN1_kZrt:bzc3trg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L27)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

In the doc, follow other functions style, you need to give a description of params and return values. Do this for all JSDOC

Like 
/**
   * build the JSON file
   *
   * @param {GridRowId} gridRowIds the array of the rowId
   * @return {JSON.stringify} Json gile content
   *
   */
  const getJson = (gridRowIds: GridRowId[])
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 15 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtYWm_DjE7aL8sLw6I:-NU1zIl91krfgEAW4Awz:b-v3voe5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L15)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You should not import cgpv, you only import api. cgpv is for packages
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 58 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NU24xMcC6eELRcweuT6:-NU24xMcC6eELRcweuT7:b5585hy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b42331cf48686151302ba964e3f965b6b7b00732/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L58)):*
> ```XML
>     setSearchValue('');
>     if (reset) {
>       reset();
> ```

Why are calling fetch dispatch on reset?
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 123 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NU21lbO1kf2jSp8VqWj:-NU21lbO1kf2jSp8VqWk:b42xqza) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b42331cf48686151302ba964e3f965b6b7b00732/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L123)):*
> ```XML
>             {(!data.length || error) && (
>               <Typography component="p" sx={{ fontSize: 14, p: 10 }}>
>                 No matches found for {searchValue}
> ```

This need to be in i18n so we can have french and english message
___
*[`packages/geoview-core/src/core/components/geolocator/types.ts` line 1 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NU219bV4v1VxwweIEW4:-NU219bV4v1VxwweIEW5:b-10kacr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/types.ts#L1)):*
> ```XML
> export interface GeoListItem {
> ```

Can you add your type to the tsx component file to keep everything more bundle?

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031)* status: 7 of 15 files reviewed, 8 unresolved discussions (waiting on @jolevesq, @param, and @return)

___
*[`packages/geoview-core/schema.json` line 1858 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NU23q0M-NdIxG49sjOK:-NU2ULkE5N08yBZUIarE:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b42331cf48686151302ba964e3f965b6b7b00732/packages/geoview-core/schema.json#L1858)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do not put the the default value here, We only need it in the default schema config.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 14 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtWyeR9q8ZuYaYOUip:-NU2KI7h74ZsRid5sik_:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Tooltip just missing the last part of the item (tag)
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 27 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtXHE78e9rOzdyauci:-NU2UNPfES_HZlF22jAe:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L27)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

In the doc, follow other functions style, you need to give a description of params and return values. Do this for all JSDOC

Like 
/**
   * build the JSON file
   *
   * @param {GridRowId} gridRowIds the array of the rowId
   * @return {JSON.stringify} Json gile content
   *
   */
  const getJson = (gridRowIds: GridRowId[])
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 15 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NTtYWm_DjE7aL8sLw6I:-NU2EcgH4LJ4e2CkIBT_:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L15)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You should not import cgpv, you only import api. cgpv is for packages
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 123 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NU21lbO1kf2jSp8VqWj:-NU2EYeI7cc_GqWT1BEv:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b42331cf48686151302ba964e3f965b6b7b00732/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L123)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This need to be in i18n so we can have french and english message
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/types.ts` line 1 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-NU219bV4v1VxwweIEW4:-NU2BcdI7xWwyQR60oCM:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b11fd6004ada8b06907ce87216f0b9ba71e3cd3c/packages/geoview-core/src/core/components/geolocator/types.ts#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add your type to the tsx component file to keep everything more bundle?
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 7 files at r3, 6 of 6 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031)* status: all files reviewed, 2 unresolved discussions (waiting on @kaminderpal)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1031#-:-NU3361N4a7Z1BQwqVVn:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @kaminderpal)

**Pull request merged**
