### PR TITLE
feat(time-slider): update time-slider layout to use config values #1540

### PR DESCRIPTION
**Pull request by mayurmarakana89**
# Description

Use config values to update time slider layout

Fixes # ([1540](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1540))

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://mayurmarakana89.github.io/geoview/package-time-slider.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, 4 of 8 files at r2, 7 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591)* status: 13 of 14 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @kaminderpal, @mayurmarakana89, and @ychoquet)

___
*[`packages/geoview-core/public/configs/package-time-slider-config-time-slider.json` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-Nl4EzbbDADY7ztcJQNu:-Nl4EzbbDADY7ztcJQNv:b-wm9f0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a4fa0c2211689ea13547d874e75591a365fe8f5/packages/geoview-core/public/configs/package-time-slider-config-time-slider.json#L3)):*
> ```JSON
> {
>   "layers": [],
>   "suportedLanguages": ["en", "fr"]
> ```

This file is not needed, default will be use
___
*[`packages/geoview-core/src/api/plugin/plugin.ts` line 70 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV3xg95osegHkhkS4S:-NlV3xgA8A7z2kALNCkt:b-985awz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a7b48ff76c57c092a268e63506528556b9c668e7/packages/geoview-core/src/api/plugin/plugin.ts#L70)):*
> ```XML
>         document.body.appendChild(script);
>         script.onload = () => {
>           setTimeout(() => resolve(window.plugins[pluginId]), 1000);
> ```

Why timeout? Put /// TODO: make async
___
*[`packages/geoview-core/src/api/plugin/plugin.ts` line 74 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV42awB2RUvE0nbebF:-NlV42awB2RUvE0nbebG:b-985awz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a7b48ff76c57c092a268e63506528556b9c668e7/packages/geoview-core/src/api/plugin/plugin.ts#L74)):*
> ```XML
> 
>         script.onerror = () => {
>           setTimeout(() => resolve(null), 1000);
> ```

Why timeout? Put /// TODO: make async
___
*[`packages/geoview-core/src/api/plugin/plugin.ts` line 79 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV43AuCqU4iniPrz_l:-NlV43AuCqU4iniPrz_m:b-985awz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a7b48ff76c57c092a268e63506528556b9c668e7/packages/geoview-core/src/api/plugin/plugin.ts#L79)):*
> ```XML
> 
>       if (existingScript && window.plugins && window.plugins[pluginId]) {
>         setTimeout(() => resolve(window.plugins[pluginId]), 1000);
> ```

Why timeout? Put /// TODO: make async
___
*[`packages/geoview-time-slider/schema.json` line 14 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV4NKt2biQr1ziysh4:-NlV4NKt2biQr1ziysh5:b4ktcnw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a7b48ff76c57c092a268e63506528556b9c668e7/packages/geoview-time-slider/schema.json#L14)):*
> ```JSON
>         "type": "object",
>         "properties": {
>           "title": {
> ```

Use localized type of field where we can have ne and fr value so both supported language can be inside one file
___
*[`packages/geoview-time-slider/schema.json` line 20 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV4Uls3KPOprgbLTuO:-NlV4Uls3KPOprgbLTuP:b4ktcnw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a7b48ff76c57c092a268e63506528556b9c668e7/packages/geoview-time-slider/schema.json#L20)):*
> ```JSON
>           },
>           "description": {
>             "type": "string",
> ```

Use localized type of field where we can have ne and fr value so both supported language can be inside one file
___
*[`packages/geoview-time-slider/src/index.tsx` line 8 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV4BkNDTGUyQD0vg_M:-NlV4BkNDTGUyQD0vg_N:b1ukls4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a4fa0c2211689ea13547d874e75591a365fe8f5/packages/geoview-time-slider/src/index.tsx#L8)):*
> ```XML
>   TypePluginOptions,
>   TypeButtonPanel,
>   getLocalizedValue,
> ```

Keep this as your title, description are localized field
___
*[`packages/geoview-time-slider/src/time-slider.tsx` line 117 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV4grhCf-cHHwhGL0o:-NlV4grhCf-cHHwhGL0p:b-ptsj3g) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a7b48ff76c57c092a268e63506528556b9c668e7/packages/geoview-time-slider/src/time-slider.tsx#L117)):*
> ```XML
>     locked,
>     reversed,
>   } = useTimeSliderLayers()[layerPath];
> ```

Will need to check performance as we should technically have one selector by constant, take note

**Review by Alex-NRCan — APPROVED** [review]
:lgtm: thanks for the review, it's useful for the little plugin overhaul I'm doing with AbstractPlugin class.

> Reviewed 2 of 8 files at r2, 1 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-:-NlYVyD15M1ISxvcqhxc:bw1ffeh)* status: all files reviewed, 8 unresolved discussions (waiting on @amir-azma, @cphelefu, @DamonU2, @kaminderpal, @mayurmarakana89, and @ychoquet)

**Comment by mayurmarakana89** [comment]
> > Reviewed 8 of 11 files at r1, 4 of 8 files at r2, 7 of 8 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591)_ status: 13 of 14 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @kaminderpal, @mayurmarakana89, and @ychoquet)
> 
> _[`packages/geoview-core/public/configs/package-time-slider-config-time-slider.json` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-Nl4EzbbDADY7ztcJQNu:-Nl4EzbbDADY7ztcJQNv:b-wm9f0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a4fa0c2211689ea13547d874e75591a365fe8f5/packages/geoview-core/public/configs/package-time-slider-config-time-slider.json#L3)):_
> 
> > ```json
> > {
> >   "layers": [],
> >   "suportedLanguages": ["en", "fr"]
> > ```
> 
> This file is not needed, default will be use
> 
> _[`packages/geoview-core/src/api/plugin/plugin.ts` line 70 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV3xg95osegHkhkS4S:-NlV3xgA8A7z2kALNCkt:b-985awz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a7b48ff76c57c092a268e63506528556b9c668e7/packages/geoview-core/src/api/plugin/plugin.ts#L70)):_
> 
> > ```
> >         document.body.appendChild(script);
> >         script.onload = () => {
> >           setTimeout(() => resolve(window.plugins[pluginId]), 1000);
> > ```
> 
> Why timeout? Put /// TODO: make async
> 
> _[`packages/geoview-core/src/api/plugin/plugin.ts` line 74 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV42awB2RUvE0nbebF:-NlV42awB2RUvE0nbebG:b-985awz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a7b48ff76c57c092a268e63506528556b9c668e7/packages/geoview-core/src/api/plugin/plugin.ts#L74)):_
> 
> > ```
> >         script.onerror = () => {
> >           setTimeout(() => resolve(null), 1000);
> > ```
> 
> Why timeout? Put /// TODO: make async
> 
> _[`packages/geoview-core/src/api/plugin/plugin.ts` line 79 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV43AuCqU4iniPrz_l:-NlV43AuCqU4iniPrz_m:b-985awz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a7b48ff76c57c092a268e63506528556b9c668e7/packages/geoview-core/src/api/plugin/plugin.ts#L79)):_
> 
> > ```
> >       if (existingScript && window.plugins && window.plugins[pluginId]) {
> >         setTimeout(() => resolve(window.plugins[pluginId]), 1000);
> > ```
> 
> Why timeout? Put /// TODO: make async
> 
> _[`packages/geoview-time-slider/schema.json` line 14 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV4NKt2biQr1ziysh4:-NlV4NKt2biQr1ziysh5:b4ktcnw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a7b48ff76c57c092a268e63506528556b9c668e7/packages/geoview-time-slider/schema.json#L14)):_
> 
> > ```json
> >         "type": "object",
> >         "properties": {
> >           "title": {
> > ```
> 
> Use localized type of field where we can have ne and fr value so both supported language can be inside one file
> 
> _[`packages/geoview-time-slider/schema.json` line 20 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV4Uls3KPOprgbLTuO:-NlV4Uls3KPOprgbLTuP:b4ktcnw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a7b48ff76c57c092a268e63506528556b9c668e7/packages/geoview-time-slider/schema.json#L20)):_
> 
> > ```json
> >           },
> >           "description": {
> >             "type": "string",
> > ```
> 
> Use localized type of field where we can have ne and fr value so both supported language can be inside one file
> 
> _[`packages/geoview-time-slider/src/index.tsx` line 8 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV4BkNDTGUyQD0vg_M:-NlV4BkNDTGUyQD0vg_N:b1ukls4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a4fa0c2211689ea13547d874e75591a365fe8f5/packages/geoview-time-slider/src/index.tsx#L8)):_
> 
> > ```
> >   TypePluginOptions,
> >   TypeButtonPanel,
> >   getLocalizedValue,
> > ```
> 
> Keep this as your title, description are localized field
> 
> _[`packages/geoview-time-slider/src/time-slider.tsx` line 117 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV4grhCf-cHHwhGL0o:-NlV4grhCf-cHHwhGL0p:b-ptsj3g) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a7b48ff76c57c092a268e63506528556b9c668e7/packages/geoview-time-slider/src/time-slider.tsx#L117)):_
> 
> > ```
> >     locked,
> >     reversed,
> >   } = useTimeSliderLayers()[layerPath];
> > ```
> 
> Will need to check performance as we should technically have one selector by constant, take note

Thank you for your comments, have addressed them. Please re-review.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591)* status: 9 of 14 files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @kaminderpal, @mayurmarakana89, and @ychoquet)

___
*[`packages/geoview-core/src/ui/slider/slider.tsx` line 143 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlYfQgaDfGA09TZg2-4:-NlYfQgaDfGA09TZg2-5:bfmpsp3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b73cdba461197c5b26b56a87e2bfa0030815bd56/packages/geoview-core/src/ui/slider/slider.tsx#L143)):*
> ```XML
> 
>   // eslint-disable-next-line react-hooks/exhaustive-deps
>   const removeLabelOverlap = (mapId: string) => {
> ```

Why are you using the map id, there is ne slider by layer so we can have multiple on a map. Should you create it like mapid-layerid?

**Review by mayurmarakana89 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591)* status: 8 of 14 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @jolevesq, @kaminderpal, and @ychoquet)

___
*[`packages/geoview-core/src/api/plugin/plugin.ts` line 70 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV3xg95osegHkhkS4S:-NlYfZ_2D4LWIzG-A--n:b-8ebts) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a7b48ff76c57c092a268e63506528556b9c668e7/packages/geoview-core/src/api/plugin/plugin.ts#L70)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why timeout? Put /// TODO: make async
</blockquote></details>

Explained why timeout is being used.
___
*[`packages/geoview-core/src/api/plugin/plugin.ts` line 74 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV42awB2RUvE0nbebF:-NlYfhYMBftag2rghr47:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a7b48ff76c57c092a268e63506528556b9c668e7/packages/geoview-core/src/api/plugin/plugin.ts#L74)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why timeout? Put /// TODO: make async
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/plugin/plugin.ts` line 79 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV43AuCqU4iniPrz_l:-NlYfhxKDwVRP0nBPGMU:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a7b48ff76c57c092a268e63506528556b9c668e7/packages/geoview-core/src/api/plugin/plugin.ts#L79)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why timeout? Put /// TODO: make async
</blockquote></details>

Done.
___
*[`packages/geoview-time-slider/schema.json` line 14 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV4NKt2biQr1ziysh4:-NlYfk2X2Gu9QDvGnn-x:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a7b48ff76c57c092a268e63506528556b9c668e7/packages/geoview-time-slider/schema.json#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use localized type of field where we can have ne and fr value so both supported language can be inside one file
</blockquote></details>

Done.
___
*[`packages/geoview-time-slider/schema.json` line 20 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV4Uls3KPOprgbLTuO:-NlYfkmW3Egsai6B8ygl:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a7b48ff76c57c092a268e63506528556b9c668e7/packages/geoview-time-slider/schema.json#L20)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use localized type of field where we can have ne and fr value so both supported language can be inside one file
</blockquote></details>

Done.
___
*[`packages/geoview-time-slider/src/index.tsx` line 8 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlV4BkNDTGUyQD0vg_M:-NlYflQNDL0RlVFndbda:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a4fa0c2211689ea13547d874e75591a365fe8f5/packages/geoview-time-slider/src/index.tsx#L8)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Keep this as your title, description are localized field
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/configs/package-time-slider-config-time-slider.json` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-Nl4EzbbDADY7ztcJQNu:-NlYfQvdCpDj2BU2vkws:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a4fa0c2211689ea13547d874e75591a365fe8f5/packages/geoview-core/public/configs/package-time-slider-config-time-slider.json#L3)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This file is not needed, default will be use
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 5 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @kaminderpal, @mayurmarakana89, and @ychoquet)

**Review by mayurmarakana89 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @jolevesq, @kaminderpal, and @ychoquet)

___
*[`packages/geoview-core/src/ui/slider/slider.tsx` line 143 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlYfQgaDfGA09TZg2-4:-NlYkF1v5H0EXsItJQ5c:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b73cdba461197c5b26b56a87e2bfa0030815bd56/packages/geoview-core/src/ui/slider/slider.tsx#L143)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why are you using the map id, there is ne slider by layer so we can have multiple on a map. Should you create it like mapid-layerid?
</blockquote></details>

Done.

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591)* status: 12 of 14 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @jolevesq, @kaminderpal, @mayurmarakana89, and @ychoquet)

___
*[`packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json` line 4 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlYglXS-oLI1mwa50nT:-NlYglXS-oLI1mwa50nU:b-ml5l03) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b73cdba461197c5b26b56a87e2bfa0030815bd56/packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json#L4)):*
> ```JSON
>   "sliders": [
>     {
>       "layerPaths": ["historical-flood/0"],
> ```

This is not showing up on the demo page - both maps only have a slider for MSI
___
*[`packages/geoview-time-slider/src/time-slider.tsx` line 124 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlYi5vD7NwmxG2IEbdz:-NlYi5vD7NwmxG2IEbe-:b-jp5gw2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b73cdba461197c5b26b56a87e2bfa0030815bd56/packages/geoview-time-slider/src/time-slider.tsx#L124)):*
> ```XML
>   const sliderDefaultValue = configValues?.defaultValue || defaultValue;
>   const sliderLocked = configValues?.locked !== undefined ? configValues?.locked : locked;
>   const sliderReversed = configValues?.reversed !== undefined ? configValues?.reversed : reversed;
> ```

We should be using the states from the store, not constants for these. The store states should be set to the values from the config initially, and then the config values can be ignored.

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591)* status: 12 of 14 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @jolevesq, @kaminderpal, @mayurmarakana89, and @ychoquet)

___
*[`packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json` line 4 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlYglXS-oLI1mwa50nT:-NlYlGzkEDVuTdIhaTU3:bvqtn53) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b73cdba461197c5b26b56a87e2bfa0030815bd56/packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json#L4)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

This is not showing up on the demo page - both maps only have a slider for MSI
</blockquote></details>

Nevermind, seems to have been fixed

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 1 of 11 files at r1, 1 of 8 files at r3, 4 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591)* status: 12 of 14 files reviewed, 3 unresolved discussions (waiting on @amir-azma, @cphelefu, @jolevesq, @kaminderpal, @mayurmarakana89, and @ychoquet)

**Review by mayurmarakana89 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591)* status: 10 of 14 files reviewed, 3 unresolved discussions (waiting on @amir-azma, @cphelefu, @DamonU2, @jolevesq, @kaminderpal, and @ychoquet)

___
*[`packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json` line 4 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlYglXS-oLI1mwa50nT:-NlYsLRB4iQcfptElGGU:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b73cdba461197c5b26b56a87e2bfa0030815bd56/packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json#L4)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Nevermind, seems to have been fixed
</blockquote></details>

Done.
___
*[`packages/geoview-time-slider/src/time-slider.tsx` line 124 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlYi5vD7NwmxG2IEbdz:-NlYsI9h2zNkIWzSkhDw:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b73cdba461197c5b26b56a87e2bfa0030815bd56/packages/geoview-time-slider/src/time-slider.tsx#L124)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

We should be using the states from the store, not constants for these. The store states should be set to the values from the config initially, and then the config values can be ignored.
</blockquote></details>

Done.

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591)* status: 9 of 14 files reviewed, 4 unresolved discussions (waiting on @amir-azma, @cphelefu, @jolevesq, @kaminderpal, @mayurmarakana89, and @ychoquet)

___
*[`packages/geoview-time-slider/src/time-slider.tsx` line 98 at r8](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlYvQAjEH0PMoMwtmJp:-NlYvQAjEH0PMoMwtmJq:br6emtx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/44ea4a8a4cf9a68524ee9e63f021d42d72c18bf0/packages/geoview-time-slider/src/time-slider.tsx#L98)):*
> ```XML
>     setTitle(layerPath, getLocalizedValue(sliderConfig?.title, mapId) || '');
>     setDescription(layerPath, getLocalizedValue(sliderConfig?.description, mapId) || '');
>     setDefaultValue(layerPath, sliderConfig?.defaultValue || '');
> ```

Don't want to override the original value unless there is something in the config
___
*[`packages/geoview-time-slider/src/time-slider.tsx` line 100 at r8](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlYvt15EPTABUbdx8EK:-NlYvt15EPTABUbdx8EL:b-u823eq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/44ea4a8a4cf9a68524ee9e63f021d42d72c18bf0/packages/geoview-time-slider/src/time-slider.tsx#L100)):*
> ```XML
>     setDefaultValue(layerPath, sliderConfig?.defaultValue || '');
>     setLocked(layerPath, sliderConfig?.locked !== undefined ? sliderConfig?.locked : false);
>     setReversed(layerPath, sliderConfig?.reversed !== undefined ? sliderConfig?.reversed : false);
> ```

Same for locked and reversed, preserve the values unless there is something in the config. This will also reset them to config values when switching between layers, which is probably not what we want. It might be best to move handling of the config to the event processor.

**Review by mayurmarakana89 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591)* status: 6 of 16 files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @jolevesq, @kaminderpal, and @ychoquet)

___
*[`packages/geoview-time-slider/src/time-slider.tsx` line 98 at r8](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlYvQAjEH0PMoMwtmJp:-NlxOvG757T8d3525JT3:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/44ea4a8a4cf9a68524ee9e63f021d42d72c18bf0/packages/geoview-time-slider/src/time-slider.tsx#L98)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Don't want to override the original value unless there is something in the config
</blockquote></details>

Done.
___
*[`packages/geoview-time-slider/src/time-slider.tsx` line 100 at r8](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-NlYvt15EPTABUbdx8EK:-NlxOuLwAODLObJolbGA:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/44ea4a8a4cf9a68524ee9e63f021d42d72c18bf0/packages/geoview-time-slider/src/time-slider.tsx#L100)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Same for locked and reversed, preserve the values unless there is something in the config. This will also reset them to config values when switching between layers, which is probably not what we want. It might be best to move handling of the config to the event processor.
</blockquote></details>

Done.

**Review by DamonU2 — COMMENTED** [review]
We lost the optional items from the title at some point - it doesn't look like it is in this PR, but if you look at Spatiotemporel in the default map, the slider is (correctly) only showing the time, but the day that it is occurring is not showing after the field.

> Reviewed 1 of 2 files at r5, 1 of 1 files at r8, 5 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-:-NlxqVQZ895pDUdUMBZ9:b-ub17uq)* status: 13 of 16 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @jolevesq, @kaminderpal, and @ychoquet)

**Comment by mayurmarakana89** [comment]
> We lost the optional items from the title at some point - it doesn't look like it is in this PR, but if you look at Spatiotemporel in the default map, the slider is (correctly) only showing the time, but the day that it is occurring is not showing after the field.
> 
> > Reviewed 1 of 2 files at r5, 1 of 1 files at r8, 5 of 7 files at r9, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591#-:-NlxqVQZ895pDUdUMBZ9:b-ub17uq)_ status: 13 of 16 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @jolevesq, @kaminderpal, and @ychoquet)

Yeah as far as I remember, we were calculating the fieldAlias to display that, and now in my PR, I'm just using it directly from the store. Let me find that logic and add it in the initialize call.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r8, 7 of 7 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1591)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amir-azma, @cphelefu, @DamonU2, @kaminderpal, and @ychoquet)

**Pull request merged**
