### PR TITLE
feat(ui): zoom to my location button added

### LINKED ISSUE #1092: [FEATURE] Add Show MyLocation button to nav bar
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

As a user, I would like to have to button to zoom to my location

### Implementation UI

As in RAMP, add a button to use ip address to zoom to my location

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #1092

# Description

Nav-bar button to zoom to location added

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Only tested with my location

[__URL for deploy__](https://damonu2.github.io/geoview/geojson.html)

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1122)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1122)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @DamonU2)

___
*[`packages/geoview-core/src/core/components/nav-bar/buttons/location.tsx` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1122#-NZ2QvTqEw3qjn2NqPfI:-NZ2QvTqEw3qjn2NqPfJ:b-poqf3j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e6ce5f763699798712524a26114d04217bf30c23/packages/geoview-core/src/core/components/nav-bar/buttons/location.tsx#L50)):*
> ```XML
>       api
>         .map(mapId)
>         .map.getView()
> ```

I think we have a function in geo utils to zoom to a location

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1122)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @DamonU2)

___
*[`packages/geoview-core/src/core/components/nav-bar/buttons/location.tsx` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1122#-NZ2QvTqEw3qjn2NqPfI:-NZ2RAvx1tSVr9QA8fB_:bpp3i69) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e6ce5f763699798712524a26114d04217bf30c23/packages/geoview-core/src/core/components/nav-bar/buttons/location.tsx#L50)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think we have a function in geo utils to zoom to a location
</blockquote></details>

Check if it zooms nearer the place. Zoom level 10 is a little bit far

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1122)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/nav-bar/buttons/location.tsx` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1122#-NZ2QvTqEw3qjn2NqPfI:-NZ2RCtd0XpFY2LezVkv:bt0f1jb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e6ce5f763699798712524a26114d04217bf30c23/packages/geoview-core/src/core/components/nav-bar/buttons/location.tsx#L50)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Check if it zooms nearer the place. Zoom level 10 is a little bit far
</blockquote></details>

That was how it was done in the home button, I kept it that way for easy consistency.

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1122)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/nav-bar/buttons/location.tsx` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1122#-NZ2QvTqEw3qjn2NqPfI:-NZ2T9MAAvy9hDrYtaGW:bizyu5b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e6ce5f763699798712524a26114d04217bf30c23/packages/geoview-core/src/core/components/nav-bar/buttons/location.tsx#L50)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

That was how it was done in the home button, I kept it that way for easy consistency.
</blockquote></details>

Updated with zoom 13

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1122)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/nav-bar/buttons/location.tsx` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1122#-NZ2QvTqEw3qjn2NqPfI:-NZ2gSdJELilGkxbYcEI:b-7wt8xa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e6ce5f763699798712524a26114d04217bf30c23/packages/geoview-core/src/core/components/nav-bar/buttons/location.tsx#L50)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Updated with zoom 13
</blockquote></details>

Updated this and home with zoomToExtent

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
