### PR TITLE
2611 visibility refresh

### PR DESCRIPTION
**Pull request by MatthewMuehlhauserNRCan**
# Description

Added functionality to update the visibility and remove layers as necessary on language change. Also cleaned up the setLanguage method in the map-viewer.ts.

Fixes # 2611

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Turned off a layer and removed a child layer and then changed the language.

[GeoCore Custom](https://matthewmuehlhausernrcan.github.io/geoview/demos-navigator.html?config=./configs/navigator/27-geocore-custom.json)

# Checklist:

- [X] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [X] I have connected the issues(s) to this PR
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627)

### CODE REVIEW

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @jolevesq, and @MatthewMuehlhauserNRCan)

___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 941 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627#-ODCx-prCJTjpfKUImep:-ODCx-psA9UXfdC0ZTnx:bia63sq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9b8f0fcc5c5ef3f5b76f7cad4a7ab00d919ed48c/packages/geoview-core/src/geo/map/map-viewer.ts#L941)):*
> ```XML
>         // Reload just the Geocore Layers instead of the entire map
>         this.layer.reloadGeocoreLayers();
>         // this.reloadWithCurrentState();
> ```

Need to keep?
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 589 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627#-ODCvpd8AcesMK9TZx4n:-ODCvpd8AcesMK9TZx4o:btnbvng) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9b8f0fcc5c5ef3f5b76f7cad4a7ab00d919ed48c/packages/geoview-core/src/geo/layer/layer.ts#L589)):*
> ```XML
>   /**
>    * Refreshes GeoCore Layers
>    * @returns {void} A promise which resolves when done refreshing
> ```

No longer a promise - update comment

**Comment by MatthewMuehlhauserNRCan** [comment]
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 941 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627#-ODCx-prCJTjpfKUImep:-ODGklyRCsJNGiUnT2zH:b-2wi2ek) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9b8f0fcc5c5ef3f5b76f7cad4a7ab00d919ed48c/packages/geoview-core/src/geo/map/map-viewer.ts#L941)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Need to keep?
</blockquote></details>

I wasn't sure if wanted that as a reference there that it was tested? It is an alternative to the current solution, although it would refresh the entire map and not just the GeoCore layers. Which one is better would depend on if there are layers in the map that aren't GeoCore layers since they would be reloaded as well.

**Review by MatthewMuehlhauserNRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 589 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627#-ODCvpd8AcesMK9TZx4n:-ODGkjcf18IPQBwaqZ7h:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9b8f0fcc5c5ef3f5b76f7cad4a7ab00d919ed48c/packages/geoview-core/src/geo/layer/layer.ts#L589)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

No longer a promise - update comment
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 941 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627#-ODCx-prCJTjpfKUImep:-ODGpzQl7O8JOTmdbQM6:b-l4vs5o) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9b8f0fcc5c5ef3f5b76f7cad4a7ab00d919ed48c/packages/geoview-core/src/geo/map/map-viewer.ts#L941)):*
<details><summary><i>Previously, MatthewMuehlhauserNRCan wrote…</i></summary><blockquote>

I wasn't sure if wanted that as a reference there that it was tested? It is an alternative to the current solution, although it would refresh the entire map and not just the GeoCore layers. Which one is better would depend on if there are layers in the map that aren't GeoCore layers since they would be reloaded as well.
</blockquote></details>

If the relaod geocore works, we do not need the refresh state. It was another solution if the geocore switch as not working good.

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 941 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627#-ODCx-prCJTjpfKUImep:-ODGqABw5dtvPQtidBMK:b-f9fb9k) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9b8f0fcc5c5ef3f5b76f7cad4a7ab00d919ed48c/packages/geoview-core/src/geo/map/map-viewer.ts#L941)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If the relaod geocore works, we do not need the refresh state. It was another solution if the geocore switch as not working good.
</blockquote></details>

We can remove or put in comment that we reload instead of relaod with current state to not reload the whole map

**Review by DamonU2 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @DamonU2 and @MatthewMuehlhauserNRCan)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 660 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627#-ODMGGfJ23f5BG_ONElz:-ODMGGfJ23f5BG_ONEm-:b-9jo8wn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/438c3cd135e7384151c3162d7839ffb296d3ca16/packages/geoview-core/src/geo/layer/layer.ts#L660)):*
> ```XML
>           }
>           // Tried with onLayerLoaded, but didn't work as expected
>           this.onLayerAdded(setLayerVisibility);
> ```

I was curious why the onLayerLoaded couldn't be used here and I think I've figured it out. 2 reasons:

1- There's an issue with how the LayerApi registers the onLayerLoaded event which we have an inbound fix for in another big PR. I'd suggest to cherry pick the fix right away. I'll create a small PR for it. It'll save a lot of code here and remove the need for a 'whenThisThen'.

2- In the layers classes (old and new), in their onLoaded() function (in which they raise their loaded event), there's code that sets the visibility right *after* triggering the event. I believe this is because one can't set the visibility of a layer until it's in an *OpenLayers loaded state on the map* (iirc I've read a comment about something like this when doing the layers refactoring). If we want our own 'layerLoaded' event to be raised *after* we've set the visibility flag, which I think makes sense, we should switch these 2 lines order:

Switching those 2 lines will set the visibility as expected, by default using the initialSettings, and only then emit the event, which only then will be caught by the code here, re-adjusting the visibility to what we actually want. Otherwise, the visibility of the layer would get changed here (when caught by the onLayerLoaded), then *re-changed* in the screenshotted function to its initialSettings, which isn't what we want in this case.

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @DamonU2, @jolevesq, and @MatthewMuehlhauserNRCan)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 660 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627#-ODMGGfJ23f5BG_ONElz:-ODMKNafCBjauxzFEwTF:b-lg5jxq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/438c3cd135e7384151c3162d7839ffb296d3ca16/packages/geoview-core/src/geo/layer/layer.ts#L660)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I was curious why the onLayerLoaded couldn't be used here and I think I've figured it out. 2 reasons:

1- There's an issue with how the LayerApi registers the onLayerLoaded event which we have an inbound fix for in another big PR. I'd suggest to cherry pick the fix right away. I'll create a small PR for it. It'll save a lot of code here and remove the need for a 'whenThisThen'.

2- In the layers classes (old and new), in their onLoaded() function (in which they raise their loaded event), there's code that sets the visibility right *after* triggering the event. I believe this is because one can't set the visibility of a layer until it's in an *OpenLayers loaded state on the map* (iirc I've read a comment about something like this when doing the layers refactoring). If we want our own 'layerLoaded' event to be raised *after* we've set the visibility flag, which I think makes sense, we should switch these 2 lines order:

Switching those 2 lines will set the visibility as expected, by default using the initialSettings, and only then emit the event, which only then will be caught by the code here, re-adjusting the visibility to what we actually want. Otherwise, the visibility of the layer would get changed here (when caught by the onLayerLoaded), then *re-changed* in the screenshotted function to its initialSettings, which isn't what we want in this case.
</blockquote></details>

The hot fix PR is: https://github.com/Canadian-Geospatial-Platform/geoview/pull/2634

After these 2 points addressed. I believe the code here becomes the following and the `setLayerVisibility` function can be removed:



_Code snippet:_
```XML
// Catch the layer loaded event
this.onLayerLoaded((sender, event) => {
  const { visible } = originalMapOrderedLayerInfo.filter((info) => info.layerPath === event.layerPath)[0];
  event.layer?.setVisible(visible, path);
});
```

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @DamonU2, @jolevesq, and @MatthewMuehlhauserNRCan)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 660 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627#-ODMGGfJ23f5BG_ONElz:-ODMLPS_5EkGfUv95ieT:b8w3fjo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/438c3cd135e7384151c3162d7839ffb296d3ca16/packages/geoview-core/src/geo/layer/layer.ts#L660)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

The hot fix PR is: https://github.com/Canadian-Geospatial-Platform/geoview/pull/2634

After these 2 points addressed. I believe the code here becomes the following and the `setLayerVisibility` function can be removed:
</blockquote></details>

Rather, this, most likely:



_Code snippet:_
```XML
// Catch the layer loaded event
this.onLayerLoaded((sender, event) => {
  const { visible } = originalMapOrderedLayerInfo.filter((info) => info.layerPath === event.layerPath)[0];
  event.layer?.setVisible(visible, event.layerPath);
});
```

**Comment by MatthewMuehlhauserNRCan** [comment]
*[`packages/geoview-core/src/geo/layer/layer.ts` line 660 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627#-ODMGGfJ23f5BG_ONElz:-ODMnnvq4kLgy5cLECH2:b-u5dy5i) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/438c3cd135e7384151c3162d7839ffb296d3ca16/packages/geoview-core/src/geo/layer/layer.ts#L660)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Rather, this, most likely:
</blockquote></details>

I've switched to the onLayerLoaded after the rebase. It seems to work well and simplifies the code a lot. I did keep the callback function so I was able to remove the listener afterwards so they don't continue to build up. Although, they could potentially build up if someone continues to switch back and forth really fast. Maybe clearing the handlers array could make sure that doesn't happen, but I don't want to remove anything important that may also use this, although when I currently check, it is an empty array.

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2627)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MatthewMuehlhauserNRCan)

**Pull request merged**
