### PR TITLE
618-WMS metadata extent bug

### PR DESCRIPTION
**Pull request by ychoquet**
Added properties inheritance as specified in the WMS standard.
Added a catch on the methode that load the legend images. When there is an error, a null value is returned instead of a canvas.
Changed isDynamicLayerGroup to isMetadataLayerGroup to eliminate confusion with esri-dynamic.

- - -
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/633)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/633)* status: all files reviewed, 2 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/public/templates/test.html` line 40 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/633#-NGWXy5j9OaashSzpuzp:-NGWXy5j9OaashSzpuzq:b-5h1h6b) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5fe01bf9856b2a449aa09069d2cc9172bf4d7bf7/packages/geoview-core/public/templates/test.html#L40)):*
> ```HTML
>             'listOfLayerEntryConfig': [
>               {
>                 'layerId': 'hydro_network'
> ```

I try to the getLegend and it trigger an error. The getFeatureInfo always return null. Is it because of the output format (<Format>text/html</Format>)? I do noy see call in the network tab. Plus the service itself is problematic because it is http not hhtps. It will never work properly on the viewer. Are they aware?

58Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'. This request has been blocked; the content must be served over HTTPS.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 367 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/633#-NGW_iK67sF6MBgmZH38:-NGW_iK67sF6MBgmZH39:bi3mlm5) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5fe01bf9856b2a449aa09069d2cc9172bf4d7bf7/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L367)):*
> ```XML
>             layerEntryConfig.source.featureInfo = { queryable: !!layerCapabilities.queryable as boolean };
>           if (!layerEntryConfig.initialSettings) layerEntryConfig.initialSettings = {};
>           // ! TODO: The solution implemented in the following 4 lines is not right. scale and zoom are not the same things.
> ```

Do we have an issue for this and the other one in this PR?

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/633)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/test.html` line 40 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/633#-NGWXy5j9OaashSzpuzp:-NGWsVB4DAEv6qBC7Xn0:b1zholy) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5fe01bf9856b2a449aa09069d2cc9172bf4d7bf7/packages/geoview-core/public/templates/test.html#L40)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I try to the getLegend and it trigger an error. The getFeatureInfo always return null. Is it because of the output format (<Format>text/html</Format>)? I do noy see call in the network tab. Plus the service itself is problematic because it is http not hhtps. It will never work properly on the viewer. Are they aware?

58Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'. This request has been blocked; the content must be served over HTTPS.
</blockquote></details>

The getLegend error is normal. This is a desired viewer behavior implemented to warn the user that the service they are using has a problem. It comes from the NHN service endpoint. They have a buggy link on eight of their layers caused by the style inheritance rule as described in the OGC standard.

The getFeatureInfo on the NHN dataset returns nothing because none of their layers are queryable.

Regarding the https protocol, I'm not sure if they are aware of it. Do we have any documentation on this topic?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 367 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/633#-NGW_iK67sF6MBgmZH38:-NGWqP292a3EFVcmPhPw:bz2ib9o) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5fe01bf9856b2a449aa09069d2cc9172bf4d7bf7/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L367)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we have an issue for this and the other one in this PR?
</blockquote></details>

I reactivated the WMS #480 scale dependency issue. The solution I implemented was not good and prevented the wms service from displaying. The other problems were discovered when solving the scope bug. Do you want me to create an issue for them?

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/633)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

___
*[`packages/geoview-core/public/templates/test.html` line 40 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/633#-NGWXy5j9OaashSzpuzp:-NGWvuK_2Up4anV_PgOD:big2zxr) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5fe01bf9856b2a449aa09069d2cc9172bf4d7bf7/packages/geoview-core/public/templates/test.html#L40)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

The getLegend error is normal. This is a desired viewer behavior implemented to warn the user that the service they are using has a problem. It comes from the NHN service endpoint. They have a buggy link on eight of their layers caused by the style inheritance rule as described in the OGC standard.

The getFeatureInfo on the NHN dataset returns nothing because none of their layers are queryable.

Regarding the https protocol, I'm not sure if they are aware of it. Do we have any documentation on this topic?
</blockquote></details>

I talk to Pierre Tardif about the protocol error. The problems is nobody it updating this service anymore.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/633)* status: 1 of 10 files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/633)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/633#-:-NGX44e97mn1xcwtGNqE:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/633)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
