### PR TITLE
fix(data-table) DataTable now attempts to export the geometries for the EsriDynamic layers

### LINKED ISSUE #2545: [BUG] Data table download missing geometry for esriDynamic
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

At the moment, geometry for esriDynamic are only resqueted when the zoom in button is click to get extend. When we download the JSON for esriDynamic, geometry is undefined.

It is working for vector because geometry is part of the feature

### Expected Behavior

We should have the geometry for esriDynamic. We should use the same approach as getExtentFromFeatures for extent and implement a global solution.

### Steps To Reproduce

1. Go to https://canadian-geospatial-platform.github.io/geoview/public/demos-navigator.html?config=./configs/navigator/16-esri-dynamic.json
2. Open data table for Water....
3. Click Download and download as JSON
4. Open the file and see geometry is missing

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

DataTable now attempts to export the geometries for the EsriDynamic layers

Fixes #2545

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Hosted Nov 4th 16h30: https://alex-nrcan.github.io/geoview/demos-navigator.html?config=./configs/navigator/16-esri-dynamic.json

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2579)

### CODE REVIEW

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2579)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/core/components/data-table/json-export-button.tsx` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2579#-OAt9MU74--0LgW-OLx2:-OAt9MU74--0LgW-OLx3:bs3xn6n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bec1a1cc5783a93e4a8dc5844fac21c122b6169c/packages/geoview-core/src/core/components/data-table/json-export-button.tsx#L5)):*
> ```XML
> import _ from 'lodash';
> 
> import { Geometry, Point, Polygon, LineString, MultiPoint, MultiLineString } from 'ol/geom';
> ```

Need to add MultiPolygon?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2579)* status: all files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/core/components/data-table/json-export-button.tsx` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2579#-OAt7LIACKQEoaYb9QO8:-OAt7LIACKQEoaYb9QO9:b-50xtll) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bec1a1cc5783a93e4a8dc5844fac21c122b6169c/packages/geoview-core/src/core/components/data-table/json-export-button.tsx#L5)):*
> ```XML
> import _ from 'lodash';
> 
> import { Geometry, Point, Polygon, LineString, MultiPoint, MultiLineString } from 'ol/geom';
> ```

We should add multi polygons I think. This page has one outlier-ESRI-maxRecordCount.html
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 103 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2579#-OAwFWBO44inuEo1bQxJ:-OAwFWBO44inuEo1bQxK:bgmousp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bec1a1cc5783a93e4a8dc5844fac21c122b6169c/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L103)):*
> ```XML
>        * @returns A Promise of results of type TypeFeatureInfoEntryPartial
>        */
>       queryLayerEsriDynamic: (layerPath: string, objectIDs: number[]): Promise<TypeFeatureInfoEntryPartial[]> => {
> ```

Can we reuse this function in https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L1017 (same for gv-layers??? Is it overkill?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2579)* status: all files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 103 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2579#-OAwFWBO44inuEo1bQxJ:-OAwHIk69YZT2KBshMAM:b-v23okr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bec1a1cc5783a93e4a8dc5844fac21c122b6169c/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L103)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we reuse this function in https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L1017 (same for gv-layers??? Is it overkill?
</blockquote></details>

or the one from gv-util esriQueryRecordsByUrlObjectIds

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2579)* status: all files reviewed, 4 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/core/components/data-table/json-export-button.tsx` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2579#-OAt9MU74--0LgW-OLx2:-OAwd99H1mhFSTPcBgyk:b6bvwyx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bec1a1cc5783a93e4a8dc5844fac21c122b6169c/packages/geoview-core/src/core/components/data-table/json-export-button.tsx#L5)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Need to add MultiPolygon?
</blockquote></details>

Done. (other comment)
___
*[`packages/geoview-core/src/core/components/data-table/json-export-button.tsx` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2579#-OAt7LIACKQEoaYb9QO8:-OAwd9P0E8mdlC__3rR1:b-59zmac) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bec1a1cc5783a93e4a8dc5844fac21c122b6169c/packages/geoview-core/src/core/components/data-table/json-export-button.tsx#L5)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should add multi polygons I think. This page has one outlier-ESRI-maxRecordCount.html
</blockquote></details>

Yeah we probably should. I can try to do it in this PR, though I hope it won't make it too big (or dangerous impacts).
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 103 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2579#-OAwFWBO44inuEo1bQxJ:-OAwcrn99GG3uBsMQf4V:b-4rtlzy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bec1a1cc5783a93e4a8dc5844fac21c122b6169c/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L103)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

or the one from gv-util esriQueryRecordsByUrlObjectIds
</blockquote></details>

This function `queryLayerEsriDynamic` uses `esriQueryRecordsByUrlObjectIds` indeed. I had to create this function, because it was called by a UI component through a UI action.
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 831 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2579#-OAwHhm9CTv8l5nX0Pit:-OAwdNN_7wF7I6CyCPM5:bbr8ag6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bec1a1cc5783a93e4a8dc5844fac21c122b6169c/packages/geoview-core/src/geo/map/map-schema-types.ts#L831)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

hum, for style do we really need the Multi? Style will be the same for point or multipoint. If we really need this we need multi point and multi polygon as well.
</blockquote></details>

I think this is used more than just for style purposes. It's used to actually create geometries. See EsriDynamic.getAllFeatureInfo() for example.

**Review by jolevesq — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2579)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2)

**Pull request merged**
