### PR TITLE
feat(geojson) Add support for geojson

### LINKED ISSUE #22: Add support for GeoJSON
Add support for adding geometries from GeoJSON format.

For the moment, all layers are in the same class. May be a good idea to have a parent class and every type of layers will inherits from that class. Having GeoJSON in is own class will be a good start. For this first phase we need to
[ ] Show GeoJSON on map
[ ] Apply style

### PR DESCRIPTION
**Pull request by yass0016**
Closes #22

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 8 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46)* status: 8 of 14 files reviewed, 20 unresolved discussions (waiting on @yass0016)

___
*[public/index.html, line 110 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4Aaix14UlDPPzvcsV:-MS4Aaiy4UqBbJEBQOmU:b-dwv19c) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/public/index.html#L110)):*
> ```HTML
>             });
> 
>             var addGeoJSONButton = document.getElementById('add-geojson');
> ```

Can you just add a comment to explain what you are doing?
___
*[public/index.html, line 112 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4AiUB9Q9ZNTlpQINA:-MS4AiUB9Q9ZNTlpQINB:bcxmd6p) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/public/index.html#L112)):*
> ```HTML
>             var addGeoJSONButton = document.getElementById('add-geojson');
>             addGeoJSONButton.addEventListener('click', function (e) {
>                 cgpv.api.emit('geojson/add', null, {
> ```

Should it be layer/add then from property we have url and type + optional entries array. This way we can add any type of layer
___
*[src/api/api.ts, line 21 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4B5vE9OMoR8ulUIsZ:-MS4B5vE9OMoR8ulUIs_:b-lbu0h) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/api/api.ts#L21)):*
> ```XML
>      * Event triggered when adding a new geojson layer
>      */
>     EVENT_GEOJSON_ADD: 'geojson/add',
> ```

Same comment, EVENT_LAYER_ADD?
___
*[src/common/layers/esri-dynamic.ts, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4EHuu87QtMqO_GLI5:-MS4EHuu87QtMqO_GLI6:b-cb5prp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/esri-dynamic.ts#L7)):*
> ```XML
> /**
>  * a class to add esri dynamic layer
>  */
> ```

Can you add

@export
@class esri-dynamic to class comment. Can you do it for all new class
___
*[src/common/layers/esri-dynamic.ts, line 16 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4Bs2f4B-Uj526wsSv:-MS4Bs2g3iH1HLT7ANk9:bd4blqh) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/esri-dynamic.ts#L16)):*
> ```XML
>      * @returns {feat is object}
>      */
>     addEsriDynamic(map: any, layer: LayerConfig) {
> ```

Can you use leaflet type map instead of any? I did this fast and didn't bother at that time but it would be nice to remove all any reference if a type exist
___
*[src/common/layers/esri-feature.ts, line 16 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4CJe2ACRp6QthtRYO:-MS4CJe2ACRp6QthtRYP:bfe64xy) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/esri-feature.ts#L16)):*
> ```XML
>      * @returns {feat is object}
>      */
>     addEsriFeature(map: any, layer: LayerConfig) {
> ```

Can you use leaflet type map instead of any?
___
*[src/common/layers/geojson.ts, line 16 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4EW-4DxVGNgUUErBM:-MS4EW-4DxVGNgUUErBN:b-37kf8u) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L16)):*
> ```XML
>     private map: Map;
> 
>     layers: L.GeoJSON[] = [];
> ```

Should layer reference be deal at super class level?
___
*[src/common/layers/geojson.ts, line 20 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4D-uD-7KEgUc2IkXL:-MS4D-uD-7KEgUc2IkXM:b-dnukps) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L20)):*
> ```XML
>     /**
>      * initialize the geojson url and listens to add events from outside
>      * @param map a reference to the map
> ```

The object type should be in bracket: {Map}
___
*[src/common/layers/geojson.ts, line 28 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4CRXy-TKH8DhvfsIX:-MS4CRXy-TKH8DhvfsIY:b-823gpj) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L28)):*
> ```XML
> 
>         // will be used to listen to outside events to add json
>         api.on('geojson/add', (payload) => {
> ```

Should we have this listener on the super class (layer/add)
___
*[src/common/layers/geojson.ts, line 35 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4Csr5BE3WAkSmPpiz:-MS4Csr5BE3WAkSmPpj-:b-fln06j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L35)):*
> ```XML
> 
>     /**
>      * Load geojosn from a file and then send it as a string using the callback
> ```

Typo in geojson
___
*[src/common/layers/geojson.ts, line 36 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4DDRWBN5tlNZKpYQx:-MS4DDRWBN5tlNZKpYQy:bdnnzjd) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L36)):*
> ```XML
>     /**
>      * Load geojosn from a file and then send it as a string using the callback
>      * @param url the file url
> ```

param type in bracket {string} url ... Same for callback
___
*[src/common/layers/geojson.ts, line 53 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4CigO8zzw-FQXYZE7:-MS4CigO8zzw-FQXYZE8:bi198za) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L53)):*
> ```XML
>     /**
>      * Add a geojson to the map
>      */
> ```

Can you add url param in doc
___
*[src/common/layers/geojson.ts, line 55 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4Corr5UY2y_b2LxaE:-MS4Corr5UY2y_b2LxaF:b-6oh2ev) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L55)):*
> ```XML
>      */
>     add(url: string): void {
>         this.load(url, (data) => {
> ```

Can you add variable type
___
*[src/common/layers/geojson.ts, line 62 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4DutzBwZZuyAdW7UY:-MS4DutzBwZZuyAdW7UZ:b-dgopoj) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L62)):*
> ```XML
>             // add the geojson to the map
>             const geojson = L.geoJSON(featureCollection, {
>                 // add styling
> ```

Put a TODO comment to say we will create a class to style element. It may get info from theming
___
*[src/common/layers/geojson.ts, line 87 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4DTNpB5zc4XdEsRll:-MS4DTNpB5zc4XdEsRlm:bkvvjee) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L87)):*
> ```XML
>             geojson.addTo(this.map);
> 
>             this.layers.push(geojson);
> ```

You use for events? Should it be on super class with subtype?
___
*[src/common/layers/geojson.ts, line 93 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4D_El5Qxt_VGyOPAn:-MS4D_El5Qxt_VGyOPAo:bs66r4) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L93)):*
> ```XML
>     /**
>      * Remove a geojson layer from the map
>      * @param index the index of the layer to be removed
> ```

{number} index
___
*[src/common/layers/geojson.ts, line 96 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4DfYR7DZrQXBgwjI5:-MS4DfYS-qUbUhJJKMVv:b1siqfc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L96)):*
> ```XML
>      */
>     remove(index: number): void {
>         this.layers[index].removeFrom(this.map);
> ```

Would be better to assign id to all layer and find the layer by id to remove. This function should be on super class
___
*[src/common/layers/layer.ts, line 2 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4EiXQC41Ndn11zcvJ:-MS4EiXR544V53Y2ZNNp:brj6dbc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/layer.ts#L2)):*
> ```XML
> // TODO: look at a bundler for esri-leaflet: https://github.com/esri/esri-leaflet-bundler
> import 'esri-leaflet-renderers';
> ```

Is this import still needed?
___
*[src/common/layers/layer.ts, line 4 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4Ew5V7cMcM-L6IAeN:-MS4Ew5V7cMcM-L6IAeO:bf7l39z) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/layer.ts#L4)):*
> ```XML
> import 'esri-leaflet-renderers';
> 
> export interface LayerConfig {
> ```

Can you add a bloc of comment for the interface
___
*[src/components/map/map.tsx, line 89 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4Fl4R0h6tBMLACM-7:-MS4Fl4R0h6tBMLACM-8:b-w08wbt) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5604ba17d35e097a131439bbde14b34b67c3504f/src/components/map/map.tsx#L89)):*
> ```XML
> 
>                 // TODO: put this a t the right place. This is temporary to show we can add different layer type to the map
>                 const layer = new Layer();
> ```

Can you add to the TODO, need to refactor, will be part of #45 where we will create a configuration class to read, validate and execute the configuration. We will remove the map layer add from map.tsx

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46)* status: 4 of 16 files reviewed, 20 unresolved discussions (waiting on @Class, @export, and @jolevesq)

___
*[public/index.html, line 110 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4Aaix14UlDPPzvcsV:-MS4I_p4AIen9SqtOYo6:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/public/index.html#L110)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you just add a comment to explain what you are doing?
</blockquote></details>

Done.
___
*[public/index.html, line 112 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4AiUB9Q9ZNTlpQINA:-MS4IdJb4Trf3gpAauB2:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/public/index.html#L112)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should it be layer/add then from property we have url and type + optional entries array. This way we can add any type of layer
</blockquote></details>

Done.
___
*[src/api/api.ts, line 21 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4B5vE9OMoR8ulUIsZ:-MS4IerZBk1NzvlpbUnN:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/api/api.ts#L21)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same comment, EVENT_LAYER_ADD?
</blockquote></details>

Done.
___
*[src/common/layers/esri-dynamic.ts, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4EHuu87QtMqO_GLI5:-MS4IhIK0H1j4iJvBM0l:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/esri-dynamic.ts#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add

@export
@class esri-dynamic to class comment. Can you do it for all new class


</blockquote></details>

Done.
___
*[src/common/layers/esri-dynamic.ts, line 16 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4Bs2f4B-Uj526wsSv:-MS4Ikbo8KGByLTCkiSM:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/esri-dynamic.ts#L16)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you use leaflet type map instead of any? I did this fast and didn't bother at that time but it would be nice to remove all any reference if a type exist
</blockquote></details>

Done.
___
*[src/common/layers/esri-feature.ts, line 16 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4CJe2ACRp6QthtRYO:-MS4Ip5ZE5_oVd8LQU6a:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/esri-feature.ts#L16)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you use leaflet type map instead of any?
</blockquote></details>

Done.
___
*[src/common/layers/geojson.ts, line 16 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4EW-4DxVGNgUUErBM:-MS4Ir-38YL5cBQLz8Gi:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L16)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should layer reference be deal at super class level?
</blockquote></details>

Done.
___
*[src/common/layers/geojson.ts, line 20 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4D-uD-7KEgUc2IkXL:-MS4NiXl42xUHz_u6pm1:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L20)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The object type should be in bracket: {Map}
</blockquote></details>

Done.
___
*[src/common/layers/geojson.ts, line 28 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4CRXy-TKH8DhvfsIX:-MS4MntV2FnIt2rfGHIH:b-qh1pqp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L28)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we have this listener on the super class (layer/add)
</blockquote></details>

How would we call "add" from the GeoJSON class in the super class?
___
*[src/common/layers/geojson.ts, line 35 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4Csr5BE3WAkSmPpiz:-MS4Mkqb2961gDv_NP-w:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L35)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo in geojson
</blockquote></details>

Done.
___
*[src/common/layers/geojson.ts, line 36 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4DDRWBN5tlNZKpYQx:-MS4MalXBi8fuG-IIc4L:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L36)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

param type in bracket {string} url ... Same for callback
</blockquote></details>

Done.
___
*[src/common/layers/geojson.ts, line 53 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4CigO8zzw-FQXYZE7:-MS4M_Vd0Tx-9uGCMmAP:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L53)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add url param in doc
</blockquote></details>

Done.
___
*[src/common/layers/geojson.ts, line 55 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4Corr5UY2y_b2LxaE:-MS4MP7o9KvQi5iJR_--:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L55)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add variable type
</blockquote></details>

Done.
___
*[src/common/layers/geojson.ts, line 62 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4DutzBwZZuyAdW7UY:-MS4LB_11x0GlGY5CaAp:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L62)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put a TODO comment to say we will create a class to style element. It may get info from theming
</blockquote></details>

Done.
___
*[src/common/layers/geojson.ts, line 87 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4DTNpB5zc4XdEsRll:-MS4LF7u1U2D6lOpaJiw:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L87)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You use for events? Should it be on super class with subtype?
</blockquote></details>

Done.
___
*[src/common/layers/geojson.ts, line 93 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4D_El5Qxt_VGyOPAn:-MS4KoWu9INzrw3_chMF:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L93)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

{number} index
</blockquote></details>

Done.
___
*[src/common/layers/geojson.ts, line 96 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4DfYR7DZrQXBgwjI5:-MS4Q0ti4ebPWx7cyL5r:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L96)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Would be better to assign id to all layer and find the layer by id to remove. This function should be on super class
</blockquote></details>

Done.
___
*[src/common/layers/layer.ts, line 2 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4EiXQC41Ndn11zcvJ:-MS4M993-7FqTRJpI9Wh:b66p2r7) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/layer.ts#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this import still needed?
</blockquote></details>

I think we do
___
*[src/common/layers/layer.ts, line 4 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4Ew5V7cMcM-L6IAeN:-MS4LbHG7T3AR2trZhJ4:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/layer.ts#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add a bloc of comment for the interface
</blockquote></details>

Done.
___
*[src/components/map/map.tsx, line 89 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4Fl4R0h6tBMLACM-7:-MS4Lx5e6XrdgcF_mxGa:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5604ba17d35e097a131439bbde14b34b67c3504f/src/components/map/map.tsx#L89)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add to the TODO, need to refactor, will be part of #45 where we will create a configuration class to read, validate and execute the configuration. We will remove the map layer add from map.tsx
</blockquote></details>

Done.

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46)* status: 4 of 16 files reviewed, 20 unresolved discussions (waiting on @Class, @export, and @jolevesq)

___
*[src/common/layers/geojson.ts, line 28 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS4CRXy-TKH8DhvfsIX:-MS8hyK2DcX4OQJP1htO:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9060b18d3bb3ed2e96a19001999a705824c4f789/src/common/layers/geojson.ts#L28)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

How would we call "add" from the GeoJSON class in the super class?
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46)* status: 10 of 16 files reviewed, 6 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[src/common/layers/geojson.ts, line 72 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS8kreoDfJaL09dgFy3:-MS8kreoDfJaL09dgFy4:byzuvn2) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e9714d71db8fd28c7feeee50d66df5226804e585/src/common/layers/geojson.ts#L72)):*
> ```XML
>             layers.push({
>                 // TODO generate an ID with better format
>                 id: new Date().getTime().toString(),
> ```

Can you create an issue for this? We should reuse the same function across all layer type. Maybe we should add a parameter like name to all layer so we can from name get the id. Name will be added to config info. The same way we can remove from name and or id. If 2 layer share same name, remove both. This can part of the issue you will create.
___
*[src/common/layers/layer.ts, line 31 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS8lTIh3YLe76tn1fau:-MS8lTIh3YLe76tn1fav:b-tqnxrj) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e9714d71db8fd28c7feeee50d66df5226804e585/src/common/layers/layer.ts#L31)):*
> ```XML
>     entries: string;
> }
> ```

Can you add a block of comment for this interface
___
*[src/common/layers/layer.ts, line 66 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS8liCw2ziAhyf7fpNp:-MS8liCw2ziAhyf7fpNq:b-pd05yp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e9714d71db8fd28c7feeee50d66df5226804e585/src/common/layers/layer.ts#L66)):*
> ```XML
> 
>     /**
>      * initialize the geojson url and listens to add events from outside
> ```

It should be another description, it is not only for geojson
___
*[src/common/layers/layer.ts, line 79 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS8lpf7-9KsNApz5NCB:-MS8lpf7-9KsNApz5NCC:b7va01v) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e9714d71db8fd28c7feeee50d66df5226804e585/src/common/layers/layer.ts#L79)):*
> ```XML
>         // listen to outside events to add layers
>         api.on(EVENT_NAMES.EVENT_LAYER_ADD, (payload) => {
>             if (payload.type === 'geojson') {
> ```

Should we have this event handler for other layer type as well?
___
*[src/common/layers/layer.ts, line 88 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS8lxz42biJEUaiq9ly:-MS8lxz42biJEUaiq9lz:b-9krzuv) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e9714d71db8fd28c7feeee50d66df5226804e585/src/common/layers/layer.ts#L88)):*
> ```XML
>         api.on(EVENT_NAMES.EVENT_REMOVE_LAYER, (payload) => {
>             // remove layer from outside
>             this.remove(payload.id);
> ```

As part of the issue you will create, can you add a remove button to remove the geojson you add from the add button?
___
*[src/components/map/map.tsx, line 86 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS8mELn3iz8A37cJiHT:-MS8mELn3iz8A37cJiHU:b-7n5vtp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e9714d71db8fd28c7feeee50d66df5226804e585/src/components/map/map.tsx#L86)):*
> ```XML
>             maxBounds={mapOptions.maxBounds}
>             whenCreated={(cgpMap) => {
>                 // initialize the geojson object
> ```

Should be layer object

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46)* status: 10 of 16 files reviewed, 6 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[src/common/layers/layer.ts, line 31 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS8lTIh3YLe76tn1fau:-MS8nFi0DOKKj7Fojad3:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e9714d71db8fd28c7feeee50d66df5226804e585/src/common/layers/layer.ts#L31)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add a block of comment for this interface
</blockquote></details>

Done.
___
*[src/common/layers/layer.ts, line 66 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS8liCw2ziAhyf7fpNp:-MS8nWV067Dp-m9SBlIy:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e9714d71db8fd28c7feeee50d66df5226804e585/src/common/layers/layer.ts#L66)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It should be another description, it is not only for geojson
</blockquote></details>

Done.
___
*[src/common/layers/layer.ts, line 79 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS8lpf7-9KsNApz5NCB:-MS8nxokEUYX15bIDFFe:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e9714d71db8fd28c7feeee50d66df5226804e585/src/common/layers/layer.ts#L79)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we have this event handler for other layer type as well?
</blockquote></details>

Done.
___
*[src/components/map/map.tsx, line 86 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS8mELn3iz8A37cJiHT:-MS8o93-EdGrnPkXWs1F:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e9714d71db8fd28c7feeee50d66df5226804e585/src/components/map/map.tsx#L86)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should be layer object
</blockquote></details>

Done.

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46)* status: 10 of 16 files reviewed, 6 unresolved discussions (waiting on @jolevesq)

___
*[src/common/layers/geojson.ts, line 72 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS8kreoDfJaL09dgFy3:-MS8rV4V5oMpLHw_6qtQ:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e9714d71db8fd28c7feeee50d66df5226804e585/src/common/layers/geojson.ts#L72)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you create an issue for this? We should reuse the same function across all layer type. Maybe we should add a parameter like name to all layer so we can from name get the id. Name will be added to config info. The same way we can remove from name and or id. If 2 layer share same name, remove both. This can part of the issue you will create.
</blockquote></details>

Done.
___
*[src/common/layers/layer.ts, line 88 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-MS8lxz42biJEUaiq9ly:-MS8rTAt08FeV5NaPyvK:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e9714d71db8fd28c7feeee50d66df5226804e585/src/common/layers/layer.ts#L88)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

As part of the issue you will create, can you add a remove button to remove the geojson you add from the add button?
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 12 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46#-:-MS90mHR2ttJ73Zbu9Vk:bg7igkv)* status: 13 of 16 files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 12 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/46)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
