### PR TITLE
1930-REFACTOR_geoviewLayer_using_layerPath

### LINKED ISSUE #1930: [REFACTOR] getGeoviewLayer using layerPath
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### Issue description

There are at least two methods in the viewer for obtaining the Geoview layer using the layer path. In addition, one of them uses a property to encapsulate the layer path and uses this encapsulated property in other methods such as getOpacity, setOpacity, getVisible, setVisible and so on. This approach is ambiguous and obscures the actual use of the layer path.

### Implementation

We want to eliminate this dangerous behavior from our code for a single method that doesn't hide the use of the layer path.

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

There are at least two methods in the viewer for obtaining the Geoview layer using the layer path. In addition, one of them uses a property to encapsulate the layer path and uses this encapsulated property in other methods such as getOpacity, setOpacity, getVisible, setVisible and so on. This approach is ambiguous and obscures the actual use of the layer path. We want to eliminate this dangerous behavior from our code for a single method that doesn't hide the use of the layer path.

Fixes #1930

## Type of change

- [x] Refactor (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using Chrome Devtools and the geoview templates.

__Deploy URL__: https://ychoquet.github.io/GeoView/index.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938)

### CODE REVIEW

**Review by DamonU2 — APPROVED** [review]
> Reviewed 4 of 22 files at r2, 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 4 of 22 files at r2, 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938)* status: all files reviewed, 7 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/public/templates/layers-temporal.html` line 235 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938#-Ntqpp1V4CitWOn2ruub:-Ntqpp1V4CitWOn2ruuc:bqzr95w) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5857b2a6db93e1b6e61134c32f4484114f5497c1/packages/geoview-core/public/templates/layers-temporal.html#L235)):*
> ```HTML
>             cgpv.api.maps['LYR1'].layer
>               .geoviewLayer('wmsLYR1-Root/wmsLYR1-Group1/wmsLYR1-Group2/wmsLYR1-Group3/RADAR_1KM_RSNO.ending')
>               .getTemporalDimension(),
> ```

To make this work we need some redundancy for the moment...
```
cgpv.api.maps['LYR1'].layer.geoviewLayer('wmsLYR1-Root/wmsLYR1-Group1/wmsLYR1-Group2/wmsLYR1-Group3/RADAR_1KM_RSNO.ending').getTemporalDimension('wmsLYR1-Root/wmsLYR1-Group1/wmsLYR1-Group2/wmsLYR1-Group3/RADAR_1KM_RSNO.ending')
```
OR
```
cgpv.api.maps['LYR1'].layer.geoviewLayers['wmsLYR1-Root'].listOfLayerEntryConfig[0].listOfLayerEntryConfig[0].listOfLayerEntryConfig[0].geoviewLayerInstance.getTemporalDimension('wmsLYR1-Root/wmsLYR1-Group1/wmsLYR1-Group2/wmsLYR1-Group3/RADAR_1KM_RSNO.ending')
```
___
*[`packages/geoview-core/public/templates/layers/esri-dynamic.html` line 1102 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938#-Ntqt-mtD6Cwo9dK9-pH:-Ntqt-mtD6Cwo9dK9-pI:b-dmyy9w) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5857b2a6db93e1b6e61134c32f4484114f5497c1/packages/geoview-core/public/templates/layers/esri-dynamic.html#L1102)):*
> ```HTML
>           listenToLegendLayerSetChanges('HLYR4-state', 'LYR4');
> 
>           if (cgpv.api.maps.LYR2.layer.registeredLayers['historical-flood/0'].layerStatus === 'loaded') {
> ```

When we arrive here, the layer status is processing so it never goes in the if statement
___
*[`packages/geoview-core/public/templates/layers/esri-dynamic.html` line 1123 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938#-NtqwK422GbVbOflhZnW:-NtqwK43BIf0TOZaiS1S:b-ya81ng) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5857b2a6db93e1b6e61134c32f4484114f5497c1/packages/geoview-core/public/templates/layers/esri-dynamic.html#L1123)):*
> ```HTML
>           }
> 
>           if (cgpv.api.maps.LYR3.layer.registeredLayers['historical-flood/0'].layerStatus === 'loaded') {
> ```

Same as above
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts` line 212 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938#-NtqyKspAXYLeAU2fGMC:-NtqyKspAXYLeAU2fGMD:btu71qc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5857b2a6db93e1b6e61134c32f4484114f5497c1/packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts#L212)):*
> ```XML
>         const newValue = `${new Date(values[0]).toISOString().slice(0, new Date(values[0]).toISOString().length - 5)}Z`;
>         const filter = `${field}=date '${newValue}'`;
>         (api.maps[mapId].layer.geoviewLayer(layerPath) as WMS).applyViewFilter(layerPath, filter);
> ```

For the moment it is ok but there is some kind of duplication here.... layer.geoviewLayer(layerpath... applyFilter(layerPath). We have layer path twice. The applyFilter and other methods should be on geoviewLayer instance. Once we access the instance no need for layer path anymore has the instance knows and the value/function is attach to the instance.
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 265 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938#-NtqzqJtDQHBJvJvKNsL:-NtqzqJuCJCdCkTpONBK:b-95q7nd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5857b2a6db93e1b6e61134c32f4484114f5497c1/packages/geoview-core/src/geo/layer/layer.ts#L265)):*
> ```XML
>   geoviewLayer(layerPath: string): AbstractGeoViewLayer {
>     // The first element of the layerPath is the geoviewLayerId
>     return this.geoviewLayers[layerPath.split('/')[0]];
> ```

More thinking for later but this should sent back the geoviewInstance directly and functions - attributes are attach to it. It can be a layer or group as group has functions and attributes.
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 689 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938#-Ntr-Bgi0cJYoV3bSuMN:-Ntr-Bgi0cJYoV3bSuMO:b-3s0fsi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5857b2a6db93e1b6e61134c32f4484114f5497c1/packages/geoview-core/src/geo/layer/layer.ts#L689)):*
> ```XML
>     this.removeHighlightLayer();
>     this.highlightedLayer = { layerPath, originalOpacity: this.geoviewLayer(layerPath).getOpacity(layerPath) };
>     this.geoviewLayer(layerPath).setOpacity(1, layerPath);
> ```

Same comment as above, we should be able to get to the instance we want and call function without repeating the layerPath. This will need some refactoring...
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1003 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938#-Ntr4a0L0JxVY0nGgCDx:-Ntr4a0L0JxVY0nGgCDy:b-miwfna) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5857b2a6db93e1b6e61134c32f4484114f5497c1/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1003)):*
> ```XML
>    * @returns {number | undefined} The opacity of the layer.
>    */
>   getOpacity(layerPath: string): number | undefined {
> ```

Consideration... we need to expose these getter and setter from the store. If not, modification to layer does not reflect in UI. 

getOpacity, we ask layer path in parameter, for the set, layer path is also required but in second. This is confusing

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938)* status: 5 of 23 files reviewed, 7 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/public/templates/layers-temporal.html` line 235 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938#-Ntqpp1V4CitWOn2ruub:-NtrAS7N8z6125UVLUHO:bk7id3q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5857b2a6db93e1b6e61134c32f4484114f5497c1/packages/geoview-core/public/templates/layers-temporal.html#L235)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

To make this work we need some redundancy for the moment...
```
cgpv.api.maps['LYR1'].layer.geoviewLayer('wmsLYR1-Root/wmsLYR1-Group1/wmsLYR1-Group2/wmsLYR1-Group3/RADAR_1KM_RSNO.ending').getTemporalDimension('wmsLYR1-Root/wmsLYR1-Group1/wmsLYR1-Group2/wmsLYR1-Group3/RADAR_1KM_RSNO.ending')
```
OR
```
cgpv.api.maps['LYR1'].layer.geoviewLayers['wmsLYR1-Root'].listOfLayerEntryConfig[0].listOfLayerEntryConfig[0].listOfLayerEntryConfig[0].geoviewLayerInstance.getTemporalDimension('wmsLYR1-Root/wmsLYR1-Group1/wmsLYR1-Group2/wmsLYR1-Group3/RADAR_1KM_RSNO.ending')
```
</blockquote></details>

First of all, let me say that you've found a bug in my PR. After verification, I realize that this file was not modifyed properly. The getTemporal dimension after this PR must have a layerPath as a parameter. I made the correction.

With the new code resulting from this PR, the easyest way to get the temporal dimension is with the first snippet you gave. The geoviewLayer method of the Layer class accepts a geoview layer Id or a layer path. Then, if the layer path is in a variable, the line is as simple as :
```
temporalDimension = cgpv.api.maps['LYR1'].layer.geoviewLayer(layerPath).getTemporalDimension(layerPath);
```
You will never have to travel the layerPath through the listOfLayerEntryConfig. The getTemporalDimension of the geoview layer does the job.

Now, one issue in zenhub propose to move to the sub layers all the methods related to a layer path that are attached to the geoview layers in the current version. Those methods are getVisible, setVisible, getOpacity, setOpacity, getTemporalDimensionthat etc. So, in the futur, the syntax will be simpler.
___
*[`packages/geoview-core/public/templates/layers/esri-dynamic.html` line 1102 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938#-Ntqt-mtD6Cwo9dK9-pH:-NtrIEvmChId1dhd73gX:b5dtuyj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5857b2a6db93e1b6e61134c32f4484114f5497c1/packages/geoview-core/public/templates/layers/esri-dynamic.html#L1102)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

When we arrive here, the layer status is processing so it never goes in the if statement
</blockquote></details>

Made the correction.
___
*[`packages/geoview-core/public/templates/layers/esri-dynamic.html` line 1123 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938#-NtqwK422GbVbOflhZnW:-Ntredae5h98gVMKHkSm:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5857b2a6db93e1b6e61134c32f4484114f5497c1/packages/geoview-core/public/templates/layers/esri-dynamic.html#L1123)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts` line 212 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938#-NtqyKspAXYLeAU2fGMC:-NtrdEFpA1LjHun-fG-r:bhnxu5j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5857b2a6db93e1b6e61134c32f4484114f5497c1/packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts#L212)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

For the moment it is ok but there is some kind of duplication here.... layer.geoviewLayer(layerpath... applyFilter(layerPath). We have layer path twice. The applyFilter and other methods should be on geoviewLayer instance. Once we access the instance no need for layer path anymore has the instance knows and the value/function is attach to the instance.
</blockquote></details>

We are supposed to have an issue to move methods attached to the geoview layer to the sub layer to eliminate this duplication as I mentioned above.
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 265 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938#-NtqzqJtDQHBJvJvKNsL:-Ntre0qJ7aPZkkmNmeMG:bdrhftw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5857b2a6db93e1b6e61134c32f4484114f5497c1/packages/geoview-core/src/geo/layer/layer.ts#L265)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

More thinking for later but this should sent back the geoviewInstance directly and functions - attributes are attach to it. It can be a layer or group as group has functions and attributes.
</blockquote></details>

All these comments are related to the geoview layer and sub layers getter refactoring using the layerPath.
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 689 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938#-Ntr-Bgi0cJYoV3bSuMN:-NtreEeqA81ajFiFKkdg:b-fvtltw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5857b2a6db93e1b6e61134c32f4484114f5497c1/packages/geoview-core/src/geo/layer/layer.ts#L689)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same comment as above, we should be able to get to the instance we want and call function without repeating the layerPath. This will need some refactoring...
</blockquote></details>

Same answer as above
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1003 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938#-Ntr4a0L0JxVY0nGgCDx:-NtreSBe2V3asWtG4L0G:b-bdcysq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5857b2a6db93e1b6e61134c32f4484114f5497c1/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1003)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Consideration... we need to expose these getter and setter from the store. If not, modification to layer does not reflect in UI. 

getOpacity, we ask layer path in parameter, for the set, layer path is also required but in second. This is confusing
</blockquote></details>

Need to be corrected in the getter for layers refactoring.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 17 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938)* status: 22 of 23 files reviewed, 6 unresolved discussions (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/public/templates/layers-temporal.html` line 233 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938#-Ntu_iaJ4pJAPReiCA5x:-Ntu_iaJ4pJAPReiCA5y:b64t1t1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2318604d8c1c9f0a9a0b93223ff09c69e5343dc5/packages/geoview-core/public/templates/layers-temporal.html#L233)):*
> ```HTML
>             cgpv.api.maps['LYR1'].layer
>               .geoviewLayer('wmsLYR1-Root/wmsLYR1-Group1/wmsLYR1-Group2/wmsLYR1-Group3/RADAR_1KM_RSNO.ending')
>               .getTemporalDimension(),
> ```

Still miss layerpath here....

Plus we have synch problem as the layer temporal dimension is not set when the function enter...  The function on layers must be async and only call when layers is loaded. The new way of doing with config prior to layers will make this more clear as most of processing will be done before so when layer is created, it should be quick to get the object.

In the mean time we can add a TODO: solve async issue and wrapped the call in a setTimeout

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938)* status: 13 of 23 files reviewed, 6 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/public/templates/layers-temporal.html` line 233 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938#-Ntu_iaJ4pJAPReiCA5x:-Ntvuo-v1IVqN7F2FMLp:bn5at20) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2318604d8c1c9f0a9a0b93223ff09c69e5343dc5/packages/geoview-core/public/templates/layers-temporal.html#L233)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Still miss layerpath here....

Plus we have synch problem as the layer temporal dimension is not set when the function enter...  The function on layers must be async and only call when layers is loaded. The new way of doing with config prior to layers will make this more clear as most of processing will be done before so when layer is created, it should be quick to get the object.

In the mean time we can add a TODO: solve async issue and wrapped the call in a setTimeout
</blockquote></details>

I made the correction to the layers that did not use the second callback when the map is loaded tosolve the template load issues. Also corrected the layer load errors caused by a bad metadataAccessPath to metadata.json in raw-feature-info.html

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 11 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1938)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Pull request merged**
