### PR TITLE
fix(slider, demo): Fix SLider interval and Swiper demo

### LINKED ISSUE #2229: [BUG] Time slider right anchor won't be respected when using the "Forward" button
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using the ["Package time slider" config](https://canadian-geospatial-platform.github.io/geoview/public/demos-navigator.html?config=./configs/navigator/10-package-time-slider.json)

In the "Time Slider" tab, use the first layer of the list: "Historical Flood Events". Move the right anchor towards the right just a bit. eg. past the "1779-01-01" tick mark: 

image

Then use the "Forward" button:

image

It brings back the right anchor to its original position. It seems the initial preset range overwrites the one manually set:

image

If you click once again on the "Forward" button, the range will move towards like expected but using the default preset range:

image

Where ever you position any of the anchors and use the "Forward" or "Back" buttons on this layer, the preset range will systematically overwrite the range you set.

### Expected Behavior

Range you manually set should be respected when using the "Forward" and "Back" buttons.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #2229

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #2229 and swiper demo

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Hosted June 26th, 10 am
- https://jolevesq.github.io/geoview/demos-navigator.html?config=./configs/navigator/10-package-time-slider.json
- https://jolevesq.github.io/geoview/package-swiper.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2310)

### CODE REVIEW

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2310)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 181 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2310#-O0JwZU47Onji9vjEWyq:-O0JwZU47Onji9vjEWyr:b4v4i58) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4374fe2e54ba4dc001141a09b878a78f5178c4ce/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L181)):*
> ```XML
>             // ESRI Feature layer response will have exceededTransferLimit property set to true if there are more features
>             // GV Some layers will return XML, skip
>             if (xhr.responseText.search("<?xml version='1.0'") === -1 && JSON.parse(xhr.responseText).exceededTransferLimit) {
> ```

Maybe just check for `<?xml` or does it have to be xml version 1.0?
___
*[`packages/geoview-time-slider/src/time-slider.tsx` line 176 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2310#-O0JwOsi4pZ8XmSxRpQc:-O0JwOsj5cBgfUeuszAL:b-cf38tz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4374fe2e54ba4dc001141a09b878a78f5178c4ce/packages/geoview-time-slider/src/time-slider.tsx#L176)):*
> ```XML
>     } else {
>       let [leftHandle, rightHandle] = values;
>       if (!sliderDeltaRef.current) {
> ```

Should probably move some logic in a common function to reduce code duplication. Not pressing. Maybe a TODO?

**Review by DamonU2 — APPROVED** [review]
> Reviewed 7 of 9 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2310)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2310)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 181 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2310#-O0JwZU47Onji9vjEWyq:-O0Jx_vV2wWOOPqAyTzw:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4374fe2e54ba4dc001141a09b878a78f5178c4ce/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L181)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Maybe just check for `<?xml` or does it have to be xml version 1.0?
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2310)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

**Pull request merged**
