### PR TITLE
fix(ui): legend toggle parent update

### LINKED ISSUE #662: Swtich visibility group should toggle children
When we toggle visibility for a group, It should toggle visibility for children icon

- Toggle false, all children false
- Toggle true, one previously set false stay false, other become true.

See example: https://gcgeo.gc.ca/viz/index-en.html?keys=917b8854-64a5-41d6-ad7f-d0a3c0c3cb29

### PR DESCRIPTION
**Pull request by dayc-mapdev**
Closes #662

- - -
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/691)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/691)* status: all files reviewed, 1 unresolved discussion (waiting on @dayc-mapdev)

___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 400 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/691#-NI3-vZr1ginC70Ru7WQ:-NI3-vZs8Bz5QMAFtOox:bpaidb9) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/25a45b7ff87b9e66d333b46bdac0ae929228066d/packages/geoview-core/src/core/components/legend/legend-item.tsx#L400)):*
> ```XML
>                 subLayerId={subLayerId ? `${subLayerId}/${subItem.layerId}` : `${layerId}/${subItem.layerId}`}
>                 layerConfigEntry={subItem}
>                 isParentVisible={isParentVisible === false ? false : isChecked}
> ```

The only missing function would be when we change a children (hidden to visibile) it should trigger the parent visibility is it was hidden. For the moment, it works on the  map but the icon are not in synch

**Review by dayc-mapdev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/691)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 400 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/691#-NI3-vZr1ginC70Ru7WQ:-NI3eNtm4JChps8nKIH6:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/25a45b7ff87b9e66d333b46bdac0ae929228066d/packages/geoview-core/src/core/components/legend/legend-item.tsx#L400)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The only missing function would be when we change a children (hidden to visibile) it should trigger the parent visibility is it was hidden. For the moment, it works on the  map but the icon are not in synch
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/691)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dayc-mapdev)

___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 400 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/691#-NI3-vZr1ginC70Ru7WQ:-NI7rbTq0tlTKchHmByJ:bqe1n30) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/25a45b7ff87b9e66d333b46bdac0ae929228066d/packages/geoview-core/src/core/components/legend/legend-item.tsx#L400)):*
<details><summary><i>Previously, dayc-mapdev (Chris Day) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There is still a little something

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/691)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dayc-mapdev)

**Pull request merged**
