### PR TITLE
1231 filter map

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Do Map filter when we do filter search in data table.

Fixes # ([1231](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1231))

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
1) Open the below given url.
2) Create a table.
3) Switch on for filter on map.
4) Do some search by column.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/raw-data-table.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1239)

### CODE REVIEW

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1239)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @cphelefu, @DamonU2, and @kaminderpal)

___
*[`packages/geoview-core/public/locales/fr/translation.json` line 112 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1239#-NcTUzcg9YR81D-rf1W9:-NcTUzcg9YR81D-rf1WA:b-6c1rll) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/874f7c7766cc513d293dad7e7b1db1ffc6fcd449/packages/geoview-core/public/locales/fr/translation.json#L112)):*
> ```JSON
>     "downloadAsCSV": "Télécharger la CSV",
>     "filterMap": "Filter Map",
>     "stopFilterMap": "Stop Filter Map"
> ```

Do we need to use the French text for "Stop Filter Map"  and  "Filter Map" ?

**Review by amir-azma — APPROVED** [review]
:lgtm:

> Reviewed 6 of 8 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1239#-:-NcYfIaf2Y7SNKGhPDV_:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @cphelefu and @DamonU2)

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1239)* status: all files reviewed, 2 unresolved discussions (waiting on @cphelefu and @kaminderpal)

___
*[`packages/geoview-core/src/core/components/data-table/data-table-api.ts` line 146 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1239#-NcxpHpIBHUSkVjjy9Nl:-NcxpHpIBHUSkVjjy9Nm:bck0gwi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/22f84d03f7ff15c5647c57ecff74d1d85492fc46/packages/geoview-core/src/core/components/data-table/data-table-api.ts#L146)):*
> ```XML
>   /**
>    * Create data table based on layer id from map.
>    * @param {string} layerId layerId of the feature added on map.
> ```

Add layerKey
___
*[`packages/geoview-core/src/core/components/data-table/map-data-table.tsx` line 60 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1239#-NcxpWRVAF83GZ5n2ZhN:-NcxpWRVAF83GZ5n2ZhO:bck0gwi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/22f84d03f7ff15c5647c57ecff74d1d85492fc46/packages/geoview-core/src/core/components/data-table/map-data-table.tsx#L60)):*
> ```XML
>  * @param {MapDataTableProps} data map data which will be used to build data table.
>  * @param {string} layerId id of the layer
>  * @param {string} mapId id of the map.
> ```

Add layerKey

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1239)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @cphelefu and @DamonU2)

___
*[`packages/geoview-core/src/core/components/data-table/data-table-api.ts` line 146 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1239#-NcxpHpIBHUSkVjjy9Nl:-NcxrLL6AZbA_mDRET4U:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/22f84d03f7ff15c5647c57ecff74d1d85492fc46/packages/geoview-core/src/core/components/data-table/data-table-api.ts#L146)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Add layerKey
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/data-table/map-data-table.tsx` line 60 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1239#-NcxpWRVAF83GZ5n2ZhN:-NcxrLpGCDmvK8rzZJP-:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/22f84d03f7ff15c5647c57ecff74d1d85492fc46/packages/geoview-core/src/core/components/data-table/map-data-table.tsx#L60)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Add layerKey
</blockquote></details>

Done.

**Review by DamonU2 — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 1 of 2 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
