### PR TITLE
GeoView-GeoChart Plugin

### PR DESCRIPTION
**Pull request by Alex-NRCan**
The Geoview-geochart plugin PR

This PR needs #1443 to be merged first, ideally and then this PR be rebased for a cleaner history.

https://alex-nrcan.github.io/geoview/package-geochart.html

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1444)

### CODE REVIEW

**Review by ychoquet — APPROVED** [review]
> Reviewed 9 of 33 files at r1, 1 of 10 files at r2, 14 of 22 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1444)* status: all files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts` line 119 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1444#-NjDb8knD_uH26fhmWLk:-NjDb8knD_uH26fhmWLl:b-l9vnuu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ff1a501b61eb25286e2c65de0033fc99c6d4f5fa/packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts#L119)):*
> ```XML
> export const payloadIsQueryLayerQueryTypeAtLongLat = (verifyIfPayload: PayloadBaseClass): verifyIfPayload is TypeQueryLayerPayload => {
>   return payloadIsQueryLayer(verifyIfPayload) && verifyIfPayload.queryType === 'at_long_lat';
> };
> ```

We will have to change the store implementation to avoid the creation of this type gard function. Normally, the components should only rely on the store to do what's need to be done. Also, many things can trigger an event with ***queryType*** equal to ***at_long_lat***. Using this function to find if a click has been done is an error.



_Code quote:_
```XML
/**
 * Returns true if the payload is a TypeQueryLayerPayload with queryType equal to 'at_long_lat'.
 *
 * @param {PayloadBaseClass} verifyIfPayload object to test in order to determine if the type assertion and property are valid
 * @returns {boolean} returns true if the payload is valid
 */
export const payloadIsQueryLayerQueryTypeAtLongLat = (verifyIfPayload: PayloadBaseClass): verifyIfPayload is TypeQueryLayerPayload => {
  return payloadIsQueryLayer(verifyIfPayload) && verifyIfPayload.queryType === 'at_long_lat';
};
```
___
*[`packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts` line 153 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1444#-NjDdlC67sY8Ap93T9_d:-NjDdlC67sY8Ap93T9_e:br332hh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ff1a501b61eb25286e2c65de0033fc99c6d4f5fa/packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts#L153)):*
> ```XML
> export const payloadIsAllQueriesDoneEventClick = (verifyIfPayload: PayloadBaseClass): verifyIfPayload is TypeAllQueriesDonePayload => {
>   return payloadIsAllQueriesDone(verifyIfPayload) && verifyIfPayload.eventType === 'click';
> };
> ```

Same as above (revision of the store implementation).



_Code quote:_
```XML
/**
 * Returns true if the payload is a TypeAllQueriesDonePayload with eventType equal to 'click'.
 *
 * @param {PayloadBaseClass} verifyIfPayload object to test in order to determine if the type assertion and property are valid
 * @returns {boolean} returns true if the payload is valid
 */
export const payloadIsAllQueriesDoneEventClick = (verifyIfPayload: PayloadBaseClass): verifyIfPayload is TypeAllQueriesDonePayload => {
  return payloadIsAllQueriesDone(verifyIfPayload) && verifyIfPayload.eventType === 'click';
};
```
___
*[`packages/geoview-core/src/geo/utils/feature-info-layer-set.ts` line 84 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1444#-NjDeD_O6ywF_yxGHt_z:-NjDeD_O6ywF_yxGHta-:b-8z0i64) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ff1a501b61eb25286e2c65de0033fc99c6d4f5fa/packages/geoview-core/src/geo/utils/feature-info-layer-set.ts#L84)):*
> ```XML
>           // Because otherwise, we have to attach to both events in our Component to determine the status of the query and
>           // it might potentially unsynch between event calls.
>           // Doing so would also be nicer, because we'd have both ways work with store instead of having one working with api.event GET_FEATURE_INFO.QUERY_LAYER and one with store.
> ```

This work can be done in the store revision issue or in a separated one



_Code quote:_
```XML
          // TODO: Suggestion - Implement a "loading state" between query events. Via new function in FeatureInfoEventProcessor?
          // TO.DO.CONT: It'd be great to have a "store state" that indicates when a query is
          // in progress (that is between this event (and its siblings) and the GET_FEATURE_INFO.QUERY_RESULT).
          // Because otherwise, we have to attach to both events in our Component to determine the status of the query and
          // it might potentially unsynch between event calls.
          // Doing so would also be nicer, because we'd have both ways work with store instead of having one working with api.event GET_FEATURE_INFO.QUERY_LAYER and one with store.
```
___
*[`packages/geoview-geochart/src/geochart.tsx` line 270 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1444#-NjDenXj-x9MV0egTDja:-NjDenXj-x9MV0egTDjb:b4ka9qf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ff1a501b61eb25286e2c65de0033fc99c6d4f5fa/packages/geoview-geochart/src/geochart.tsx#L270)):*
> ```XML
>     cgpv.api.event.on(EVENT_CHART_LOAD, handleChartLoad, mapId);
>     cgpv.api.event.on(EVENT_CHART_REDRAW, handleChartRedraw, mapId);
>     cgpv.api.event.on(cgpv.api.eventNames.GET_FEATURE_INFO.QUERY_LAYER, handleQueryStarted, `${mapId}`);
> ```

Components should not rely directly on layerSets event but on store instead.



_Code quote:_
```XML
    cgpv.api.event.on(cgpv.api.eventNames.GET_FEATURE_INFO.QUERY_LAYER, handleQueryStarted, `${mapId}`);
```

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1444)* status: all files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-geochart/src/geochart.tsx` line 81 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1444#-NjDyE716kiYsWieodYe:-NjDyE716kiYsWieodYf:b-atvaga) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ff1a501b61eb25286e2c65de0033fc99c6d4f5fa/packages/geoview-geochart/src/geochart.tsx#L81)):*
> ```XML
> 
>   // Use Store
>   const storeLayerDataArray = useStore(getGeoViewStore(mapId), (state) => state.detailsState.layerDataArray);
> ```

Use atomic selector

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 1 of 33 files at r1, 3 of 22 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1444)* status: 34 of 37 files reviewed, 5 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/public/configs/package-geochart-map1-config-geochart.json` line 12 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1444#-NjDTtP4Cd09acy8wYBk:-NjDZzHc6w4nKB3c7yEg:bxizykw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ff1a501b61eb25286e2c65de0033fc99c6d4f5fa/packages/geoview-core/public/configs/package-geochart-map1-config-geochart.json#L12)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should be the table itself, not the layer. Layer should be retreive by layerId who is the layerpath
</blockquote></details>

Dans un autre issue, on va enlever esriRelatedRecords type et généraliser d'avantage le query.
___
*[`packages/geoview-core/public/configs/package-geochart-map1-config-geochart.json` line 53 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1444#-NjDU1k43pYjx6lamfTc:-NjE3QGf8txsyIcFwVuD:bxizykw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ff1a501b61eb25286e2c65de0033fc99c6d4f5fa/packages/geoview-core/public/configs/package-geochart-map1-config-geochart.json#L53)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same here, url for data should the data itself
</blockquote></details>

Dans un autre issue, on va enlever esriRelatedRecords type et généraliser d'avantage le query.
___
*[`packages/geoview-geochart/src/geochart.tsx` line 81 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1444#-NjDyE716kiYsWieodYe:-NjE6wSY4N8kNpEDKSO8:b-esadgv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ff1a501b61eb25286e2c65de0033fc99c6d4f5fa/packages/geoview-geochart/src/geochart.tsx#L81)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use atomic selector
</blockquote></details>

Added TODO about it, because it needs some work done for plugin support.
___
*[`packages/geoview-geochart/src/geochart.tsx` line 270 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1444#-NjDenXj-x9MV0egTDja:-NjDoSoMBqNXyeumkcnX:b-bwv2ly) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ff1a501b61eb25286e2c65de0033fc99c6d4f5fa/packages/geoview-geochart/src/geochart.tsx#L270)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Components should not rely directly on layerSets event but on store instead.
</blockquote></details>

Yes, that's the reason of the discussion. I'll add an explicit TODO.
___
*[`packages/geoview-geochart/src/geochart-event-base.ts` line 14 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1444#-NjDVuBG-H7r1qRms7BS:-NjD_Cxn7ZSzdv6HNPnC:b32w1t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ff1a501b61eb25286e2c65de0033fc99c6d4f5fa/packages/geoview-geochart/src/geochart-event-base.ts#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We will have to test the automatic injection of config from a call to its geocore uuid. We can do this with airborne as the geocore uuid has already a config in geocore. This can be created as a new issue.
</blockquote></details>

Ok
___
*[`packages/geoview-geochart/src/geochart-parsing.ts` line 188 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1444#-NjDWkob-4CzNWL5nyGP:-NjE6q0T5vNtiL2Pixjk:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ff1a501b61eb25286e2c65de0033fc99c6d4f5fa/packages/geoview-geochart/src/geochart-parsing.ts#L188)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should have a special parser for esri. The parser can also be a url with a json files that may not need all this. Thais can be in another issue.
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1444)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1444)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Pull request merged**
