### PR TITLE
fix(source-leaking-layer-configs) - Fixes an issue with the 'source' attribute leaking between layer configs

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

This PR addresses an issue, where the `source` class attribute is leaking from one layer config to another. Indeed, when the `source` is already set, it was using that one. The lines `Object.assign()` in each class  is also dangerous and remains to be fixed at this stage (_can do it in this PR too, but maybe even more impactful_).

The issue was intermittent and most problematic with the esri-dynamic-layer-config, where whichever the first sub-layer was getting its `source` first, all other siblings sub-layers were pointing to that `source`. This caused an issue when, for example, reading the out-fields when building the `DataTable` component. Sometimes, the sub-layer was looking for out-fields of another sibling layer and wasn't displaying the correct columns in the `DataTable`.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Hosted, April 19th: https://alex-nrcan.github.io/geoview/esri-dynamic.html#HLYR4

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2028)

### CODE REVIEW

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2028)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/core/utils/config/validation-classes/raster-validation-classes/esri-dynamic-layer-entry-config.ts` line 40 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2028#-NvhSmpu2TL6Tg_98YgE:-NvhSmpu2TL6Tg_98YgF:bk2aij6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c934fa4761e5bb0d00ab136de0cd7f9b1a0966fe/packages/geoview-core/src/core/utils/config/validation-classes/raster-validation-classes/esri-dynamic-layer-entry-config.ts#L40)):*
> ```XML
>     // if layerConfig.source.dataAccessPath is undefined, we assign the metadataAccessPath of the GeoView layer to it.
>     this.source = {};
>     this.source.dataAccessPath = { ...layerConfig.geoviewLayerConfig.metadataAccessPath! };
> ```

The if are important here because if the user specify something in in the ***source*** property of the config, then
***this.source = {};***   <= This will drop the source information provided by the user

The goal of the first is to verify if the user provided something in the  ***source*** property. If not we create an empty one to make sure the next line doesn't say  ***source is undefined*** when we assign the new value to ***this.source.dataAccessPath***
The second ***if*** veriffy if the user provided a ***dataAccessPath***. If it  is undefined, we define it.

There's probably a more elegant way to do the same thing. The idea here is to keep information provided by the user and if it is not provided, use the default.

The solution is probably to use ***lodash*** to clone the ***layerConfig*** in ***this*** instead of using ***Object.assign(this, layerConfig);*** at the beginning of the constructor.



_Code quote:_
```XML
    this.source = {};
    this.source.dataAccessPath = { ...layerConfig.geoviewLayerConfig.metadataAccessPath! };
```

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 1 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2028)* status: 1 of 12 files reviewed, 1 unresolved discussion (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/core/utils/config/validation-classes/raster-validation-classes/esri-dynamic-layer-entry-config.ts` line 40 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2028#-NvhSmpu2TL6Tg_98YgE:-NvhnLQI1zXqpExV3EWr:b-n02dxv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c934fa4761e5bb0d00ab136de0cd7f9b1a0966fe/packages/geoview-core/src/core/utils/config/validation-classes/raster-validation-classes/esri-dynamic-layer-entry-config.ts#L40)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

The if are important here because if the user specify something in in the ***source*** property of the config, then
***this.source = {};***   <= This will drop the source information provided by the user

The goal of the first is to verify if the user provided something in the  ***source*** property. If not we create an empty one to make sure the next line doesn't say  ***source is undefined*** when we assign the new value to ***this.source.dataAccessPath***
The second ***if*** veriffy if the user provided a ***dataAccessPath***. If it  is undefined, we define it.

There's probably a more elegant way to do the same thing. The idea here is to keep information provided by the user and if it is not provided, use the default.

The solution is probably to use ***lodash*** to clone the ***layerConfig*** in ***this*** instead of using ***Object.assign(this, layerConfig);*** at the beginning of the constructor.
</blockquote></details>

We'd need to verify if a deepclone isn't going to infinitely loop on the cyclic properties of the layer config object. Yves will verify.

That said, if it works, we could do this and bring back the `if !source then source = default (otherwise the source attribute will use a copy from the given object)`.

That said again, personally, I'd probably give the responsibility to provide the correct source (when the caller do want to provide a source), by the caller, when they are providing the params. Basically, let the caller create the source object instead of relying on the constructor to do a systematic copy all the time. Seems more explicit to me?

**Review by jolevesq — APPROVED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2028)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

___
*[`packages/geoview-core/src/core/utils/config/validation-classes/raster-validation-classes/esri-dynamic-layer-entry-config.ts` line 40 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2028#-NvhSmpu2TL6Tg_98YgE:-NvlxpPt4MrmfBjNwV_Q:bt7b1mk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c934fa4761e5bb0d00ab136de0cd7f9b1a0966fe/packages/geoview-core/src/core/utils/config/validation-classes/raster-validation-classes/esri-dynamic-layer-entry-config.ts#L40)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

We'd need to verify if a deepclone isn't going to infinitely loop on the cyclic properties of the layer config object. Yves will verify.

That said, if it works, we could do this and bring back the `if !source then source = default (otherwise the source attribute will use a copy from the given object)`.

That said again, personally, I'd probably give the responsibility to provide the correct source (when the caller do want to provide a source), by the caller, when they are providing the params. Basically, let the caller create the source object instead of relying on the constructor to do a systematic copy all the time. Seems more explicit to me?
</blockquote></details>

You are right, with the new config, source will ALWAYS be set ahead of creation and pass to the layer constructor.

**Review by jolevesq — APPROVED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2028)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Pull request merged**
