### PR TITLE
Small fixes in layers

### LINKED ISSUE #1993: [BUG] Tabs in the footer have different background colors
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Tabs in the footer have a different background color.
Make sure the color is the same and it is centralized.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### LINKED ISSUE #2009: [BUG] Fix console log errors on the layers page
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Fix console log errors on the layers page

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### LINKED ISSUE #2011: [BUG] [Layers] Remove subtitles that say "1 of 1" items. Also remove it in the layer details.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Remove subtitles that say "1 of 1" items. Also remove it in the layer details.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### LINKED ISSUE #2012: [BUG] [Layers] Make the datable icon a little smaller
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

_No response_

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

Minor fixes in layers.

LAYERS
- [x] Fixes #1993 
- [x] Fixes #2012 
- [x] Remove layer, speed it up a little bit.
- [x] Fixes #2009 
- [x] Make sure we have tooltips in layer titles. Also in the datable icon.
- [x] Fixes #2011 
- [x] Set max width on opacity bar and float it right. Maybe same width as the other controls.
- [x] Fix '1 of 1 items' in legend page.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://cphelefu.github.io/geoview/

# Checklist:

- [X] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [X] I have connected the issues(s) to this PR
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2020)

### CODE REVIEW

**Review by kaminderpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2020)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 126 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2020#-NvdgkJI8Ry3tXH0p1xn:-NvdgkJI8Ry3tXH0p1xo:b8uw92j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/74edd76db664bdd84da6b9537d4829bbf4af3b68/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L126)):*
> ```XML
>         <span>
>           {itemsLengthDesc} &nbsp;
>           <TableViewIcon sx={{ marginBottom: '-5px' }} fontSize="small" />{' '}
> ```

-ve margin and px?
any reason for using {' '}?
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 109 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2020#-Nvdh122DdsPmihZIvX3:-Nvdh122DdsPmihZIvX4:bkd3svv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/74edd76db664bdd84da6b9537d4829bbf4af3b68/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L109)):*
> ```XML
> 
>     if (totalCount <= 1) {
>       return null;
> ```

I think we can return empty string, this way we can keep return type `String` instead of null.

**Review by kaminderpal — CHANGES_REQUESTED** [review]
> Dismissed @kaminderpal from a discussion.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2020)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 124 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2020#-NvgCJfI2YP0BOcN0-nR:-NvgCJfJBmid0x4AavIQ:b-xapguk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/94035bb9ddd3e1d2fbad36d4d05772d2ccf5afe1/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L124)):*
> ```XML
>     if (datatableSettings[layer.layerPath]) {
>       return (
>         <span>
> ```

I think `<span>` can be replaced by `<Box component="span">`. This way to dnt need to introduce native HTML elements in Core package.
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 109 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2020#-Nvdh122DdsPmihZIvX3:-NvgC2jw8jFUWenUnbbM:b-jdn40p) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/74edd76db664bdd84da6b9537d4829bbf4af3b68/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L109)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think u change at one place, but missed here.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 109 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2020#-Nvdh122DdsPmihZIvX3:-NvgGYHk9oeBOawp53lF:b-7nxict) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/74edd76db664bdd84da6b9537d4829bbf4af3b68/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L109)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

I think u change at one place, but missed here.
</blockquote></details>

I dont think this is error

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 124 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2020#-NvgCJfI2YP0BOcN0-nR:-NvgGfcmAMWm5GX3W5gc:b-gfl04q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/94035bb9ddd3e1d2fbad36d4d05772d2ccf5afe1/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L124)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

I think `<span>` can be replaced by `<Box component="span">`. This way to dnt need to introduce native HTML elements in Core package.
</blockquote></details>

Doing that results in a console log

**Review by kaminderpal — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2020#-:-NvgJswW7-wFw1ifjflO:bnfp4nl)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
