### PR TITLE
1174 adding alias paths

### LINKED ISSUE #1174: [FEATURE] Add alias paths and reduce the use of relative paths.
**Is there an existing issue for this?**
Nope

**Who request this Feature**
Development team

**User Story**
Throughout the application we are using relative paths in our import statements, e.g. `import { EVENT_NAMES } from '../../../api/events/event-types'`.
We need to add alias paths so we can change paths to `import { EVENT_NAMES } from '@/api/events/event-types'`.

We can use [webpack alias path](https://webpack-v3.jsx.app/configuration/resolve/).

**Additional context**
We can add the following paths.

```
alias: {
  @: path.resolve(__dirname, 'src'),
  @api: path.resolve(__dirname, 'src/api/')
  @core: path.resolve(__dirname, 'src/core/')
  @ui: path.resolve(__dirname, 'src/ui/')
  @geo: path.resolve(__dirname, 'src/geo/')
}
```

### PR DESCRIPTION
**Pull request by cphelefu**
# Description
Closes #1174 

Adding alias paths to the code to make our imports more easy to understand.

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

This has been verified by making sure all components still work as expected.

__Add the URL for your deploy!__

# Checklist:

- [X] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [X] I have connected the issues(s) to this PR
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 92 of 92 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196)* status: 88 of 92 files reviewed, 15 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar-buttons.ts` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tOhul6UDlt_yaoj9I:-N_tOhul6UDlt_yaoj9J:bhjzapu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/app-bar/app-bar-buttons.ts#L5)):*
> ```XML
> import { EVENT_NAMES } from '@/api/events/event-types';
> 
> import { PanelApi } from '../../../ui';
> ```

Can we do this one as well with @ui
___
*[`packages/geoview-core/src/core/components/attribution/attribution.tsx` line 10 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tOd8QCL-zOUfKeD1B:-N_tOd8QCL-zOUfKeD1C:bhjzapu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/attribution/attribution.tsx#L10)):*
> ```XML
> import { MapContext } from '../../app-start';
> import { api } from '../../../app';
> import { Tooltip, Box } from '../../../ui';
> ```

Can we do this one as well with @ui
___
*[`packages/geoview-core/src/core/components/click-marker/click-marker.tsx` line 18 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tOWgJ79f7qe8q6K_4:-N_tOWgK6iC4_qkzL2Ba:bhjzapu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/click-marker/click-marker.tsx#L18)):*
> ```XML
> import { PayloadBaseClass, TypeFeatureInfoEntry, api, payloadIsAllQueriesDone } from '../../../app';
> import { EVENT_NAMES } from '@/api/events/event-types';
> import { ClickMapMarker } from '../../../ui';
> ```

Can we do this one as well with @ui
___
*[`packages/geoview-core/src/core/components/crosshair/crosshair.tsx` line 16 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tOofwBm0UVaITfEKP:-N_tOofwBm0UVaITfEKQ:bhjzapu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/crosshair/crosshair.tsx#L16)):*
> ```XML
> import { CrosshairIcon } from './crosshair-icon';
> 
> import { Fade } from '../../../ui';
> ```

Can we do this one as well with @ui
___
*[`packages/geoview-core/src/core/components/feature-info/feature-info.tsx` line 22 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tP-M7AbfySqjnIFPu:-N_tP-M7AbfySqjnIFPv:bhjzapu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/feature-info/feature-info.tsx#L22)):*
> ```XML
>   IconButton,
>   Box,
> } from '../../../ui';
> ```

Can we do this one as well with @ui
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-expand-button.tsx` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tP5OiB-PmxX0ion88:-N_tP5OiB-PmxX0ion89:bhjzapu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/footer-bar/footer-bar-expand-button.tsx#L3)):*
> ```XML
> import { useContext, useState } from 'react';
> 
> import { ExpandMoreIcon, ExpandLessIcon, IconButton, Box } from '../../../ui';
> ```

Can we do this one as well with @ui
___
*[`packages/geoview-core/src/core/components/map/map.tsx` line 30 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tPGhj7YZj30ZsZ985:-N_tPGhj7YZj30ZsZ986:b-3n854b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/map/map.tsx#L30)):*
> ```XML
> import { EVENT_NAMES } from '@/api/events/event-types';
> 
> import { MapViewer } from '../../../geo/map/map';
> ```

Do we have one for geo?
___
*[`packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx` line 18 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tPM443K1U6igY-ER1:-N_tPM443K1U6igY-ER2:bhjzapu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx#L18)):*
> ```XML
> import { payloadIsABoolean } from '@/api/events/payloads/boolean-payload';
> 
> import { Box, CheckIcon, Tooltip } from '../../../ui';
> ```

Can we do this one as well with @ui
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tPOYn0IxoGkzMR9gd:-N_tPOYn0IxoGkzMR9ge:bhjzapu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L17)):*
> ```XML
> 
> import { api, payloadIsABoolean } from '../../../app';
> import { Panel, ButtonGroup, IconButton, Box } from '../../../ui';
> ```

Can we do this one as well with @ui
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar-buttons.ts` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tPQKxAiaMqyELxAZv:-N_tPQKxAiaMqyELxAZw:bhjzapu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/nav-bar/nav-bar-buttons.ts#L5)):*
> ```XML
> import { EVENT_NAMES } from '@/api/events/event-types';
> 
> import { PanelApi } from '../../../ui';
> ```

Can we do this one as well with @ui
___
*[`packages/geoview-core/src/core/components/scale/scale.tsx` line 14 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tPa0T6oQLiOGZ3g0Y:-N_tPa0T6oQLiOGZ3g0Z:bhjzapu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/scale/scale.tsx#L14)):*
> ```XML
> import { EVENT_NAMES } from '@/api/events/event-types';
> 
> import { CheckIcon, Tooltip, Box } from '../../../ui';
> ```

Can we do this one as well with @ui
___
*[`packages/geoview-core/src/core/types/global-types.ts` line 11 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tPetW6ABSUjCTPbyv:-N_tPetW6ABSUjCTPbyw:b-3n854b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/types/global-types.ts#L11)):*
> ```XML
> import * as UI from '../../ui';
> import { AbstractPlugin } from '@/api/plugin/abstract-plugin';
> import { TypeDisplayLanguage, TypeMapFeaturesInstance } from '../../geo/map/map-schema-types';
> ```

Do we have one for geo?
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 13 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tQ-Dh-32xq15G9B3o:-N_tQ-Dh-32xq15G9B3p:b-3n854b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/utils/utilities.ts#L13)):*
> ```XML
> 
> import { AbstractGeoViewLayer, api } from '../../app';
> import { TypeLocalizedString } from '../../geo/map/map-schema-types';
> ```

Do we have one for geo?
___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 41 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tQ2NW1pTwuxsoZb44:-N_tQ2NW1pTwuxsoZb45:b-3n854b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/utils/config/config-validation.ts#L41)):*
> ```XML
> import { snackbarMessagePayload } from '@/api/events/payloads/snackbar-message-payload';
> import { EVENT_NAMES } from '@/api/events/event-types';
> import { Layer } from '../../../geo/layer/layer';
> ```

Do we have one for geo?
___
*[`packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts` line 22 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tQ71ZCpJWUCTocD-y:-N_tQ71ZCpJWUCTocD-z:b-3n854b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts#L22)):*
> ```XML
> import { TypeGeoJSONLayerConfig, TypeGeoJSONLayerEntryConfig } from '../../../../geo/layer/geoview-layers/vector/geojson';
> import { TypeGeoPackageLayerConfig, TypeGeoPackageLayerEntryConfig } from '../../../../geo/layer/geoview-layers/vector/geopackage';
> import { TypeXYZTilesConfig, TypeXYZTilesLayerEntryConfig } from '../../../../geo/layer/geoview-layers/raster/xyz-tiles';
> ```

Do we have one for geo?

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196)* status: 21 of 119 files reviewed, 15 unresolved discussions (waiting on @jolevesq and @ui)

___
*[`packages/geoview-core/src/core/components/feature-info/feature-info.tsx` line 22 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tP-M7AbfySqjnIFPu:-N_tWnJq3LLutIc_C6ex:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/feature-info/feature-info.tsx#L22)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we do this one as well with @ui
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-expand-button.tsx` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tP5OiB-PmxX0ion88:-N_tWqvx2opj8VwlAKu-:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/footer-bar/footer-bar-expand-button.tsx#L3)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we do this one as well with @ui
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/map/map.tsx` line 30 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tPGhj7YZj30ZsZ985:-N_tWuDzD1bN1_Zyo5eb:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/map/map.tsx#L30)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we have one for geo?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx` line 18 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tPM443K1U6igY-ER1:-N_tWwUl-S19M0ATrf-U:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx#L18)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we do this one as well with @ui
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tPOYn0IxoGkzMR9gd:-N_tWxTq7_u6DbmrYaXY:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L17)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we do this one as well with @ui
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar-buttons.ts` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tPQKxAiaMqyELxAZv:-N_tWylRBQT48eP7vNFE:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/nav-bar/nav-bar-buttons.ts#L5)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we do this one as well with @ui
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/scale/scale.tsx` line 14 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tPa0T6oQLiOGZ3g0Y:-N_tX2AoAD7HfrBbbQDE:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/scale/scale.tsx#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we do this one as well with @ui
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/types/global-types.ts` line 11 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tPetW6ABSUjCTPbyv:-N_tX3io3OKlSpXiduQr:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/types/global-types.ts#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we have one for geo?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 13 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tQ-Dh-32xq15G9B3o:-N_tX5Zn4GsnZxwvo1Kb:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/utils/utilities.ts#L13)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we have one for geo?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 41 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tQ2NW1pTwuxsoZb44:-N_tX7u369Yq7SFzSGp9:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/utils/config/config-validation.ts#L41)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we have one for geo?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts` line 22 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tQ71ZCpJWUCTocD-y:-N_tXOUd-WxneFSNVAkM:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts#L22)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we have one for geo?
</blockquote></details>

Done.

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196)* status: 21 of 119 files reviewed, 15 unresolved discussions (waiting on @jolevesq and @ui)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar-buttons.ts` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tOhul6UDlt_yaoj9I:-N_tZY1J3B-HafUGRv0d:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/app-bar/app-bar-buttons.ts#L5)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we do this one as well with @ui
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/attribution/attribution.tsx` line 10 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tOd8QCL-zOUfKeD1B:-N_tZZNVBvQGVgE8fB-Y:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/attribution/attribution.tsx#L10)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we do this one as well with @ui
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/click-marker/click-marker.tsx` line 18 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tOWgJ79f7qe8q6K_4:-N_tZ_6v7jwVL9i8nhcH:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/click-marker/click-marker.tsx#L18)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we do this one as well with @ui
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/crosshair/crosshair.tsx` line 16 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-N_tOofwBm0UVaITfEKP:-N_tZa0m8pQPmmx8vft4:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e76c1f4baabcfb7f3176ec3acf9ed4f885fadf23/packages/geoview-core/src/core/components/crosshair/crosshair.tsx#L16)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we do this one as well with @ui
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
:lgtm:

> Reviewed 44 of 98 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196#-:-N_t_v5k2sUDyw8Re_MM:bnfp4nl)* status: 65 of 119 files reviewed, all discussions resolved (waiting on @cphelefu)

**Review by jolevesq — APPROVED** [review]
> Reviewed 54 of 98 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1196)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
