### PR TITLE
group layer data grid; remove the timeout from details component

### LINKED ISSUE #851: [BUG] Footer Panel Data Tab Missing Group Layers
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I use the footer package demo page, https://canadian-geospatial-platform.github.io/geoview/public/package-footer-panel.html#HUC1, I can't access Data Grid for group layer the same way I can access Data Grid for stand alone layer.

If a layer is added and is raster, the footer crash as there is no getAllFeatureInfo excpet for ESRI Dynamic.

### Expected Behavior

When we select a group layer from Data tabs, we should have a drop down list of child layers (with firs one selected) and the table should be created for this layer. Switching form a layer to another should recreate the table.

UI should be manage from data-items.tsx in the footer-package. The drop down will not solve nested group layers but for footer panel it may be enough as it is not aim for complex view.

The footer should not crash and call only when function is available

### Steps To Reproduce

1. Go on this page: https://canadian-geospatial-platform.github.io/geoview/public/package-footer-panel.html#HUC1
2. Click the tab Data
3. Select GeoJSON Sample
4. See there is no table because it is a group layer

1. Add a WMS layer to config
2. The map failed because getAllFeatureInfo is not undefined

### Anything else?

Call to group level gave empty result
```
cgpv.api.maps.mapWM1.layer.geoviewLayers.geojsonLYR5.getAllFeatureInfo("geojsonLYR5")
```

Call to child layer of group layer gave table info
```
cgpv.api.maps.mapWM1.layer.geoviewLayers.geojsonLYR5.getAllFeatureInfo("geojsonLYR5/lines.json")
```
```
[
    {
        "featureKey": 0,
        "featureInfo": {
            "Road Number": 55,
            "Province": "Quebec"
        }
    },
    {
        "featureKey": 1,
        "featureInfo": {
            "Road Number": 20,
            "Province": "Ontario"
        }
    }
]
```

### PR DESCRIPTION
**Pull request by dennisfu**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #851

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Footer panel, data tab, the GeoJsonSample, new dropdown list if layers, change the layers, the data table of the selected layer showing up below

For the feature info only have featurekey, set the featureKey column showing (default hidden) 

Fix the issue of data grid column max

Also remove the timeout from the details component, set the marker timeout separately in details panel and footer panel details tab

# Checklist:

- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/897)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/897)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @dennisfu)

___
*[`packages/geoview-core/src/core/components/data-grid/data-grid-api.ts` line 43 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/897#-NO9pc7r1X2E_WMPPEi1:-NO9pc7s96mHUKBvCuYt:b-2vitl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fcd6c166199143aac788c3b931f4caa995f5b1e7/packages/geoview-core/src/core/components/data-grid/data-grid-api.ts#L43)):*
> ```XML
>    */
>   createDataGrid = (layerDataGridProps: TypeLayerDataGridProps): ReactElement => {
>     const { layerId, onChangeLayer } = layerDataGridProps;
> ```

The component should not deal with the onChange, this should be in the footer panel package. Core component are high level component to reuse in packages/outside api. The core component  should only return table elements.
___
*[`packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx` line 133 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/897#-NO9qtI83BSc8ynqoEdK:-NO9qtI83BSc8ynqoEdL:b-sl5zdk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/afa3a34865999d20b7c17fe5fff79bec07f83c91/packages/geoview-core/src/core/components/footer-tabs/footer-tabs.tsx#L133)):*
> ```XML
>               const mapContainer = tabsContainer.previousElementSibling as HTMLDivElement;
>               if (mapContainer.style.height === 'calc(100% - 300px)') {
>                 setIsCollapsed(false);
> ```

Why is this removed?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/897)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @dennisfu)

___
*[`packages/geoview-core/src/core/components/data-grid/data-grid-api.ts` line 43 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/897#-NO9pc7r1X2E_WMPPEi1:-NO9rgse54HFw69IFtOL:b6kwn70) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fcd6c166199143aac788c3b931f4caa995f5b1e7/packages/geoview-core/src/core/components/data-grid/data-grid-api.ts#L43)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The component should not deal with the onChange, this should be in the footer panel package. Core component are high level component to reuse in packages/outside api. The core component  should only return table elements.
</blockquote></details>

Because this component will be called by the layer item in layer-package and be shown in a panel with no onChange, only the table elment.

**Comment by dennisfu** [comment]
1. removed the onchange from core component, and added the event listener in outside plugin
2. the setIscollapse was added back, removed it since the default is false already. added it back for the coding logic

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/897)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dennisfu)

**Pull request merged**
