### PR TITLE
646 UI components mui

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Migirate all UI and custom components to use SX prop.
Overview map is not done because it requires native html and cant support SX prop.

Also update custom Button component in UI folder.

Fixes # (646)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/
# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
> Reviewed 11 of 12 files at r1, 18 of 32 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431)* status: 27 of 42 files reviewed, 11 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 30 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-NhazfwR1SgGJqeV4mBj:-NhazfwR1SgGJqeV4mBk:b9jd5ja) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L30)):*
> ```XML
>  */
> export function Appbar({ activeTrap, activeTrapSet }: AppbarProps): JSX.Element {
>   const sxtheme = useTheme();
> ```

We need to be consistent so call the const theme
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 31 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-Nhaznca1sae_VTVdY9b:-Nhaznca1sae_VTVdY9c:bn0hd1h) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L31)):*
> ```XML
> export function Appbar({ activeTrap, activeTrapSet }: AppbarProps): JSX.Element {
>   const sxtheme = useTheme();
>   const classes = getSxClasses(sxtheme);
> ```

Rename classes to sxClasses to know where it come from when we use it.
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 36 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-Nhaw7-HD7YP3oA3m30w:-Nhaw7-HD7YP3oA3m30x:bhes4aa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L36)):*
> ```XML
>   const [selectedAppBarButtonId, setSelectedAppbarButtonId] = useState<string>('');
> 
>   // const classes = useStyles();
> ```

Remove dead code
___
*[`packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx` line 44 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-NhawJ-y7LlhGmd52yC3:-NhawJ-y7LlhGmd52yC4:b19xdp8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx#L44)):*
> ```XML
>   const classes = getSxClasses(theme);
> 
>   const mousePosition = {
> ```

Why this style does not came from the style file in sx classes. We should use MUI Button?
___
*[`packages/geoview-core/src/core/components/scale/scale.tsx` line 44 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-NhawdWI0GHhD9-Yo4qI:-NhawdWI0GHhD9-Yo4qJ:bu968p6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/core/components/scale/scale.tsx#L44)):*
> ```XML
> 
>   const classes = getSxClasses(defaultTheme);
>   const scaleContainer = {
> ```

Why do we need style instead of sx and why it is in this file instead of style file
___
*[`packages/geoview-core/src/ui/button/button.tsx` line 46 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-NhazL2I7WcMrysRzIQb:-NhazL2I7WcMrysRzIQc:b-gl354n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/ui/button/button.tsx#L46)):*
> ```XML
>   const buttonRef = useRef<HTMLElement>(null);
>   const theme = useTheme();
>   const classes = getSxClasses(theme);
> ```

For all the components, use const name sxClasses instead of classes so we know where it comes from when we use it.
___
*[`packages/geoview-core/src/ui/button/button.tsx` line 57 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-NhaxVOj5WlXBNi46SwZ:-NhaxVOj5WlXBNi46Sw_:b-mxxays) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/ui/button/button.tsx#L57)):*
> ```XML
>   };
> 
>   const textStyle = {
> ```

Same here, why style, why not in the style file
___
*[`packages/geoview-core/src/ui/list/checkbox-list/checkbox-list-enhanced-style.ts` line 22 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-NhayA853jyBwTDAfApZ:-NhayA853jyBwTDAfAp_:bkne3p8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/ui/list/checkbox-list/checkbox-list-enhanced-style.ts#L22)):*
> ```XML
>     minWidth: '0px',
>   },
>   boxcontent: {
> ```

Can we have both checkbox style in one file checkbox-list-style.ts and have 2 exports... styles are almost identical. Soma part may be reuse.
___
*[`packages/geoview-core/src/ui/modal/modal.tsx` line 89 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-Nhb-1Mk85JNa1i8ZJBp:-Nhb-1Mk85JNa1i8ZJBq:b4dw25o) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/ui/modal/modal.tsx#L89)):*
> ```XML
>   let openEvent = false;
> 
>   const sxtheme = useTheme();
> ```

rename theme
___
*[`packages/geoview-core/src/ui/modal/modal.tsx` line 90 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-Nhb-3By1pNCgQ7y70lO:-Nhb-3By1pNCgQ7y70lP:b-pczmxg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/ui/modal/modal.tsx#L90)):*
> ```XML
> 
>   const sxtheme = useTheme();
>   const dialogClasses = getSxClasses(sxtheme);
> ```

Rename sxClassesDialog
___
*[`packages/geoview-core/src/ui/panel/panel.tsx` line 71 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-NhaytM2BjUPe_SMJMIn:-NhaytM2BjUPe_SMJMIo:biu9qrv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/ui/panel/panel.tsx#L71)):*
> ```XML
>   const [, updatePanelContent] = useState(0);
> 
>   const classes = getSxClasses(theme);
> ```

Move this line below theme to regroup the theme const and the use of it. Rename to sxClasses

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431)* status: 14 of 43 files reviewed, 11 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 30 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-NhazfwR1SgGJqeV4mBj:-NhbpM7q6rAaq9074VAh:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L30)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We need to be consistent so call the const theme
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 31 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-Nhaznca1sae_VTVdY9b:-NhbpLoo252r0IY09y2p:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L31)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Rename classes to sxClasses to know where it come from when we use it.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 36 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-Nhaw7-HD7YP3oA3m30w:-NhbpLGp3UPFZ6oBCDYL:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L36)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove dead code
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/button/button.tsx` line 46 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-NhazL2I7WcMrysRzIQb:-Nhbp_1p0JoS9v4vTk5E:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/ui/button/button.tsx#L46)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

For all the components, use const name sxClasses instead of classes so we know where it comes from when we use it.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/modal/modal.tsx` line 89 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-Nhb-1Mk85JNa1i8ZJBp:-NhbqHsw2hN69K-_RVYu:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/ui/modal/modal.tsx#L89)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

rename theme
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/modal/modal.tsx` line 90 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-Nhb-3By1pNCgQ7y70lO:-NhbqIPK2oZQCF_scnDa:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/ui/modal/modal.tsx#L90)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Rename sxClassesDialog
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/panel/panel.tsx` line 71 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-NhaytM2BjUPe_SMJMIn:-NhbqJfN8YSSrlJVH9xd:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/ui/panel/panel.tsx#L71)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Move this line below theme to regroup the theme const and the use of it. Rename to sxClasses
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/list/checkbox-list/checkbox-list-enhanced-style.ts` line 22 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-NhayA853jyBwTDAfApZ:-NhbqGuA7pNwildBGz_7:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/ui/list/checkbox-list/checkbox-list-enhanced-style.ts#L22)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we have both checkbox style in one file checkbox-list-style.ts and have 2 exports... styles are almost identical. Soma part may be reuse.
</blockquote></details>

Done.

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431)* status: 14 of 43 files reviewed, 11 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx` line 44 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-NhawJ-y7LlhGmd52yC3:-NhbrPOP5RN0m37RSJWo:b-vw8458) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx#L44)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why this style does not came from the style file in sx classes. We should use MUI Button?
</blockquote></details>

I have use style because it is developed using native button, on which we cant add sx prop, To use MUI Button it requires more effort, because there are 2 more components in similar scenarios.

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431)* status: 10 of 55 files reviewed, 11 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/scale/scale.tsx` line 44 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-NhawdWI0GHhD9-Yo4qI:-NhgQVXnAmL6TQiv0DOx:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/core/components/scale/scale.tsx#L44)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why do we need style instead of sx and why it is in this file instead of style file
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/button/button.tsx` line 57 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1431#-NhaxVOj5WlXBNi46SwZ:-NhgQXbb1zif7mMhKZUq:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8dedc6a7166050d5d2535f66d41afb1ab4b984b2/packages/geoview-core/src/ui/button/button.tsx#L57)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same here, why style, why not in the style file
</blockquote></details>

Done.

**Pull request merged**
