### PR TITLE
2255-Implement ConfigApi.validateMapConfig and ConfigApi.convertGeoco…

### LINKED ISSUE #2255: Implement ConfigApi.validateMapConfig
Implement the ConfigApi.validateMapConfig static method as shown on the implementation diagram.  The current implementation is named createMapConfig and is doing more than expected.

Also implement theConfigApi.convertGeocoreToGeoview to convert one or a list of GeoCore layers to their GeoView equivalents.

### PR DESCRIPTION
**Pull request by ychoquet**
…reToGeoview

# Description

Implement the ConfigApi.validateMapConfig static method as shown on the implementation diagram. The current implementation is named createMapConfig and is doing more than expected.

Also implement theConfigApi.convertGeocoreToGeoview to convert one or a list of GeoCore layers to their GeoView equivalents.

Fixes #2255

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using Chrome Devtools to trace and debug using the deploy link below.

__Deploy URL__: https://ychoquet.github.io/GeoView/config-sandbox.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265)

### CODE REVIEW

**Review by DamonU2 — APPROVED** [review]
> Reviewed 6 of 9 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265)* status: all files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265)* status: all files reviewed, 5 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 264 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-bHWqX3O-SRVBJyCca:-O-bHWqY1paeKm-Ju9mC:b-5csfz8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7d6aaefd96a444ee52749f708da1b1ccc4a7a600/packages/geoview-core/src/api/config/config-api.ts#L264)):*
> ```XML
>         // filterUndefinedValues flag is true, filter out the erroneous GeoCore layers.
>         newListOfGeoviewLayerConfig = newListOfGeoviewLayerConfig.filter((layerConfig) => {
>           if (layerConfig.geoviewLayerType === CV_CONFIG_GEOCORE_TYPE) {
> ```

I might end up blaming reviewable presentation here, so this might be a non-issue, but, here, if a `geoviewLayerType` is geocore it's an automatic error.
Above, we're checking for `geoviewLayerType` is geocore to get info.
I don't see where the `geoviewLayerType` is changed between the calls?
I'm just surprised it's not logging all geocore in errors?

Maybe this is supposed to be filtering on the `arrayOfJsonConfig` instead? That array will contain the 'validated' GeoviewLayers information (non-geocore), right?
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 108 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-bJg0x4kp_0uHZ8rnm:-O-bJg0y6sgONLRGaHaQ:btrz0ow) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7d6aaefd96a444ee52749f708da1b1ccc4a7a600/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L108)):*
> ```XML
> 
>     // set map configuration
>     const gvMap = cloneDeep(providedMapFeatureConfig.map) as TypeJsonObject;
> ```

It seems the leak has been reduced to the '.map' content?

If the intention of this class is to be working on a copy of the provided param (the one stored in `#originalgeoviewLayerConfig`), shouldn't it work on the copy of the provided param, not store a copy and work on the provided param?

If the intention is to work on the parameter, it can stay as-is. Might lead to a class-state disconnection later with the attribute though.

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265)* status: all files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 298 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-b8rZV9QMZN-kiHOLh:-O-brOxIE54AGMx9X8cg:b-7sq2k6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5cb8436173a856c88cb59f7084612572f387e95b/packages/geoview-core/src/api/config/config-api.ts#L298)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The name says validateLayerConfig but takes a mapConfig in parameters... should take a listOfGEoviewLAyers or function name should be validateMapConfigAgainstSchema?

The section to validate layers should take list of layers in params, not a string because at this point mapConfig is an object and if we call this directly, we will pass an object
</blockquote></details>

The mapConfig name is an error. However, it is supposed to be a geoviewLayerConfig. I say that because on the schema, the forEachGeoviewLayer loop is outside the Config API box and you've told me many times that the layers are processed one by one from outside the API. Is it still right?
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 264 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-bHWqX3O-SRVBJyCca:-O-boL8m2ciN6zq5Lu6c:b-gbz26n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7d6aaefd96a444ee52749f708da1b1ccc4a7a600/packages/geoview-core/src/api/config/config-api.ts#L264)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I might end up blaming reviewable presentation here, so this might be a non-issue, but, here, if a `geoviewLayerType` is geocore it's an automatic error.
Above, we're checking for `geoviewLayerType` is geocore to get info.
I don't see where the `geoviewLayerType` is changed between the calls?
I'm just surprised it's not logging all geocore in errors?

Maybe this is supposed to be filtering on the `arrayOfJsonConfig` instead? That array will contain the 'validated' GeoviewLayers information (non-geocore), right?
</blockquote></details>

The reason it's like this is that if a geocore layer in the list processed by the service is in error, it's not returned in the array by the service and no error has been logged. A comment above says: 

// If a geocore layer cannot be found in the array of layers returned by the server, we leave it as is in
// the listOfGeoviewLayerConfig.

We therefore print a message for all geocore layers that remain intact to inform the user that these layers are in error.

The method gives you the choice of eliminating these geocore layers or keeping them. If you eliminate them, the difference in the number of layers in the resulting arrray compared to that of the incoming array is a sign of error. If you keep them, the presence of geocore layers is a sign of error. 
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 265 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-bjyaU4JDIeWTPdE40:-O-bjyaV5FuXtULjB3WE:b-bjela3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7d6aaefd96a444ee52749f708da1b1ccc4a7a600/packages/geoview-core/src/api/config/config-api.ts#L265)):*
> ```XML
>         newListOfGeoviewLayerConfig = newListOfGeoviewLayerConfig.filter((layerConfig) => {
>           if (layerConfig.geoviewLayerType === CV_CONFIG_GEOCORE_TYPE) {
>             logger.logError(`Unable to convert GeoCore layer (Id=${layerConfig.geoviewLayerId}).`);
> ```

The reason why it is like that is 



_Code quote:_
```XML
logger.logError(`Unable to convert GeoCore layer (Id=${layerConfig.geoviewLayerId}).`);
```
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 102 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-bB8szAyeOO6uxpud9:-O-bMHtX1iryVJ8A3oN_:bi2xt2w) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5cb8436173a856c88cb59f7084612572f387e95b/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L102)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we really need this? Once validated we will keep a copy in the store but I am not sure the validation schema function needs it.
</blockquote></details>

Once fully validated, the configuration is no longer the same as the one supplied by the user. It contains the metadata information that the user didn't supply, as well as default values for fields that were left empty.  So, yes, you need to keep the original if you want to be able to return to it and change language, for example.

All clones and spread operators prevent the changes we make from leaking back into the original object, because even if the JSON object is a constant or we forbid parameter reassignment, it's still possible, somehow, to change the properties it contains.

You must remember that if an object contains another object, the encapsulated object is retained **by reference**.  So, if I do:

*const gvMap = providedMapFeatureConfig.map;*
*gvMap.listOfGeoviewLayerConfig =[];*

I'm not only changing gvMap, but also providedMapFeatureConfig.map, because gvMap **refers** to the same object as providedMapFeatureConfig.map.

This behavior applies to class instances as well as to simple JSON onjets.
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 108 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-bJg0x4kp_0uHZ8rnm:-O-bXBIU0L1_AIOzK1mg:b2xq2cw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7d6aaefd96a444ee52749f708da1b1ccc4a7a600/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L108)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

It seems the leak has been reduced to the '.map' content?

If the intention of this class is to be working on a copy of the provided param (the one stored in `#originalgeoviewLayerConfig`), shouldn't it work on the copy of the provided param, not store a copy and work on the provided param?

If the intention is to work on the parameter, it can stay as-is. Might lead to a class-state disconnection later with the attribute though.
</blockquote></details>

The `#originalgeoviewLayerConfig` is a copy that **must not be changed**. If we want to reload the config with a different language, we will use it to reconfigure the instance based on the new language. however, if you have a better idea to keep the original config provided by the user or you don't want to keep it at all, I can remove the clone to `#originalgeoviewLayerConfig`.

Nevertheless, some clone operations and spread operators need to be preserve to avoid leaking back into the original object provided by the user as explained to Johann. Especially the map.listOfGeoviewLayerConfig that will be heavily modified to include the styles and the source.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts` line 62 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-bCmIbBUoyeKTWNjJF:-O-beye-DZ6ir6xHTsUM:b-lxqzfj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5cb8436173a856c88cb59f7084612572f387e95b/packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts#L62)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

From the diagram, this exposed as we should have a function to apply a default config on top a raw raw config made by metadata.
</blockquote></details>

The exposed function needs to be more clearly defined. I say this because the internal mechanism for applying configuration values is as follows:
- We take the user's config;
- All metadata fields are applied to properties of the user's config that don't already have a value;
- Finally, all fields that are left empty and have a default value are populated with the default value.

This is what we call the precedence of configuration data over metadata. In the end, all fields should have a value. 

A default value is applied to an empty field. It is therefore difficult to make another default value pass on a config object that has already undergone the default value process. However, it would be possible to expose a function that would replace fields already initialized by another value.

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265)* status: all files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 298 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-b8rZV9QMZN-kiHOLh:-O-c-gmn1NPtRYfDQPK-:b7qppgx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5cb8436173a856c88cb59f7084612572f387e95b/packages/geoview-core/src/api/config/config-api.ts#L298)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

The mapConfig name is an error. However, it is supposed to be a geoviewLayerConfig. I say that because on the schema, the forEachGeoviewLayer loop is outside the Config API box and you've told me many times that the layers are processed one by one from outside the API. Is it still right?
</blockquote></details>

Forget what I wrote above. In fact this routine shoud be named validateMapConfig based on the first schema you gave me or validateMapConfigAgainstSchema as you said. It's up to you to decide the name you prefere. And you're right the validateLayerConfigs should take a listOfGeoviewLayers and return a validated listOfGeoviewLayers with the errorDetected flag on each config set properly.

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265)* status: all files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 298 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-b8rZV9QMZN-kiHOLh:-O-c1WOY9tIa_YH27z5P:b-ywkqfq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5cb8436173a856c88cb59f7084612572f387e95b/packages/geoview-core/src/api/config/config-api.ts#L298)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Forget what I wrote above. In fact this routine shoud be named validateMapConfig based on the first schema you gave me or validateMapConfigAgainstSchema as you said. It's up to you to decide the name you prefere. And you're right the validateLayerConfigs should take a listOfGeoviewLayers and return a validated listOfGeoviewLayers with the errorDetected flag on each config set properly.
</blockquote></details>

These two methods only validate the config before the metadata fetch.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265)* status: all files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 298 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-b8rZV9QMZN-kiHOLh:-O-f-i4j6VHbQ3X7S6YW:b1w8j9l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5cb8436173a856c88cb59f7084612572f387e95b/packages/geoview-core/src/api/config/config-api.ts#L298)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

These two methods only validate the config before the metadata fetch.
</blockquote></details>

That is good, the name was confusing but we need a the validationAgainstSchema functions(s)
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 264 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-bHWqX3O-SRVBJyCca:-O-ezdemE9edyLg_kIcv:bp52zdh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7d6aaefd96a444ee52749f708da1b1ccc4a7a600/packages/geoview-core/src/api/config/config-api.ts#L264)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

The reason it's like this is that if a geocore layer in the list processed by the service is in error, it's not returned in the array by the service and no error has been logged. A comment above says: 

// If a geocore layer cannot be found in the array of layers returned by the server, we leave it as is in
// the listOfGeoviewLayerConfig.

We therefore print a message for all geocore layers that remain intact to inform the user that these layers are in error.

The method gives you the choice of eliminating these geocore layers or keeping them. If you eliminate them, the difference in the number of layers in the resulting arrray compared to that of the incoming array is a sign of error. If you keep them, the presence of geocore layers is a sign of error.
</blockquote></details>

Why not doing the validation in a sequence, layer by layer. If it is a geocore it will try to convert the layer and if it cant, it will throw error on this layer. Because layers validation (geocore/metadata) is never done in an array... loooks like there is geocore validation mixing in the schema validation. It was like this at first but the diagram moved the geocore withing layer/metadata validation to remove async on the configSchemaValidation.

I think this function should take one layer in entry and return the converted values or undefined and throw error. It can take a uuid or a config (type geocore)... maybe if we pass only the uuid the if geocore will done outside and this function is really just here a uuid,,give me the geoveiw config 
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 108 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-bJg0x4kp_0uHZ8rnm:-O-f1uST8xIzR2BkP9AK:ba2ufaw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7d6aaefd96a444ee52749f708da1b1ccc4a7a600/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L108)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

The `#originalgeoviewLayerConfig` is a copy that **must not be changed**. If we want to reload the config with a different language, we will use it to reconfigure the instance based on the new language. however, if you have a better idea to keep the original config provided by the user or you don't want to keep it at all, I can remove the clone to `#originalgeoviewLayerConfig`.

Nevertheless, some clone operations and spread operators need to be preserve to avoid leaking back into the original object provided by the user as explained to Johann. Especially the map.listOfGeoviewLayerConfig that will be heavily modified to include the styles and the source.
</blockquote></details>

It is why I would do it the other way around... layers object take in parameters url, type and there is a function to createOriginalLayerConfig who create a geoview config from the url, no user values. Because we want user to overwrite the service metadata, we have on this object a function to pass a geoview config who will replace provided values by user and return the JSON to use. For all the creation process, we do not care about user values, just with the last function. The layer config object can have the original config (only from metadata) and the curated one (mix between metadata and user provided config. This way we have 2 distinct functions
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts` line 62 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-bCmIbBUoyeKTWNjJF:-O-f34AfDE9nMIPsffHh:b4rwk0j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5cb8436173a856c88cb59f7084612572f387e95b/packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts#L62)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

The exposed function needs to be more clearly defined. I say this because the internal mechanism for applying configuration values is as follows:
- We take the user's config;
- All metadata fields are applied to properties of the user's config that don't already have a value;
- Finally, all fields that are left empty and have a default value are populated with the default value.

This is what we call the precedence of configuration data over metadata. In the end, all fields should have a value. 

A default value is applied to an empty field. It is therefore difficult to make another default value pass on a config object that has already undergone the default value process. However, it would be possible to expose a function that would replace fields already initialized by another value.
</blockquote></details>

Like my comment above and the diagram, we create config solely from metadata AND default. This is return or store in the object. Then there is another function to apply curatedUserConfig on top of this fully original config

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265)* status: all files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 298 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-b8rZV9QMZN-kiHOLh:-O-fwSTG5LSlEo315nMm:b-9d1x7p) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5cb8436173a856c88cb59f7084612572f387e95b/packages/geoview-core/src/api/config/config-api.ts#L298)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

That is good, the name was confusing but we need a the validationAgainstSchema functions(s)
</blockquote></details>

I will correct the method name.
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 264 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-bHWqX3O-SRVBJyCca:-O-fwDLM2cWfYMAJDoX2:b-vrl0mt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7d6aaefd96a444ee52749f708da1b1ccc4a7a600/packages/geoview-core/src/api/config/config-api.ts#L264)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why not doing the validation in a sequence, layer by layer. If it is a geocore it will try to convert the layer and if it cant, it will throw error on this layer. Because layers validation (geocore/metadata) is never done in an array... loooks like there is geocore validation mixing in the schema validation. It was like this at first but the diagram moved the geocore withing layer/metadata validation to remove async on the configSchemaValidation.

I think this function should take one layer in entry and return the converted values or undefined and throw error. It can take a uuid or a config (type geocore)... maybe if we pass only the uuid the if geocore will done outside and this function is really just here a uuid,,give me the geoveiw config
</blockquote></details>

Do you think this fonction should... or you want this function to...
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 108 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-bJg0x4kp_0uHZ8rnm:-O-ft7JBAaVBlHO3NjtV:bbhxs42) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7d6aaefd96a444ee52749f708da1b1ccc4a7a600/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L108)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It is why I would do it the other way around... layers object take in parameters url, type and there is a function to createOriginalLayerConfig who create a geoview config from the url, no user values. Because we want user to overwrite the service metadata, we have on this object a function to pass a geoview config who will replace provided values by user and return the JSON to use. For all the creation process, we do not care about user values, just with the last function. The layer config object can have the original config (only from metadata) and the curated one (mix between metadata and user provided config. This way we have 2 distinct functions
</blockquote></details>

So, instead of using defaultsDeep and start with the userConfig and insert in it metadata config for undefined fields in the user config and then insert default config for fields of the resulting config that are still undefined, you want me to use the lodash merge function and start with the default config and use the metadata to overwrite default values when the metadata config has another value for a field and then use the user config to overwrite the resulting config when the user provide a value for a field.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts` line 62 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-bCmIbBUoyeKTWNjJF:-O-fv0h773Jl0UYqIaF1:bfdx6hx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5cb8436173a856c88cb59f7084612572f387e95b/packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts#L62)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Like my comment above and the diagram, we create config solely from metadata AND default. This is return or store in the object. Then there is another function to apply curatedUserConfig on top of this fully original config
</blockquote></details>

The diagram doesn't provide enough detail on how things should be implemented. I need a detailed implementation description for each functionality to be implemented otherwise we will dance the cha cha for a long time.

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265)* status: all files reviewed, 5 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 264 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-bHWqX3O-SRVBJyCca:-O-fvZ4kDKvSassdtXJH:b-slsrrz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7d6aaefd96a444ee52749f708da1b1ccc4a7a600/packages/geoview-core/src/api/config/config-api.ts#L264)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Do you think this fonction should... or you want this function to...
</blockquote></details>

I think I was confused with the 3 arrays being worked on `listOfGeoviewLayerConfig`,  `geocoreArrayOfKeys` and `arrayOfJsonConfig`. And then `newListOfGeoviewLayerConfig`.

Okay.
Do note that the function getGVConfigFromUUIDs() throws exceptions when things fail also. It'd be better to regroup the failure logic together. That is, when a geocore translation to geoviewlayerconfig has failed, for any reason, have the code that maintains the general  'map config' regrouped.
I can be wrong, but it seems like `getGVConfigFromUUIDs` can both (1) throw or (2) not do its job and we have like 2 different ways of handling the issue (the catch and the 2 loops). Is that it?
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 108 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-bJg0x4kp_0uHZ8rnm:-O-fptN-3f-4L_kfliVO:bk8wgg1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7d6aaefd96a444ee52749f708da1b1ccc4a7a600/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L108)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It is why I would do it the other way around... layers object take in parameters url, type and there is a function to createOriginalLayerConfig who create a geoview config from the url, no user values. Because we want user to overwrite the service metadata, we have on this object a function to pass a geoview config who will replace provided values by user and return the JSON to use. For all the creation process, we do not care about user values, just with the last function. The layer config object can have the original config (only from metadata) and the curated one (mix between metadata and user provided config. This way we have 2 distinct functions
</blockquote></details>

Commenting on this thread (as I'm the one that started this one) for the comment above about the reason for the cloning.

Hmm, isn't that the whole point of the cloneDeep? To make sure all internal nested structures are also cloned? This is surprising behavior.

I feel that there is something else at play here causing you to clone multiple times. My guess is that you're working with internal class instances? If so, then yes, those need to have their own ways of cloning themselves to retain their essence. One shouldn't use cloneDeep to clone class instances.

By the way, eventually, we should stop using `cloneDeep` and use `structuredClone` instead. JavaScript supports cloning primitives natively now (and it even supports circular references!).

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265)* status: all files reviewed, 5 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 264 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-bHWqX3O-SRVBJyCca:-O-g2h7W3PdldgQ-UB8D:b-e4s8gr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7d6aaefd96a444ee52749f708da1b1ccc4a7a600/packages/geoview-core/src/api/config/config-api.ts#L264)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I think I was confused with the 3 arrays being worked on `listOfGeoviewLayerConfig`,  `geocoreArrayOfKeys` and `arrayOfJsonConfig`. And then `newListOfGeoviewLayerConfig`.

Okay.
Do note that the function getGVConfigFromUUIDs() throws exceptions when things fail also. It'd be better to regroup the failure logic together. That is, when a geocore translation to geoviewlayerconfig has failed, for any reason, have the code that maintains the general  'map config' regrouped.
I can be wrong, but it seems like `getGVConfigFromUUIDs` can both (1) throw or (2) not do its job and we have like 2 different ways of handling the issue (the catch and the 2 loops). Is that it?
</blockquote></details>

Oh, I see how it calls the service one time with all geocore ids now.. maybe adjusting that to call the service for each geocore uuids would be sufficient to handle errors per layer basis?

Anyways, I can resolve this once the implementation choice is made.

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265)* status: all files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 264 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-bHWqX3O-SRVBJyCca:-O-kzgGKAV_OX0DIlrgY:bhyqax9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7d6aaefd96a444ee52749f708da1b1ccc4a7a600/packages/geoview-core/src/api/config/config-api.ts#L264)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Oh, I see how it calls the service one time with all geocore ids now.. maybe adjusting that to call the service for each geocore uuids would be sufficient to handle errors per layer basis?

Anyways, I can resolve this once the implementation choice is made.
</blockquote></details>

You're right, getGVConfigFromUUIDs receive an array of geocore ids. If they are all wrong or an other kind of error happens it returns through an exception. In the specific case where all geocore ids cannot be found, the error says "No layers returned by GeoCore service". However, if only one geocore id can be converted, no error is raised and if the array passed to getGVConfigFromUUIDs was let's say of length 10, the output array is of length 1. The loop is mainly there to print 9 errors wit the geocore id that failled. At the same time, if the caller asked to filter the eroneous layers, we removed them from the list returned.
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 108 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265#-O-bJg0x4kp_0uHZ8rnm:-O-kvaECD-oQU-rsJIuh:bpbcq16) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7d6aaefd96a444ee52749f708da1b1ccc4a7a600/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L108)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Commenting on this thread (as I'm the one that started this one) for the comment above about the reason for the cloning.

Hmm, isn't that the whole point of the cloneDeep? To make sure all internal nested structures are also cloned? This is surprising behavior.

I feel that there is something else at play here causing you to clone multiple times. My guess is that you're working with internal class instances? If so, then yes, those need to have their own ways of cloning themselves to retain their essence. One shouldn't use cloneDeep to clone class instances.

By the way, eventually, we should stop using `cloneDeep` and use `structuredClone` instead. JavaScript supports cloning primitives natively now (and it even supports circular references!).
</blockquote></details>

Intersting, structuredClone is a JavaScript built-in method used to clone objects in a deep manner, preserving their structure and properties. It allows you to copy an object, including its sub-objects, without sharing references between the original and the copy. This ensures that modifications made to the copy do not affect the original, and vice versa.

Should we add a general TODO or create an issue asking to do this replacment?

Concerning the double clone, it was decided in our last scrum to keep only clone operations needed to ensure that modifications made to the copy do not affect the original, and vice versa. I removed the #originalgeoviewLayerConfig clone and property in this PR.

**Review by Alex-NRCan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265)* status: all files reviewed, 3 unresolved discussions (waiting on @jolevesq)

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2265)* status: all files reviewed, 3 unresolved discussions (waiting on @jolevesq)

**Pull request merged**
