### PR TITLE
feat(appBar): add tab in app bar  #closes1280

### LINKED ISSUE #1280: [FEATURE] Link side panel and footer panel
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

_No response_

### User Story

As a user, I would like to take a component like legend and have open as a appbar panel.

Need more clarifications on this.

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Implement guide tab inside app bar

Fixes #1280

Issue created for mobile scrolling https://github.com/Canadian-Geospatial-Platform/geoview/issues/1819

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/raw-feature-info.html
# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 8 of 13 files at r1, 6 of 9 files at r2, 5 of 10 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811)* status: 16 of 22 files reviewed, 7 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 55 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811#-NqlxwMS3XxZHkgkAlA-:-NqlxwMS3XxZHkgkAlA0:b8phzep) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2576a996b8df446a0d4be61172ffa9ac67698299/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L55)):*
> ```XML
>   const appBarComponents = useUIAppbarComponents();
>   const { hideClickMarker } = useMapStoreActions();
>   const activeFooterTabId = useUIActiveFooterBarTabId();
> ```

Why are we using footer id in app bar?
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 154 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811#-Nqly7rdEqbm67meTfSW:-Nqly7rdEqbm67meTfSX:b8y5f70) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2576a996b8df446a0d4be61172ffa9ac67698299/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L154)):*
> ```XML
> 
>     // open appbar detail drawer when click on map.
>     if (activeFooterTabId === 'details' && buttonPanelGroups?.details?.AppbarPanelButtonDetails?.panel) {
> ```

We should have the same logic for open appbar control... Technically, we should not have details in footer and in appbar at the same time
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 189 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811#-NqlyQxW9wfbL2e9EKpo:-NqlyQxW9wfbL2e9EKpp:b-os54xp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2576a996b8df446a0d4be61172ffa9ac67698299/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L189)):*
> ```XML
>   useEffect(() => {
>     // Log
>     logger.logTraceUseEffect('APP-BAR - create group of appbar buttons from footer bar group', mapId);
> ```

Should be no mention of footer... appbar can work with no footer
___
*[`packages/geoview-core/src/core/components/common/layout.tsx` line 84 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811#-Nqm-R0d9toK1G1OZHt7:-Nqm-R0d9toK1G1OZHt8:b75409q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2576a996b8df446a0d4be61172ffa9ac67698299/packages/geoview-core/src/core/components/common/layout.tsx#L84)):*
> ```XML
> 
>   // // If we're on mobile
>   // if (theme.breakpoints.down('md')) {
> ```

Do we need dead code?
___
*[`packages/geoview-core/src/core/components/common/layout.tsx` line 44 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811#-NqnXPv-ArWpF0rQEJlS:-NqnXPv-ArWpF0rQEJlT:b-rzqjo4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/849287e23489a62e4878b5ce80818bf1055ce467/packages/geoview-core/src/core/components/common/layout.tsx#L44)):*
> ```XML
>     (layer: LayerListEntry): void => {
>       onLayerListClicked?.(layer);
>       console.log('change is firing..');
> ```

No console log, use logger with proper level
___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 282 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811#-Nqm0asc4JiJMAxUPtMO:-Nqm0asc4JiJMAxUPtMP:bfpt7ds) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2576a996b8df446a0d4be61172ffa9ac67698299/packages/geoview-core/src/core/components/details/details-panel.tsx#L282)):*
> ```XML
>       if (anotherLayerEntry) {
>         // Log
>         // logger.logDebug('DETAILS-PANEL', 'select another', memoLayerSelectedItem, anotherLayerEntry.layerPath);
> ```

Can you uncomment logger
___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 287 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811#-Nqm0doo-Hzu9L8vjVLY:-Nqm0doo-Hzu9L8vjVLZ:bfpt7ds) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2576a996b8df446a0d4be61172ffa9ac67698299/packages/geoview-core/src/core/components/details/details-panel.tsx#L287)):*
> ```XML
>       } else {
>         // Log
>         // logger.logDebug('DETAILS-PANEL', 'select none', memoLayerSelectedItem);
> ```

Can you uncomment logger

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 9 files at r2, 2 of 3 files at r3, 1 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811)* status: 20 of 22 files reviewed, 7 unresolved discussions (waiting on @kaminderpal)

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811)* status: 18 of 23 files reviewed, 7 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 55 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811#-NqlxwMS3XxZHkgkAlA-:-NqnZumL2x3rVtcsfC4H:b1400i3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2576a996b8df446a0d4be61172ffa9ac67698299/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L55)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why are we using footer id in app bar?
</blockquote></details>

add TODO for this
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 154 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811#-Nqly7rdEqbm67meTfSW:-NqnZxNr0ernWZkCRTKx:b1400i3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2576a996b8df446a0d4be61172ffa9ac67698299/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L154)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should have the same logic for open appbar control... Technically, we should not have details in footer and in appbar at the same time
</blockquote></details>

add TODO for this
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 189 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811#-NqlyQxW9wfbL2e9EKpo:-NqnZyqyBRtzfEJdIJNB:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2576a996b8df446a0d4be61172ffa9ac67698299/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L189)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should be no mention of footer... appbar can work with no footer
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/common/layout.tsx` line 84 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811#-Nqm-R0d9toK1G1OZHt7:-Nqn_0m4D0FHWP4jAPAM:b-dfnjl5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2576a996b8df446a0d4be61172ffa9ac67698299/packages/geoview-core/src/core/components/common/layout.tsx#L84)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we need dead code?
</blockquote></details>

add investigation for this
___
*[`packages/geoview-core/src/core/components/common/layout.tsx` line 44 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811#-NqnXPv-ArWpF0rQEJlS:-Nqn_-nS8jD3CYOkTsTx:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/849287e23489a62e4878b5ce80818bf1055ce467/packages/geoview-core/src/core/components/common/layout.tsx#L44)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

No console log, use logger with proper level
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 282 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811#-Nqm0asc4JiJMAxUPtMO:-Nqn_54UA5cW8EgnV5d7:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2576a996b8df446a0d4be61172ffa9ac67698299/packages/geoview-core/src/core/components/details/details-panel.tsx#L282)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you uncomment logger
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 287 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811#-Nqm0doo-Hzu9L8vjVLY:-Nqn_5Pl5QD9OBVT5ZQR:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2576a996b8df446a0d4be61172ffa9ac67698299/packages/geoview-core/src/core/components/details/details-panel.tsx#L287)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you uncomment logger
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r4, 2 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811)* status: 21 of 23 files reviewed, 4 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/common/enlarge-button-style.tsx` line 30 at r6](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811#-NqnaN90Ev6ZUoWmGs5K:-NqnaN91-ATK3-wn_O4w:bwichhx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63d87bb7e81bb5a7a2101c318410e9ee6f4bfade/packages/geoview-core/src/core/components/common/enlarge-button-style.tsx#L30)):*
> ```XML
>     width: '7rem !important',
>   },
>   appBarEnlargeBtn: {
> ```

Put same name appBarEnlargeButton, like enlarege for for footer not Btn

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811)* status: 22 of 23 files reviewed, 1 unresolved discussion (waiting on @kaminderpal)

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811)* status: 22 of 23 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/common/enlarge-button-style.tsx` line 30 at r6](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811#-NqnaN90Ev6ZUoWmGs5K:-Nqndcok71pwnsnr3Bdn:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63d87bb7e81bb5a7a2101c318410e9ee6f4bfade/packages/geoview-core/src/core/components/common/enlarge-button-style.tsx#L30)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put same name appBarEnlargeButton, like enlarege for for footer not Btn
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 1 files at r7, 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811)* status: 22 of 23 files reviewed, all discussions resolved (waiting on @kaminderpal)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1811)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Pull request merged**
