### PR TITLE
fix(load): fixes basemap loading issues

### LINKED ISSUE #1030: [BUG] Infinite looping when launching the app, happening on occasion
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Sometimes**, upon launching the web application, the system enters an infinite loop of tile requests. It can be noticed by the times on the west side of Canada being blurred (as seen in the yellow square in the screenshot below) and by opening the Chrome network tab and looking at the requests happening. The screenshot below shows the network tab after 1 min after launch. Many tiles are requested more than once, 4022 requests were made, about 40MB were downloaded. 
image

This additional screenshot below shows the state after 7.5 minutes, over 10,000 requests were made for the same tiles(!):
image

### Expected Behavior

Each tile is requested only once.

### Steps To Reproduce

My initialization config is below, but **this behavior doesn't happen all the time(!)**:
```
const map_config = {
	'map': {
		'interaction': 'dynamic',
		'viewSettings': {
			'zoom': 4,
			'minZoom': 2,
			'maxZoom': 12,
			'center': [-100, 60],
			'projection': 3978
		},
		'basemapOptions': {
			'basemapId': 'simple',
			'shaded': true,
			'labeled': false
		},
		'listOfGeoviewLayerConfig': []
	},
	'theme': 'dark',
	'components': ['app-bar', 'nav-bar', 'north-arrow', 'overview-map', 'footer-bar'],
	'corePackages': ['layers-panel'],
	'suportedLanguages': ['en', 'fr']
};
```

*EDITED*: to remove the listOfGeoviewLayerConfig array values which are outside the scope for this issue

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #1030

# Description

Changed overview map to use transport map with no shading or labels instead of matching base of main map.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Checked most test pages with and without disable cache.

# Checklist:

- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1059)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1059)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @DamonU2)

___
*[`packages/geoview-core/src/geo/layer/basemap/basemap.ts` line 583 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1059#-NV6julb6nwXXa3q90Vv:-NV6julb6nwXXa3q90Vw:bpuxrlr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fb8b495665d6d368a25dc1eed6eef4d0bb14a458/packages/geoview-core/src/geo/layer/basemap/basemap.ts#L583)):*
> ```XML
>   loadDefaultBasemaps = async (): Promise<TypeBasemapProps | undefined> => {
>     const basemap = await this.createCoreBasemap(this.basemapOptions);
>     const overviewBasemap = await this.createCoreBasemap({ basemapId: 'transport', shaded: false, labeled: false });
> ```

From your test, should we keep label?

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1059)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/basemap/basemap.ts` line 583 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1059#-NV6julb6nwXXa3q90Vv:-NV7Y1-SBvZuw_6fRAIL:b5s7r3a) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fb8b495665d6d368a25dc1eed6eef4d0bb14a458/packages/geoview-core/src/geo/layer/basemap/basemap.ts#L583)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

From your test, should we keep label?
</blockquote></details>

I don't think that their is any reason to, the labels are never visible

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1059)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @DamonU2)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1059)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
