### PR TITLE
Handling empty layers

### LINKED ISSUE #2181: [BUG]  Handling no layers in the layers tab
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

if there are no layers currently this is what the UI looks like.

image

### Expected Behavior

Either default to 'Add Layer' functionality or add a message clearly communicating that there are no layers - instead of just a blank left side.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### LINKED ISSUE #2188: [BUG, UI] Make buttons on the right look like buttons on the left
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Buttons on the right look too big; especially when viewed within the AppBar.|

image

### Expected Behavior

Make the buttons on he right look like buttons on the left.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

This PR does the following;

- [x] In layers - it adds remove layers to all layers that are in error.
- [x] If there are no layers - it displays the right message in legend.
- [x] If there are layers - it defaults to 'Add layer' tab in layers.
- [x] Adds responsive layer button components in uses it for top buttons in the responsive grid.

Fixes #2181 
Fixes #2188

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://cphelefu.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189)

### CODE REVIEW

**Review by kaminderpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189)* status: 0 of 11 files reviewed, 5 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/common/responsive-button.tsx` line 30 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzTebIP0YQ1dIMroPBj:-NzTebIP0YQ1dIMroPBk:bmt66vp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/553501d08b044dd28b6a6b2c619a37e2d28b96b9/packages/geoview-core/src/core/components/common/responsive-button.tsx#L30)):*
> ```XML
>     };
> 
>     window.addEventListener('resize', handleResize);
> ```

We dnt need this event, we can levarage `useMapSize` hook, which have abstracted this event handler.
___
*[`packages/geoview-core/src/core/components/common/responsive-button.tsx` line 49 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzTf2Gt3tFP50jcrQvv:-NzTf2Gt3tFP50jcrQvw:bm3wysx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/553501d08b044dd28b6a6b2c619a37e2d28b96b9/packages/geoview-core/src/core/components/common/responsive-button.tsx#L49)):*
> ```XML
>         {children}
>       </Button>
>     </Tooltip>
> ```

This `If` block has lot of duplicate jsx, we can clean this up



_Code snippet:_
```XML
<Tooltip title={t(tooltipKey)} placement="top" enterDelay={1000}>
      <Button color="primary" variant={variant} startIcon={startIcon} onClick={onClick} className="OutlinedButton" {...rest}>
        {screenWidth < breakpoint ? children : ''}
      </Button>
    </Tooltip>
```
___
*[`packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx` line 133 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzTfYLjC77YYpzB315w:-NzTfYLjC77YYpzB315x:bi6vnmq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3df1e46b193971b6599099a1124fc0686650497f/packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx#L133)):*
> ```XML
>           className="buttonFilledOutline"
>           startIcon={isEnlarged ? <ArrowForwardIcon /> : <ArrowBackIcon />}
>           sx={{ height: '40px', borderRadius: '1.5rem', boxShadow: 'none', [theme.breakpoints.down('md')]: { display: 'none' } }}
> ```

Any reason why you remove Show/Hide of button css solution and replace it with js solution?
___
*[`packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx` line 150 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzTfnTC7EtDCJ-9xmnp:-NzTfnTC7EtDCJ-9xmnq:bl0cypi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/553501d08b044dd28b6a6b2c619a37e2d28b96b9/packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx#L150)):*
> ```XML
>       if (!fullWidth && !isRightPanelVisible) {
>         return null; // Return null for another hiding condition
>       }
> ```

can we combine these 2 if blocks both have same return type.
Also i feel like comments like `// Return null for another hiding condition` doesnt serve any purpose, we should have proper jsDocs comment for this function and explain these conditions there.
___
*[`packages/geoview-core/src/core/components/legend/legend.tsx` line 112 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzTh-fE-n0lD1jBxf8k:-NzTh-fE-n0lD1jBxf8l:bhrlomt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/553501d08b044dd28b6a6b2c619a37e2d28b96b9/packages/geoview-core/src/core/components/legend/legend.tsx#L112)):*
> ```XML
>       </Box>
>     );
>   }
> ```

We already have this block which handle no legend layers 
 {/* Show legend Instructions when no layer found. */}
        {!legendLayers.length && (
inside container.

Also if put this if block outside of container, css will be diff bcz there is no container wrapper.

**Review by kaminderpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/common/responsive-button.tsx` line 14 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzTrn3g9f7rRXNL4BS3:-NzTrn3g9f7rRXNL4BS4:b-yl9l53) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/14d71080fb12107df5d5529aa4eea16b7dfbd720/packages/geoview-core/src/core/components/common/responsive-button.tsx#L14)):*
> ```XML
>   const { tooltipKey, children, variant, startIcon, onClick, ...rest } = props;
>   const { t } = useTranslation<string>();
>   const breakpoint = 710;
> ```

we can use `const mobileView \= useMediaQuery(theme.breakpoints.down('md'));` for this breakpoint.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx` line 133 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzTfYLjC77YYpzB315w:-NzU4WE74l3R166YTzM0:b-xxcdwj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3df1e46b193971b6599099a1124fc0686650497f/packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx#L133)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

Any reason why you remove Show/Hide of button css solution and replace it with js solution?
</blockquote></details>

Where?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/legend/legend.tsx` line 112 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzTh-fE-n0lD1jBxf8k:-NzU5nRD35HF7TBct-BX:b-8rngw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/553501d08b044dd28b6a6b2c619a37e2d28b96b9/packages/geoview-core/src/core/components/legend/legend.tsx#L112)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

We already have this block which handle no legend layers 
 {/* Show legend Instructions when no layer found. */}
        {!legendLayers.length && (
inside container.

Also if put this if block outside of container, css will be diff bcz there is no container wrapper.
</blockquote></details>

the code is not outside container, it is inside container.

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189)* status: 0 of 13 files reviewed, 6 unresolved discussions (waiting on @jolevesq and @kaminderpal)

___
*[`packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx` line 150 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzTfnTC7EtDCJ-9xmnp:-NzU4jezDiHxJ-sbJ3X4:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/553501d08b044dd28b6a6b2c619a37e2d28b96b9/packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx#L150)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

can we combine these 2 if blocks both have same return type.
Also i feel like comments like `// Return null for another hiding condition` doesnt serve any purpose, we should have proper jsDocs comment for this function and explain these conditions there.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/common/responsive-button.tsx` line 30 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzTebIP0YQ1dIMroPBj:-NzTierd7JdmTUJUiuuq:b-i6ulvv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/553501d08b044dd28b6a6b2c619a37e2d28b96b9/packages/geoview-core/src/core/components/common/responsive-button.tsx#L30)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

We dnt need this event, we can levarage `useMapSize` hook, which have abstracted this event handler.
</blockquote></details>

mapSize monitors the size of the map
___
*[`packages/geoview-core/src/core/components/common/responsive-button.tsx` line 49 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzTf2Gt3tFP50jcrQvv:-NzU4BgN6cIGSQ7Ti7eT:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/553501d08b044dd28b6a6b2c619a37e2d28b96b9/packages/geoview-core/src/core/components/common/responsive-button.tsx#L49)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

This `If` block has lot of duplicate jsx, we can clean this up
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/common/responsive-button.tsx` line 14 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzTrn3g9f7rRXNL4BS3:-NzU47us5mYCq7L1rfCn:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/14d71080fb12107df5d5529aa4eea16b7dfbd720/packages/geoview-core/src/core/components/common/responsive-button.tsx#L14)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

we can use `const mobileView \= useMediaQuery(theme.breakpoints.down('md'));` for this breakpoint.
</blockquote></details>

Done.

**Review by kaminderpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189)* status: 0 of 13 files reviewed, 8 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx` line 133 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzTfYLjC77YYpzB315w:-NzU9JBt0LnBDwZ3SIpA:b2jja15) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3df1e46b193971b6599099a1124fc0686650497f/packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx#L133)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Where?
</blockquote></details>

`[theme.breakpoints.down('md')]: { display: 'none' }` in sx prop was used to hide the button based on breakpoint. Now u have remove this and add 



_Code snippet:_
```XML
if (window.innerWidth <= theme.breakpoints.values.md) {
        return null; // Return null if on small screens (down to md)
      }
```
___
*[`packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx` line 150 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzTfnTC7EtDCJ-9xmnp:-NzUA1xzEdIeaX40wvnF:b-fnvb0f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/553501d08b044dd28b6a6b2c619a37e2d28b96b9/packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx#L150)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think we can remove this comment ` // Return null if conditions are met` 
___
*[`packages/geoview-core/src/ui/button/button.tsx` line 48 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzUBeZ47At-7a1noZOi:-NzUBeZ47At-7a1noZOj:b-qq9zj7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/16e23545ad2c24b97abed8cc6b87c3b0a67c63d8/packages/geoview-core/src/ui/button/button.tsx#L48)):*
> ```XML
>         id={id}
>         size={size || 'medium'}
>         sx={{ ...sx }}
> ```

we dnt need spread operator, can be written as sx={sx} or just sx
___
*[`packages/geoview-core/src/ui/button/button.tsx` line 58 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzUCSHP8k9VqVYfnuwO:-NzUCSHP8k9VqVYfnuwP:b-d5rx7g) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/16e23545ad2c24b97abed8cc6b87c3b0a67c63d8/packages/geoview-core/src/ui/button/button.tsx#L58)):*
> ```XML
>         endIcon={endIcon}
>       >
>         {!(makeResponsive && mobileView) && children}
> ```

When value is `falsy`. On UI it might render `undefined`
___
*[`packages/geoview-core/src/core/components/common/responsive-button.tsx` line 30 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzTebIP0YQ1dIMroPBj:-NzUC0qN3pCdhVoShu35:b-spbwlj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/553501d08b044dd28b6a6b2c619a37e2d28b96b9/packages/geoview-core/src/core/components/common/responsive-button.tsx#L30)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

mapSize monitors the size of the map
</blockquote></details>

yes it does, but we can leverage `useMapSize` from store,  this way we dnt need to write anymore resize event handler in ur codebase.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx` line 133 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzTfYLjC77YYpzB315w:-NzUMRe-9UHm2UxoGvow:b-hzvotb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3df1e46b193971b6599099a1124fc0686650497f/packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx#L133)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

`[theme.breakpoints.down('md')]: { display: 'none' }` in sx prop was used to hide the button based on breakpoint. Now u have remove this and add
</blockquote></details>

Oh yes. If you use CSS - the button is still rendered just not displayed.
If the button is part of a ButtonGroup and it is the last one - it looks like an error in the UI. We end up missing rounded corners on the last displayed button.

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189)* status: 0 of 13 files reviewed, 8 unresolved discussions (waiting on @jolevesq and @kaminderpal)

___
*[`packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx` line 150 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzTfnTC7EtDCJ-9xmnp:-NzUMqJM8t-7oUi9Fprp:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/553501d08b044dd28b6a6b2c619a37e2d28b96b9/packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx#L150)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

I think we can remove this comment ` // Return null if conditions are met`
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/button/button.tsx` line 48 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzUBeZ47At-7a1noZOi:-NzUMxuj7XXUDm-joiUA:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/16e23545ad2c24b97abed8cc6b87c3b0a67c63d8/packages/geoview-core/src/ui/button/button.tsx#L48)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

we dnt need spread operator, can be written as sx={sx} or just sx
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/button/button.tsx` line 58 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzUCSHP8k9VqVYfnuwO:-NzUNAmxBKD77QilHKeY:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/16e23545ad2c24b97abed8cc6b87c3b0a67c63d8/packages/geoview-core/src/ui/button/button.tsx#L58)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

When value is `falsy`. On UI it might render `undefined`
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/common/responsive-button.tsx` line 30 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzTebIP0YQ1dIMroPBj:-NzUND0n4T9jKvMtPZJx:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/553501d08b044dd28b6a6b2c619a37e2d28b96b9/packages/geoview-core/src/core/components/common/responsive-button.tsx#L30)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

yes it does, but we can leverage `useMapSize` from store,  this way we dnt need to write anymore resize event handler in ur codebase.
</blockquote></details>

Done.

**Review by kaminderpal — APPROVED** [review]
:lgtm:

> Reviewed 5 of 11 files at r1, 1 of 3 files at r2, 3 of 6 files at r4, 3 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-:-NzUmEZ57KtuqP9mWmdS:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, 1 of 3 files at r2, 3 of 6 files at r4, 2 of 4 files at r5, 2 of 2 files at r6, 2 of 3 files at r7, 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189)* status: all files reviewed, 1 unresolved discussion (waiting on @cphelefu)

___
*[`packages/geoview-core/public/locales/en/translation.json` line 81 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzUpB4mCCnhsnorTkKx:-NzUpB4mCCnhsnorTkKy:bq0drlw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4bc34cfbe57db60d12aadd27617b1ac174a9f57a/packages/geoview-core/public/locales/en/translation.json#L81)):*
> ```JSON
>     "noLayersAdded": "No layers added to the map",
>     "noLayersAddedDescription": "Add layers to the map by clicking on the 'Layers' button and adding the layers you want to display.",
>     "itemsCount": "{count} of {totalCount} classes",
> ```

I think this should not be removed. For next line, remove in fr file as well. I se there one on top with same info... if not use delete in fr

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189)* status: all files reviewed, 2 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/public/locales/en/translation.json` line 77 at r8](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzUqiNZ0YYER9FldbAA:-NzUqiNZ0YYER9FldbAB:b-s0wjoj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/15bde90325320d49b3581a9ccbf489f4c092c20b/packages/geoview-core/public/locales/en/translation.json#L77)):*
> ```JSON
>     "highlightLayer": "Highlight layer",
>     "subLayersCount": "{count} sub-layers",
>     "itemsCount": "{count} of {totalCount} items",
> ```

Should be class not item

**Comment by cphelefu** [comment]
*[`packages/geoview-core/public/locales/en/translation.json` line 77 at r8](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzUqiNZ0YYER9FldbAA:-NzUrpwEDsoNrngNtGEt:b20s3ij) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aae916714c097414e640999ca5ee1cf8212b7064/packages/geoview-core/public/locales/en/translation.json#L77)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should be class not item
</blockquote></details>

Not sure I understand. I didnt change this. It always saif 'items'.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/public/locales/en/translation.json` line 81 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzUpB4mCCnhsnorTkKx:-NzUrznz0KQmPme8ZW0n:bisnv2v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4bc34cfbe57db60d12aadd27617b1ac174a9f57a/packages/geoview-core/public/locales/en/translation.json#L81)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think this should not be removed. For next line, remove in fr file as well. I se there one on top with same info... if not use delete in fr
</blockquote></details>

This was removed because it was duplicated.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189)* status: all files reviewed, 2 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/public/locales/en/translation.json` line 77 at r8](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2189#-NzUqiNZ0YYER9FldbAA:-NzY-BvZ7QiNBlsKhnfF:b-y3qad3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aae916714c097414e640999ca5ee1cf8212b7064/packages/geoview-core/public/locales/en/translation.json#L77)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Not sure I understand. I didnt change this. It always saif 'items'.
</blockquote></details>

But it needs to be classes, I will update in my PR

**Pull request merged**
