### PR TITLE
feat(view): Update to view settings

### LINKED ISSUE #1586: [BUG] default extent and max extent schema
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

map is not centered on extent coordinates if provided in config. At the same time, extent is not restricted. We need max extent on our schema to restrict panning

### Expected Behavior

If provided, the extent should be use to set view area and zoom level.
If provided, the maxExtent should be use to restrict panning

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### LINKED ISSUE #1969: [FEATURE] Automatic Zoom to Content
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Geo.ca

### User Story

As a map creator, I would like my map to zoom automatically to content exent

### Implementation UI

We already have the function to zoom to a layer extent. In the same manner, we need a function to aggregate all bounds and zoom automatically on load. To do this we need a new setting in the view section of our schema

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #1969
Closes #1586

# Description

Added additional options to set initial view:
- zoomAndCenter: replaces separate zoom and center parameters
- extent: zooms to provided extent
- layerIds: uses bounds of provided layer ID's for initial view
Extent changed to maxExtent, default extents added for LCC and web mercator.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

zoomAndCenter: https://damonu2.github.io/geoview/image-static.html - [6, [-90, 50]]
extent: https://damonu2.github.io/geoview/projections.html#HPRJ1 - [-90, 45, -65, 70]
layerIds: https://damonu2.github.io/geoview/raw-feature-info.html - 
['polygons.json', 'lines.json']

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042)

### CODE REVIEW

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042)* status: 4 of 78 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/schema.json` line 1593 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042#-NwGPDU3EbaC5wLQFEfl:-NwGT8tl7-KGXmJ-xYeT:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/28c7489eb498fbf00a1b96e431e573054796bca4/packages/geoview-core/schema.json#L1593)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We need to have same default in the config validation section....
</blockquote></details>

Done.
___
*[`packages/geoview-core/schema.json` line 1648 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042#-NwGQiUj0a-8YAEefqAn:-NwGRvu75JqseyE30NLT:b478vmf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/28c7489eb498fbf00a1b96e431e573054796bca4/packages/geoview-core/schema.json#L1648)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Instead of array you did not want to keep center and zoom object. This way the code for store and and map-viewer would staty the same except popreties is not in initialViewDettings
</blockquote></details>

I did that initially, but I thought that it was much clearer for the config this way. We could split them, and have zoomAndCenter be an object with two properties, but that seems less clear.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042)* status: 4 of 78 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/schema.json` line 1648 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042#-NwGQiUj0a-8YAEefqAn:-NwGTgvOD-gsunO7GEcK:b-85usdf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/28c7489eb498fbf00a1b96e431e573054796bca4/packages/geoview-core/schema.json#L1648)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

I did that initially, but I thought that it was much clearer for the config this way. We could split them, and have zoomAndCenter be an object with two properties, but that seems less clear.
</blockquote></details>

You have point, if I am the only one who comment on this we can keep this way

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042)* status: 4 of 78 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/schema.json` line 1593 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042#-NwGPDU3EbaC5wLQFEfl:-NwGTvN-ATHbuN5_MuEy:boy6v8q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/28c7489eb498fbf00a1b96e431e573054796bca4/packages/geoview-core/schema.json#L1593)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

For this comment, I meant if your number a better, we should adjust validation :-)

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 78 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042)* status: 10 of 78 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 357 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042#-NwGVUkB3JL-1HnjomPA:-NwGVUkC0XPiTx5Laq8J:b3aqbxu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3df133be44c348ba68f3f95811b043861468df26/packages/geoview-core/src/core/utils/config/config-validation.ts#L357)):*
> ```XML
>    * @param {AnyValidateFunction<unknown>} validate The Ajv validator.
>    * @param {any} objectAffected Object that was validated.
>    * @private
> ```

Bring back the @private in JSDOC because function is prefix by # that means private.... for all modification in this file
@ychoquet is this file been moved to your config folder? We need too apply same modification if so.
___
*[`packages/geoview-core/src/core/utils/config/reader/url-config-reader.ts` line 166 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042#-NwGW6hK28POddnFjHTa:-NwGW6hK28POddnFjHTb:b-qlb9as) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/210cf05634b7a382748216b3b27d7f88bbe6076f/packages/geoview-core/src/core/utils/config/reader/url-config-reader.ts#L166)):*
> ```XML
>           interaction: urlParams.i as TypeInteraction,
>           viewSettings: {
>             initialView: {
> ```

@ychoquet  same here..... we need link the validation for tha map to the new config object in your next PR. At the moment if we have nolayers it is fine but map should be using new config correctly and we shoud remove the old stuff. When it is done we start ftaching the esri layer
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 776 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042#-NwGWaPyCKtgB1yduqqE:-NwGWaPyCKtgB1yduqqF:bo7sw8h) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/210cf05634b7a382748216b3b27d7f88bbe6076f/packages/geoview-core/src/geo/layer/layer.ts#L776)):*
> ```XML
>    * @returns {Extent} The overall extent.
>    */
>   getExtentOfMultipleLayers(layerIds: string[] = Object.keys(this.registeredLayers)): Extent {
> ```

Can you add some spacing and comments
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 759 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042#-NwGWfamAyTSLz1BN8bJ:-NwGWfamAyTSLz1BN8bK:bybjzio) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/210cf05634b7a382748216b3b27d7f88bbe6076f/packages/geoview-core/src/geo/map/map-schema-types.ts#L759)):*
> ```XML
>  *  Definition of the initial view settings.
>  */
> export type TypeInitialViewSettings = {
> ```

@ychoquet this need to make its way to your config. Like I said after your current PR it should be the stuff to do
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 591 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042#-NwGX5H83l4GbTqQ5gsU:-NwGX5H83l4GbTqQ5gsV:bu7ie3h) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/210cf05634b7a382748216b3b27d7f88bbe6076f/packages/geoview-core/src/geo/map/map-viewer.ts#L591)):*
> ```XML
>             const layerExtents = this.layer.getExtentOfMultipleLayers(this.mapFeaturesConfig.map.viewSettings.initialView.layerIds);
>             // Disabling to avoid unnecessary complication
>             // eslint-disable-next-line @typescript-eslint/no-floating-promises
> ```

To remove this eslint You need to handle the promise explicitly I think by adding a .catch((error) => logger ...

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042)* status: 10 of 78 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan, @jolevesq, @Private, and @ychoquet)

___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 357 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042#-NwGVUkB3JL-1HnjomPA:-NwGZsKT1XAaogpvQ8nl:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3df133be44c348ba68f3f95811b043861468df26/packages/geoview-core/src/core/utils/config/config-validation.ts#L357)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Bring back the @private in JSDOC because function is prefix by # that means private.... for all modification in this file
@ychoquet is this file been moved to your config folder? We need too apply same modification if so.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 776 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042#-NwGWaPyCKtgB1yduqqE:-NwGa8O22AiQ8Wh0Lsx3:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/210cf05634b7a382748216b3b27d7f88bbe6076f/packages/geoview-core/src/geo/layer/layer.ts#L776)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add some spacing and comments
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 591 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042#-NwGX5H83l4GbTqQ5gsU:-NwGb6m89sJCLdOu1Upa:b-mp0byy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/210cf05634b7a382748216b3b27d7f88bbe6076f/packages/geoview-core/src/geo/map/map-viewer.ts#L591)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

To remove this eslint You need to handle the promise explicitly I think by adding a .catch((error) => logger ...
</blockquote></details>

Oops, missed the "or" in there, thought I had to take care of each one of those. Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 66 of 78 files at r1, 1 of 2 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2042)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan and @ychoquet)

**Pull request merged**
