### PR TITLE
921 & 922, add element icon and zoom button

### LINKED ISSUE #921: [FEATURE] Add element Icon to details and data
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

As a user, I' would like to see the symbology of me selected feature from map click and data-grid selection

### Implementation UI

For details:
Add the icon to the collapse item
image

For data-grid:
Add a new column with the icon after the selector check box. We can't show/hide this column, it should always be there

### PR DESCRIPTION
**Pull request by dennisfu**
# Description

Adding element icon and zoom button in data grid table

Fixes #921 & #922

## Type of change

- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Footer panel -> data tap : add 2 columns Icon and Zoom, Click the Zoom column icon, would toggling the feature info extent and reset on map

# Checklist:

- [ X ] I have connected the issues(s) to this PR
- [ X ] My code follows the style guidelines of this project
- [ X ] I have performed a self-review of my own code
- [ X ] I have commented my code, particularly in hard-to-understand areas
- [ X ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/965)

### CODE REVIEW

**Comment by dennisfu** [comment]
*[`packages/geoview-core/src/core/components/data-grid/layer-data-grid.tsx` line 188 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/965#-NQjkHkS7ZEeJ9m2e1MQ:-NQkPObC-fJmwHp7PjK9:b-7ql1td) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/543bdd70dc44224e788e67603fa8e252cdcc0e14/packages/geoview-core/src/core/components/data-grid/layer-data-grid.tsx#L188)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

When we zoom out, the icon is not reset
</blockquote></details>

fixed

**Comment by dennisfu** [comment]
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 66 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/965#-NQjkf5Z3wLgan5bLPVA:-NQkPZLZBA6pg2anzulY:b-ony7zt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/543bdd70dc44224e788e67603fa8e252cdcc0e14/packages/geoview-core/src/core/components/details/feature-info.tsx#L66)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This icon info is duplicated in two components. Can we use it form the theme?
</blockquote></details>

there is the iconImg in legend also, without the size and object-fit setting

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/965)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @dennisfu)

___
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 66 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/965#-NQjkf5Z3wLgan5bLPVA:-NQkR-_39LrC-eHj0-cT:b6avvgc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/543bdd70dc44224e788e67603fa8e252cdcc0e14/packages/geoview-core/src/core/components/details/feature-info.tsx#L66)):*
<details><summary><i>Previously, dennisfu (Dennis Fu) wrote…</i></summary><blockquote>

there is the iconImg in legend also, without the size and object-fit setting
</blockquote></details>

Can this be move to theme?

**Comment by dennisfu** [comment]
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 66 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/965#-NQjkf5Z3wLgan5bLPVA:-NQmEkdG34B9eqTBnmwQ:b-br3jm2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/543bdd70dc44224e788e67603fa8e252cdcc0e14/packages/geoview-core/src/core/components/details/feature-info.tsx#L66)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can this be move to theme?
</blockquote></details>

moved to theme

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/965)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @dennisfu)

___
*[`packages/geoview-core/src/core/components/data-grid/layer-data-grid.tsx` line 54 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/965#-NR31eNV63qGSlzGv74a:-NR31eNV63qGSlzGv74b:b-sdh3il) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a2e46ca5d3e71ff62efd15c1dcfd5696435c9995/packages/geoview-core/src/core/components/data-grid/layer-data-grid.tsx#L54)):*
> ```XML
> }
> 
> const useStyles = makeStyles((theme) => ({
> ```

Make style is deprecated. You should be able to use theme file with sxClasses?
___
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 24 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/965#-NR31RarB_8Oaj09tJYS:-NR31RarB_8Oaj09tJYT:b-sdh3il) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a2e46ca5d3e71ff62efd15c1dcfd5696435c9995/packages/geoview-core/src/core/components/details/feature-info.tsx#L24)):*
> ```XML
> import { DetailsProps } from './details';
> 
> const useStyles = makeStyles((theme) => ({
> ```

Make style is deprecated. You should be able to use theme file with sxClasses?
___
*[`packages/geoview-core/src/core/components/legend/legend-icon-list.tsx` line 25 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/965#-NR31jhy6Nx7ckXa-0SC:-NR31jhy6Nx7ckXa-0SD:b-sdh3il) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a2e46ca5d3e71ff62efd15c1dcfd5696435c9995/packages/geoview-core/src/core/components/legend/legend-icon-list.tsx#L25)):*
> ```XML
> } from '../../types/cgpv-types';
> 
> const useStyles = makeStyles((theme) => ({
> ```

Make style is deprecated. You should be able to use theme file with sxClasses?

**Comment by dennisfu** [comment]
*[`packages/geoview-core/src/core/components/data-grid/layer-data-grid.tsx` line 54 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/965#-NR31eNV63qGSlzGv74a:-NR3BGpBEkm-DWcKTzzx:bvrkukt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a2e46ca5d3e71ff62efd15c1dcfd5696435c9995/packages/geoview-core/src/core/components/data-grid/layer-data-grid.tsx#L54)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Make style is deprecated. You should be able to use theme file with sxClasses?
</blockquote></details>

sxClass can only reference the css value defined in platte by the name string, for example color: 'text.primary', but there is no way to reference the whole class as a part of the custom class object as iconImg: { ...theme.iconImg, ... }

**Comment by dennisfu** [comment]
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/965#-NQjhBXeDeFWKUokOtOL):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Please do git commit --amend to avoid tree pollution
</blockquote></details>

Done.

**Comment by dennisfu** [comment]
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 24 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/965#-NR31RarB_8Oaj09tJYS:-NR3DESO-Au4uHknPXV7:bnj7hl0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a2e46ca5d3e71ff62efd15c1dcfd5696435c9995/packages/geoview-core/src/core/components/details/feature-info.tsx#L24)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Make style is deprecated. You should be able to use theme file with sxClasses?
</blockquote></details>

same as above

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 7 files at r3, 4 of 7 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/965)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @dennisfu)

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/965)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dennisfu)

**Pull request merged**
