### PR TITLE
fix(Time): Fix time slider dynamic source and add flag for geocore not time aware

### LINKED ISSUE #1765: [FEATURE] Automatic TimeSlider from Geocore
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

As a data manager, I want to exclude layer from automatic time slider.

- [ ] Load the map with time slider enable but no layers with time dimension __see if we should hide the tab?_
- [ ] Load a layer (with time dimension) from __add layer__ to see if added to the tab
- [ ]  Load a layer (with time dimension) from __api call__ to see if added to the tab
- [ ]  Load a __Geocore__ layer (with time dimension) from __add layer__ to see if added to the tab
- [ ]  Load a layer __Geocore__ (with time dimension but time aware false) from __add layer__ to see if it is __NOT__ added to the tab

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by jolevesq**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- Fix the source problem with date filter from esri dynamic
- Add a flag isTimeAware inside the schema to exclude a layer from time function like time slider. This is a value mainly extracted from geocore

Fixes #1765 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Hosted, June 18th, 3:30: https://jolevesq.github.io/geoview/add-layers.html

Add the latest geocore layer in the list - HFE layer whiteout time slider
Add the HFE esri dynamic from add layer - HFE with time slider

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2278)

### CODE REVIEW

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2278)* status: all files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/schema.json` line 1436 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2278#-O-gzHgd9CD-UsL5-lBg:-O-gzHgd9CD-UsL5-lBh:b39df25) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7ec789d11e02ad4c612f72901f4c28bed9518101/packages/geoview-core/schema.json#L1436)):*
> ```JSON
>         "isTimeAware": {
>           "type": "boolean",
>           "description": "Flag to mention if layer will use is time dimension if provided. Use to remove a layer from time enable function like time slider."
> ```

A few typos. Revision: "Flag to mention if layer will use its time dimension if provided. Used to remove a layer from time enabled functions like time slider."
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 876 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2278#-O-h-dls7n1647zzOzL2:-O-h-dls7n1647zzOzL3:b1feg5u) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7ec789d11e02ad4c612f72901f4c28bed9518101/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L876)):*
> ```XML
> 
>     // Convert date constants using the externalFragmentsOrder derived from the externalDateFormat
>     // GV this regex is deifferent then the other layers because if not we have this error: The source image cannot be decoded.
> ```

deifferent > different
___
*[`packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts` line 126 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2278#-O-h01vm9H1qgD7k_HNn:-O-h01vm9H1qgD7k_HNo:b-1j9h98) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7ec789d11e02ad4c612f72901f4c28bed9518101/packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts#L126)):*
> ```XML
>     this.#externalFragmentsOrder = DateMgt.getDateFragmentsOrder(layerConfig.geoviewLayerConfig.externalDateFormat);
> 
>     // Boolean flag set to false if the layer, even if time enable, will be added to time function like teime slider
> ```

teime > time

**Review by Alex-NRCan — APPROVED** [review]
:lgtm:

> Reviewed 5 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2278#-:-O-hPEQG7cBavNQFFvra:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts` line 91 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2278#-O-hPfO65x7PMhZBvSEY:-O-hPfO65x7PMhZBvSEZ:bxe7hog) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7ec789d11e02ad4c612f72901f4c28bed9518101/packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts#L91)):*
> ```XML
>               metadataAccessPath: createLocalizedString(url as string),
>               geoviewLayerType: CONST_LAYER_TYPES.ESRI_DYNAMIC,
>               isTimeAware: isTimeAware as boolean,
> ```

Not really important, also I'm not sure, but here, it's casting isTimeAware to a boolean, but it can be 'undefined' too can it? Do we want to have it explicit, like `as boolean | undefined`?
I guess the plan is that if it's undefined, it'll just be undefined here in the object and later it turns to true by default?
___
*[`packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts` line 83 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2278#-O-hOjGjBy5x6L629KUz:-O-hOjGjBy5x6L629KV-:b993ik8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7ec789d11e02ad4c612f72901f4c28bed9518101/packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts#L83)):*
> ```XML
>   #externalFragmentsOrder?: TypeDateFragments;
> 
>   /** Boolean to exclude layer from any time function like time slider even if time dimension is provided */
> ```

Quick suggestion, as it was reading a bit off to me "to exclude layer from any time" and then setting it to `true`.
I was kind of perceiving it as 'true' to exclude it?
Maybe just say something like: "Boolean indicating if the layer should be included in time awareness functions such as the Time Slider. True by default."
?

**Review by jolevesq — COMMENTED** [review]
> Reviewed 11 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2278)* status: all files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/schema.json` line 1436 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2278#-O-gzHgd9CD-UsL5-lBg:-O-kP9wJ0G0MMguQcsgZ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7ec789d11e02ad4c612f72901f4c28bed9518101/packages/geoview-core/schema.json#L1436)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

A few typos. Revision: "Flag to mention if layer will use its time dimension if provided. Used to remove a layer from time enabled functions like time slider."
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts` line 91 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2278#-O-hPfO65x7PMhZBvSEY:-O-kPIGUCW0ogj-8ra8b:b-1ox8nc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7ec789d11e02ad4c612f72901f4c28bed9518101/packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts#L91)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Not really important, also I'm not sure, but here, it's casting isTimeAware to a boolean, but it can be 'undefined' too can it? Do we want to have it explicit, like `as boolean | undefined`?
I guess the plan is that if it's undefined, it'll just be undefined here in the object and later it turns to true by default?
</blockquote></details>

IsTimeAware is always set in geocore so I think it may not be undefined here. It is part of return value for geocore API
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 876 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2278#-O-h-dls7n1647zzOzL2:-O-kRAXW0tnrgTqNhsXj:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7ec789d11e02ad4c612f72901f4c28bed9518101/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L876)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

deifferent > different
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts` line 83 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2278#-O-hOjGjBy5x6L629KUz:-O-kRIbx2ellQyRrP5Rb:b7x7y5o) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7ec789d11e02ad4c612f72901f4c28bed9518101/packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts#L83)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Quick suggestion, as it was reading a bit off to me "to exclude layer from any time" and then setting it to `true`.
I was kind of perceiving it as 'true' to exclude it?
Maybe just say something like: "Boolean indicating if the layer should be included in time awareness functions such as the Time Slider. True by default."
?
</blockquote></details>

Yeah it is the way they define it in geocore API. I will update the comment, yours is better.
___
*[`packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts` line 126 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2278#-O-h01vm9H1qgD7k_HNn:-O-kRlctCkso9lvHiWIu:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7ec789d11e02ad4c612f72901f4c28bed9518101/packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts#L126)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

teime > time
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2278)* status: all files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @ychoquet)

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2278)* status: all files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2278)* status: all files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @ychoquet)

**Review by DamonU2 — APPROVED** [review]
> Reviewed 5 of 5 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2278)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
