### PR TITLE
feat(ui): Enable light/dark themes

### LINKED ISSUE #610: Update them dark vs light
For the momoent we have in our configuration a theme paramter with 'dark' or 'light'. I do not think this paramter is use at the moment. Make it work and create the light theme (looks like the old one - white with black text). At the same time repair the dark theme because some panel content are not visible properly in the some panel content. Make sure que al text and border are light.

Does all the component needs modification or it can be manage in the theme file? If the issues is too big, we may split. 

At the same time it may be related to #556

### PR DESCRIPTION
**Pull request by dayc-mapdev**
Closes #610

- - -
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/626)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
In Legend.html

There is an error in list-item.tsx: 
color: theme.palette.text.primary, is undefined

The WMS image background color is black with black text.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/626#-:-NGIwN0lDQy-QCCT_AWM:bjyge22)* status: all files reviewed, 1 unresolved discussion (waiting on @dayc-mapdev and @ychoquet)

___
*[`packages/geoview-core/public/templates/legend.html` line 131 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/626#-NGIy0CL9plGdf3GnWiN:-NGIy0CL9plGdf3GnWiO:b-tq9k66) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2c3a24ad19daa81b187342ff73629b159c714ce6/packages/geoview-core/public/templates/legend.html#L131)):*
> ```HTML
>             ]
>           },
>           'theme': 'dark',
> ```

There is error in this page, see my message at the top

**Review by dayc-mapdev — COMMENTED** [review]
I think the createTheme method fills in default values if not defined, but we should be explicit and add all those values so they are easier to customize. 

I will investigate the WMS issue, it seems some have white and some have a transparent background..

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/626#-:-NGMAa5p3lM4uG70md5D:b3errgi)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Review by ychoquet — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/626)* status: all files reviewed, 1 unresolved discussion (waiting on @dayc-mapdev)

**Review by dayc-mapdev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/626)* status: 6 of 11 files reviewed, 2 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/public/templates/legend.html` line 131 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/626#-NGIy0CL9plGdf3GnWiN:-NGRtnSE2vVdbPykU92T:b-jkg0hd) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2c3a24ad19daa81b187342ff73629b159c714ce6/packages/geoview-core/public/templates/legend.html#L131)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There is error in this page, see my message at the top
</blockquote></details>

See my comment below in list-item.tsx on how its getting the style now
___
*[`packages/geoview-core/src/ui/list/list-item.tsx` line 15 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/626#-NGRt7SFDgG9EYhW179t:-NGRt7SFDgG9EYhW179u:bpnpzvc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/483553a5eb84ddbcf5a2a684e85318e47c027a88/packages/geoview-core/src/ui/list/list-item.tsx#L15)):*
> ```XML
> 
>   return (
>     <MaterialListItem sx={{ color: 'text.primary' }} className={`${className || ''}`} style={style || undefined}>
> ```

New way to get theme info. If it can't find the theme it uses MUI defaults

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/626)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @dayc-mapdev and @ychoquet)

___
*[`packages/geoview-core/public/templates/legend.html` line 384 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/626#-NGRx9sY2AHBeaSs7TEw:-NGRx9sY2AHBeaSs7TEx:b-kon821) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/483553a5eb84ddbcf5a2a684e85318e47c027a88/packages/geoview-core/public/templates/legend.html#L384)):*
> ```HTML
> 
>       // call an api function to add a panel with a button in the default group
>       api.map(mapIdFour).appBarButtons.createAppbarPanel(button, panel, null);
> ```

When we click on unknow layer title in demo 3, it creates this error:

```
map-schema-types.ts:148 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'type')
    at r (map-schema-types.ts:148:25)
    at e.value (geoview-renderer.ts:685:9)
    at geoview-renderer.ts:361:62
    at Array.forEach (<anonymous>)
    at geoview-renderer.ts:360:55
    at new Promise (<anonymous>)
    at e.value (geoview-renderer.ts:323:32)
    at abstract-geoview-layers.ts:760:25
    at new Promise (<anonymous>)
    at n.value (abstract-geoview-layers.ts:750:28)
```

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/626)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/626)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/626)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/626)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @dayc-mapdev)

**Review by jolevesq — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/626)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dayc-mapdev)

**Pull request merged**
