### PR TITLE
separate legend and layers

### LINKED ISSUE #1436: [FEATURE] Separate existing legend into two (Legend + Layers)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Christopher Phelefu

### User Story

The existing legend contains both legend and layers data, separate into two tabs

### Implementation UI

_No response_

### LINKED ISSUE #1440: [FEATURE] Add icons to the footer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Christopher Phelefu

### User Story

Add icons to the footer.
image

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

Separate the legend and the layers components.

Fixes #1436 
Fixes #1440 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://cphelefu.github.io/geoview/

# Checklist:

- [X] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [X] I have connected the issues(s) to this PR
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 23 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439)* status: 23 of 26 files reviewed, 9 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/public/index.html` line 35 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439#-Nhkwr3d3WgDjSBmPkPs:-Nhkwr3eB41NOY00uPQ5:bti444v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c43ddc4f09cf8cf1f334804b7000990bf0bfa39b/packages/geoview-core/public/index.html#L35)):*
> ```HTML
>     <a class="page-link" href="./raw-data-table.html">Basic Data Table</a>
>     <a class="page-link" href="./raw-legend-2.html">Basic Legend(2)</a>
>     <a class="page-link" href="./raw-layers.html">Basic Layers</a>
> ```

Why do you create a new demo page that is like the one we have? I think we can have only one demo (more then one map) to showcase legend/layers
___
*[`packages/geoview-core/public/templates/raw-layers.html` line 6 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439#-Nhkx4ml0MonMuzfxcuc:-Nhkx4ml0MonMuzfxcud:bbxgkzp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c43ddc4f09cf8cf1f334804b7000990bf0bfa39b/packages/geoview-core/public/templates/raw-layers.html#L6)):*
> ```HTML
>     <meta charset="UTF-8" />
>     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>     <title><%= htmlWebpackPlugin.options.title %></title>
> ```

Same comment as above
___
*[`packages/geoview-core/src/core/components/layers/layers.tsx` line 29 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439#-NhkxEX_3W4_mko6BMIv:-NhkxEX_3W4_mko6BMIw:bb752ax) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c43ddc4f09cf8cf1f334804b7000990bf0bfa39b/packages/geoview-core/src/core/components/layers/layers.tsx#L29)):*
> ```XML
>   const sxClasses = getSxClasses(theme);
> 
>   // Populatig fake legend data
> ```

Typo
___
*[`packages/geoview-core/src/core/components/legend-2/legend-api.ts` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439#-Nhkxvr66ugqKZzPf5HM:-Nhkxvr66ugqKZzPf5HN:bpljhzf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c43ddc4f09cf8cf1f334804b7000990bf0bfa39b/packages/geoview-core/src/core/components/legend-2/legend-api.ts#L3)):*
> ```XML
> import { createElement } from 'react';
> import { LegendsLayerSet, api } from '@/app';
> import { TypeLegendProps } from '../layers/types';
> ```

Relative path?
___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439#-NhkyARgBpJlrKvmd-sv:-NhkyARhAhuIWAC84IfK:bpljhzf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c43ddc4f09cf8cf1f334804b7000990bf0bfa39b/packages/geoview-core/src/core/stores/geoview-store.ts#L17)):*
> ```XML
> import { TypeMapFeaturesConfig, TypeValidMapProjectionCodes } from '@/core/types/global-types';
> import { TypeArrayOfLayerData } from '../components/details/details';
> import { TypeLegendItemProps, TypeLegendLayer } from '../components/layers/types';
> ```

Relative path?
___
*[`packages/geoview-core/src/ui/icons/index.ts` line 73 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439#-NhkyKFv1OuYK-fehA02:-NhkyKFv1OuYK-fehA03:b-jb8d91) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c43ddc4f09cf8cf1f334804b7000990bf0bfa39b/packages/geoview-core/src/ui/icons/index.ts#L73)):*
> ```XML
>   ZoomIn as ZoomInSearchIcon,
>   ZoomOut as ZoomOutSearchIcon,
>   HubOutlined as HubOutlinedIcon,
> ```

Put in alphabetical order
___
*[`packages/geoview-footer-panel/src/index.tsx` line 103 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439#-NhkydBJ15tFPlcwK7xK:-NhkydBJ15tFPlcwK7xL:b-yo1j24) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c43ddc4f09cf8cf1f334804b7000990bf0bfa39b/packages/geoview-footer-panel/src/index.tsx#L103)):*
> ```XML
>         tabsCounter++;
>       }
>       console.log('defaultTabs ', defaultTabs);
> ```

Remove console log
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-icon-list.tsx` line 13 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439#-NhkxZI82mYre-IeSdOI:-NhkxZI82mYre-IeSdOJ:bs0h9uv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c43ddc4f09cf8cf1f334804b7000990bf0bfa39b/packages/geoview-core/src/core/components/layers/right-panel/layer-icon-list.tsx#L13)):*
> ```XML
>   TypeUniqueValueStyleConfig,
>   TypeClassBreakStyleConfig,
> } from '../../../types/cgpv-types';
> ```

Should use relative path?
___
*[`packages/geoview-core/src/core/components/legend-2/legend-layer.tsx` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439#-Nhky1IuCmuE-s73mn0e:-Nhky1IuCmuE-s73mn0f:bpljhzf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c43ddc4f09cf8cf1f334804b7000990bf0bfa39b/packages/geoview-core/src/core/components/legend-2/legend-layer.tsx#L17)):*
> ```XML
>   KeyboardArrowUpIcon,
> } from '@/ui';
> import { TypeLegendLayer } from '../layers/types';
> ```

Relative path?

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439)* status: 16 of 26 files reviewed, 8 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/index.html` line 35 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439#-Nhkwr3d3WgDjSBmPkPs:-NhlVIgw2nbEFS_jjxE1:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c43ddc4f09cf8cf1f334804b7000990bf0bfa39b/packages/geoview-core/public/index.html#L35)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why do you create a new demo page that is like the one we have? I think we can have only one demo (more then one map) to showcase legend/layers
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/legend-2/legend-api.ts` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439#-Nhkxvr66ugqKZzPf5HM:-NhlVMqJ0qTvk6DyaMWm:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c43ddc4f09cf8cf1f334804b7000990bf0bfa39b/packages/geoview-core/src/core/components/legend-2/legend-api.ts#L3)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Relative path?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439#-NhkyARgBpJlrKvmd-sv:-NhlVU4r7KP7sv4YxHnp:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c43ddc4f09cf8cf1f334804b7000990bf0bfa39b/packages/geoview-core/src/core/stores/geoview-store.ts#L17)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Relative path?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/icons/index.ts` line 73 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439#-NhkyKFv1OuYK-fehA02:-NhlVVG-0yDQpPVAjjiQ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c43ddc4f09cf8cf1f334804b7000990bf0bfa39b/packages/geoview-core/src/ui/icons/index.ts#L73)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put in alphabetical order
</blockquote></details>

Done.
___
*[`packages/geoview-footer-panel/src/index.tsx` line 103 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439#-NhkydBJ15tFPlcwK7xK:-NhlVWA8EM3Qu7MGjbvE:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c43ddc4f09cf8cf1f334804b7000990bf0bfa39b/packages/geoview-footer-panel/src/index.tsx#L103)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove console log
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-icon-list.tsx` line 13 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439#-NhkxZI82mYre-IeSdOI:-NhlVKyA2tWPl2QAFRnj:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c43ddc4f09cf8cf1f334804b7000990bf0bfa39b/packages/geoview-core/src/core/components/layers/right-panel/layer-icon-list.tsx#L13)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should use relative path?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/legend-2/legend-layer.tsx` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439#-Nhky1IuCmuE-s73mn0e:-NhlVNyS8KKa3wL2ZwO1:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c43ddc4f09cf8cf1f334804b7000990bf0bfa39b/packages/geoview-core/src/core/components/legend-2/legend-layer.tsx#L17)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Relative path?
</blockquote></details>

Done.

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439)* status: 16 of 26 files reviewed, 8 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/raw-layers.html` line 6 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439#-Nhkx4ml0MonMuzfxcuc:-NhlVYAO1G85_fihY_SV:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c43ddc4f09cf8cf1f334804b7000990bf0bfa39b/packages/geoview-core/public/templates/raw-layers.html#L6)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same comment as above
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 26 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1439)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
