### PR TITLE
feature(geopackage): Multiple layer geopackages now supported

### LINKED ISSUE #833: Add support for geopackages with multiple layers
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

_No response_

### User Story

As a geoview user, I would like to be able to load multiple layers from a single geopackage. Currently only the first layer is used.

### Implementation UI

_No response_

### LINKED ISSUE #1103: [BUG] MultiPolygon highlight uses central point instead of each plygon
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a multipolygon is highlighted, it uses a central point as the animation center instead of the center of each individual polygon.

### Expected Behavior

Refactor to operate the same way as multipoint, highlighting each polygon separately.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #833
Closes #1103 

# Description

Refactored geopackage handling to support .gpkg's with multiple layers.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested by adding through layers panel and changing geopackage.html, tested with multiple entries in listOfLayerEntryConfig, and in a group layer.

# Checklist:

- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1107)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1107)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/public/templates/layers/geopackage.html` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1107#-NY4R4dmCq1yEqkg1hOK:-NY4R4dmCq1yEqkg1hOL:b-ycnbjf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d3e80c120928e5cbbf076fb3c42c9dc437a18b6/packages/geoview-core/public/templates/layers/geopackage.html#L79)):*
> ```HTML
>           'interaction': 'dynamic',
>           'viewSettings': {
>             'zoom': 4,
> ```

Can you keep booth sample the original and this one on the same page.

Inside the footer tab legend, icon for the layer is not there. It is when we click on element in details panel
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 525 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1107#-NY4RQhv-E8GgUaDymLu:-NY4RQhv-E8GgUaDymLv:btit691) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d3e80c120928e5cbbf076fb3c42c9dc437a18b6/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L525)):*
> ```XML
>           this.processOneLayerEntry(listOfLayerEntryConfig[0] as TypeBaseLayerEntryConfig).then((baseLayer) => {
>             if (baseLayer) {
>               baseLayer.setVisible(true);
> ```

Why have you removed this?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 183 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1107#-NY4RzAPA69oU8wzmL3C:-NY4RzAPA69oU8wzmL3D:b-lgd3oq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/35f2b227c601969ce2ac3a423de0c023f98d8cd2/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L183)):*
> ```XML
>    * @returns {VectorLayer<VectorSource>} The vector layer created.
>    */
>   createVectorLayer(layerEntryConfig: TypeVectorLayerEntryConfig, vectorSource: VectorSource<Geometry>): VectorLayer<VectorSource> {
> ```

Is it the first use case where we have to switch from private to public?

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1107)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @DamonU2)

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1107)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/layers/geopackage.html` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1107#-NY4R4dmCq1yEqkg1hOK:-NY59e1ADznn-5IelLSM:b-886gsx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d3e80c120928e5cbbf076fb3c42c9dc437a18b6/packages/geoview-core/public/templates/layers/geopackage.html#L79)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you keep booth sample the original and this one on the same page.

Inside the footer tab legend, icon for the layer is not there. It is when we click on element in details panel
</blockquote></details>

Fixed
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 525 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1107#-NY4RQhv-E8GgUaDymLu:-NY4WxCj1IDMt3U2mJvx:b-ggmk04) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d3e80c120928e5cbbf076fb3c42c9dc437a18b6/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L525)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why have you removed this?
</blockquote></details>

It is overriding the config visibility without checking if it should be visible.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 183 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1107#-NY4RzAPA69oU8wzmL3C:-NY4Y0Tj0HK40lp70NwW:b1dxnwb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/35f2b227c601969ce2ac3a423de0c023f98d8cd2/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L183)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is it the first use case where we have to switch from private to public? 
</blockquote></details>

The other one is in abstract-geoview-layer.ts

**Comment by DamonU2** [comment]
Details is now working. and I added in a fix for the multipolygon highlight.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1107)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @DamonU2)

___
*[`packages/geoview-core/public/templates/layers/geopackage.html` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1107#-NY4R4dmCq1yEqkg1hOK:-NYIU8RX4-QNRB6x69a2:by67jiw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d3e80c120928e5cbbf076fb3c42c9dc437a18b6/packages/geoview-core/public/templates/layers/geopackage.html#L79)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Fixed
</blockquote></details>

Details is working now but not legend icon. Zoom to layer is not working as well.

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1107)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/layers/geopackage.html` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1107#-NY4R4dmCq1yEqkg1hOK:-NYJMukUES953cjp_DKa:bt2vr0y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d3e80c120928e5cbbf076fb3c42c9dc437a18b6/packages/geoview-core/public/templates/layers/geopackage.html#L79)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Details is working now but not legend icon. Zoom to layer is not working as well.


</blockquote></details>

Fixed!
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 525 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1107#-NY4RQhv-E8GgUaDymLu:-NYJMxFa1sUup_ZE2VgK:b-mofmv1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d3e80c120928e5cbbf076fb3c42c9dc437a18b6/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L525)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

It is overriding the config visibility without checking if it should be visible.
</blockquote></details>

I put it back in, settings were checked once all layers were visible, and I found an issue that removing it might have caused.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
