### PR TITLE
fix(wcag): Control focus on keyboard and removed Overview map from cycle

### LINKED ISSUE #105: Set focus on map tab
When use tab to the map, the map should highlight

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #105

## Checklist

* [x] Commit message follow the guidelines
* [x] PR targets the correct release version
* [x] Deploy has been done
* [x] Check styling
* [ ] _Help files and documentation have been updated_
* [ ] ~Release notes have been updated~

## What's to look for styling
* Use camelCase for identifier names (variables and functions)
* Use PascalCase for type names
* Do not use "I" as a prefix for interface names
* Do not export types/functions unless you need to share it across multiple components
* All names start with a letter
* Always put spaces around operators ( = + - * / ), and after colon:
* Remove all trailing white spaces
* Look for bad indentation
* Carriage return are mandatory
  * Before comments
  * Before if condition
  * After if condition
  * Before properties
  * Before classes
  * Before functions

The use of Prettier Visual Studio Code extension let's you format automatically your code to remove most of the styling issues like white space and indentation.

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/116)

### CODE REVIEW

**Review by yass0016 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/116)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @jolevesq and @melzeiny1980)

___
*[common/docs/app/accessibility.md, line 5 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/116#-MUPC0x5AK1pmO38jFbj:-MUPC0x61mnioa-JYSGh:bp4uyof) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/4b043103a96b858fcb75c60b563b772e08476d8f/common/docs/app/accessibility.md#L5)):*
> ```Markdown
> _Work in progress_
> 
> The viewer needs to be accessible for keyboard ans screen reader. It's should follow WCAG 2.1 requirements: https://www.w3.org/TR/WCAG21
> ```

typo ans

**Review by jolevesq — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 4 of 7 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/116#-:-MUPVT-z0HgO80Y6I16J:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @melzeiny1980 and @yass0016)

___
*[common/docs/app/accessibility.md, line 5 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/116#-MUPC0x5AK1pmO38jFbj:-MUPVBfm-hPvXu_zQUvC:bb6un1j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/4b043103a96b858fcb75c60b563b772e08476d8f/common/docs/app/accessibility.md#L5)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

typo ans
</blockquote></details>

Done

**Review by yass0016 — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @melzeiny1980)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @melzeiny1980)

**Pull request merged**
