### PR TITLE
2321-draft version aoi

### PR DESCRIPTION
**Pull request by guichoquette**
# Description

I created a Schema for the package area of interest.

Fixes # (2351)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

I made sure that the web site was still loading.

the URL for the deploy : https://guichoquette.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @guichoquette)

___
*[`packages/geoview-aoi-panel/default-config-area-of-interest.json` line 4 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352#-O1NUmfaCCgB3rgBWiBN:-O1NUmfaCCgB3rgBWiBO:b-fgiz4d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/569d3cb681a44b46372b7864b18df9328f85f515/packages/geoview-aoi-panel/default-config-area-of-interest.json#L4)):*
> ```JSON
>   "isOpen": false,
>   "aoiList": [
>     {
> ```

Your default config should be an empty array aoiList
___
*[`packages/geoview-aoi-panel/schema.json` line 25 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352#-O1NUuA-C7SrvBjBQaGN:-O1NUuA-C7SrvBjBQaGO:bqxbvrg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/569d3cb681a44b46372b7864b18df9328f85f515/packages/geoview-aoi-panel/schema.json#L25)):*
> ```JSON
>             "format": "uri"
>           },
>           "aoiDescription": {
> ```

Should be aoiTitle. We can add aoiDescription as optional
___
*[`packages/geoview-aoi-panel/schema.json` line 52 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352#-O1NV8-M-GHxpbUO5pHQ:-O1NV8-M-GHxpbUO5pHR:bozr2u) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/569d3cb681a44b46372b7864b18df9328f85f515/packages/geoview-aoi-panel/schema.json#L52)):*
> ```JSON
>               }
>             ],
>             "minItems": 4,
> ```

Min is 0 (your default) and there is no max
___
*[`packages/geoview-aoi-panel/schema.json` line 56 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352#-O1NVCk73yKdnwj5ssMl:-O1NVCk73yKdnwj5ssMm:b-m0day7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/569d3cb681a44b46372b7864b18df9328f85f515/packages/geoview-aoi-panel/schema.json#L56)):*
> ```JSON
>           }
>         },
>         "required": ["aoiDescription", "extent"]
> ```

aoiTitle and extent
___
*[`packages/geoview-aoi-panel/src/index.tsx` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352#-O1NVPnz-7Ka9SuuLlAG:-O1NVPnz-7Ka9SuuLlAH:bsnl138) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a50a34915e75f21269d4ec3cd02975679fdb213/packages/geoview-aoi-panel/src/index.tsx#L51)):*
> ```XML
>     // Button props
>     return {
>       id: `aoi-panel`,
> ```

Revert to aoi-panel



_Code quote:_
```XML
`aoi-panel`
```
___
*[`packages/geoview-aoi-panel/src/index.tsx` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352#-O1NVU-t22KAqL15dqvK:-O1NVU-t22KAqL15dqvL:bsnl138) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/569d3cb681a44b46372b7864b18df9328f85f515/packages/geoview-aoi-panel/src/index.tsx#L51)):*
> ```XML
>     // Button props
>     return {
>       id: `${this.pluginProps.mapId}-AoiPanelButton`,
> ```

Revert to aoi-panel
___
*[`packages/geoview-core/public/configs/loading-packages-config.json` line 18 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352#-O1NVZgb6XDvRfB_QrSy:-O1NVZgb6XDvRfB_QrSz:b-e9hgjn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/569d3cb681a44b46372b7864b18df9328f85f515/packages/geoview-core/public/configs/loading-packages-config.json#L18)):*
> ```JSON
>   "appBar": {
>     "tabs": {
>       "core": ["basemap-panel", "aoi-panel"]
> ```

Revert to previous values

**Review by guichoquette — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @guichoquette and @jolevesq)

___
*[`packages/geoview-aoi-panel/default-config-area-of-interest.json` line 4 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352#-O1NUmfaCCgB3rgBWiBN:-O1Ns9Do64Q99txwRFAJ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/569d3cb681a44b46372b7864b18df9328f85f515/packages/geoview-aoi-panel/default-config-area-of-interest.json#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Your default config should be an empty array aoiList
</blockquote></details>

Done.
___
*[`packages/geoview-aoi-panel/schema.json` line 25 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352#-O1NUuA-C7SrvBjBQaGN:-O1NsRfVDIBK2eEuB9f1:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/569d3cb681a44b46372b7864b18df9328f85f515/packages/geoview-aoi-panel/schema.json#L25)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should be aoiTitle. We can add aoiDescription as optional
</blockquote></details>

Done.
___
*[`packages/geoview-aoi-panel/schema.json` line 52 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352#-O1NV8-M-GHxpbUO5pHQ:-O1NsfXK36lX7GhNZ4ws:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/569d3cb681a44b46372b7864b18df9328f85f515/packages/geoview-aoi-panel/schema.json#L52)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Min is 0 (your default) and there is no max
</blockquote></details>

Done.
___
*[`packages/geoview-aoi-panel/schema.json` line 56 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352#-O1NVCk73yKdnwj5ssMl:-O1NssPn3o9hONRtlrJj:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/569d3cb681a44b46372b7864b18df9328f85f515/packages/geoview-aoi-panel/schema.json#L56)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

aoiTitle and extent
</blockquote></details>

Done.
___
*[`packages/geoview-aoi-panel/src/index.tsx` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352#-O1NVPnz-7Ka9SuuLlAG:-O1NyH5YB-tW9aNJxy_G:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a50a34915e75f21269d4ec3cd02975679fdb213/packages/geoview-aoi-panel/src/index.tsx#L51)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Revert to aoi-panel
</blockquote></details>

Done.
___
*[`packages/geoview-aoi-panel/src/index.tsx` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352#-O1NVU-t22KAqL15dqvK:-O1NyU1uCitMP8WN6to_:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/569d3cb681a44b46372b7864b18df9328f85f515/packages/geoview-aoi-panel/src/index.tsx#L51)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Revert to aoi-panel
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/configs/loading-packages-config.json` line 18 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352#-O1NVZgb6XDvRfB_QrSy:-O1NuF8jEhP9VMnUKu7j:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/569d3cb681a44b46372b7864b18df9328f85f515/packages/geoview-core/public/configs/loading-packages-config.json#L18)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Revert to previous values
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @guichoquette)

___
*[`packages/geoview-aoi-panel/default-config-area-of-interest.json` line 1 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352#-O1O4XAm4BGKsXujF_Un:-O1O4XAm4BGKsXujF_Uo:bdzq4xa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/157af333c6a429143e160bf70c43c9b98baf8847/packages/geoview-aoi-panel/default-config-area-of-interest.json#L1)):*
> ```JSON
> {
> ```

The file name should have the same name as the package: aoi-panel is the package name I think

**Review by guichoquette — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @guichoquette and @jolevesq)

___
*[`packages/geoview-aoi-panel/default-config-area-of-interest.json` line 1 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352#-O1O4XAm4BGKsXujF_Un:-O1O7IVGDG7i-DsZTq3P:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/157af333c6a429143e160bf70c43c9b98baf8847/packages/geoview-aoi-panel/default-config-area-of-interest.json#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The file name should have the same name as the package: aoi-panel is the package name I think
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guichoquette)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2352)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guichoquette)

**Pull request merged**
