### PR TITLE
1114 implement lightbox for images

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Implement LightBox for images in data table for polygon layer.

Fixes # (1114)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/raw-data-table.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1459)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1459)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/data-table/map-data-table.tsx` line 373 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1459#-NiJzCqj8CYlysWEB4Y2:-NiJzCqj8CYlysWEB4Y3:b-nphlgd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4e82ba1587fb665eb56923b3aedd9030f6b40bc5/packages/geoview-core/src/core/components/data-table/map-data-table.tsx#L373)):*
> ```XML
>     if (typeof cellValue === 'string' && isImage(cellValue)) {
>       return (
>         <Button
> ```

Can we add the url to a tooltip elements?
___
*[`packages/geoview-core/src/core/components/data-table/map-data-table.tsx` line 379 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1459#-NiJyst0A551TQ649fCU:-NiJyst0A551TQ649fCV:b-eqbndr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4e82ba1587fb665eb56923b3aedd9030f6b40bc5/packages/geoview-core/src/core/components/data-table/map-data-table.tsx#L379)):*
> ```XML
>           sx={{ height: '2.5rem', paddingLeft: '0.5rem', paddingRight: '0.5rem', textTransform: 'none' }}
>         >
>           Images
> ```

Do not hardcode the button text, put in translation json file as Image(s)

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1459)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/data-table/map-data-table.tsx` line 373 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1459#-NiJzCqj8CYlysWEB4Y2:-NiKOj737qIZstS4PEZF:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4e82ba1587fb665eb56923b3aedd9030f6b40bc5/packages/geoview-core/src/core/components/data-table/map-data-table.tsx#L373)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we add the url to a tooltip elements?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/data-table/map-data-table.tsx` line 379 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1459#-NiJyst0A551TQ649fCU:-NiKOib--5I70p2R1MO8:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4e82ba1587fb665eb56923b3aedd9030f6b40bc5/packages/geoview-core/src/core/components/data-table/map-data-table.tsx#L379)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do not hardcode the button text, put in translation json file as Image(s)
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1459)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1459#-:-NiKU15d9yJUDQHWUot3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Pull request merged**
