### PR TITLE
feat(plugins): Hides plugin tabs if no layers support them

### LINKED ISSUE #2369: [UX] Packages Tab Visible when Empty
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we have a map with packages enable like "Chart" and "Time-Slider" the tabs are visible on the footer and/or app bar. This may be confusiong for the user as some maps may never have dataset to enable the Chart or Time-Slider.

image

### Expected Behavior

When there is no layer registered in an available package, the tab should not be visible. As soon as a layer on the map has the capacity to use the package the tab is visible even if the layer itself is not.

### Steps To Reproduce

1. https://canadian-geospatial-platform.github.io/geoview/public/add-layers.html
2. See the chat/time-slider tabs even with no layers on the map

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #2369

# Description

Removes (hides) tabs for time slider and geochart from footer-bar if there are no layers that support them. Also adds name and email to type action to stabilize it, and span tags to buttons to avoid errors when they are disabled.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/10-package-time-slider.json
https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/12-package-geochart.json
https://damonu2.github.io/geoview/add-layers.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2384)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2384)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @DamonU2, and @kaminderpal)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2384#-O25-Bv909NGzOW5eIXa:-O25-Bv909NGzOW5eIXb:b-acrj5m) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5b26cb92a45e3c1f43cf37c533944721e52dcea9/packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts#L50)):*
> ```XML
>   static addHiddenTab(mapId: string, tab: string): void {
>     if (!this.getUIState(mapId).hiddenTabs.includes(tab))
>       this.getUIState(mapId).setterActions.setHiddenTabs([...this.getUIState(mapId).hiddenTabs, tab]);
> ```

Maybe rename getUIState to getUIStateProtected like in other processor

**Review by kaminderpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2384)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/ui/icon-button/icon-button.tsx` line 35 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2384#-O255X1UCNdQ4ga1KZ4k:-O255X1UCNdQ4ga1KZ4l:b-6wfznx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5b26cb92a45e3c1f43cf37c533944721e52dcea9/packages/geoview-core/src/ui/icon-button/icon-button.tsx#L35)):*
> ```XML
>   function getMaterialIconButton(): JSX.Element {
>     return (
>       <span>
> ```

We dnt use `span`/html element directly, we leverage Material UI `Box` component.

Also please make sure, it doesn't break any functionality, i dnt remember fully, their was reason to remove span tag.



_Code snippet:_
```XML
<Box component="span">
</Box>
```
___
*[`packages/geoview-core/src/ui/icon-button/icon-button.tsx` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2384#-O256-W20xW4p7gQGGEc:-O256-W20xW4p7gQGGEd:b-84146f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5b26cb92a45e3c1f43cf37c533944721e52dcea9/packages/geoview-core/src/ui/icon-button/icon-button.tsx#L51)):*
> ```XML
>           {children && children}
>         </MaterialIconButton>
>       </span>
> ```

Same span issue above.

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 10 of 12 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2384)* status: all files reviewed, 4 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/ui/button/button.tsx` line 45 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2384#-O25FN8j6lWBm3YSULdT:-O25FN8j6lWBm3YSULdU:b-mqypvm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e3124303c5bbe3fbf39e58ea6aa100786e4ac1e9/packages/geoview-core/src/ui/button/button.tsx#L45)):*
> ```XML
>   return (
>     <Tooltip title={t(tooltip || '')} placement={tooltipPlacement || 'bottom'} TransitionComponent={Fade}>
>       <span>
> ```

Same comment from Kamy below for this line here

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2384)* status: all files reviewed, 5 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts` line 91 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2384#-O25GKkI79aD68wc8tN_:-O25GKkI79aD68wc8tNa:b-h8pe9m) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e3124303c5bbe3fbf39e58ea6aa100786e4ac1e9/packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts#L91)):*
> ```XML
> 
>     // Make sure tab is visible
>     UIEventProcessor.removeHiddenTab(mapId, 'time-slider');
> ```

Minor
I understand why it was coded the way it is and all. Makes sense.
That said, from an outsider perspective, reading 'remove hidden' is a bit weird as it's a bit like a double negation.
Suggestion to see if it couldn't be more like a tab visibility flag? visible/invisible.
showTab()
hideTab()
kind of functions?

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2384)* status: 7 of 15 files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @jolevesq, and @kaminderpal)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts` line 91 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2384#-O25GKkI79aD68wc8tN_:-O25JJrg8xrzygZCJJno:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e3124303c5bbe3fbf39e58ea6aa100786e4ac1e9/packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts#L91)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Minor
I understand why it was coded the way it is and all. Makes sense.
That said, from an outsider perspective, reading 'remove hidden' is a bit weird as it's a bit like a double negation.
Suggestion to see if it couldn't be more like a tab visibility flag? visible/invisible.
showTab()
hideTab()
kind of functions?
</blockquote></details>

Done
___
*[`packages/geoview-core/src/ui/button/button.tsx` line 45 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2384#-O25FN8j6lWBm3YSULdT:-O25JS5e5EhqQm9BBEGl:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e3124303c5bbe3fbf39e58ea6aa100786e4ac1e9/packages/geoview-core/src/ui/button/button.tsx#L45)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Same comment from Kamy below for this line here
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/icon-button/icon-button.tsx` line 35 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2384#-O255X1UCNdQ4ga1KZ4k:-O25JSjA1lzdOUrzdU5K:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5b26cb92a45e3c1f43cf37c533944721e52dcea9/packages/geoview-core/src/ui/icon-button/icon-button.tsx#L35)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

We dnt use `span`/html element directly, we leverage Material UI `Box` component.

Also please make sure, it doesn't break any functionality, i dnt remember fully, their was reason to remove span tag.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/icon-button/icon-button.tsx` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2384#-O256-W20xW4p7gQGGEc:-O25JT7YCxVQVJsMFHn3:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5b26cb92a45e3c1f43cf37c533944721e52dcea9/packages/geoview-core/src/ui/icon-button/icon-button.tsx#L51)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

Same span issue above.
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, 8 of 8 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2384)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

**Pull request merged**
