### PR TITLE
feat(footer-bar): Add fix  north in LCC map

### LINKED ISSUE #481: Support rotation to true north
Add map rotation to true north and reset map angle.

Add the control within footer bar when refactor done.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #481

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/490)

### CODE REVIEW

**Review by yass0016 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/490)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/footerbar/footer-bar.tsx` line 66 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/490#-N6hbeaID3yq4IdzfNTV:-N6hbeaID3yq4IdzfNTW:b-vu73dp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/58df32a77dcca67112de7ab8b0f23c72d04d5dfa/packages/geoview-core/src/core/components/footerbar/footer-bar.tsx#L66)):*
> ```XML
> 
>   useEffect(() => {
>     // TODO: Is this still needed?
> ```

No longer needed, its handled under the Attribution component

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/490)* status: all files reviewed, 1 unresolved discussion (waiting on @yass0016)

___
*[`packages/geoview-core/src/core/components/footerbar/footer-bar.tsx` line 66 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/490#-N6hbeaID3yq4IdzfNTV:-N6mIGMP8JJwLcoBR11K:bb6un1j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/58df32a77dcca67112de7ab8b0f23c72d04d5dfa/packages/geoview-core/src/core/components/footerbar/footer-bar.tsx#L66)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

No longer needed, its handled under the Attribution component
</blockquote></details>

Done

**Review by yass0016 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/490)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by yass0016 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/490)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
