### PR TITLE
feat(ui): Add buttons to export as PNG or PDF

### LINKED ISSUE #794: Create export function

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #794

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/801)

### CODE REVIEW

**Comment by DamonU2** [comment]
Exports are working for everything but XYZ, if the same cross-origin value is added for them, it breaks the map with the current example.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/801)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/package.json` line 151 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/801#-NLaE8i6ClRR--lirblt:-NLaE8i6ClRR--lirblu:b-s108ls) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63f2361cd813fc6ab3af6f9f8b3af36694740cf4/packages/geoview-core/package.json#L151)):*
> ```JSON
>     "webpack": "^5.68.0",
>     "webpack-bundle-analyzer": "^4.5.0",
>     "webpack-bundle-size-analyzer": "^3.1.0",
> ```

Have you just reorganize alphabetically?
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 16 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/801#-NLaELRrCRXp4Bx8oBGV:-NLaELRrCRXp4Bx8oBGW:b-oyb8qd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63f2361cd813fc6ab3af6f9f8b3af36694740cf4/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L16)):*
> ```XML
> import { FooterbarRotationButton } from './footer-bar-rotation-button';
> import { FooterbarFixNorthSwitch } from './footer-bar-fixnorth-switch';
> import { FooterBarExportPngButton } from './footer-bar-exportpng-button';
> ```

Keep it here in this PR but with issue https://github.com/canadian-geospatial-platform/geoview/issues/796 we will move it to nav bar and bar set by the config.
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-exportpdf-button.tsx` line 41 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/801#-NLaEtc5D_Qr7A-G30U8:-NLaEtc5D_Qr7A-G30U9:b799lyh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63f2361cd813fc6ab3af6f9f8b3af36694740cf4/packages/geoview-core/src/core/components/footer-bar/footer-bar-exportpdf-button.tsx#L41)):*
> ```XML
>     const size = map.getSize();
>     // dpi of exported map
>     const dpi = 200;
> ```

Code related to the export function should be in utilities and only ui is in the component. We can merge as is but will be modified with issues #796. Same for PNG button. Try to make everything duplicate from both function in a utility function (core/utils or geo/utils). The issues about template willl handle the export type. for #796, we should just have a button to open the template view. From there we set the format.

**Comment by DamonU2** [comment]
> _[`packages/geoview-core/package.json` line 151 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/801#-NLaE8i6ClRR--lirblt:-NLaE8i6ClRR--lirblu:b-s108ls) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/63f2361cd813fc6ab3af6f9f8b3af36694740cf4/packages/geoview-core/package.json#L151)):_
> 
> > ```json
> >     "webpack": "^5.68.0",
> >     "webpack-bundle-analyzer": "^4.5.0",
> >     "webpack-bundle-size-analyzer": "^3.1.0",
> > ```
> 
> Have you just reorganize alphabetically?

Not sure what happened here, that all was rewritten when I fixed my build issue. The only manual addition was `jspdf`.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/801)* status: all files reviewed, 2 unresolved discussions (waiting on @DamonU2 and @ychoquet)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/801)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
