### PR TITLE
feat(geojson): Added ability to inject features overriding geojson

### LINKED ISSUE #2411: [FEATURE] Pass layer data into cpgv.init as parameter
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Greg Boyce, Data Management Plan tool, NRCan

### User Story

I'd like to be able to pass GeoJSON data (e.g. as a text string) into the cgpv.init function.

### Implementation UI

Rather than being forced to read GeoJSON data from a fixed file on the web server, I'd like to dynamically build up the data using an SQL query in PHP, and pass that GeoJSON string into the cgpv.init function.  (Instead of parsing the file, parse the passed string.)

Otherwise, I'll likely need to create files on the web server, which gets messy (disk space checks, regular file cleanup, etc).

Note:  we already have a web page which creates HTML/JavaScript output from SQL queries, so setting up a new WFS server to also query this data, would presumably double the database query load.

Data passed into cgpv.init, should probably be **_in addition to_** layers already defined in the map Config section.  (E.g. you have several layers well defined by WFS or other layer types in the map config section, and just want to add data for one dynamically constructed layer.)

So, using the following Config string (from [GeoJSON layer page](https://canadian-geospatial-platform.github.io/geoview/public/geojson.html)):
```
        "metadataAccessPath": {
          "en": "./datasets/geojson/metadata.json"
        },
        "geoviewLayerType": "GeoJSON",
        "listOfLayerEntryConfig": [
          {
            "layerId": "polygons.json",
            "layerName": {
              "en": "Polygons"
            },
            "layerFilter": "creationDate >= date '2020/02/15'"
          },
```

Basically allowing the contents of "polygons.json" to be passed into cgpv.init as a parameter.

The metadataAccessPath (metadata.json) could remain in the config (or be passed in, too).

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #2411

# Description

Added a function to inject new geojson into a layer, overriding existing features.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://damonu2.github.io/geoview/demo-geojson-inject.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2454)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2454)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @DamonU2)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 335 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2454#-O5t7a-hE1t4-0nhlTRw:-O5t7a-i7bDAEgBMyfVB:baccc0b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a8304fbc6118338ca998d6a52aa7f979135982ee/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L335)):*
> ```XML
>           bounds,
>           controls,
>           layerId: layerPathNodes[currentLevel - 1],
> ```

This is because of a bugs?

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2454)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @DamonU2)

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2454)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 335 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2454#-O5t7a-hE1t4-0nhlTRw:-O5tSauk0w1JxfDx-BrO:b-hj3ymm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a8304fbc6118338ca998d6a52aa7f979135982ee/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L335)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This is because of a bugs?
</blockquote></details>

Well, I noticed it because of the bugs. I saw that most layers in the legend-layers in store had an undefined layerId because this was one level higher than it shoud be.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2454)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Comment by G-Boyce** [comment]
Thanks.  I'll start testing this Monday.

**Comment by G-Boyce** [comment]
Seems to be working so far!

**Pull request merged**
