### PR TITLE
597-Bug with sub layers defined in metadata

### PR DESCRIPTION
**Pull request by ychoquet**
This correction will solve certain problems Chris has.

- - -
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/598)

### CODE REVIEW

**Comment by jvanulde** [comment]
@indiciumx @ychoquet can we reference the issue(s) that this will resolve please?

**Review by ychoquet — COMMENTED** [review]
597- Bug with sub layers defined in the metadata

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/598#-:-NFKKv5X7Q9Fl6zZ2UM4:baspkhl)* status: 0 of 6 files reviewed, all discussions resolved

**Review by ychoquet — COMMENTED** [review]
In fact it affect everything that use an esri dynamic and feature layer and a WMS layer. The correction was made to help Chris in implementing issue "Create Legend reusable component #534".

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/598#-:-NFKLhqA--hxPy0Syc0y:b-exawet)* status: 0 of 6 files reviewed, all discussions resolved

**Review by jolevesq — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/598)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
