### PR TITLE
587+624-Aliases bug and type guard in legend

### PR DESCRIPTION
**Pull request by ychoquet**
Related issues: 587, 624
587: corrected the aliases bug. The getFeatureInfo did not take into account aliases when they were provided.
624: Two tests in the code could use an existing type guard function.

- - -
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/625)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/625)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @ychoquet)

___
*[`packages/geoview-core/public/templates/layers.html` line 251 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/625#-NGIt5gk7DiRBys-o87a:-NGIt5gk7DiRBys-o87b:b-pkkitp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2c3a24ad19daa81b187342ff73629b159c714ce6/packages/geoview-core/public/templates/layers.html#L251)):*
> ```HTML
>                 'geoviewLayerType': 'esriFeature',
>                 'listOfLayerEntryConfig': [
>                   { 'layerId': '8' }
> ```

Why have you changed the layer id. This one only has one legend element. Plus datagrid is broken.

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/625)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/layers.html` line 251 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/625#-NGIt5gk7DiRBys-o87a:-NGKGYEDBF295vLlDMuN:b9bub1d) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2c3a24ad19daa81b187342ff73629b159c714ce6/packages/geoview-core/public/templates/layers.html#L251)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why have you changed the layer id. This one only has one legend element. Plus datagrid is broken.
</blockquote></details>

I made these changes by accident. These changes were intended for the legend.html file. I must have changed the code here thinking I was in the right file, which was not the case.

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/625)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/layers.html` line 251 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/625#-NGIt5gk7DiRBys-o87a:-NGKHzKW3j--PF3DmgUc:b2rmmyl) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2c3a24ad19daa81b187342ff73629b159c714ce6/packages/geoview-core/public/templates/layers.html#L251)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I made these changes by accident. These changes were intended for the legend.html file. I must have changed the code here thinking I was in the right file, which was not the case. 
</blockquote></details>

I've restored the original code.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/625)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
