### PR TITLE
add layer checkboxes + animation

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

This PR adds checkboxes to the 'Add Layer' page.
It also adds basic animations to the applications; to the layers, panels and popper.

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://cphelefu.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1878)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1878)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 1047 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1878#-Nrvi39q5JQXJuaV_1hR:-Nrvi39q5JQXJuaV_1hS:b-z6qk5b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0052bdc191cead242fd68be8d5f14b28f7678cdc/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L1047)):*
> ```XML
>   const checkedIcon = <CheckBoxIcon fontSize="small" />;
> 
>   console.log('layersList ', layerList);
> ```

No console log
___
*[`packages/geoview-core/src/core/utils/useSpringAnimations.ts` line 45 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1878#-Nrvicxy7BPb884XKx_c:-Nrvicxy7BPb884XKx_d:b-ytjbk0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0052bdc191cead242fd68be8d5f14b28f7678cdc/packages/geoview-core/src/core/utils/useSpringAnimations.ts#L45)):*
> ```XML
> 
> // Color Change animation
> export const useColorChange = (config?: SpringConfig): SpringValues => {
> ```

Can we use this for transition to white - green - white for loading or querying layer?
___
*[`packages/geoview-core/src/ui/popper/popper.tsx` line 35 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1878#-NrvjHFG6Mf2-EpVWZpZ:-NrvjHFG6Mf2-EpVWZp_:b-hzgkxd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0052bdc191cead242fd68be8d5f14b28f7678cdc/packages/geoview-core/src/ui/popper/popper.tsx#L35)):*
> ```XML
>   }, [open, onClose]);
> 
>   const springProps = useSpring({
> ```

Why not using the fadeIn you have in spring utils file?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/ui/popper/popper.tsx` line 35 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1878#-NrvjHFG6Mf2-EpVWZpZ:-NrvkZTUBg5KLraPUdO2:b-gvfvlj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0052bdc191cead242fd68be8d5f14b28f7678cdc/packages/geoview-core/src/ui/popper/popper.tsx#L35)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why not using the fadeIn you have in spring utils file?
</blockquote></details>

This one is different in the sense that it depends on the open variable.

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1878)* status: 12 of 15 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 1047 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1878#-Nrvi39q5JQXJuaV_1hR:-NrvkWE47fK11WMULbUv:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0052bdc191cead242fd68be8d5f14b28f7678cdc/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L1047)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

No console log
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1878)* status: 10 of 15 files reviewed, 2 unresolved discussions (waiting on @cphelefu)

**Review by jolevesq — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1878)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1878)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
