### PR TITLE
2366 aoi UI implementation phase1

### PR DESCRIPTION
**Pull request by guichoquette**
# Description

I added UI functionalities to AOI. Strangely the URL image does not get displayed.

Fixes # (2366)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

I added 2 AOI to make sure both were appearing in the AOI panel.

__[URL for your deploy!](https://guichoquette.github.io/geoview/)__

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2367)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 4 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2367)* status: all files reviewed, 4 unresolved discussions (waiting on @guichoquette)

___
*[`packages/geoview-aoi-panel/src/aoi-panel.tsx` line 1 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2367#-O1vQ472BQWXkUjM7Gl-:-O1vQ472BQWXkUjM7Gl0:bx9hgrf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fad75ac37e1c02ab2184225aa3a6adce55698cab/packages/geoview-aoi-panel/src/aoi-panel.tsx#L1)):*
> ```XML
> // import { TypeBasemapProps } from 'geoview-core/src/geo/layer/basemap/basemap-types';
> ```

Remove all dead code.
___
*[`packages/geoview-aoi-panel/src/aoi-panel.tsx` line 29 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2367#-O1vQZZI2ofCr10PP8oa:-O1vQZZI2ofCr10PP8ob:b-qkrt7l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fad75ac37e1c02ab2184225aa3a6adce55698cab/packages/geoview-aoi-panel/src/aoi-panel.tsx#L29)):*
> ```XML
> 
> export function AoiPanel(props: AoiPanelProps): JSX.Element {
>   // eslint-disable-next-line @typescript-eslint/no-unused-vars
> ```

Why do you have this eslint escape. If a variableis not use, remove from props
___
*[`packages/geoview-aoi-panel/src/aoi-panel.tsx` line 49 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2367#-O1vQUZFBHCHrtCiISgw:-O1vQUZFBHCHrtCiISgx:b-dfm6ez) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fad75ac37e1c02ab2184225aa3a6adce55698cab/packages/geoview-aoi-panel/src/aoi-panel.tsx#L49)):*
> ```XML
>             tabIndex={0}
>             className="aoiCardThumbnail"
>             onClick={() => myMap.zoomToLngLatExtentOrCoordinate(aoiItem.extent, { maxZoom: 13 })}
> ```

CAn we try 14
___
*[`packages/geoview-aoi-panel/src/area-of-interest-style.ts` line 53 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2367#-O1vQm807tlpA8Ei7-D3:-O1vQm817nzux9OebYis:b-pj36ll) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fad75ac37e1c02ab2184225aa3a6adce55698cab/packages/geoview-aoi-panel/src/area-of-interest-style.ts#L53)):*
> ```XML
>         width: '100%',
>         overflow: 'hidden',
>         border: '1px solid #ccc',
> ```

We use theme.palette.geoViewColor.xxx  for color

**Review by guichoquette — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2367)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-aoi-panel/src/aoi-panel.tsx` line 1 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2367#-O1vQ472BQWXkUjM7Gl-:-O1vtupuE2wOQGA5KoeV:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fad75ac37e1c02ab2184225aa3a6adce55698cab/packages/geoview-aoi-panel/src/aoi-panel.tsx#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove all dead code.
</blockquote></details>

Done.
___
*[`packages/geoview-aoi-panel/src/aoi-panel.tsx` line 29 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2367#-O1vQZZI2ofCr10PP8oa:-O1w4V5oAP51mfCa5ec1:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fad75ac37e1c02ab2184225aa3a6adce55698cab/packages/geoview-aoi-panel/src/aoi-panel.tsx#L29)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why do you have this eslint escape. If a variableis not use, remove from props
</blockquote></details>

Done.
___
*[`packages/geoview-aoi-panel/src/aoi-panel.tsx` line 49 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2367#-O1vQUZFBHCHrtCiISgw:-O1w482PEMroGmGKB6k1:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fad75ac37e1c02ab2184225aa3a6adce55698cab/packages/geoview-aoi-panel/src/aoi-panel.tsx#L49)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

CAn we try 14
</blockquote></details>

Done.
___
*[`packages/geoview-aoi-panel/src/area-of-interest-style.ts` line 53 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2367#-O1vQm807tlpA8Ei7-D3:-O1wIb7t93S7HtiJCQ5v:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fad75ac37e1c02ab2184225aa3a6adce55698cab/packages/geoview-aoi-panel/src/area-of-interest-style.ts#L53)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We use theme.palette.geoViewColor.xxx  for color
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2367)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @guichoquette)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2367)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @guichoquette)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2367)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guichoquette)

**Pull request merged**
