### PR TITLE
2040-config sandbox & 2051-return an unilingual config

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

Create a sandbox that allows the user to specify a configuration string, validate it and view the resulting configuration.
In the event of an error, inform the user that the error log is in the console. Also create an empty map in anticipation of the possibility of displaying the configuration on this map.

Creation of a unilingual JSON configuration. Added asynchronous behavior to configuration to prepare for metadata processing. Corrected the timing of default values.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using Chrome Devtools.

__Deploy URL__: https://ychoquet.github.io/GeoView/config-sandbox.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 9 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054)* status: 9 of 18 files reviewed, 6 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 444 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwLVM5F4HZJA7zHBmAj:-NwLVM5F4HZJA7zHBmAk:bgazg7p) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/312d92652f98e08bfbea2e8990f001fece462062/packages/geoview-core/src/api/config/config-api.ts#L444)):*
> ```XML
>   static getMapConfig(jsonStringMapConfig: string, language: TypeDisplayLanguage): Promise<MapFeaturesConfig | undefined> {
>     // Return the config
>     const test = Promise.resolve(MapFeaturesConfig.getInstance(jsonStringMapConfig, language));
> ```

You return a resolve promises, is it still a promises return type? Can we have another name then test
___
*[`packages/geoview-core/src/api/config/utils.ts` line 13 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwLVroA8w58orD-XTBg:-NwLVroA8w58orD-XTBh:b-p1kun7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/312d92652f98e08bfbea2e8990f001fece462062/packages/geoview-core/src/api/config/utils.ts#L13)):*
> ```XML
> import { layerEntryIsGroupLayer } from '@config/types/type-guards';
> import { logger } from '@/core/utils/logger';
> import { GroupLayerEntryConfig } from './types/classes/sub-layer-config/group-layer-entry-config';
> ```

Use @ and for the line after
___
*[`packages/geoview-core/src/api/config/utils.ts` line 99 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwLVz5T9p9ChMzNQ8Hl:-NwLVz5T9p9ChMzNQ8Hm:b1t6lrk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/312d92652f98e08bfbea2e8990f001fece462062/packages/geoview-core/src/api/config/utils.ts#L99)):*
> ```XML
>  * @returns {TypeLocalizedString} A normalized localized string.
>  */
> export function normalizeLocalizedString(localizedString: TypeLocalizedString | TypeJsonObject): TypeLocalizedString | undefined {
> ```

I think we have function in the core for this in utilities. We should put a comment to remove from core if only use here after the refactor
___
*[`packages/geoview-core/src/api/config/utils.ts` line 121 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwLW9av70LcQVzmiT4l:-NwLW9av70LcQVzmiT4m:b-n4vz80) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/312d92652f98e08bfbea2e8990f001fece462062/packages/geoview-core/src/api/config/utils.ts#L121)):*
> ```XML
>  * @returns {ConfigBaseClass[]} The array of sub layer instances.
>  */
> export async function getListOfLayerEntryConfig(
> ```

This should not be async as the first loop just structure json the proper way, The layerAPI will send this one by one later when viewer send it
___
*[`packages/geoview-core/src/api/config/types/classes/map-features-config.ts` line 118 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwLWm5O8JwIqsOhLZ0E:-NwLWm5O8JwIqsOhLZ0F:b1czgaj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/312d92652f98e08bfbea2e8990f001fece462062/packages/geoview-core/src/api/config/types/classes/map-features-config.ts#L118)):*
> ```XML
>    * @returns {MapFeaturesConfig} The map features configuration instance.
>    */
>   static async getInstance(providedMapFeaturesConfig: string | TypeJsonObject, language: TypeDisplayLanguage): Promise<MapFeaturesConfig> {
> ```

Is this need to async?
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 82 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwLXAJG60zDyM20EVsj:-NwLXAJG60zDyM20EVsk:b-v5ropq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/312d92652f98e08bfbea2e8990f001fece462062/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L82)):*
> ```XML
>    * @param {MapFeaturesConfig} mapFeaturesConfig An optional mapFeatureConfig instance if the layer is part of it.
>    * /
>   static abstract async getInstance(
> ```

Again, not sure we should go async in this level of config. We should have layer async because of fetch but here it is mainly formatting and validating

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054)* status: 9 of 18 files reviewed, 6 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 444 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwLVM5F4HZJA7zHBmAj:-NwLieXN0ykmyQ23iM7l:b9r54n9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/312d92652f98e08bfbea2e8990f001fece462062/packages/geoview-core/src/api/config/config-api.ts#L444)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You return a resolve promises, is it still a promises return type? Can we have another name then test
</blockquote></details>

Done. Was there for debugging purpose.
___
*[`packages/geoview-core/src/api/config/utils.ts` line 13 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwLVroA8w58orD-XTBg:-NwLoFoP3wimlXrpaPaq:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/312d92652f98e08bfbea2e8990f001fece462062/packages/geoview-core/src/api/config/utils.ts#L13)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use @ and for the line after
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/utils.ts` line 99 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwLVz5T9p9ChMzNQ8Hl:-NwLpI7cBIOjEQZA6GIf:bjkazql) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/312d92652f98e08bfbea2e8990f001fece462062/packages/geoview-core/src/api/config/utils.ts#L99)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think we have function in the core for this in utilities. We should put a comment to remove from core if only use here after the refactor
</blockquote></details>

This function doesn't exist in the utilities file. It is a new one that replace the private function  processLocalizedString that was in the old config cvalidation.
___
*[`packages/geoview-core/src/api/config/utils.ts` line 121 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwLW9av70LcQVzmiT4l:-NwLrjHJ-nJKqaELIdUO:bognwps) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/312d92652f98e08bfbea2e8990f001fece462062/packages/geoview-core/src/api/config/utils.ts#L121)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This should not be async as the first loop just structure json the proper way, The layerAPI will send this one by one later when viewer send it
</blockquote></details>

This utility fonction needs to be async because it is used to instanciate the layer tree that will read metadata for each leaf in the tree.
___
*[`packages/geoview-core/src/api/config/types/classes/map-features-config.ts` line 118 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwLWm5O8JwIqsOhLZ0E:-NwLtIim-JPmoFD02iqS:bftjbzu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/312d92652f98e08bfbea2e8990f001fece462062/packages/geoview-core/src/api/config/types/classes/map-features-config.ts#L118)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this need to async?
</blockquote></details>

It is possible to remove the async on this fonction. however, when it comes time to process service metadata nad layer metadata we must stay async.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 82 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwLXAJG60zDyM20EVsj:-NwLy4Z54I0lBkZudugt:bhqmbci) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/312d92652f98e08bfbea2e8990f001fece462062/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L82)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Again, not sure we should go async in this level of config. We should have layer async because of fetch but here it is mainly formatting and validating
</blockquote></details>

We need it to be async because it is here we fetch the service metadata.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054)* status: 10 of 18 files reviewed, 3 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 444 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwLVM5F4HZJA7zHBmAj:-NwPA29V80SNJrKP69QE:bma9wvb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/312d92652f98e08bfbea2e8990f001fece462062/packages/geoview-core/src/api/config/config-api.ts#L444)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Done. Was there for debugging purpose.
</blockquote></details>

Should still not be a promise I think
___
*[`packages/geoview-core/src/api/config/utils.ts` line 121 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwLW9av70LcQVzmiT4l:-NwPACoK5jNdsx89v2Qn:b-3piy95) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/312d92652f98e08bfbea2e8990f001fece462062/packages/geoview-core/src/api/config/utils.ts#L121)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

This utility fonction needs to be async because it is used to instanciate the layer tree that will read metadata for each leaf in the tree.
</blockquote></details>

This function will be run by layer api, config will receive the layer one by one as layer api process them
___
*[`packages/geoview-core/src/api/config/types/classes/map-features-config.ts` line 118 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwLWm5O8JwIqsOhLZ0E:-NwPAOTeBPfZHRB4_zE8:b-702hhe) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/312d92652f98e08bfbea2e8990f001fece462062/packages/geoview-core/src/api/config/types/classes/map-features-config.ts#L118)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

It is possible to remove the async on this fonction. however, when it comes time to process service metadata nad layer metadata we must stay async.
</blockquote></details>

Like we discuss yesterday. I would like to have distinc function to get map config (JSON valid with default). This should not be async.... Once wiewer receive this, he will process the formatted list of layer and send them one by one to config. This function can be async

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054)* status: 4 of 21 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 444 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwLVM5F4HZJA7zHBmAj:-NwjEglmDwqNuCFAowqD:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/312d92652f98e08bfbea2e8990f001fece462062/packages/geoview-core/src/api/config/config-api.ts#L444)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should still not be a promise I think
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/utils.ts` line 121 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwLW9av70LcQVzmiT4l:-NwjEqqg4LSr-RVXUAiw:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/312d92652f98e08bfbea2e8990f001fece462062/packages/geoview-core/src/api/config/utils.ts#L121)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This function will be run by layer api, config will receive the layer one by one as layer api process them
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/map-features-config.ts` line 118 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwLWm5O8JwIqsOhLZ0E:-NwjF0MWD_H-ghMDTWWb:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/312d92652f98e08bfbea2e8990f001fece462062/packages/geoview-core/src/api/config/types/classes/map-features-config.ts#L118)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Like we discuss yesterday. I would like to have distinc function to get map config (JSON valid with default). This should not be async.... Once wiewer receive this, he will process the formatted list of layer and send them one by one to config. This function can be async
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 22 of 24 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054)* status: 26 of 28 files reviewed, 2 unresolved discussions (waiting on @ychoquet)

___
*[`packages/.babelrc` line 2 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwnvRRZDQRHWS_viWc5:-NwnvRR_0cxtlkVQZufL:bz6pv05) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/baca85d75e4c7bacf7d40430791be45d3f1ab2d0/packages/.babelrc#L2)):*
> ```jsonc
> {
>   "presets": [
> ```

You didn't say you wanted to remove this file?

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054)* status: 26 of 28 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/.babelrc` line 2 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2054#-NwnvRRZDQRHWS_viWc5:-NwoGDGp0abOZ5V1Ke_N:b95i123) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/baca85d75e4c7bacf7d40430791be45d3f1ab2d0/packages/.babelrc#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You didn't say you wanted to remove this file?
</blockquote></details>

You told me that you don't have it in your code. This file is unused.

**Pull request merged**
