### PR TITLE
Fixing some async stuff and removed some setTimeout

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

New getLayerConfigAsync function
Vector, Dynamic and WMS done-ish
Better error handling in Plugin async logic
Core functions
Log error when unable to calculate bounds on layer applyViewFilter
createMapFromConfig fixes
Added async when setting projection and showing circular progress
Removed timeout in default-config.html following earlier fix with createMapFromConfig
Cleanup

Fixes some async stuff all around and #1618 on the side (with Johann's modifications around footer package too)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

On my host: https://alex-nrcan.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684)

### CODE REVIEW

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 12 of 15 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684)* status: all files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/app.tsx` line 152 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684#-NoDMnOe7ncO5uhvAVYs:-NoDMnOe7ncO5uhvAVYt:bw3xeoi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a723751925cfd3e27be3771e06311e5626650ff9/packages/geoview-core/src/app.tsx#L152)):*
> ```XML
>   }
>   // Wait for map renders to end. Note: the api.readyCallback isn't quite done yet; that's different.
>   await Promise.all(promises);
> ```

Do we want to stop execution on the first renderMap that throw an error or we want all render to be executed (Promise.allSettled) and deal with all error thrown at the end?



_Code quote:_
```XML
await Promise.all(promises);
```
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 422 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684#-NoDQwH-Di2LP2JNJvET:-NoDQwH-Di2LP2JNJvEU:b-vtle6q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a723751925cfd3e27be3771e06311e5626650ff9/packages/geoview-core/src/geo/layer/layer.ts#L422)):*
> ```XML
>   ): Promise<AbstractGeoViewLayer | null> => {
>     // Redirects
>     const lyr = this.getGeoviewLayerById(geoviewLayerId);
> ```

The programmer's guide in the documentation says that for clarity, it is better to write complete words in properties/methodes name. In this case, lyr sould be writen as layer.



_Code quote:_
```XML
lyr 
```
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1015 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684#-NoDTktx2c9izwUDltN0:-NoDTkty0w-ooNeGBikT:b-ya81ng) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a723751925cfd3e27be3771e06311e5626650ff9/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1015)):*
> ```XML
>   ): Promise<TypeLayerEntryConfig | null> {
>     // Redirects
>     const lyr = this.getLayerConfig(layerPath);
> ```

Same as above



_Code quote:_
```XML
lyr
```
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 781 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684#-NoDV7Mp8H2mO_yhDCD4:-NoDV7Mp8H2mO_yhDCD5:b8exyo1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a723751925cfd3e27be3771e06311e5626650ff9/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L781)):*
> ```XML
>     // Get the layer config in a loaded phase
>     const layerConfig = await this.getLayerConfigAsync(layerPath, true);
>     if (!layerConfig) throw new Error(`Couldn't applyViewFilter for esri-dynamic as couldn't get layer config for layerPath ${layerPath}`);
> ```

When there is an error, should we set the layerStatus to error to warn users and prevent them (if they take into account the layerStatus) from using the layer?



_Code quote:_
```XML
if (!layerConfig) throw new Error(`Couldn't applyViewFilter for esri-dynamic as couldn't get layer config for layerPath ${layerPath}`);
```
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 237 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684#-NoDWeJLBrQCl6Kakdb7:-NoDWeJM4eAEctDC1Asr:b3dvyeb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a723751925cfd3e27be3771e06311e5626650ff9/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L237)):*
> ```XML
>       // TO.DO.CONT: undefined, it crashes (which I'm fine with it), but then returns empty array which
>       // TO.DO.CONT: seems to be different behavior than in `getFeatureInfoAtPixel`? Should it be 'standard' (`null` or `[]`)?
>       // TO.DO.CONT: Leaving logic untouched on this PR to minimize impacts.
> ```

The methode getAllFeatureInfo can have three values for TypeArrayOffFeatureInfoEntries:
undefine means the querry has been sent and we're waiting for the answer;
null means qhe querry ended with an error;
TypeFeatureInfoEntry[] is the result set returned by the querry.

Mormally, getAllFeatureInfo never returns undefined. This value is set in the FeatureInfoLayerSet class before sending the event GET_FEATURE_INFO.QUERY_LAYER.



_Code quote:_
```XML
      // TODO: Check - Is it okay to not have the `| null` at the end of here? The way it is here, when layerConfig is
      // TO.DO.CONT: undefined, it crashes (which I'm fine with it), but then returns empty array which
      // TO.DO.CONT: seems to be different behavior than in `getFeatureInfoAtPixel`? Should it be 'standard' (`null` or `[]`)?
      // TO.DO.CONT: Leaving logic untouched on this PR to minimize impacts.
```

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 11 of 15 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684)* status: all files reviewed, 5 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/app.tsx` line 152 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684#-NoDMnOe7ncO5uhvAVYs:-NoEplykDKn42m9A7blt:b-dfhx9a) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a723751925cfd3e27be3771e06311e5626650ff9/packages/geoview-core/src/app.tsx#L152)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Do we want to stop execution on the first renderMap that throw an error or we want all render to be executed (Promise.allSettled) and deal with all error thrown at the end?
</blockquote></details>

Hmm good question.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 781 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684#-NoDV7Mp8H2mO_yhDCD4:-NoEqFBa82HNiIsen993:b-q1wmex) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a723751925cfd3e27be3771e06311e5626650ff9/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L781)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

When there is an error, should we set the layerStatus to error to warn users and prevent them (if they take into account the layerStatus) from using the layer?
</blockquote></details>

I'm fine with either/or personally.

The reason I touched those functions was because I saw in the comment something like `We must wait for the layer to be created.`, which I figured might have been causing issues in past(?) and possibly awating on it by calling the new `await getLayerConfigAsync` function was going to fix those issues and make it more stable?
I can make it return nothing like it was when it was synchronically failing (is that going to set the status to error though?)
I'm open on it.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 237 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684#-NoDWeJLBrQCl6Kakdb7:-NoErUjh-sN1Yc_VJL8q:brgeo1s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a723751925cfd3e27be3771e06311e5626650ff9/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L237)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

The methode getAllFeatureInfo can have three values for TypeArrayOffFeatureInfoEntries:
undefine means the querry has been sent and we're waiting for the answer;
null means qhe querry ended with an error;
TypeFeatureInfoEntry[] is the result set returned by the querry.

Mormally, getAllFeatureInfo never returns undefined. This value is set in the FeatureInfoLayerSet class before sending the event GET_FEATURE_INFO.QUERY_LAYER.
</blockquote></details>

Yeah I understand about the 4 returns scenarios (undefined, null, [] or [...]), but when you look at the catch (or when layer config isn't found), this function `getAllFeatureInfo`returns an empty array, while `getFeatureInfoAtPixel` below returns `null` in the catch (or when the layer config isn't found). Shouldn't both of these (and `getFeatureInfoAtCoordinate`, `getFeatureInfoAtLongLat`, etc ) have the same logic in their returns?
As for the `getLayerConfigAsync`change that I'm suggesting specifically, when that fails, it goes in the catch pattern (reason why I'm pointing this out).

Also, on two other notes:

(1) notice the getLayerConfigAsync line here ends like: `as TypeLayerEntryConfig`, but in `getFeatureInfoAtPixel`below it ends like `as TypeLayerEntryConfig | null` (explicitely handling the null case of the promise). I'd like to standardize that as well if possible. I just wasn't sure what the intend was supposed to be, because they were returning different things in their catch ([] vs null). `wms` and `esri-dynamic` classes, for examples, also have this in this PR.

(2) if you look at `getFeatureInfoAtCoordinate` it returns `Promise<TypeArrayOfFeatureInfoEntries>`, however, in the implementation, it redirects to `getFeatureInfoAtPixel` which returns `Promise<TypeArrayOfFeatureInfoEntries | null>` (explicitely suggesting the null scenario of the promise). Maybe that should be standardized too? Doing so would, at the same time, help making sure the null return is properly handled when awaiting? (similar to note (1))

**Review by ychoquet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684)* status: all files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/app.tsx` line 152 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684#-NoDMnOe7ncO5uhvAVYs:-NoHx_zQ65wdfvapvP0Q:b-osc4hf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a723751925cfd3e27be3771e06311e5626650ff9/packages/geoview-core/src/app.tsx#L152)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Hmm good question.
</blockquote></details>

Ask Johann what he wants. I know that the viewer should try to do a fail over when there is a config error using default values.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 781 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684#-NoDV7Mp8H2mO_yhDCD4:-NoHy_I3-Fd9yruGyx4W:b-ag28lk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a723751925cfd3e27be3771e06311e5626650ff9/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L781)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I'm fine with either/or personally.

The reason I touched those functions was because I saw in the comment something like `We must wait for the layer to be created.`, which I figured might have been causing issues in past(?) and possibly awating on it by calling the new `await getLayerConfigAsync` function was going to fix those issues and make it more stable?
I can make it return nothing like it was when it was synchronically failing (is that going to set the status to error though?)
I'm open on it.
</blockquote></details>

Well, I think setting the layerStatus to error goes against the fail over I just explained. Let's leave it like that for the moment, we'll see if it cause problems.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 237 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684#-NoDWeJLBrQCl6Kakdb7:-NoI0Prw6VERfJcXED5N:b-ghyn2g) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a723751925cfd3e27be3771e06311e5626650ff9/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L237)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Yeah I understand about the 4 returns scenarios (undefined, null, [] or [...]), but when you look at the catch (or when layer config isn't found), this function `getAllFeatureInfo`returns an empty array, while `getFeatureInfoAtPixel` below returns `null` in the catch (or when the layer config isn't found). Shouldn't both of these (and `getFeatureInfoAtCoordinate`, `getFeatureInfoAtLongLat`, etc ) have the same logic in their returns?
As for the `getLayerConfigAsync`change that I'm suggesting specifically, when that fails, it goes in the catch pattern (reason why I'm pointing this out).

Also, on two other notes:

(1) notice the getLayerConfigAsync line here ends like: `as TypeLayerEntryConfig`, but in `getFeatureInfoAtPixel`below it ends like `as TypeLayerEntryConfig | null` (explicitely handling the null case of the promise). I'd like to standardize that as well if possible. I just wasn't sure what the intend was supposed to be, because they were returning different things in their catch ([] vs null). `wms` and `esri-dynamic` classes, for examples, also have this in this PR.

(2) if you look at `getFeatureInfoAtCoordinate` it returns `Promise<TypeArrayOfFeatureInfoEntries>`, however, in the implementation, it redirects to `getFeatureInfoAtPixel` which returns `Promise<TypeArrayOfFeatureInfoEntries | null>` (explicitely suggesting the null scenario of the promise). Maybe that should be standardized too? Doing so would, at the same time, help making sure the null return is properly handled when awaiting? (similar to note (1))
</blockquote></details>

In this case, we must revise the return types of all these fellows because they must be compatible to the communicastion strategy we want to implement.

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684)* status: all files reviewed, 4 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/app.tsx` line 152 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684#-NoDMnOe7ncO5uhvAVYs:-NoIKnGM-EUXSQz4AoNP:bok87v0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a723751925cfd3e27be3771e06311e5626650ff9/packages/geoview-core/src/app.tsx#L152)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Ask Johann what he wants. I know that the viewer should try to do a fail over when there is a config error using default values.
</blockquote></details>

I've added a TODO for this.
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 422 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684#-NoDQwH-Di2LP2JNJvET:-NoIKZRoEDuWkpR8W_MS:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a723751925cfd3e27be3771e06311e5626650ff9/packages/geoview-core/src/geo/layer/layer.ts#L422)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

The programmer's guide in the documentation says that for clarity, it is better to write complete words in properties/methodes name. In this case, lyr sould be writen as layer.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1015 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684#-NoDTktx2c9izwUDltN0:-NoIK_GP6pIPFvS0Nahc:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a723751925cfd3e27be3771e06311e5626650ff9/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1015)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 781 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684#-NoDV7Mp8H2mO_yhDCD4:-NoIIGyB9lPeizmozTn2:b-wyjihm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a723751925cfd3e27be3771e06311e5626650ff9/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L781)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Well, I think setting the layerStatus to error goes against the fail over I just explained. Let's leave it like that for the moment, we'll see if it cause problems.
</blockquote></details>

Leaving it like that as discussed in the scrum meeting
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 237 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684#-NoDWeJLBrQCl6Kakdb7:-NoIKfnI-8ap0pGBKoy9:bd80uf6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a723751925cfd3e27be3771e06311e5626650ff9/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L237)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

In this case, we must revise the return types of all these fellows because they must be compatible to the communicastion strategy we want to implement.
</blockquote></details>

I've added/edited TODOs for this

**Review by jolevesq — APPROVED** [review]
> Reviewed 11 of 15 files at r1, 4 of 4 files at r2, 3 of 4 files at r3, 1 of 2 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684)* status: all files reviewed, 4 unresolved discussions (waiting on @ychoquet)

**Review by ychoquet — APPROVED** [review]
> Reviewed 3 of 4 files at r3, 1 of 2 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1684)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Pull request merged**
