### PR TITLE
1044-Introspect-date-format

### LINKED ISSUE #1044: Introspect date format
We want the layers to be able to determine the date format when the configuration file does not give any information on it.

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

Added an introspection routine to deduce the date format when not specified in the config file.
Standardization of date processing both internally and externally.
Fixed a bug on the legend filter.
Fixed the bug of double loading of features on ESRI feature layers.

Fixes #1044 [Introspect date format](https://github.com/canadian-geospatial-platform/geoview/issues/1044)
         #1051 [Esri feature loads twice](https://github.com/canadian-geospatial-platform/geoview/issues/1051)
         #1060 [uniqueValue Legend filtering bug](https://github.com/canadian-geospatial-platform/geoview/issues/1060)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?

As usual, I used the chrome development tools to locate where the code wasn't working properly and fix the code.

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1061)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1061)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 388 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1061#-NVBXsYs3L365bGts0Ip:-NVBXsYs3L365bGts0Iq:b-tijlkd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a13c7818cea92c4766e01acf404676d66950c7dd/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L388)):*
> ```XML
>    * @param {boolean} checkCluster An optional value to see if we check for clustered layers.
>    */
>   applyViewFilter(
> ```

Is it mostly the same between wms, esri dynamic and vector? CAn we extract common part and just keep final call in these classes?

**Comment by DamonU2** [comment]
Sorry, didn't have time to get through everything, nothing jumped out from a quick overview of the code, but I did find some errors. The geojson is not loading on the first map in package-footer-panel.html, and none of the cluster maps load on cluster.html. Date error on ui-components.html .

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1061)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 388 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1061#-NVBXsYs3L365bGts0Ip:-NVDQDWE7KWIlJ6fsqPb:b-189mem) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a13c7818cea92c4766e01acf404676d66950c7dd/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L388)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is it mostly the same between wms, esri dynamic and vector? CAn we extract common part and just keep final call in these classes?
</blockquote></details>

After checking and trying to unify everything, I have come to the conclusion that it is better to keep things separate. There are small things that make unification very difficult.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1061)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

___
*[`packages/geoview-core/public/templates/ui-components.html` line 74 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1061#-NVGKE3X3ohmbSFexRZc:-NVGKE3X3ohmbSFexRZd:b-jxo91m) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/406117392d629e693a856080076edb5b2b0ba408/packages/geoview-core/public/templates/ui-components.html#L74)):*
> ```HTML
>                 'geoviewLayerId': 'historical-flood',
>                 'geoviewLayerName': { 'en': 'Historical Flood Events (HFE)' },
>                 'serviceDateFormat': 'mm/dd/yyyy',
> ```

Can you change the code because the page is calling setLayerFilter and function not there anymore.

-components.html:59 Uncaught TypeError: cgpv.api.maps.UI1.layer.geoviewLayers.historical-flood.setLayerFilter is not a function

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1061)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/ui-components.html` line 74 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1061#-NVGKE3X3ohmbSFexRZc:-NVH1RvR-KeUuVo_mgCR:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/406117392d629e693a856080076edb5b2b0ba408/packages/geoview-core/public/templates/ui-components.html#L74)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you change the code because the page is calling setLayerFilter and function not there anymore.

-components.html:59 Uncaught TypeError: cgpv.api.maps.UI1.layer.geoviewLayers.historical-flood.setLayerFilter is not a function
 
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1061)* status: 24 of 29 files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 5 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1061)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Pull request merged**
