### PR TITLE
Using Arrows to Re-order Layers

### LINKED ISSUE #2010: [BUG] [Layers]  Make draggable work in sort.. otherwise switch to using arrows.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Make draggable work in sort.. otherwise switch to using arrows.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

Make draggable work in sort.. otherwise switch to using arrows.

Fixes #2010 

image

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://cphelefu.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2063)

### CODE REVIEW

**Review by kaminderpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2063)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2063#-Nwk6et02EbpyXUUjwGZ:-Nwk6et02EbpyXUUjwG_:b-jcemj7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/288706bd66d67ebf92d148c29b6f6d3c1e0df12e/packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx#L37)):*
> ```XML
> 
>   // ? I doubt we want to define an explicit type for style properties?
>   // eslint-disable-next-line @typescript-eslint/no-explicit-any
> ```

i think we can remove this comment.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2063#-Nwk6et02EbpyXUUjwGZ:-Nwk7pSI4Lx5ILpTOTM5:bvt4ip5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d89e401efa0635df5f266ca2d2ce6926f10bb405/packages/geoview-core/src/core/components/layers/left-panel/layers-list.tsx#L37)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

i think we can remove this comment.
</blockquote></details>

We need this line for the getListClass below it

**Review by kaminderpal — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2063#-:-NwkC_Ub5t7mUC9uWIG4:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2063)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
