### PR TITLE
refactor(map-events) Moved the generic map events to MapViewer - Privatization of functions - Documentation - Spinner delay and more

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

- Event emits now private
- MAP events moved to MapViewer
- Better mouse wheel handling when over the map
- Crosshair fix when querying
- Async fix with the scale control to wait for it to be ready before saving to store
- Now waiting a minimum period before removing the loading spinning circle overlay
- Cleanup and rewriting of many comments/jsdocs
- Replaced wire/unwire terms to register/unregister terms as that seems to be more the convention in JavaScript

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Hosted here as of April 2nd 15h40: https://alex-nrcan.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1978)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 35 of 37 files at r1, 16 of 17 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1978)* status: all files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/public/templates/events.html` line 124 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1978#-NuUmTMz7okRikuhJjsn:-NuUmTMz7okRikuhJjso:b8zx48p) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6e79be6a9c5737316230397985141538477f90a7/packages/geoview-core/public/templates/events.html#L124)):*
> ```HTML
>           });
> 
>           // listen to map moveend event
> ```

typo map rotation
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 102 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1978#-NuUn2UQ26piIntQTDUJ:-NuUn2UQ26piIntQTDUK:bwnx3hw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6e79be6a9c5737316230397985141538477f90a7/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L102)):*
> ```XML
>   }
> 
>   // GV THIS IS THE ONLY FUNCTION TO SET STORE DIRECTLY
> ```

This comment is not true anymore, can remove.... now it sues the new setter actions
___
*[`packages/geoview-core/src/core/components/crosshair/crosshair.tsx` line 53 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1978#-NuUr2Tf7kZyGV2Ho4c0:-NuUr2Tf7kZyGV2Ho4c1:b7oi3at) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6e79be6a9c5737316230397985141538477f90a7/packages/geoview-core/src/core/components/crosshair/crosshair.tsx#L53)):*
> ```XML
> 
>         // Perform query via the feature info layer set process
>         api.maps[mapId].layer.featureInfoLayerSet.queryLayers(pointerPosition.lnglat);
> ```

You do not prefer to use  the store setClick... to call the mapEventProcessor to do the action instead of linking api to component?
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts` line 163 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1978#-NuUr_sW27W7kN9B0-n2:-NuUr_sW27W7kN9B0-n3:b7wk4g3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9a2a969d85167bf85ae36a05a1a2d08c622c41b0/packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts#L163)):*
> ```XML
>           basemapOptions: geoviewConfig.map.basemapOptions,
>           centerCoordinates: geoviewConfig.map.viewSettings.center as Coordinate,
>           currentProjection: geoviewConfig.map.viewSettings.projection as TypeValidMapProjectionCodes,
> ```

Why are not using the type anymore?
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 220 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1978#-NuUu4kr2I5lThx4ccj2:-NuUu4ks55yEN6VJbQP4:bez0l04) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8598cc39f5ed9248459a8c52642640e691e34fa6/packages/geoview-core/src/geo/layer/layer.ts#L220)):*
> ```XML
>    * Validates the geoview layer configuration array to eliminate duplicate entries and inform the user.
>    * @param {MapConfigLayerEntry[]} mapConfigLayerEntries The Map Config Layer Entries to validate.
>    * @returns {MapConfigLayerEntry[]} The new configuration with duplicate entries eliminated.
> ```

Should you add @private?
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 245 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1978#-NuUuAF6DWf5wEKxLhkZ:-NuUuAF6DWf5wEKxLhk_:bitacsr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8598cc39f5ed9248459a8c52642640e691e34fa6/packages/geoview-core/src/geo/layer/layer.ts#L245)):*
> ```XML
>    * Prints an error message for the duplicate geoview layer configuration.
>    * @param {MapConfigLayerEntry} geoviewLayerConfig The Map Config Layer Entry in error.
>    */
> ```

Should you add @private
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 452 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1978#-NuUuMyF3w-pYa_7-F5g:-NuUuMyG9M_t5XMmOq7h:bez0l04) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8598cc39f5ed9248459a8c52642640e691e34fa6/packages/geoview-core/src/geo/layer/layer.ts#L452)):*
> ```XML
>    * @param {AbstractGeoViewLayer} geoviewLayer The Geoview layer to register
>    * @param {GeoViewLayerRegistrationEvent} registrationEvent The registration event
>    */
> ```

Should you add @private?
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 1207 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1978#-NuUwlu_As26-Uqke2Pq:-NuUwlu_As26-Uqke2Pr:bk3xq0o) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6e79be6a9c5737316230397985141538477f90a7/packages/geoview-core/src/geo/map/map-viewer.ts#L1207)):*
> ```XML
>    */
>   zoomToExtent(extent: Extent, options?: FitOptions): Promise<void> {
>     // TODO: Discussion - Where is the line between a function using MapEventProcessor in MapViewer vs in MapState action?
> ```

We use to have this before.... it is a hard line to draw. the one from map sate action is called by component tsx file. The one from map viewer ts are in mapEventProcessor. Then the setter action in mapsate should help to wrap the rest... let<S discuss to make this clear....
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 1224 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1978#-NuUwNGbANgLZKvri97D:-NuUwNGc7Th5ms9L3B87:b-e0unni) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6e79be6a9c5737316230397985141538477f90a7/packages/geoview-core/src/geo/map/map-viewer.ts#L1224)):*
> ```XML
>    */
>   // TODO: only use in the layers panel package... see if still needed and if it is the right place
>   fitBounds(bounds?: Extent, projectionCode: string | number | undefined = undefined) {
> ```

If it return nothing, should we add :void

**Review by jolevesq — COMMENTED** [review]
> Reviewed 6 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1978)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1978)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2 and @ychoquet)

**Review by ychoquet — COMMENTED** [review]
> Reviewed 21 of 37 files at r1, 15 of 17 files at r2, 2 of 3 files at r3, 6 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1978)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

**Pull request merged**
