### PR TITLE
feat(Utils): Calculate distance utilities function

### LINKED ISSUE #2378: [FEATURE] Utilities to Calculate sphere distance
**Is there an existing issue for this?**
Please search to see if an issue already exists for this feature.
No

**Who request this Feature**
Individual, team, project, organization...
OSDP

**User Story**
A concise description of what you expected to happen (one paragraph).
As a dev, I would like to be able to enter a geometry and calculate distance and area

**Implementation UI**
If needed, what user interface do you suggest, feel free to add mockups.
Add a utilities function in our geo api to get a geometry and output distance

https://openlayers.org/en/latest/examples/measure.html

```
import {getArea, getLength} from 'ol/sphere.js';

/**
 * Format length output.
 * @param {LineString} line The line.
 * @return {string} The formatted length.
 */
const formatLength = function (line) {
  const length = getLength(line);
  let output;
  if (length > 100) {
    output = Math.round((length / 1000) * 100) / 100 + ' ' + 'km';
  } else {
    output = Math.round(length * 100) / 100 + ' ' + 'm';
  }
  return output;
};

/**
 * Format area output.
 * @param {Polygon} polygon The polygon.
 * @return {string} Formatted area.
 */
const formatArea = function (polygon) {
  const area = getArea(polygon);
  let output;
  if (area > 10000) {
    output = Math.round((area / 1000000) * 100) / 100 + ' ' + 'km<sup>2</sup>';
  } else {
    output = Math.round(area * 100) / 100 + ' ' + 'm<sup>2</sup>';
  }
  return output;
};
```

**Additional context**

### PR DESCRIPTION
**Pull request by jolevesq**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- Calculate distance function
- Demo for World of Maps

Fixes #2378 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Hosted, July 24th: 9:30:
https://jolevesq.github.io/geoview/demo-function-event.html
https://jolevesq.github.io/geoview/demo-world-of-maps.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2401)

### CODE REVIEW

**Review by Alex-NRCan — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2401#-:-O2Zzu2EA0SRPEupN68u:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Review by DamonU2 — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2401)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2401)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2401)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
