### PR TITLE
feat(load): Add geometries from API call  set by URL parameter

### LINKED ISSUE #110: Use api to draw vector on map
Use an api like http://pygeoapi.geocat.live/collections/nrcan-geocore/items/000183ed-8864-42f0-ae43-c4313a860720 to add automatically  vector on map.

We may have a drop down to select different id and use the answer to add a vector on the map.

Related to the vector sample page #91

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #110

We can test the deploy because the api used is only http and GitHub only allows call from https.

## Checklist

* [x] Commit message follow the guidelines
* [x] PR targets the correct release version
* [x] Deploy has been done
* [x] Check styling
* [ ] _Help files and documentation have been updated_
* [ ] ~Release notes have been updated~

## What's to look for styling
* Use camelCase for identifier names (variables and functions)
* Use PascalCase for type names
* Do not use "I" as a prefix for interface names
* Do not export types/functions unless you need to share it across multiple components
* All names start with a letter
* Always put spaces around operators ( = + - * / ), and after colon:
* Remove all trailing white spaces
* Look for bad indentation
* Carriage return are mandatory
  * Before comments
  * Before if condition
  * After if condition
  * Before properties
  * Before classes
  * Before functions

The use of Prettier Visual Studio Code extension let's you format automatically your code to remove most of the styling issues like white space and indentation.

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/141)

### CODE REVIEW

**Review by yass0016 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/141)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[src/components/map/map.tsx, line 134 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/141#-MVNQnBK9xjOTMtyzGTj:-MVNQnBLBU4r92Mho9oJ:bp56i5y) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/65d74637ec94b0a4f1af18c0bad58ddbdae0f29e/src/components/map/map.tsx#L134)):*
> ```XML
> 
>                 // check if geometries are provided from url
>                 viewer.loadGeomtries();
> ```

This can be moved to init in map-viewer

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/141)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @yass0016)

___
*[src/components/map/map.tsx, line 134 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/141#-MVNQnBK9xjOTMtyzGTj:-MVNTnG365bbptfSK6zp:bb6un1j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/65d74637ec94b0a4f1af18c0bad58ddbdae0f29e/src/components/map/map.tsx#L134)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

This can be moved to init in map-viewer
</blockquote></details>

Done

**Review by yass0016 — APPROVED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/141)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by yass0016 — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/141)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/141#-:-MVNkVV065_5_nNBLHyP:bnfp4nl)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @yass0016)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/141)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
