### PR TITLE
refactor(map): Create a map state to encapsulate map properties and i…

### LINKED ISSUE #1566: [REFACTOR} Initialize Layer Store event
Set all store attribute initialize in a central location once the layer object / ol layer is ready. e.g. bounds calculation.

- [ ] bounds
- [ ] table available flag (to build data table layer list). Then we should create table only when selected
- [ ] feature info available flag
- [ ] ...
related to #1560

All init value will propagate to the store sot hey can be use...

### PR DESCRIPTION
**Pull request by jolevesq**
…nit within store

Closes 1566

# Description

 Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- Centralize init in the store state section
- Stat the removal of api access to get info, replaced it by map event process static functions
- Use map event processor function to access api instead of store directly

Fixes #1566 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://jolevesq.github.io/geoview/package-footer-panel.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1570)

### CODE REVIEW

**Review by kaminderpal — CHANGES_REQUESTED** [review]
> Reviewed 38 of 38 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1570)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @jolevesq, @mayurmarakana89, and @ychoquet)

___
*[`packages/geoview-core/src/core/components/data-table/json-export-button.tsx` line 47 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1570#-NkausDbDh0PiMIj6M_F:-NkausDc-w7TLJpTgxIF:b-j3nr88) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d70ffa1ed6ad89b6745d1d5b1260621b2c69131/packages/geoview-core/src/core/components/data-table/json-export-button.tsx#L47)):*
> ```XML
>       };
>     } else if (geometry instanceof LineString) {
>       builtGeometry = { type: 'LineString', coordinates: geometry.getCoordinates().map((coord) => toLonLat(coord, `EPSG: ${projection}`)) };
> ```

this can be extracted into new variable, as it used in `Multipoint`

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1570)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @jolevesq, @mayurmarakana89, and @ychoquet)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 164 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1570#-Nkb7a_X9Te6rdzkn0FU:-Nkb7a_X9Te6rdzkn0FV:b-u5i0xz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/98485174918c033831f2e9975db48c0b42a6f653/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L164)):*
> ```XML
>   //! THIS IS THE ONLY FUNCTION TO SET STORE DIRECTLY
>   static setMapLoaded(mapId: string): void {
>     // use api to access map because this function will set amp element in store
> ```

amp > map

**Review by kaminderpal — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1570)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @jolevesq, @mayurmarakana89, and @ychoquet)

**Review by kaminderpal — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1570#-:-NkpShT3Es2v-sWPjxHx:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @jolevesq, @mayurmarakana89, and @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 37 of 38 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1570)* status: 34 of 41 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @kaminderpal, @mayurmarakana89, and @ychoquet)

___
*[`packages/geoview-core/src/core/components/data-table/json-export-button.tsx` line 47 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1570#-NkausDbDh0PiMIj6M_F:-NkpA76qCz5y1OFtshb8:b-6z4c11) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d70ffa1ed6ad89b6745d1d5b1260621b2c69131/packages/geoview-core/src/core/components/data-table/json-export-button.tsx#L47)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

this can be extracted into new variable, as it used in `Multipoint`
</blockquote></details>

This section will be modify in another PR where we will remove all ol actions

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1570)* status: 35 of 41 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @kaminderpal, @mayurmarakana89, and @ychoquet)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 164 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1570#-Nkb7a_X9Te6rdzkn0FU:-NkpwUqY2XSdaumTaa6C:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/98485174918c033831f2e9975db48c0b42a6f653/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L164)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

amp > map
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1570)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @DamonU2, @kaminderpal, @mayurmarakana89, and @ychoquet)

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1570)* status: all files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, @jolevesq, @kaminderpal, @mayurmarakana89, and @ychoquet)

___
*[`packages/geoview-core/src/core/components/data-table/json-export-button.tsx` line 41 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1570#-NkqGwnM7bIu7UrIw40h:-NkqGwnM7bIu7UrIw40i:bnhlgo5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/377722948c72f38c1a7388e80bbcb214cae3edb1/packages/geoview-core/src/core/components/data-table/json-export-button.tsx#L41)):*
> ```XML
>         type: 'Polygon',
>         coordinates: geometry.getCoordinates().map((coords) => {
>           return coords.map((coord) => transformPoints([coord], 4326)[0]);
> ```

I am just wondering where does the number 4326 come from? if this number always remains the same, can we export it from a constant file?

**Pull request merged**
