### PR TITLE
523 code the renderer for vector layers

### PR DESCRIPTION
**Pull request by ychoquet**
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/524)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 19 of 21 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/524)* status: all files reviewed, 3 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 219 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/524#-NBYNpfJBcXDR1jzavsi:-NBYNpfJBcXDR1jzavsj:b-pulw93) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/16166855cf9fae5044cb3588abab3fe2b56c84ab/packages/geoview-core/src/geo/map/map-schema-types.ts#L219)):*
> ```XML
>  * Stroke style for vector features.
>  */
> export type TypeStrokeSymbolConfig = {
> ```

You replaces stroke by line at few places... should it be stroke here?
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 502 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/524#-NBYORFa2KQlGEtZGaAv:-NBYORFb-aC0S2y1GiOO:b-mh37hp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/16166855cf9fae5044cb3588abab3fe2b56c84ab/packages/geoview-core/src/geo/map/map-schema-types.ts#L502)):*
> ```XML
>  * @return {boolean} true if the type ascention is valid.
>  */
> export const layerEntryIsVectorTile = (verifyIfLayer: TypeLayerEntryConfig): verifyIfLayer is TypeVectorLayerEntryConfig => {
> ```

The vector tile renderer will work differently then vector renderer as it is generated at the vector tile creation process
___
*[`packages/geoview-core/src/geo/renderer/esri-renderer.ts` line 2 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/524#-NBYOvEX365PXgfrQXT1:-NBYOvEYA6Latax2-577:b3965zm) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/16166855cf9fae5044cb3588abab3fe2b56c84ab/packages/geoview-core/src/geo/renderer/esri-renderer.ts#L2)):*
> ```XML
> /* eslint-disable no-console */
> import { asString } from 'ol/color';
> ```

Do you need this class? ESRI renderer are not automatically applied to the layer? With this class it means we can even drop the ESRI and take info from metadata and use GeoJSON?

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/524)* status: 19 of 21 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 219 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/524#-NBYNpfJBcXDR1jzavsi:-NBYaca0B8QOh9R42obi:berzjnw) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/16166855cf9fae5044cb3588abab3fe2b56c84ab/packages/geoview-core/src/geo/map/map-schema-types.ts#L219)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You replaces stroke by line at few places... should it be stroke here?
</blockquote></details>

Not necessarily, this is realy the line style to apply to the stroke. 
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 502 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/524#-NBYORFa2KQlGEtZGaAv:-NBYZpoOCzU9_54yB0Ho:byrtgec) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/16166855cf9fae5044cb3588abab3fe2b56c84ab/packages/geoview-core/src/geo/map/map-schema-types.ts#L502)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The vector tile renderer will work differently then vector renderer as it is generated at the vector tile creation process
</blockquote></details>

Currently, the code only implement vector. I created vectorTile in prevision of the futur implementation. We will have to modify the schema to allow the user to specify that he wants to use tile vector. 
___
*[`packages/geoview-core/src/geo/renderer/esri-renderer.ts` line 2 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/524#-NBYOvEX365PXgfrQXT1:-NBY_frYE-3xzwt7WMZF:b-52blbk) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/16166855cf9fae5044cb3588abab3fe2b56c84ab/packages/geoview-core/src/geo/renderer/esri-renderer.ts#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do you need this class? ESRI renderer are not automatically applied to the layer? With this class it means we can even drop the ESRI and take info from metadata and use GeoJSON?
</blockquote></details>

I think that if we do not specify a style in Openlayers, the esri style will automaticaly be applied. However, if we do so, it will be harder to allow the user to overide the esri style provided by the server.

**Review by jolevesq — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/524#-:-NBYc-aF-kalXjH8312f:bg7igkv)* status: 20 of 21 files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 8 files at r5, 6 of 10 files at r6, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/524)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 288 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/524#-NBlTlebD764wgyENTww:-NBlTlebD764wgyENTwx:b-s5btx5) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2a051052bdca0d54898073a76f616774e72fbbc1/packages/geoview-core/src/core/utils/config/config-validation.ts#L288)):*
> ```XML
> 
>             api.event.emit(
>               snackbarMessagePayload(EVENT_NAMES.SNACKBAR.EVENT_SNACKBAR_OPEN, this.mapId, {
> ```

There is no more error message when config validation fails?

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/524)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 288 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/524#-NBlTlebD764wgyENTww:-NBlwhld6mtPxPfXRbjb:b-2bcrp1) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2a051052bdca0d54898073a76f616774e72fbbc1/packages/geoview-core/src/core/utils/config/config-validation.ts#L288)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There is no more error message when config validation fails?
</blockquote></details>

Actually, the display time of the snackbar error message is too short for us to read the message and the number of messages is very high. So, the only way to let us see what is wrong is to print it in the console. If you prefer, we can print a snackbar that says "There is a schema error, check the console to see what is wrong".

**Review by jolevesq — APPROVED** [review]
> Reviewed 10 of 11 files at r11, 1 of 1 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/524)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/524#-:-NBmcQ629epQC5fwrn77:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> Reviewed 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/524)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/524)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
