### PR TITLE
refactor(geocore-layer) Removed GeoCore from a 'Layer', now only a MapConfigLayerEntry option

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

This PR aims to remove GeoCore from the GeoView Layers logic. GeoCore remains a possible layer config in the configuration, but it is not a 'type of geoview layer' anymore.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Hosted here as of March 13 16h00:
- https://alex-nrcan.github.io/geoview/geocore.html
- https://alex-nrcan.github.io/geoview/all-layers.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917)

### CODE REVIEW

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 9 of 16 files at r1, 7 of 10 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917)* status: 16 of 18 files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 7 of 16 files at r1, 9 of 10 files at r2, 1 of 2 files at r3, 3 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917)* status: 15 of 18 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/core/utils/config/config.ts` line 127 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-Nsrh25T1ChHf60rKPK1:-Nsrh25T1ChHf60rKPK2:b3uwj63) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/86dd5c58987d59c0ea0a40180f744335111d2e2e/packages/geoview-core/src/core/utils/config/config.ts#L127)):*
> ```XML
>       mapFeaturesConfig.map.listOfGeoviewLayerConfig.forEach((geoviewLayerEntry) => {
>         if (mapConfigLayerEntryIsGeoCore(geoviewLayerEntry)) {
>           //  Skip it
> ```

Can we add to the comment why we skip it
___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 481 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-Nsriqcj1NXQWU0qYp-n:-Nsriqcj1NXQWU0qYp-o:b86q8gx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/75eba0849bb4f845ce11ac8b92b1d2662e541b91/packages/geoview-core/src/core/utils/config/config-validation.ts#L481)):*
> ```XML
>       let isValid = this.IsValidTypeMapFeaturesInstance(mapFeaturesConfigToValidate, validator);
>       for (let i = 0; i < mapFeaturesConfigToValidate.map.listOfGeoviewLayerConfig.length && isValid; i++) {
>         // If not GeoCore
> ```

Can you add more comment for what we do if not geocore so we understand why geocore is not treated the same way
___
*[`packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts` line 70 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-Nsrjyc24pZqeFc-eBRI:-Nsrjyc24pZqeFc-eBRJ:b-2tsquw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0700863cd52815d1c7908ea119531f7420c1df5a/packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts#L70)):*
> ```XML
>     if (!result?.data || !result.data.reponse || !result.data.reponse.rcs || !result.data.reponse.rcs[lang])
>       throw new Error('Invalid response from GeoCore service');
>     if (result.data.reponse.rcs[lang].length === 0) throw new Error('No layers returned by GeoCore service');
> ```

Is it not supposed to be ...response.rcs[lang[.layers.length?
___
*[`packages/geoview-core/src/geo/layer/other/geocore.ts` line 52 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-NsrlFyr4Tj6sHjbkoHi:-NsrlFyr4Tj6sHjbkoHj:bqs4lly) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/86dd5c58987d59c0ea0a40180f744335111d2e2e/packages/geoview-core/src/geo/layer/other/geocore.ts#L52)):*
> ```XML
> 
>       // // For each found layer associated with the Geocore UUIDs
>       // response.layers.forEach((geoviewLayerConfig) => {
> ```

Do we still need dead code?
___
*[`packages/geoview-core/src/geo/layer/other/geocore.ts` line 75 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-NsrlMOq1JAbU7qDZiau:-NsrlMOq1JAbU7qDZiav:bgg7y6u) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/86dd5c58987d59c0ea0a40180f744335111d2e2e/packages/geoview-core/src/geo/layer/other/geocore.ts#L75)):*
> ```XML
>   }
> 
>   // /**
> ```

Do we need dead code? To test we should set initial states like layer name and visibility and see if it is injected properly. Technically it is not geocore who does this. It is the proper layer type so we should be able to delete all this.
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 443 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-Nsrlt4t7JPGmk_B47H7:-Nsrlt4t7JPGmk_B47H8:bo1zh41) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/86dd5c58987d59c0ea0a40180f744335111d2e2e/packages/geoview-core/src/geo/map/map-schema-types.ts#L443)):*
> ```XML
>  * List of layers. Corresponds to the layerList defined in the schema.
>  */
> // TODO: Suggestion - Get rid of this type. Simply use TypeLayerEntryConfig[]. It'd simplify types management accross the source code.
> ```

All things derive from this are classes, can we delete this type with no side effect?
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 497 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-Nsrm43jE0QxX9iieKKn:-Nsrm43jE0QxX9iieKKo:b-5il2pu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/86dd5c58987d59c0ea0a40180f744335111d2e2e/packages/geoview-core/src/geo/map/map-schema-types.ts#L497)):*
> ```XML
>    */
>   // TODO: Bug - The geoviewLayerName doesn't override the name from GeoCore. Fix this.
>   geoviewLayerName: TypeLocalizedString;
> ```

On type we should have the initial setting as well. This is to override the information from service.
I think it is working with other type of layer. Now having geocore not a layer type anymore, we should be able to overrides. 

For this we will need a little trick because when we create the config the setting are set at the root level and in our config it will take it from the layerID. There is refactor to do to make this work for all layer type. Global setting should be cascade to child of the root layer.
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 173 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-NsrmuSjAuplzVhewUik:-NsrmuSjAuplzVhewUil:buyggyi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/86dd5c58987d59c0ea0a40180f744335111d2e2e/packages/geoview-core/src/geo/map/map-viewer.ts#L173)):*
> ```XML
>    * @param {MapConfigLayerEntry[]} listOfMapLayerEntryConfig The list of geoview layer configurations.
>    */
>   setLayerAddedListener4ThisListOfLayer(listOfMapLayerEntryConfig: MapConfigLayerEntry[]) {
> ```

We should not have a listener on layer added on map viewer. The viewer does not care about layers status. As soon as the init state is done (store, basemap, plugins, ....) We should remove the spinner. All layers boxes should be there with their status (loading, error, loaded). Their status change but the viewer does not care. We show it in legend and emit an event for the outside world for each status.

Please add a TODO as it is main part of the refactor for splitting validation/layer and make the viewer ready.

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917)* status: 15 of 18 files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/schema.json` line 1161 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-Nss6VzS4LnzHAQxZrBI:-Nss6VzT7-ZZA4Li8mds:boivw9x) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3fc2dbd3314536a935edb384247045a27bf72255/packages/geoview-core/schema.json#L1161)):*
> ```JSON
>     },
>     "TypeLayerEntryType": {
>       "enum": ["vector", "vector-tile", "vector-heatmap", "raster-tile", "raster-image", "geoCore"],
> ```

Remove 'geocore' from 'TypeLayerEntryType'. This type is used by the GeoView layers and 'geocore' is not part of it  anymore.

**Review by ychoquet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917)* status: 15 of 18 files reviewed, 10 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 537 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-NssEaGP1y_xHx6Tz3oI:-NssEaGP1y_xHx6Tz3oJ:bylda7m) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/75eba0849bb4f845ce11ac8b92b1d2662e541b91/packages/geoview-core/src/core/utils/config/config-validation.ts#L537)):*
> ```XML
>    * validate.
>    */
>   private doExtraValidation(listOfMapConfigLayerEntry?: MapConfigLayerEntry[]) {
> ```

Renaming listOfGeoviewLayerConfig to listOfMapConfigLayerEntry is  not a good idea. Everywhere in the code this list is named listOfGeoviewLayerConfig because it contains GeoView Layer Configuration. All the GeoView layers of this list is put on the same map. The map configuration is done using TypeMapFeaturesConfig.

**Review by ychoquet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917)* status: 15 of 18 files reviewed, 11 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 690 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-NssTvK74Z5U2n-0xczY:-NssTvK81S43xLfXpvoh:b2nreh6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/75eba0849bb4f845ce11ac8b92b1d2662e541b91/packages/geoview-core/src/core/utils/config/config-validation.ts#L690)):*
> ```XML
>    * Adjust the map features configuration localized strings according to the suported languages array content.
>    * @param {TypeListOfLocalizedLanguages} suportedLanguages The list of supported languages.
>    * @param {MapConfigLayerEntry[]} listOfMapConfigLayerEntry The list of Map Config Layer Entry configuration to adjust according
> ```

Same as above.

**Review by ychoquet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917)* status: 15 of 18 files reviewed, 12 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 294 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-NssWsCx8p3gKv7dAqDy:-NssWsCx8p3gKv7dAqDz:bfv2lkb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/75eba0849bb4f845ce11ac8b92b1d2662e541b91/packages/geoview-core/src/geo/layer/layer.ts#L294)):*
> ```XML
>     // Wait for all GeoCore to process
>     const orderedLayerInfos: TypeOrderedLayerInfo[] = [];
>     Promise.allSettled(promisesOfGeoCoreGeoviewLayers).then((promisedLayers) => {
> ```

Do we still want to use a promise instead of async/await in our code. I ask because we have begun a transformation of the old promise implementation to async/await and this section of code seems to be a good candidate for async/await.

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917)* status: 15 of 18 files reviewed, 12 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 443 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-Nsrlt4t7JPGmk_B47H7:-NssbDbsB44OqrGyHKUh:b8bsdwr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/86dd5c58987d59c0ea0a40180f744335111d2e2e/packages/geoview-core/src/geo/map/map-schema-types.ts#L443)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

All things derive from this are classes, can we delete this type with no side effect?
</blockquote></details>

It doesn't harm if we rename TypeListOfLayerEntryConfig to TypeLayerEntryConfig[]

**Review by ychoquet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917)* status: 15 of 18 files reviewed, 12 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 537 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-NssEaGP1y_xHx6Tz3oI:-Nsse91Y4xXilUGsC2ad:brar9mk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/75eba0849bb4f845ce11ac8b92b1d2662e541b91/packages/geoview-core/src/core/utils/config/config-validation.ts#L537)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Renaming listOfGeoviewLayerConfig to listOfMapConfigLayerEntry is  not a good idea. Everywhere in the code this list is named listOfGeoviewLayerConfig because it contains GeoView Layer Configuration. All the GeoView layers of this list is put on the same map. The map configuration is done using TypeMapFeaturesConfig.
</blockquote></details>

The way the config is made is a ***Map Features*** section that represent a map which contains a ***list of GeoView layers*** composed of a tree of sublayers recursively defined in a ***list of layer config*** as group/layer entries

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 1 of 5 files at r4, 42 of 42 files at r5.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917)* status: 47 of 50 files reviewed, 12 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/schema.json` line 1161 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-Nss6VzS4LnzHAQxZrBI:-Nssowes341mv3oQY-RB:b-9amwxu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3fc2dbd3314536a935edb384247045a27bf72255/packages/geoview-core/schema.json#L1161)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Remove 'geocore' from 'TypeLayerEntryType'. This type is used by the GeoView layers and 'geocore' is not part of it  anymore.
</blockquote></details>

This is confusing, but it is still a layer entry type as far as the configuration is concerned.
___
*[`packages/geoview-core/src/core/utils/config/config.ts` line 127 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-Nsrh25T1ChHf60rKPK1:-NssphkfDSuLuUKL5d1C:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/86dd5c58987d59c0ea0a40180f744335111d2e2e/packages/geoview-core/src/core/utils/config/config.ts#L127)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we add to the comment why we skip it
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 481 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-Nsriqcj1NXQWU0qYp-n:-NssqErs7ZABt3uiE3Kl:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/75eba0849bb4f845ce11ac8b92b1d2662e541b91/packages/geoview-core/src/core/utils/config/config-validation.ts#L481)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add more comment for what we do if not geocore so we understand why geocore is not treated the same way
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 537 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-NssEaGP1y_xHx6Tz3oI:-NssqO1w16VumvdMnPwI:b-gfhmfh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/75eba0849bb4f845ce11ac8b92b1d2662e541b91/packages/geoview-core/src/core/utils/config/config-validation.ts#L537)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

The way the config is made is a ***Map Features*** section that represent a map which contains a ***list of GeoView layers*** composed of a tree of sublayers recursively defined in a ***list of layer config*** as group/layer entries
</blockquote></details>

The point of the renaming is to clarify exactly that a MapConfigLayer is either a GeoViewLayerConfig OR a GeoCore Config and GeoCore doesn't have any 'listOfGeoviewLayerConfig' at all.
___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 690 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-NssTvK74Z5U2n-0xczY:-NssqoOiAkC_4FO1d_yl:b-816h6l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/75eba0849bb4f845ce11ac8b92b1d2662e541b91/packages/geoview-core/src/core/utils/config/config-validation.ts#L690)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Same.
___
*[`packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts` line 70 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-Nsrjyc24pZqeFc-eBRI:-NssqvRu1EymEwKUrNRf:b10u9u9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0700863cd52815d1c7908ea119531f7420c1df5a/packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts#L70)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is it not supposed to be ...response.rcs[lang[.layers.length?
</blockquote></details>

No, it's correct like this. Double verified with the service with Johann on the phone.
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 294 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-NssWsCx8p3gKv7dAqDy:-NsstH9BB7FbHl61CgJe:blmkxf5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/75eba0849bb4f845ce11ac8b92b1d2662e541b91/packages/geoview-core/src/geo/layer/layer.ts#L294)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Do we still want to use a promise instead of async/await in our code. I ask because we have begun a transformation of the old promise implementation to async/await and this section of code seems to be a good candidate for async/await.
</blockquote></details>

The reason for the Promise.allSettled here is because of synch issues with the 'setMapOrderedLayerInfo' which happens below and the other setMapOrderedLayerInfos that happen in parallel via the ADD_LAYER events ping/pong'ing in the universe, making the setMapOrdered below fail if we don't stage the promises. If we don't stage the promises, sometimes I have 4 layers loaded in 'Details' and sometimes I have 3 layers loaded in Details - for example.
___
*[`packages/geoview-core/src/geo/layer/other/geocore.ts` line 52 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-NsrlFyr4Tj6sHjbkoHi:-NssroTOE6wVSnl6wjk_:bwpgyw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/86dd5c58987d59c0ea0a40180f744335111d2e2e/packages/geoview-core/src/geo/layer/other/geocore.ts#L52)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we still need dead code?
</blockquote></details>

I wasn't sure so left it there. Since, I've removed it completely as it was roughly confirmed as being now obsolete with Johann on the phone.
___
*[`packages/geoview-core/src/geo/layer/other/geocore.ts` line 75 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-NsrlMOq1JAbU7qDZiau:-Nsss-Ot8Q7ohPFeNAPL:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/86dd5c58987d59c0ea0a40180f744335111d2e2e/packages/geoview-core/src/geo/layer/other/geocore.ts#L75)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we need dead code? To test we should set initial states like layer name and visibility and see if it is injected properly. Technically it is not geocore who does this. It is the proper layer type so we should be able to delete all this.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 443 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-Nsrlt4t7JPGmk_B47H7:-NsssAOV3t6nSfyvV14f:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/86dd5c58987d59c0ea0a40180f744335111d2e2e/packages/geoview-core/src/geo/map/map-schema-types.ts#L443)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

It doesn't harm if we rename TypeListOfLayerEntryConfig to TypeLayerEntryConfig[]
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 497 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-Nsrm43jE0QxX9iieKKn:-Nssu72--hQve1GtIKWf:birhbgk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/86dd5c58987d59c0ea0a40180f744335111d2e2e/packages/geoview-core/src/geo/map/map-schema-types.ts#L497)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

On type we should have the initial setting as well. This is to override the information from service.
I think it is working with other type of layer. Now having geocore not a layer type anymore, we should be able to overrides. 

For this we will need a little trick because when we create the config the setting are set at the root level and in our config it will take it from the layerID. There is refactor to do to make this work for all layer type. Global setting should be cascade to child of the root layer.
</blockquote></details>

I've added details in the TODO
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 173 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917#-NsrmuSjAuplzVhewUik:-Nsst-_Z9l3CHUwmUTdS:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/86dd5c58987d59c0ea0a40180f744335111d2e2e/packages/geoview-core/src/geo/map/map-viewer.ts#L173)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should not have a listener on layer added on map viewer. The viewer does not care about layers status. As soon as the init state is done (store, basemap, plugins, ....) We should remove the spinner. All layers boxes should be there with their status (loading, error, loaded). Their status change but the viewer does not care. We show it in legend and emit an event for the outside world for each status.

Please add a TODO as it is main part of the refactor for splitting validation/layer and make the viewer ready.
</blockquote></details>

Done.

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 1 of 10 files at r2, 1 of 5 files at r4, 3 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917)* status: all files reviewed, 12 unresolved discussions (waiting on @jolevesq and @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 40 of 42 files at r5, 3 of 3 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1917)* status: all files reviewed, 4 unresolved discussions (waiting on @ychoquet)

**Pull request merged**
