### PR TITLE
feature(time-slider): added animation functionality to time slider

### LINKED ISSUE #1451: [FEATURE] Time slider button to cycle through single handle scale
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Geoview team

### User Story

Add a "play", "backward", "forward" and "lock" buttons to cycle through the items in a single handle and dual handles time slider

https://github.com/fgpv-vpgf/contributed-plugins/blob/master/range-slider/src/slider-bar.ts

__ we need tokeep in mind we will need the "reverse" button later and it will affect the functionalities in this issue.

### Implementation UI

[_No response_](https://jolevesq.github.io/contributed-plugins/range-slider/samples/range-slider-index.html?sample=1)

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #1451

# Description

Added forward, back, play/pause, lock, and reverse buttons to time slider.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested on package-time-slider.html with three layers.

https://damonu2.github.io/geoview/package-time-slider.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1484)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
I think lock icon should be reverse state

> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1484#-:-NipQtM12uB8Z_cEKiak:bxgtzj7)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @manoharnrcan)

**Review by jolevesq — COMMENTED** [review]
Same for reverse, the purple triangle should point in the direction of the handles move

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1484#-:-NipRB0MB3gT3y3zW4GE:b-kx63d)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @manoharnrcan)

**Review by jolevesq — COMMENTED** [review]
- Can you add tooltip to button?
- Reverse seems to behave weird when handle is lock.  If I put an interval , lock handle and step forward and back none of the handles seems locked and the interval change
- Can you add a delay selector for animation.... river and ice seems slow and do not animate

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1484#-:-NipRSW740z849c4yb2o:bcvbxp9)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @manoharnrcan)

**Review by ychoquet — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1484)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @manoharnrcan)

**Review by DamonU2 — COMMENTED** [review]
All done!

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1484#-:-NjKP_XYAes-bnHVw_89:b-cw6y1x)* status: 1 of 7 files reviewed, all discussions resolved (waiting on @jolevesq, @manoharnrcan, and @ychoquet)

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1484)* status: 4 of 7 files reviewed, 2 unresolved discussions (waiting on @jolevesq, @manoharnrcan, and @ychoquet)

___
*[`packages/geoview-core/src/core/components/time-slider/time-slider.tsx` line 234 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1484#-NjNBr5z5BIkpoWAcsyA:-NjO8BAk-Wj2fA5eh5LQ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d1b874675f74f655645084ab4ac7f2d8ac8eb847/packages/geoview-core/src/core/components/time-slider/time-slider.tsx#L234)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add a TODO to remove all api call from within the component. We should have the filter attribute in the store layer object and have a function to set it from the component. Like in data table when layer is filtered... I am also wondering if the filter should be in layer store. not on component so we know there is an active filter and append to it.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/time-slider/time-slider-api.tsx` line 34 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1484#-NjNAuTL3MCAph-BAKS-:-NjO8B_j79RCWbKTC6Qd:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d1b874675f74f655645084ab4ac7f2d8ac8eb847/packages/geoview-core/src/core/components/time-slider/time-slider-api.tsx#L34)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add a TODO and a create a new issue. This value should came from the store. The api file may be removed and the component is listening to the store array.
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 6 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1484)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @manoharnrcan)

**Review by manoharnrcan — COMMENTED** [review]
QA Acceptance Criteria :

 The buttons should operate as follows (left to right):  
Lock: Locks and unlocks the left or right handle of the slider (left for regular, right for reversed)  
Left Arrow: Move one increment left - if the lock is engaged only the non-locked handle should move  
Play: Cycle through increments - as right arrow if regular, left if reversed  
Right Arrow: One increment right  - if the lock is engaged only the non-locked handle should move  
Two Arrows: switch animation direction/change locked handle  
Animation time delay: change delay between increments when play is pressed.

Notes: Animation direction tooltip to be changed to  - "Change animation direction"

QA Passed

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1484#-:-NjQ1LElDE92pIQAmbJI:b-s39j6e)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
