### PR TITLE
implementing navbar custom buttons

### LINKED ISSUE #2180: [Refactor] <refactor Navbar panel>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When user open this page https://canadian-geospatial-platform.github.io/geoview/public/add-panels.html
and add `Navbar` panels it shows panel with width of `2px`. Which is wrong behaviour.

### Expected Behavior

We need to refactor this to open panel as modal because opening of panel from right side of map is not good UI.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

This PR refactors Navbar component. It does the following;
* Adds ability to add custom button (with an onClick action).
* Adds custom buttons that open up a panel.

Fixes #2180 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://cphelefu.github.io/geoview/add-panels.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362)* status: all files reviewed, 13 unresolved discussions (waiting on @cphelefu and @kaminderpal)

___
*[`packages/geoview-core/public/templates/add-panels.html` line 144 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YPZheAom8eAfAJ5Yy:-O1YPZheAom8eAfAJ5Yz:b-ecinnx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/public/templates/add-panels.html#L144)):*
> ```HTML
>             const groupName = navbarButtonGroupNameInput.value;
> 
>             if(groupName === '') {
> ```

Space between if and (
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 24 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YPgZa10_KrYZgg7Nv:-O1YPgZa10_KrYZgg7Nw:bas9fki) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L24)):*
> ```XML
> };
> 
> type DefaultNavbar = 'fullScreen' | 'location' | 'home' | 'zoomIn' | 'zoomOut';
> ```

Type should be map-schema-type in api folder. If constant is needed, it should be in constant.ts
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 60 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YQN7T4Z8pwE2LOhX2:-O1YQN7T4Z8pwE2LOhX3:b-jedeox) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L60)):*
> ```XML
>   const [buttonPanelGroups, setButtonPanelGroups] = useState<NavButtonGroups>(defaultButtonGroups);
> 
>   useEffect(() => {
> ```

Add logger to useEffect
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 65 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YQGQo5wePOfZclg5I:-O1YQGQo5wePOfZclg5J:b-5uvt2o) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L65)):*
> ```XML
>       displayButtons = { ...displayButtons, fullScreen: 'fullScreen' };
>     }
>     if (navBarComponents.includes('location')) {
> ```

Blank line between if
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 68 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YQJzO8m7RJbMaKBbj:-O1YQJzO8m7RJbMaKBbk:b-5uvt2o) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L68)):*
> ```XML
>       displayButtons = { ...displayButtons, location: 'location' };
>     }
>     if (navBarComponents.includes('home')) {
> ```

Blank line between if
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 83 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YQ4MO7qC5GPityRLP:-O1YQ4MO7qC5GPityRLQ:b-bfd3on) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L83)):*
> ```XML
>       logger.logTraceUseCallback('NAV-BAR - addButtonPanel');
> 
>       const d = {
> ```

What is d for? Maybe a more meaningful name?
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 101 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YQAX-9InJyXxAaRoU:-O1YQAX-9InJyXxAaRoV:bjq2ari) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L101)):*
> ```XML
>     (sender: NavBarApi, event: NavBarRemovedEvent) => {
>       logger.logTraceUseCallback('NAV-BAR - handleRemoveButtonPanel');
>       setButtonPanelGroups((prevState) => {
> ```

Blank line between logger and function
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx` line 14 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YQyi49RFwE4g0nWDP:-O1YQyi49RFwE4g0nWDQ:b-pyvhuz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx#L14)):*
> ```XML
> 
> /**
>  * Navbar modal component
> ```

Not modal, it is popover
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx` line 16 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YR0127D9jDKtp7O-v:-O1YR0127D9jDKtp7O-w:b114lf7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx#L16)):*
> ```XML
>  * Navbar modal component
>  *
>  * @returns {JSX.Element} the export modal component
> ```

not export modal
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx` line 19 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YQhru35R0WrBu1ZE-:-O1YQhru35R0WrBu1ZE0:b-yc6cw4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx#L19)):*
> ```XML
>  */
> export default function NavbarPanelButton({ buttonPanel }: NavbarPanelButtonType): JSX.Element {
>   const theme = useTheme();
> ```

 logger.logTraceRender( at the start of component
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx` line 79 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YR4vJCWIS0HFvDsGB:-O1YR4vJCWIS0HFvDsGC:bahqkn4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx#L79)):*
> ```XML
>           <DialogTitle>{(buttonPanel.panel?.title as string) ?? ''}</DialogTitle>
>           <DialogContent dividers>
>             <Typography dangerouslySetInnerHTML={{ __html: buttonPanel?.panel?.content ?? '' }} />
> ```

For now but content can be a react component pass by props, not only sting
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar-style.ts` line 28 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YRECV86XhgPuC2qwf:-O1YRECV86XhgPuC2qwg:bvcjq1e) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar-style.ts#L28)):*
> ```XML
>     position: 'relative',
>     pointerEvents: 'auto',
>     // justifyContent: 'end',
> ```

remove dead code
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar-style.ts` line 32 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YRFl58_wmBzgPWUa3:-O1YRFl58_wmBzgPWUa4:bvcjq1e) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar-style.ts#L32)):*
> ```XML
>     padding: 5,
>     flexDirection: 'column',
>     // flexWrap: 'wrap',
> ```

remove dead code

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362)* status: all files reviewed, 13 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx` line 79 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YR4vJCWIS0HFvDsGB:-O1YVy3u8Jw1uDDqK34W:bk857te) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx#L79)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

For now but content can be a react component pass by props, not only sting
</blockquote></details>

Also we can use `HtmlToReact` npm package instead of `dangerouslySetInnerHTML`

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 24 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YPgZa10_KrYZgg7Nv:-O1akS8l2V94_c_Litnf:b-nem5je) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L24)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Type should be map-schema-type in api folder. If constant is needed, it should be in constant.ts
</blockquote></details>

This type is just specific to this file; it can even just be converted to a string. Just added it to reduce errors of wrong key.

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362)* status: all files reviewed, 13 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/add-panels.html` line 144 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YPZheAom8eAfAJ5Yy:-O1ajvPN4YAxtRS-CL3b:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/public/templates/add-panels.html#L144)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Space between if and (
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 60 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YQN7T4Z8pwE2LOhX2:-O1alCJV9MYLkVUEGbT4:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L60)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add logger to useEffect
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 68 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YQJzO8m7RJbMaKBbj:-O1alKlR8ikXh_RtBybz:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L68)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank line between if
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 83 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YQ4MO7qC5GPityRLP:-O1alWb2DLoRiiFhJG2f:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L83)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

What is d for? Maybe a more meaningful name?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 101 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YQAX-9InJyXxAaRoU:-O1aldg91aSY3DAYA0h9:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L101)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank line between logger and function
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx` line 14 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YQyi49RFwE4g0nWDP:-O1aloOQ2PLe9-Tc-0p2:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Not modal, it is popover
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx` line 16 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YR0127D9jDKtp7O-v:-O1alqVg-KDhevNjJJJ8:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx#L16)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

not export modal
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx` line 19 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YQhru35R0WrBu1ZE-:-O1amIaA6OQs9EoqFpxa:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx#L19)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

logger.logTraceRender( at the start of component
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar-style.ts` line 28 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YRECV86XhgPuC2qwf:-O1amc3l7zzY8AKbPDxG:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar-style.ts#L28)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

remove dead code
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar-style.ts` line 32 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YRFl58_wmBzgPWUa3:-O1amd8UB5xe54PnYaYj:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar-style.ts#L32)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

remove dead code
</blockquote></details>

Done.

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362)* status: 2 of 6 files reviewed, 13 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx` line 79 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YR4vJCWIS0HFvDsGB:-O1aojoY7eOa20Oe0WK_:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx#L79)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

Also we can use `HtmlToReact` npm package instead of `dangerouslySetInnerHTML`
</blockquote></details>

Done.

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362)* status: 2 of 8 files reviewed, 13 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 65 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YQGQo5wePOfZclg5I:-O1b4NhOB0SGcFHgTQEL:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L65)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank line between if
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362)* status: all files reviewed, 2 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 24 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YPgZa10_KrYZgg7Nv:-O1b6ufI6QGeIwrDu1NQ:bymthxb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L24)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

This type is just specific to this file; it can even just be converted to a string. Just added it to reduce errors of wrong key.
</blockquote></details>

But component should reuse the type made for them by the map-schema-type. Because at the end, map-schema type is the one who validates if the component is good or not. The map-schema-Type must be aligned with the component. The zoom always come with zoomIn/zoomOut in one group

```
/** Valid values for the navBar array. */
export type TypeValidNavBarProps = 'zoom' | 'fullscreen' | 'home' | 'location';
```
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx` line 1 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1b6ILH9ynEAgVYnTXT:-O1b6ILH9ynEAgVYnTXU:b-hntpjm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/19f8dbfa43056d59f5d6bed9eb588bc8f03c2edd/packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx#L1)):*
> ```XML
> /* eslint-disable @typescript-eslint/no-explicit-any */
> ```

No global eslint, we need to use them were needed

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 24 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1YPgZa10_KrYZgg7Nv:-O1bFEiz5O9TUOndjJW1:b-9d6xwf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cb364aff75488747283940b547fef6a369ee592/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L24)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

But component should reuse the type made for them by the map-schema-type. Because at the end, map-schema type is the one who validates if the component is good or not. The map-schema-Type must be aligned with the component. The zoom always come with zoomIn/zoomOut in one group

```
/** Valid values for the navBar array. */
export type TypeValidNavBarProps = 'zoom' | 'fullscreen' | 'home' | 'location';
```
</blockquote></details>

Done. Removed that code.
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx` line 1 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362#-O1b6ILH9ynEAgVYnTXT:-O1bFDQ4DxWOo_8mRvYg:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/19f8dbfa43056d59f5d6bed9eb588bc8f03c2edd/packages/geoview-core/src/core/components/nav-bar/nav-bar-panel-button.tsx#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

No global eslint, we need to use them were needed
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 4 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2362)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
