### PR TITLE
Move config validation to layerConfig object

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

This PR is part of #528
[Use config-validation for auto completing all kinds of GeoView layers](https://github.com/Canadian-Geospatial-Platform/geoview/issues/528).

Fixes # Part of issue 528

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using Chrome Devtools and templates from [Type of layers](https://ychoquet.github.io/GeoView/type-of-layers.html).

__Deploy URL:__ https://ychoquet.github.io/GeoView/type-of-layers.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1673)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 23 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1673)* status: 23 of 25 files reviewed, 2 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 205 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1673#-Nntm7yrDzrVBjplJ88u:-Nntm7yrDzrVBjplJ88v:b-zd1ud4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/38887b8ad6b23b2ef98534d00487de69e044aa5b/packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts#L205)):*
> ```XML
>       }
> 
>       // ! The following line cause an error now.
> ```

Can you add a TODO soo we can fix later.... maybe an issue as well
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 608 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1673#-Nntn5tQD1Qe-vypXs2X:-Nntn5tQD1Qe-vypXs2Y:ba4fe1e) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/38887b8ad6b23b2ef98534d00487de69e044aa5b/packages/geoview-core/src/geo/map/map-schema-types.ts#L608)):*
> ```XML
>  * Base type used to define a GeoView layer to display on the map.
>  */
> export class BaseLayerProperties {
> ```

Why is it a class now? Should our type ts file only have type inside? Should it be separate in their own helpers class?

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1673)* status: 22 of 25 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 205 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1673#-Nntm7yrDzrVBjplJ88u:-Nnttphm4FwSFqwCMQLt:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/38887b8ad6b23b2ef98534d00487de69e044aa5b/packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts#L205)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add a TODO soo we can fix later.... maybe an issue as well
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 608 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1673#-Nntn5tQD1Qe-vypXs2X:-Nntu1734tacS93o2lbU:b-gidamm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/38887b8ad6b23b2ef98534d00487de69e044aa5b/packages/geoview-core/src/geo/map/map-schema-types.ts#L608)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why is it a class now? Should our type ts file only have type inside? Should it be separate in their own helpers class?
</blockquote></details>

Normally, we code only one classe per ts file. However, I wanted to keep all classes related to the schema in the same file. If you prefere, we can keep the "single class per ts  file" constraint and separate the classes in a schema helper folder.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1673)* status: 23 of 25 files reviewed, all discussions resolved

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1673)* status: 24 of 25 files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1673)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1673)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
