### PR TITLE
[FIX] Fixing indexing issues inside Details core component.. waiting for store layer arrays improvements.

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

Fixes an indexing issue with the Details layers list.
Temporary fix until further work is done in the store concerning the arrays.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Hosted here: https://alex-nrcan.github.io/geoview/raw-feature-info.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 5 of 20 files at r3, 7 of 20 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739)* status: 9 of 31 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts` line 24 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-Npflmvd5bx9oB6JPJHH:-Npflmvd5bx9oB6JPJHI:b-ts1esz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts#L24)):*
> ```XML
> 
>   /**
>    * Shortcut to get the Geochart state for a given map id
> ```

Maybe a wrong description
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts` line 54 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfmT4ABiWKm5yAatzn:-NpfmT4ABiWKm5yAatzo:bray4hc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts#L54)):*
> ```XML
> 
>     const featureInfoState = this.getFeatureInfoState(mapId);
>     const { uiState } = getGeoViewStore(mapId).getState();
> ```

Here, we should use the getUIState from ui processor?
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts` line 83 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfmmJ8-Wrw1soqT18Z:-NpfmmJ8-Wrw1soqT18_:b-81k5qp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts#L83)):*
> ```XML
>       if (atLeastOneFeature) {
>         // If the current tab is not 'details' nor 'geochart', switch to details
>         if (!['details', 'geochart'].includes(uiState.activeFooterBarTabId)) uiState.actions.setActiveFooterBarTab('details');
> ```

Should we not use the uiprocessor static method? Or because it is event processor to event processor we let go...

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 20 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739)* status: 10 of 31 files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 265 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfohOJCD0g6lZq6kpN:-NpfohOJCD0g6lZq6kpO:bir8udk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L265)):*
> ```XML
>    * @returns {TypeMapFeaturesConfig | undefined} the map config or undefined if there is no config for this map id
>    */
>   public static getGeoViewMapConfig(mapId: string): TypeMapFeaturesConfig | undefined {
> ```

Why put public?

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 11 of 20 files at r3, 18 of 20 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739)* status: all files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts` line 24 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-Npflmvd5bx9oB6JPJHH:-NpfqsE2BL199i8_bzFW:bhy9q7g) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts#L24)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Maybe a wrong description
</blockquote></details>

Will fix
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts` line 54 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfmT4ABiWKm5yAatzn:-NpfpgGEBkN8CaMf2tgu:bp4ttcj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts#L54)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Here, we should use the getUIState from ui processor?
</blockquote></details>

Oh, yes, that's true, getUIState is public now. Initially, I had those set to protected level, to make sure only the processors could use their states and leaving the external calls between processors using getGeoViewStore() (to expose the inter-processor calls).
I can point to it and we review later.. what's the best approach (protected or public level).
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts` line 83 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfmmJ8-Wrw1soqT18Z:-NpfqC4j4jQmhmY3daBJ:b4gtw4d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts#L83)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we not use the uiprocessor static method? Or because it is event processor to event processor we let go...
</blockquote></details>

Here I'm just using the state. I guess if getUIState would have remained protected I'd have had no choice to use processor yes (linked to above comment).
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 265 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfohOJCD0g6lZq6kpN:-NpfqcxzDKwKzbPHBEks:b-yu2w4a) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L265)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why put public?
</blockquote></details>

Because it was public. And I didn't like it either lol. But it was public, because it's used in map-viewer.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts` line 19 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfmhLB3oLKrPHDpq8p:-NpfmhLCD69JnAzFrPh-:bwlt0ln) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d6f394423679d200ebdd027bc444232cdb0503db/packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts#L19)):*
> ```XML
>    * Override the initialization process to wire subscriptions and return them so they can be destroyed later.
>    */
>   protected onInitialize(store: GeoviewStoreType) {
> ```

Missing the return type, will add.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts` line 13 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfnB-1EKDJb--LytTX:-NpfnB-1EKDJb--LytTY:b-l1gvf2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d6f394423679d200ebdd027bc444232cdb0503db/packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts#L13)):*
> ```XML
>   //! Some action does state modifications AND map actions.
>   //! ALWAYS use map event processor when an action modify store and IS NOT trap by map state event handler
> ```

Looks like I dropped the getActiveFooterBarTab by accident. Still builds though, but I'll add back.
___
*[`packages/geoview-geochart/src/geochart-panel.tsx` line 90 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfmtEG9oSuCwkWjLrO:-NpfmtEG9oSuCwkWjLrP:b-sagnmi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d6f394423679d200ebdd027bc444232cdb0503db/packages/geoview-geochart/src/geochart-panel.tsx#L90)):*
> ```XML
>   const memoLayersList = useMemo(() => {
>     // Log
>     logger.logTraceUseEffect('GEOCHART-PANEL - ArrayOfLayerData', arrayOfLayerData);
> ```

Wrong trace, will fix.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 10 of 20 files at r3, 9 of 20 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739)* status: all files reviewed, 14 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/core/components/common/layer-list.tsx` line 42 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-Npfp9quEm6zdp4uPKcV:-Npfp9quEm6zdp4uPKcW:b-4miq41) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/90eb19105d639001b1c78a9ea91e20710d565cc0/packages/geoview-core/src/core/components/common/layer-list.tsx#L42)):*
> ```XML
>   const sxClasses = getSxClasses(theme);
> 
>   const renderQueryStatusBackground = () => {
> ```

Can we have a TODO with a a basic issue just to say to standardize css for item loading - error
___
*[`packages/geoview-core/src/core/components/common/layer-list-style.ts` line 72 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfpRLW4KPONGltN2LQ:-NpfpRLW4KPONGltN2LR:bppl2mf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/90eb19105d639001b1c78a9ea91e20710d565cc0/packages/geoview-core/src/core/components/common/layer-list-style.ts#L72)):*
> ```XML
>   borderWithIndex: `2px solid ${theme.palette.geoViewColor.primary.main}`,
>   borderNone: 'none',
>   backgroundProcessing: 'bisque',
> ```

Just to make sure we do not introduce other color, reuse the theme.palette with red and yellow (error and warning 
___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 129 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfuFrtBo3-wAHJ90jw:-NpfuFrtBo3-wAHJ90jx:b-ww3auo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/ui/tabs/tabs.tsx#L129)):*
> ```XML
> 
>     // no tab field which will be used to collapse the footer panel.
>     const noTab = { type: 'item', item: { value: '', children: t('footerTabsContainer.noTab') } };
> ```

Weird.... should be footerBar
___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 181 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfuLJyAY8U7XGuITtd:-NpfuLJyAY8U7XGuITte:b-p7fppp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/ui/tabs/tabs.tsx#L181)):*
> ```XML
>             <Box sx={sxClasses.mobileDropdown}>
>               <Select
>                 labelId="footerTabsDropdownLabel"
> ```

footerBar
___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 183 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfuMO609xUNt6t_nMc:-NpfuMO609xUNt6t_nMd:b-p7fppp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/ui/tabs/tabs.tsx#L183)):*
> ```XML
>                 labelId="footerTabsDropdownLabel"
>                 formControlProps={{ size: 'small' }}
>                 id="footerTabsDropdown"
> ```

footerBar
___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 185 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfuNMVCRFxBSrQfsk5:-NpfuNMVCRFxBSrQfsk6:bgt1fd8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/ui/tabs/tabs.tsx#L185)):*
> ```XML
>                 id="footerTabsDropdown"
>                 fullWidth
>                 inputLabel={{ id: 'footerTabsDropdownLabel' }}
> ```

footerBarfooterTabs
___
*[`packages/geoview-geochart/src/geochart-panel.tsx` line 134 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfufGD5iXXnRBckLKh:-NpfufGD5iXXnRBckLKi:b-iss4l5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/90eb19105d639001b1c78a9ea91e20710d565cc0/packages/geoview-geochart/src/geochart-panel.tsx#L134)):*
> ```XML
>    * A useEffect is necessary in order to keep this component pure and be able to set the selected layer path elsewhere than in this component.
>    */
>   useEffect(() => {
> ```

This is the same useEffect as details... may see if we should do a customHook to be reuse an other components

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739)* status: all files reviewed, 14 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts` line 54 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfmT4ABiWKm5yAatzn:-Npfv7Wq5LioqeeVFt75:b60n2qu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts#L54)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Oh, yes, that's true, getUIState is public now. Initially, I had those set to protected level, to make sure only the processors could use their states and leaving the external calls between processors using getGeoViewStore() (to expose the inter-processor calls).
I can point to it and we review later.. what's the best approach (protected or public level).
</blockquote></details>

I think each event processor expose its on state and other processor used this hook to access the state. It can be protected if we can restrict to whoe state access to only processor.

The way it is now, there is no public access to state from outside

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739)* status: all files reviewed, 14 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts` line 83 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfmmJ8-Wrw1soqT18Z:-NpfvZtj310jjL0S1Syr:b-4b39a0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts#L83)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Here I'm just using the state. I guess if getUIState would have remained protected I'd have had no choice to use processor yes (linked to above comment).
</blockquote></details>

Maybe we should go back to protected

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739)* status: 19 of 31 files reviewed, 13 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts` line 54 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfmT4ABiWKm5yAatzn:-Npg1bzc4BqTEzQhnkHE:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts#L54)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think each event processor expose its on state and other processor used this hook to access the state. It can be protected if we can restrict to whoe state access to only processor.

The way it is now, there is no public access to state from outside
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts` line 83 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfmmJ8-Wrw1soqT18Z:-Npg1iiV9A2ohvzCIPrc:b-8kd1zs) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts#L83)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Maybe we should go back to protected
</blockquote></details>

going back to protected then ;)
___
*[`packages/geoview-core/src/core/components/common/layer-list.tsx` line 42 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-Npfp9quEm6zdp4uPKcV:-Npfw9BF8O8LYMr_a2NL:b-j1vdsl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/90eb19105d639001b1c78a9ea91e20710d565cc0/packages/geoview-core/src/core/components/common/layer-list.tsx#L42)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we have a TODO with a a basic issue just to say to standardize css for item loading - error
</blockquote></details>

TODO added
___
*[`packages/geoview-core/src/core/components/common/layer-list-style.ts` line 72 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfpRLW4KPONGltN2LQ:-NpfyKOA5NSDBQ0opcv5:b32w1t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/90eb19105d639001b1c78a9ea91e20710d565cc0/packages/geoview-core/src/core/components/common/layer-list-style.ts#L72)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Just to make sure we do not introduce other color, reuse the theme.palette with red and yellow (error and warning
</blockquote></details>

Ok
___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 129 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfuFrtBo3-wAHJ90jw:-Npg19F43xhvTkzqxGVQ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/ui/tabs/tabs.tsx#L129)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Weird.... should be footerBar
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 181 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfuLJyAY8U7XGuITtd:-Npg19s08fsmL-lXRGcJ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/ui/tabs/tabs.tsx#L181)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

footerBar
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 183 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfuMO609xUNt6t_nMc:-Npg2KMk4f1VdL9BLTuf:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/ui/tabs/tabs.tsx#L183)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

footerBar
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 185 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfuNMVCRFxBSrQfsk5:-Npg1APQ-fmpDsikkkY8:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04df95ba6d9b43ed44ab0ff0ebbf17885f878870/packages/geoview-core/src/ui/tabs/tabs.tsx#L185)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

footerBarfooterTabs
</blockquote></details>

Done.
___
*[`packages/geoview-geochart/src/geochart-panel.tsx` line 134 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739#-NpfufGD5iXXnRBckLKh:-Npg1IY4AUN5I_hrlSm4:bc9t8kd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/90eb19105d639001b1c78a9ea91e20710d565cc0/packages/geoview-geochart/src/geochart-panel.tsx#L134)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This is the same useEffect as details... may see if we should do a customHook to be reuse an other components
</blockquote></details>

Good idea, I'll add TODO for now

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 20 files at r4, 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1739)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Pull request merged**
