### PR TITLE
fix(stepper): better WMS url parsing

### LINKED ISSUE #696: WMS layer URL error
https://geo.weather.gc.ca/geomet?lang=en&service=WMS&request=GetCapabilities&layers=REPS.DIAG.6_PRMM.ERGE10

This url should be abler to load but the layer stepper says it is not valid

### PR DESCRIPTION
**Pull request by dayc-mapdev**
Closes #696

- - -
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/708)

### CODE REVIEW

**Review by dayc-mapdev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/708)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-layers-panel/src/layer-stepper.tsx` line 74 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/708#-NIXn5f0Bh5A_XXBPDhs:-NIXn5f0Bh5A_XXBPDht:b-55tz5w) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/621a376010a2e27bf5e869f7db38c05a5aef9c37/packages/geoview-layers-panel/src/layer-stepper.tsx#L74)):*
> ```XML
>   useEffect(() => {
>     api.event.on(
>       api.eventNames.SNACKBAR.EVENT_SNACKBAR_OPEN,
> ```

there was no other way to detect the timeout, maybe error events might be good to add

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/708)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dayc-mapdev and @ychoquet)

___
*[`packages/geoview-layers-panel/src/layer-stepper.tsx` line 403 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/708#-NIXpsjU6F5Ynr595vZG:-NIXpsjVDbrzyKd-8Vfj:b74cejq) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/621a376010a2e27bf5e869f7db38c05a5aef9c37/packages/geoview-layers-panel/src/layer-stepper.tsx#L403)):*
> ```XML
>     } else if (layerURL.indexOf('/') === -1 && layerURL.replaceAll('-', '').length === 32) {
>       setLayerType(GEOCORE);
>     } else if (layerURL.toUpperCase().indexOf('WMS') !== -1) {
> ```

I can't load https://geo.weather.gc.ca/geomet. Works great when I set the service=WMS. I think if we can't scrape the service from the url, we whould use the one provided by the user without validation.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/708)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dayc-mapdev and @ychoquet)

___
*[`packages/geoview-layers-panel/src/layer-stepper.tsx` line 403 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/708#-NIXpsjU6F5Ynr595vZG:-NIXqLbZBn6KssF9vKHV:b6j2xpe) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/621a376010a2e27bf5e869f7db38c05a5aef9c37/packages/geoview-layers-panel/src/layer-stepper.tsx#L403)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I can't load https://geo.weather.gc.ca/geomet. Works great when I set the service=WMS. I think if we can't scrape the service from the url, we whould use the one provided by the user without validation.
</blockquote></details>

Even with services = WMS it won't work. Layers param needs to be there. It is better to have but it should work without

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/708)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @dayc-mapdev and @ychoquet)

___
*[`packages/geoview-layers-panel/src/layer-stepper.tsx` line 403 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/708#-NIXpsjU6F5Ynr595vZG:-NIXv6iuC16acBsGZMRg:b4ehi0c) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/621a376010a2e27bf5e869f7db38c05a5aef9c37/packages/geoview-layers-panel/src/layer-stepper.tsx#L403)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Even with services = WMS it won't work. Layers param needs to be there. It is better to have but it should work without
</blockquote></details>

When I add many layers from the WMS service I get:
https://canadian-geospatial-platform.github.io/geoview/696-wms-url-error/[object%20Object]service=WMS&version=1.3.0&request=GetLegendGraphic&FORMAT=image/png&layer=SRTM30-Contour
https://canadian-geospatial-platform.github.io/geoview/696-wms-url-error/[object%20Object]service=WMS&version=1.3.0&request=GetLegendGraphic&FORMAT=image/png&layer=OSM-WMS-no-labels

Looks like a parsing issue

**Review by dayc-mapdev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/708)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-layers-panel/src/layer-stepper.tsx` line 403 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/708#-NIXpsjU6F5Ynr595vZG:-NIcTfaeA7puYxeeedWc:b-gz7d6c) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/621a376010a2e27bf5e869f7db38c05a5aef9c37/packages/geoview-layers-panel/src/layer-stepper.tsx#L403)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

When I add many layers from the WMS service I get:
https://canadian-geospatial-platform.github.io/geoview/696-wms-url-error/[object%20Object]service=WMS&version=1.3.0&request=GetLegendGraphic&FORMAT=image/png&layer=SRTM30-Contour
https://canadian-geospatial-platform.github.io/geoview/696-wms-url-error/[object%20Object]service=WMS&version=1.3.0&request=GetLegendGraphic&FORMAT=image/png&layer=OSM-WMS-no-labels

Looks like a parsing issue
</blockquote></details>

https://geo.weather.gc.ca/geome will work, but I can't support adding multiple WMS layers at a time, see https://github.com/Canadian-Geospatial-Platform/geoview/issues/714

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/708)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Pull request merged**
