### PR TITLE
1217 Add Export button with csv and geojson download option

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Add Export button at right top corner in toolbar.

Fixes # ([1217](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1217))

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/raw-data-table.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1229)

### CODE REVIEW

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1229)* status: all files reviewed, 3 unresolved discussions (waiting on @cphelefu and @kaminderpal)

___
*[`packages/geoview-core/src/core/components/data-table/data-table-api.ts` line 99 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1229#-Naqexyi5gVMX6xiB9YB:-NaqexyjDJq6ruGVBRDo:b-r4njdd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6bae34b45be213141b568b80d5acb0c7dd3dfece/packages/geoview-core/src/core/components/data-table/data-table-api.ts#L99)):*
> ```XML
>    * Create a data table rows
>    *
>    * @param {TypeArrayOfFeatureInfoEntries} arrayOfFeatureInfoEntries the properties of the data table to be created
> ```

Add projectionConfig as a @param
___
*[`packages/geoview-core/src/core/components/data-table/json-export-button.tsx` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1229#-NaqiDRFCJLVMgwXTFLG:-NaqiDRFCJLVMgwXTFLH:b-xsefwf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6bae34b45be213141b568b80d5acb0c7dd3dfece/packages/geoview-core/src/core/components/data-table/json-export-button.tsx#L3)):*
> ```XML
> import React from 'react';
> import { useTranslation } from 'react-i18next';
> import { MenuItem } from '../../../ui';
> ```

Does '@/ui' work here?
___
*[`packages/geoview-core/src/core/components/data-table/json-export-button.tsx` line 13 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1229#-NaqimrCD-D-J6hPRUIH:-NaqimrCD-D-J6hPRUII:bsp9nuw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6bae34b45be213141b568b80d5acb0c7dd3dfece/packages/geoview-core/src/core/components/data-table/json-export-button.tsx#L13)):*
> ```XML
> /**
>  * Custom  GeoJson export button which will help to download data table data in geojson format.
>  * @param {Features} features list of rows to be displayed in data table
> ```

{Features[]}

**Review by DamonU2 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1229)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Review by cphelefu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1229)* status: all files reviewed, 1 unresolved discussion (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/data-table/data-table-api.ts` line 72 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1229#-NarXSJ9DKKpXzTIZD9i:-NarXSJ9DKKpXzTIZD9j:bj7r8yw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c3eee75bd37931b4c0b0b972b638c3ac78dc98fe/packages/geoview-core/src/core/components/data-table/data-table-api.ts#L72)):*
> ```XML
>    *
>    */
>   buildGeometry = (geometry: Geometry, projectionConfig: Projection) => {
> ```

This method looks like it can be reusable and its not really dataTable specific. Is this the best place for this method?

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1229)* status: all files reviewed, 1 unresolved discussion (waiting on @cphelefu)

___
*[`packages/geoview-core/src/core/components/data-table/data-table-api.ts` line 72 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1229#-NarXSJ9DKKpXzTIZD9i:-NarZU7O8AM9HqNGWshK:bfq1m8s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c3eee75bd37931b4c0b0b972b638c3ac78dc98fe/packages/geoview-core/src/core/components/data-table/data-table-api.ts#L72)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

This method looks like it can be reusable and its not really dataTable specific. Is this the best place for this method?
</blockquote></details>

At the moment we havnt used this function anywhere else, so i thought it would be ideal to keep it inside api class.

**Review by DamonU2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1229)* status: all files reviewed, 1 unresolved discussion (waiting on @cphelefu)

**Pull request merged**
