### PR TITLE
[REFACTOR] Details-Panel reusing the Layout component

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

As GeoChart-panel and TimeSlider-panel were using Layout common component, we've decided to use Layout in Details-panel too. A TODO was added for Datatable-panel to reuse Layout as well, when other parallel work, happening at the time of writing, is done on that component.

Also now showing a 'No layers visible' panel in the blank section on the left when no layers are listed.

Update: The 'No layers visible' is now clickable to show details.
Update: Typography component is now 'useRefable' (for future).
Update: TimeSlider enhancements to update the states and show message when no more layers in the list
Update: Legend UI now displays an instruction message when no layers are visible on the map
Update: Guide component now reusing Layout common component
Update: Improvements to the UI when Layout is used on mobile mode
Update: Got rid of old Geochart config files
Update: Refactored some zoomToExtent to add asynchronicity and now showing a click marker on zoom in Details panel
Update: Refactored TimeSlider to use the visibleLayers generic store instead of a custom TimeSlider visible layers store

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Hosted here as of Feb. 13th 11h40: https://alex-nrcan.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 374 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780#-NqSVhiV9VU_DkiMbWSB:-NqSVhiV9VU_DkiMbWSC:bw7yw3u) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9becd4e69c365ee208c21c33a783feab221f4bcd/packages/geoview-core/src/core/components/details/details-panel.tsx#L374)):*
> ```XML
> 
>   /**
>    * Renders the complete GeoChart Panel component
> ```

Should be details component

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 374 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780#-NqSVhiV9VU_DkiMbWSB:-NqSaYlNCQJVfizWN8FA:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9becd4e69c365ee208c21c33a783feab221f4bcd/packages/geoview-core/src/core/components/details/details-panel.tsx#L374)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should be details component
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 18 of 25 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780)* status: 25 of 29 files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/public/locales/en/translation.json` line 135 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780#-NqXV0qC7r77r5aTV0jW:-NqXV0qC7r77r5aTV0jX:b-s82hu0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6263e54d284c3d80dcee65d884410ee062484051/packages/geoview-core/public/locales/en/translation.json#L135)):*
> ```JSON
>   },
>   "timeSlider": {
>     "detailsInstructions": "Details Instructions"
> ```

We should replace by timeSliderInstruction and I think it should be in the package dictionary like geochart. Later we should have a function to take value from the overall md file
___
*[`packages/geoview-core/public/locales/fr/translation.json` line 135 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780#-NqXVhbuBJH-inABQCTX:-NqXVhbv0ZWI2TIBme7t:bm0xn15) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6263e54d284c3d80dcee65d884410ee062484051/packages/geoview-core/public/locales/fr/translation.json#L135)):*
> ```JSON
>   },
>   "timeSlider": {
>     "detailsInstructions": "Details Instructions"
> ```

Same here.... time slider
___
*[`packages/geoview-core/src/core/components/common/enlarge-button.tsx` line 9 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780#-NqXW-LW-vDqcnGETTnt:-NqXW-LW-vDqcnGETTnu:b-erzthh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ff3efdcfec250dc855125ed74d4d3190d440cb9b/packages/geoview-core/src/core/components/common/enlarge-button.tsx#L9)):*
> ```XML
> interface EnlargeButtonProps {
>   isEnlargeDataTable: boolean;
>   // TODO: Refactor this props something like 'onEnlarge'? (getting rid of legacy 'data table' stuff and align with callback namings conv?)
> ```

Good cleanup!
___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 171 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780#-NqXY8uF3S9jpwjfWiSP:-NqXY8uF3S9jpwjfWiSQ:b3tnbi3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6263e54d284c3d80dcee65d884410ee062484051/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L171)):*
> ```XML
>   return (
>     <Box sx={sxClasses.dataPanel}>
>       <ResponsiveGrid.Root sx={{ pt: 8, pb: 8 }} ref={panelTitleRef}>
> ```

Can you put a TODO to say refactor with layout like other components
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 99 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780#-NqXYmzwEPoTxjuWuQPz:-NqXYmzwEPoTxjuWuQQ-:b-wzx0s1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6263e54d284c3d80dcee65d884410ee062484051/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L99)):*
> ```XML
>         layerName: item.substring(1),
>         layerPath: item,
>         layerStatus: 'processed',
> ```

Why put processed instead of loaded? With the standard ui for layerStatus, will this become with laoding UI?
___
*[`packages/geoview-time-slider/src/time-slider-panel.tsx` line 55 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780#-NqXZXIa5Oxyc4nZLSAK:-NqXZXIa5Oxyc4nZLSAL:b-ewn0mz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6263e54d284c3d80dcee65d884410ee062484051/packages/geoview-time-slider/src/time-slider-panel.tsx#L55)):*
> ```XML
>     logger.logTraceUseCallback('TIME-SLIDER-PANEL - renderLayerList');
> 
>     const array = visibleTimeSliderLayers.map((layerPath: string) => {
> ```

There is a check for visiblelayer... there is also one in time slider event processor. Do we need both? Is it working like details and geochart are updating with visibility?
___
*[`packages/geoview-time-slider/src/time-slider-panel.tsx` line 86 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780#-NqX_1bB70Zzvp0l2qjn:-NqX_1bC0GDgdMPAvTdV:bx5plnk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6263e54d284c3d80dcee65d884410ee062484051/packages/geoview-time-slider/src/time-slider-panel.tsx#L86)):*
> ```XML
>         <Paper sx={{ padding: '2rem' }}>
>           <Typography variant="h3" gutterBottom sx={sxClasses.timeSliderInstructionsTitle}>
>             {getLocalizedMessage(mapId, 'timeSlider.detailsInstructions')}
> ```

timeSlider.instructions

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 22 of 25 files at r4, 3 of 3 files at r5, 11 of 11 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780)* status: all files reviewed, 6 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/locales/en/translation.json` line 135 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780#-NqXV0qC7r77r5aTV0jW:-NqXe0Kd4CUbPYjfJ1LS:b-9aynno) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6263e54d284c3d80dcee65d884410ee062484051/packages/geoview-core/public/locales/en/translation.json#L135)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should replace by timeSliderInstruction and I think it should be in the package dictionary like geochart. Later we should have a function to take value from the overall md file
</blockquote></details>

Done (removed from here).
___
*[`packages/geoview-core/public/locales/fr/translation.json` line 135 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780#-NqXVhbuBJH-inABQCTX:-NqXf-9m3grduzVvvfnP:b-9aynno) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6263e54d284c3d80dcee65d884410ee062484051/packages/geoview-core/public/locales/fr/translation.json#L135)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same here.... time slider
</blockquote></details>

Done (removed from here).
___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 171 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780#-NqXY8uF3S9jpwjfWiSP:-NqXfDPs6N07Uk3J8yK4:be5f3pi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6263e54d284c3d80dcee65d884410ee062484051/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L171)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put a TODO to say refactor with layout like other components
</blockquote></details>

The TODO is already there, just above. I can't put comments inside a (<JSX>) parentheses, due to a known React Production build issues with inline comments inside templates.
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 99 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780#-NqXYmzwEPoTxjuWuQPz:-NqXfihMArkC3My-k8-_:b-r08o3n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6263e54d284c3d80dcee65d884410ee062484051/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L99)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why put processed instead of loaded? With the standard ui for layerStatus, will this become with laoding UI?
</blockquote></details>

I used the same code as in TimeSlider. But I realize it was in TimeSlider that it was wrong? I'll change back to 'loaded' here and change TimeSlider to 'loaded' as well then :thumbsup: 
___
*[`packages/geoview-time-slider/src/time-slider-panel.tsx` line 55 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780#-NqXZXIa5Oxyc4nZLSAK:-NqXgY_rAhFA7OJKbFgD:bf85tyk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6263e54d284c3d80dcee65d884410ee062484051/packages/geoview-time-slider/src/time-slider-panel.tsx#L55)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There is a check for visiblelayer... there is also one in time slider event processor. Do we need both? Is it working like details and geochart are updating with visibility?
</blockquote></details>

It seems the logic was indeed different and I didn't refactor it for this PR. Details and GeoChart use the visibleLayers store state to memoize their respective layers list. TimeSlider seems to have it's own specific store for the visibility of the layers. Maybe it was done before we had the visibleLayers in the generic store?

Shall I refactor this as part of this PR and if so, which is the right way? (1) use the generic store like Details/GeoChart or (2) build a custom visible store per component basically?
___
*[`packages/geoview-time-slider/src/time-slider-panel.tsx` line 86 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780#-NqX_1bB70Zzvp0l2qjn:-NqXh4gKBEypH2FBrvzb:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6263e54d284c3d80dcee65d884410ee062484051/packages/geoview-time-slider/src/time-slider-panel.tsx#L86)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

timeSlider.instructions
</blockquote></details>

Done.

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780)* status: all files reviewed, 6 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-time-slider/src/time-slider-panel.tsx` line 55 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780#-NqXZXIa5Oxyc4nZLSAK:-NqYgv-e32jUxWWRx1Ue:b-tue5m6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6263e54d284c3d80dcee65d884410ee062484051/packages/geoview-time-slider/src/time-slider-panel.tsx#L55)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

It seems the logic was indeed different and I didn't refactor it for this PR. Details and GeoChart use the visibleLayers store state to memoize their respective layers list. TimeSlider seems to have it's own specific store for the visibility of the layers. Maybe it was done before we had the visibleLayers in the generic store?

Shall I refactor this as part of this PR and if so, which is the right way? (1) use the generic store like Details/GeoChart or (2) build a custom visible store per component basically?
</blockquote></details>

Refactored to use option (1) above.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 4 of 11 files at r6, 2 of 3 files at r8, 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780)* status: 37 of 38 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 2 of 3 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1780)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Pull request merged**
