### PR TITLE
refactor(time-slider): move slider to package

### PR DESCRIPTION
**Pull request by DamonU2**
# Description

Changes time slider to be a plugin.

Fixes # 1509
Fixes # 1530

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Checked that time slider was working on time slider page.

https://damonu2.github.io/geoview/package-time-slider.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1534)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
> Reviewed 16 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1534)* status: 16 of 19 files reviewed, all discussions resolved (waiting on @Alex-NRCan, @kaminderpal, and @ychoquet)

**Review by Alex-NRCan — APPROVED** [review]
I see the geochart class has been fixed for the store in the PR which will probably cause conflicts for me as I've done the same fix on my branch. It's good to know so that I'll resolve conflicts (if any) on my next rebase.

:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1534#-:-Nk0wvuTAA56JHDRGJXc:b7526nf)* status: 16 of 19 files reviewed, all discussions resolved (waiting on @kaminderpal and @ychoquet)

**Review by ychoquet — APPROVED** [review]
> Reviewed 3 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1534)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Review by ychoquet — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1534)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Review by jolevesq — APPROVED** [review]
> Reviewed 3 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1534)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Pull request merged**
