### PR TITLE
feat(footerTabs): implement mobile dropdown tabs #closes1707

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Implement mobile tabs as dropdown for mobile screen.

Fixes # ([1707](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1707))

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/raw-feature-info.html
# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1745)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1745)* status: all files reviewed, 4 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 134 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1745#-NpZk0a35_MPVVhb9ajD:-NpZk0a35_MPVVhb9ajE:b-45gp1q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d9aeefc97554652802f8af455db655d1bdc45d92/packages/geoview-core/src/ui/tabs/tabs.tsx#L134)):*
> ```XML
>     return tabs.map((tab) => ({
>       type: 'item',
>       item: { value: tab.value, children: t(`${tab.label}`) },
> ```

For mobile, we should have a no tab like filter for geolocator. This selection will collapse the footer tab section
___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 140 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1745#-NpZi_2YDrimKipUUsRs:-NpZi_2YDrimKipUUsRt:b-iwzkgd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d9aeefc97554652802f8af455db655d1bdc45d92/packages/geoview-core/src/ui/tabs/tabs.tsx#L140)):*
> ```XML
>   useEffect(() => {
>     // show/hide mobile dropdown when screen size change.
>     const resizeHandler = () => (document.body.offsetWidth < 768 ? setShowMobileDropdown(true) : setShowMobileDropdown(false));
> ```

Do we have breakpoints for this.... we should we have one.... 768 is width of iPadMini
___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 145 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1745#-NpZiA7PA_bPxlZLQ3zU:-NpZiA7PA_bPxlZLQ3zV:bqphycj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d9aeefc97554652802f8af455db655d1bdc45d92/packages/geoview-core/src/ui/tabs/tabs.tsx#L145)):*
> ```XML
> 
>     const handleResizeDebounced = debounce(resizeHandler, 10);
>     window.addEventListener('resize', handleResizeDebounced);
> ```

We already have an event in the store who listen to map change onMapChangeSize
___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 191 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1745#-NpZjmE-73xQ1oljUE3t:-NpZjmE-73xQ1oljUE3u:bgypklz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d9aeefc97554652802f8af455db655d1bdc45d92/packages/geoview-core/src/ui/tabs/tabs.tsx#L191)):*
> ```XML
>             <Box sx={sxClasses.mobileDropdown}>
>               <Select
>                 labelId="provinceGeolocatorFiltersLabel"
> ```

Wrong labelid

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1745)* status: all files reviewed, 2 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 147 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1745#-Np_rS1vCcOID285aKRU:-Np_rS1vCcOID285aKRV:blkc4ib) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c99513242d32acde5f60767daadfe472696d4a1b/packages/geoview-core/src/ui/tabs/tabs.tsx#L147)):*
> ```XML
> 
>     // add no tab field which will be used to collapse the footer panel.
>     const noTab = { type: 'item', item: { value: '', children: 'No Tab' } };
> ```

Use translation

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1745)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 140 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1745#-NpZi_2YDrimKipUUsRs:-Np_sWbE4yd0lcmnTLfB:bb7f2mf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d9aeefc97554652802f8af455db655d1bdc45d92/packages/geoview-core/src/ui/tabs/tabs.tsx#L140)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we have breakpoints for this.... we should we have one.... 768 is width of iPadMini
</blockquote></details>

done
___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 145 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1745#-NpZiA7PA_bPxlZLQ3zU:-Np_sXWVERgOPXWm8-JW:bb7f2mf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d9aeefc97554652802f8af455db655d1bdc45d92/packages/geoview-core/src/ui/tabs/tabs.tsx#L145)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We already have an event in the store who listen to map change onMapChangeSize
</blockquote></details>

done
___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 191 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1745#-NpZjmE-73xQ1oljUE3t:-Np_sYNS4bcIHwW2qFvg:b-7ql1td) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d9aeefc97554652802f8af455db655d1bdc45d92/packages/geoview-core/src/ui/tabs/tabs.tsx#L191)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Wrong labelid
</blockquote></details>

fixed
___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 147 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1745#-Np_rS1vCcOID285aKRU:-Np_sVC_9jfgHfTZBUIO:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c99513242d32acde5f60767daadfe472696d4a1b/packages/geoview-core/src/ui/tabs/tabs.tsx#L147)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use translation
</blockquote></details>

Done.

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1745)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 134 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1745#-NpZk0a35_MPVVhb9ajD:-Np_sg7b0_w3u1lHog9h:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d9aeefc97554652802f8af455db655d1bdc45d92/packages/geoview-core/src/ui/tabs/tabs.tsx#L134)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

For mobile, we should have a no tab like filter for geolocator. This selection will collapse the footer tab section
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1745)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Pull request merged**
