### PR TITLE
fix(Appbar): refactor appbar for export modal   #closes2161

### LINKED ISSUE #2161: [BUG] <Display Appbar Legend in Export Modal>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Open navigator page with appbar, and user clicked on export modal, legend is not displayed when legend is not opened in panel.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Refactor app bar component, so that panels can be opened using getter and setters, which can be used inside export modal template to show/hide legends.

Fixes #2161 
New ticket for navbar panel #2180 
## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/demos-navigator.html?config=./configs/navigator/07-basic-appbar.json

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174)* status: 7 of 8 files reviewed, 6 unresolved discussions (waiting on @cphelefu and @kaminderpal)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 73 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174#-NyzgA_j6I6rNkzmfKFL:-NyzgA_k0oCFUbKg1bB8:b-4jmy57) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cdb84f3c4ee4f9749015add968a42d7a72867a77/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L73)):*
> ```XML
>   const interaction = useMapInteraction();
>   const appBarComponents = useUIAppbarComponents();
>   const isGeolocatorActive = useUIAppbarGeolocatorActive();
> ```

Should we treat geolocator like other panel and check which panel is active and not focus on geolocator?
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 209 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174#-Nyzi7yS4RpR6Eczc0If:-Nyzi7yT6Vz6foAnut2N:bdv4lm7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cdb84f3c4ee4f9749015add968a42d7a72867a77/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L209)):*
> ```XML
>       appBarApi.offAppBarRemoved(handleRemoveButtonPanel);
>     };
>     // eslint-disable-next-line react-hooks/exhaustive-deps
> ```

Can you add a comment for why we do the eslint disable
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 218 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174#-NyziOC9E1i5xmCVoWWX:-NyziOC9E1i5xmCVoWWY:b-6aqcaj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cdb84f3c4ee4f9749015add968a42d7a72867a77/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L218)):*
> ```XML
>     if (isOpen) {
>       // close geolocator if opened when panel is open.
>       if (isGeolocatorActive) {
> ```

Should it be for all panel, not only geolocator?
___
*[`packages/geoview-core/src/core/components/export/export-modal.tsx` line 126 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174#-NyzlbySAVCwD6nZArJB:-NyzlbySAVCwD6nZArJC:bq7ckmr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cdb84f3c4ee4f9749015add968a42d7a72867a77/packages/geoview-core/src/core/components/export/export-modal.tsx#L126)):*
> ```XML
>         // add legend
> 
>         // check if footer tab exist then we dnt need
> ```

Typo dnt
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 136 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174#-NyzltbO-DfDi2ICjAyG:-NyzltbP9g-cbUdLS399:bo8rfs6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cdb84f3c4ee4f9749015add968a42d7a72867a77/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L136)):*
> ```XML
>     // Log
>     logger.logTraceUseEffect('NAV-BAR - mount');
>     // TODO: it will be fixed in #2180
> ```

Can we have a big comment at the top for all the dead code and the link to the issues.
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/ui-state.ts` line 43 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174#-NyzmLPiDoU9Hcqoq1AP:-NyzmLPiDoU9Hcqoq1AQ:btf0r0q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cdb84f3c4ee4f9749015add968a42d7a72867a77/packages/geoview-core/src/core/stores/store-interface-and-intial-values/ui-state.ts#L43)):*
> ```XML
>     openModal: (uiFocus: FocusItemProps) => void;
>     setActiveFooterBarTab: (id: string) => void;
>     setActiveAppBarTab: (tabId: string, tabGroup: string, isOpen: boolean) => void;
> ```

Do we have the same setter in footer to select automatically a footer tab.... We will need the same thing for footer

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174)* status: 6 of 8 files reviewed, 7 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 209 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174#-Nyzi7yS4RpR6Eczc0If:-NyztuNBDvZkCJUkQsmn:b-qssebl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cdb84f3c4ee4f9749015add968a42d7a72867a77/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L209)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add a comment for why we do the eslint disable
</blockquote></details>

fixed.
___
*[`packages/geoview-core/src/core/components/export/export-modal.tsx` line 126 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174#-NyzlbySAVCwD6nZArJB:-NyzuAWxAe64cC1fNknP:b-qssebl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cdb84f3c4ee4f9749015add968a42d7a72867a77/packages/geoview-core/src/core/components/export/export-modal.tsx#L126)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo dnt
</blockquote></details>

fixed.
___
*[`packages/geoview-core/src/core/components/export/export-modal.tsx` line 149 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174#-NyzpMx2CREtRskpsKJ4:-NyzqO2E2E9ilm2DheHa:bvind27) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cdb84f3c4ee4f9749015add968a42d7a72867a77/packages/geoview-core/src/core/components/export/export-modal.tsx#L149)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Is there a reason for the time increment?
</blockquote></details>

Panels are rendered on UI with animation which delay full render, When i click on export modal, `htmlToImage` needs content to be rendered on DOM before it is executed, thats why i have added 
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 136 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174#-NyzltbO-DfDi2ICjAyG:-Nyzsyp16astFdMFhTwF:b-t5phfy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cdb84f3c4ee4f9749015add968a42d7a72867a77/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L136)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Why did we comment out the code? Why didnt we just delete it if its not used?
</blockquote></details>

@cphelefu It is will not be dead code, because i need some part of it when i will refactor navbar panels in #2180 
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/ui-state.ts` line 43 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174#-NyzmLPiDoU9Hcqoq1AP:-NyztMNy5o0_gdr5729i:b-ctrmsy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cdb84f3c4ee4f9749015add968a42d7a72867a77/packages/geoview-core/src/core/stores/store-interface-and-intial-values/ui-state.ts#L43)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we have the same setter in footer to select automatically a footer tab.... We will need the same thing for footer
</blockquote></details>

setActiveFooterBarTab: (id: string) => void;
can be refactored into ` setActiveAppBarTab`

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174)* status: 5 of 8 files reviewed, 8 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 18 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174#-Nz--SRx46PdO4bLpx_1:-Nz-0OWc0Lik33sfGNhD:biysgqq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9d2d5ddcbb936262a97022bc2b77c2e209aa5a2d/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L18)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

I think we can just delete this commented out code.
</blockquote></details>

I will clean up #2180

**Review by cphelefu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174#-:-Nz-6IWV8k5-WP2EQ7AF:bnfp4nl)* status: 5 of 8 files reviewed, 7 unresolved discussions (waiting on @jolevesq and @kaminderpal)

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174)* status: 5 of 15 files reviewed, 7 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 73 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174#-NyzgA_j6I6rNkzmfKFL:-Nz-Dzv49pm85rCqt2Ao:bb7f2mf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cdb84f3c4ee4f9749015add968a42d7a72867a77/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L73)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we treat geolocator like other panel and check which panel is active and not focus on geolocator?
</blockquote></details>

done
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 218 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2174#-NyziOC9E1i5xmCVoWWX:-Nz-E0ml89DMGOdrrZ9E:bb7f2mf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cdb84f3c4ee4f9749015add968a42d7a72867a77/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L218)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should it be for all panel, not only geolocator?
</blockquote></details>

done

**Pull request merged**
