### PR TITLE
fix(geo/core): Fix zoom multi geometry, bad dates in layers, return g…

### LINKED ISSUE #2109: [BUG] DataTable/Details zoom Multi Geometry
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we have multi geometry, the zoom to function zooms to center of the extent of all feature n the multi geometry

image

image

In data table it is worst because feature zoomed to (selected) are not highlighted on the map

### Expected Behavior

When multiple geometry, the zoom should zoom to the extent of all geometries and highlight them

### Steps To Reproduce

1. https://canadian-geospatial-platform.github.io/geoview/public/demos-navigator.html?config=./configs/navigator/10-package-time-slider.json
2. Go to data table - historical flood
3. Filter by province code = MB
4. Zoom to item in the table, see difference when selected from details

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jolevesq**
…eometry for esri

Closes #2109, #2200, #2208

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- Add extent on feature zoom for details and table
- Add fail over data format when field value is null for n on loading layer
- Add geometry false for esri dynamioc fetch all feature info for table not loading. This as a side effect to disable de zoom. I have added an issue to tackle this

Fixes  #2109, #2200, #2208

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
- Can test multi on timeslider sample with historical flood
- CAn test boath layers in problem (not loadiing, no table) on second link
Hosted May, 05, 10AM: 
https://jolevesq.github.io/geoview/demos-navigator.html
https://jolevesq.github.io/geoview/outliers.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2217)

### CODE REVIEW

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2217)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

___
*[`packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts` line 122 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2217#-NzdCA0vAallgouqMyl0:-NzdCA0wEqM9HwN-4g9o:b6nygq0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8afc67335f278cb87d875a81e1fb130c0dd6e3cf/packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts#L122)):*
> ```XML
>       // TODO: we put false so on heavy geometry, dynamic layer can load datatable. If not the featch fails.
>       // TODO.CONT: fix the zoom to feature who is disable for esri because geometry is not fetched #2215
>       const url = `${urlRoot}${layerConfig.layerId}/query?where=1=1&outFields=*&f=json&returnGeometry=false`;
> ```

Merci de le faire dans le mirroir :)

**Review by DamonU2 — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2217)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2217)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by DamonU2 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2217)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
