### PR TITLE
refactor(store): Refactor north arrow to use the store and remove api…

### LINKED ISSUE #1329: [REFACTOR] North Arrow Use Store
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

North arrow is using events

### Expected Behavior

North arrow should use store

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jolevesq**
… from footer element

Closes #1329

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358)

### CODE REVIEW

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358)* status: all files reviewed, 5 unresolved discussions (waiting on @cphelefu, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/src/api/eventProcessors/map-event-process.ts` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358#-NfwDZtr3g5AV8eU9Rof:-NfwDZts2jz61WFpJEh-:bcq236j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/eaa360e517d2672287d69d281deda4fc9d136c0f/packages/geoview-core/src/api/eventProcessors/map-event-process.ts#L51)):*
> ```XML
>         // because emit and on from api events can be trigger in loop, compare also the api value
>         if (cur !== prev && api.maps[mapId].currentProjection !== cur!) {
>           console.log(`proj emit ${mapId}`);
> ```

"Disable no console for this line" to prevent flags?
___
*[`packages/geoview-core/src/api/eventProcessors/map-event-process.ts` line 84 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358#-NfwDkpx07O8jxa14Vus:-NfwDkpx07O8jxa14Vut:b-8a05gs) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/eaa360e517d2672287d69d281deda4fc9d136c0f/packages/geoview-core/src/api/eventProcessors/map-event-process.ts#L84)):*
> ```XML
>         // because emit and on from api events can be trigger in loop, compare also the api value
>         if (payloadIsAMapViewProjection(payload) && api.maps[mapId].currentProjection !== payload.projection!) {
>           console.log(`proj on ${mapId}`);
> ```

As above
___
*[`packages/geoview-core/src/core/components/overview-map/overview-map.tsx` line 113 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358#-NfwIyHi4_ukHzYaJHuE:-NfwIyHi4_ukHzYaJHuF:b-k3mwr1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/eaa360e517d2672287d69d281deda4fc9d136c0f/packages/geoview-core/src/core/components/overview-map/overview-map.tsx#L113)):*
> ```XML
> 
>   /**
>    * Return the map ovberview map
> ```

ovberview > overview
___
*[`packages/geoview-core/src/core/stores/stores-managers.ts` line 35 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358#-NfwKZYjEmQaSUXefUJJ:-NfwKZYjEmQaSUXefUJK:b-doj4fq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/eaa360e517d2672287d69d281deda4fc9d136c0f/packages/geoview-core/src/core/stores/stores-managers.ts#L35)):*
> ```XML
>   initializeEventProcessors(geoViewStore);
> 
>   console.log('store creation');
> ```

Disable no console?
___
*[`packages/geoview-core/src/geo/map/map.ts` line 413 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358#-NfwKggEEXRadP7R8T_u:-NfwKggEEXRadP7R8T_v:b-8a05gs) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/eaa360e517d2672287d69d281deda4fc9d136c0f/packages/geoview-core/src/geo/map/map.ts#L413)):*
> ```XML
>           this.map.getView().on('change:rotation', store.getState().mapState.onMapRotation);
> 
>           console.log('store add map event');
> ```

As above

**Review by cphelefu — APPROVED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358)* status: all files reviewed, 5 unresolved discussions (waiting on @jolevesq and @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 7 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358)* status: 19 of 25 files reviewed, 5 unresolved discussions (waiting on @cphelefu, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/api/eventProcessors/map-event-process.ts` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358#-NfwDZtr3g5AV8eU9Rof:-Ng3q1fq92grz_qbGL_W:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/eaa360e517d2672287d69d281deda4fc9d136c0f/packages/geoview-core/src/api/eventProcessors/map-event-process.ts#L51)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

"Disable no console for this line" to prevent flags?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/eventProcessors/map-event-process.ts` line 84 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358#-NfwDkpx07O8jxa14Vus:-Ng3q2Pz7ai33UH3Z-77:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/eaa360e517d2672287d69d281deda4fc9d136c0f/packages/geoview-core/src/api/eventProcessors/map-event-process.ts#L84)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

As above
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/overview-map/overview-map.tsx` line 113 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358#-NfwIyHi4_ukHzYaJHuE:-Ng3q9Z4EM9XtKQvMnKZ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/eaa360e517d2672287d69d281deda4fc9d136c0f/packages/geoview-core/src/core/components/overview-map/overview-map.tsx#L113)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

ovberview > overview
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/stores/stores-managers.ts` line 35 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358#-NfwKZYjEmQaSUXefUJJ:-Ng3qAzr7dFUcTZA0G6w:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/eaa360e517d2672287d69d281deda4fc9d136c0f/packages/geoview-core/src/core/stores/stores-managers.ts#L35)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Disable no console?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/map/map.ts` line 413 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358#-NfwKggEEXRadP7R8T_u:-Ng3qD4H95SFSkGmSwVO:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/eaa360e517d2672287d69d281deda4fc9d136c0f/packages/geoview-core/src/geo/map/map.ts#L413)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

As above
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 14 of 21 files at r1, 4 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358)* status: 23 of 25 files reviewed, 5 unresolved discussions (waiting on @cphelefu, @DamonU2, and @ychoquet)

**Review by DamonU2 — APPROVED** [review]
> Reviewed 2 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/api/eventProcessors/notification-event-process.ts` line 15 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358#-Ng4m1J2-3YZ0FyTHDV5:-Ng4m1J2-3YZ0FyTHDV6:biokkd2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f79b1f0724fd915f64ba1d058f6da0b9bcd262a2/packages/geoview-core/src/api/eventProcessors/notification-event-process.ts#L15)):*
> ```XML
>     api.event.on(
>       EVENT_NAMES.NOTIFICATIONS.NOTIFICATION_ADD,
>       (payload: PayloadBaseClass) => {
> ```

Why do we have this here? Where do we call this NOTIFICATION_ADD; why didnt we just add it to the store directly from there?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/map/map.tsx` line 59 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358#-Ng4mWhh9m5WTytBC6YB:-Ng4mWhh9m5WTytBC6YC:bnbe5bt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f79b1f0724fd915f64ba1d058f6da0b9bcd262a2/packages/geoview-core/src/core/components/map/map.tsx#L59)):*
> ```XML
> 
>   // get values from the store
>   const { mapLoaded, northArrow, overviewMap } = useStore(getGeoViewStore(mapId), (state) => state.mapState);
> ```

This is going to refresh page whenever any property in mapState is changed. 
I think it should be (state) => [state.mapState.mapLoaded, state.mapState,northArrow ])..

Something along these lines, confirm in zustand documentation

**Review by jolevesq — COMMENTED** [review]
> Reviewed 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358)* status: all files reviewed, 2 unresolved discussions (waiting on @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358)* status: all files reviewed, 2 unresolved discussions (waiting on @cphelefu and @ychoquet)

___
*[`packages/geoview-core/src/api/eventProcessors/notification-event-process.ts` line 15 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358#-Ng4m1J2-3YZ0FyTHDV5:-Ng4p6wPAey-YrrfqIjn:bphsvyg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f79b1f0724fd915f64ba1d058f6da0b9bcd262a2/packages/geoview-core/src/api/eventProcessors/notification-event-process.ts#L15)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Why do we have this here? Where do we call this NOTIFICATION_ADD; why didnt we just add it to the store directly from there?
</blockquote></details>

Because this event may be emit by the api from outside the viewer

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358)* status: all files reviewed, 2 unresolved discussions (waiting on @cphelefu and @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @cphelefu and @ychoquet)

___
*[`packages/geoview-core/src/core/components/map/map.tsx` line 59 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358#-Ng4mWhh9m5WTytBC6YB:-Ng4sI85-s1qMiXk-W8b:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f79b1f0724fd915f64ba1d058f6da0b9bcd262a2/packages/geoview-core/src/core/components/map/map.tsx#L59)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

This is going to refresh page whenever any property in mapState is changed. 
I think it should be (state) => [state.mapState.mapLoaded, state.mapState,northArrow ])..

Something along these lines, confirm in zustand documentation
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358)* status: all files reviewed, 2 unresolved discussions (waiting on @cphelefu and @ychoquet)

**Review by cphelefu — COMMENTED** [review]
> Reviewed 8 of 13 files at r2, 13 of 14 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1358)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Pull request merged**
