### PR TITLE
refactor (basemap): update styling and focus issues on basepanel close #1577

### LINKED ISSUE #1577: [UI] Basemap Package
The basemap package is not behaving the way ti should be... needs a better looking ui

- [ ] Need a selected indicator
- [ ] The is a dark overlay on all items
- [ ] Width of panel is nor right

BUG:

- [ ] When I close the second basemap panel, the focus jump on the first map
- [ ] The second panel has no available layers in the panel

### PR DESCRIPTION
**Pull request by mayurmarakana89**
# Description

1. Fixed styling issues:
> - updated selected state of basepanel card
> - updated hovering state of basepanel card
> - fixed width of basepanel
> - fixed width of searchbox on basepanel

2. Fixed focus issue while closing the 2nd maps basepanel

Fixes # ([1577](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1577))

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://mayurmarakana89.github.io/geoview/package-basemap-panel.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1631)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1631)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @kaminderpal, @mayurmarakana89, and @ychoquet)

___
*[`packages/geoview-core/public/css/style.css` line 187 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1631#-Nm1VJ-a3WTrrP-ixTpz:-Nm1VJ-b9N_iXHe9bk9N:bx8ss9d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/24e0267cfee6ee96c043de424d0919c15725a7c6/packages/geoview-core/public/css/style.css#L187)):*
> ```CSS
> 
> /* Customize website's scrollbar */
> *::-webkit-scrollbar {
> ```

If we want to modify the scroll bar we should do it only for the inside of the viewer

**Review by mayurmarakana89 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1631)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @jolevesq, @kaminderpal, and @ychoquet)

___
*[`packages/geoview-core/public/css/style.css` line 187 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1631#-Nm1VJ-a3WTrrP-ixTpz:-Nm2am2g84ls-zbDxgNj:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/24e0267cfee6ee96c043de424d0919c15725a7c6/packages/geoview-core/public/css/style.css#L187)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If we want to modify the scroll bar we should do it only for the inside of the viewer
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1631)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @kaminderpal, @mayurmarakana89, and @ychoquet)

___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 148 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1631#-Nm7OdM14OZ6QHmRQ_WX:-Nm7OdM14OZ6QHmRQ_WY:b-k4gqvi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b9646cbda90cd8898ccd6c667d79e0430f9cfddc/packages/geoview-core/src/core/containers/shell.tsx#L148)):*
> ```XML
>           <CircularProgress isLoaded={mapLoaded} />
>           <CircularProgress isLoaded={!circularProgressActive} />
>           <Box id={`map-container-${mapId}`} sx={sxClasses.mapShellContainer} className="mapContainer">
> ```

Why do you add container, have you tested an many pages for side effects?
___
*[`packages/geoview-core/src/ui/panel/panel.tsx` line 245 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1631#-Nm7NIdO8ZT9HQFZhLGX:-Nm7NIdO8ZT9HQFZhLGY:b3qlort) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b9646cbda90cd8898ccd6c667d79e0430f9cfddc/packages/geoview-core/src/ui/panel/panel.tsx#L245)):*
> ```XML
>           escapeDeactivates: false,
>           clickOutsideDeactivates: true,
>           initialFocus: false,
> ```

This is not WCAG. When open by the keyboard, it must focus on the close button. You should put this to false only when the user is in keyboard navigation. When this store value is tru, the navigation is from keyboard: useUIActiveTrapGeoView

**Review by mayurmarakana89 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1631)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @jolevesq, @kaminderpal, and @ychoquet)

___
*[`packages/geoview-core/src/ui/panel/panel.tsx` line 245 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1631#-Nm7NIdO8ZT9HQFZhLGX:-Nm7t_d03D0-Zb455jId:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b9646cbda90cd8898ccd6c667d79e0430f9cfddc/packages/geoview-core/src/ui/panel/panel.tsx#L245)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This is not WCAG. When open by the keyboard, it must focus on the close button. You should put this to false only when the user is in keyboard navigation. When this store value is tru, the navigation is from keyboard: useUIActiveTrapGeoView
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 148 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1631#-Nm7OdM14OZ6QHmRQ_WX:-Nm7taraEZuESMg59ACk:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b9646cbda90cd8898ccd6c667d79e0430f9cfddc/packages/geoview-core/src/core/containers/shell.tsx#L148)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why do you add container, have you tested an many pages for side effects?
</blockquote></details>

Done.

**Review by mayurmarakana89 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1631)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @jolevesq, @kaminderpal, and @ychoquet)

___
*[`packages/geoview-core/src/ui/panel/panel.tsx` line 245 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1631#-Nm7NIdO8ZT9HQFZhLGX:-Nm7uil_CK8fFzdrROs9:b-gl0kvl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b9646cbda90cd8898ccd6c667d79e0430f9cfddc/packages/geoview-core/src/ui/panel/panel.tsx#L245)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think you can just do initialFocus: activeTrapGeoView..
</blockquote></details>

intialFocus accepts only focusTargetOrFalse or undefined. hence used this.

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1631)* status: all files reviewed, 1 unresolved discussion (waiting on @amir-azma, @cphelefu, @DamonU2, @jolevesq, @kaminderpal, and @ychoquet)

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 4 of 7 files at r1, 2 of 3 files at r2, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1631)* status: all files reviewed, 1 unresolved discussion (waiting on @amir-azma, @cphelefu, @DamonU2, @jolevesq, @kaminderpal, and @ychoquet)

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 3 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1631)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @amir-azma, @cphelefu, @DamonU2, @kaminderpal, and @ychoquet)

**Pull request merged**
