### PR TITLE
fix(core): zoom default, translation, zoom layer

### LINKED ISSUE #2183: [BUG] Default Zoom Issue
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There's a zoom-out problem with the demos on the https://canadian-geospatial-platform.github.io/geoview/public/demos-navigator.html page. When loading a map, for example the first choice (Basemap LCC Transport-Labeled-Shaded), it is impossible to zoom out. If we look at mapState.zoom in the store, the initial value is 3.5, but in reality the zoom is 5.337602481695214. You can see this value by trying to zoom out. If you go back and forth between projections (LCC->Mercator->LCC), zooming out is now possible.

There's also a problem with the default value for the map center. The map-viewer.ts file (line ~247) gives a zoomAndCenter of [-90, 06] whereas the configuration file gives [-90, 67].

Another problem detected is that the map-event-processor.ts file (line ~753) has this line of code:

***[options.maxZoom] = getGeoViewStore(mapId).getState().mapConfig!.map.viewSettings.initialView!.zoomAndCenter!;***

However, there is no maxZoom property at this level.
Instead, the line should contain the following code:

***options.maxZoom = getGeoViewStore(mapId).getState().mapConfig!.map.viewSettings.maxZoom!;***

### Expected Behavior

Restore the normall behavior of the zoom and center feature of the viewer. Use a constant definition from the config-constants.ts file for the default values instead of hard coding a value.

### Steps To Reproduce

1. Go to https://canadian-geospatial-platform.github.io/geoview/public/demos-navigator.html
2. Select the first item ***Basemap LCC Transport-Labeled-Shaded***
3. Open the Chrome Devtool , select tab Components, and inspect mapState.zoom in getViewStore-sandboxMap (it should be 3.5 but config-constants.ts file defines it as 4.5)
4. Try to zoom out and inspect mapState.zoom again, it shoud be around 5.33 and you should not be ables to zoom out more than that
5. Change the projection from LCC to Mercator and back to LCC
6. You sould be able to zoom out now.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jolevesq**
Closes 2183-zoom

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- translation
- zoom to layer not working on legend panel for geoJSON
- default zoom/maxExtent

Fixes #2183

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Hosted, June 03, 16:3-: https://jolevesq.github.io/geoview/demos-navigator.html

# Checklist:

- [ ] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2202)

### CODE REVIEW

**Review by DamonU2 — APPROVED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2202)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 10 of 14 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2202)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 785 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2202#-NzZT_jD0bolc0i3lObX:-NzZT_jD0bolc0i3lObY:b240omp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fb5d756b2ff0fc27fe86d91c760464e37798782a/packages/geoview-core/src/api/config/types/config-validation-schema.json#L785)):*
> ```JSON
>             "minimum": -80,
>             "maximum": 80,
>             "default": 65
> ```

Must be the same as CV_MAP_CENTER[3978]



_Code quote:_
```JSON
"default": 65
```

**Review by ychoquet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2202)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/api/config/types/config-constants.ts` line 140 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2202#-NzZVI9K1aWlqc-RoOgm:-NzZVI9K1aWlqc-RoOgn:b-3y93za) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fb5d756b2ff0fc27fe86d91c760464e37798782a/packages/geoview-core/src/api/config/types/config-constants.ts#L140)):*
> ```XML
>   3857: [-90, 55],
>   3978: [-90, 60],
> };
> ```

Creating different center depending on the projection code is a good idea. However, it must be set in the static method #getDefaultMapConfig that is in map-feature-config in a similar way we set  the maxExtent.



_Code quote:_
```XML
export const CV_MAP_CENTER: Record<TypeValidMapProjectionCodes, number[]> = {
  3857: [-90, 55],
  3978: [-90, 60],
};
```

**Review by jolevesq — COMMENTED** [review]
> Reviewed 13 of 14 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2202)* status: 10 of 15 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/config-constants.ts` line 140 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2202#-NzZVI9K1aWlqc-RoOgm:-NzZrOH14bxnRanEzXe-:busxcau) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fb5d756b2ff0fc27fe86d91c760464e37798782a/packages/geoview-core/src/api/config/types/config-constants.ts#L140)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Creating different center depending on the projection code is a good idea. However, it must be set in the static method #getDefaultMapConfig that is in map-feature-config in a similar way we set  the maxExtent.
</blockquote></details>

I set in default config if no settings provided
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 785 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2202#-NzZT_jD0bolc0i3lObX:-NzZrVDDAxnF-LWnn4uV:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fb5d756b2ff0fc27fe86d91c760464e37798782a/packages/geoview-core/src/api/config/types/config-validation-schema.json#L785)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Must be the same as CV_MAP_CENTER[3978]
</blockquote></details>

Done

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2202)* status: 12 of 15 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/config-constants.ts` line 140 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2202#-NzZVI9K1aWlqc-RoOgm:-NzZu6rz1IO_rPNp4vUm:b-gu1ow8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fb5d756b2ff0fc27fe86d91c760464e37798782a/packages/geoview-core/src/api/config/types/config-constants.ts#L140)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I set in default config if no settings provided
</blockquote></details>

Done in map feature config

**Review by ychoquet — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2202)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan and @DamonU2)

**Pull request merged**
