### PR TITLE
feat(map-accessibility): Fix some accessibility issues on the map, and related buttons

### LINKED ISSUE #1791: [FEATURE] Map accessibility
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

_No response_

### User Story

We need to make sure our accessibility features we have added in our project will work on screen readers and also with keyboard navigation

__Map__
- [ ] Map container focus
- [ ] Overview map
- [ ] Map information section (attribution, mouse coord, scale, rotation)
- [ ] Swiper

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by amir-azma**
# Description

We need to make sure our accessibility features we have added in our project will work on screen readers and also with keyboard navigation

Fixes #1791

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
https://amir-azma.github.io/geoview/index.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822)

### CODE REVIEW

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822)* status: 0 of 8 files reviewed, 1 unresolved discussion

___
*[`packages/geoview-core/src/ui/icon-button/icon-button.tsx` line 35 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822#-Nqno5PEBbP8NjuHniUY:-Nqno5PEBbP8NjuHniUZ:brdaolr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ef43e12c12c5cc2fa412231f8aeb353bab08c296/packages/geoview-core/src/ui/icon-button/icon-button.tsx#L35)):*
> ```XML
>   return (
>     <Tooltip title={t((tooltip as string) || '') as string} placement={tooltipPlacement} TransitionComponent={Fade}>
>       <span>
> ```

We don't need span tag here.

**Comment by kmansoor713** [comment]
In #1822, All the issues are pretty much similar to #1791
1-	Keyboard Navigation pop up should display in middle of map
 2-	About Geoview - Geo.Ca and Repo Link  are in similar color format, It should be different color.
 3-	When user selects the Attribution and move the arrow key up-down, Hover over text “© His Majesty the King in Right of Canada, as represented by the Minister of Natural Resources” is also moving
4-	Arrow keys keep moving the map far Up-Down and Left-Right, It should stay within map boundary.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822)* status: 8 of 10 files reviewed, 6 unresolved discussions (waiting on @amir-azma and @kmansoor713)

___
*[`packages/geoview-core/src/core/containers/focus-trap.tsx` line 93 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822#-NrAeCKu69MhGFPONWsJ:-NrAeCKu69MhGFPONWsK:b8olfo7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b530b78bafbc6e930aa2cd30dff471175d9e5af3/packages/geoview-core/src/core/containers/focus-trap.tsx#L93)):*
> ```XML
>     if (!arrowKeyCodes.includes(evt.code as string)) {
>       // remove the border from the map
>       document.getElementById(`mapbox-${mapId}`)!.style.border = '';
> ```

Instead of applying style, can we just use classList to toggle a class name with a style applied?
___
*[`packages/geoview-core/src/core/containers/focus-trap.tsx` line 122 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822#-NrAeOS04TU5rqtCyaLu:-NrAeOS11Bs7Xh-M7WJs:bbxgkzp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b530b78bafbc6e930aa2cd30dff471175d9e5af3/packages/geoview-core/src/core/containers/focus-trap.tsx#L122)):*
> ```XML
>     setFocusTrap();
>     const borderColor =
>       theme.palette.mode === 'light' ? theme.palette.geoViewColor.primary.dark[300] : theme.palette.geoViewColor.primary.light[300];
> ```

Same comment as above
___
*[`packages/geoview-core/src/core/containers/focus-trap.tsx` line 157 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822#-NrAeRPt5cYM8dM-mrs5:-NrAeRPt5cYM8dM-mrs6:b-vkj4w4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b530b78bafbc6e930aa2cd30dff471175d9e5af3/packages/geoview-core/src/core/containers/focus-trap.tsx#L157)):*
> ```XML
>           exitFocus();
>           // remvoe border from the map
>           document.getElementById(`mapbox-${mapId}`)!.style.border = '';
> ```

Typo remove and same comment as above
___
*[`packages/geoview-core/src/ui/icon-button/icon-button.tsx` line 38 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822#-NrAe_u10rRT5AO6XlDv:-NrAe_u10rRT5AO6XlDw:b-n0d2n4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b530b78bafbc6e930aa2cd30dff471175d9e5af3/packages/geoview-core/src/ui/icon-button/icon-button.tsx#L38)):*
> ```XML
>         id={id}
>         sx={sx}
>         aria-label={t((ariaLabel as string) || '') as string}
> ```

If not specific aria value, apply tooltip
___
*[`packages/geoview-core/src/ui/popover/popover.tsx` line 12 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822#-NrAelr24ESLuRGnjJR8:-NrAelr24ESLuRGnjJR9:b-t4qn5d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b530b78bafbc6e930aa2cd30dff471175d9e5af3/packages/geoview-core/src/ui/popover/popover.tsx#L12)):*
> ```XML
>  */
> export function Popover(props: PopoverProps): JSX.Element {
>   const arrowKeyCodes: string[] = ['ArrowUp', 'ArrowRight', 'ArrowDown', 'ArrowLefts', 'Space'];
> ```

Arrow key code is used twice, Put it in constant file and reuse. Then do a push of space in the array an explain why because space is not an arrow

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822)* status: 7 of 12 files reviewed, 6 unresolved discussions (waiting on @jolevesq and @kmansoor713)

___
*[`packages/geoview-core/src/core/containers/focus-trap.tsx` line 93 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822#-NrAeCKu69MhGFPONWsJ:-NrBSi8SD3lAxziSeSXx:b-r86ixc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1486d7ffe38187cc591c724db13275abdacb7923/packages/geoview-core/src/core/containers/focus-trap.tsx#L93)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Instead of applying style, can we just use classList to toggle a class name with a style applied?
</blockquote></details>

I used this logic 
document.getElementById(\`mapbox-${mapId}\`)!.style.border \= sxClasses.enableFocus.border;
Done
___
*[`packages/geoview-core/src/core/containers/focus-trap.tsx` line 122 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822#-NrAeOS04TU5rqtCyaLu:-NrBSlu40hxtY25ehnmz:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1486d7ffe38187cc591c724db13275abdacb7923/packages/geoview-core/src/core/containers/focus-trap.tsx#L122)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same comment as above
</blockquote></details>

Done
___
*[`packages/geoview-core/src/core/containers/focus-trap.tsx` line 156 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822#-NrBSpEnEMQCMherwMhy:-NrBSpEnEMQCMherwMhz:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1486d7ffe38187cc591c724db13275abdacb7923/packages/geoview-core/src/core/containers/focus-trap.tsx#L156)):*
> ```XML
>           setOpen(false);
>           exitFocus();
>           // remvoe border from the map
> ```

Done
___
*[`packages/geoview-core/src/core/containers/focus-trap.tsx` line 157 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822#-NrAeRPt5cYM8dM-mrs5:-NrBT6m93V6ZhbJ2Tk_0:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1486d7ffe38187cc591c724db13275abdacb7923/packages/geoview-core/src/core/containers/focus-trap.tsx#L157)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo remove and same comment as above
</blockquote></details>

Done
___
*[`packages/geoview-core/src/ui/icon-button/icon-button.tsx` line 38 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822#-NrAe_u10rRT5AO6XlDv:-NrC6ob57RG-GEE_gJ7Z:be9uqa5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1486d7ffe38187cc591c724db13275abdacb7923/packages/geoview-core/src/ui/icon-button/icon-button.tsx#L38)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If not specific aria value, apply tooltip
</blockquote></details>

applied this change:  aria-label={(t(ariaLabel as string) || t(tooltip as string)) as string}
___
*[`packages/geoview-core/src/ui/popover/popover.tsx` line 12 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822#-NrAelr24ESLuRGnjJR8:-NrB_Fox-YqhJPnMjKgJ:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1486d7ffe38187cc591c724db13275abdacb7923/packages/geoview-core/src/ui/popover/popover.tsx#L12)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Arrow key code is used twice, Put it in constant file and reuse. Then do a push of space in the array an explain why because space is not an arrow
</blockquote></details>

Done

**Review by jolevesq — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822)* status: all files reviewed, 2 unresolved discussions (waiting on @kmansoor713)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1822)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kmansoor713)

**Pull request merged**
