### PR TITLE
fix(1855) - Esri Dynamic can now query "all" features

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

This PR implements the getAllFeatureInfo() for Esri Dynamic layers.
Fixes: #1855 #1921 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Hosted, April 10th, 19h30: https://alex-nrcan.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1997)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1997)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/geo/renderer/geoview-renderer.ts` line 197 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1997#-Nv6w9mx-rOK3mivCTbO:-Nv6w9mx-rOK3mivCTbP:bto8egs) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5ddd0825396960875047a1630dfabcd73ab464f0/packages/geoview-core/src/geo/renderer/geoview-renderer.ts#L197)):*
> ```XML
>     // TODO: Refactor - This whole class should be all static functions. Remove these 2 class attributes, adjusting the code accordingly
>     this.mapId = mapId;
>     this.defaultColorIndex = 0;
> ```

How do we keep reference of increment value in static method?

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1997)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/renderer/geoview-renderer.ts` line 197 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1997#-Nv6w9mx-rOK3mivCTbO:-Nv71qkIBYNEmSjmtVg_:b-tgr7jw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5ddd0825396960875047a1630dfabcd73ab464f0/packages/geoview-core/src/geo/renderer/geoview-renderer.ts#L197)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

How do we keep reference of increment value in static method?
</blockquote></details>

We don't :)
I mean that we remove those attributes from here and manage it differently, can be by sending them as params to the static methods.

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 3 of 4 files at r3, 5 of 7 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1997)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 439 at r6](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1997#-NvCLVNq-owv5XGvIB_p:-NvCLVNq-owv5XGvIB_q:b-yv7xvn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6a2ceea9138b6e69d8926d5eaffdbb08ab8afd8f/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L439)):*
> ```XML
>     // Log
>     logger.logError('esri-layer-common.queryRecordsByUrl()\n', error);
>     throw error;
> ```

Question: Does this throw error result in a black screen or the viewer catch it elsewhere and is still able to operate?



_Code quote:_
```XML
throw error;
```

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 6 of 7 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1997)* status: all files reviewed, 2 unresolved discussions (waiting on @DamonU2, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 439 at r6](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1997#-NvCLVNq-owv5XGvIB_p:-NvCpEDwDk4AShDsgOmK:b-srxmab) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6a2ceea9138b6e69d8926d5eaffdbb08ab8afd8f/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L439)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Question: Does this throw error result in a black screen or the viewer catch it elsewhere and is still able to operate?
</blockquote></details>

It throws an error like a regular error with a black screen.
Nobody is using this function at the moment (the TODO is still there). I think it's best that an error is thrown when a query fails.

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1997)* status: all files reviewed, 2 unresolved discussions (waiting on @DamonU2, @jolevesq, and @ychoquet)

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 4 of 5 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1997)* status: all files reviewed, 2 unresolved discussions (waiting on @DamonU2, @jolevesq, and @ychoquet)

**Pull request merged**
