### PR TITLE
fix(esriImage): time dimension added

### LINKED ISSUE #1817: [BUG] Time dimension ImageSErver
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is no time dimension creation image server: https://agriculture.canada.ca/atlas/rest/services/app_agclimate_agclimat/agclimate_hw/ImageServer

### Expected Behavior

We should extract and set time slider automatically from image server

### Steps To Reproduce

1. demo-osdp-climate.html
2. There is no layer in time slider

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #1817

# Description

Added time dimension to ESRI Image layer when there is time info in service. Added apply filter to ESRI Image layer. Updated time-slider to handle ESRI Image time dimension properly.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested playing with time slider on the following pages:
https://damonu2.github.io/geoview/package-time-slider.html
https://damonu2.github.io/geoview/demo-osdp-climate.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967)* status: all files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/core/utils/date-mgt.ts` line 322 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967#-NtzlrC2AZkln6BfXGaF:-NtzlrC31YT2Crf-6dEo:b-a4q1h3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b206d1b99f0d4b22d7f85de11412c6d5441289f/packages/geoview-core/src/core/utils/date-mgt.ts#L322)):*
> ```XML
>       range: rangeItem,
>       nearestValues: startTimeField === '' ? 'absolute' : 'discrete',
>       singleHandle: singleHandle || false,
> ```

I think you can put a default value in the function signature so you do not have to  to do || here
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 354 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967#-NtzmEPJ3P6J4c0zZ4QT:-NtzmEPJ3P6J4c0zZ4QU:b-lk7vt8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b206d1b99f0d4b22d7f85de11412c6d5441289f/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L354)):*
> ```XML
>   let queryUrl = getLocalizedValue(this.metadataAccessPath, this.mapId);
>   if (queryUrl) {
>     if (layerConfig.geoviewLayerConfig.geoviewLayerType !== 'esriImage')
> ```

Use constant, not string
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts` line 334 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967#-NtznDlb2LBlfvtQTHz5:-NtznDlb2LBlfvtQTHz6:b-96c7mp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b206d1b99f0d4b22d7f85de11412c6d5441289f/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts#L334)):*
> ```XML
>   }
> 
>   /** ***************************************************************************************************************************
> ```

Yves PR changed this apply filter a lot. Depending on who goes first there will be conflicts

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967)* status: all files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 217 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967#-NtzxEvQEi0U-VnW1uS6:-NtzxEvQEi0U-VnW1uS7:b-fvafu8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b206d1b99f0d4b22d7f85de11412c6d5441289f/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L217)):*
> ```XML
> ) {
>   if (esriTimeDimension !== undefined) {
>     this.layerTemporalDimension[layerConfig.layerPath] = api.dateUtilities.createDimensionFromESRI(
> ```

This is more a general comment with regard to the esri-layer-common file than specific to this PR. Maybe a good opportunity to try this out though and see if it works "better/simpler":

I'm guessing the usage of 'this' here, as parameter name, is the reason for having to call this function using the `.call` pattern below.
Instead of using that pattern which can be misleading sometimes, I'd suggest to transform the function static, simply use another parameter name, and call `commonProcessTemporalDimension` as a regular function.

Like:


Then: commonProcessTemporalDimension(this, xx, yy);

In fact, likely suggestion would be to make all esri-layer-common functions static.

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967)* status: all files reviewed, 4 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts` line 217 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967#-Nu-H5TF9y8HxTiCNR2J:-Nu-H5TF9y8HxTiCNR2K:bjsnvnf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b206d1b99f0d4b22d7f85de11412c6d5441289f/packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts#L217)):*
> ```XML
>       } else {
>         const filter = `${field}=date '${defaultValue}'`;
>         (api.maps[mapId].layer.geoviewLayer(layerPath) as WMS).applyViewFilter(filter);
> ```

Change this line for:
        (api.maps[mapId].layer.geoviewLayer(layerPath) as WMS).applyViewFilter(layerPath, filter);

applyViewFilter is an overloaded method and the signature I propose is compatible with your PR. When we merge my PR (1930), the overloaded signature will be eliminated and layerPath will be mandatory. So if you add layerPath now, we won't have to get back here to correct the code. Don't forget to apply this change to all applyViewFilter calls in your PR.

The elimination of the overloading will be done by me when I reconcile my PR 1930.



_Code quote:_
```XML
        (api.maps[mapId].layer.geoviewLayer(layerPath) as WMS).applyViewFilter(filter);
```
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 354 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967#-NtzmEPJ3P6J4c0zZ4QT:-Nu-J2do2OHAo5DqmzjM:b-1ofjsk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b206d1b99f0d4b22d7f85de11412c6d5441289f/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L354)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use constant, not string
</blockquote></details>

Do we have a typeguard function for this?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts` line 334 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967#-NtznDlb2LBlfvtQTHz5:-Nu-JBe77xYMi_uBAYJG:b-x2b316) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b206d1b99f0d4b22d7f85de11412c6d5441289f/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts#L334)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Yves PR changed this apply filter a lot. Depending on who goes first there will be conflicts
</blockquote></details>

Add a TODO: Yves will correct this when he rebase his PR 1930

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967)* status: 2 of 10 files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts` line 217 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967#-Nu-H5TF9y8HxTiCNR2J:-Nu-ejNQ8ut5g1QMzLtC:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b206d1b99f0d4b22d7f85de11412c6d5441289f/packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts#L217)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Change this line for:
        (api.maps[mapId].layer.geoviewLayer(layerPath) as WMS).applyViewFilter(layerPath, filter);

applyViewFilter is an overloaded method and the signature I propose is compatible with your PR. When we merge my PR (1930), the overloaded signature will be eliminated and layerPath will be mandatory. So if you add layerPath now, we won't have to get back here to correct the code. Don't forget to apply this change to all applyViewFilter calls in your PR.

The elimination of the overloading will be done by me when I reconcile my PR 1930.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/date-mgt.ts` line 322 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967#-NtzlrC2AZkln6BfXGaF:-Nu-ek2a2rLlswDVU1nW:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b206d1b99f0d4b22d7f85de11412c6d5441289f/packages/geoview-core/src/core/utils/date-mgt.ts#L322)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think you can put a default value in the function signature so you do not have to  to do || here
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 217 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967#-NtzxEvQEi0U-VnW1uS6:-Nu-el9_2D2lMbWb4bRS:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b206d1b99f0d4b22d7f85de11412c6d5441289f/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L217)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

This is more a general comment with regard to the esri-layer-common file than specific to this PR. Maybe a good opportunity to try this out though and see if it works "better/simpler":

I'm guessing the usage of 'this' here, as parameter name, is the reason for having to call this function using the `.call` pattern below.
Instead of using that pattern which can be misleading sometimes, I'd suggest to transform the function static, simply use another parameter name, and call `commonProcessTemporalDimension` as a regular function.

Like:


Then: commonProcessTemporalDimension(this, xx, yy);

In fact, likely suggestion would be to make all esri-layer-common functions static.
</blockquote></details>

Done
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 354 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967#-NtzmEPJ3P6J4c0zZ4QT:-Nu-emg50luWSsm8VVkZ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b206d1b99f0d4b22d7f85de11412c6d5441289f/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L354)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Do we have a typeguard function for this?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts` line 334 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967#-NtznDlb2LBlfvtQTHz5:-Nu-enMTBQ27DrptCwv4:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b206d1b99f0d4b22d7f85de11412c6d5441289f/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts#L334)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Add a TODO: Yves will correct this when he rebase his PR 1930
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 8 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1967)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Pull request merged**
