### PR TITLE
Add Group Param To Geometry #2241

### PR DESCRIPTION
**Pull request by guichoquette**
# Description

Under the map 4 new buttons and a short description of what the buttons does got added. The buttons add a geometry in a group named static which is not the active group. If the group is not created when the buttons are used it create the group and add the geometry concerned by the button used to it. 

Fixes # (2241)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- I used the new buttons to make sure the geometries were appearing on the map. (Add Polyline to static Group, Add Polygon to static Group, Add Circle to static Group and Add marker to static Group.
- I created a group named static with the button "Create Geometry Group".
- I selected the "static" group and deleted it. Making sure the geometries added were getting deleted at the same time.

__URL for the deploy!__
https://guichoquette.github.io/geoview/geometry.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2263)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2263)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @guichoquette)

___
*[`packages/geoview-core/public/templates/geometry.html` line 307 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2263#-O-a566K1SXxcAI58hrT:-O-a566L4JDS2hf7HzEu:b-6d6u5y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79afe874c0f0f50875c1cff61148c998d995a2e1/packages/geoview-core/public/templates/geometry.html#L307)):*
> ```HTML
>           var addPolylineBtn = document.getElementsByClassName('add-polyline-btn')[0];
>           addPolylineBtn.addEventListener('click', function (e) {
>             let groupName = document.getElementById('selectGroupsName').value
> ```

Why do you have this modification only for polylines? addPolylines only accepts one parameter
___
*[`packages/geoview-core/public/templates/geometry.html` line 365 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2263#-O-a5QyT3aRReWdWF1Xa:-O-a5QyT3aRReWdWF1Xb:b-okn2hu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79afe874c0f0f50875c1cff61148c998d995a2e1/packages/geoview-core/public/templates/geometry.html#L365)):*
> ```HTML
> 
>           // get create GeomtryFromGroup button element and add event handler
>           var createInStaticGroup = document.getElementsByClassName('create-polyline-in-static-group-btn')[0];
> ```

You should not repeat the same variable name. You should not use var but conts or let. Wth const, you would have seens the problem right away because we cannot reassign a value to a const.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2263)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @guichoquette)

**Review by guichoquette — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2263)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/geometry.html` line 307 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2263#-O-a566K1SXxcAI58hrT:-O-bQ97O3AlkUG-N0cg6:b-v2t2q6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79afe874c0f0f50875c1cff61148c998d995a2e1/packages/geoview-core/public/templates/geometry.html#L307)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why do you have this modification only for polylines? addPolylines only accepts one parameter
</blockquote></details>

Done. It was an accidental modification. I was solving the issue with a more complex solution that was using the groupName at first. When I changed my approach I just forgot the remove groupName from the parameters.
___
*[`packages/geoview-core/public/templates/geometry.html` line 365 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2263#-O-a5QyT3aRReWdWF1Xa:-O-bRqeH3tNUBAh5OpQb:bu5s0ui) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79afe874c0f0f50875c1cff61148c998d995a2e1/packages/geoview-core/public/templates/geometry.html#L365)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You should not repeat the same variable name. You should not use var but conts or let. Wth const, you would have seens the problem right away because we cannot reassign a value to a const.
</blockquote></details>

Done. I changed var for const. Also the const now have a name more representative.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2263)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guichoquette)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2263)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guichoquette)

**Pull request merged**
