### PR TITLE
adding container to select popover

### LINKED ISSUE #2248: [BUG] Chart config - Full screen mode disabled the "Steps" menu
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the "Package geochart" config, if the map is put in full screen mode, the "Steps" drop-down menu of the chart is disabled. You can't open it.

### Expected Behavior

The "Steps"drop-down menu should offer you the folowing options as usual: 
image

### Steps To Reproduce

1. Select the Package geochart config
2. Click on a "Airborne Radioactivity" station point
3. go in the chart menu
4. Put map in full screen
5. Try to open the "Steps" drop-down menu

### Anything else?

When you disabled the Full screen mode, the drop-down menu appears, floating over the map: 
image

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

In FullScreen Popovers are not visible unless container is specified. This affects Select component as it uses a Popover to show its dropdown. This fix enforces adding container to all Select.

Fixes #2248

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://cphelefu.github.io/geoview/demos-navigator.html?config=./configs/navigator/06-basic-footer.json

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2285)

### CODE REVIEW

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2285)* status: all files reviewed, 1 unresolved discussion (waiting on @cphelefu)

___
*[`packages/geoview-core/src/ui/select/select.tsx` line 48 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2285#-O-pum-vAFtHF0gv-ZRb:-O-pum-w1E6hKZIO1qk2:b-upydjp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1e51cf2e0c8bc2fa760138888a1e0c7023f39bd2/packages/geoview-core/src/ui/select/select.tsx#L48)):*
> ```XML
>   const sxClasses = getSxClasses(theme);
> 
>   const mapId = useGeoViewMapId();
> ```

We shouldn't use 'map related' contexts as part of UI components which are meant to be reusable and eventually even detached in standalone component.
Here, the 'mapElem' (or container to use the generic term) could it be passed as param to the UI component instead of automatically retrived using 'document' and a 'must know' 'shell-mapId' key?

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2285)* status: all files reviewed, 2 unresolved discussions (waiting on @cphelefu)

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2285)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @kaminderpal)

___
*[`packages/geoview-core/src/ui/select/select.tsx` line 48 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2285#-O-pum-vAFtHF0gv-ZRb:-O0Euj5h2pGbQlAjM3cE:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/57df70352f7c5295077801a74eebd6e0b26fc3db/packages/geoview-core/src/ui/select/select.tsx#L48)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

We shouldn't use 'map related' contexts as part of UI components which are meant to be reusable and eventually even detached in standalone component.
Here, the 'mapElem' (or container to use the generic term) could it be passed as param to the UI component instead of automatically retrived using 'document' and a 'must know' 'shell-mapId' key?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/select/select.tsx` line 55 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2285#-O0ELecH3pYwrpy-MimC:-O0Eujx97tchSFaHHwU1:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6ba4c6b7d3e43cb40dbacbc96eb625b484229733/packages/geoview-core/src/ui/select/select.tsx#L55)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

can u convert MenuProps={{ container: container }} to
</blockquote></details>

Done.

**Review by kaminderpal — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2285#-:-O0F0XOT0qqOYygYKScq:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan)

**Pull request merged**
