### PR TITLE
fix(guide): Clean inconsisties and repair added icon

### LINKED ISSUE #2193: [UPDATE] Update Guide Doc
Review for guide highlighted some problems..

GeoView Guide Validation

I recommend using a single icon for the guide. Currently there’s the graduate hat - less common - and the question mark (?) – universal. I would keep the latter.
 

**Layers Tab Guide**
View submenu:
“submenu” should be a single word here:
 

Missing capital “L” for “layers”:
 

What is the proper way to write “sub-layer”? With a hyphen, a space or is it a single word? Both cases are used:
 

I don’t think “Categories” is the proper term:  

In the layers list, the 
word “items” is used, that’s better, I think. “Classification” and “classes” could be an alterative as well.
 

Add submenu:
I think these two terms are inverted:
 

I think this verb is incorrectly conjugated:
 

Sort submenu:
The drag and drop does not work, this whole sentence has to be deleted:  

Remove submenu:
“Tab” or “submenu”? I think it should be the “Remove” submenu which can be found within the “Layers” tab.
 

**Details Tab Guide**
The following are missing: colon (:) after “Note” and “a” should be capitalized:
 

Same thing under the “Chart” section:
 

The right arrow icon is missing here:
 

**Data Table Tab Guide**
 
It seems the “Details” column is always there as well:
 

Missing a capital “S” to “some”:
 

Not sure what this is, remove

**Guide Tab**
“Footer Panel” section: **NEED to be Panel and inside we need to specify it can be panel / footer**
This information needs clarification: 
“The Footer Panel can be expanded or collapsed by clicking on a tab in the Footer Panel menu bar (collapse by clicking active tab).”
At first, I did not find any specific “tab” to collapse the footer panel. I recommend putting more emphasis on the parenthesis portion of the sentence, like this:

“The Footer Panel can be expanded or collapsed by clicking on a tab in the Footer Panel menu bar. To collapse the panel, simply click again on the active tab (Legend, Layers, Details or Guide).”

Under the “Add” section, I think “closes” is incorrectly conjugated and there are weird stuff as the end of two lines (in green):
 

I think the information regarding the “Sort” and “Remove” sections was not copied from the  “Layers” tab guide.

Under the “Details” category, the following are missing : colon (:) after “Note” and “a” should be capitalized:
 

Missing a capital “S” to “some”:
 

Forgotten tag:
 

 “Load Times / Unanticipated Behaviour guide” section:
For consistency with text of other sections, “Note” should not be in bold here:

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #2193

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #2193 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Hosted, May 31th, 10h15: https://jolevesq.github.io/geoview/demos-navigator.html?config=./configs/navigator/06-basic-footer.json

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195)

### CODE REVIEW

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195)* status: all files reviewed, 12 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/locales/en/guide.md` line 24 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE6cH00rChVj6mHghu:-NzE6cH00rChVj6mHghv:bbwcx1f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L24)):*
> ```Markdown
> To reset the map orientation, click the reset rotation arrow located at the right side of the Map Information Bar at the bottom of the map.
> 
> _Note: The map **must be** focused for key binding to work._
> ```

This Note is just italic, some others are bold and italic (I think just italic looks better, and it allows for bolding individual segments)
___
*[`packages/geoview-core/public/locales/en/guide.md` line 56 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE4uPI1nnaklmSJ0NR:-NzE4uPI1nnaklmSJ0NS:bh55hnh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L56)):*
> ```Markdown
> Press **CTRL** and **Q** to exit keyboard navigation.
> 
> _Note: The map **must be** focused for key binding to work. The map has focus when the crosshairs marker is present._
> ```

Italic note
___
*[`packages/geoview-core/public/locales/en/guide.md` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE1s654DyfHVK7Ay1Q:-NzE1s654DyfHVK7Ay1R:b8k329y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L60)):*
> ```Markdown
> **Accessibility**
> 
> This page is WCAG 2.0 AA compliant.
> ```

Should it say "This map" instead of "This page" as we have no idea what's on the rest of the page?
___
*[`packages/geoview-core/public/locales/en/guide.md` line 82 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE2FZDBwYiV7lJCjLT:-NzE2FZDBwYiV7lJCjLU:btk1jjz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L82)):*
> ```Markdown
> =1!sidebar=
> 
> # App Bar
> ```

I think that "Side Bar" is much more descriptive. App bar could be anywhere, and we use footer bar for the lower one which seems to align.
___
*[`packages/geoview-core/public/locales/en/guide.md` line 181 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE36H4-hATPI8H9PQz:-NzE36H55elUZBao9v6Q:b-5t2gus) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L181)):*
> ```Markdown
> _Depending on viewer configuration some tabs may not be available_
> 
> **_Note: Some tabs in the Footer Bar are also available as tools in the Side Bar, such as Legend or Details. A tool opened from the Side Bar is displayed on the map, in a condensed 'mobile' view (single column). The same tab opened in the Footer Bar is displayed below the map in a fully expanded view._**
> ```

Side Bar used here, should follow above name (App Bar) or change above. 
Also bold and italic note
___
*[`packages/geoview-core/public/locales/en/guide.md` line 241 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE48Sh-W-F7kPqchpS:-NzE48Sh-W-F7kPqchpT:b-sji8mx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L241)):*
> ```Markdown
> | Vector tiles layer | WFS                   |
> 
> _Note: If a layer fails to load correctly it will be identified by an error notice in the notifications tool on the **Side Bar**. Instead of the standard layer actions you can select to either reload the layer (this is particularly helpful if there is a temporary network connectivity issue) or remove the layer. If a layer is removed it will be taken out of the layer selector completely._
> ```

Side Bar again
Italic note
___
*[`packages/geoview-core/public/locales/en/guide.md` line 249 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE73Rz4muaWP4hU2ZJ:-NzE73Rz4muaWP4hU2ZK:bh55hnh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L249)):*
> ```Markdown
> Click a layer in the left section of the layers view tab, and the layer settings are displayed in right section.
> 
> _Note: Some settings may not be available depending on various factors such as layer type or configuration._
> ```

Italic note
___
*[`packages/geoview-core/public/locales/en/guide.md` line 304 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE7EwCBwSdScpDYKai:-NzE7EwCBwSdScpDYKaj:b-mqvbvh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L304)):*
> ```Markdown
> The **Details** tab has two sections. The available layers for the map are listed in the left section, and the feature details for each layer are displayed in the right section.
> 
> _**Note: A feature on the map must be selected to enable the layer in the list. Otherwise layers are disabled (greyed out).**_
> ```

Bold and italic note
___
*[`packages/geoview-core/public/locales/en/guide.md` line 327 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE7IOL2-p0NfK30SAR:-NzE7IOL2-p0NfK30SAS:bh55hnh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L327)):*
> ```Markdown
> The **Data Table** controls are shown in the upper right section of the layer data panel.
> 
> _Note: Some options may not be available or are preselected depending on various factors._
> ```

Italic note
___
*[`packages/geoview-core/public/locales/en/guide.md` line 425 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE6MfiApD4wDjlYfbD:-NzE6MfiApD4wDjlYfbE:b-mqvbvh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L425)):*
> ```Markdown
> The Chart tab on the Footer Bar has two sections. Layers with a chart are listed in the left section. Select a feature on the map to display its chart in the right section.
> 
> _**Note: A feature on the map must be selected to enable the layer in the list. Otherwise layers are disabled (greyed out).**_
> ```

Bold and italic note
___
*[`packages/geoview-core/public/locales/en/guide.md` line 460 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE6USj5AiLY_cnI8q_:-NzE6USj5AiLY_cnI8qa:bh55hnh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L460)):*
> ```Markdown
> Unanticipated behaviour may occur if any map interactions occur before data is fully loaded. Please allow the map to load completely before triggering any map functions.
> 
> _Note: If the loading spinner is visible for a layer, please wait for it to disappear before triggering any function on the map._
> ```

Italic note
___
*[`packages/geoview-core/public/locales/fr/guide.md` line 58 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE7w68E5ponr6lwVV-:-NzE7w68E5ponr6lwVV0:b-8gu3od) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/fr/guide.md#L58)):*
> ```Markdown
> # Accessibility
> 
> This page is not fully WCAG 2.0 AA compliant.
> ```

This file has not been updated the same as the english. Recopy/paste after changes?

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195)* status: 12 of 15 files reviewed, 12 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/public/locales/en/guide.md` line 24 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE6cH00rChVj6mHghu:-NzEg1pkDUc94pL3bnJZ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L24)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

This Note is just italic, some others are bold and italic (I think just italic looks better, and it allows for bolding individual segments)
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/locales/en/guide.md` line 56 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE4uPI1nnaklmSJ0NR:-NzEg2JgBHl3Ee8EdCG2:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L56)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Italic note
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/locales/en/guide.md` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE1s654DyfHVK7Ay1Q:-NzEg8lgDb6s0qIShwZ_:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L60)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Should it say "This map" instead of "This page" as we have no idea what's on the rest of the page?
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/locales/en/guide.md` line 82 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE2FZDBwYiV7lJCjLT:-NzEgNJ--ac6cFSpHGuk:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L82)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

I think that "Side Bar" is much more descriptive. App bar could be anywhere, and we use footer bar for the lower one which seems to align.
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/locales/en/guide.md` line 181 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE36H4-hATPI8H9PQz:-NzEgWD59OHT0jABepkb:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L181)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Side Bar used here, should follow above name (App Bar) or change above. 
Also bold and italic note
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/locales/en/guide.md` line 241 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE48Sh-W-F7kPqchpS:-NzEgWbsAgTs_2pqLBVu:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L241)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Side Bar again
Italic note
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/locales/en/guide.md` line 249 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE73Rz4muaWP4hU2ZJ:-NzEglOs5cGpH7Ih3Q_n:b-25ctz7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L249)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Italic note
</blockquote></details>

This one is already just Italic
___
*[`packages/geoview-core/public/locales/en/guide.md` line 304 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE7EwCBwSdScpDYKai:-NzEgm9z7K4rl7kI4ZJA:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L304)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Bold and italic note
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/locales/en/guide.md` line 327 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE7IOL2-p0NfK30SAR:-NzEh08l-gd3CCVCdeRK:b-25ctz7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L327)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Italic note
</blockquote></details>

This one is already just Italic
___
*[`packages/geoview-core/public/locales/en/guide.md` line 425 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE6MfiApD4wDjlYfbD:-NzEh2LNC8B3BwYYtGDr:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L425)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Bold and italic note
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/locales/en/guide.md` line 460 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE6USj5AiLY_cnI8q_:-NzEhFgPBuZuTWd3cxgZ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/en/guide.md#L460)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Italic note
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/locales/fr/guide.md` line 58 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195#-NzE7w68E5ponr6lwVV-:-NzEhGgIAaLmLHwwusAy:bbhn7lc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8088df277262f62187c6128ef75073132d135ee5/packages/geoview-core/public/locales/fr/guide.md#L58)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

This file has not been updated the same as the english. Recopy/paste after changes?
</blockquote></details>

I will update once en  is good

**Review by DamonU2 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2195)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Comment by jolevesq** [comment]
Branch and repo corrupted, will redo

**Pull request closed without merging**
