### PR TITLE
Separate_Feature_Info_By_Categories

### LINKED ISSUE #1904: [REFACTOR] Separate Feature Info By Categories
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

As a developer, I would like to have different layerSet for the 'get feature info', 'hover feature info' and 'get all feature info'

### Implementation (back end)

We need to separathe these three categories because the do not always share teh same caracteristiques. For example, a WMS service can use the 'get feature info' but it can't use the 'get all feature info',

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

The FeatureInfoLayerSet has been splitted into three new layerSets: HoverFeatureInfoLayerSet, AllFeatureInfoLayerSet and FeatureInfoLayerSet.

Fixes #1904 Separate_Feature_Info_By_Categories

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using the Chrome Devtools and the layer's template.

__Deploy URL__: https://ychoquet.github.io/GeoView/index.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 74 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906)* status: 1 of 74 files reviewed, 1 unresolved discussion (waiting on @ychoquet)

___
*[`packages/geoview-core/public/templates/raw-feature-info.html` line 493 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUuf9P6f4rzsjopNZW:-NsUuf9P6f4rzsjopNZX:bs3j1ee) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/public/templates/raw-feature-info.html#L493)):*
> ```HTML
>             cgpv.api.maps['mapWM1'].layer.hoverFeatureInfoLayerSet.isHoverListenerEnabled,
>             cgpv.api.maps['mapWM1'].layer.hoverFeatureInfoLayerSet.disableHoverListener,
>             cgpv.api.maps['mapWM1'].layer.hoverFeatureInfoLayerSet.enableHoverListener,
> ```

Hover listener should return the values in same order as layer list. So it display the layer that is on the top.

Hover should only return the canvas (symbiology) and the display name

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 74 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906)* status: 2 of 74 files reviewed, 2 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 143 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUxVlHBz-WVSzf8aaA:-NsUxVlHBz-WVSzf8aaB:bewkntl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L143)):*
> ```XML
>       const layerConfig = api.maps[mapId].layer.registeredLayers[entryLayerPath] as TypeLayerEntryConfig;
>       let entryIndex = existingEntries.findIndex((entry) => entry.layerPath === entryLayerPath);
>       if (layerEntryIsGroupLayer(layerConfig as Exclude<TypeLayerEntryConfig, GeoCoreLayerEntryConfig>)) {
> ```

Why do we have the excludes?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 74 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906)* status: 5 of 74 files reviewed, 3 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/core/app-start.tsx` line 72 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUyHL_8VmgM46jkBIs:-NsUyHL_8VmgM46jkBIt:b-wdgvh0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/src/core/app-start.tsx#L72)):*
> ```XML
>     //! call layer sets creation here instead of map event processor because the store map event processor
>     //! is not created yet
>     // TODO YC:delete this line = "    api.getFeatureInfoLayerSet(mapId);"
> ```

If not needed anymore here we can delete the lines

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 4 of 74 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906)* status: 9 of 74 files reviewed, 6 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx` line 93 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUyOPb8yW734LovXnT:-NsUyOPb8yW734LovXnU:btuj2hx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx#L93)):*
> ```XML
>   };
> 
>   const allQueriesDoneListenerFunciton = (payload: PayloadBaseClass) => {
> ```

Typo funciton
___
*[`packages/geoview-core/src/core/components/layers/hooks/helpers.ts` line 165 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUyYbW-a-28psantJW:-NsUyYbW-a-28psantJX:ba8486c) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/src/core/components/layers/hooks/helpers.ts#L165)):*
> ```XML
> 
>     const legendInfo = api.maps[mapId].layer.legendsLayerSet.resultSet;
>     // console.log('I got here ', legendInfo, _.keys(legendInfo));
> ```

Dead console log
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUygaq3HvZVQSr5EpQ:-NsUygaq3HvZVQSr5EpR:b-u5vyya) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L60)):*
> ```XML
> import { EsriImageLayerEntryConfig } from '@/core/utils/config/validation-classes/raster-validation-classes/esri-image-layer-entry-config';
> import { OgcWmsLayerEntryConfig } from '@/core/utils/config/validation-classes/raster-validation-classes/ogc-wms-layer-entry-config';
> import { GeoCoreLayerEntryConfig } from '@/core/utils/config/validation-classes/geocore-layer-entry-config';
> ```

Because geocore is not really a layer type do we want to remove it from this folder and handle in another section. Geocore is a pre process before validation to crate the config snippet from geocore api response

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 41 of 74 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906)* status: 49 of 74 files reviewed, 7 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/geo/utils/legends-layer-set.ts` line 12 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsV0H9uA3gWYE7Up--_:-NsV0H9uA3gWYE7Up--a:b75409q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/src/geo/utils/legends-layer-set.ts#L12)):*
> ```XML
>   payloadIsLayerSetUpdated,
> } from '@/api/events/payloads';
> // import { api } from '@/app';
> ```

Do we need dead code?

**Review by DamonU2 — APPROVED** [review]
> Reviewed 25 of 74 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906)* status: all files reviewed, 7 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/public/templates/raw-feature-info.html` line 493 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUuf9P6f4rzsjopNZW:-NsV1yYOAYL0wcto5hZx:b-9vwud6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/public/templates/raw-feature-info.html#L493)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Hover listener should return the values in same order as layer list. So it display the layer that is on the top.

Hover should only return the canvas (symbiology) and the display name
</blockquote></details>

If we do it by layer order, do we have any way to tell how far the feature is from the clicked point? If it's just layer order, we could get a feature that is not right at the click point instead of the one clicked on, because it is higher.

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906)* status: all files reviewed, 6 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/raw-feature-info.html` line 493 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUuf9P6f4rzsjopNZW:-NsWNy213CA6o805KNnu:b-p6e8fq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/public/templates/raw-feature-info.html#L493)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

If we do it by layer order, do we have any way to tell how far the feature is from the clicked point? If it's just layer order, we could get a feature that is not right at the click point instead of the one clicked on, because it is higher.
</blockquote></details>

So far, none of the layerSets change the layer order to follow what users see and do on the UI side. The work is done in the store and I think it's OK that way. I agree that the hover doesn't need to return the whole record. The display field and symbology are enough. Up to a certain point, I'm beginning to think that layer sets are unnecessary. If we have to make them identical to what we have in the store, I'd say we're duplicating code. Theoretically, the layersets already have a delete function and it's them that should signal to the store that a layer has been deleted. However, we've coded an independent delete layer in the store and the result is that we now have to remember that deleting a layer has two different sections of code to accomplish the delete task. I think we should be more cautious when coding solutions for our issues.

Concerning the distance between the element and the clicked position, I'd say that if a user has selected a layer, they probably expect the hover functionality to return an element from that layer.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 143 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUxVlHBz-WVSzf8aaA:-NsWIpSkAmB3zzlPB2-_:b5tv0u8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L143)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why do we have the excludes?
</blockquote></details>

Can't explain why previous deployment of the viewer did not flag these lines as an error, but I had to exclude the geocore config from the TypeLayerEntryConfig because these lines appered as an error in the deploy I used when I started my developpements. Some of them can be reverted following the last rebase, but not all of them. Anyway, these exclude will disappear because the fact we have to use an exclude in some cases made us realize that we must remove geocore layers from the TypeLayerEntryConfig. This will be done in a next PR.
___
*[`packages/geoview-core/src/core/app-start.tsx` line 72 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUyHL_8VmgM46jkBIs:-NsWL5V5DyxPKUCR87Ho:bhofej8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/src/core/app-start.tsx#L72)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If not needed anymore here we can delete the lines
</blockquote></details>

Deleted
___
*[`packages/geoview-core/src/core/components/layers/hooks/helpers.ts` line 165 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUyYbW-a-28psantJW:-NsWMxeXAR3VVdG-C3pY:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/src/core/components/layers/hooks/helpers.ts#L165)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Dead console log
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUygaq3HvZVQSr5EpQ:-NsWN5NY3A5yAtarg_hT:b4o8q2r) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L60)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Because geocore is not really a layer type do we want to remove it from this folder and handle in another section. Geocore is a pre process before validation to crate the config snippet from geocore api response
</blockquote></details>

If not already done, we should create an issue to remove the geocore type from the typeLayerEntryConfig and the validation classes.
___
*[`packages/geoview-core/src/geo/utils/legends-layer-set.ts` line 12 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsV0H9uA3gWYE7Up--_:-NsWNhs94Jv_tP8yV0aH:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/src/geo/utils/legends-layer-set.ts#L12)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we need dead code?
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906)* status: 67 of 75 files reviewed, 4 unresolved discussions (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 143 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUxVlHBz-WVSzf8aaA:-NshP71mAL9Zbe_ubu0L:bt07bpt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L143)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Can't explain why previous deployment of the viewer did not flag these lines as an error, but I had to exclude the geocore config from the TypeLayerEntryConfig because these lines appered as an error in the deploy I used when I started my developpements. Some of them can be reverted following the last rebase, but not all of them. Anyway, these exclude will disappear because the fact we have to use an exclude in some cases made us realize that we must remove geocore layers from the TypeLayerEntryConfig. This will be done in a next PR.
</blockquote></details>

Definitly, geocore is not a type layer entry config... it is a pre step before we can add a layer (of supported layer type. Can you just create an issue for this
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUygaq3HvZVQSr5EpQ:-NshPqTeDfsRrJ3HOGXs:bklcugi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L60)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

If not already done, we should create an issue to remove the geocore type from the typeLayerEntryConfig and the validation classes.
</blockquote></details>

It is not done yet I think. Can you create one to so this should remove the exclude you had to use.

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906)* status: 67 of 75 files reviewed, 4 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/public/templates/raw-feature-info.html` line 493 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUuf9P6f4rzsjopNZW:-NshfJd_88uHg8u6847B:b-4dpdwo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/public/templates/raw-feature-info.html#L493)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Ok so let's clean the hover to return display name and symbology only. As for the info to display, it should be selected layer (if one or if there is something), if not layer order. It is weird to see info from a layer that is hidden under another. If we go with selectedlayerpath - layer order we can explain in the help.

As for removing the layer set, we should have the flag for hoverable in the store layers array to know if we query or not. For hover it may not be that important...
</blockquote></details>

The next step of this PR is to change the event calls to direct calls whenever possible. I can do this modification  in my next PR or this one. Which one do you prefer?
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 143 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUxVlHBz-WVSzf8aaA:-Nshewfy-cXN1sZ7oONH:b-t2sudq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L143)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Definitly, geocore is not a type layer entry config... it is a pre step before we can add a layer (of supported layer type. Can you just create an issue for this
</blockquote></details>

An issue already exists for this refactoring.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUygaq3HvZVQSr5EpQ:-Nshf7Zd6UJuJNhX6qNQ:b-fagvwv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L60)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It is not done yet I think. Can you create one to so this should remove the exclude you had to use.
</blockquote></details>

I search the zenhub and found an issue  this topic.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906)* status: 68 of 75 files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/public/templates/raw-feature-info.html` line 493 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUuf9P6f4rzsjopNZW:-NshiUnu-bCzSaeXogJD:bv33m0j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/public/templates/raw-feature-info.html#L493)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

The next step of this PR is to change the event calls to direct calls whenever possible. I can do this modification  in my next PR or this one. Which one do you prefer?
</blockquote></details>

May be better in this PR if it can be done quickly

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906)* status: 65 of 75 files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/public/templates/raw-feature-info.html` line 493 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-NsUuf9P6f4rzsjopNZW:-NsiiKLy0FirVDJmH2Lm:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daef74bb798aac054df0d6bbb673a5be43736df0/packages/geoview-core/public/templates/raw-feature-info.html#L493)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

May be better in this PR if it can be done quickly
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 15 of 74 files at r1, 5 of 12 files at r2, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906)* status: 73 of 75 files reviewed, 1 unresolved discussion (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 105 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-Nsj-HBt9E6mYvaveLia:-Nsj-HBt9E6mYvaveLib:b-legueg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b4d934877b883c3b246de1e68e174bf4e2fdb027/packages/geoview-core/src/geo/layer/layer.ts#L105)):*
> ```XML
>   constructor(mapId: string) {
>     this.mapId = mapId;
>     this.legendsLayerSet = api.getLegendsLayerSet(mapId);
> ```

Why layerSets are create by api function? Why they are note created by the layer class itself on the map element?

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906)* status: 72 of 75 files reviewed, 1 unresolved discussion (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 105 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906#-Nsj-HBt9E6mYvaveLia:-Nsj-brNEvpMQKHzJhzL:b-24olac) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b4d934877b883c3b246de1e68e174bf4e2fdb027/packages/geoview-core/src/geo/layer/layer.ts#L105)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why layerSets are create by api function? Why they are note created by the layer class itself on the map element?
</blockquote></details>

You are right, the layerSets creation should be placed in the layer class.  I try to create them there, but the viewer enter an infinit loop and crashes. I tryed to transform the class from static to non static, but it changes nothing. We need to investigate more to find what causes this bug. I've put a todo to keep track of this issue. I'll try to resolve it in my next Pr.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 12 files at r2, 1 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1906)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
