### PR TITLE
1177 swiper utilize layerset

### PR DESCRIPTION
**Pull request by DamonU2**
# Description

Swiper updated - now utilizes layerset and accounts for slow loading layers

Fixes # (1177)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested on package-swiper.html with all maps.

https://damonu2.github.io/geoview/package-swiper.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1297)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1297)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-swiper/package.json` line 14 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1297#-NeIW-hSA3Gh6hEMU0_4:-NeIW-hSA3Gh6hEMU0_5:b-ycytxk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bc98701a6a2cb70221fe610a106558bcda60c792/packages/geoview-swiper/package.json#L14)):*
> ```JSON
>   "dependencies": {
>     "react": "^18.2.0",
>     "react-dom": "^18.2.0",
> ```

Do we need in dependencies... are not using the one from the core
___
*[`packages/geoview-swiper/package.json` line 22 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1297#-NeIVtEP0M5poxuFEqNh:-NeIVtEP0M5poxuFEqNi:b-txgjeq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bc98701a6a2cb70221fe610a106558bcda60c792/packages/geoview-swiper/package.json#L22)):*
> ```JSON
>   "devDependencies": {
>     "@types/react": "^18.2.0",
>     "@types/react-dom": "^18.2.0",
> ```

Moving them will break alphabetical order

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1297)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-swiper/package.json` line 14 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1297#-NeIW-hSA3Gh6hEMU0_4:-NeiVqok0WUWzieU7WiN:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bc98701a6a2cb70221fe610a106558bcda60c792/packages/geoview-swiper/package.json#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we need in dependencies... are not using the one from the core
</blockquote></details>

Done.
___
*[`packages/geoview-swiper/package.json` line 22 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1297#-NeIVtEP0M5poxuFEqNh:-NeiVr3b8aiy0EU4Nxt_:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bc98701a6a2cb70221fe610a106558bcda60c792/packages/geoview-swiper/package.json#L22)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Moving them will break alphabetical order
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1297)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Review by jolevesq — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1297#-:-NeiWCqDEpMaBTPz37Rn:b-uwkowd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Review by jolevesq — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1297)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
