### PR TITLE
feat-fix(layers-event): Add getGeoJSON for vector layer, patch timing…

### LINKED ISSUE #2338: [FEATURE] Utility Conversion Function ol-geoJSON
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team, CHN

### User Story

As a developer, I would like to easily convert an ol vector source to a geoJSON

### Implementation UI

Add a utilities function in geo (or in abstract vector layer, who takes a ol vector source and return a proper formatted geoJSON. We should modify the data table export JSON button to reuse this function.

```
var format = new ol.format["GeoJSON"](); 
var geoJsonStr = format.writeFeatures(vectorSource.getFeatures(), { dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
```

### PR DESCRIPTION
**Pull request by jolevesq**
… issue with geoCoreLayer, add layerError event, add global  layerVisibility event

Closes #2338, #2376

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- utility function on vectorlayer to get geoJSON
- layerError event added
- Global  layerVisibility event Added
- Temporary fix with a timeout for layer geoCore because the mapInit is triggered before the geoviewLayers array is populated
Fixes #2338, #2376

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Hosted July 17th, 2h30:

https://canadian-geospatial-platform.github.io/geoview/public/esri-feature.html
In the console type and see the result
cgpv.api.maps['LYR1'].layer.getGeoviewLayers()[0].getFeaturesAsGeoJSON('uniqueValueId/1')

https://jolevesq.github.io/geoview/demo-function-event.html
in the notifiaction, new event for layerError and one for visibility (use the GeoJSON layer)

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2382)

### CODE REVIEW

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2382)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 518 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2382#-O21--tG4HFjombCKlPg:-O21--tG4HFjombCKlPh:bu98hf4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2a9718735ca1d639d63c93cebd679461ed72dcb4/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L518)):*
> ```XML
>   getFeaturesAsGeoJSON(layerPath: string): JSON {
>     // Get map projection
>     const mapProjection: ProjectionLike = MapEventProcessor.getMapViewer(this.mapId).getProjection().getCode();
> ```

FYI
Alternatively can call `this.getMapViewer()` as well if preferred.
___
*[`packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts` line 594 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2382#-O21-zKPCnBsu72n_Zjm:-O21-zKQ4fwml_eFLdBa:buuk7jb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2a9718735ca1d639d63c93cebd679461ed72dcb4/packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts#L594)):*
> ```XML
>     const curVisible = this.getVisible();
>     this.getOLLayer().setVisible(layerVisibility);
>     if (layerVisibility !== curVisible) this.#emitVisibleChanged({ layerPath: this.getLayerPath(), visible: layerVisibility });
> ```

FYI
Here, the `sender` parameter, when handling the event in the handler method, would be able to do something like `sender.getLayerPath()` if we want to know which layer has raised the visible changed.
There's no harm in providing it, explicitly, via the event as well if we feel it's necessary. It's just growing the event payload.
___
*[`packages/geoview-core/src/geo/layer/gv-layers/vector/abstract-gv-vector.ts` line 298 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2382#-O21-jxmBZi78HfpjSG8:-O21-jxmBZi78HfpjSG9:b-ma2jzp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2a9718735ca1d639d63c93cebd679461ed72dcb4/packages/geoview-core/src/geo/layer/gv-layers/vector/abstract-gv-vector.ts#L298)):*
> ```XML
>   getFeaturesAsGeoJSON(): JSON {
>     // Get map projection
>     const mapProjection: ProjectionLike = MapEventProcessor.getMapViewer(this.getMapId()).getProjection().getCode();
> ```

FYI
Same comment as before

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2382)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 557 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2382#-O210JFB7joaoxIPgIT0:-O210JFC9V0OemJoLaN-:bz65eff) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2a9718735ca1d639d63c93cebd679461ed72dcb4/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L557)):*
> ```XML
>   }
> 
>   static setOrToggleMapLayerVisibilityState(mapId: string, curOrderedLayerInfo: TypeOrderedLayerInfo[]): void {
> ```

Should this be something more generic like setOrderedLayerInfoWithNoOrderChange? It will probably be used for other purposes going forward.
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1747 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2382#-O2107R33xtsnWnT20Gi:-O2107R33xtsnWnT20Gj:ba5lqt1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2a9718735ca1d639d63c93cebd679461ed72dcb4/packages/geoview-core/src/geo/layer/layer.ts#L1747)):*
> ```XML
>  */
> export type LayerRemovedEvent = {
>   // The added layer
> ```

I think I did this, but added should be removed in this comment

**Review by DamonU2 — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2382)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 10 files at r1, 3 of 6 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2382)* status: all files reviewed, 2 unresolved discussions (waiting on @DamonU2)

**Pull request merged**
