### PR TITLE
[FIX] Details-panel highlighting and more things

### PR DESCRIPTION
**Pull request by Alex-NRCan**
`details-panel` highlight fixing when selecting different layers and browsing features.
`click-marker` not touching the feature highlights logic anymore.
Fix for FooterBar collapsing not working. **NEED HELP TESTING MOBILE MODE.**
Some logging tweaking
Layer opacity in the `layers-list`
Comments integration
Details uncollapse on click on map
Details Feature info : the highlight checkbox is disabled when the feature has no geometry
Click-marker doesn't hide automatically when clicking on a feature anymore
Added logs and cleanup

Fixes: #1764 and #1769

**In draft, because if #1749 gets merged before this one, I can add another small thing in this one. Update: 1749 got merged, this PR has been updated with it.**

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Hosted here as of Feb. 8th, 18h30 EST : https://alex-nrcan.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1761)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1761)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts` line 402 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1761#-Nq3Kigp8IdMWfAxlo9X:-Nq3Kigp8IdMWfAxlo9Y:bv92g8v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/75383a3088609711261dd8c6f52b81dfd371f6a5/packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts#L402)):*
> ```XML
>     } catch (error: unknown) {
>       // Log
>       logger.logError('Failed to get the GV layer from UUI', requestUrl, error);
> ```

We should put explicit naming I think GeoView and uuid-config

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1761)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts` line 402 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1761#-Nq3Kigp8IdMWfAxlo9X:-Nq59O0U7nLhuXgdXWuA:bxzfzcy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/75383a3088609711261dd8c6f52b81dfd371f6a5/packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts#L402)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should put explicit naming I think GeoView and uuid-config
</blockquote></details>

I've put the `GeoView` mention. However, inside this function, all I have is the `requestUrl`. The UUID is higher in the call stack. If we want it, we'd have to move the try/catch higher and I wasn't sure I wanted to do that kind of change, not when I know Yves was working on some fixes around those files.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1761)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 93 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1761#-Nq7xUAnC66O6GXAgXKB:-Nq7xUAnC66O6GXAgXKC:bmg6uog) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e3fec2e760b28c6d6ffdbacc1aba2383fe701bec/packages/geoview-core/src/core/components/details/details-panel.tsx#L93)):*
> ```XML
>    * Helper function to clear the highlighed features when they are not checked
>    *
>    * @param {TypeFeatureInfoEntry} feature The feature to check
> ```

Seems to be wrong type.... should it be TypeArrayOf....

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1761)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 93 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1761#-Nq7xUAnC66O6GXAgXKB:-Nq7ywPP-lBqvgQ3EiXw:b-7692gt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e3fec2e760b28c6d6ffdbacc1aba2383fe701bec/packages/geoview-core/src/core/components/details/details-panel.tsx#L93)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Seems to be wrong type.... should it be TypeArrayOf....
</blockquote></details>

Bien vu, je l'ai changé, sera repoussé bientôt.

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 4 of 7 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1761)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, 9 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1761)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Pull request merged**
