### PR TITLE
refactor(app-start) Make maps under one root component

### LINKED ISSUE #126: Modify app-start to make maps be under one root component
Currently each map is it's own parent component, modify app-start and map.tsx to make maps become children under one root component

### PR DESCRIPTION
**Pull request by yass0016**
Closes #126

## Checklist

* [ ] Commit message follow the guidelines
* [ ] PR targets the correct release version
* [ ] Deploy has been done
* [ ] Check styling
* [ ] _Help files and documentation have been updated_
* [ ] ~Release notes have been updated~

## What's to look for styling
* Use camelCase for identifier names (variables and functions)
* Use PascalCase for type names
* Do not use "I" as a prefix for interface names
* Do not export types/functions unless you need to share it across multiple components
* All names start with a letter
* Always put spaces around operators ( = + - * / ), and after colon:
* Remove all trailing white spaces
* Look for bad indentation
* Carriage return are mandatory
  * Before comments
  * Before if condition
  * After if condition
  * Before properties
  * Before classes
  * Before functions

The use of Prettier Visual Studio Code extension let's you format automatically your code to remove most of the styling issues like white space and indentation.

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/127)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/127)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @yass0016)

___
*[src/app.tsx, line 43 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/127#-MUUTgw8CBSosBsc004v:-MUUTgw93u02uYgQJTvo:b-gz8cki) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/cb3fccc413e929db2553287bd991a4c0c8f23d28/src/app.tsx#L43)):*
> ```XML
>     if (callback) api.readyCallback = callback;
> 
>     ReactDOM.render(<AppStart html={html} />, document.getElementById('root'));
> ```

Do you know if it can create side effect to remove innerHTML and push it back wrapped
___
*[src/components/map/map.tsx, line 46 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/127#-MUUXJGcCHEqJGVJoWOY:-MUUXJGcCHEqJGVJoWOZ:b-cjgtse) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/cb3fccc413e929db2553287bd991a4c0c8f23d28/src/components/map/map.tsx#L46)):*
> ```XML
> }
> 
> export function Map(props: MapProps): JSX.Element {
> ```

Will you remove not needed stuff like duplicate theme provider and cssbaseline?

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/127)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[src/app.tsx, line 43 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/127#-MUUTgw8CBSosBsc004v:-MUUYZg00DWqWfDhpEfi:bhq1fwu) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/cb3fccc413e929db2553287bd991a4c0c8f23d28/src/app.tsx#L43)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do you know if it can create side effect to remove innerHTML and push it back wrapped
</blockquote></details>

I don't think it should create side effects, the module I used `html-react-parser` will retain all the html that was before removing it, it will still run the scripts in the script tag. We can tell from the sample showcase to create panels, we can still click the add panel buttons. Later on we should have some sort of loading icon so even if it takes milliseconds to remove then render back the content it should show a loading progress
___
*[src/components/map/map.tsx, line 46 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/127#-MUUXJGcCHEqJGVJoWOY:-MUUZ6cH4v0y03FtDUKI:bb6un1j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/cb3fccc413e929db2553287bd991a4c0c8f23d28/src/components/map/map.tsx#L46)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Will you remove not needed stuff like duplicate theme provider and cssbaseline?
</blockquote></details>

Done

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/127)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @yass0016)

___
*[src/app.tsx, line 43 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/127#-MUUTgw8CBSosBsc004v:-MUUd7w674jg_4F1k6zE:b-dd3fcg) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/cb3fccc413e929db2553287bd991a4c0c8f23d28/src/app.tsx#L43)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

I don't think it should create side effects, the module I used `html-react-parser` will retain all the html that was before removing it, it will still run the scripts in the script tag. We can tell from the sample showcase to create panels, we can still click the add panel buttons. Later on we should have some sort of loading icon so even if it takes milliseconds to remove then render back the content it should show a loading progress
</blockquote></details>

Can you create an issue for loading the icon?

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/127)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @yass0016)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/127)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
