### PR TITLE
refactor(utilities): clean utilities structure

### LINKED ISSUE #1964: {REFACTOR} Clean Utilities
There is 2 utilities section

api.utilities

api.maps[mapId].utilities

There is stand alone utilities that does not need a map to work and there is some that needs a map. For the moment they are all over the place... we need to move them in their proper place.

### PR DESCRIPTION
**Pull request by jolevesq**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1964 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://jolevesq.github.io/geoview/raw-feature-info.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1981)

### CODE REVIEW

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 28 of 80 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1981)* status: 28 of 80 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 177 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1981#-NuZDQQP-e0Jx1AzesTl:-NuZDQQQ2thOYa8Ghfu1:bk04191) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a9f4265d37536f753322399d72e4a4923505f03/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L177)):*
> ```XML
>   const emitErrorEmpty = (textField: string) => {
>     setIsLoading(false);
>     api.maps[mapId].notifications.showError(`${textField} ${t('layers.errorEmpty')}`, [], false);
> ```

We still have a lot of dependency on the MapViewer in the UI components. Are we going to get rid of those eventually to also be using "EventProcessors"?

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1981)* status: 28 of 80 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/utils/config/reader/div-config-reader.ts` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1981#-NuZEuiS966kErlUbSal:-NuZEuiS966kErlUbSam:bm74mvy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a9f4265d37536f753322399d72e4a4923505f03/packages/geoview-core/src/core/utils/config/reader/div-config-reader.ts#L78)):*
> ```XML
>             logger.logError('Failed to get the GeoView layers from url keys', mapElement.getAttribute('data-geocore-keys'), error);
>             // TODO: config should not push message to map... only to console and as return value.. map will be responsible to throw notification
>             api.maps[mapId].notifications.showError('validation.layer.loadfailed', [error as TypeJsonValue, mapId]);
> ```

Same comment with code in ts. Here a div-config-reader asks for a MapViewer. It should probably throw an error higher instead of coupling it with the MapViewer?

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 1 of 80 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1981)* status: 47 of 88 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1981)* status: 47 of 88 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/core/utils/notifications.ts` line 230 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1981#-NuZLipT1r-vfDI-DRpv:-NuZNIiKAIziYI-V4Iuw:b-rnhfsw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4b29ccc18bc2215fc9a7c6c88f2f16fcc3cced73/packages/geoview-core/src/core/utils/notifications.ts#L230)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Probably not necessary to export the delegate?
</blockquote></details>

Needed it in the shell.tsx

**Pull request merged**
