### PR TITLE
core(dependencies): Upgrade to OL 10.1 and solve issues

### LINKED ISSUE #2451: Migration to OL version 10.1

### PR DESCRIPTION
**Pull request by jolevesq**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #2451, #2139, #2435, #2395, #2455 PR

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Hosted Septmeber 6th, 4pm

#2455
https://jolevesq.github.io/geoview/demo-geojson-inject.html
Test click on details see panel updating

#2435
https://jolevesq.github.io/geoview/demos-navigator.html
Reload the map many time and see there is no more bad height

#2139
https://jolevesq.github.io/geoview/demos-navigator.html?config=./configs/navigator/16-esri-dynamic.json
cgpv.api.maps['sandboxMap'].layer.getGeoviewLayers()[1].getTemporalDimension('esriFeatureLYR4/0')

Fixed  layerDef for historical flood on map 2
https://jolevesq.github.io/geoview/esri-dynamic.html

Fixed pygeoapi proecess not appearing on map
https://jolevesq.github.io/geoview/pygeoapi-processes.html

Fixed Swiper for geocore layer, remove rcs. and .en added by the layer creation
https://jolevesq.github.io/geoview/package-swiper.html

Fixed name field value for details open by data table. Previously it was name field, now it is the name field value
https://jolevesq.github.io/geoview/demos-navigator.html?config=./configs/navigator/16-esri-dynamic.json
- click on data table and select first layer
- click on details and see value in modal

Fixed zoomToLayerIds by listening on layers loaded event
https://jolevesq.github.io/geoview/demos-navigator.html?config=./configs/navigator/05-zoom-layer.json

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2460)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
> Reviewed 27 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2460)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 638 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2460#-O67s7zr3RFROeZZMkHj:-O67s7zr3RFROeZZMkHk:b-hih2k2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7ecf81d42a49bd5394584303818072460994940a/packages/geoview-core/src/geo/map/map-viewer.ts#L638)):*
> ```XML
>           // Check if all registered layers are registered
>           const [allGood] = this.layer.checkLayerStatus('loaded', this.mapFeaturesConfig.map.listOfGeoviewLayerConfig, (geoviewLayer) => {
>             logger.logTraceDetailed('checkMapReady - 1 - waiting on layer registration...', geoviewLayer.geoviewLayerId);
> ```

Loaded instead of registration

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2460)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 638 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2460#-O67s7zr3RFROeZZMkHj:-O6MTgxx9jrU-6yFFpxg:bb6ywmx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7ecf81d42a49bd5394584303818072460994940a/packages/geoview-core/src/geo/map/map-viewer.ts#L638)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Loaded instead of registration
</blockquote></details>

LGTM
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 1229 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2460#-O6MQ13P-m1Tm1uKNIfw:-O6MQ13P-m1Tm1uKNIfx:byykouu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7ecf81d42a49bd5394584303818072460994940a/packages/geoview-core/src/geo/map/map-viewer.ts#L1229)):*
> ```XML
> 
>     // Remove the map
>     const mapDiv = await this.remove(false);
> ```

Type  : This is important ***because*** ...  and map will take ***its*** height.

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 26 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2460)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 638 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2460#-O67s7zr3RFROeZZMkHj:-O6XqqkxBpmfO9igsJEI:b-ucx0sf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7ecf81d42a49bd5394584303818072460994940a/packages/geoview-core/src/geo/map/map-viewer.ts#L638)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

LGTM
</blockquote></details>

I'm a bit out of the loop on this change requirement, but if this new interval is because we only want the `this.layer.getExtentOfMultipleLayers` line to happen when all layers are 'loaded', I'd remove the setInterval from here and I'd put the line of code in the function `#checkMapLayersLoaded`. The latter already has an interval which "resolves" when all layers are 'loaded'.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2460)* status: 21 of 31 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 638 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2460#-O67s7zr3RFROeZZMkHj:-O6aWJnv8vadozPOHBq0:b-6zu7ai) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7ecf81d42a49bd5394584303818072460994940a/packages/geoview-core/src/geo/map/map-viewer.ts#L638)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I'm a bit out of the loop on this change requirement, but if this new interval is because we only want the `this.layer.getExtentOfMultipleLayers` line to happen when all layers are 'loaded', I'd remove the setInterval from here and I'd put the line of code in the function `#checkMapLayersLoaded`. The latter already has an interval which "resolves" when all layers are 'loaded'.
</blockquote></details>

Good idea, will try
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 1229 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2460#-O6MQ13P-m1Tm1uKNIfw:-O6aWNGWCza666VVRKFJ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7ecf81d42a49bd5394584303818072460994940a/packages/geoview-core/src/geo/map/map-viewer.ts#L1229)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Type  : This is important ***because*** ...  and map will take ***its*** height.
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2460)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

**Pull request merged**
