### PR TITLE
935 components theme

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description

Update theme of the components when switch themes

Fixes # ([935](https://github.com/Canadian-Geospatial-Platform/geoview/issues/935))

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

tested manually

# Checklist:

- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/976)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
White theme should keep app bar black, it is the panel content who is white.
Text on details panel when light theme is not good.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/976#-:-NR8AtIkCTBRKReg4FTt:b7aj9ab)* status: all files reviewed, 1 unresolved discussion (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/ui/style/theme.tsx` line 346 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/976#-NR8BWrJ3JwTq3cqA0M7:-NR8BWrJ3JwTq3cqA0M8:b3of9mo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e3536183417a96b382dc2c8dffcd22597c0352fd/packages/geoview-core/src/ui/style/theme.tsx#L346)):*
> ```XML
>   },
>   appBar: {
>     background: '#fff',
> ```

Should always be black, it is the panel content who is suppose to be white.

**Review by kaminderpal — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/976#-:-NRB2K21AjFPzhUwnejB:bnfp4nl)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/ui/style/theme.tsx` line 346 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/976#-NR8BWrJ3JwTq3cqA0M7:-NRB2IJi5-vDjXPhicEK:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e3536183417a96b382dc2c8dffcd22597c0352fd/packages/geoview-core/src/ui/style/theme.tsx#L346)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should always be black, it is the panel content who is suppose to be white.
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r2, 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/976)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/ui/select/select.tsx` line 41 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/976#-NRIyZF73jXS6QvgxqbD:-NRIyZF73jXS6QvgxqbE:b3wndbk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cba9d070766aff3cceaad4a863d139ba6924a0f8/packages/geoview-core/src/ui/select/select.tsx#L41)):*
> ```XML
>       padding: '0 12px 0 8px',
>       '&[aria-hidden="true"]': {
>         border: `1px solid ${theme.palette.text.primary}`,
> ```

Why border has a property set to primary text. Should it be border primary. What will happen if we change text property, will it modify the border as well?

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/976)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Pull request merged**
