### PR TITLE
640-Three-bugs-correction

### PR DESCRIPTION
**Pull request by ychoquet**
Related issues:
637-Improve type guards robustness
638-Include default symbols in the geoview renderer
639-Correction of a bug in the CRS metadata inheritance

These bugs was discovered while working on issue 605-Esri-dynamic layer visibility.

- - -
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/640)

### CODE REVIEW

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/640)* status: 0 of 42 files reviewed, 2 unresolved discussions (waiting on @github-code-scanning[bot])

___
*[`packages/geoview-core/public/templates/layers.html` line 699 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/640#-NGoVBBKxcp6rzu1kKKT-r1-699:-NGrVYtM6eGSohxgyowr:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ab7bc7e98a784526f370b8a37f5014bd0683e0ba/packages/geoview-core/public/templates/layers.html#L699)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Incomplete string escaping or encoding

This replaces only the first occurrence of '>'.

[Show more details](https://github.com/Canadian-Geospatial-Platform/geoview/security/code-scanning/46)
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/test.html` line 98 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/640#-NGoVBBKxcp6rzu1kKKV-r1-98:-NGrV_8L6g4GkYyDjSiQ:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ab7bc7e98a784526f370b8a37f5014bd0683e0ba/packages/geoview-core/public/templates/test.html#L98)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Incomplete string escaping or encoding

This replaces only the first occurrence of '>'.

[Show more details](https://github.com/Canadian-Geospatial-Platform/geoview/security/code-scanning/48)
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 38 of 42 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/640)* status: all files reviewed, 4 unresolved discussions (waiting on @github-code-scanning[bot] and @ychoquet)

___
*[`packages/geoview-core/src/geo/renderer/geoview-renderer.ts` line 283 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/640#-NGvdfFU2hBnIz1rzHA2:-NGvdfFV35geDLG612tX:b-uech55) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0b87146c66b5fd26b87ca9c18a1703ab8b29e2c3/packages/geoview-core/src/geo/renderer/geoview-renderer.ts#L283)):*
> ```XML
>     drawingCanvas.height = this.LEGEND_CANVAS_HEIGHT;
>     const context = drawingCanvas.getContext('2d')!;
>     const gradient = context.createLinearGradient(0, drawingCanvas.height, drawingCanvas.width, 0);
> ```

Why do we have this? It is preferable to have the symbol on a white background.
___
*[`packages/geoview-core/src/geo/renderer/geoview-renderer.ts` line 349 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/640#-NGvdzjR3v3UuXXGkGU6:-NGvdzjR3v3UuXXGkGU7:bc2yepg) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0b87146c66b5fd26b87ca9c18a1703ab8b29e2c3/packages/geoview-core/src/geo/renderer/geoview-renderer.ts#L349)):*
> ```XML
>    * @param {TypeKindOfVectorSettings | undefined} defaultSettings The settings associated to simple styles or default style of
>    * unique value and class break styles. When this parameter is undefined, no defaultCanvas is created.
>    * @param {TypeUniqueValueStyleInfo[] | TypeClassBreakStyleInfo[] | undefined} arrayOfPointStyleConfig The array of point style
> ```

For unique value, it is not the array on canvas with only one element?

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/640)* status: all files reviewed, 4 unresolved discussions (waiting on @github-code-scanning[bot] and @jolevesq)

___
*[`packages/geoview-core/src/geo/renderer/geoview-renderer.ts` line 283 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/640#-NGvdfFU2hBnIz1rzHA2:-NGvwYvSCXJpiyQQrYmt:by1xrwy) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0b87146c66b5fd26b87ca9c18a1703ab8b29e2c3/packages/geoview-core/src/geo/renderer/geoview-renderer.ts#L283)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why do we have this? It is preferable to have the symbol on a white background.
</blockquote></details>

This change was made because I found a service with a legend element coded as a white line, which led me to believe that the code was wrong. Using this gradient background, we can now see white on white elements.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/640)* status: all files reviewed, 4 unresolved discussions (waiting on @github-code-scanning[bot] and @ychoquet)

___
*[`packages/geoview-core/src/geo/renderer/geoview-renderer.ts` line 283 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/640#-NGvdfFU2hBnIz1rzHA2:-NGvzVnD5YofvdbSS7i9:b-kos89d) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0b87146c66b5fd26b87ca9c18a1703ab8b29e2c3/packages/geoview-core/src/geo/renderer/geoview-renderer.ts#L283)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

This change was made because I found a service with a legend element coded as a white line, which led me to believe that the code was wrong. Using this gradient background, we can now see white on white elements.
</blockquote></details>

Can we test and apply gradiant only on white element?

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/640)* status: 0 of 60 files reviewed, 4 unresolved discussions (waiting on @github-code-scanning[bot] and @jolevesq)

___
*[`packages/geoview-core/src/geo/renderer/geoview-renderer.ts` line 283 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/640#-NGvdfFU2hBnIz1rzHA2:-NGw-33W1JRBAeeROo2c:b-qh391a) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0b87146c66b5fd26b87ca9c18a1703ab8b29e2c3/packages/geoview-core/src/geo/renderer/geoview-renderer.ts#L283)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we test and apply gradiant only on white element?
</blockquote></details>

This can probably done. Let's create an issue on this.
___
*[`packages/geoview-core/src/geo/renderer/geoview-renderer.ts` line 349 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/640#-NGvdzjR3v3UuXXGkGU6:-NGw6OvWEaFOeMOGqN1a:b9bhb7w) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0b87146c66b5fd26b87ca9c18a1703ab8b29e2c3/packages/geoview-core/src/geo/renderer/geoview-renderer.ts#L349)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

For unique value, it is not the array on canvas with only one element?
</blockquote></details>

No, I put it in the defaultCanvas.

**Review by jolevesq — APPROVED** [review]
> Reviewed 19 of 19 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/640)* status: all files reviewed, 2 unresolved discussions (waiting on @github-code-scanning[bot])

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/640)* status: all files reviewed, 2 unresolved discussions (waiting on @github-code-scanning[bot])

**Review by ychoquet — COMMENTED** [review]
> Dismissed @github-code-scanning[bot] from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/640)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> Dismissed @github-code-scanning[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/640)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
