### PR TITLE
refactor(events) - Finished work on events, incl. map-events, appbar, navbar, footerbar, and more

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

- Appbar and Navbar events refactored
- FooterBar and Modal events refactored
- MapComponent and MapKeyFocus events refactored
- Slider events refactored
- Map-reload events refactored
- Main Event class rewritten (now was a good time)
- TimeSlider fix with the new Slider implementation

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Hosted here as of April 4th 20h10: https://alex-nrcan.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 29 of 33 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990)* status: all files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/public/templates/ui-components.html` line 136 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-Nuhzl6j6W0xVtRHqIBD:-Nuhzl6k6fJuUCA5FnrA:bprc17j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/public/templates/ui-components.html#L136)):*
> ```HTML
> 
>         // Update the component
>         // GV Ideally, we'd like to reuse the root and just do root.render(), but it is unstable, because react doesn't know if you want to actually change the state inside the Swiper component or not.
> ```

Slider, not swiper
___
*[`packages/geoview-core/public/templates/ui-components.html` line 138 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-NuhzqBU6QL3gNX9apR_:-NuhzqBU6QL3gNX9apRa:bprc17j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/public/templates/ui-components.html#L138)):*
> ```HTML
>         // GV Ideally, we'd like to reuse the root and just do root.render(), but it is unstable, because react doesn't know if you want to actually change the state inside the Swiper component or not.
>         // It'll even try to guess based on the props you've sent it originally. This can be proven with the Math.random() below.
>         // This can lead to unexpected results. So, I've ended up just unmounting and recreating from scratch to make sure all state is reset inside Swiper.
> ```

Slider, not swiper
___
*[`packages/geoview-core/src/api/events/event.ts` line 150 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-Nui5_L0CyUNekc896Ip:-Nui5_L1EJNIvDwf6PYU:b-ahba6m) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/api/events/event.ts#L150)):*
> ```XML
> 
>   /**
>    * Emits a map reconstruct event to all handlers.
> ```

We should add more info between map reload and map reconstruct
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 193 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-Nui6glY27_I4EuLGaat:-Nui6glY27_I4EuLGaau:b-i2gq1w) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L193)):*
> ```XML
> 
>     // Register appbar created/removed handlers
>     api.maps[mapId].appBarApi.onAppbarCreated(handleAddButtonPanel);
> ```

Instead of accessing the map, should we pass the api class in props?
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 294 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-Nui7P682GYkv93ffnVr:-Nui7P682GYkv93ffnVs:bqebcmy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L294)):*
> ```XML
> 
>     // Register footerbar tab created/removed handlers
>     api.maps[mapId].footerBarApi.onFooterTabCreated(handleAddTab);
> ```

Same comment as the one for app-bar.tsx
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 138 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-Nui7bn1C88Gg0_Gm5ns:-Nui7bn1C88Gg0_Gm5nt:bcbkac9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L138)):*
> ```XML
> 
>     // Register navbar created/removed handlers
>     api.maps[mapId].navBarApi.onNavbarCreated(handleAddButtonPanel);
> ```

Same as app-bar.tsx, footer-bar.tsx
___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 164 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-Nui8NjTB_0YZClwadRP:-Nui8NjTB_0YZClwadRQ:b-h69n1r) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/core/containers/shell.tsx#L164)):*
> ```XML
>    */
>   const handleMapReload = useCallback(
>     // TODO: Check - The callback does provide this config information, shouldn't it be used in this handler instead of `geoviewConfig`?
> ```

If it works, I would say yes
___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 185 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-NuiALzsAFslHNRoMgkz:-NuiALzsAFslHNRoMgl-:buxiwtl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/core/containers/shell.tsx#L185)):*
> ```XML
> 
>     // to open the modal
>     api.maps[mapId].modal.onModalOpened(handleModalOpen);
> ```

Shell is a very high level component, there is no props.... should we keep it like this or pass the map as props? I have no real preference
___
*[`packages/geoview-core/src/ui/slider/slider.tsx` line 29 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-NuiBN3ED-_Qih-4fvA0:-NuiBN3ED-_Qih-4fvA1:bphjeu6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/ui/slider/slider.tsx#L29)):*
> ```XML
> 
>   // callback when slider value changes
>   // TODO: Refactor - Probably good to see what's the intended difference vs customOnChange (which btw should be renamed to onCustomChanged)
> ```

 think we should not have 2 callback for slider values change. This callback is used in ui-component.html and time-slider.tsx. I think we should use only one

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 32 of 33 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990)* status: all files reviewed, 9 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/public/templates/ui-components.html` line 136 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-Nuhzl6j6W0xVtRHqIBD:-NuiTnFk6-2owikaqEpA:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/public/templates/ui-components.html#L136)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Slider, not swiper
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/ui-components.html` line 138 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-NuhzqBU6QL3gNX9apR_:-NuiTnZ024LFFK4mYWi_:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/public/templates/ui-components.html#L138)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Slider, not swiper
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/events/event.ts` line 150 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-Nui5_L0CyUNekc896Ip:-NuiUoo335YffBdRtLml:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/api/events/event.ts#L150)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should add more info between map reload and map reconstruct
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 193 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-Nui6glY27_I4EuLGaat:-NuiUrejC2IlfS8SXyV2:brldhnq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L193)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Instead of accessing the map, should we pass the api class in props?
</blockquote></details>

Yes, we can do that.
Is it common in react to send an associated 'api' as props to a component tsx or should they talk with callbacks. Do we send an api in a component anywhere else?
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 294 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-Nui7P682GYkv93ffnVr:-NuiW0bA23HgL0j7GcRu:b-mfrfzr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L294)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same comment as the one for app-bar.tsx
</blockquote></details>

Ok, see app-bar.
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 138 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-Nui7bn1C88Gg0_Gm5ns:-NuiW4Fx2TKcXingNiuk:b-mfrfzr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L138)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same as app-bar.tsx, footer-bar.tsx
</blockquote></details>

Ok, see app-bar.
___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 164 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-Nui8NjTB_0YZClwadRP:-Nui_tlh5tcWh8w2KZHA:ba6d7ew) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/core/containers/shell.tsx#L164)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If it works, I would say yes
</blockquote></details>

It's already not quite working, because of the endsWith layerPath issue (same in upstream), but it seems good. I'll do it with the callback info.
___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 185 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-NuiALzsAFslHNRoMgkz:-NuiWFsy3L6WUqnhazoU:b-5y19hz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/core/containers/shell.tsx#L185)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Shell is a very high level component, there is no props.... should we keep it like this or pass the map as props? I have no real preference
</blockquote></details>

Can be a discussion for review, mid-term.
___
*[`packages/geoview-core/src/ui/slider/slider.tsx` line 29 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-NuiBN3ED-_Qih-4fvA0:-NuiWUXgBKxCjKK7iGU6:byvxukj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/ui/slider/slider.tsx#L29)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

think we should not have 2 callback for slider values change. This callback is used in ui-component.html and time-slider.tsx. I think we should use only one
</blockquote></details>

Agreed that we should have just one. They have different signatures and I was focusing on making sure the events were still working as-is for now, but I can take a look and combine them using the greater signature of them both. Would be another breaking change for sure though. Should I do it in this PR or add a TODO?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990)* status: all files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 193 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-Nui6glY27_I4EuLGaat:-NuibUHO1ThqNrmsMcIE:b25z9lz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L193)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Yes, we can do that.
Is it common in react to send an associated 'api' as props to a component tsx or should they talk with callbacks. Do we send an api in a component anywhere else?
</blockquote></details>

I dont think we do but passing only api would be cleaner I think
___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 185 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-NuiALzsAFslHNRoMgkz:-Nuibgrk40Z-w8hdivVr:b-8ayu6x) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/core/containers/shell.tsx#L185)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Can be a discussion for review, mid-term.
</blockquote></details>

Agree
___
*[`packages/geoview-core/src/ui/slider/slider.tsx` line 29 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-NuiBN3ED-_Qih-4fvA0:-Nuibm6NAtxMbIzc882B:b-r63wb4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/ui/slider/slider.tsx#L29)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Agreed that we should have just one. They have different signatures and I was focusing on making sure the events were still working as-is for now, but I can take a look and combine them using the greater signature of them both. Would be another breaking change for sure though. Should I do it in this PR or add a TODO?
</blockquote></details>

Depend how long it can take I would say

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 28 of 29 files at r5, 3 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990)* status: all files reviewed, 9 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 193 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-Nui6glY27_I4EuLGaat:-Nuird__7oOG5hwlB9Mr:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L193)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I dont think we do but passing only api would be cleaner I think
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 185 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-NuiALzsAFslHNRoMgkz:-NuirbilBnqpXhlgOJ-N:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/core/containers/shell.tsx#L185)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Agree
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/slider/slider.tsx` line 29 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-NuiBN3ED-_Qih-4fvA0:-NujbN2E8i1hA7e0i0yw:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/src/ui/slider/slider.tsx#L29)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Depend how long it can take I would say
</blockquote></details>

Done.

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990)* status: 50 of 52 files reviewed, 9 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/public/templates/ui-components.html` line 136 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990#-Nuhzl6j6W0xVtRHqIBD:-NujgHqs8WVBzhKZiOOJ:bdqxay) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/042d7a7adb66841eca4c5b11d44a9cebc9b74f1c/packages/geoview-core/public/templates/ui-components.html#L136)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Now it is Sliper :-)
</blockquote></details>

lol, done

**Review by jolevesq — APPROVED** [review]
> Reviewed 28 of 29 files at r5, 3 of 4 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1990)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
