### PR TITLE
{REFACTOR] Refactor store to clean components

### LINKED ISSUE #1461: [REFACTOR] Store new state/selector
Continue the refactor to use the new state selector approach.

- Footer Bar Component and content
- Crosshair
- Nav Bar

### PR DESCRIPTION
**Pull request by jolevesq**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Refactor many small components to use store values and store action so no more logic/ol inside components.
We still miss bigger components like (north arrow, overview map, marker/geolocator, higlights)

Fixes #1461 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://jolevesq.github.io/geoview/projections.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1463)

### CODE REVIEW

**Review by DamonU2 — APPROVED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1463)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan, @cphelefu, and @ychoquet)

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts` line 106 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1463#-NiXA-A28s_nj0fHldNN:-NiXA-A28s_nj0fHldNO:bkl3q05) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f3be349a2d3cfc1cdd8eeb1741cf50114a2217c/packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts#L106)):*
> ```XML
>       // this will enable mouse position and hover tooltip
>       if (get().appState.isCrosshairsActive) {
>         console.log('set)');
> ```

Can remove the console log

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts` line 106 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1463#-NiXAc7N8-57XIoEEzx1:-NiXAc7N8-57XIoEEzx2:b-6gghhn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f3be349a2d3cfc1cdd8eeb1741cf50114a2217c/packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts#L106)):*
> ```XML
>       // this will enable mouse position and hover tooltip
>       if (get().appState.isCrosshairsActive) {
>         console.log('set)');
> ```

remove the console log

**Review by cphelefu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1463)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @jolevesq, and @ychoquet)

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1463)* status: all files reviewed, 3 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/core/components/crosshair/crosshair.tsx` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1463#-NiZkPPP76CAVIBF0Byp:-NiZkPPP76CAVIBF0Byq:bcnawgl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f3be349a2d3cfc1cdd8eeb1741cf50114a2217c/packages/geoview-core/src/core/components/crosshair/crosshair.tsx#L37)):*
> ```XML
>    * @param {KeyboardEvent} evt the keyboard event
>    */
>   function simulateClick(evt: KeyboardEvent): void {
> ```

simulateClick should probably be wrapped in a "useCallback" method so that it doesn't force a re-render of the useEffect with the simulateClick reference used there.
___
*[`packages/geoview-core/src/core/components/crosshair/crosshair.tsx` line 48 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1463#-NiZkqDVC0rNx9x4M6k5:-NiZkqDVC0rNx9x4M6k6:b-u9ob53) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f3be349a2d3cfc1cdd8eeb1741cf50114a2217c/packages/geoview-core/src/core/components/crosshair/crosshair.tsx#L48)):*
> ```XML
>    * @param {KeyboardEvent} evt the keyboard event to trap
>    */
>   function managePanDelta(evt: KeyboardEvent): void {
> ```

managePanDelta should probably be wrapped in a "useCallback" method so that it doesn't force a re-render of the useEffect with the managePanDelta reference used there.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts` line 224 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1463#-Ni_039B6OMzvqynsCkz:-Ni_039B6OMzvqynsCl-:b-rxppan) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f3be349a2d3cfc1cdd8eeb1741cf50114a2217c/packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts#L224)):*
> ```XML
> 
>         // set ol map rotation
>         get().mapState.mapElement.getView().animate({ rotation: 0 });
> ```

this is supposed to be `get().mapState.mapElement.getView().animate({ rotation: degree });`

**Review by ychoquet — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1463)* status: all files reviewed, 4 unresolved discussions (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1463)* status: 22 of 24 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @cphelefu, and @DamonU2)

___
*[`packages/geoview-core/src/core/components/crosshair/crosshair.tsx` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1463#-NiZkPPP76CAVIBF0Byp:-Ni_xRruCdVmrUDY5jxc:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f3be349a2d3cfc1cdd8eeb1741cf50114a2217c/packages/geoview-core/src/core/components/crosshair/crosshair.tsx#L37)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

simulateClick should probably be wrapped in a "useCallback" method so that it doesn't force a re-render of the useEffect with the simulateClick reference used there.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/crosshair/crosshair.tsx` line 48 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1463#-NiZkqDVC0rNx9x4M6k5:-Ni_xSIT4iTuv9uU84X3:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f3be349a2d3cfc1cdd8eeb1741cf50114a2217c/packages/geoview-core/src/core/components/crosshair/crosshair.tsx#L48)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

managePanDelta should probably be wrapped in a "useCallback" method so that it doesn't force a re-render of the useEffect with the managePanDelta reference used there.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts` line 224 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1463#-Ni_039B6OMzvqynsCkz:-Ni_xgf16SpM_S0QXhvG:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5f3be349a2d3cfc1cdd8eeb1741cf50114a2217c/packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts#L224)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

this is supposed to be `get().mapState.mapElement.getView().animate({ rotation: degree });`
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 22 of 24 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1463)* status: 23 of 24 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @cphelefu, and @DamonU2)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1463)* status: all files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan and @cphelefu)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1463)* status: all files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan and @cphelefu)

**Pull request merged**
