### PR TITLE
#1746 Add status flag to feature info layers set and the store

### PR DESCRIPTION
**Pull request by ychoquet**
# Description
### Current Behavior

The add-new-layer.tsx file use an old method to validate and add new layers on a map. This cause code duplication and to a certain extent code discrepencies.

### Expected Behavior

Implement these flags as soon as possible because they are needed for the current developpements. Also implement in the store the hover data table and the all features data table.

Fixes # (1746)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Use the raw-feature-info.html template. Implementation will be deployed at URL https://ychoquet.github.io/GeoView/raw-feature-info.html for testing.

__Deploy URL__:  https://ychoquet.github.io/GeoView/raw-feature-info.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1747)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 40 of 45 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1747)* status: 40 of 45 files reviewed, 4 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/public/templates/layers/esri-dynamic.html` line 1129 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1747#-NpZpdo977Li354FmPzM:-NpZpdo977Li354FmPzN:b-az20ri) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bc5f9ff32c97bda8c88055872aa03d67642773fa/packages/geoview-core/public/templates/layers/esri-dynamic.html#L1129)):*
> ```HTML
>         cgpv.api.eventNames.GET_FEATURE_INFO.ALL_QUERIES_DONE,
>         (payload) => {
>           const { layerSetId, resultsSet, eventType } = payload;
> ```

get feature info is always empty... did some refresh and it works now... weird.  __It is because layer filter is not reflected on the map on load... so I see the data but un reality it is not there. When I zoomed out they disappears and details works as expected__

name in map status flag is empty (for all layer)
___
*[`packages/geoview-core/public/templates/layers/esri-feature.html` line 428 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1747#-NpZvEeWEabYvi_7I_wG:-NpZvEeWEabYvi_7I_wH:b-ogcccf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bc5f9ff32c97bda8c88055872aa03d67642773fa/packages/geoview-core/public/templates/layers/esri-feature.html#L428)):*
> ```HTML
> 
>       cgpv.api.event.on(
>         cgpv.api.eventNames.GET_FEATURE_INFO.ALL_QUERIES_DONE,
> ```

Map 2 and 3 we cant see the layer... should be a problem with layer filter
___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 32 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1747#-NpZxhVS1R-yuTRg72vB:-NpZxhVS1R-yuTRg72vC:b-apswen) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bc5f9ff32c97bda8c88055872aa03d67642773fa/packages/geoview-core/src/core/stores/geoview-store.ts#L32)):*
> ```XML
>   // core state interfaces
>   appState: IAppState;
>   detailsState: IFeatureInfoState;
> ```

To be in synch we should change the whole thing to feature-info. Can you create an issue for this... will see if we do later. Not now as there is a lot of work in details at the moment....
___
*[`packages/geoview-core/src/geo/utils/feature-info-layer-set.ts` line 179 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1747#-NpZz6Gc8fGOiJsAaFwM:-NpZz6Gd0g6D1NW7FWr4:b-1i1egk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bc5f9ff32c97bda8c88055872aa03d67642773fa/packages/geoview-core/src/geo/utils/feature-info-layer-set.ts#L179)):*
> ```XML
> 
>     api.event.on(
>       EVENT_NAMES.GET_FEATURE_INFO.GET_ALL_LAYER_FEATURES,
> ```

Can we have a function from the api to emit this event like getAllFeatureInfo(layerPath). This function can even be in the layer object itself ...

**Review by jolevesq — COMMENTED** [review]
> Reviewed 5 of 45 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1747)* status: all files reviewed, 4 unresolved discussions (waiting on @ychoquet)

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1747)* status: all files reviewed, 5 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/feature-info-state.ts` line 28 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1747#-Np_-5s-9c1_cub9Ya-O:-Np_-5s-9c1_cub9Ya-P:b-otc4it) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bc5f9ff32c97bda8c88055872aa03d67642773fa/packages/geoview-core/src/core/stores/store-interface-and-intial-values/feature-info-state.ts#L28)):*
> ```XML
>     layerDataArray: [],
>     hoverDataArray: [],
>     allFeaturesDataArray: [],
> ```

The same way you create the array for featureInfo click from layer type, can we do the same thing for the allFeature... crate the array with layers who can have a table then we trigger the function after to populate.... Can we test table query without downloading?

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 45 of 45 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1747)* status: all files reviewed, 5 unresolved discussions (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> Reviewed 32 of 32 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1747)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
