### PR TITLE
fix(geolocator): Geolocator

### LINKED ISSUE #1826: [BUG] Geolocator bold value
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we search with geolocator, all text before first come is bold

### Expected Behavior

Only the match between search and text should be bold
image

At the same time, restrict call to the api when at least 3 characters are put

Support zoom to coordinates decimal degree

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Fix font bold for search term in search result, limit the query until 3 chars and add support for lat and long.

Fixes #1826 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
1) Open https://kaminderpal.github.io/geoview/raw-feature-info.html
2) Click on Geolocator icon in appbar.
3) do search for place, font will be bold for search item in search result.
4) No api request sent until 3 chars are typed.
5) do search for `-86.7792,51.6607`, it will add one item for lat and long.

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/raw-feature-info.html
# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1888)

### CODE REVIEW

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1888)* status: all files reviewed, 3 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1888#-NsF_qGP6FpOEsWqUcg4:-NsF_qGP6FpOEsWqUcg5:b-j5ze75) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ea26072eba1fd9c239536a374ea3d46d859e4508/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L60)):*
> ```XML
> /**
>  * Create list of items to display under search.
>  * @param {GeoListItem} geoListItems - items to display
> ```

Should be {GeoListItem[]}
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 45 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1888#-NsFa63T-S96R9ySIw3s:-NsFa63T-S96R9ySIw3t:bg1j9qx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ea26072eba1fd9c239536a374ea3d46d859e4508/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L45)):*
> ```XML
> 
>   /**
>    * Checks if search term is decimal degree and return geo list item.
> ```

a decimal degree coordinate
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 137 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1888#-NsFab7Q6OGkYP_YU150:-NsFab7RE3LwnyqmyMrn:b7dwh5w) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ea26072eba1fd9c239536a374ea3d46d859e4508/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L137)):*
> ```XML
>     const { value } = e.target;
>     setSearchValue(value);
>     // do fetch request when user enter alteast 3 characters. #1826
> ```

alteast -> at least
Also, do we need the issue number if this PR is closing the issue?

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1888)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1888#-NsF_qGP6FpOEsWqUcg4:-NsGTDZ-D8Gxhcyy4rIl:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ea26072eba1fd9c239536a374ea3d46d859e4508/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L60)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Should be {GeoListItem[]}
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 45 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1888#-NsFa63T-S96R9ySIw3s:-NsGTEhP7H9pvBhM2FhA:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ea26072eba1fd9c239536a374ea3d46d859e4508/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L45)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

a decimal degree coordinate
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 137 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1888#-NsFab7Q6OGkYP_YU150:-NsGTFjS-2F5dxQEIcmj:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ea26072eba1fd9c239536a374ea3d46d859e4508/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L137)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

alteast -> at least
Also, do we need the issue number if this PR is closing the issue?
</blockquote></details>

Done.

**Review by DamonU2 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1888)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Review by DamonU2 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1888#-:-NsJIyib9HMxhH8qqVBo:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Pull request merged**
