### PR TITLE
601-First version of feature info layer set

### PR DESCRIPTION
**Pull request by ychoquet**
This PR also correct some bugs with the vector layers from the config or added dynamically.

- - -
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602)* status: all files reviewed, 5 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/public/templates/layers.html` line 334 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFTRLwfD-fj2GIEJHp5:-NFTRLwgAOFNU4S-sbEK:b-hvpf7t) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/4278a25bf310697daa61558c591b2ae54eb60a8d/packages/geoview-core/public/templates/layers.html#L334)):*
> ```HTML
>   <button id="add-geojson">Add GeoJSON Layer</button><button id="remove-geojson">Remove GeoJSON Layer</button> <br />
>   <label> Added Layer ID : </label><label id="new-layer-id-label"></label>
>   <button type="button" class="collapsible">Get Feature Info polygons</button>
> ```

Can remove polygon as now it queries everything
___
*[`packages/geoview-core/public/templates/layers.html` line 509 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFTT79jD8L4fO5I4JG6:-NFTT79jD8L4fO5I4JG7:b-5uckcu) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/4278a25bf310697daa61558c591b2ae54eb60a8d/packages/geoview-core/public/templates/layers.html#L509)):*
> ```HTML
>           'listOfLayerEntryConfig': [
>             {
>               'layerId': 'historical_flood_0.geojson',
> ```

You are using double quote but all the rest of template configuration for all sample are single quote. Can we stick with single quote?
___
*[`packages/geoview-core/public/templates/layers.html` line 519 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFTRUVVAUX2Y9RR7f0m:-NFTRUVVAUX2Y9RR7f0n:bcdbfr2) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/4278a25bf310697daa61558c591b2ae54eb60a8d/packages/geoview-core/public/templates/layers.html#L519)):*
> ```HTML
>                   "nameField": { "en": "comment_en", "fr": "comment_fr" },
>                   "outfields": { "en": "comment_en,death_en_1,end_date", "fr": "comment_fr,death_fr_1,end_date" },
>                   "aliasFields":  { "en": "comment_en,death_en_1,end_date", "fr": "comment_fr,death_fr_1,end_date" }
> ```

Can you put alias field different then name field so we can see them in the return value. At the same time alias should be an array of field return by the query info but the result set should contain the original

What do you think of something like 
```
{
  "esriDynamicLYR3/0": [
    fields: [{
        OBJECTID: { "alias": "id", "type": "number", "length": 10},
        "uuid" ...
    ],
    features: [{
      "OBJECTID": "4",
      "uuid": "2987b601-fef9-4ac0-a0ee-e246a9a4500c",
      "event_id": "39f0e005-e778-4baa-99c2-6002dbe3bb5a",
      "event_name": "Null",
      "year": "1953",
      "start_date": "1953",
      "end_date": "Null",
      "season": "unknown",
      "flood_cause": "unknown",
      "flood_cause_description": "The flooding mechanism is not known.",
      "death": "unknown",
      "evacuation"
```

I see you have outfiels set but all the fields are there, is it read by the getFeatureInfo?
___
*[`packages/geoview-core/public/templates/layers.html` line 616 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFTV70OEWfU4I-bEeEK:-NFTV70OEWfU4I-bEeEL:b8go4nw) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/4278a25bf310697daa61558c591b2ae54eb60a8d/packages/geoview-core/public/templates/layers.html#L616)):*
> ```HTML
>       cgpv.api
>         .map('LYR1')
>         .layer.geoviewLayers['wmsLYR1-Root'].getLegend('wmsLYR1-Root/wmsLYR1-Group/TOPO-OSM-WMS')
> ```

This is a good modification to make a distinction between OL et our layers object but it has a huge impact on all the function call. Hope we trapped everything.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 213 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFTWoHo4GA-r59efvjJ:-NFTWoHo4GA-r59efvjK:b-lbir5j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/4278a25bf310697daa61558c591b2ae54eb60a8d/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L213)):*
> ```XML
>         const layerSource = layer.get('layerEntryConfig')?.source; if (!layerSource) return false;
>         const configSource = layerConfig?.source; if (!configSource) return false;
>         if (layerSource === configSource) console.log('SAME2');
> ```

What are these console.log for?

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602)* status: 16 of 29 files reviewed, 5 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/layers.html` line 334 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFTRLwfD-fj2GIEJHp5:-NFThL419cqxH_KdkTNP:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/4278a25bf310697daa61558c591b2ae54eb60a8d/packages/geoview-core/public/templates/layers.html#L334)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can remove polygon as now it queries everything
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/layers.html` line 509 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFTT79jD8L4fO5I4JG6:-NFTi3ab4Q-atvSUQQ-_:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/4278a25bf310697daa61558c591b2ae54eb60a8d/packages/geoview-core/public/templates/layers.html#L509)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You are using double quote but all the rest of template configuration for all sample are single quote. Can we stick with single quote?
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/layers.html` line 519 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFTRUVVAUX2Y9RR7f0m:-NFVdD2s-9WdPD5_n52l:b-fhg8sd) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/4278a25bf310697daa61558c591b2ae54eb60a8d/packages/geoview-core/public/templates/layers.html#L519)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put alias field different then name field so we can see them in the return value. At the same time alias should be an array of field return by the query info but the result set should contain the original

What do you think of something like 
```
{
  "esriDynamicLYR3/0": [
    fields: [{
        OBJECTID: { "alias": "id", "type": "number", "length": 10},
        "uuid" ...
    ],
    features: [{
      "OBJECTID": "4",
      "uuid": "2987b601-fef9-4ac0-a0ee-e246a9a4500c",
      "event_id": "39f0e005-e778-4baa-99c2-6002dbe3bb5a",
      "event_name": "Null",
      "year": "1953",
      "start_date": "1953",
      "end_date": "Null",
      "season": "unknown",
      "flood_cause": "unknown",
      "flood_cause_description": "The flooding mechanism is not known.",
      "death": "unknown",
      "evacuation"
```

I see you have outfiels set but all the fields are there, is it read by the getFeatureInfo?
</blockquote></details>

GeoJSON added dynamically outside the config file does not have metadata. We must provide fields and aliases in the dynamic config. I'm not sure I answer the question. If not, can you be more precise?
___
*[`packages/geoview-core/public/templates/layers.html` line 616 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFTV70OEWfU4I-bEeEK:-NFTihYu84Mp1-qCcts7:b-wgjx8w) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/4278a25bf310697daa61558c591b2ae54eb60a8d/packages/geoview-core/public/templates/layers.html#L616)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This is a good modification to make a distinction between OL et our layers object but it has a huge impact on all the function call. Hope we trapped everything.
</blockquote></details>

It is supposed to cover all of them, otherwise I would have had a compile error.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 213 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFTWoHo4GA-r59efvjJ:-NFVeIDf9FY74Svum0_6:b2mbwr0) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/4278a25bf310697daa61558c591b2ae54eb60a8d/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L213)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

What are these console.log for?
</blockquote></details>

debugging left over. I deleted them.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 6 of 13 files at r2, 11 of 12 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602)* status: 32 of 33 files reviewed, 4 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/public/templates/layers.html` line 519 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFTRUVVAUX2Y9RR7f0m:-NFnT0U7CnMDzKzdXXiX:b-9k1bzc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/4278a25bf310697daa61558c591b2ae54eb60a8d/packages/geoview-core/public/templates/layers.html#L519)):*
<details><summary><i>Previously, ychoquet wrote…</i></summary><blockquote>

GeoJSON added dynamically outside the config file does not have metadata. We must provide fields and aliases in the dynamic config. I'm not sure I answer the question. If not, can you be more precise?
</blockquote></details>

That is good but can you rename the alias something like ```{ 'en': 'Comments, Death, Date', 'fr': 'Commentaires, Morts, Date' }```
___
*[`packages/geoview-core/src/api/events/constants/layer-set.ts` line 21 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFn_Kem8jxd2gX9g4Pe:-NFn_Kem8jxd2gX9g4Pf:b-it16cn) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9772557289ff4f0c4503c152f478b8436fe2ca0e/packages/geoview-core/src/api/events/constants/layer-set.ts#L21)):*
> ```XML
>    * Event triggered when a layer wants to register to the layer set
>    */
>   LAYER_REGISTRATION: 'layer_set/layer_registration',
> ```

Chris sais: I'm not always getting all layers (from api.map(mapId).layer.layers). Does this layer-set may solve the problem by emitting something when new layer are added?
___
*[`packages/geoview-core/src/api/events/payloads/layer-set-payload.ts` line 8 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFnixsuDTY7J0g1Z1JH:-NFnixsvC-u3PlboO6RV:b-s44vvy) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9772557289ff4f0c4503c152f478b8436fe2ca0e/packages/geoview-core/src/api/events/payloads/layer-set-payload.ts#L8)):*
> ```XML
> const validEvents: EventStringId[] = [EVENT_NAMES.LAYER_SET.LAYER_REGISTRATION, EVENT_NAMES.LAYER_SET.REQUEST_LAYER_INVENTORY];
> 
> export type TypeQueryType = 'at pixel' | 'at coordinate' | 'at long lat' | 'using a bounding box' | 'using a polygon';
> ```

This is layer set registration but it is tight to feature info. Should we have a generic layer registration for the whole map and then add a key for specific panel-task (legend, table, filters, ...)?

Or can you explain me how the registration works. We will need documentation for this aspect
___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 38 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFnk7rV8UyILTRQPbpC:-NFnk7rW9HpAR4H1mWWz:b3mtm4t) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9772557289ff4f0c4503c152f478b8436fe2ca0e/packages/geoview-core/src/geo/utils/layer-set.ts#L38)):*
> ```XML
>     layerSetId: string,
>     resultSets: TypeResultSets,
>     registrationConditionFonction: (layerPath: string) => boolean
> ```

Fonction ... should it be Function?

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602)* status: 22 of 33 files reviewed, 4 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/layers.html` line 519 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFTRUVVAUX2Y9RR7f0m:-NFoOEzK6KeIbLbrTF0z:b-avw9h4) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/4278a25bf310697daa61558c591b2ae54eb60a8d/packages/geoview-core/public/templates/layers.html#L519)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

That is good but can you rename the alias something like ```{ 'en': 'Comments, Death, Date', 'fr': 'Commentaires, Morts, Date' }```
</blockquote></details>

The format is imposed by the geoview code and is very compact. If we want a format more liberal and easyer to read we must modify the schema and the processLayerMetadata code that translate the metadata into the schema format.
___
*[`packages/geoview-core/src/api/events/constants/layer-set.ts` line 21 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFn_Kem8jxd2gX9g4Pe:-NFoLczoCK4XFEVjLrNW:b-rlwmc0) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9772557289ff4f0c4503c152f478b8436fe2ca0e/packages/geoview-core/src/api/events/constants/layer-set.ts#L21)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Chris sais: I'm not always getting all layers (from api.map(mapId).layer.layers). Does this layer-set may solve the problem by emitting something when new layer are added?
</blockquote></details>

I think we should create an issue on that topic to make sure the layers are loaded when we want to use them
___
*[`packages/geoview-core/src/api/events/payloads/layer-set-payload.ts` line 8 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFnixsuDTY7J0g1Z1JH:-NFoM9sG9kcB8xDjDVPo:bxxr5nh) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9772557289ff4f0c4503c152f478b8436fe2ca0e/packages/geoview-core/src/api/events/payloads/layer-set-payload.ts#L8)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This is layer set registration but it is tight to feature info. Should we have a generic layer registration for the whole map and then add a key for specific panel-task (legend, table, filters, ...)?

Or can you explain me how the registration works. We will need documentation for this aspect
</blockquote></details>

Obviously, I'm going to have to document this. The layer set separation is already done. I extracted it from the get feature info layer set and reused it in get legend.
___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 38 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFnk7rV8UyILTRQPbpC:-NFoNKrsBZ2wBsl86_Fu:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9772557289ff4f0c4503c152f478b8436fe2ca0e/packages/geoview-core/src/geo/utils/layer-set.ts#L38)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Fonction ... should it be Function?
</blockquote></details>

Done.



_Code quote:_
```XML
registrationConditionFonction
```

**Review by jolevesq — APPROVED** [review]
:lgtm: 

> Reviewed 11 of 11 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-:-NFod4IlD_jBpOnefVgo:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/public/templates/layers.html` line 519 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFTRUVVAUX2Y9RR7f0m:-NFoc66X2z27d6vh5EEd:b-sr6xkj) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/4278a25bf310697daa61558c591b2ae54eb60a8d/packages/geoview-core/public/templates/layers.html#L519)):*
<details><summary><i>Previously, ychoquet wrote…</i></summary><blockquote>

The format is imposed by the geoview code and is very compact. If we want a format more liberal and easyer to read we must modify the schema and the processLayerMetadata code that translate the metadata into the schema format.
</blockquote></details>

Will do in another issue
___
*[`packages/geoview-core/src/api/events/payloads/layer-set-payload.ts` line 8 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602#-NFnixsuDTY7J0g1Z1JH:-NFochsmCflDfurpKNAU:b8rpjsp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/9772557289ff4f0c4503c152f478b8436fe2ca0e/packages/geoview-core/src/api/events/payloads/layer-set-payload.ts#L8)):*
<details><summary><i>Previously, ychoquet wrote…</i></summary><blockquote>

Obviously, I'm going to have to document this. The layer set separation is already done. I extracted it from the get feature info layer set and reused it in get legend.
</blockquote></details>

Perfect, looking forward for this documentation :-)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/602)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
