### PR TITLE
fix(multiple): Fix crosshair, hydro demo, sandbox demo

### LINKED ISSUE #1674: [BUG] Crosshair does not return when tabbing back to map
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If you tab to the map and enable keyboard navigation, the crosshair appears and works fine. If you tab away from the map and return, the crosshair does not return, but operates normally otherwise.

### Expected Behavior

Crosshair should return upon tabbing back to the map

### Steps To Reproduce

Go to any map, enable keyboard navigation, tab out and tab back.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1674

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1674 (crosshair), #1688 (static), #1689/#1733 (default config), #1666 (sandbox)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- Pygeoapi process for hydro: https://jolevesq.github.io/geoview/pygeoapi-processes.html
- Default config: https://jolevesq.github.io/geoview/default-config.html?p=3857&z=4&c=-100,40&l=en&t=dark&b={basemapId:transport,shaded:false,labeled:true}&i=dynamic&cc=overview-map&keys=12acd145-626a-49eb-b850-0a59c9bc7506,ccc75c12-5acc-4a6a-959f-ef6f621147b9
- Crosshair, static, sandbox: https://jolevesq.github.io/geoview/sandbox.html
     - for crosshair, tab to the map, enable WCAG mode then tab map to see crosshair, continue tabbing until crosshair is back
     - for static, change interaction to static and recreate the map

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740)

### CODE REVIEW

**Review by DamonU2 — APPROVED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan and @ychoquet)

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 9 of 15 files at r1, 20 of 22 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740)* status: all files reviewed, 6 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/public/templates/codedoc.js` line 30 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#-NpVJ4j58jrgul0QD1OE:-NpVJ4j61-4nZ-jfHcB7:bydh68z) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/693eecf257d33c082f9d92ba973454055f6dfef6/packages/geoview-core/public/templates/codedoc.js#L30)):*
> ```JavaScript
> 
> function createCodeSnippetUsingIDs() {
>   sleep(1000);
> ```

Maybe not important, but maybe turn async and await on a delay instead of blocking the main thread?
___
*[`packages/geoview-core/src/api/api.ts` line 145 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#-NpVJpci3Ndw6yL7erE4:-NpVJpci3Ndw6yL7erE5:bm069h2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/693eecf257d33c082f9d92ba973454055f6dfef6/packages/geoview-core/src/api/api.ts#L145)):*
> ```XML
>         if (mapId !== undefined) {
>           const mapFocus = activeEl?.getAttribute('id') === `mapbox-${mapId}`;
>           logger.logTraceCore(`Map ${mapId} focus and crosshair is enable`, [mapFocus]);
> ```

Perso, je prendrais probablement plus un logInfo, parce que c'est plus informatif que de la trace d'appel de fonction, mais c'est un détail.

Aussi, 'is enabled'.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts` line 24 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#-NpVKt5zAgJHFARuhF_4:-NpVKt6-2_IfgOi6LVvx:b-azboj9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/693eecf257d33c082f9d92ba973454055f6dfef6/packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts#L24)):*
> ```XML
>     // because notification is called before map is created, we just loop until
>     // store for this map is created.
>     const myInterval = setInterval(() => {
> ```

Me semble être un bon cas d'usage de async et faire un await sur un whenThisThen ça.
Mettre la fonction async aiderait le développeur à comprendre qu'il y a un délai à l'intérieur (dans l'implémentation).
___
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 145 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#-NpVKenL9yWZvf-VnpYv:-NpVKenL9yWZvf-VnpYw:b-a084ef) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/693eecf257d33c082f9d92ba973454055f6dfef6/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L145)):*
> ```XML
> 
>   const handleReloadLayer = () => {
>     logger.logInfo('reloading layer not implemented...');
> ```

Maybe a 'logWarning' instead? I don't know
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 379 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#-NpVLB2LB5fJAGLZBoq_:-NpVLB2MAcnjhORqltcH:b8uz15a) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/693eecf257d33c082f9d92ba973454055f6dfef6/packages/geoview-core/src/geo/map/map-viewer.ts#L379)):*
> ```XML
>         if (AppEventProcessor.getSupportedLanguages(this.mapId).includes(displayLanguage)) {
>           // eslint-disable-next-line no-console
>           logger.logInfo('reset layers not implemented yet');
> ```

Remove the // eslint comment and maybe logWarning instead?

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740)* status: all files reviewed, 6 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts` line 24 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#-NpVKt5zAgJHFARuhF_4:-NpVLuMT2MjXEsECGiam:b-abbafi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/693eecf257d33c082f9d92ba973454055f6dfef6/packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts#L24)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Me semble être un bon cas d'usage de async et faire un await sur un whenThisThen ça.
Mettre la fonction async aiderait le développeur à comprendre qu'il y a un délai à l'intérieur (dans l'implémentation).
</blockquote></details>

getGeoViewStore pourrait être async même, rendu là

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740)* status: all files reviewed, 7 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 236 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#-NpVN66l1aHdhlcCdN36:-NpVN66m7gobBlq_pqbm:b-bho6p9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/693eecf257d33c082f9d92ba973454055f6dfef6/packages/geoview-core/src/core/utils/utilities.ts#L236)):*
> ```XML
>     }
>   } catch (e) {
>     logger.logError('- Invalid JSON string. String passed to the JSON parser:');
> ```

Should probably combine the logErrors into a single one, for clarity in the console output (because logError already spits out the callstack and things)

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740)* status: all files reviewed, 8 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 359 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#-NpVNNT95WvXY7tsbPcr:-NpVNNTA4nQOIrO3YkOl:bvqu4s3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/693eecf257d33c082f9d92ba973454055f6dfef6/packages/geoview-core/src/core/utils/config/config-validation.ts#L359)):*
> ```XML
>         node = node[path[j]];
>       }
>       logger.logWarning(this.mapId, '='.repeat(200));
> ```

Should probably combine the logWarning into a single one, for clarity in the console output

**Review by jolevesq — COMMENTED** [review]
> Reviewed 15 of 15 files at r1, 22 of 22 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740)* status: all files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/public/templates/codedoc.js` line 30 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#-NpVJ4j58jrgul0QD1OE:-NpVm3u-AD4s0czhWNAH:b-v1bc1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/693eecf257d33c082f9d92ba973454055f6dfef6/packages/geoview-core/public/templates/codedoc.js#L30)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Maybe not important, but maybe turn async and await on a delay instead of blocking the main thread?
</blockquote></details>

Yeah it is only for demo pages
___
*[`packages/geoview-core/src/api/api.ts` line 145 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#-NpVJpci3Ndw6yL7erE4:-NpVMg2ZCLr_t0ZyB0Oi:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/693eecf257d33c082f9d92ba973454055f6dfef6/packages/geoview-core/src/api/api.ts#L145)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Perso, je prendrais probablement plus un logInfo, parce que c'est plus informatif que de la trace d'appel de fonction, mais c'est un détail.

Aussi, 'is enabled'.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts` line 24 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#-NpVKt5zAgJHFARuhF_4:-NpVuswY4xjuQUMc_1fD:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/693eecf257d33c082f9d92ba973454055f6dfef6/packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts#L24)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

getGeoViewStore pourrait être async même, rendu là
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 145 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#-NpVKenL9yWZvf-VnpYv:-NpVp3DvCwu8vhb3uKRz:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/693eecf257d33c082f9d92ba973454055f6dfef6/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L145)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Maybe a 'logWarning' instead? I don't know
</blockquote></details>

Done
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 236 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#-NpVN66l1aHdhlcCdN36:-NpVqHRfCvA4xddvU9Ut:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/693eecf257d33c082f9d92ba973454055f6dfef6/packages/geoview-core/src/core/utils/utilities.ts#L236)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Should probably combine the logErrors into a single one, for clarity in the console output (because logError already spits out the callstack and things)
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 359 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#-NpVNNT95WvXY7tsbPcr:-NpVqXl-BjE_Kznu2h4n:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/693eecf257d33c082f9d92ba973454055f6dfef6/packages/geoview-core/src/core/utils/config/config-validation.ts#L359)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Should probably combine the logWarning into a single one, for clarity in the console output
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 379 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#-NpVLB2LB5fJAGLZBoq_:-NpVqh7-CwO44vMq-wsu:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/693eecf257d33c082f9d92ba973454055f6dfef6/packages/geoview-core/src/geo/map/map-viewer.ts#L379)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Remove the // eslint comment and maybe logWarning instead?
</blockquote></details>

Done.

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740)* status: all files reviewed, 8 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/core/stores/stores-managers.ts` line 57 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#-NpVvoSU1nMbeeLCsPJV:-NpVvoSV2SgnK34HtW48:b-fzayvb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1d2700fd7d03436b1a0f6da2f4564f143a527bc/packages/geoview-core/src/core/stores/stores-managers.ts#L57)):*
> ```XML
> export const getGeoViewStoreAsync = async (id: string | undefined): Promise<GeoviewStoreType> => {
>   const store = await whenThisThen(() => getGeoViewStore(id));
>   return store;
> ```

Si tu veux te sauver un Promise d'un Promise, tu peux écrire ça en one-liner ainsi:

return whenThisThen(() => getGeoViewStore(id));

**Review by jolevesq — COMMENTED** [review]
> Reviewed 4 of 8 files at r4, 2 of 2 files at r5, 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740)* status: 31 of 32 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 8 files at r4, 1 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740)* status: all files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan, @github-advanced-security[bot], and @ychoquet)

___
*[`packages/geoview-core/public/templates/sandbox.html` line 181 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#gh-1473089949:-NpWDVCVAtnRgi1jkGiv:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6836dd0336c5bde08ecda5db6e349b3e68eedd22/packages/geoview-core/public/templates/sandbox.html#L181)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Exception text reinterpreted as HTML

[Exception text](1) is reinterpreted as HTML without escaping meta-characters.

[Show more details](https://github.com/Canadian-Geospatial-Platform/geoview/security/code-scanning/55)
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/sandbox.html` line 181 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#gh-1473336040:-NpWDVeY9eccB4-yflAA:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1d2700fd7d03436b1a0f6da2f4564f143a527bc/packages/geoview-core/public/templates/sandbox.html#L181)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Exception text reinterpreted as HTML

[Exception text](1) is reinterpreted as HTML without escaping meta-characters.

[Show more details](https://github.com/Canadian-Geospatial-Platform/geoview/security/code-scanning/56)
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740)* status: all files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan, @github-advanced-security[bot], and @ychoquet)

___
*[`packages/geoview-core/src/core/stores/stores-managers.ts` line 57 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1740#-NpVvoSU1nMbeeLCsPJV:-NpWDb7R2hXVqdO8ODS5:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1d2700fd7d03436b1a0f6da2f4564f143a527bc/packages/geoview-core/src/core/stores/stores-managers.ts#L57)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Si tu veux te sauver un Promise d'un Promise, tu peux écrire ça en one-liner ainsi:

return whenThisThen(() => getGeoViewStore(id));
</blockquote></details>

Done.

**Pull request merged**
