### PR TITLE
feat(swiper): Add first version of swiper core package

### LINKED ISSUE #666: Create basic swiper package

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #666

- - -
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686)* status: 0 of 23 files reviewed, 1 unresolved discussion (waiting on @ychoquet)

___
*[`packages/geoview-swiper/src/swiper.tsx` line 195 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHj3Xek2MxjQOdUqK14:-NHj3Xek2MxjQOdUqK15:b-51b4sz) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L195)):*
> ```XML
>       const olLayer = geoviewLayers[`${layer}`].gvLayers;
>       setOlLayers((prevArray) => [...prevArray, olLayer]);
>       olLayer?.on(['precompose', 'prerender'], prerender);
> ```

I have TypeScript type error...

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686)* status: 0 of 23 files reviewed, 2 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-swiper/src/swiper.tsx` line 134 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHj5KZL4y0sgNrv9S0x:-NHj5KZM4R5x92JewvtX:b-24yy8x) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L134)):*
> I have TypeScript type error...

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686)* status: 0 of 23 files reviewed, 4 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-swiper/src/swiper.tsx` line 184 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHj5TMu32KNfEcruRL1:-NHj5TMu32KNfEcruRL2:b-51b4sz) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L184)):*
> ```XML
>     // force VectorImage to refresh
>     olLayers.forEach((layer: BaseLayer) => {
>       if (typeof layer.getImageRatio === 'function') layer?.changed();
> ```

I have TypeScript type error...
___
*[`packages/geoview-swiper/src/swiper.tsx` line 205 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHj5Qsw3-ZCVpuSVLRl:-NHj5Qsw3-ZCVpuSVLRm:b-51b4sz) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L205)):*
> ```XML
>       layersIds.forEach((layer: string) => {
>         const olLayer = geoviewLayers[`${layer}`].gvLayers;
>         olLayer?.un(['precompose', 'prerender'], prerender);
> ```

I have TypeScript type error...

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686)* status: 0 of 23 files reviewed, 5 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-swiper/src/swiper.tsx` line 193 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHj6VdZ7KGaBWZLZOol:-NHj6VdZ7KGaBWZLZOom:be7ikzt) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L193)):*
> ```XML
>     // set listener for layers in config array
>     layersIds.forEach((layer: string) => {
>       const olLayer = geoviewLayers[`${layer}`].gvLayers;
> ```

On map3, some layers are not loaded when the code hit this section

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686)* status: all files reviewed, 15 unresolved discussions (waiting on @jolevesq)

___
*[`README.md` line 30 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHk-MVGEZ2ULMq9VG6c:-NHk-MVGEZ2ULMq9VG6d:bare5tx) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/README.md#L30)):*
> ```Markdown
> 
> - [geoview-swiper](packages/geoview-swiper) - a package that enable a swiper control to tooggle visibility of layers from one side to theother seide of the swiper bar.
> ```

Typo: the other side



_Code quote:_
```Markdown
theother seide
```
___
*[`packages/geoview-swiper/README.md` line 3 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHk0VIJ9gnwnvogzlfN:-NHk0VIJ9gnwnvogzlfO:b1h3az) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/README.md#L3)):*
> ```Markdown
> # geoview-swiper
> 
> a package that enable a swiper control to tooggle visibility of layers from one side to theother seide of the swiper bar. This package is based on the following sample:
> ```

Type: the other side



_Code quote:_
```Markdown
theother seide
```
___
*[`packages/geoview-swiper/src/swiper.tsx` line 10 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkLJE61PPPZdXmoHhH:-NHkLJE7-YlR1YlyF0Ut:b-g4youa) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L10)):*
> ```XML
> import RenderEvent from 'ol/render/Event';
> import BaseLayer from 'ol/layer/Base';
> ```

for the type problems, insert this here:



_Code snippet:_
```XML
import { VectorImage } from 'ol/layer';
import VectorSource from 'ol/source/Vector';
import { EventTypes } from 'ol/Observable';
import BaseEvent from 'ol/events/Event';
```
___
*[`packages/geoview-swiper/src/swiper.tsx` line 113 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkLlHF7VCcSNmnSm9Y:-NHkLlHF7VCcSNmnSm9Z:buzbesz) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L113)):*
> ```XML
>   const [layersIds] = useState<string[]>(config.layers);
>   const [geoviewLayers] = useState(api.map(mapId).layer.geoviewLayers);
>   const [olLayers, setOlLayers] = useState([]);
> ```

For the Type problems, replace the code quote with:
    const [olLayers, setOlLayers] = useState<BaseLayer[]>([]);



_Suggestion:_
```XML
const [olLayers, setOlLayers] = useState([]);
```
___
*[`packages/geoview-swiper/src/swiper.tsx` line 121 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkMFlP2dvm_jYs3HxU:-NHkMFlP2dvm_jYs3HxV:btj0gv0) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L121)):*
> ```XML
>    * Pre compose, Pre render event callback
>    * @param {RenderEvent} evt The pre compose, pre render event
>    * @private
> ```

For the Type problems, replace the code quote with:
   * @param {Event | BaseEvent} event The pre compose, pre render event



_Code quote:_
```XML
   * @param {RenderEvent} evt The pre compose, pre render event
```
___
*[`packages/geoview-swiper/src/swiper.tsx` line 121 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkOgOb7ptQtWS8BM3H:-NHkOgOb7ptQtWS8BM3I:b-k02g2y) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L121)):*
> ```XML
>    * Pre compose, Pre render event callback
>    * @param {RenderEvent} evt The pre compose, pre render event
>    * @private
> ```

Why @private? The function is not private.



_Code quote:_
```XML
   * @private
```
___
*[`packages/geoview-swiper/src/swiper.tsx` line 125 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkNMwXCrgBNvW3dWWC:-NHkNMwXCrgBNvW3dWWD:bmqp9ia) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L125)):*
> ```XML
>   function prerender(evt: RenderEvent) {
>     const ctx: CanvasRenderingContext2D | WebGLRenderingContext = evt.context!;
>     const width = ((mapSize.current[0] + 6) * swiperValue.current) / 100;
> ```

  For the Type problems, replace the code quote with:
function prerender(event: Event | BaseEvent) {
    const evt = event as RenderEvent;
    const ctx: CanvasRenderingContext2D = evt.context! as CanvasRenderingContext2D;



_Code quote:_
```XML
  function prerender(evt: RenderEvent) {
    const ctx: CanvasRenderingContext2D | WebGLRenderingContext = evt.context!;
```
___
*[`packages/geoview-swiper/src/swiper.tsx` line 134 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHj5KZL4y0sgNrv9S0x:-NHkQsiL3zTlc5u0upQ_:b-9objgp) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L134)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

> I have TypeScript type error...
</blockquote></details>

Apply the corrections I proposed to solve the type problems.
___
*[`packages/geoview-swiper/src/swiper.tsx` line 147 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkOA3110jk9fOFREwS:-NHkOA3110jk9fOFREwT:bqkdcmg) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L147)):*
> ```XML
>    * Post compose, Post render event callback
>    * @param {RenderEvent} evt the post compose, post render event
>    * @private
> ```

For the Type problems, replace the code quote with:
   * @param {Event | BaseEvent} event the post compose, post render event



_Code quote:_
```XML
   * @param {RenderEvent} evt the post compose, post render event
```
___
*[`packages/geoview-swiper/src/swiper.tsx` line 147 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkOtUGBqQWeqOYKn-W:-NHkOtUGBqQWeqOYKn-X:b-k02g2y) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L147)):*
> ```XML
>    * Post compose, Post render event callback
>    * @param {RenderEvent} evt the post compose, post render event
>    * @private
> ```

Why @private? The function is not private.



_Code quote:_
```XML
   * @private
```
___
*[`packages/geoview-swiper/src/swiper.tsx` line 151 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkOMcr2xFXvphc-b6e:-NHkOMcr2xFXvphc-b6f:bxrhzdu) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L151)):*
> ```XML
>   function postcompose(evt: RenderEvent) {
>     const ctx: CanvasRenderingContext2D | WebGLRenderingContext = evt.context!;
>     if (ctx instanceof WebGLRenderingContext) {
> ```

For the Type problems, replace the code quote with:
  function postcompose(event: Event | BaseEvent) {
    const evt: RenderEvent = event as RenderEvent;



_Suggestion:_
```XML
  function postcompose(evt: RenderEvent) {
```
___
*[`packages/geoview-swiper/src/swiper.tsx` line 184 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHj5TMu32KNfEcruRL1:-NHkP7Dj08P8QENtO0aR:b4qchl1) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L184)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I have TypeScript type error...
</blockquote></details>

      if (typeof (layer as VectorImage<VectorSource>).getImageRatio === 'function') layer?.changed();



_Code quote:_
```XML
      if (typeof layer.getImageRatio === 'function') layer?.changed();
```
___
*[`packages/geoview-swiper/src/swiper.tsx` line 193 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHj6VdZ7KGaBWZLZOol:-NHkQSSEBqibM0g4HZZR:bphkd8o) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L193)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

On map3, some layers are not loaded when the code hit this section 
</blockquote></details>

Maybe the PR that resolve the map ready bug will solve this problem too. I propose to wait.
___
*[`packages/geoview-swiper/src/swiper.tsx` line 195 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHj3Xek2MxjQOdUqK14:-NHkPbm77m0dyrfGnKGu:b-fwcweo) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L195)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I have TypeScript type error...
</blockquote></details>

      setOlLayers((prevArray) => [...prevArray, olLayer!]);
      olLayer?.on(['precompose' as EventTypes, 'prerender' as EventTypes], prerender);
      olLayer?.on(['postcompose' as EventTypes, 'postrender' as EventTypes], postcompose);

      // force VectorImage to refresh
      if (typeof (olLayer as VectorImage<VectorSource>)?.getImageRatio === 'function') olLayer?.changed();
___
*[`packages/geoview-swiper/src/swiper.tsx` line 205 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHj5Qsw3-ZCVpuSVLRl:-NHkPvEJ0L_wGAPKSUI9:b-nrwbp4) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L205)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I have TypeScript type error...
</blockquote></details>

        olLayer?.un(['precompose' as EventTypes, 'prerender' as EventTypes], prerender);
        olLayer?.un(['postcompose' as EventTypes, 'postrender' as EventTypes], postcompose);

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686)* status: 20 of 23 files reviewed, 12 unresolved discussions (waiting on @param, @Private, and @ychoquet)

___
*[`README.md` line 30 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHk-MVGEZ2ULMq9VG6c:-NI3ntrb-icOduaEQQ6k:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/README.md#L30)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Typo: the other side
</blockquote></details>

Done.
___
*[`packages/geoview-swiper/README.md` line 3 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHk0VIJ9gnwnvogzlfN:-NI3nuIiDpSy3Idq9mZB:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/README.md#L3)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Type: the other side
</blockquote></details>

Done.
___
*[`packages/geoview-swiper/src/swiper.tsx` line 10 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkLJE61PPPZdXmoHhH:-NI3nwRr25Hx5rYv1cUU:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L10)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

for the type problems, insert this here:
</blockquote></details>

Done.
___
*[`packages/geoview-swiper/src/swiper.tsx` line 113 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkLlHF7VCcSNmnSm9Y:-NI3nyA997IVPpenOi7e:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L113)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

For the Type problems, replace the code quote with:
    const [olLayers, setOlLayers] = useState<BaseLayer[]>([]);
</blockquote></details>

Done.
___
*[`packages/geoview-swiper/src/swiper.tsx` line 121 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkMFlP2dvm_jYs3HxU:-NI3o0Y2DWk8n2hVil3b:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L121)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

For the Type problems, replace the code quote with:
   * @param {Event | BaseEvent} event The pre compose, pre render event

</blockquote></details>

Done.
___
*[`packages/geoview-swiper/src/swiper.tsx` line 121 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkOgOb7ptQtWS8BM3H:-NI3o9rU8hCY7QLZ59PB:b-q6u2dl) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L121)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Why @private? The function is not private.
</blockquote></details>

It is internal to the exported function so not accessible from outside. This is not considered private?
___
*[`packages/geoview-swiper/src/swiper.tsx` line 125 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkNMwXCrgBNvW3dWWC:-NI3oKWE201dkWkIQKsb:b-b24bve) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L125)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

  For the Type problems, replace the code quote with:
function prerender(event: Event | BaseEvent) {
    const evt = event as RenderEvent;
    const ctx: CanvasRenderingContext2D = evt.context! as CanvasRenderingContext2D;

</blockquote></details>

Done but kept WebGl as context can be of this type too
___
*[`packages/geoview-swiper/src/swiper.tsx` line 147 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkOA3110jk9fOFREwS:-NI3oSWq-tc3p3wX7Ldl:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L147)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

For the Type problems, replace the code quote with:
   * @param {Event | BaseEvent} event the post compose, post render event

</blockquote></details>

Done.
___
*[`packages/geoview-swiper/src/swiper.tsx` line 147 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkOtUGBqQWeqOYKn-W:-NI3oT-950NJJ-pUlXu8:bcibkzq) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L147)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Why @private? The function is not private.
</blockquote></details>

Same comments as above
___
*[`packages/geoview-swiper/src/swiper.tsx` line 151 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkOMcr2xFXvphc-b6e:-NI3oeZ6AfLaFnLlhfXw:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L151)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

For the Type problems, replace the code quote with:
  function postcompose(event: Event | BaseEvent) {
    const evt: RenderEvent = event as RenderEvent;

</blockquote></details>

Done.

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686)* status: all files reviewed, 4 unresolved discussions (waiting on @jolevesq and @Private)

___
*[`packages/geoview-swiper/src/swiper.tsx` line 121 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkOgOb7ptQtWS8BM3H:-NI7q7y9DqvTyTpoFElX:b-b7mfh7) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L121)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It is internal to the exported function so not accessible from outside. This is not considered private?
</blockquote></details>

In this case you must declare the function as private:
private function prerender(evt: RenderEvent) {
___
*[`packages/geoview-swiper/src/swiper.tsx` line 147 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkOtUGBqQWeqOYKn-W:-NI7rPBo7cI96wZLw4Nl:b-jg6p7m) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L147)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same comments as above
</blockquote></details>

In this case you must declare the function as private:
private function postcompose(evt: RenderEvent) {
___
*[`packages/geoview-swiper/src/swiper.tsx` line 193 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHj6VdZ7KGaBWZLZOol:-NI7sBpT8G5Uw5hAb7M9:b-3qg3ks) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L193)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Maybe the PR that resolve the map ready bug will solve this problem too. I propose to wait.
</blockquote></details>

Is it still the case?

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686)* status: 22 of 23 files reviewed, 3 unresolved discussions (waiting on @Private and @ychoquet)

___
*[`packages/geoview-swiper/src/swiper.tsx` line 121 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkOgOb7ptQtWS8BM3H:-NI7uTGI-vzW7OrRk8TF:b-t5uk5w) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L121)):*
> I removed the private as I get a modifier not allowed error
___
*[`packages/geoview-swiper/src/swiper.tsx` line 147 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHkOtUGBqQWeqOYKn-W:-NI7uK3j4uSErY6XaUvh:b770w74) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L147)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

In this case you must declare the function as private:
private function postcompose(evt: RenderEvent) {
</blockquote></details>

I removed the private as I get a modifier not allowed error
___
*[`packages/geoview-swiper/src/swiper.tsx` line 193 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686#-NHj6VdZ7KGaBWZLZOol:-NI7uV_o7-8jrnaR3sLA:bsrfkwe) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1cfb2b5e795e3a02e02850e95582d4e94418af89/packages/geoview-swiper/src/swiper.tsx#L193)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Is it still the case?
</blockquote></details>

Looks good

**Review by ychoquet — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/686)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
