### PR TITLE
feat(north-arrow) Create a north arrow

### LINKED ISSUE #41: Add north arrow
Add north arrow component. Very useful when you are in LCC projection because north is not always on top.

### PR DESCRIPTION
**Pull request by yass0016**
Closes #41

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[src/components/mapctrl/north-arrow.tsx, line 6 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76#-MTMYBupEEBlOG1bHrW_:-MTMYBupEEBlOG1bHrWa:b-8lvbe6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/388c736906582ca332757eb66bf1f8df1ba37ee2/src/components/mapctrl/north-arrow.tsx#L6)):*
> ```XML
> 
> import { useMapEvent } from 'react-leaflet';
> import { makeStyles } from '@material-ui/core/styles';
> ```

Material ui import should be in the second group. Then leaflet and react-leaflett together in the third then the api import in the fourth.
___
*[src/components/mapctrl/north-arrow.tsx, line 11 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76#-MTMYXcw79azxA2YK5-c:-MTMYXcw79azxA2YK5-d:b-jr5p7a) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/388c736906582ca332757eb66bf1f8df1ba37ee2/src/components/mapctrl/north-arrow.tsx#L11)):*
> ```XML
> 
> const useStyles = makeStyles((theme) => ({
>     northArrowContainer: {
> ```

Can the styling be part of our theme class
___
*[src/components/mapctrl/north-arrow.tsx, line 20 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76#-MTMY14aBBg1vrLGJ0vW:-MTMY14aBBg1vrLGJ0vX:b-86ef92) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/388c736906582ca332757eb66bf1f8df1ba37ee2/src/components/mapctrl/north-arrow.tsx#L20)):*
> ```XML
> }));
> 
> interface NorthArrowProps {
> ```

JSDOC
___
*[src/components/mapctrl/north-arrow.tsx, line 24 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76#-MTMYdGc4A4OKclpjO8M:-MTMYdGc4A4OKclpjO8N:b-86ef92) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/388c736906582ca332757eb66bf1f8df1ba37ee2/src/components/mapctrl/north-arrow.tsx#L24)):*
> ```XML
> }
> 
> export function NorthArrow(props: NorthArrowProps): JSX.Element {
> ```

JSDOC
___
*[src/components/mapctrl/north-arrow.tsx, line 64 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76#-MTMWpCOCfONghJMZO_o:-MTMWpCOCfONghJMZO_p:b-aadb2) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/388c736906582ca332757eb66bf1f8df1ba37ee2/src/components/mapctrl/north-arrow.tsx#L64)):*
> ```XML
>     };
> 
>     const onMouseMove = useCallback((e) => {
> ```

The callback should be on moveend. The rotation modification occurs only  when the center of the map move end. 
___
*[src/components/mapctrl/north-arrow.tsx, line 82 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76#-MTMYn2FENpoK2nZ_JO8:-MTMYn2FENpoK2nZ_JO9:by7j753) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/388c736906582ca332757eb66bf1f8df1ba37ee2/src/components/mapctrl/north-arrow.tsx#L82)):*
> ```XML
>     useMapEvent('move', onMouseMove);
> 
>     const northArrow = (
> ```

Can this be part of theming as well. So we can modify the svg image whit out having to go to the class itself. Would be nice even if all icons are loaded by theming and just reuse inside class.

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @jolevesq and @melzeiny1980)

___
*[src/components/mapctrl/north-arrow.tsx, line 6 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76#-MTMYBupEEBlOG1bHrW_:-MTMZiWL5yQAEr2X8GJh:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/388c736906582ca332757eb66bf1f8df1ba37ee2/src/components/mapctrl/north-arrow.tsx#L6)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Material ui import should be in the second group. Then leaflet and react-leaflett together in the third then the api import in the fourth.
</blockquote></details>

Done.
___
*[src/components/mapctrl/north-arrow.tsx, line 11 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76#-MTMYXcw79azxA2YK5-c:-MTM_9aM2IlQypJDhZ2j:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/388c736906582ca332757eb66bf1f8df1ba37ee2/src/components/mapctrl/north-arrow.tsx#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can the styling be part of our theme class
</blockquote></details>

Done.
___
*[src/components/mapctrl/north-arrow.tsx, line 20 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76#-MTMY14aBBg1vrLGJ0vW:-MTMalhvBOLUDGDPj9hL:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/388c736906582ca332757eb66bf1f8df1ba37ee2/src/components/mapctrl/north-arrow.tsx#L20)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

JSDOC
</blockquote></details>

Done.
___
*[src/components/mapctrl/north-arrow.tsx, line 24 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76#-MTMYdGc4A4OKclpjO8M:-MTMamFZ4SakWmkGM5Pm:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/388c736906582ca332757eb66bf1f8df1ba37ee2/src/components/mapctrl/north-arrow.tsx#L24)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

JSDOC
</blockquote></details>

Done.
___
*[src/components/mapctrl/north-arrow.tsx, line 64 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76#-MTMWpCOCfONghJMZO_o:-MTMbH8v2pvquvR6jvC-:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/388c736906582ca332757eb66bf1f8df1ba37ee2/src/components/mapctrl/north-arrow.tsx#L64)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The callback should be on moveend. The rotation modification occurs only  when the center of the map move end. 
</blockquote></details>

Done.
___
*[src/components/mapctrl/north-arrow.tsx, line 82 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76#-MTMYn2FENpoK2nZ_JO8:-MTMcw4T6EuvgwHM3zTu:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/388c736906582ca332757eb66bf1f8df1ba37ee2/src/components/mapctrl/north-arrow.tsx#L82)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can this be part of theming as well. So we can modify the svg image whit out having to go to the class itself. Would be nice even if all icons are loaded by theming and just reuse inside class.
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @melzeiny1980 and @yass0016)

___
*[src/components/mapctrl/north-arrow.tsx, line 64 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76#-MTMWpCOCfONghJMZO_o:-MTMddER7QQSXdbyMq8w:b9vp383) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/388c736906582ca332757eb66bf1f8df1ba37ee2/src/components/mapctrl/north-arrow.tsx#L64)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you rename onMapMoveEnd, not onMouseMovEnd

**Review by jolevesq — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/76#-:-MTMf8jz1lwB7mKJYUeF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @melzeiny1980)

**Pull request merged**
