### PR TITLE
refactor: remove dataAccessPath from initial layer configs

### LINKED ISSUE #2537: [REFACTOR] Remove localize string for metadata url and layer name.
**Is there an existing issue for this?**
Please search to see if an issue already exists for this feature.
No

**Who request this Feature**
Individual, team, project, organization...
Geoview

**User Story**
A concise description of what you expected to happen (one paragraph).
As a developer, I want to simplify the management of language. The configuration and code will be simpler. So user will need 2 config files if their source is not bilingual or uuid.

**Implementation UI**
If needed, what user interface do you suggest, feel free to add mockups.

- Remove localize string for metadata access path
- Remove supportedLanguage is it is there.
- Remove the dataAcessPath attribute.
- Remove all localize function and type.

Plus on language change, have an attribute to ask for reload layer. If layers are uuid, it should reload with proper language.

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #2537

# Description

Removes the dataAccessPath from the source in the inital layer config source.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://damonu2.github.io/geoview/demos-navigator.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 15 of 44 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583)* status: 15 of 44 files reviewed, 2 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/schema.json` line 1493 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583#-OB7QKn67er2VW62JbT_:-OB7QKn67er2VW62JbTa:b-9x9lvf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b93e7ea6b171751b27fc29fe40d95eb2f0dd96ed/packages/geoview-core/schema.json#L1493)):*
> ```JSON
>         }
>       },
>       "required": ["geoviewLayerType", "metadataAccessPath", "listOfLayerEntryConfig"]
> ```

Is it mandatory? geocore doesn not have it
___
*[`packages/geoview-core/public/templates/demos/demo-cgdi.html` line 70 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583#-OB7Ryt_9OSw2cCwj1F1:-OB7Ryt_9OSw2cCwj1F2:b211p4d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b93e7ea6b171751b27fc29fe40d95eb2f0dd96ed/packages/geoview-core/public/templates/demos/demo-cgdi.html#L70)):*
> ```HTML
>               'listOfLayerEntryConfig': [
>                 {
>                   'layerId': 'items?f=json',
> ```

This looks weird..... should it stay hydrometric-stations for layerId but having the metadtaAccessPAth like the dataAccesssPath?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583)* status: 15 of 44 files reviewed, 3 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/public/templates/demos/demo-gsc.html` line 71 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583#-OB7SiZa3Mp494lYv7Th:-OB7SiZa3Mp494lYv7Ti:b-v9yv0s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b93e7ea6b171751b27fc29fe40d95eb2f0dd96ed/packages/geoview-core/public/templates/demos/demo-gsc.html#L71)):*
> ```HTML
>               'listOfLayerEntryConfig': [
>                 {
>                   'layerId': '46E.JSON',
> ```

Here as well... medataDataAccesssPAth it root and layerId is last section but in this case it is duplicated

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583)* status: 15 of 44 files reviewed, 4 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/public/templates/demos/demo-osdp-non-currated.html` line 114 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583#-OB7T57eB8UCc-dlt1E7:-OB7T57eB8UCc-dlt1E8:b-ybt40) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b93e7ea6b171751b27fc29fe40d95eb2f0dd96ed/packages/geoview-core/public/templates/demos/demo-osdp-non-currated.html#L114)):*
> ```HTML
>             'geoviewLayerId': 'geojsonlyr3',
>             'geoviewLayerName': 'Multi Polygon Layer',
>             'metadataAccessPath': './configs/OSDP/datasets/DDFO-CURATED-1-03336A72-E5AD-4EEE-803D-E70B7FDE9FCB_en.json',
> ```

Should it be metada.. ./configs/OSDP/datasets/ and layerId DDFO...

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 44 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583)* status: 16 of 44 files reviewed, 5 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/public/templates/layers/csv.html` line 75 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583#-OB7THPA5rY8OgdScmVN:-OB7THPA5rY8OgdScmVO:b1ayvrn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b93e7ea6b171751b27fc29fe40d95eb2f0dd96ed/packages/geoview-core/public/templates/layers/csv.html#L75)):*
> ```HTML
>               'geoviewLayerId': 'csvLYR1',
>               'geoviewLayerName': 'NPRI',
>               'metadataAccessPath': './datasets/csv-files/',
> ```

re is it good compared to the json sample
___
*[`packages/geoview-core/public/templates/layers/csv.html` line 90 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583#-OB7TO4K5BiqGbyCKXKe:-OB7TO4K5BiqGbyCKXKf:b-eq9kr3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b93e7ea6b171751b27fc29fe40d95eb2f0dd96ed/packages/geoview-core/public/templates/layers/csv.html#L90)):*
> ```HTML
>               'geoviewLayerId': 'csvLYR2',
>               'geoviewLayerName': 'Station List MELCC',
>               'metadataAccessPath': './datasets/csv-files/Station_List_Minus_HQ-MELCC.csv',
> ```

Here we have duplication again. What is the difference with the item above?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 17 of 44 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583)* status: 33 of 44 files reviewed, 9 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/public/templates/layers/geojson.html` line 172 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583#-OB7Tb-P-iCRFkPxUkJL:-OB7Tb-P-iCRFkPxUkJM:b-ik2po7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b93e7ea6b171751b27fc29fe40d95eb2f0dd96ed/packages/geoview-core/public/templates/layers/geojson.html#L172)):*
> ```HTML
>           geoviewLayerId: 'geoJsonSample',
>           geoviewLayerName: 'Historical Flood',
>           metadataAccessPath: './datasets/geojson/historical_flood_0.geojson',
> ```

duplication again
___
*[`packages/geoview-core/src/core/utils/config/validation-classes/raster-validation-classes/esri-dynamic-layer-entry-config.ts` line 30 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583#-OB7U69ZCDboIxD3fbXR:-OB7U69ZCDboIxD3fbXS:b-vs6jkr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b93e7ea6b171751b27fc29fe40d95eb2f0dd96ed/packages/geoview-core/src/core/utils/config/validation-classes/raster-validation-classes/esri-dynamic-layer-entry-config.ts#L30)):*
> ```XML
>     // We assign the metadataAccessPath of the GeoView layer to dataAccessPath.
>     if (!this.source) this.source = {};
>     this.source.dataAccessPath = this.geoviewLayerConfig.metadataAccessPath;
> ```

workaround to keep dataAccessPath internal but remove from schema? If so we need a GV comment.

If we need some tweeking, because each class has it, we may do it here. In new config, this is not there anymore, we need comment implement behaviour in  new structure when we progress in the refactor. Please add TODO comment in each class
___
*[`packages/geoview-core/src/core/utils/config/validation-classes/raster-validation-classes/xyz-layer-entry-config.ts` line 19 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583#-OB7V39u123B1cXNlNrJ:-OB7V39u123B1cXNlNrK:b-jkphiw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b93e7ea6b171751b27fc29fe40d95eb2f0dd96ed/packages/geoview-core/src/core/utils/config/validation-classes/raster-validation-classes/xyz-layer-entry-config.ts#L19)):*
> ```XML
>     if (!this.source.dataAccessPath.endsWith('{z}/{y}/{x}'))
>       this.source.dataAccessPath = this.source.dataAccessPath!.endsWith('/')
>         ? `${this.source.dataAccessPath}tile/{z}/{y}/{x}`
> ```

I like the way we tweak it so config is clean and internal stuff if added after
___
*[`packages/geoview-core/src/geo/map/map-schema-types.ts` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583#-OB7VN-wBRwnXxmub6lU:-OB7VN-wBRwnXxmub6lV:b-1cepp9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b93e7ea6b171751b27fc29fe40d95eb2f0dd96ed/packages/geoview-core/src/geo/map/map-schema-types.ts#L79)):*
> ```XML
>    */
>   nameField?: string;
>   /** Array of the outfield objects. */
> ```

Have you looked at the map-schema type in config api to see if it need to be modify as well

**Review by Alex-NRCan — APPROVED** [review]
General question. Was this PR tested with `HYBRID_MODE = true`? It should(?) be transparent, so I understand it wasn't, but I'd like to make sure we don't hit an unforeseen issue, notably with the 'source' property being removed and whatnot.

> Reviewed 44 of 44 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583#-:-OBRUIck8B21Wk5V-HXl:b-4suwcs)* status: all files reviewed, 9 unresolved discussions (waiting on @DamonU2)

**Review by DamonU2 — COMMENTED** [review]
It was

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583#-:-OBVrWuj-u0v2r-EjZza:bumij89)* status: all files reviewed, 9 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/schema.json` line 1493 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583#-OB7QKn67er2VW62JbT_:-OB7XSYz8OE5aG6FR1mj:byvqges) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b93e7ea6b171751b27fc29fe40d95eb2f0dd96ed/packages/geoview-core/schema.json#L1493)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is it mandatory? geocore doesn not have it
</blockquote></details>

Oops, good catch

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583)* status: all files reviewed, 9 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/demos/demo-cgdi.html` line 70 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583#-OB7Ryt_9OSw2cCwj1F1:-OBVy3ks457y44zxCGMz:bz98xjg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b93e7ea6b171751b27fc29fe40d95eb2f0dd96ed/packages/geoview-core/public/templates/demos/demo-cgdi.html#L70)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This looks weird..... should it stay hydrometric-stations for layerId but having the metadtaAccessPAth like the dataAccesssPath?
</blockquote></details>

It can't. The first path has the metadata and needs "items" added to fetch the layer data
___
*[`packages/geoview-core/public/templates/demos/demo-gsc.html` line 71 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583#-OB7SiZa3Mp494lYv7Th:-OBXTTNJ4tklscbnQtyS:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b93e7ea6b171751b27fc29fe40d95eb2f0dd96ed/packages/geoview-core/public/templates/demos/demo-gsc.html#L71)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Here as well... medataDataAccesssPAth it root and layerId is last section but in this case it is duplicated
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/demos/demo-osdp-non-currated.html` line 114 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583#-OB7T57eB8UCc-dlt1E7:-OBXTSUa7RwrXs9X1XS1:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b93e7ea6b171751b27fc29fe40d95eb2f0dd96ed/packages/geoview-core/public/templates/demos/demo-osdp-non-currated.html#L114)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should it be metada.. ./configs/OSDP/datasets/ and layerId DDFO...
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/layers/csv.html` line 90 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583#-OB7TO4K5BiqGbyCKXKe:-OBXTXyZE-zu6ex5hOf_:b1bpw6e) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b93e7ea6b171751b27fc29fe40d95eb2f0dd96ed/packages/geoview-core/public/templates/layers/csv.html#L90)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Here we have duplication again. What is the difference with the item above?
</blockquote></details>

Just testing to make sure it worked if entered either way
___
*[`packages/geoview-core/public/templates/layers/geojson.html` line 172 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583#-OB7Tb-P-iCRFkPxUkJL:-OBXTkjD5WfQA1J0nDpk:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b93e7ea6b171751b27fc29fe40d95eb2f0dd96ed/packages/geoview-core/public/templates/layers/geojson.html#L172)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

duplication again
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 4 of 44 files at r1, 26 of 26 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Review by jolevesq — APPROVED** [review]
> Reviewed 6 of 6 files at r3, 3 of 3 files at r4, 6 of 6 files at r5, 28 of 30 files at r6, 11 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2583)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
