### PR TITLE
Rebase update dependencies

### LINKED ISSUE #2555: Update dependencies

### PR DESCRIPTION
**Pull request by PVautour**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #2555 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

It was deployed to gh pages and tested manually.

https://pvautour.github.io/geoview/api-functions-test.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559)

### CODE REVIEW

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 15 of 136 files at r1, 3 of 8 files at r2, 18 of 120 files at r3, 107 of 107 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq and @PVautour)

___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 23 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559#-OAYMQiC9IoIO-QuGJSy:-OAYMQiC9IoIO-QuGJSz:b3ydaa4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8bc9a7ec4dcb3bc763f4ffd901f446699d1e16ad/packages/geoview-core/src/core/stores/geoview-store.ts#L23)):*
> ```XML
> export type TypeSetStore = (
>   partial: IGeoviewState | Partial<IGeoviewState> | ((state: IGeoviewState) => IGeoviewState | Partial<IGeoviewState>),
>   replace?: false | undefined
> ```

Can it only be false or undefined? Seems weird

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 4 of 136 files at r1, 2 of 8 files at r2, 2 of 120 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559)* status: all files reviewed, 3 unresolved discussions (waiting on @PVautour)

___
*[`packages/.eslintrc` line 37 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559#-OAYbyhb5h-FAcOL8Bk8:-OAYbyhb5h-FAcOL8Bk9:bdbjbtx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8bc9a7ec4dcb3bc763f4ffd901f446699d1e16ad/packages/.eslintrc#L37)):*
> ```
>     "no-useless-constructor": "off",
>     "@typescript-eslint/no-useless-constructor": "error",
>     "@typescript-eslint/no-unused-vars": "warn",
> ```

Why did you removed the error?
___
*[`packages/geoview-core/package.json` line 38 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559#-OAYctrmAusICO0w5gm3:-OAYctrmAusICO0w5gm4:b-krv8o7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8bc9a7ec4dcb3bc763f4ffd901f446699d1e16ad/packages/geoview-core/package.json#L38)):*
> ```JSON
>     "test": "jest",
>     "update_test": "jest --updateSnapshot",
>     "format": "npm run format --prefix ../",
> ```

This prefix thing goes up a level and find the same function in the root package.json?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 6 of 136 files at r1, 7 of 120 files at r3, 1 of 107 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559)* status: all files reviewed, 4 unresolved discussions (waiting on @PVautour)

___
*[`packages/geoview-core/src/core/components/map-info/map-info.tsx` line 37 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559#-OAYfJsABg3MPwBOYZbv:-OAYfJsABg3MPwBOYZbw:bf0acyo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8bc9a7ec4dcb3bc763f4ffd901f446699d1e16ad/packages/geoview-core/src/core/components/map-info/map-info.tsx#L37)):*
> ```XML
>     <Box
>       sx={{
>         display: 'flex',
> ```

Le sx est dans le fichier de style associé au composante. Ce n'est pas toujours respecté mais le plus possible on voudrais avoir le style dans le fichier de style et pas de css dans le sx du composante

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559)* status: all files reviewed, 5 unresolved discussions (waiting on @PVautour)

___
*[`packages/geoview-core/src/core/components/map-info/map-info.tsx` line 44 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559#-OAYfjFz4vUzFuDJzVG6:-OAYfjFz4vUzFuDJzVG7:b-1g5qca) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d55a8d9559e870f567dd41b5723ff0228be1499b/packages/geoview-core/src/core/components/map-info/map-info.tsx#L44)):*
> ```XML
>   return (
>     <Box
>       id={`${mapId}-mapInfo`}
> ```

Is there a place where this id is access?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559)* status: all files reviewed, 6 unresolved discussions (waiting on @PVautour)

___
*[`packages/geoview-core/src/core/components/map-info/map-info-expand-button.tsx` line 17 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559#-OAYgqVAALbnuuj01LD5:-OAYgqVAALbnuuj01LD6:b-tx29l0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d55a8d9559e870f567dd41b5723ff0228be1499b/packages/geoview-core/src/core/components/map-info/map-info-expand-button.tsx#L17)):*
> ```XML
> export function MapInfoExpandButton(): JSX.Element {
>   const theme = useTheme();
>   const sxClasses = getSxClasses(theme);
> ```

We try to use sxClasses as much as we can

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559)* status: all files reviewed, 7 unresolved discussions (waiting on @PVautour)

___
*[`packages/geoview-core/src/core/components/map-info/map-info-style.ts` line 6 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559#-OAYhxbk5L-G8aqlb_pl:-OAYhxbk5L-G8aqlb_pm:bl1qb10) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d55a8d9559e870f567dd41b5723ff0228be1499b/packages/geoview-core/src/core/components/map-info/map-info-style.ts#L6)):*
> ```XML
> // ? I doubt we want to define an explicit type for style properties?
> // eslint-disable-next-line @typescript-eslint/no-explicit-any
> export const getSxClasses = (theme: Theme): any => ({
> ```

Why have you removed a lot of the style to put it directly in the sx element of HTML tag?

**Comment by PVautour** [comment]
> > Reviewed 15 of 136 files at r1, 3 of 8 files at r2, 18 of 120 files at r3, 107 of 107 files at r4, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559)_ status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq and @PVautour)
> 
> _[`packages/geoview-core/src/core/stores/geoview-store.ts` line 23 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559#-OAYMQiC9IoIO-QuGJSy:-OAYMQiC9IoIO-QuGJSz:b3ydaa4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8bc9a7ec4dcb3bc763f4ffd901f446699d1e16ad/packages/geoview-core/src/core/stores/geoview-store.ts#L23)):_
> 
> > ```
> > export type TypeSetStore = (
> >   partial: IGeoviewState | Partial<IGeoviewState> | ((state: IGeoviewState) => IGeoviewState | Partial<IGeoviewState>),
> >   replace?: false | undefined
> > ```
> 
> Can it only be false or undefined? Seems weird

Yes it's weird, but typescript inferred this from the code. It should be correct. Obviously this should become an optional boolean, but for now it would throw a typescript error. I prefer to use the "stricter type" rather that disabling the eslint until we figure out what it does.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 5 of 136 files at r1, 9 of 120 files at r3, 101 of 107 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559)* status: all files reviewed, 7 unresolved discussions (waiting on @DamonU2 and @PVautour)

**Comment by PVautour** [comment]
> > Reviewed 4 of 136 files at r1, 2 of 8 files at r2, 2 of 120 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559)_ status: all files reviewed, 3 unresolved discussions (waiting on @PVautour)
> 
> _[`packages/.eslintrc` line 37 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559#-OAYbyhb5h-FAcOL8Bk8:-OAYbyhb5h-FAcOL8Bk9:bdbjbtx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8bc9a7ec4dcb3bc763f4ffd901f446699d1e16ad/packages/.eslintrc#L37)):_
> 
> > ```
> >     "no-useless-constructor": "off",
> >     "@typescript-eslint/no-useless-constructor": "error",
> >     "@typescript-eslint/no-unused-vars": "warn",
> > ```
> 
> Why did you removed the error?
> 

I removed the error because now that all files are parse, there are no unused var errors preventing from compiling. However those unused vars are not nececerally bad. They are simply use to store errors in prevision of adding error handling.

> _[`packages/geoview-core/package.json` line 38 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559#-OAYctrmAusICO0w5gm3:-OAYctrmAusICO0w5gm4:b-krv8o7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8bc9a7ec4dcb3bc763f4ffd901f446699d1e16ad/packages/geoview-core/package.json#L38)):_
> 
> > ```json
> >     "test": "jest",
> >     "update_test": "jest --updateSnapshot",
> >     "format": "npm run format --prefix ../",
> > ```
> 
> This prefix thing goes up a level and find the same function in the root package.json?

Yes it calls npm run format from the parent. Therefore it goes over all the files in `/packages/`.

**Comment by PVautour** [comment]
> > Reviewed 6 of 136 files at r1, 7 of 120 files at r3, 1 of 107 files at r4.
> > _[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559)_ status: all files reviewed, 4 unresolved discussions (waiting on @PVautour)
> 
> _[`packages/geoview-core/src/core/components/map-info/map-info.tsx` line 37 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559#-OAYfJsABg3MPwBOYZbv:-OAYfJsABg3MPwBOYZbw:bf0acyo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8bc9a7ec4dcb3bc763f4ffd901f446699d1e16ad/packages/geoview-core/src/core/components/map-info/map-info.tsx#L37)):_
> 
> > ```
> >     <Box
> >       sx={{
> >         display: 'flex',
> > ```
> 
> Le sx est dans le fichier de style associé au composante. Ce n'est pas toujours respecté mais le plus possible on voudrais avoir le style dans le fichier de style et pas de css dans le sx du composante

Ok ca peut être changé sans problème!

**Comment by PVautour** [comment]
> > _[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559)_ status: all files reviewed, 5 unresolved discussions (waiting on @PVautour)
> 
> _[`packages/geoview-core/src/core/components/map-info/map-info.tsx` line 44 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559#-OAYfjFz4vUzFuDJzVG6:-OAYfjFz4vUzFuDJzVG7:b-1g5qca) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d55a8d9559e870f567dd41b5723ff0228be1499b/packages/geoview-core/src/core/components/map-info/map-info.tsx#L44)):_
> 
> > ```
> >   return (
> >     <Box
> >       id={`${mapId}-mapInfo`}
> > ```
> 
> Is there a place where this id is access?

Good catch, I believe this whole section of code can be removed:

```JSX

  const mapInfoExpanded = useUIMapInfoExpanded();

...

  /**
   * Update the height of the panel when the mapInfo is expanded
   */
  useEffect(() => {
    const mapInfo = document.getElementById(`${mapId}-mapInfo`);
    if (panelContainerRef.current && open && mapInfo) {
      const mapInfoHeight = mapInfo.getBoundingClientRect().height;
      panelContainerRef.current.style.height = `calc(100%  - ${mapInfoHeight}px)`;
    }
  }, [mapInfoExpanded, mapSize, open, mapId]);

```

**Comment by PVautour** [comment]
> > _[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559)_ status: all files reviewed, 7 unresolved discussions (waiting on @PVautour)
> 
> _[`packages/geoview-core/src/core/components/map-info/map-info-style.ts` line 6 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2559#-OAYhxbk5L-G8aqlb_pl:-OAYhxbk5L-G8aqlb_pm:bl1qb10) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d55a8d9559e870f567dd41b5723ff0228be1499b/packages/geoview-core/src/core/components/map-info/map-info-style.ts#L6)):_
> 
> > ```
> > // ? I doubt we want to define an explicit type for style properties?
> > // eslint-disable-next-line @typescript-eslint/no-explicit-any
> > export const getSxClasses = (theme: Theme): any => ({
> > ```
> 
> Why have you removed a lot of the style to put it directly in the sx element of HTML tag?

I was not familiar with the sxStyle way of doing things. It's an artifact from using tailwindscss where I tend to put the css in the html so everything is close together. Only creating classes when there is alot of custom css and it affects readability. 

This is more a question of preferences / habits than anything else. 

I can certainly move it into the theme file.

**Pull request merged**
