### PR TITLE
feat(demo): All layers and CGDI catalogue page added

### PR DESCRIPTION
**Pull request by DamonU2**
# Description

Added a demo page with all layer types for testing, also added a page for the CGDI catalogue

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://damonu2.github.io/geoview/all-layers.html
https://damonu2.github.io/geoview/water-resources.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1744)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1744)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @DamonU2)

___
*[`packages/geoview-core/public/templates/layers/water-resources.html` line 25 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1744#-NpVBUhT9KXctjYBRMQk:-NpVBUhU4ArszvewoUYI:bbiq7r8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/dd4ca2b0351a03f22863b3c65af4d6d045b0c6e2/packages/geoview-core/public/templates/layers/water-resources.html#L25)):*
> ```HTML
>             <td>logo</td>
>             <td class="header-title">
>               <h1><strong>All Layers</strong></h1>
> ```

Can you just make this page about CGDI demo. It can be a section below all layer type called CGDI starter kit. Update info in title and header for CGDI

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1744)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/layers/water-resources.html` line 25 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1744#-NpVBUhT9KXctjYBRMQk:-NpVZkFt-W2d2bPB3ynt:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/dd4ca2b0351a03f22863b3c65af4d6d045b0c6e2/packages/geoview-core/public/templates/layers/water-resources.html#L25)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you just make this page about CGDI demo. It can be a section below all layer type called CGDI starter kit. Update info in title and header for CGDI
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1744)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @DamonU2)

**Review by jolevesq — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1744)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1744)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
