### PR TITLE
GeoChart Plugin in footer and general Plugin partial refactor

### LINKED ISSUE #1568: [BUG] <Update GeoChart Plugin>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Geochart plugin fetch the layers from store and display the chart.
This functionality works only for one layer at a time. 

We need to update the geochart plugin, where all the layers which have charts, fetch the data when component mounts, instead of layer click on map.

### Expected Behavior

We need to update the geochart plugin, where all the layers which have charts, fetch the data when component mounts, instead of layer click on map.

### Steps To Reproduce

1) Visit https://kaminderpal.github.io/geoview/package-footer-panel-geochart.html
2) Click on Geo chart tab in footer panel
3) All the layers which have charts are displayed but charts are not displayed for each layer.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

This PR puts the GeoChart Plugin in the footer by using a new "FooterPlugin" mechanism.

AbstractPlugin now has FooterPlugin, AppBarPlugin and MapPlugin:
- GeoChartFooterPlugin now a FooterPlugin
- GeoChartAppBarPlugin now a AppBarPlugin
- BasemapPanelPlugin now a AppBarPlugin
- LayersPanelPlugin now a AppBarPlugin
- TimeSliderPlugin now a FooterPlugin
- Swiper plugin now using MapPlugin
- FooterPanelPlugin now a AbstractPlugin

Tabs now using a React.ElementType instead of ReactNode (seems to be working better)

Fixes #1568

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Hosted here: [https://alex-nrcan.github.io/geoview/](https://alex-nrcan.github.io/geoview/)

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
> Reviewed 26 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606)* status: 26 of 27 files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/api/plugin/abstract-plugin.ts` line 43 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-NlZxHXXDse72pSiQxAp:-NlZxHXXDse72pSiQxAq:b-xk7byw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f8170bc11a0a15be3c066e046f0de0409cc2d9f/packages/geoview-core/src/api/plugin/abstract-plugin.ts#L43)):*
> ```XML
>   // Plugin createElement object
>   // TODO: Refactor - Plugin - Why createElement? - I'll just comment it out for now, as I've made it work another way in this refactor
>   // createElement?: typeof React.createElement;
> ```

Was to create react root element. If we have another way it is ok
___
*[`packages/geoview-core/src/api/plugin/abstract-plugin.ts` line 47 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-NlZxM821_KATIVpfbyp:-NlZxM821_KATIVpfbyq:b-jk33cs) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f8170bc11a0a15be3c066e046f0de0409cc2d9f/packages/geoview-core/src/api/plugin/abstract-plugin.ts#L47)):*
> ```XML
>   // Plugin useTheme object
>   // TODO: Refactor - Plugin - Why useTheme? - I'll just comment it out for now, as it doesn't seem to be used at all anyways (it should be commented out in plugin addPlugin too)
>   // useTheme?: typeof useTheme;
> ```

Was to use the useTheme react hook inside the plugins, if we have another way it is ok
___
*[`packages/geoview-core/src/api/plugin/abstract-plugin.ts` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-NlZzxVo9ylrmwLS66-h:-NlZzxVo9ylrmwLS66-i:b-sadj5z) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f8170bc11a0a15be3c066e046f0de0409cc2d9f/packages/geoview-core/src/api/plugin/abstract-plugin.ts#L78)):*
> ```XML
>    */
>   displayLanguage(): string {
>     return this.translate?.getI18n().language || 'en';
> ```

I think we should the app-state getDisplay from the AppEventProcessor
___
*[`packages/geoview-core/src/api/plugin/footer-plugin.ts` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-Nl_-ZtH1FackEuT3YLM:-Nl_-ZtH1FackEuT3YLN:b-qd0r85) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f8170bc11a0a15be3c066e046f0de0409cc2d9f/packages/geoview-core/src/api/plugin/footer-plugin.ts#L37)):*
> ```XML
>     const footerProps = this.onCreateContentProps();
> 
>     // Create table with the props
> ```

Typo, tab instead of table
___
*[`packages/geoview-footer-panel/src/index.tsx` line 109 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-Nl_0JfyDyWfs5rMOwe7:-Nl_0JfyDyWfs5rMOwe8:b-sr0lyi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f8170bc11a0a15be3c066e046f0de0409cc2d9f/packages/geoview-footer-panel/src/index.tsx#L109)):*
> ```XML
>       // select the details tab when map click queries are done
>       // TODO: This info should be kept in the store cause we do notlisten to layerset directly anymore
>       this.api.event.on(
> ```

I think tis whole event can be remove
___
*[`packages/geoview-swiper/src/index.tsx` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-Nl_3Y_h1sQn8Z7J_1aB:-Nl_3Y_h1sQn8Z7J_1aC:b-9z5s9s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5df7a31212a5c24707e8baeb0fed089412453015/packages/geoview-swiper/src/index.tsx#L60)):*
> ```XML
> 
>     // if there is layers in the array, initialize the swiper
>     if (cgpv && (configObj?.layers as string[]).length > 0) {
> ```

Is this in the plugin class in core^ If not how does it gets initialized?

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 2 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606)* status: 26 of 27 files reviewed, 5 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/plugin/abstract-plugin.ts` line 43 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-NlZxHXXDse72pSiQxAp:-Nlcdj3GBHS_F1rGWTvb:b-3qn15k) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f8170bc11a0a15be3c066e046f0de0409cc2d9f/packages/geoview-core/src/api/plugin/abstract-plugin.ts#L43)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Was to create react root element. If we have another way it is ok
</blockquote></details>

Yeah, that one seems redundant, I'll remove it entirely.
___
*[`packages/geoview-core/src/api/plugin/abstract-plugin.ts` line 47 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-NlZxM821_KATIVpfbyp:-NlccomuD0DOzgtkh585:brjl2mj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f8170bc11a0a15be3c066e046f0de0409cc2d9f/packages/geoview-core/src/api/plugin/abstract-plugin.ts#L47)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Was to use the useTheme react hook inside the plugins, if we have another way it is ok
</blockquote></details>

I'm not entirely sure, not familiar enough yet with everything. I'll leave it there for now with the TODO
___
*[`packages/geoview-core/src/api/plugin/abstract-plugin.ts` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-NlZzxVo9ylrmwLS66-h:-NlcdoU4C9paYoAR7DFd:bmbdwxm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f8170bc11a0a15be3c066e046f0de0409cc2d9f/packages/geoview-core/src/api/plugin/abstract-plugin.ts#L78)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think we should the app-state getDisplay from the AppEventProcessor
</blockquote></details>

Yeah, I thought about that as well, but I was wondering... Is AppEventProcessor, inside, listening on i18n?
Because for the GeoChart Component (and even the GeoChart plugin) I'm doing it more straigth forward with `const { i18n } \= useTranslation();` and then listening on `i18n.language`. Seems more natural to me as we're already call 'useTranslation()' in the components. The coupling seems more natural to me.
I'm not refusing to use AppEventProcessor either, just discussing..
___
*[`packages/geoview-core/src/api/plugin/footer-plugin.ts` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-Nl_-ZtH1FackEuT3YLM:-NlcfRtn7czxV2nI6ElX:b-dtkdrq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f8170bc11a0a15be3c066e046f0de0409cc2d9f/packages/geoview-core/src/api/plugin/footer-plugin.ts#L37)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo, tab instead of table
</blockquote></details>

Done, thanks.
___
*[`packages/geoview-footer-panel/src/index.tsx` line 109 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-Nl_0JfyDyWfs5rMOwe7:-NlcfhVv6RiDXGkALenQ:b-6soh76) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f8170bc11a0a15be3c066e046f0de0409cc2d9f/packages/geoview-footer-panel/src/index.tsx#L109)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think tis whole event can be remove
</blockquote></details>

Yeah, that TODO was already existing actually. I just copied it over when I refactored, not really sure what were the impacts.
If you're sure we can remove it, I can do it. I didn't want to change the behavior of anything in this partial refactor.
Please confirm if you're sure we can remove.
___
*[`packages/geoview-swiper/src/index.tsx` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-Nl_3Y_h1sQn8Z7J_1aB:-NlcgK0-A_eTtu1h6QCT:b-uku826) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5df7a31212a5c24707e8baeb0fed089412453015/packages/geoview-swiper/src/index.tsx#L60)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this in the plugin class in core^ If not how does it gets initialized?
</blockquote></details>

This is called automatically by the plugin initializer which executes `added` method in the AbstractPlugin abstract class which calls the onAdd() abstract method which calls the onCreateContent() method for the plugin being initialized.
That way, and the Swiper is an easy example, one can create a plugin by creating a class and inheriting the class from the right kind of plugin they want to make, override that onCreateContent method and voilà, they're basically done and can focus on their component.

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606)* status: 23 of 27 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/api/plugin/abstract-plugin.ts` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-NlZzxVo9ylrmwLS66-h:-NlcmLH17yE51zdYeIAg:brd100q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f8170bc11a0a15be3c066e046f0de0409cc2d9f/packages/geoview-core/src/api/plugin/abstract-plugin.ts#L78)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Yeah, I thought about that as well, but I was wondering... Is AppEventProcessor, inside, listening on i18n?
Because for the GeoChart Component (and even the GeoChart plugin) I'm doing it more straigth forward with `const { i18n } \= useTranslation();` and then listening on `i18n.language`. Seems more natural to me as we're already call 'useTranslation()' in the components. The coupling seems more natural to me.
I'm not refusing to use AppEventProcessor either, just discussing..
</blockquote></details>

i18n is using displayLanguage from the store when created... When I change language I change the store (like AppEventProcessor) and because i18n is using the sotre hook, it change automatically
___
*[`packages/geoview-footer-panel/src/index.tsx` line 109 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-Nl_0JfyDyWfs5rMOwe7:-Nlcowo063GA9Tj4SJrK:b-syyeo0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f8170bc11a0a15be3c066e046f0de0409cc2d9f/packages/geoview-footer-panel/src/index.tsx#L109)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Yeah, that TODO was already existing actually. I just copied it over when I refactored, not really sure what were the impacts.
If you're sure we can remove it, I can do it. I didn't want to change the behavior of anything in this partial refactor.
Please confirm if you're sure we can remove.
</blockquote></details>

I will do it in my PR.... just in case :-)
___
*[`packages/geoview-swiper/src/index.tsx` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-Nl_3Y_h1sQn8Z7J_1aB:-NlcpNbuCzGXKbYJG973:b26l23v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5df7a31212a5c24707e8baeb0fed089412453015/packages/geoview-swiper/src/index.tsx#L60)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

This is called automatically by the plugin initializer which executes `added` method in the AbstractPlugin abstract class which calls the onAdd() abstract method which calls the onCreateContent() method for the plugin being initialized.
That way, and the Swiper is an easy example, one can create a plugin by creating a class and inheriting the class from the right kind of plugin they want to make, override that onCreateContent method and voilà, they're basically done and can focus on their component.
</blockquote></details>

I will need to see, we should discuss

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 1 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606)* status: 23 of 27 files reviewed, 3 unresolved discussions (waiting on @DamonU2, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/src/api/plugin/abstract-plugin.ts` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-NlZzxVo9ylrmwLS66-h:-NldBhPmB2EjvrJQd0YM:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f8170bc11a0a15be3c066e046f0de0409cc2d9f/packages/geoview-core/src/api/plugin/abstract-plugin.ts#L78)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

i18n is using displayLanguage from the store when created... When I change language I change the store (like AppEventProcessor) and because i18n is using the sotre hook, it change automatically
</blockquote></details>

Done.
___
*[`packages/geoview-footer-panel/src/index.tsx` line 109 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-Nl_0JfyDyWfs5rMOwe7:-NldBdrm3RICF9g5M4Uv:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f8170bc11a0a15be3c066e046f0de0409cc2d9f/packages/geoview-footer-panel/src/index.tsx#L109)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I will do it in my PR.... just in case :-)
</blockquote></details>

Done.
___
*[`packages/geoview-swiper/src/index.tsx` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-Nl_3Y_h1sQn8Z7J_1aB:-NldBclp-y7t2DNfmZJ5:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5df7a31212a5c24707e8baeb0fed089412453015/packages/geoview-swiper/src/index.tsx#L60)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I will need to see, we should discuss
</blockquote></details>

Done.

**Review by DamonU2 — APPROVED** [review]
> Reviewed 1 of 27 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606)* status: all files reviewed, 3 unresolved discussions (waiting on @jolevesq and @ychoquet)

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606)* status: all files reviewed, 3 unresolved discussions (waiting on @jolevesq and @ychoquet)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> Reviewed 1 of 27 files at r1, 2 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606#-:-NliEQCwCUcqzyZDYBqX:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 14 of 14 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606)* status: 24 of 27 files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1606)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
