### PR TITLE
fix(footer-panel): remove hardcoded legend ids

### LINKED ISSUE #743: Footer panel legend event
For the moment, the footer panel use the harcoded value of the layer id. We should add event management inside the package

### LINKED ISSUE #761: Tab components removed from DOM
When switching tabs the components are removed from the DOM so all component states are lost.

Steps to reproduce:
See package-footer-panel.html, turn off a layer in legend, switch tabs, switch back to legend tab. Component is re-rendered to original state (all layers visible)

### PR DESCRIPTION
**Pull request by dayc-mapdev**
Closes #761 Closes #743

- - -
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/762)

### CODE REVIEW

**Review by dayc-mapdev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/762)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/ui/tabs/tab-panel.tsx` line 33 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/762#-NJpbB7w7qCboOf1BJo8:-NJpbB7w7qCboOf1BJo9:b-i739l4) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e195594b28d896c21dab8e71cbc2d64f86be1f8b/packages/geoview-core/src/ui/tabs/tab-panel.tsx#L33)):*
> ```XML
>       style={{ height: '100%', overflow: 'auto' }}
>     >
>       {value === index && <MaterialBox sx={{ p: 3 }}>{children}</MaterialBox>}
> ```

This fixes #761 . Tab content now remains in the DOM even if it isn't selected

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/762)* status: all files reviewed, 1 unresolved discussion (waiting on @dayc-mapdev)

___
*[`packages/geoview-core/src/ui/tabs/tab-panel.tsx` line 33 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/762#-NJpbB7w7qCboOf1BJo8:-NJq2vAH7RGCKM5I01JZ:b-paxcfn) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e195594b28d896c21dab8e71cbc2d64f86be1f8b/packages/geoview-core/src/ui/tabs/tab-panel.tsx#L33)):*
<details><summary><i>Previously, dayc-mapdev (Chris Day) wrote…</i></summary><blockquote>

This fixes #761 . Tab content now remains in the DOM even if it isn't selected
</blockquote></details>

Good!

I have this error in the console, is it related?
MUI: useResizeContainer - The parent DOM element of the data grid has an empty width.
Please make sure that this element has an intrinsic width.
The grid displays with a width of 0px.

**Review by dayc-mapdev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/762)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/ui/tabs/tab-panel.tsx` line 33 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/762#-NJpbB7w7qCboOf1BJo8:-NJqCK0u1dKdnq-oZJF6:b-720k3w) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e195594b28d896c21dab8e71cbc2d64f86be1f8b/packages/geoview-core/src/ui/tabs/tab-panel.tsx#L33)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Good!

I have this error in the console, is it related?
MUI: useResizeContainer - The parent DOM element of the data grid has an empty width.
Please make sure that this element has an intrinsic width.
The grid displays with a width of 0px.
</blockquote></details>

Yes, its trying to render the data grid tab but it has 0 width when the tab isn't selected. I think I will just suppress that warning because the DataGrid can recover without a problem once the tab is selected. The other error I get is about theme.spacing, but it looks like that is an open issue in mui-x => https://github.com/mui/mui-x/issues/5454

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/762)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dayc-mapdev)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/762)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dayc-mapdev)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/762)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dayc-mapdev)

**Pull request merged**
