### PR TITLE
feat(wcag): Add a focus trap and skip tot he map

### LINKED ISSUE #120: Add trap focus and skip navigation
Add a trap to keep focus inside the map when user is inside and a link to bypass the map.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #120

## Checklist

* [x] Commit message follow the guidelines
* [x] PR targets the correct release version
* [x] Deploy has been done
* [x] Check styling
* [ ] _Help files and documentation have been updated_
* [ ] ~Release notes have been updated~

## What's to look for styling
* Use camelCase for identifier names (variables and functions)
* Use PascalCase for type names
* Do not use "I" as a prefix for interface names
* Do not export types/functions unless you need to share it across multiple components
* All names start with a letter
* Always put spaces around operators ( = + - * / ), and after colon:
* Remove all trailing white spaces
* Look for bad indentation
* Carriage return are mandatory
  * Before comments
  * Before if condition
  * After if condition
  * Before properties
  * Before classes
  * Before functions

The use of Prettier Visual Studio Code extension let's you format automatically your code to remove most of the styling issues like white space and indentation.

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/152)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
> Reviewed 9 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/152)* status: 7 of 18 files reviewed, 2 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[src/api/event.ts, line 9 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/152#-MW0rk66-_NK6VMir_aw:-MW0rk66-_NK6VMir_ax:b-qzfszw) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/560c7378d88b9de23dfe6da6e7a76573567b8cec/src/api/event.ts#L9)):*
> ```XML
>  */
> export const EVENT_NAMES = {
>     EVENT_MAP_LOADED: 'map/loaded',
> ```

Add doc
___
*[src/components/appbar/buttons/version.tsx, line 51 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/152#-MW0sQGk6ETmOlfN3VHG:-MW0sQGk6ETmOlfN3VHH:byp18fd) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/560c7378d88b9de23dfe6da6e7a76573567b8cec/src/components/appbar/buttons/version.tsx#L51)):*
> ```XML
>         <ButtonApp
>             tooltip="appbar.version"
>             className="cgp-github"
> ```

Remove

**Review by jolevesq — COMMENTED** [review]
> Reviewed 5 of 19 files at r1, 6 of 7 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/152)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yass0016)

**Review by yass0016 — APPROVED** [review]
> Reviewed 11 of 19 files at r1, 5 of 7 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/152)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/152#-:-MW4fQC_43wnEq3ZGlTo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/152)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
