### PR TITLE
feature(demo): Add demo for OSDP configuration

### LINKED ISSUE #1812: [DEMO] Create OSDP Demo Section
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

As a OSDP member, I would like to see the curated config inside Geoview

### Implementation UI

We should have a demo section https://canadian-geospatial-platform.github.io/geoview/public/demo were we will find sub sections for different teams CGDI, OSDP....

Inside OSDP, we need one demo by curated product they have
[2024-02-07 Current OSDP RAMP Config Files.zip](https://github.com/Canadian-Geospatial-Platform/geoview/files/14297537/2024-02-07.Current.OSDP.RAMP.Config.Files.zip)

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1812

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1812

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://jolevesq.github.io/geoview/demos.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1825)

### CODE REVIEW

**Review by DamonU2 — COMMENTED** [review]
No layers load for me on: https://jolevesq.github.io/geoview/demo-osdp-land.html

> Reviewed 37 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1825#-:-Nr2eggE61mFGOu6QIfb:b-3woqeo)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 36 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1825)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1825)* status: 36 of 37 files reviewed, all discussions resolved (waiting on @DamonU2)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1825)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
