### PR TITLE
refactor(details): Improve performance

### LINKED ISSUE #2639: Performance for Details
When tested on a panel with 300 features, the rendering was very slow because it goes trough all of them.... improve

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #2639 

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
 - Remove a double query on each click
 - Remove unessacary render of all features in  a query. Only render the visible one
 
Fixes #2639

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Compare with https://canadian-geospatial-platform.github.io/geoview/public/outlier-elections-2019.html and https://canadian-geospatial-platform.github.io/geoview/public/demos-navigator.html?config=./configs/navigator/28-geocore.json

https://jolevesq.github.io/geoview/demos-navigator.html?config=./configs/navigator/28-geocore.json
https://jolevesq.github.io/geoview/outlier-elections-2019.html

There is less render (and console logs)
Faster rendering
No more panel diseaper when waiting for the component to re render, better use of skeleton

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2650)

### CODE REVIEW

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2650)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/app-start.tsx` line 1 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2650#-ODvyHQ17_rs2XuVueqT:-ODvyHQ28Zm0GKhnSdaU:b-oud46l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc3ebda97b029ef7d7b2dd33d00bca7cbd7c1a5d/packages/geoview-core/src/core/app-start.tsx#L1)):*
> ```XML
> import { createContext, StrictMode, Suspense, useMemo } from 'react';
> ```

Do we want strict mode removed?
___
*[`packages/geoview-core/src/core/components/details/feature-info-new.tsx` line 1 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2650#-ODvynJa7FcR4KVNUmUu:-ODvynJa7FcR4KVNUmUv:b-dki5ja) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc3ebda97b029ef7d7b2dd33d00bca7cbd7c1a5d/packages/geoview-core/src/core/components/details/feature-info-new.tsx#L1)):*
> ```XML
> import { useCallback, useEffect, useMemo, useState } from 'react';
> ```

Should this file be renamed? I think that the -new is from refactoring it ages ago.

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2650)* status: 9 of 14 files reviewed, 2 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/src/core/app-start.tsx` line 1 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2650#-ODvyHQ17_rs2XuVueqT:-ODwsaZc-Kl8Vt1N7aQZ:b-xcsbex) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc3ebda97b029ef7d7b2dd33d00bca7cbd7c1a5d/packages/geoview-core/src/core/app-start.tsx#L1)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Do we want strict mode removed?
</blockquote></details>

Forgot to re add, Done
___
*[`packages/geoview-core/src/core/components/details/feature-info-new.tsx` line 1 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2650#-ODvynJa7FcR4KVNUmUu:-ODwsfUDE5LK7doE4yTk:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc3ebda97b029ef7d7b2dd33d00bca7cbd7c1a5d/packages/geoview-core/src/core/components/details/feature-info-new.tsx#L1)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Should this file be renamed? I think that the -new is from refactoring it ages ago.
</blockquote></details>

Done

**Review by DamonU2 — APPROVED** [review]
> Reviewed 4 of 5 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2650)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 3 of 12 files at r1, 4 of 6 files at r2, 5 of 5 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2650)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2650)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2650)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @jolevesq)

**Pull request merged**
