### PR TITLE
887-getAllFeatureInfo_and_getFeatureInfo_result_formatting

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

Correction to a bug found in the unique value find routine in geoviewRenderer.
The values returned by the get feature info call have a new type. It contains the field names, the field types, the field values, the field aliases, the feature with its style set to the right value, the extent, the domain for esri featuresand an entry key.

Fixes # 877

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
The tests were done using the layers template.

# Checklist:

- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/914)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
Laers.html, wms layer. The Zoom to feature always goes to Africa. Must be a projection problem.

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/914#-:-NOpJumg24lx-L65o_HO:buu7gfn)* status: 0 of 24 files reviewed, all discussions resolved

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/914)* status: 19 of 24 files reviewed, 2 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 113 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/914#-NOpWg3_0wNdH5l9DJlZ:-NOpWg3_0wNdH5l9DJl_:bmpf8s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b4aed9e654d340485a16f47be7da129eed1096bd/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L113)):*
> ```XML
> 
>   /** ***************************************************************************************************************************
>    * Extract the domain of the specified field from the metadata. If the type can not be found, return 'string'.
> ```

Theses functions should not be a level higher in the abstraction instead of duplicated in layer type? Is it because it is only for Dynamic and WMS in raster layer?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts` line 104 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/914#-NOpXR0o8qSng6MgsDct:-NOpXR0o8qSng6MgsDcu:bv88mgd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b4aed9e654d340485a16f47be7da129eed1096bd/packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts#L104)):*
> ```XML
> 
>   /** ***************************************************************************************************************************
>    * Extract the domain of the specified field from the metadata. If the type can not be found, return 'string'.
> ```

Should it be at the abstract level?

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/914)* status: 19 of 24 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 113 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/914#-NOpWg3_0wNdH5l9DJlZ:-NOrpf8q3sENuBUo1OKJ:b8t06s7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b4aed9e654d340485a16f47be7da129eed1096bd/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L113)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Theses functions should not be a level higher in the abstraction instead of duplicated in layer type? Is it because it is only for Dynamic and WMS in raster layer?
</blockquote></details>

Field types and domains method are abstract in the parent class. The implementation is specific to the layer we want to instanciate. When possible, it is defined lower in the class tree as it is done for esri-dynamic and esri-feature.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts` line 104 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/914#-NOpXR0o8qSng6MgsDct:-NOrtfmr59FU9WPuHAcu:b-b5adm5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b4aed9e654d340485a16f47be7da129eed1096bd/packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts#L104)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should it be at the abstract level?
</blockquote></details>

Field types and domains method are abstract in the parent class. The implementation is specific to the layer we want to instanciate. When possible, it is defined lower in the class tree as it is done for esri-dynamic and esri-feature.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/914)* status: 10 of 24 files reviewed, 2 unresolved discussions (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> Reviewed 3 of 5 files at r2, 10 of 11 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/914)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/914#-:-NOtratvCB99kbagYtg4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
