### PR TITLE
2259 osdp geocore

### LINKED ISSUE #2259: [FEATURE] Method to handle feature info for outlier layers
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Geoview team

### User Story

We need the ability to add/correct alias fields for layers that do not provide metadata, do not build the aliases into the features, and have inconsistent feature data (ex. ea4c0bdb-a63f-49a4-b14a-09c1560aad0b). This layer lacks the first two, and different features, even in the same category, return different numbers of features, so the implemented method of handling this does not work.
Previously handled with:
https://osdp-psdo.canada.ca/dp/assets/osdp/templates/wms-bc-script.js

https://maps.canada.ca/wmsproxy/ws/wmsproxy/executeFromProxy?https://openmaps.gov.bc.ca/geo/pub/WHSE_HUMAN_CULTURAL_ECONOMIC.MPI_ECON_MAJOR_PROJECTS_POINT/ows?CRS=EPSG%3A3978&I=460&J=456&STYLES=&FORMAT=image%2Fpng&BBOX=-5654057.176149353%2C-1454941.5086360178%2C3362960.8578867167%2C4069569.540386081&SERVICE=WMS&REQUEST=GetFeatureInfo&VERSION=1.3.0&WIDTH=1136&HEIGHT=696&QUERY_LAYERS=pub%3AWHSE_HUMAN_CULTURAL_ECONOMIC.MPI_ECON_MAJOR_PROJECTS_POINT&LAYERS=pub%3AWHSE_HUMAN_CULTURAL_ECONOMIC.MPI_ECON_MAJOR_PROJECTS_POINT&INFO_FORMAT=text%2Fhtml

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by jolevesq**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

- Add the ability to extract layers config from Geocore
- Fix the issue with the details panel not opening on feature click because of panel index added to id. At the same time fix the script loading issue for packages when index is not in the id
- Fix for the third time the regex for date filter. Kept the old version in comment and kept the todo to standardize that section of code

Fixes #2259, #2531

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Hosted, October 3rd, 7:30AM

https://jolevesq.github.io/geoview/add-layers.html
- Add ea4c0bdb-a63f-49a4-b14a-09c1560aad0b, 21b821cf-0f1c-40ee-8925-eab12d357668 and see custom name, feature info and Chart
- Geocre response: https://geocore.api.geo.ca/vcs?lang=en&id=21b821cf-0f1c-40ee-8925-eab12d357668

https://jolevesq.github.io/geoview/demos-navigator.html?config=./configs/navigator/27-geocore-custom.json
- Layers added automatically

https://jolevesq.github.io/geoview/config-sandbox.html
- On first tab, replace uuid of first layer by ea4c0bdb-a63f-49a4-b14a-09c1560aad0b and select "Create .... apply user config"
- Check the updated value in the right section after pressed execute
- 
# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
> Reviewed 13 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 147 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535#-O8HHr6ZCsh8xZHYNSpB:-O8HHr6ZCsh8xZHYNSpC:b-dwjlzh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc79c837c0efb0c796ea5f59108ac29ca8e44799/packages/geoview-core/src/api/config/uuid-config-reader.ts#L147)):*
> ```XML
>                 return mergedConfig;
> 
>                 // return toJsonObject({
> ```

DEad code, add comment if we need to keep. Fix the esri dynamic as well
___
*[`packages/geoview-core/src/api/plugin/plugin.ts` line 45 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535#-O8HI8xT8cdvTq9BdtI_:-O8HI8xT8cdvTq9BdtIa:b-ljmht3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc79c837c0efb0c796ea5f59108ac29ca8e44799/packages/geoview-core/src/api/plugin/plugin.ts#L45)):*
> ```XML
>         script.src = `${scriptPath}/corePackages/geoview-${pluginId}.js`;
>         script.id = pluginId;
>         script.setAttribute('data-name', `geoview-${pluginId}`);
> ```

This may not be needed as we are only using id with query selector
___
*[`packages/geoview-geochart/src/index.tsx` line 65 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535#-O8HIYD77chjzEGigkrf:-O8HIYD77chjzEGigkrg:b-xc5zgc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc79c837c0efb0c796ea5f59108ac29ca8e44799/packages/geoview-geochart/src/index.tsx#L65)):*
> ```XML
>    */
>   override onAdd(): void {
>     // Initialize the store with geochart provided configuration in there is one
> ```

Typo if instead of in

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 10 of 14 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535)* status: all files reviewed, 5 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 62 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535#-O8HLxZ412G5kdYfli9G:-O8HLxZ5-SWqEC0NVn8U:bhkd1wz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2770bb07a9adb32f4af5c4f3ecc4bd10a1db49f1/packages/geoview-core/src/api/config/uuid-config-reader.ts#L62)):*
> ```XML
> 
>           // Get Geocore custom config layer entries values
>           // TODO: The prrof of concept is done only for WMS layers. We need to implement other layer types after the refactor
> ```

typo 'proof'
___
*[`packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts` line 124 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535#-O8HMfDm0yvAGIgxcLVu:-O8HMfDm0yvAGIgxcLVv:b-iu3994) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2770bb07a9adb32f4af5c4f3ecc4bd10a1db49f1/packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts#L124)):*
> ```XML
>                 customGeocoreLayerConfig as unknown as TypeJsonObject
>               );
>               const esriDynamicLayerEntryConfig = new EsriDynamicLayerEntryConfig(mergedConfig as unknown as EsriDynamicLayerEntryConfig);
> ```

This type of self-construct using another copy of the class has been causing many issues when we started privatizing methods with '#'. We realized that the variable sent in the constructor were NOT in fact a class, but a simple JS object casted as a class.
If it's still working, I guess we can keep for now, but this should be revised here and other places in this section.
For example, here, mergedConfig is not an EsriDynamicLayerEntryConfig. The constructor of EsriDynamicLayerEntryConfig shouldn't expect a EsriDynamicLayerEntryConfig.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535)* status: all files reviewed, 3 unresolved discussions (waiting on @DamonU2)

**Review by Alex-NRCan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2 and @jolevesq)

**Review by Alex-NRCan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts` line 124 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535#-O8HMfDm0yvAGIgxcLVu:-O8HQOLK1x_crNJWT6gg:bl645bj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2770bb07a9adb32f4af5c4f3ecc4bd10a1db49f1/packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts#L124)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is it the same way it is done in new config API? I don't think so, looks like it uses TypeJSON
```
 else if (layerType === CV_CONST_LAYER_TYPES.WMS) {
            const geoviewLayerConfig = toJsonObject({
              geoviewLayerId: `${id}`,
              geoviewLayerName: createLocalizedString(name),
              metadataAccessPath: createLocalizedString(url),
              geoviewLayerType: CV_CONST_LAYER_TYPES.WMS,
              isGeocore: true,
              isTimeAware,
            });
            (geoviewLayerConfig.listOfLayerEntryConfig as TypeJsonObject[]) = (layerEntries as TypeJsonArray).map(
              (item): TypeJsonObject => {
                const originalConfig = {
                  layerId: `${item.id}`,
                  source: {
                    serverType: serverType === undefined ? 'mapserver' : serverType,
                  },
                };

                // Overwrite default from geocore custom config
                const mergedConfig = deepMergeObjects(
                  originalConfig as unknown as TypeJsonObject,
                  customGeocoreLayerConfig as unknown as TypeJsonObject
                );

                return mergedConfig;
              }
            );
            listOfGeoviewLayerConfig.push(geoviewLayerConfig);
```

This whole file will be deleted once refactor is done
</blockquote></details>

I believe it's more in `nodeFactory` that it's now done and it looks better yes.
Here `layerConfig` is of right type, no 'as' is used.

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 14 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 62 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535#-O8IDvoV7QcEil7KdP8v:-O8IDvoV7QcEil7KdP8w:b1sk1vo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2770bb07a9adb32f4af5c4f3ecc4bd10a1db49f1/packages/geoview-core/src/core/utils/utilities.ts#L62)):*
> ```XML
>  * Check if an object is empty
>  * @param {object} obj - The object to test
>  * @returns true is object is empty, false otherwise
> ```

true is > true if

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, 10 of 11 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535)* status: all files reviewed, 6 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer-sets/abstract-layer-set.ts` line 452 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535#-O8NPg2q9mmXYrBIdl0_:-O8NPg2r7HLU-2BrX8hS:b-vtemsb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/673ef424312eb4f0ff3003b99faf310c9315437b/packages/geoview-core/src/geo/layer/layer-sets/abstract-layer-set.ts#L452)):*
> ```XML
>    * Align records with informatiom provided by OutFields from layer config.
>    * This will update fields in and delete unwanted fields from the arrayOfRecords
>    * @param {TypeLayerEntryConfig} layerPath - Path of the layerto get config from.
> ```

layerto > layer to
___
*[`packages/geoview-core/src/geo/layer/layer-sets/abstract-layer-set.ts` line 457 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535#-O8NPn8n2ztxrFnzifT1:-O8NPn8n2ztxrFnzifT2:b-api4na) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/673ef424312eb4f0ff3003b99faf310c9315437b/packages/geoview-core/src/geo/layer/layer-sets/abstract-layer-set.ts#L457)):*
> ```XML
>    * @static
>    */
>   protected static alingRecordsWithOutFields(layerEntryConfig: TypeLayerEntryConfig, arrayOfRecords: TypeFeatureInfoEntry[]): void {
> ```

alingRecordsWithOutFields > align...
___
*[`packages/geoview-core/src/geo/layer/layer-sets/all-feature-info-layer-set.ts` line 131 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535#-O8NQ0prDN-_jHT3Tia9:-O8NQ0prDN-_jHT3TiaA:b-api4na) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/673ef424312eb4f0ff3003b99faf310c9315437b/packages/geoview-core/src/geo/layer/layer-sets/all-feature-info-layer-set.ts#L131)):*
> ```XML
>         // Use the response to align arrayOfRecords fields with layerConfig fields
>         if (arrayOfRecords?.length)
>           AbstractLayerSet.alingRecordsWithOutFields(this.layerApi.getLayerEntryConfig(layerPath) as TypeLayerEntryConfig, arrayOfRecords);
> ```

alingRecordsWithOutFields > align...
___
*[`packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts` line 159 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535#-O8NQAQTEoxoAmQls4nf:-O8NQAQTEoxoAmQls4ng:b-api4na) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/673ef424312eb4f0ff3003b99faf310c9315437b/packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts#L159)):*
> ```XML
>             // Use the response to align arrayOfRecords fields with layerConfig fields
>             if (arrayOfRecords?.length)
>               AbstractLayerSet.alingRecordsWithOutFields(
> ```

alingRecordsWithOutFields > align...

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, 10 of 11 files at r4, 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535)* status: 20 of 21 files reviewed, 5 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 62 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535#-O8IDvoV7QcEil7KdP8v:-O8N1Q671ZxVf3h9n-lq:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2770bb07a9adb32f4af5c4f3ecc4bd10a1db49f1/packages/geoview-core/src/core/utils/utilities.ts#L62)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

true is > true if
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/layer-sets/abstract-layer-set.ts` line 452 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535#-O8NPg2q9mmXYrBIdl0_:-O8NWpx_3ymVduhhcC91:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/673ef424312eb4f0ff3003b99faf310c9315437b/packages/geoview-core/src/geo/layer/layer-sets/abstract-layer-set.ts#L452)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

layerto > layer to
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/layer-sets/abstract-layer-set.ts` line 457 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535#-O8NPn8n2ztxrFnzifT1:-O8NWqTl7U-1b-t131yp:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/673ef424312eb4f0ff3003b99faf310c9315437b/packages/geoview-core/src/geo/layer/layer-sets/abstract-layer-set.ts#L457)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

alingRecordsWithOutFields > align...
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/layer-sets/all-feature-info-layer-set.ts` line 131 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535#-O8NQ0prDN-_jHT3Tia9:-O8NWtlJ7w3cMClDejzZ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/673ef424312eb4f0ff3003b99faf310c9315437b/packages/geoview-core/src/geo/layer/layer-sets/all-feature-info-layer-set.ts#L131)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

alingRecordsWithOutFields > align...
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts` line 159 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535#-O8NQAQTEoxoAmQls4nf:-O8NWv-GDIyzy1ay5bF-:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/673ef424312eb4f0ff3003b99faf310c9315437b/packages/geoview-core/src/geo/layer/layer-sets/feature-info-layer-set.ts#L159)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

alingRecordsWithOutFields > align...
</blockquote></details>

Done.

**Review by DamonU2 — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2535)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
