### PR TITLE
Update Material React Table toolbar and props

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description

This PR will refactor the fetch functionality on page load instead of button click, add export button and render table in virtualized way to improve performance.

Fixes # ([1170](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1160))

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Manually tested on localhost and host environment.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1170)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
Can you pin the first 3 column by default to the left (checkbox, icon and zoom). The export is good but will need to be redone to export as GeoJSON as well to keep geometry.

Don't know if you would like to add it now but zebra style for rows

> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1170#-:-N_jFFqpBVtg1ctIuvYH:b-xgrohj)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/data-table/data-table.tsx` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1170#-N_jJtEE0oQZoflkfE9E:-N_jJtEE0oQZoflkfE9F:bg6drkl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fcf97a7133a91db95c9d6ddee82198465eab88e0/packages/geoview-core/src/core/components/data-table/data-table.tsx#L79)):*
> ```XML
>    */
>   const columns = useMemo<MRTColumnDef<ColumnsType>[]>(() => {
>     return Object.values({ icon: 'ICON', zoom: 'ZOOM', ...data.fieldAliases }).map((fieldAlias) => {
> ```

The columns name hardcoded needs to be added to translation object: en icon, fr icône
___
*[`packages/geoview-core/src/core/components/data-table/export-button.tsx` line 21 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1170#-N_jMSGo7qp4I-Cm8wVe:-N_jMSGo7qp4I-Cm8wVf:bvf2hcj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fcf97a7133a91db95c9d6ddee82198465eab88e0/packages/geoview-core/src/core/components/data-table/export-button.tsx#L21)):*
> ```XML
> function ExportButton({ dataTableData, columns }: ExportButtonProps): JSX.Element {
>   /**
>    * Build CSV Options for download.
> ```

Export button should be similar, have CSSV and GeoJSON. If not part of this PR, create a new issue for it.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1170)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/public/templates/raw-data-table.html` line 99 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1170#-N_jTy7ME2-Loa1eTtou:-N_jTy7ME2-Loa1eTtov:bkq8o00) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fcf97a7133a91db95c9d6ddee82198465eab88e0/packages/geoview-core/public/templates/raw-data-table.html#L99)):*
> ```HTML
>         result = await response.json();
> 
>         reactDOM.unmountComponentAtNode(loadingIndicator)
> ```

You should use the api add component instead of ReactDOM. It will break soon when we migrate to React 18

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1170)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/raw-data-table.html` line 99 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1170#-N_jTy7ME2-Loa1eTtou:-N_ntNMI6KxZL3KOEMuk:b-wu1gxt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fcf97a7133a91db95c9d6ddee82198465eab88e0/packages/geoview-core/public/templates/raw-data-table.html#L99)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You should use the api add component instead of ReactDOM. It will break soon when we migrate to React 18
</blockquote></details>

this needs to be replaced with https://es.react.dev/reference/react-dom/client/createRoot#root-unmount
when we migrate to React 18.
___
*[`packages/geoview-core/src/core/components/data-table/data-table.tsx` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1170#-N_jJtEE0oQZoflkfE9E:-N_nszBFCE22altTPJmI:bx1vcnj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fcf97a7133a91db95c9d6ddee82198465eab88e0/packages/geoview-core/src/core/components/data-table/data-table.tsx#L79)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The columns name hardcoded needs to be added to translation object: en icon, fr icône
</blockquote></details>

will add language support in new issue
___
*[`packages/geoview-core/src/core/components/data-table/export-button.tsx` line 21 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1170#-N_jMSGo7qp4I-Cm8wVe:-N_nsn5y6fVem92xFdfS:bbtzxa9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fcf97a7133a91db95c9d6ddee82198465eab88e0/packages/geoview-core/src/core/components/data-table/export-button.tsx#L21)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Export button should be similar, have CSSV and GeoJSON. If not part of this PR, create a new issue for it.
</blockquote></details>

i will create a new issue for this.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1170)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

___
*[`packages/geoview-core/public/templates/raw-data-table.html` line 99 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1170#-N_jTy7ME2-Loa1eTtou:-N_o9fIR7wuDV5ldmAIH:b-m9h37s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fcf97a7133a91db95c9d6ddee82198465eab88e0/packages/geoview-core/public/templates/raw-data-table.html#L99)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

this needs to be replaced with https://es.react.dev/reference/react-dom/client/createRoot#root-unmount
when we migrate to React 18.
</blockquote></details>

Let it like this I will refactor when I rebase with React 18

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1170)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Pull request merged**
