### PR TITLE
demo(clean): Clean demo and add a config file navigator

### LINKED ISSUE #2045: [FEATURE] Clean Demo Pages
**Is there an existing issue for this?**
Please search to see if an issue already exists for this feature.
no

**Who request this Feature**
Individual, team, project, organization...
Geoview

**User Story**
A concise description of what you expected to happen (one paragraph).
As a use, dev I would like to be able to navigate demo pages more easily

**Implementation UI**
If needed, what user interface do you suggest, feel free to add mockups.
Bring most of the demo to sandbox linked to a config file. For demos who do not have code section it is obvious to do this.

For other, evaluate if we keep them or not. Bring setlanguage and setTheme to sandbox

**Additional context**

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #2045

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #2045

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

hosted April 30th: 18:15: https://jolevesq.github.io/geoview/index.html and https://jolevesq.github.io/geoview/demos-navigator.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2059)

### CODE REVIEW

**Review by DamonU2 — COMMENTED** [review]
I think it would be helpful to remove preloaded layers from the first map in raw-add-layers.html, other than that, looks good.

> Reviewed 74 of 74 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2059#-:-NwjPTkm18_pnXUsLp61:bxhsfov)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
Done

> Reviewed 27 of 28 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2059#-:-NwoPLsO5z1Moywh-dG7:b-896fjx)* status: 88 of 97 files reviewed, all discussions resolved (waiting on @cphelefu, @DamonU2, and @kaminderpal)

**Comment by cphelefu** [comment]
*[`packages/geoview-core/public/templates/demos-navigator.html` line 100 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2059#-NwoPlChAJo7q7RE2Lf8:-NwoPlChAJo7q7RE2Lf9:b-5kxwd5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/da234da6a6b41f9d3ea221f34adf9e3fc3655f3c/packages/geoview-core/public/templates/demos-navigator.html#L100)):*
> ```HTML
>           <select name="Config Loader" id="configLoader">
>             <option value="">--select--</option>
>             <option value="./configs/navigator/01-basemap-LCC-TLS.json">Basemap LCC Transport-Labeled-Shaded</option>
> ```

Can this be sorted alphabetically?

**Review by kaminderpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2059)* status: 88 of 97 files reviewed, 2 unresolved discussions (waiting on @cphelefu, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 1372 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2059#-NwoQ88f2GLMs8QuduIf:-NwoQ88f2GLMs8QuduIg:bm5b5h8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/da234da6a6b41f9d3ea221f34adf9e3fc3655f3c/packages/geoview-core/src/geo/map/map-viewer.ts#L1372)):*
> ```XML
>           this.layer.removeAllGeoviewLayers();
>         } catch (err) {
>           // Failed to remove layers, eat the exception and continue to remove th map
> ```

Will it be good idea, to have error in notifications component.

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2059)* status: 88 of 97 files reviewed, 3 unresolved discussions (waiting on @cphelefu and @DamonU2)

___
*[`packages/geoview-core/public/templates/demos-navigator.html` line 98 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2059#-NwoQnnNAB9LFRrocyW7:-NwobAzg52bPoBO9yY5e:ba4a8wu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/da234da6a6b41f9d3ea221f34adf9e3fc3655f3c/packages/geoview-core/public/templates/demos-navigator.html#L98)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

If it was possible we would use this.
https://mui.com/material-ui/react-autocomplete/
</blockquote></details>

This is a raw javascript demo page. Would need more work to use our react ui. For later maybe
___
*[`packages/geoview-core/public/templates/demos-navigator.html` line 100 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2059#-NwoPlChAJo7q7RE2Lf8:-NwobIZV28ITfMnhD607:b5vdb3j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/da234da6a6b41f9d3ea221f34adf9e3fc3655f3c/packages/geoview-core/public/templates/demos-navigator.html#L100)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Can this be sorted alphabetically?
</blockquote></details>

They are group by task, we may revise later

**Review by cphelefu — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2059#-:-NwohKlx0Gqnm-W0XxUt:bnfp4nl)* status: 87 of 97 files reviewed, 1 unresolved discussion

**Pull request merged**
