### PR TITLE
1720 layer add refactoring

### LINKED ISSUE #1720: BUG-Layer Add Refactoring
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The add-new-layer.tsx file use an old method to validate and add new layers on a map. This cause code duplication and to a certain extent code discrepencies.

### Expected Behavior

We want to use the geoview classes every time we need to create and add a new layer.

### Steps To Reproduce

The code in add-new-layer.tsx is obsolete and must be replace with a new implementation.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

Current Behavior
The add-new-layer.tsx file use an old method to validate and add new layers on a map. This cause code duplication and to a certain extent code discrepencies.

Expected Behavior
We want to use the geoview classes every time we need to create and add a new layer.

The code in add-new-layer.tsx is obsolete and must be replace with a new implementation.

Fixes #1720 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
By tracing the code using the Chrome Devtools and the raw-feature-info.html template

__Deploy URL__: https://ychoquet.github.io/GeoView/raw-feature-info.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1756)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 11 of 40 files at r1, 18 of 66 files at r2, 3 of 9 files at r3, 6 of 9 files at r4, 9 of 40 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1756)* status: 36 of 73 files reviewed, 3 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-api.ts` line 85 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1756#-NpzhFdXALaSlT7wIn5E:-NpzhFdXALaSlT7wIn5F:b-sz15j1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bdf4c4b0c6242032364c9d7bc06bb9706750114d/packages/geoview-core/src/core/components/footer-bar/footer-bar-api.ts#L85)):*
> ```XML
>     const tabToSelect = this.tabs.find((tab) => tab.id === id);
>     if (tabToSelect) {
>       UIEventProcessor.setActiveFooterTab(this.mapId, id);
> ```

This function should be setActiveFooterBarTab.... has been changed by one of the rebase... we can let or you fix it in your code
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 634 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1756#-Npzi9ea9NZ9PdUYqGDj:-Npzi9ea9NZ9PdUYqGDk:bh5ohdu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bdf4c4b0c6242032364c9d7bc06bb9706750114d/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L634)):*
> ```XML
>    * @returns {Promise<boolean>} True if layer passes validation
>    */
>   const geoPackageValidation = async (): Promise<boolean> => {
> ```

All logic in this file should be in ts files... not in component. Make component too complex to debug
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 140 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1756#-NpzioGyEAf3vBn4vvdP:-NpzioGyEAf3vBn4vvdQ:b-2cdn40) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/13804b7ec88688174f921b14c47bc48cdd855d04/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L140)):*
> ```XML
>         const layer = findLayerByPath(curLayers, layerPath);
>         setVisibilityInLayerAndItems(layer as TypeLegendLayer, layer?.isVisible === 'no' ? 'yes' : 'no');
>         // TODO: verify if the isVisible value can be 'always', if so we have a bug here
> ```

Do we have a bug?

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1756)* status: 66 of 73 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-api.ts` line 85 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1756#-NpzhFdXALaSlT7wIn5E:-Npzt6NYDWdSr-rkiiP6:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bdf4c4b0c6242032364c9d7bc06bb9706750114d/packages/geoview-core/src/core/components/footer-bar/footer-bar-api.ts#L85)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This function should be setActiveFooterBarTab.... has been changed by one of the rebase... we can let or you fix it in your code
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 634 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1756#-Npzi9ea9NZ9PdUYqGDj:-NpztKm75YNtWVY2GE_5:b-9sj5y0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bdf4c4b0c6242032364c9d7bc06bb9706750114d/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L634)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

All logic in this file should be in ts files... not in component. Make component too complex to debug
</blockquote></details>

We still have work to do on this tsx file. We'll do the separation in the second phase of the layer-add-refactoring.
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 140 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1756#-NpzioGyEAf3vBn4vvdP:-Npzto4s3tVbXWigZ8vD:b-vg4h0s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/13804b7ec88688174f921b14c47bc48cdd855d04/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L140)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we have a bug?
</blockquote></details>

After verification, there is no bug here. I'll remove the TODO.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 4 of 40 files at r5.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1756)* status: 70 of 73 files reviewed, 1 unresolved discussion (waiting on @ychoquet)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 634 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1756#-Npzi9ea9NZ9PdUYqGDj:-NpzvM7u2pZ4c3nODm9n:b-qn5lbb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bdf4c4b0c6242032364c9d7bc06bb9706750114d/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L634)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

We still have work to do on this tsx file. We'll do the separation in the second phase of the layer-add-refactoring.
</blockquote></details>

Perfect!

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1756)* status: 66 of 73 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 634 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1756#-Npzi9ea9NZ9PdUYqGDj:-Nq-1TQ99P6e2Hv198Lk:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bdf4c4b0c6242032364c9d7bc06bb9706750114d/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L634)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Perfect!
</blockquote></details>

Done.

**Comment by ychoquet** [comment]
Mooving again to issue #1760

**Pull request closed without merging**
