### PR TITLE
feat(layer-panel): add new layer panel actions

### LINKED ISSUE #732: Add layer panel actions
- Expand/Collapse All
- Show/Hide All
- Set Opacity

### PR DESCRIPTION
**Pull request by dayc-mapdev**
Closes #732

- - -
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/737)

### CODE REVIEW

**Review by dayc-mapdev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/737)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/ui/slider/slider-base.tsx` line 1 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/737#-NJH6QdC2Icbfw1sbmX0:-NJH6QdC2Icbfw1sbmX1:b6f447j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/7b1d91d90be9342cc9d9b91e6b998859ae438fed/packages/geoview-core/src/ui/slider/slider-base.tsx#L1)):*
> ```XML
> /* eslint-disable react/require-default-props */
> ```

I didn't want to create a new slider component, but the other one looked too highly customized with events. This one is simple for smaller things like setting opacity
___
*[`packages/geoview-layers-panel/src/panel-content.tsx` line 231 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/737#-NJH6sAcCna6MHS9-u8c:-NJH6sAcCna6MHS9-u8d:bh06hh0) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/7b1d91d90be9342cc9d9b91e6b998859ae438fed/packages/geoview-layers-panel/src/panel-content.tsx#L231)):*
> ```XML
>             </IconButton>
>           </div>
>           <Box onClick={handleShowAddLayer}>
> ```

There is a bit of a re-design here, but I think moving "All Layers" button to the top makes better use of the available space

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 7 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/737)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @dayc-mapdev)

___
*[`packages/geoview-core/src/ui/slider/slider-base.tsx` line 1 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/737#-NJH6QdC2Icbfw1sbmX0:-NJHQKwtAwjEgctjdUJP:b-f0lxrb) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/7b1d91d90be9342cc9d9b91e6b998859ae438fed/packages/geoview-core/src/ui/slider/slider-base.tsx#L1)):*
<details><summary><i>Previously, dayc-mapdev (Chris Day) wrote…</i></summary><blockquote>

I didn't want to create a new slider component, but the other one looked too highly customized with events. This one is simple for smaller things like setting opacity
</blockquote></details>

Good idea. The other will be use to create slider for the range-time filtering. It is more complex for sure.
___
*[`packages/geoview-layers-panel/src/panel-content.tsx` line 59 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/737#-NJHQpHVEO1Y997R2aGk:-NJHQpHVEO1Y997R2aGl:b-15i9ql) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/7b1d91d90be9342cc9d9b91e6b998859ae438fed/packages/geoview-layers-panel/src/panel-content.tsx#L59)):*
> ```XML
>     en: {
>       addLayer: 'Add Layer',
>       expandAll: 'Expand Groups',
> ```

The expand all only expand the first group. Should it expand the all group (parents and children?)

**Review by dayc-mapdev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/737)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-layers-panel/src/panel-content.tsx` line 59 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/737#-NJHQpHVEO1Y997R2aGk:-NJeacoX4swt96YjvcVC:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/7b1d91d90be9342cc9d9b91e6b998859ae438fed/packages/geoview-layers-panel/src/panel-content.tsx#L59)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The expand all only expand the first group. Should it expand the all group (parents and children?)
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/737)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

**Pull request merged**
