### PR TITLE
fix feature info image and zoom button

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
This PR fixes the image and zoom button of each feature row for data table.

Fixes # ([1232](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1232))

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
image

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
1) Open `https://kaminderpal.github.io/geoview/raw-data-table.html`
2) Click on `Create Data Table From Map` button
3) Data table will be displayed in accordion
4) Open accordion.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/raw-data-table.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1236)

### CODE REVIEW

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1236)* status: all files reviewed, 4 unresolved discussions (waiting on @amir-azma, @cphelefu, and @kaminderpal)

___
*[`packages/geoview-core/src/core/components/data-table/data-table-api.ts` line 143 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1236#-NbZqMPLB4ImxWZZXthG:-NbZqMPLB4ImxWZZXthH:bhuhxws) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6e4f2d8826c01d084edfe443232640db7d2c2e39/packages/geoview-core/src/core/components/data-table/data-table-api.ts#L143)):*
> ```XML
>    * Create data table based on layer id from map.
>    * @param {string} layerId layerId of the feature added on map.
>    * @param {string} mapId id of the map.
> ```

This is not needed as it is in the constructor for the class
___
*[`packages/geoview-core/src/core/components/data-table/data-table-api.ts` line 147 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1236#-NbZsuN084WJjuLkioac:-NbZsuN084WJjuLkioad:b-9hsqdc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6e4f2d8826c01d084edfe443232640db7d2c2e39/packages/geoview-core/src/core/components/data-table/data-table-api.ts#L147)):*
> ```XML
>    */
> 
>   createDataTableByLayerId = async ({ layerId, mapId }: TypeLayerDataGridProps): Promise<ReactElement | null> => {
> ```

remove mapId
___
*[`packages/geoview-core/src/core/components/data-table/data-table-api.ts` line 171 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1236#-NbZqpY47a71xTOWpYJr:-NbZqpY47a71xTOWpYJs:b-kpgqg9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6e4f2d8826c01d084edfe443232640db7d2c2e39/packages/geoview-core/src/core/components/data-table/data-table-api.ts#L171)):*
> ```XML
>           });
> 
>         return createElement(MapDataTable, { data: data[0], layerId, mapId }, []);
> ```

mapId > this.mapId
___
*[`packages/geoview-core/src/core/components/data-table/map-data-table.tsx` line 127 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1236#-NbZsSde8uTTFNuqim6M:-NbZsSde8uTTFNuqim6N:b-ptkx05) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6e4f2d8826c01d084edfe443232640db7d2c2e39/packages/geoview-core/src/core/components/data-table/map-data-table.tsx#L127)):*
> ```XML
>             alt={feature.featureIcon?.featureInfoValue.toString()}
>             src={feature.featureIcon?.featureInfoValue.toString()}
>             style={{ ...iconImage, width: '35px', height: '35px' }}
> ```

Can we add width and height to iconImage above?

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1236)* status: all files reviewed, 4 unresolved discussions (waiting on @amir-azma, @cphelefu, and @DamonU2)

___
*[`packages/geoview-core/src/core/components/data-table/data-table-api.ts` line 143 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1236#-NbZqMPLB4ImxWZZXthG:-NbZy-d_AHwqXIXh5NtV:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6e4f2d8826c01d084edfe443232640db7d2c2e39/packages/geoview-core/src/core/components/data-table/data-table-api.ts#L143)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

This is not needed as it is in the constructor for the class
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/data-table/data-table-api.ts` line 147 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1236#-NbZsuN084WJjuLkioac:-NbZy0Aj9C4JmrHY0qKY:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6e4f2d8826c01d084edfe443232640db7d2c2e39/packages/geoview-core/src/core/components/data-table/data-table-api.ts#L147)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

remove mapId
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/data-table/data-table-api.ts` line 171 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1236#-NbZqpY47a71xTOWpYJr:-NbZy0f01czA9Ah6wMyr:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6e4f2d8826c01d084edfe443232640db7d2c2e39/packages/geoview-core/src/core/components/data-table/data-table-api.ts#L171)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

mapId > this.mapId
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/data-table/map-data-table.tsx` line 127 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1236#-NbZsSde8uTTFNuqim6M:-NbZy1X70vL58D5ctP5e:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6e4f2d8826c01d084edfe443232640db7d2c2e39/packages/geoview-core/src/core/components/data-table/map-data-table.tsx#L127)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Can we add width and height to iconImage above?
</blockquote></details>

Done.

**Review by DamonU2 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1236)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amir-azma and @cphelefu)

**Review by amir-azma — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1236)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Review by amir-azma — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1236)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
