### PR TITLE
fix(datatable): ESRI Dynamic zoom in data table fixed

### LINKED ISSUE #2215: [BUG] Fetch Geometry for feature in data table
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We needed to change the fetch all features to return geometry false for esriDynamic because some heavy geometry make the fetch fails. For t he moment because there is geometry, the zoom is disable.

### Expected Behavior

We should be able to fetch the feature when click on the zoom button if no extent is present

### Steps To Reproduce

1. https://canadian-geospatial-platform.github.io/geoview/public/demos-navigator.html?config=./configs/navigator/16-esri-dynamic.json
2. Go to data table and select one
3. Zoom is disable

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #2215

# Description

ESRI Dynamic layers will now fetch there geometries when the zoom is clicked in the data table

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/16-esri-dynamic.json

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/data-table-event-processor.ts` line 15 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0tZp-CDEveDP2Ugbl3:-O0tZp-CDEveDP2Ugbl4:b-rwbszb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a114ee3d2f56fabbdaf5620ae93d0ce9abcf676/packages/geoview-core/src/api/event-processors/event-processor-children/data-table-event-processor.ts#L15)):*
> ```XML
> import { AbstractGVVector } from '@/geo/layer/gv-layers/vector/abstract-gv-vector';
> import { TypeFeatureInfoEntry, TypeResultSetEntry } from '@/geo/map/map-schema-types';
> import { EsriDynamicLayerEntryConfig } from '@/core/utils/config/validation-classes/raster-validation-classes/esri-dynamic-layer-entry-config';
> ```

I am not sure we should leak specific layer type in store/state/processor...

Is this featureExtent function be part of the layer itself and when feature has no extent we call this function?
___
*[`packages/geoview-core/src/core/components/data-table/data-table.tsx` line 291 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0t_2XK-paMYukgwAI1:-O0t_2XL5xDI-s2F0tP6:bcad8s7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a114ee3d2f56fabbdaf5620ae93d0ce9abcf676/packages/geoview-core/src/core/components/data-table/data-table.tsx#L291)):*
> ```XML
>       let { extent } = feature;
>       if (feature.geoviewLayerType === CONST_LAYER_TYPES.ESRI_DYNAMIC && !extent) {
>         extent = await getESRIDynamicFeatureExtent(layerPath, feature);
> ```

I do not think we should have specific layer type in component.... if extent not provided the layer itself should have a function zoomToFeatureExtent and we should call it...

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341)* status: all files reviewed, 2 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/data-table-event-processor.ts` line 15 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0tZp-CDEveDP2Ugbl3:-O0tfNES2Niyf9LyMWJp:b-c9uvzo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a114ee3d2f56fabbdaf5620ae93d0ce9abcf676/packages/geoview-core/src/api/event-processors/event-processor-children/data-table-event-processor.ts#L15)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I am not sure we should leak specific layer type in store/state/processor...

Is this featureExtent function be part of the layer itself and when feature has no extent we call this function?
</blockquote></details>

Interesting yeah, hmmm.

Food for thought, can probably dig into it deeper and should probably talk about it some more than just via a reviewable comment. But at first glance, the `getESRIDynamicFeatureExtent` function kind of is reminiscent of the `getBounds` function. Function which all layer-classes, inheriting from `abstract-geoview-layer` and `abstract-gv-layer`, implement.

Admittedly, the `getBounds` implementation is different, it uses the metadata information to return an extent, but maybe we could put add a sort of `EsriDynamic.getBoundsFromFeatures()` function next to the `EsriDynamic.getBounds()`function? In the layer class itself? That way it ties in better with the layer logic? And there might even be common code that can be moved to the mother class `abstract-geoview-vector` (seeing how the implementation below uses 'vector features' to build an extent?).

Of course, if we add it to `esri-dynamic` , we also have to add it to `gv-esri-dynamic`. 

For `EsriDynamic`, the line: `MapEventProcessor.getMapViewerLayerAPI(mapId).getLayerEntryConfig(layerPath)` could be changed to something like `this.getMapViewer().layer.getLayerEntryConfig()` and for `GVEsriDynamic` to something like `this.getLayerConfig()` (because the config is internal to the new GV layer classes).

Finally, this method `DataTableEventProcessor.getESRIDynamicFeatureExtent()` (as it's used by the UI) could remain and manage support for the right layer type at this level, like:



_Code snippet:_
```XML
// Get the layer
const layer = MapEventProcessor.getMapViewerLayerAPI(mapId).getGeoviewLayerHybrid(layerPath);

// If the layer is vectorial (or if it's an EsriDynamic directly if we really only want to support that kind)
if (layer instanceof AbstractGeoViewVector || layer instanceof AbstractGVVector) {
  // Generate an extent from the features
  return layer.getBoundsFromFeatures();
}

throw new Error(`Layer type associated with layer path ${layerPath} isn't a vectorial layer`);
```

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341)* status: all files reviewed, 2 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/data-table-event-processor.ts` line 15 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0tZp-CDEveDP2Ugbl3:-O0tnAOSEUIMKsj4ypne:bw6kcwy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a114ee3d2f56fabbdaf5620ae93d0ce9abcf676/packages/geoview-core/src/api/event-processors/event-processor-children/data-table-event-processor.ts#L15)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Interesting yeah, hmmm.

Food for thought, can probably dig into it deeper and should probably talk about it some more than just via a reviewable comment. But at first glance, the `getESRIDynamicFeatureExtent` function kind of is reminiscent of the `getBounds` function. Function which all layer-classes, inheriting from `abstract-geoview-layer` and `abstract-gv-layer`, implement.

Admittedly, the `getBounds` implementation is different, it uses the metadata information to return an extent, but maybe we could put add a sort of `EsriDynamic.getBoundsFromFeatures()` function next to the `EsriDynamic.getBounds()`function? In the layer class itself? That way it ties in better with the layer logic? And there might even be common code that can be moved to the mother class `abstract-geoview-vector` (seeing how the implementation below uses 'vector features' to build an extent?).

Of course, if we add it to `esri-dynamic` , we also have to add it to `gv-esri-dynamic`. 

For `EsriDynamic`, the line: `MapEventProcessor.getMapViewerLayerAPI(mapId).getLayerEntryConfig(layerPath)` could be changed to something like `this.getMapViewer().layer.getLayerEntryConfig()` and for `GVEsriDynamic` to something like `this.getLayerConfig()` (because the config is internal to the new GV layer classes).

Finally, this method `DataTableEventProcessor.getESRIDynamicFeatureExtent()` (as it's used by the UI) could remain and manage support for the right layer type at this level, like:
</blockquote></details>

Err, spoke to soon, the EsriDynamic isn't a vector, my bad there, but anyways the separation of concern logic (where to put the function) remains valid, just maybe only for the EsriDynamic layer, not Vector layer.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341)* status: 8 of 10 files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/data-table-state.ts` line 24 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xdab9A4OdIfxgh9d7:-O0xdabA8NejZF6HuPX4:bgqb73i) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/core/stores/store-interface-and-intial-values/data-table-state.ts#L24)):*
> ```XML
>   actions: {
>     applyMapFilters: (filterStrings: string) => void;
>     getExtentFromFeatures: (layerPath: string, featureIds: string[]) => Promise<Extent | undefined>;
> ```

If we need this in state, I would put it in layers state because it is layer related and can be use elsewhere
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1468 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xfEc60-BsXO0FjShT:-O0xfEc60-BsXO0FjShU:b74bv4i) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1468)):*
> ```XML
>    * Overridable function that gets the extent of an array of features.
>    * @param {string} layerPath - The layer path
>    * @param {string[]} objectIds - The features to calculate the extent from.
> ```

missing id: The IDs of the features t
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 50 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xdu3XEO9kVHGPDoK6:-O0xdu3XEO9kVHGPDoK7:bzca1rz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L50)):*
> ```XML
> import { AppEventProcessor } from '@/api/event-processors/event-processor-children/app-event-processor';
> import { AbstractBaseLayerEntryConfig } from '@/core/utils/config/validation-classes/abstract-base-layer-entry-config';
> import { getMinOrMaxExtents } from '@/app';
> ```

We should use then proper path not app
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 949 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xeFHJ8avzGSQvgTKb:-O0xeFHJ8avzGSQvgTKc:b4vg1kg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L949)):*
> ```XML
>       // Construct query
>       if (!baseUrl.endsWith('/')) baseUrl += '/';
>       const queryUrl = `${baseUrl}${layerEntryConfig.layerId}/query?&f=json&where=&objectIds=${idString}&outFields=`;
> ```

Is it suppose to be returnGeometry=true and do not specify outFields?

https://<<url>>/<<id>>/query?f=json&objectIds=<<ids>>&returnGeometry=true
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 489 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xf-2FEeXt5sw0c8WZ:-O0xf-2FEeXt5sw0c8W_:b-anqv66) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L489)):*
> ```XML
>   override getExtentFromFeatures(layerPath: string, objectIds: string[]): Promise<Extent | undefined> {
>     const features = (this.getOLLayer(layerPath) as VectorLayer<Feature>).getSource()?.getFeatures();
>     const filteredFeatures = features?.filter((feature) => objectIds.includes(getUid(feature)));
> ```

Does all vector has an objectIds field? Or any kind of unique identifier?
___
*[`packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts` line 143 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xfXUf8ToWEiyc-x7N:-O0xfXUf8ToWEiyc-x7O:b-k0wyab) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts#L143)):*
> ```XML
>    * Overridable function that gets the extent of an array of features.
>    * @param {string} layerPath - The layer path
>    * @param {string[]} objectIds - The features to calculate the extent from.
> ```

The IDs of the features t
___
*[`packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts` line 691 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xfd2y0fxHal0udBhO:-O0xfd2zAZ_3k9AkvGWx:b83pr91) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts#L691)):*
> ```XML
>       // Construct query
>       if (!baseUrl.endsWith('/')) baseUrl += '/';
>       const queryUrl = `${baseUrl}${layerEntryConfig.layerId}/query?&f=json&where=&objectIds=${idString}&outFields=`;
> ```

Same as above for query

**Review by Alex-NRCan — APPROVED** [review]
I really like the improvements on this 3rd revision personally, nice job :thumbsup: 

> Reviewed 8 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-:-O0xo92P1PDg4apofIlW:b39n7zs)* status: all files reviewed, 11 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/data-table-event-processor.ts` line 125 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xnVXJ3UtVSSnVZgqs:-O0xnVXJ3UtVSSnVZgqt:b-omo61g) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/api/event-processors/event-processor-children/data-table-event-processor.ts#L125)):*
> ```XML
>    */
>   static async getExtentFromFeatures(mapId: string, layerPath: string, objectIds: string[]): Promise<Extent | undefined> {
>     const extent = await MapEventProcessor.getMapViewerLayerAPI(mapId)
> ```

Minor
I believe that since getExtentFromFeatures already returns a promise like the return of this function; this could be rewritten without the 'async' and 'await'.
By simply returning the actual promise like:
`return MapEventProcessor.getMapViewerLayerAPI(mapId)......getExtentFromFeatures(...);`
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 489 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xf-2FEeXt5sw0c8WZ:-O0xmdl64_9u_uIIuzq4:b1po1yf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L489)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Does all vector has an objectIds field? Or any kind of unique identifier?
</blockquote></details>

Good point.
Also, I have no idea, but is there a faster way to query for a feature given objectid(s) than browsing all the features 1 by 1 and filter? Just from a performance perspective.
___
*[`packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts` line 684 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xlrtAACpZywy0ZChN:-O0xlrtAACpZywy0ZChO:bsxgk6j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts#L684)):*
> ```XML
>   override async getExtentFromFeatures(layerPath: string, objectIds: string[]): Promise<Extent | undefined> {
>     // Get url for service from layer entry config
>     const layerEntryConfig = this.getLayerConfig() as EsriDynamicLayerEntryConfig;
> ```

Minor
One "cool thing" about the new GV Layers classes, the necesarry "as something" typing are done in a better fashion.
For example, here, there's no need to add the 'as EsriDynamicLayerEntryConfig'. The layer class already "knows" it's of that type.

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341)* status: all files reviewed, 9 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/data-table-event-processor.ts` line 15 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0tZp-CDEveDP2Ugbl3:-O0y62OU-dKozuxiFWXH:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a114ee3d2f56fabbdaf5620ae93d0ce9abcf676/packages/geoview-core/src/api/event-processors/event-processor-children/data-table-event-processor.ts#L15)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Err, spoke to soon, the EsriDynamic isn't a vector, my bad there, but anyways the separation of concern logic (where to put the function) remains valid, just maybe only for the EsriDynamic layer, not Vector layer.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/data-table/data-table.tsx` line 291 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0t_2XK-paMYukgwAI1:-O0y63ab7yjw6pkSHKXr:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7a114ee3d2f56fabbdaf5620ae93d0ce9abcf676/packages/geoview-core/src/core/components/data-table/data-table.tsx#L291)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I do not think we should have specific layer type in component.... if extent not provided the layer itself should have a function zoomToFeatureExtent and we should call it...
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/data-table-state.ts` line 24 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xdab9A4OdIfxgh9d7:-O0y34P215IlhuGF0BdK:b-rpz4hl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/core/stores/store-interface-and-intial-values/data-table-state.ts#L24)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If we need this in state, I would put it in layers state because it is layer related and can be use elsewhere
</blockquote></details>

Done. Also moved redirect function from data table event processor to legend event processor.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1468 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xfEc60-BsXO0FjShT:-O0y3Egd7-MvmWJKUgrM:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1468)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

missing id: The IDs of the features t
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 50 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xdu3XEO9kVHGPDoK6:-O0y3FUk0yL1lAMEUuuu:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L50)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should use then proper path not app
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 949 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xeFHJ8avzGSQvgTKb:-O0y3GjZ4k0Paj1U8YCi:b-93wbyq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L949)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is it suppose to be returnGeometry=true and do not specify outFields?

https://<<url>>/<<id>>/query?f=json&objectIds=<<ids>>&returnGeometry=true
</blockquote></details>

Geometry=true is the default, and outFields= specifies no outfields
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 489 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xf-2FEeXt5sw0c8WZ:-O0y3i-l8Kzjg6-xuVDx:byv1j0s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L489)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Good point.
Also, I have no idea, but is there a faster way to query for a feature given objectid(s) than browsing all the features 1 by 1 and filter? Just from a performance perspective.
</blockquote></details>

The only unique identifier between the vector features from different sources is the UID that openlayers attaches to each feature. objectids is only on ESRI features unless it is added to others. Going forward we could set the ID field of all features so that we can always use that. That would mean we could also use getFeatureById to get them.
___
*[`packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts` line 143 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xfXUf8ToWEiyc-x7N:-O0y5hV13H_JBiHAs45_:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts#L143)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The IDs of the features t
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts` line 691 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xfd2y0fxHal0udBhO:-O0y70vI1adCLmQUWxKI:b-8a05gs) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts#L691)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same as above for query
</blockquote></details>

As above

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341)* status: 6 of 12 files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 949 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xeFHJ8avzGSQvgTKb:-O0yC5L42i_sMJnNFj3U:b-8plvoa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L949)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Geometry=true is the default, and outFields= specifies no outfields
</blockquote></details>

I still think make it like ?f=json&objectIds=<>&returnGeometry=true is more clear then using default value

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 489 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xf-2FEeXt5sw0c8WZ:-O0yCS0E3pp49XF9z1tm:b-vx8r25) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L489)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

The only unique identifier between the vector features from different sources is the UID that openlayers attaches to each feature. objectids is only on ESRI features unless it is added to others. Going forward we could set the ID field of all features so that we can always use that. That would mean we could also use getFeatureById to get them.
</blockquote></details>

CAn you put a TODO: Test performance on huge vector layer.... as Alex mentionned

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341)* status: 8 of 12 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 949 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xeFHJ8avzGSQvgTKb:-O0yDt79-ZTHGpWHEVpy:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L949)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I still think make it like ?f=json&objectIds=<>&returnGeometry=true is more clear then using default value
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 489 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xf-2FEeXt5sw0c8WZ:-O0yEApD7cNJFCOaE-ol:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L489)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

CAn you put a TODO: Test performance on huge vector layer.... as Alex mentionned
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 489 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2341#-O0xf-2FEeXt5sw0c8WZ:-O11sA35-mamrn1mqi7b:b8a1fjp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a1e577d010dfe1a1701988d6861c6979945a4679/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L489)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think setting an ID field (or providing the ID field as parameter to the function) might be the best approach if we want to rework it. To be able to use the getFeatureById().

**Pull request merged**
