### PR TITLE
fix(UI): refactor appbar component   #closes2145

### LINKED ISSUE #2145: [Refactor] <Performance of UI Components 2>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Need to enhance the performance of following UI Components based 

1. Appbar
2. Attribution
3. Click Marker
4. Common
5. Crosshair

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description

Refactor UI Components.
1. Appbar
2. Attribution
3. Click Marker
4. Common
5. Crosshair

Fixes #2145 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/demos-navigator.html?config=./configs/navigator/07-basic-appbar.json
https://kaminderpal.github.io/geoview/demos-navigator.html?config=./configs/navigator/06-basic-footer.json

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2147)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2147)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2147#-Ny1m6Yo83e6ackwRm6w:-Ny1m6Yo83e6ackwRm6x:b-wjr5bg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0914356ec9649c7145ba2b71d33da544d208dc54/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L50)):*
> ```XML
>   const { api: appBarApi } = props;
> 
>   const appBarTabRefs = useRef(['legend', 'details', 'guide']);
> ```

I think we have a constant or a type for this info in config (TypeValidAppBarCoreProps). If we need a constant we should create it in config-constant.ts
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 231 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2147#-Ny1nNG-BicWymMliK0f:-Ny1nNG-BicWymMliK0g:b2o5of4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0914356ec9649c7145ba2b71d33da544d208dc54/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L231)):*
> ```XML
>     }
>     // eslint-disable-next-line react-hooks/exhaustive-deps
>   }, [activeAppBarPanelId]);
> ```

For naming convention, appBar schema use tabs and at some places it is appBarTabs.... should we have activeAppBarTabId?

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2147)* status: 0 of 18 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2147#-Ny1m6Yo83e6ackwRm6w:-Ny5sAQN3BrPg0Kn7iAr:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0914356ec9649c7145ba2b71d33da544d208dc54/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L50)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think we have a constant or a type for this info in config (TypeValidAppBarCoreProps). If we need a constant we should create it in config-constant.ts
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 231 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2147#-Ny1nNG-BicWymMliK0f:-Ny5sCRkAzWpbGeVAEcA:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0914356ec9649c7145ba2b71d33da544d208dc54/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L231)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

For naming convention, appBar schema use tabs and at some places it is appBarTabs.... should we have activeAppBarTabId?
</blockquote></details>

Done.

**Review by cphelefu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2147#-:-Ny63cV1APLBZhmW3Ke5:bnfp4nl)* status: 0 of 18 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2147)* status: all files reviewed, 1 unresolved discussion (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 296 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2147#-Ny687tP4UgPK3hi7pAC:-Ny687tQ32Ahj8KQa0u_:b-vt63ci) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c974faaefe29ffa44a51ff22947e9b757a0ff793/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L296)):*
> ```XML
> 
>   /**
>    * Re-order the footer tab buttons.
> ```

Is it footer or appBar

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2147)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 296 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2147#-Ny687tP4UgPK3hi7pAC:-Ny69khY5kp3Aq0h8SEZ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c974faaefe29ffa44a51ff22947e9b757a0ff793/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L296)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is it footer or appBar
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2147)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2147)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Pull request merged**
