### PR TITLE
fix(table): UX and filter export

### LINKED ISSUE #2506: [FEATURE] UX for DataTable
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team, OSDP

### User Story

There was many UI/UX comments from the workshop about the data table.... Some of them needs a fix to improve usability...

### Implementation UI

EXPORT
- [x] Remove Icon, Zoom, and Details columns
- [x] Download table use all features, not only selected. Do only selected or have both option like in chart
- [x] _related to https://github.com/Canadian-Geospatial-Platform/geoview/issues/2414_

FILTERS and STATE
- [x] Add a reset filters all / reload initial table state
- [x] Show filter and filter map on by default... filter map, is it the right place - "Display filter on map"
_It is not clear that table filters can filter the map: Kept looking at the map to see if the filter works, however it does not seem to link to the map to filter the points there as well._

NAVIGATION
- [x] Bigger or more visible horizontal scroll bar = Use accent color instead of grey so scroll bar are more visible

### PR DESCRIPTION
**Pull request by jolevesq**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

This PR is fixing issues and add UX improvement (comments from the workshop about the data table)
- Rename export to download
- Remove Icon, Zoom, and Details columns from downloaded file
- Download only selected rows (CSV and JSON) - Add geoviewID as internal to do filtering
- Put layer name as file name for JSON and csv
- Filter open by default
- Filter map open by default
- Add clear all filters button
- Make filter map more visible
- Re arrange display, show number of features on right panel all the time
- More visible scroll bar

Fixes #2506, #2414

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Hosted October 11th, noon: https://jolevesq.github.io/geoview/demos-navigator.html?config=./configs/navigator/16-esri-dynamic.json

Go to data table, filter rows then download and see results

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2547)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2547)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan and @DamonU2)

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2547)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/public/locales/en/translation.json` line 202 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2547#-O9G5yxv1UjO5a4SKvV0:-O9G5yxv1UjO5a4SKvV1:bh39bbm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/49a4c33b00614fcda4c891e9286f724f0ad8d989/packages/geoview-core/public/locales/en/translation.json#L202)):*
> ```JSON
>     "downloadAsCSV": "Download CSV",
>     "filterMap": "Filter map",
>     "stopFilterMap": "Stop filter map",
> ```

This seems weird - "Stop filtering map" or just "Filter Map" because it is a toggle?

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2547)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts` line 647 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2547#-O9GA4-b0vM97t12ZTwK:-O9GA4-b0vM97t12ZTwL:biw4dch) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/49a4c33b00614fcda4c891e9286f724f0ad8d989/packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts#L647)):*
> ```XML
>    * @private
>    */
>   static #formatFieldValue(fieldName: string, rawValue: string | number | Date, sourceFeatureInfo: TypeFeatureInfoLayerConfig): string {
> ```

I think this PR will need to be rebased once my PR will be merged, because I believe I've changed this as well in my PR.

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2547)* status: 13 of 16 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/public/locales/en/translation.json` line 202 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2547#-O9G5yxv1UjO5a4SKvV0:-O9G6Y3sC_m_4F-B0Jtw:bp9cpeu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/49a4c33b00614fcda4c891e9286f724f0ad8d989/packages/geoview-core/public/locales/en/translation.json#L202)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

This seems weird - "Stop filtering map" or just "Filter Map" because it is a toggle?
</blockquote></details>

I was thinking about it. I tried both. Will put it back and let me know what you think

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2547)* status: 13 of 16 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/public/locales/en/translation.json` line 202 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2547#-O9G5yxv1UjO5a4SKvV0:-O9GQL0-3eE-cuWlEowX:b-yp91j1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/49a4c33b00614fcda4c891e9286f724f0ad8d989/packages/geoview-core/public/locales/en/translation.json#L202)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I was thinking about it. I tried both. Will put it back and let me know what you think
</blockquote></details>

Looks better to me, but it's removed from the french but still listed here

**Review by jolevesq — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2547)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

**Pull request merged**
