### PR TITLE
fix(datatable): responsive datatable  Closes #1462

### LINKED ISSUE #1462: [FEATURE] <Create Responsive Design for data table>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

_No response_

### User Story

Create new responsive design based on Vladd designs https://xd.adobe.com/view/87886e3a-43f1-44a0-6cae-a52487b6bf2a-f1b9/

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Update data table layout to be responsive in nature.

Fixes # (1462)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/raw-data-table.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1475)

### CODE REVIEW

**Review by manoharnrcan — COMMENTED** [review]
QA Acceptance criteria -

1.  we are hiding enlarge button when device reach to 960px

2. Show close button and table full size when browser size is less than 960px 
hide left panel when browser size is less than 960px
u can follow - 
[https://mui.com/material-ui/customization/breakpoints/](https://mui.com/material-ui/customization/breakpoints/)
(Note: MUI website mentions 900px for medium ,since in  our theme the setup is for 960px , am testing as per 960px)


Tested as per requirement.

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1475#-:-NipNC9r2OjyCzV3_dvd:bihr76q)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r2, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1475)* status: all files reviewed, 1 unresolved discussion (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/data-table/data-table-grid.tsx` line 2 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1475#-NipN-XWDuoWBj1muRBk:-NipN-XWDuoWBj1muRBl:bua51yc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d476556e234bd49dbe68de612fe02e382840d79c/packages/geoview-core/src/core/components/data-table/data-table-grid.tsx#L2)):*
> ```XML
> import React, { ReactNode } from 'react';
> import { GridProps, useTheme } from '@mui/material';
> ```

useTheme is from ...ui/material/styles

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1475)* status: 3 of 10 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/data-table/data-table-grid.tsx` line 2 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1475#-NipN-XWDuoWBj1muRBk:-NipeLzjBLtGuazP82AZ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d476556e234bd49dbe68de612fe02e382840d79c/packages/geoview-core/src/core/components/data-table/data-table-grid.tsx#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

useTheme is from ...ui/material/styles
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1475)* status: 5 of 10 files reviewed, all discussions resolved

**Review by jolevesq — COMMENTED** [review]
> Reviewed 4 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1475)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @kaminderpal)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1475)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Pull request merged**
