### PR TITLE
Add legend to store

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

First phase of the work needed to add the legends to the store. This PR has an impact on the UI which has to be modified to use the store instead of the helper functions. QA must be done later when all the UI links to the store will be done.

This fix does not close any issue. It is only a sub task of the issue #1382.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using the Chrome Devtools to trace and debug the code.

__Deploy URL:__ http://localhost:8080/raw-legend-2.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 41 of 43 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520)* status: 41 of 43 files reviewed, 7 unresolved discussions (waiting on @cphelefu and @ychoquet)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts` line 21 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520#-NjsKTPR0T7RKP-Ze__2:-NjsKTPR0T7RKP-Ze__3:b5c1a8p) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2ed51822d78bea8a1c33bba13cd90cb11faacdfa/packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts#L21)):*
> ```XML
>       (allQueriesPayload) => {
>         if (payloadIsAllQueriesDone(allQueriesPayload)) {
>           store.setState({ featureInfoResultSets: allQueriesPayload.resultSets });
> ```

This is related to our discussion this morning about details. Does the layersQuery array gets updated on each modification or only when everything is done.
___
*[`packages/geoview-core/src/core/components/data-table/data-table.tsx` line 14 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520#-NjsLM5NAnkQ01nr8KB6:-NjsLM5NAnkQ01nr8KB7:b-17f8dn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2ed51822d78bea8a1c33bba13cd90cb11faacdfa/packages/geoview-core/src/core/components/data-table/data-table.tsx#L14)):*
> ```XML
> } from 'material-react-table';
> import { Extent } from 'ol/extent';
> import Geometry from 'ol/geom/Geometry';
> ```

Why changing the import?
___
*[`packages/geoview-core/src/core/components/layers/layers.tsx` line 4 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520#-NjsLZAV3rcPkbU553yl:-NjsLZAV3rcPkbU553ym:b-1gc9hh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2ed51822d78bea8a1c33bba13cd90cb11faacdfa/packages/geoview-core/src/core/components/layers/layers.tsx#L4)):*
> ```XML
> import { useTheme } from '@mui/material/styles';
> import { styled } from '@mui/material';
> // YC import { LegendItemsDetailsProps } from './types';
> ```

The comment // YC. Can we change them with
// ? 'description' ... too understand why
// ? line in comment
___
*[`packages/geoview-core/src/core/components/layers/types.ts` line 69 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520#-NjsLven1M9YdCRz5GWo:-NjsLven1M9YdCRz5GWp:b-df2t2h) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2ed51822d78bea8a1c33bba13cd90cb11faacdfa/packages/geoview-core/src/core/components/layers/types.ts#L69)):*
> ```XML
>   name?: string;
>   iconImage?: string | null;
>   iconImgStacked?: string | null;
> ```

Should we have iconImageStacked to keep naming with property above
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 193 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520#-NjsMh6T2l4QHBAKbCuQ:-NjsMh6T2l4QHBAKbCuR:bvei1bz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2ed51822d78bea8a1c33bba13cd90cb11faacdfa/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L193)):*
> ```XML
> // **********************************************************
> export const useLayersList = () => useStore(useGeoViewStore(), (state) => state.layerState.legendLayers);
> export const useSelectedLayerPath = () => useStore(useGeoViewStore(), (state) => state.layerState.selectedLayerPath);
> ```

Should rename useLayerSelect.... use<state> is the naming convention for atomic selector
___
*[`packages/geoview-core/src/geo/renderer/geoview-renderer.ts` line 626 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520#-NjsNmAZDMMXN0mmc13R:-NjsNmAZDMMXN0mmc13S:b-sy5brp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2ed51822d78bea8a1c33bba13cd90cb11faacdfa/packages/geoview-core/src/geo/renderer/geoview-renderer.ts#L626)):*
> ```XML
>    * @returns {Style | undefined} The style applied to the feature or undefined if not found.
>    */
>   getClusterStyle(layerEntryConfig: TypeVectorLayerEntryConfig, feature?: Feature<Geometry>): Style | undefined {
> ```

Should we move cluster stuff in the cluster file code holder?
___
*[`packages/geoview-footer-panel/src/footer-panel-legend-item.tsx` line 16 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520#-NjsOE-zDEnwHgaETz5F:-NjsOE-zDEnwHgaETz5G:b-qny0zt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2ed51822d78bea8a1c33bba13cd90cb11faacdfa/packages/geoview-footer-panel/src/footer-panel-legend-item.tsx#L16)):*
> ```XML
>  * @returns {JSX.Element} created legend component
>  */
> export function FooterPanelLegendItem({ mapId }: Props): JSX.Element {
> ```

Why file is renamed

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/layers/types.ts` line 66 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520#-NjsSldD069xkPprh7RQ:-NjsSldE-DeVHtMPXMqS:b-mcsdtw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2ed51822d78bea8a1c33bba13cd90cb11faacdfa/packages/geoview-core/src/core/components/layers/types.ts#L66)):*
> ```XML
> export type TypeLegendLayerItem = {
>   geometryType?: TypeStyleGeometry;
>   iconType?: 'simple' | 'list';
> ```

I thought all categories or items can have only one image. Do we need iconType & iconImgStacked?

**Review by cphelefu — APPROVED** [review]
> Reviewed 3 of 43 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520)* status: 42 of 43 files reviewed, 7 unresolved discussions (waiting on @jolevesq and @ychoquet)

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520)* status: 38 of 43 files reviewed, 5 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts` line 21 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520#-NjsKTPR0T7RKP-Ze__2:-NjslqwvCKI_lr9aC7U2:b-cjorm2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2ed51822d78bea8a1c33bba13cd90cb11faacdfa/packages/geoview-core/src/api/event-processors/event-processor-children/feature-info-event-processor.ts#L21)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This is related to our discussion this morning about details. Does the layersQuery array gets updated on each modification or only when everything is done.
</blockquote></details>

This section of code could be remove. nothing is using it.
___
*[`packages/geoview-core/src/core/components/data-table/data-table.tsx` line 14 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520#-NjsLM5NAnkQ01nr8KB6:-Njsm9vO2cPDXMydbxhM:b-jb3q57) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2ed51822d78bea8a1c33bba13cd90cb11faacdfa/packages/geoview-core/src/core/components/data-table/data-table.tsx#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why changing the import?
</blockquote></details>

To be consistant with other places. This is the same as before.
___
*[`packages/geoview-core/src/core/components/layers/types.ts` line 66 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520#-NjsSldD069xkPprh7RQ:-NjsmZbb4YmlZ5tqGKVV:b-h1lwpd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2ed51822d78bea8a1c33bba13cd90cb11faacdfa/packages/geoview-core/src/core/components/layers/types.ts#L66)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

I thought all categories or items can have only one image. Do we need iconType & iconImgStacked?
</blockquote></details>

I replicated what was there before. I thought that it was used to display the two icons one over the other to show that there are categories.
___
*[`packages/geoview-core/src/core/components/layers/types.ts` line 69 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520#-NjsLven1M9YdCRz5GWo:-Njsn7lE8UHN6otBDfc_:b-ff454l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2ed51822d78bea8a1c33bba13cd90cb11faacdfa/packages/geoview-core/src/core/components/layers/types.ts#L69)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we have iconImageStacked to keep naming with property above
</blockquote></details>

Yes if we really want to keep this variable. I'll do that in the next PR. 
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 193 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520#-NjsMh6T2l4QHBAKbCuQ:-NjsnWSHCGb4WYCeLwx4:bxosk0u) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2ed51822d78bea8a1c33bba13cd90cb11faacdfa/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L193)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should rename useLayerSelect.... use<state> is the naming convention for atomic selector
</blockquote></details>

Agree, I'll do that in the next PR.
___
*[`packages/geoview-core/src/geo/renderer/geoview-renderer.ts` line 626 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520#-NjsNmAZDMMXN0mmc13R:-Njsni8YCFNLFAwtmlvJ:b8oznqr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2ed51822d78bea8a1c33bba13cd90cb11faacdfa/packages/geoview-core/src/geo/renderer/geoview-renderer.ts#L626)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we move cluster stuff in the cluster file code holder?
</blockquote></details>

Personnaly, I would remove all the code that is related to clustering. When we are ready, we'll code clustering from scratch.
___
*[`packages/geoview-core/src/core/components/layers/layers.tsx` line 4 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520#-NjsLZAV3rcPkbU553yl:-NjsoS23AVDaC75Mx4dk:b-1p7vz6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2ed51822d78bea8a1c33bba13cd90cb11faacdfa/packages/geoview-core/src/core/components/layers/layers.tsx#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The comment // YC. Can we change them with
// ? 'description' ... too understand why
// ? line in comment
</blockquote></details>

This is supposed to be removed by the last rebase.
___
*[`packages/geoview-footer-panel/src/footer-panel-legend-item.tsx` line 16 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520#-NjsOE-zDEnwHgaETz5F:-NjsoEu87EncQdw6k5jv:b2tf5wq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2ed51822d78bea8a1c33bba13cd90cb11faacdfa/packages/geoview-footer-panel/src/footer-panel-legend-item.tsx#L16)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why file is renamed
</blockquote></details>

Can't say. I don't remember doing that. Maybe it comes from a rebase.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 43 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1520)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
