### PR TITLE
refactor(modals) Modal events refactored

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

Modal events refactored.

Should be tested:
- Modals behavior in general
- Shell in general, including recreation of the map
- Snackbar
- The new animations by Chris
- The focus trap in the shell and the modal

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Hosted here as of March 11 15h: https://alex-nrcan.github.io/geoview/

To test, one can run commands like:
`cgpv.api.maps['sandboxMap'].modal.createModal({content: '<div>Hello sir</div>'});`
`cgpv.api.maps['sandboxMap'].modal.modals` (to look at the modal key)
`cgpv.api.maps['sandboxMap'].modal.openModal('THE KEY');`

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1910)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 4 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1910)* status: 4 of 12 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 173 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1910#-NshrbGk8vhhQvRZ-Tq1:-NshrbGk8vhhQvRZ-Tq2:b-fz7hgt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1d6a446dd7ee63c13e043fecc81da7c0128b8a74/packages/geoview-core/src/core/containers/shell.tsx#L173)):*
> ```XML
> 
>     // to open the modal
>     api.event.onModalOpen(mapId, modalOpenListenerFunction);
> ```

Should we have event on api.event or api.maps[mapId].event?

**Review by jolevesq — COMMENTED** [review]
> Reviewed 6 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1910)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/ui/modal/modal.tsx` line 245 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1910#-NsiYET592p96ApDYlL3:-NsiYET592p96ApDYlL4:bhfh1mz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1d6a446dd7ee63c13e043fecc81da7c0128b8a74/packages/geoview-core/src/ui/modal/modal.tsx#L245)):*
> ```XML
> 
>   return (
>     (modalProps && ceatedModalJSXReturner(modalProps)) || (
> ```

Typo ceated

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 10 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1910)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 173 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1910#-NshrbGk8vhhQvRZ-Tq1:-Nsieabg1mlHRi9qhr6c:bo2muji) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1d6a446dd7ee63c13e043fecc81da7c0128b8a74/packages/geoview-core/src/core/containers/shell.tsx#L173)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we have event on api.event or api.maps[mapId].event?
</blockquote></details>

Will be done in another PR.
___
*[`packages/geoview-core/src/ui/modal/modal.tsx` line 245 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1910#-NsiYET592p96ApDYlL3:-Nsi_nIF3AuwvHwBBvFC:b-886gsx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1d6a446dd7ee63c13e043fecc81da7c0128b8a74/packages/geoview-core/src/ui/modal/modal.tsx#L245)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo ceated
</blockquote></details>

Fixed

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 12 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1910)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1910)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Pull request merged**
