### PR TITLE
feat(datatable): refactor data table  #closes1737

### LINKED ISSUE #1694: [BUG] <By selecting any of the record in Water quantity data table- Zoom Icon is overlapping with text>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Zoom Icon is overlapping with text

### Expected Behavior

when moving horizontally scroll bar, Text should not be overlap on Zoom Icon Column

Note: This Issue exists in all layers
1-Volume de DEU 2020/ CSO volume 2020
2-Water quantity at monitoring stations
3-Top 100 Exploration Projects

### Steps To Reproduce

1-Go to https://canadian-geospatial-platform.github.io/geoview/public/index.html
2-Check all the features are displaying on Footer panel
3-Click on Data Table tab
4-Select any of the record (Object Id Column) in Water quantity data table
5-Move scroll bar Horizontally 

### Anything else?

image

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Refactor data table to use layers from store instead of api.

Fixes # ([1737](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1737))
Fixes #1694 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/raw-data-table.html
# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1755)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 13 of 15 files at r1, 1 of 2 files at r2, 5 of 8 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1755)* status: 17 of 19 files reviewed, 2 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/data-table-processor.ts` line 13 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1755#-Nq3yh_MBNbLHFaS67aS:-Nq3yh_MBNbLHFaS67aT:b6uvzfv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/924c682c26ba678ad66c677072d9c18f88953575/packages/geoview-core/src/api/event-processors/event-processor-children/data-table-processor.ts#L13)):*
> ```XML
>    * @param {boolean} isMapRecordExist filtered Map switch is on off.
>    */
>   static applyFilters(mapId: string, layerPath: string, filterStrings: string, isMapRecordExist: boolean) {
> ```

CAn you add comments section like https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts#L7 and line 38
___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 161 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1755#-Nq3z9eI2f_ZKfMU85G1:-Nq3z9eI2f_ZKfMU85G2:bg9j4bt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b381f41add4e3868dbbd829072f45c563bb8ec32/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L161)):*
> ```XML
>   useEffect(() => {
>     setSelectedLayerPath(orderedLayerData[0].layerPath);
>     // eslint-disable-next-line react-hooks/exhaustive-deps
> ```

You should keep logger in use effect

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1755)* status: 16 of 19 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/data-table-processor.ts` line 13 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1755#-Nq3yh_MBNbLHFaS67aS:-Nq40ftt3FACqDSdepUd:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/924c682c26ba678ad66c677072d9c18f88953575/packages/geoview-core/src/api/event-processors/event-processor-children/data-table-processor.ts#L13)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

CAn you add comments section like https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts#L7 and line 38
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 161 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1755#-Nq3z9eI2f_ZKfMU85G1:-Nq40hMmEsGbxlthCEf5:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b381f41add4e3868dbbd829072f45c563bb8ec32/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L161)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You should keep logger in use effect
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 8 files at r3, 6 of 6 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1755)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1755)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Pull request merged**
