### PR TITLE
Improvement for Static UI (Fix in Appbar and MapInfo)

### LINKED ISSUE #1971: [FEATURE] UI Static Improvement
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

As a user, I found there is too much component on the map when in static mode.

### Implementation UI

image

image

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

This PR hides the appbar background and and also background in map-info - when map interaction is set to static.

Fixes #1971 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://cphelefu.github.io/geoview/

# Checklist:

- [X] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [X] I have connected the issues(s) to this PR
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1980)

### CODE REVIEW

**Review by DamonU2 — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1980)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1980)* status: all files reviewed, 3 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/src/core/components/app-bar/app-bar-style.ts` line 14 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1980#-NudeVqo157HQ4UwcC2x:-NudeVqo157HQ4UwcC2y:b-z818gs) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/37091e74c5163d5563e15e94270f8940a68deb3f/packages/geoview-core/src/core/components/app-bar/app-bar-style.ts#L14)):*
> ```XML
> 
>     '&.interaction-static': {
>       position: 'absolute',
> ```

position, lest, ... properties are they only for static, it seems to be shared with dynamic as well.

Only color is specific to static
___
*[`packages/geoview-core/src/core/components/map-info/map-info-style.ts` line 27 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1980#-NudeHikBNguyZSa_iY_:-NudeHikBNguyZSa_iYa:bsfj7u2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/37091e74c5163d5563e15e94270f8940a68deb3f/packages/geoview-core/src/core/components/map-info/map-info-style.ts#L27)):*
> ```XML
>       color: `${theme.palette.geoViewColor.grey.dark[900]} !important`,
>       fill: `${theme.palette.geoViewColor.grey.dark[900]} !important`,
>       position: 'absolute',
> ```

position, width, .... properties. Are thy only for static. I think they are shared by dynamic and static.

Only color is specific to static
___
*[`packages/geoview-core/src/ui/style/themeOptionsGenerator.ts` line 312 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1980#-NudepOlBFl8-WzW3Eke:-NudepOlBFl8-WzW3Ekf:b-lowxib) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/37091e74c5163d5563e15e94270f8940a68deb3f/packages/geoview-core/src/ui/style/themeOptionsGenerator.ts#L312)):*
> ```XML
>               },
>             },
>             '&.style4': {
> ```

We should have better naming for different style... style3, style 4 does not mean something

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/app-bar/app-bar-style.ts` line 14 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1980#-NudeVqo157HQ4UwcC2x:-Nudjfhz1YdEGTpTM7Ux:bibr5jg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5a9e53ecdf6f13aa09f1ca1d6ea08eb2eb00d359/packages/geoview-core/src/core/components/app-bar/app-bar-style.ts#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

position, lest, ... properties are they only for static, it seems to be shared with dynamic as well.

Only color is specific to static
</blockquote></details>

Nope, position is relative for dynamic.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/map-info/map-info-style.ts` line 27 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1980#-NudeHikBNguyZSa_iY_:-NudjyQ4-UQlYCp8IDd_:b-846q19) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5a9e53ecdf6f13aa09f1ca1d6ea08eb2eb00d359/packages/geoview-core/src/core/components/map-info/map-info-style.ts#L27)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

position, width, .... properties. Are thy only for static. I think they are shared by dynamic and static.

Only color is specific to static
</blockquote></details>

position is relative for dynamic. width is is also different for both static and relative.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/ui/style/themeOptionsGenerator.ts` line 312 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1980#-NudepOlBFl8-WzW3Eke:-NudkCPp0GHSZ4UnnjI1:bd9oxg3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5a9e53ecdf6f13aa09f1ca1d6ea08eb2eb00d359/packages/geoview-core/src/ui/style/themeOptionsGenerator.ts#L312)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should have better naming for different style... style3, style 4 does not mean something
</blockquote></details>

Yep, you right... style1...style4 doesnt really make sense.  I have a task open for this.

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1980)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
