### PR TITLE
fix(core): Change language bug

### LINKED ISSUE #1082: [BUG] Change Language not working
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The cgpv.api.map('LNG2').changeLanguage('fr') function is not working. The EVENT_MAP_RELOAD event is not trap inside que app.tsx.

### Expected Behavior

The function should change the viewer language tot he desired one.

### Steps To Reproduce

1. Go to language.html page and open the console
2. Type: cgpv.api.map('LNG2').changeLanguage('fr')
3. See the map 2 in English stays in English

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1082

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # 1082

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

On the html language page, there is a button to reset the language for a map.

https://jolevesq.github.io/geoview/languages.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1116)

### CODE REVIEW

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1116)* status: all files reviewed, 2 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/geo/map/map.ts` line 444 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1116#-NYUA_Vp1f6ZlLfRyw7p:-NYUA_Vp1f6ZlLfRyw7q:byvbats) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d3881937213b8a46509cbb447bdd5f4ffbfa67b/packages/geoview-core/src/geo/map/map.ts#L444)):*
> ```XML
>     updatedMapConfig.displayLanguage = displayLanguage;
> 
>     // if a list of geoview layers parameter is present, replace the one fromt the config
> ```

replace the one fromt
___
*[`packages/geoview-core/src/geo/map/map.ts` line 463 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1116#-NYUBMVI4DSUXx1UdrmP:-NYUBMVI4DSUXx1UdrmQ:b-8q8icr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d3881937213b8a46509cbb447bdd5f4ffbfa67b/packages/geoview-core/src/geo/map/map.ts#L463)):*
> ```XML
>     // get target div and modify the id to remove map-.
>     // this string came from the GeoView map div element, not the original one
>     // if we do not so this, it creates a new map id in the array of maps instead of replacing.
> ```

if we do not do this, ...

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1116)* status: all files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/map/map.ts` line 437 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1116#-NYU-_c5AFIKX6iNUk2k:-NYU-_c5AFIKX6iNUk2l:bvo4uq7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d3881937213b8a46509cbb447bdd5f4ffbfa67b/packages/geoview-core/src/geo/map/map.ts#L437)):*
> ```XML
>    *
>    * @param {TypeDisplayLanguage} displayLanguage the language to use (en, fr)
>    * @param {TypeListOfGeoviewLayerConfig} geoviewLayerConfi optional new set of layers to apply (will override original set of layers)
> ```

geoviewLayerConfi > listOfGeoviewLayerConfig

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1116)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/src/geo/map/map.ts` line 437 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1116#-NYU-_c5AFIKX6iNUk2k:-NYx1JV5-l7jbaV4CjOA:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d3881937213b8a46509cbb447bdd5f4ffbfa67b/packages/geoview-core/src/geo/map/map.ts#L437)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

geoviewLayerConfi > listOfGeoviewLayerConfig
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/map/map.ts` line 444 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1116#-NYUA_Vp1f6ZlLfRyw7p:-NYx1OvT5Y9zNq0QEoIq:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d3881937213b8a46509cbb447bdd5f4ffbfa67b/packages/geoview-core/src/geo/map/map.ts#L444)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

replace the one fromt
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/map/map.ts` line 463 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1116#-NYUBMVI4DSUXx1UdrmP:-NYx1_PH-7mNmlzl3zSe:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d3881937213b8a46509cbb447bdd5f4ffbfa67b/packages/geoview-core/src/geo/map/map.ts#L463)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

if we do not do this, ...
</blockquote></details>

Done.

**Review by DamonU2 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1116)* status: all files reviewed, 2 unresolved discussions (waiting on @ychoquet)

**Review by ychoquet — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
