### PR TITLE
refactor(load): Refactor loading and projection class

### LINKED ISSUE #1580: [REFACTOR] On reload config, reset store values
When a map is relaoded from a new config, make sure store is updated with latest config.

refactor at the same time the function to create a map form config to use a div on the maps (createMapFromConfig) to make it use and set the store properly

Solve comment on code with number issue

Deep clone the config element when added to the store

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1580

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Refactor reload and use store
Refactor projection class and make sure all code reuse existing
Refactor api.plugins to move plugin instance to maps[mapIs].plugins

Next step, continue with store usage from within layers

Fixes #1580
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://jolevesq.github.io/geoview/index.html

cgpv.api.maps['mapWM1'].reload()
cgpv.api.maps['mapWM1'].remove(true)

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
> Reviewed 35 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647)* status: 35 of 36 files reviewed, all discussions resolved (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 36 of 36 files at r1, 4 of 11 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647)* status: 42 of 43 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/public/configs/package-time-slider-config.json` line 62 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCAkv80DENTiOBMtLS:-NmCAkv80DENTiOBMtLT:b-5kr2nu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/public/configs/package-time-slider-config.json#L62)):*
> ```JSON
>   "theme": "geo.ca",
>   "components": ["north-arrow", "overview-map"],
>   "corePackages": ["footer-panel", "time-slider"],
> ```

Does this work without footer-panel?
___
*[`packages/geoview-core/src/api/plugin/plugin.ts` line 188 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCBhdF0uMkp_9_TcHB:-NmCBhdF0uMkp_9_TcHC:bu5stb0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/src/api/plugin/plugin.ts#L188)):*
> ```XML
>         });
> 
>         // attacht he plugin tot he map plugins object
> ```

attacht he plugin tot he > attach the map to the

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 32 of 36 files at r1, 11 of 11 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647)* status: all files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/app.tsx` line 36 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmC8OCKEBu60WZtEDr_:-NmC8OCKEBu60WZtEDra:b-jgjw1z) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04c41e2f0e5e5984e8f4584fcf5379355e99f211/packages/geoview-core/src/app.tsx#L36)):*
> ```XML
>  * @param {string} mapId the map id to unmount 
>  */
> export function unmountMap(mapId: string) {
> ```

Do we need to create a function for a single line instruction. You can export reactRoot here and import it in map-viewer.ts. If I'm right, this is the only place you need it and the code there would be:

    // remove the dom element (remove rendered map and overview map)
    if (this.overviewRoot) this.overviewRoot?.unmount();
    if (reactRoot[this.mapId] !== null) reactRoot[this.mapId].unmount();



_Suggestion:_
```XML
export function unmountMap(mapId: string) {
  if (reactRoot[mapId] !== null) reactRoot[mapId].unmount();
}
```
___
*[`packages/geoview-core/src/api/plugin/plugin.ts` line 80 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCcP1FAo2jyEJJo4IE:-NmCcP1G3zBFcUNktndt:btiyvy4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04c41e2f0e5e5984e8f4584fcf5379355e99f211/packages/geoview-core/src/api/plugin/plugin.ts#L80)):*
> ```XML
>         // be calledback. Otherwise, even if 'existingScript' says that it's been loaded,
>         // it's not 'yet' true, because the js file might still be being downloaded and window.geoviewPlugins[pluginId] still undefined.
>         whenThisThen(() => window.geoviewPlugins && window.geoviewPlugins[pluginId]).then(() => {
> ```

This can be shortened to:
whenThisThen(() =>window.geoviewPlugins?.[pluginId]).then(() => {



_Code quote:_
```XML
whenThisThen(() => window.geoviewPlugins && window.geoviewPlugins[pluginId]).then(() => {
```
___
*[`packages/geoview-core/src/api/plugin/plugin.ts` line 101 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCcx1bET_BMPBeb63P:-NmCcx1c3JB8bSsRD5Y6:bowbz62) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04c41e2f0e5e5984e8f4584fcf5379355e99f211/packages/geoview-core/src/api/plugin/plugin.ts#L101)):*
> ```XML
>     props?: TypeJsonObject
>   ): Promise<void> => {
>     if (api.maps[mapId] && !api.maps[mapId].plugins[pluginId]) {
> ```

Can be shortened to:
if (!api.maps?.[mapId]?.plugins?.[pluginId]) {



_Suggestion:_
```XML
if (api.maps[mapId] && !api.maps[mapId].plugins[pluginId]) {
```
___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 42 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCiKPB6gEpBWfnBBlm:-NmCiKPC2TDJ3EnSnE78:bpt5sq0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04c41e2f0e5e5984e8f4584fcf5379355e99f211/packages/geoview-core/src/core/stores/geoview-store.ts#L42)):*
> ```XML
>     mapConfig: undefined,
>     setMapConfig: (config: TypeMapFeaturesConfig) => {
>       set({ mapConfig: cloneDeep(config), mapId: config.mapId });
> ```

I suggested in the abstract-geoview-layer-ts file to remove the original copy made there. However, the cloned copy made here must be done at the very first time of execution and the property must stay unaltered till the end of execution because it is the backup of the config provided by the user. Maybe a comment abovr the property declaration should be added to inform the developpers of this constraint.



_Code quote:_
```XML
set({ mapConfig: cloneDeep(config), mapId: config.mapId });
```
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 254 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCfPooCdZHSu__vT3v:-NmCfPooCdZHSu__vT3w:b-ifx7ir) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04c41e2f0e5e5984e8f4584fcf5379355e99f211/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L254)):*
> ```XML
> 
>   /** Original map layer configuration */
>   originalMapLayerConfig: TypeGeoviewLayerConfig;
> ```

Since we keep the config in the store, we can delete this cloned copy of it. Just make sure the copy in the store is made at the very beginning of the execution to keep an intact version of it.



_Code quote:_
```XML
  /** Original map layer configuration */
  originalMapLayerConfig: TypeGeoviewLayerConfig;
```
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 329 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCg2BM1mT9DB9Uf93Z:-NmCg2BM1mT9DB9Uf93_:b-ifx7ir) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04c41e2f0e5e5984e8f4584fcf5379355e99f211/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L329)):*
> ```XML
>   constructor(type: TypeGeoviewLayerType, mapLayerConfig: TypeGeoviewLayerConfig, mapId: string) {
>     this.mapId = mapId;
>     this.originalMapLayerConfig = cloneDeep(mapLayerConfig);
> ```

Since we keep the config in the store, we can delete this cloned copy of it. Just make sure the copy in the store is made at the very beginning of the execution to keep an intact version of it.



_Code quote:_
```XML
this.originalMapLayerConfig = cloneDeep(mapLayerConfig);
```

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647)* status: 40 of 45 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/public/configs/package-time-slider-config.json` line 62 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCAkv80DENTiOBMtLS:-NmCmU_z-ZiyufkvgZPt:b-amqrk7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/public/configs/package-time-slider-config.json#L62)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Does this work without footer-panel?
</blockquote></details>

No it wont
___
*[`packages/geoview-core/src/app.tsx` line 36 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmC8OCKEBu60WZtEDr_:-NmCmgvG6_-YZCGQk2hV:bgwexof) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04c41e2f0e5e5984e8f4584fcf5379355e99f211/packages/geoview-core/src/app.tsx#L36)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Do we need to create a function for a single line instruction. You can export reactRoot here and import it in map-viewer.ts. If I'm right, this is the only place you need it and the code there would be:

    // remove the dom element (remove rendered map and overview map)
    if (this.overviewRoot) this.overviewRoot?.unmount();
    if (reactRoot[this.mapId] !== null) reactRoot[this.mapId].unmount();
</blockquote></details>

Because reactRoot is for all maps, I prefer to keep it encapsulated in app.tsx
___
*[`packages/geoview-core/src/api/plugin/plugin.ts` line 80 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCcP1FAo2jyEJJo4IE:-NmCnZV0Ajj8LtETg9Sz:bb7f2mf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04c41e2f0e5e5984e8f4584fcf5379355e99f211/packages/geoview-core/src/api/plugin/plugin.ts#L80)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

This can be shortened to:
whenThisThen(() =>window.geoviewPlugins?.[pluginId]).then(() => {
</blockquote></details>

done
___
*[`packages/geoview-core/src/api/plugin/plugin.ts` line 101 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCcx1bET_BMPBeb63P:-NmCnw0H82ThRvljioQJ:bb7f2mf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04c41e2f0e5e5984e8f4584fcf5379355e99f211/packages/geoview-core/src/api/plugin/plugin.ts#L101)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Can be shortened to:
if (!api.maps?.[mapId]?.plugins?.[pluginId]) {
</blockquote></details>

done
___
*[`packages/geoview-core/src/api/plugin/plugin.ts` line 188 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCBhdF0uMkp_9_TcHB:-NmCk01dDvi5cmr1X9yq:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/src/api/plugin/plugin.ts#L188)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

attacht he plugin tot he > attach the map to the
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 42 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCiKPB6gEpBWfnBBlm:-NmClGUyAuh8-AdGqst_:b-6iqzuw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04c41e2f0e5e5984e8f4584fcf5379355e99f211/packages/geoview-core/src/core/stores/geoview-store.ts#L42)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I suggested in the abstract-geoview-layer-ts file to remove the original copy made there. However, the cloned copy made here must be done at the very first time of execution and the property must stay unaltered till the end of execution because it is the backup of the config provided by the user. Maybe a comment abovr the property declaration should be added to inform the developpers of this constraint.
</blockquote></details>

Added a comment, will use store config in a next PR were I will remove the passing of mapFeatureConfig object
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 254 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCfPooCdZHSu__vT3v:-NmCmAeD6qQPfpEuHoAv:bydi30s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04c41e2f0e5e5984e8f4584fcf5379355e99f211/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L254)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Since we keep the config in the store, we can delete this cloned copy of it. Just make sure the copy in the store is made at the very beginning of the execution to keep an intact version of it.
</blockquote></details>

Will take care of in my next PR
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 329 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCg2BM1mT9DB9Uf93Z:-NmCmF5K2B3J2fQWfgGQ:bydi30s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/04c41e2f0e5e5984e8f4584fcf5379355e99f211/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L329)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Since we keep the config in the store, we can delete this cloned copy of it. Just make sure the copy in the store is made at the very beginning of the execution to keep an intact version of it.
</blockquote></details>

Will take care of in my next PR

**Review by ychoquet — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

**Review by ychoquet — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
I like the window.geoviewPlugins, much clearer.

> Reviewed 31 of 36 files at r1, 5 of 11 files at r2, 6 of 6 files at r3, 2 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-:-NmCntCm1eGog5c0L4or:b-f9wq3d)* status: all files reviewed, 7 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/public/configs/package-time-slider-config.json` line 62 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCAkv80DENTiOBMtLS:-NmClRM84c53BIf6hyG-:b-ghzihq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/public/configs/package-time-slider-config.json#L62)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Does this work without footer-panel?
</blockquote></details>

That seems a bit strange to me too.
I thought the footer-panel was the one deciding what "inner plugins or inner tabs" to load based on its `defaultTabs` configuration property. Is that not the case?


___
*[`packages/geoview-core/public/templates/package-footer-panel-geochart.html` line 41 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCnTcK8bTJPxFhwedd:-NmCnTcK8bTJPxFhwede:bo7w4na) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/public/templates/package-footer-panel-geochart.html#L41)):*
> ```HTML
> 
>     <hr />
>     <div id="UIM10" class="geoview-map" data-lang="en" data-config-url="./configs/package-footer-panel-geochart-map1-config.json"></div>
> ```

This should already haven been merged by my PR earlier no? Maybe missing a rebase here?

Oh, reviewable just synced on me and it seems like it's okay now. I guess the branch got rebased?
___
*[`packages/geoview-core/public/templates/package-geochart.html` line 79 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCodqk817rsFGtGsxq:-NmCodqk817rsFGtGsxr:b-rghbm6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/public/templates/package-geochart.html#L79)):*
> ```HTML
>         // Load the config for the GeoChart
>         cgpv.api.maps['UIM10'].plugins['geochart'].loadConfig(config);
>         cgpv.api.maps['UIM11'].plugins['UIM11']['geochart'].loadConfig(config);
> ```

This seems wrongly written?
___
*[`packages/geoview-core/src/api/event-processors/index.ts` line 22 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCncpC9Aij3svtPKLZ:-NmCncpC9Aij3svtPKL_:b-d3gtme) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/src/api/event-processors/index.ts#L22)):*
> ```XML
> 
>   // package stores, only create if needed
>   if (store.getState().mapConfig!.corePackages?.includes('time-slider')) timeSliderEventProcessor.onInitialize(store);
> ```

Same general warning bell as explained in the other comment (below), do we really want to have "possible plugins" stuff inside the core like that?
___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 50 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCmhRJ-_ZpCBNXoJB7:-NmCmhRJ-_ZpCBNXoJB8:bpovttt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/src/core/stores/geoview-store.ts#L50)):*
> ```XML
> 
>       // packages states, only create if needed
>       if (config.corePackages?.includes('time-slider')) set({ timeSliderState: initializeTimeSliderState(set, get) });
> ```

This kind of pattern implies we want the `geoview-store` to start maintaining "possible plugins" states? I'm not sure about it, but haven't given it much thought, just rings a warning bell to me..
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts` line 209 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCpB674_AxLSjpzKpO:-NmCpB674_AxLSjpzKpP:b-clny6z) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts#L209)):*
> ```XML
> 
>         if (layerConfig.initialSettings?.extent)
>           layerConfig.initialSettings.extent = api.projection.transformExtent(
> ```

A thought: instead of having lots of duplication of 'EPSG: XXX', 'EPSG: XXX' written everywhere prior to calling transformExtent(), maybe have a `transformExtentEPSG`function sitting right next to `transformExtent` in `projection`class and have the 'EPSG' concatenation happen there. Would make the calls more straightforward everywhere imo. Admitedly there might be some concerns where `projection.getCode()`is used to call, but still?

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 1 of 36 files at r1, 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647)* status: all files reviewed, 7 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/public/configs/package-time-slider-config.json` line 62 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCAkv80DENTiOBMtLS:-NmCqcys4YuMaLMctbpT:bwrpgvx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/public/configs/package-time-slider-config.json#L62)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

That seems a bit strange to me too.
I thought the footer-panel was the one deciding what "inner plugins or inner tabs" to load based on its `defaultTabs` configuration property. Is that not the case?


</blockquote></details>

and

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647)* status: all files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/public/configs/package-time-slider-config.json` line 62 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCAkv80DENTiOBMtLS:-NmCrRwMAueAF31SL8De:bdbdeuv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/public/configs/package-time-slider-config.json#L62)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

and

</blockquote></details>

It is the one who decide, but it will be better to have a clue on the config use for the viewer. Will need a bit of refactoring
___
*[`packages/geoview-core/public/templates/package-footer-panel-geochart.html` line 41 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCnTcK8bTJPxFhwedd:-NmCreH03UfycQpqdktw:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/public/templates/package-footer-panel-geochart.html#L41)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

This should already haven been merged by my PR earlier no? Maybe missing a rebase here?

Oh, reviewable just synced on me and it seems like it's okay now. I guess the branch got rebased?
</blockquote></details>

Done
___
*[`packages/geoview-core/public/templates/package-geochart.html` line 79 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCodqk817rsFGtGsxq:-NmCrq3N-C-R1gJz_w8V:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/public/templates/package-geochart.html#L79)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

This seems wrongly written?
</blockquote></details>

Done
___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 50 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCmhRJ-_ZpCBNXoJB7:-NmCqcAM0ufXLa2aOP9B:b-qigeen) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/src/core/stores/geoview-store.ts#L50)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

This kind of pattern implies we want the `geoview-store` to start maintaining "possible plugins" states? I'm not sure about it, but haven't given it much thought, just rings a warning bell to me..
</blockquote></details>

?Yeah, but it is core plugins... so technically it is part of core. Just to minimize package we make it live outside
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts` line 209 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCpB674_AxLSjpzKpO:-NmCqqKABEFKoFxM4LUC:bv7arzy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts#L209)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

A thought: instead of having lots of duplication of 'EPSG: XXX', 'EPSG: XXX' written everywhere prior to calling transformExtent(), maybe have a `transformExtentEPSG`function sitting right next to `transformExtent` in `projection`class and have the 'EPSG' concatenation happen there. Would make the calls more straightforward everywhere imo. Admitedly there might be some concerns where `projection.getCode()`is used to call, but still?
</blockquote></details>

Yeah it is why I kept it like this because even when we store variable sometime we use code as number sometimes string

**Review by DamonU2 — APPROVED** [review]
> Reviewed 1 of 11 files at r2, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647)* status: all files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/public/configs/package-time-slider-config.json` line 62 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCAkv80DENTiOBMtLS:-NmCswufDDhTHuklWZC9:b-l1pz4n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/public/configs/package-time-slider-config.json#L62)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It is the one who decide, but it will be better to have a clue on the config use for the viewer. Will need a bit of refactoring
</blockquote></details>

If it is going to be in corePackages, it seems like it shoudn't need to be in the default tabs as well.

**Review by jolevesq — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647)* status: 42 of 45 files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/api/event-processors/index.ts` line 22 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCncpC9Aij3svtPKLZ:-NmCuu8l9kdwS7riBCni:bqrpmnm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/src/api/event-processors/index.ts#L22)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Same general warning bell as explained in the other comment (below), do we really want to have "possible plugins" stuff inside the core like that?
</blockquote></details>

Will have to refactor

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 1 of 5 files at r4, 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647)* status: 44 of 45 files reviewed, 1 unresolved discussion (waiting on @DamonU2, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/public/configs/package-time-slider-config.json` line 62 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCAkv80DENTiOBMtLS:-NmCuA6k-ba-giVrG2wy:b-xy8g8m) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/public/configs/package-time-slider-config.json#L62)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

If it is going to be in corePackages, it seems like it shoudn't need to be in the default tabs as well.
</blockquote></details>

I think it needs to be in default tabs as well, because the footer will want to know what order to add the stuff, maybe?

Well, I mean, it's functional that way, it's just that one has to remember that to have the 'time-slider' in the footer, they need to write the 'time-slider' flag in 2 distinct configs (map config corePackages and footer config defaultTabs) to really have it work. It can be a rule, that any plugins inside footer plugin must appear in corePackages. Or we refactor later yeah.
___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 50 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647#-NmCmhRJ-_ZpCBNXoJB7:-NmCv3j75GQJ-C82PtJS:b-9k3a7f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d59e4c57f83e9e404de22888809015a558a21ee0/packages/geoview-core/src/core/stores/geoview-store.ts#L50)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

?Yeah, but it is core plugins... so technically it is part of core. Just to minimize package we make it live outside
</blockquote></details>

After some talking, I'd vote to have 1 store like you wanted (not have multiple stores per plugin), but have the logic to "append" states happen in the plugins code, not in the geoview-store code itself. geoview-store would just expose a way to "append" plugin states if you will.

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647)* status: 44 of 45 files reviewed, 1 unresolved discussion (waiting on @DamonU2, @jolevesq, and @ychoquet)

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1647)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2 and @ychoquet)

**Pull request merged**
