### PR TITLE
refactor(store): add controls to legendLayers

### LINKED ISSUE #1835: [REFACTOR] Controls vs State
**Is there an existing issue for this?**
Please search to see if an issue already exists for this feature.
No

**Who request this Feature**
Individual, team, project, organization...
Geoview

**User Story**
A concise description of what you expected to happen (one paragraph).
We need to have a different approach between layers control and layer state. Controls are what will be display on UI to let user interact with the layer. Controls are define at creation time, store in layers-state and never be modified after.

In the other hand, layer state hold the sate of layer (visible/not visible; hoverable / not hoverable; ,,,) This may change from api call amd/or user interaction from UI controls. The sate should be attach to the layer order array in mapstate. This array __ONLY KEEPS BOOLEAN__ state. 

**Implementation UI**
If needed, what user interface do you suggest, feel free to add mockups.

__CONTROLS__ in layerState - legendLayers
```
{
  "bounds": [],
  "layerId": "lakes",
  ...
  "controls": { visibility: true, query: true, hover: true, remove: true, opacity: true, table: true, highlight: true, zoom: true, .... other??? }


}
```

__STATES__ in mapState LayerOrder
```
{
  "layerPath": "esriFeatureLYR4/8",
  "visible": true,
  "queryable": true,
  "hoverable": true
  "leaf": true/false (false when group, not layer itself) would it be nice to know easily ???
other boolean state ???
}
```

So a controls - visibility : false and state - visible : true = always visible because true by default and no UI to change value.
__NOTE__ we can always go with the api and modify the value. We do not lock down state

__NOTE__ the only time remove button is ALSWAYS there is when layer is in error

Update schema accordingly
**Additional context**

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #1835

# Description

Added controls to legend Layer to activate/deactivate ui components. Fixes to item visibility. Visibility returned to boolean. Fixes issues with time-slider.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested here: https://damonu2.github.io/geoview/raw-feature-info.html

Water quantity:             
            'initialSettings': { 
              'visible': true,
              'controls': {'visibility': false}
             },
uniqueValue:
             'initialSettings': { 
              'controls': {
                'visibility': true,
                'zoom': false,
                'highlight': false,
                'table': false,
                'opacity': false
              }
Top projects:
             'initialSettings': { 
                  'visible': true,
                  'controls': {
                    'visibility': false,
                    'remove': false
                  }
               }
GeoJSON sample - icon points
              'initialSettings': { 
                   'visible': true,
                   'controls': {'visibility': false}
               }

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 12 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932)* status: 12 of 39 files reviewed, 3 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/schema.json` line 441 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-NsyZoVt12tAmYM17OvM:-NsyZoVt12tAmYM17OvN:bm81bwm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/schema.json#L441)):*
> ```JSON
>       }
>     },
>     "TypeLayerControls": {
> ```

Discussion... it is all Boolean, it is less explicit but array of control with enum, if there = true. Would it be better?
___
*[`packages/geoview-core/schema.json` line 490 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-NsyZHon1oIPndM1quvF:-NsyZHoo3LWK0gXp0wjb:brt7ud3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/schema.json#L490)):*
> ```JSON
>           "description": "Initial opacity setting."
>         },
>         "controls": {
> ```

Should we put controls a level up initialControlSettings? Really separated from layer state?
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts` line 192 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-Nsyg5aQ-fMcYmez29LT:-Nsyg5aQ-fMcYmez29LU:boky2lt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts#L192)):*
> ```XML
>   ): void {
>     const layerType = api.maps[mapId].layer.geoviewLayer(layerPath).type;
>     if (layerType === 'ogcWms') {
> ```

We had the type to remove the string. We should try to solve the type

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932)* status: 12 of 39 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/schema.json` line 441 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-NsyZoVt12tAmYM17OvM:-NsygujzBsBgnnJ8REjU:b6xg2ln) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/schema.json#L441)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Discussion... it is all Boolean, it is less explicit but array of control with enum, if there = true. Would it be better?
</blockquote></details>

I think with boolean it is much clearer when writing the config, and simpler to implement throughout.
___
*[`packages/geoview-core/schema.json` line 490 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-NsyZHon1oIPndM1quvF:-NsyhH1R-SnqmiyF7Pez:bl26mh9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/schema.json#L490)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we put controls a level up initialControlSettings? Really separated from layer state?
</blockquote></details>

I had it like that initially, but it is used throughout the code where initial settings is used, so it made sense to me keep them together. No real difference though, can easily be either place.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932)* status: 12 of 39 files reviewed, 2 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/schema.json` line 490 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-NsyZHon1oIPndM1quvF:-NsysGpHED8M1NYdvirE:bro2c91) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/schema.json#L490)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

I had it like that initially, but it is used throughout the code where initial settings is used, so it made sense to me keep them together. No real difference though, can easily be either place.
</blockquote></details>

CAn we wrapped the states setting in a state property so we have { initialSettings: { states: {}, controls: {} }

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 7 of 39 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932)* status: 19 of 39 files reviewed, 3 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/public/templates/layers/geojson.html` line 82 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-NsytwzwC9i0mJiASyRr:-NsytwzwC9i0mJiASyRs:b-fnwai5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/public/templates/layers/geojson.html#L82)):*
> ```HTML
>               'metadataAccessPath': { 'en': './datasets/geojson/metadata.json' },
>               'geoviewLayerType': 'GeoJSON',
>               'initialSettings': { 'visible': true },
> ```

Do we make this that if it is undefined, it takes metadata by value 
(if there) or true?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 16 of 39 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932)* status: 35 of 39 files reviewed, 6 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 177 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-NsyuQJU6n0cXlMJj6MQ:-NsyuQJU6n0cXlMJj6MR:b-3c613i) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L177)):*
> ```XML
>         createNewLegendEntries(entryLayerPath, currentLevel + 1, existingEntries[entryIndex].children);
>       } else if (layerConfig) {
>         const controls: TypeLayerControls = {
> ```

Can this becomes a function, it is a duplicate of code above
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 217 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-NsyuvQh6cfQd_pm9iba:-NsyuvQh6cfQd_pm9ibb:b5xdg40) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L217)):*
> ```XML
>         </IconButton>
>         {layerDetails.controls?.highlight !== false && (
>           <IconButton
> ```

Maybe create functions to get those buttons. I think Chris did this for the view-add-delete toolbar. It encapsulate the button in a function. Other to comments....
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1067 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-NsyvJ9N6kH-z_jEdknH:-NsyvJ9N6kH-z_jEdknI:b-83t6q6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1067)):*
> ```XML
>     if (initialSettings?.opacity !== undefined) layerGroupOptions.opacity = initialSettings?.opacity;
>     if (initialSettings?.visible !== undefined) layerGroupOptions.visible = initialSettings?.visible;
>     // You dont have to provide the loadEndListenerType when you set the olLayer of an entryType = 'group'.
> ```

No string, use type

**Review by ychoquet — APPROVED** [review]
> Reviewed 39 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932)* status: all files reviewed, 6 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/schema.json` line 490 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-NsyZHon1oIPndM1quvF:-Nt1_ug65fXPcfjZwHsf:blajlt7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/schema.json#L490)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

CAn we wrapped the states setting in a state property so we have { initialSettings: { states: {}, controls: {} }
</blockquote></details>

What about 
"visible": { "initialValue": true, "control": false }
___
*[`packages/geoview-core/public/templates/layers/geojson.html` line 82 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-NsytwzwC9i0mJiASyRr:-Nt1bRZXECRCBxAvsu7e:bqripst) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/public/templates/layers/geojson.html#L82)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we make this that if it is undefined, it takes metadata by value 
(if there) or true?
</blockquote></details>

In the case of geojson, if we have metadata and the config says nothing, we use the metadata values.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts` line 192 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-Nsyg5aQ-fMcYmez29LT:-Nt1dIc0CvFH0XGg7KE_:b-gfozfz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts#L192)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We had the type to remove the string. We should try to solve the type
</blockquote></details>

Is there a problem with the type. Why do we replace the CONST_LAYER_TYPES.WMS with 'ogcWms'?

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932)* status: 9 of 46 files reviewed, 6 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/schema.json` line 490 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-NsyZHon1oIPndM1quvF:-NtItBMc7F0Q2DnBiwpq:b81hpba) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/schema.json#L490)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

What about 
"visible": { "initialValue": true, "control": false }
</blockquote></details>

States are moved to their own property.
___
*[`packages/geoview-core/public/templates/layers/geojson.html` line 82 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-NsytwzwC9i0mJiASyRr:-NtH3CMX9Jyr9XLaDgaX:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/public/templates/layers/geojson.html#L82)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

In the case of geojson, if we have metadata and the config says nothing, we use the metadata values.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 177 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-NsyuQJU6n0cXlMJj6MQ:-NtH4nn_0GJFBfbBUYUT:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L177)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can this becomes a function, it is a duplicate of code above
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts` line 192 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-Nsyg5aQ-fMcYmez29LT:-NtItL9e7EalwZRGyTqJ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts#L192)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Is there a problem with the type. Why do we replace the CONST_LAYER_TYPES.WMS with 'ogcWms'?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 217 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-NsyuvQh6cfQd_pm9iba:-NtItMce3ZlJMVP6-lKq:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L217)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Maybe create functions to get those buttons. I think Chris did this for the view-add-delete toolbar. It encapsulate the button in a function. Other to comments....
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 39 files at r1, 8 of 34 files at r2, 1 of 4 files at r3, 30 of 31 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932)* status: 45 of 46 files reviewed, 1 unresolved discussion (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 213 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-NtX8xXI4PXLKPYLiJ41:-NtX8xXI4PXLKPYLiJ42:biz3l2z) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ade0b40be757ee8dd704d6904218bed779fc1fee/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L213)):*
> ```XML
>         </IconButton>
>       );
>     return null;
> ```

3 return in a function... Technically we should have only one return by function (when we can). We should put at list comment on the if and explain why there is 3 return

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932)* status: 44 of 46 files reviewed, 1 unresolved discussion (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 213 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-NtX8xXI4PXLKPYLiJ41:-NtXEXyX4aMmSzQVX5aT:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ade0b40be757ee8dd704d6904218bed779fc1fee/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L213)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

3 return in a function... Technically we should have only one return by function (when we can). We should put at list comment on the if and explain why there is 3 return
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1067 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932#-NsyvJ9N6kH-z_jEdknH:-NtW_WDW6yp_g7-6gffl:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f20d6ab9bbe6a31fd9ed0f6347f5f4f07e454352/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1067)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

No string, use type
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 31 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932)* status: 45 of 46 files reviewed, 1 unresolved discussion (waiting on @DamonU2)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1932)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @DamonU2)

**Pull request merged**
