### PR TITLE
1340 store subscribe with selector

### LINKED ISSUE #1340: [FEATURE] Implement subscribe with selector in the code
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Christopher Phelefu

### User Story

Implement subscribeWithSelector in our stores.

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

This PR implements subscribeWithSelector in the code.

Fixes #1340

## Type of change

- [] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__

# Checklist:

- [X] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [X] I have connected the issues(s) to this PR
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1341)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1341)* status: all files reviewed, 1 unresolved discussion (waiting on @cphelefu)

___
*[`packages/geoview-core/src/core/stores/stores-managers.ts` line 19 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1341#-NfHx_I79tuevdYkD3jB:-NfHx_I96aXI4Yp1D6XC:bhes4aa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/dac9b3131efed3223478eacf3d46914baae87627/packages/geoview-core/src/core/stores/stores-managers.ts#L19)):*
> ```XML
>     return;
>   }
>   // const geoViewStore2 = createStore<IGeoViewState>(geoViewStoreDefinition);
> ```

Remove dead code

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1341)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/stores/stores-managers.ts` line 19 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1341#-NfHx_I79tuevdYkD3jB:-NfI4HwS-flp_13WIlbC:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/dac9b3131efed3223478eacf3d46914baae87627/packages/geoview-core/src/core/stores/stores-managers.ts#L19)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove dead code
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1341)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @cphelefu)

**Review by jolevesq — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1341#-:-NfIZg0588NrQDHlQ-jq:bg7igkv)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @cphelefu)

**Review by jolevesq — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1341)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Review by cphelefu — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1341)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
