### PR TITLE
refactor sample-page moving style to css file

### PR DESCRIPTION
**Pull request by melzeiny1980**
## Checklist

* [ ] Commit message follow the guidelines
* [ ] PR targets the correct release version
* [ ] Deploy has been done
* [ ] Check styling
* [ ] _Help files and documentation have been updated_
* [ ] ~Release notes have been updated~

## What's to look for styling
* Use camelCase for identifier names (variables and functions)
* Use PascalCase for type names
* Do not use "I" as a prefix for interface names
* Do not export types/functions unless you need to share it across multiple components
* All names start with a letter
* Always put spaces around operators ( = + - * / ), and after colon:
* Remove all trailing white spaces
* Look for bad indentation
* Carriage return are mandatory
  * Before comments
  * Before if condition
  * After if condition
  * Before properties
  * Before classes
  * Before functions

The use of Prettier Visual Studio Code extension let's you format automatically your code to remove most of the styling issues like white space and indentation.

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135)

### CODE REVIEW

**Comment by melzeiny1980** [comment]
closes #123

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135)* status: 0 of 12 files reviewed, 15 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[public/index.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz2C_F9ieooY1OSdQV:-MUz2C_F9ieooY1OSdQW:bioms0t) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/index.html#L7)):*
> ```HTML
>         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>         <title><%= htmlWebpackPlugin.options.title %></title>
>         <link rel="stylesheet" href="css/style.css" />
> ```

Put this link style just above </head>
___
*[public/css/style.css, line 39 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz2RKc2_pW-R5tcnhx:-MUz2RKc2_pW-R5tcnhy:btm2qe0) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/css/style.css#L39)):*
> ```CSS
>     margin: 10px;
> }
> .header-title {
> ```

Carriage return between elements
___
*[public/css/style.css, line 54 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz2WmnAAzktuWD3ab6:-MUz2WmnAAzktuWD3ab7:btm2qe0) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/css/style.css#L54)):*
> ```CSS
>     margin-right: auto;
> }
> .header-logo {
> ```

Carriage return between elements
___
*[public/templates/add-panels.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz48vm4RFAWxWOwlF6:-MUz48vm4RFAWxWOwlF7:bioms0t) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/add-panels.html#L7)):*
> ```HTML
>         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>         <title><%= htmlWebpackPlugin.options.title %></title>
>         <link rel="stylesheet" href="css/style.css" />
> ```

Put this link style just above </head>
___
*[public/templates/basemap-switcher.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz47H11AWzYNLAXxXF:-MUz47H11AWzYNLAXxXG:bioms0t) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/basemap-switcher.html#L7)):*
> ```HTML
>         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>         <title><%= htmlWebpackPlugin.options.title %></title>
>         <link rel="stylesheet" href="css/style.css" />
> ```

Put this link style just above </head>
___
*[public/templates/basemap-switcher.html, line 31 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz3qgL6PB5cnmaNZ3m:-MUz3qgL6PB5cnmaNZ3n:bi2a4mz) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/basemap-switcher.html#L31)):*
> ```HTML
>                             <h1><strong>Basemap Switcher Plugin</strong></h1>
>                         </td>
>                     </tr>
> ```

Basemap switcher sample doesn't work anymore. Please create an issue for it
___
*[public/templates/basemaps.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz449YCe7uJ_7Y9W9j:-MUz449YCe7uJ_7Y9W9k:bioms0t) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/basemaps.html#L7)):*
> ```HTML
>         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>         <title><%= htmlWebpackPlugin.options.title %></title>
>         <link rel="stylesheet" href="css/style.css" />
> ```

Put this link style just above </head>
___
*[public/templates/events.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz4CkzAKw_vLbZt8KB:-MUz4Cl-6m8y14nrwR-7:bioms0t) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/events.html#L7)):*
> ```HTML
>         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>         <title><%= htmlWebpackPlugin.options.title %></title>
>         <link rel="stylesheet" href="css/style.css" />
> ```

Put this link style just above </head>
___
*[public/templates/languages.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz4R1t3hfQYZG7qKYP:-MUz4R1t3hfQYZG7qKYQ:bioms0t) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/languages.html#L7)):*
> ```HTML
>         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>         <title><%= htmlWebpackPlugin.options.title %></title>
>         <link rel="stylesheet" href="css/style.css" />
> ```

Put this link style just above </head>
___
*[public/templates/layers.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz4TKy6LiiWQA-a7p1:-MUz4TKy6LiiWQA-a7p2:bioms0t) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/layers.html#L7)):*
> ```HTML
>         <meta name="viewport" content="width=device-width,initial-scale=1" />
>         <title>Canadian Geospatial Platform Viewer</title>
>         <link rel="stylesheet" href="css/style.css" />
> ```

Put this link style just above </head>
___
*[public/templates/projections.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz4bRn6vKOogR7i47j:-MUz4bRoAyrPZ9mKJWgF:bioms0t) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/projections.html#L7)):*
> ```HTML
>         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>         <title><%= htmlWebpackPlugin.options.title %></title>
>         <link rel="stylesheet" href="css/style.css" />
> ```

Put this link style just above </head>
___
*[public/templates/responsive_page.html, line 44 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz4kk61H8kihLvZ76L:-MUz4kk61H8kihLvZ76M:btm2qe0) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/responsive_page.html#L44)):*
> ```HTML
>                 width: 1366px;
>                 height: 800px;
>             }
> ```

Carriage return between elements
___
*[public/templates/responsive_page_map.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz4wPV4dfSNHayilRK:-MUz4wPV4dfSNHayilRL:bioms0t) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/responsive_page_map.html#L7)):*
> ```HTML
>         <meta name="viewport" content="width=device-width,initial-scale=1" />
>         <title>Canadian Geospatial Platform Viewer</title>
>         <link rel="stylesheet" href="css/style.css" />
> ```

Put this link style just above </head>
___
*[public/templates/responsive_page_map.html, line 19 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz4xOF3HqNjOBjN74C:-MUz4xOF3HqNjOBjN74D:brr4dm8) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/responsive_page_map.html#L19)):*
> ```HTML
>             #RPT1 {
>                 height: 1000px;
>                 
> ```

Trailing white space
___
*[public/templates/usecases.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz5-eGDzDApDTAUk88:-MUz5-eGDzDApDTAUk89:bioms0t) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/usecases.html#L7)):*
> ```HTML
>         <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>         <title><%= htmlWebpackPlugin.options.title %></title>
>         <link rel="stylesheet" href="css/style.css" />
> ```

Put this link style just above </head>

**Comment by melzeiny1980** [comment]
___
*[public/index.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz2C_F9ieooY1OSdQV:-MV1_tJH3sNoRAaLfpyi:bpnxxpk) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/index.html#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put this link style just above </head>
</blockquote></details>

sorry , you mean above all other tags ?

**Review by melzeiny1980 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135)* status: 0 of 12 files reviewed, 15 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[public/css/style.css, line 39 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz2RKc2_pW-R5tcnhx:-MV1cWQM1KhzweJmfsY0:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/css/style.css#L39)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return between elements
</blockquote></details>

Done.
___
*[public/css/style.css, line 54 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz2WmnAAzktuWD3ab6:-MV1cWtR3ShJBBZ352xZ:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/css/style.css#L54)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Carriage return between elements
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135)* status: 0 of 12 files reviewed, 15 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[public/index.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz2C_F9ieooY1OSdQV:-MV1jfEdEHcYLUUSkWWb:b-255a7b) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/index.html#L7)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

sorry , you mean above all other tags ?
</blockquote></details>

My bad, I forgot to add above the </head> tag.... for all style.css link tag

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135)* status: 1 of 12 files reviewed, 10 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

**Review by melzeiny1980 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135)* status: 1 of 12 files reviewed, 10 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[public/index.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz2C_F9ieooY1OSdQV:-MV1uX-zBwaNQkPRsqlj:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/index.html#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

My bad, I forgot to add above the </head> tag.... for all style.css link tag
</blockquote></details>

Done.
___
*[public/templates/add-panels.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz48vm4RFAWxWOwlF6:-MV1uXo01_6ONM1mm-xJ:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/add-panels.html#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put this link style just above </head>
</blockquote></details>

Done.
___
*[public/templates/basemap-switcher.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz47H11AWzYNLAXxXF:-MV1uYa76yFVt-_TLtOv:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/basemap-switcher.html#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put this link style just above </head>
</blockquote></details>

Done.
___
*[public/templates/basemaps.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz449YCe7uJ_7Y9W9j:-MV1uZ8Y2JedfACgO2EA:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/basemaps.html#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put this link style just above </head>
</blockquote></details>

Done.
___
*[public/templates/events.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz4CkzAKw_vLbZt8KB:-MV1uZkSA64HMUKxcARl:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/events.html#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put this link style just above </head>
</blockquote></details>

Done.
___
*[public/templates/languages.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz4R1t3hfQYZG7qKYP:-MV1u_KKD08m2OZi4KNv:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/languages.html#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put this link style just above </head>
</blockquote></details>

Done.
___
*[public/templates/layers.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz4TKy6LiiWQA-a7p1:-MV1u_mA2U7RNVXWoX3P:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/layers.html#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put this link style just above </head>
</blockquote></details>

Done.
___
*[public/templates/projections.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz4bRn6vKOogR7i47j:-MV1uaKR0ZRZwQBVY8ny:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/projections.html#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put this link style just above </head>
</blockquote></details>

Done.
___
*[public/templates/responsive_page_map.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz4wPV4dfSNHayilRK:-MV1udmHBh5OEOYtrNEF:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/responsive_page_map.html#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put this link style just above </head>
</blockquote></details>

Done.
___
*[public/templates/usecases.html, line 7 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-MUz5-eGDzDApDTAUk88:-MV1ueHv1PU6T8qg9xCh:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2b579f89ec904c55b478de9517c1f52a34d401d1/public/templates/usecases.html#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put this link style just above </head>
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq and @yass0016)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135#-:-MV211PJBdXqPbxuAYib:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq and @yass0016)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/135)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yass0016)

**Pull request merged**
