### PR TITLE
refactor(footer): remove config for footer, add to core config

### LINKED ISSUE #1665: [REFACTOR] Footer Config
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For the moment, every package has a configuration schema. Works well with package like Swiper, Sldier and Geochart. But when it comes to footer, it introduce a 3 level configuration (main-footer-plugin). This is confusing and hard to setup,

### Expected Behavior

We should no more then 2 level (main-plugin). Footer is a package but it act more like a core thing. We should use the footer config directly into the main config as an object like app-bar or nav-bar and set properties from within the core.

We should then move content on schema for footer inside main schema and add a note to the readme of footer.

Later, plugins can create themselves in app-bar or footer from main config.

There may be side effect and a lot of config to modify

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jolevesq**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1665

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

!!!  Known issue, the data table tab is not working anymore as it return a promise and the content is not ready when the footer component is created

__This will be part of data table refactor or #1686__

https://jolevesq.github.io/geoview/languages.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1675)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
> Reviewed 64 of 64 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1675)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 64 of 64 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1675)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/public/locales/fr/translation.json` line 55 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1675#-NoIQ8Mv0WMbj8d8MnYO:-NoIQ8Mv0WMbj8d8MnYP:bej0quo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d797ca4bb7d6b2844909e8454ce0fc223d7b0308/packages/geoview-core/public/locales/fr/translation.json#L55)):*
> ```JSON
>   },
>   "legend": {
>     "title": "Lédende",
> ```

Légende?

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 64 of 64 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1675)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-footer-panel/src/index.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1675#-NoIiWOK0sUvU5kX1qKZ:-NoIiWOK0sUvU5kX1qK_:b-3iq6zf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d797ca4bb7d6b2844909e8454ce0fc223d7b0308/packages/geoview-footer-panel/src/index.tsx#L2)):*
> ```XML
> import { Cast, toJsonObject, TypeJsonObject, AnySchemaObject, TypeJsonValue } from 'geoview-core';
> import { AbstractPlugin } from 'geoview-core/src/api/plugin/abstract-plugin';
> ```

Is there a reason why you want to keep this dead code?

**Review by jolevesq — COMMENTED** [review]
> Reviewed 14 of 16 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1675)* status: 73 of 75 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

**Review by ychoquet — APPROVED** [review]
> Reviewed 16 of 16 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1675)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @DamonU2)

**Pull request merged**
