### PR TITLE
[FEATURE] GeoChart in the store

### LINKED ISSUE #1501: Modify the store to fulfill chart plugin's needs
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Team

### User Story

The charts plugin in its current state must access directly the backend code in order to do what it needs to do. We want it to rely only on the store state like the new implementation does.

### Implementation UI

The UI logic must be based on the store state.

### PR DESCRIPTION
**Pull request by Alex-NRCan**
Removed a GeoChart from template for testing
Store processor stuff first
Simplified back code
Bug fix with layer-state
Typos and cleanup
eslint

Hosted here: https://alex-nrcan.github.io/geoview/

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1501

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__

# Checklist:

- [ ] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 21 of 24 files at r1, 3 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723)* status: 22 of 27 files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/public/templates/package-footer-panel-geochart.html` line 43 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723#-Np55bkC6zRoHoiS_wtM:-Np55bkC6zRoHoiS_wtN:b-ga5v6l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aeaa445daeab038c75ecbc5348b0e4c3cba1d5ba/packages/geoview-core/public/templates/package-footer-panel-geochart.html#L43)):*
> ```HTML
>     <div id="UIM10" class="geoview-map" data-lang="en" data-config-url="./configs/package-footer-panel-geochart-map1-config.json"></div>
>     <hr />
>     
> ```

Should we uncomment?
___
*[`packages/geoview-core/public/templates/package-time-slider.html` line 56 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723#-Np55exY4PYW-P33uxFE:-Np55exY4PYW-P33uxFF:b-ga5v6l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aeaa445daeab038c75ecbc5348b0e4c3cba1d5ba/packages/geoview-core/public/templates/package-time-slider.html#L56)):*
> ```HTML
>       <a class="ref-link" href="#top">Top</a>
>     </div>
>     
> ```

Should we uncomment?
___
*[`packages/geoview-core/src/core/components/common/layout.tsx` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723#-Np56Fmf1QQ5ElUarq1Y:-Np56Fmf1QQ5ElUarq1Z:bm5bknr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aeaa445daeab038c75ecbc5348b0e4c3cba1d5ba/packages/geoview-core/src/core/components/common/layout.tsx#L17)):*
> ```XML
>   layerList: LayerListEntry[];
>   selectedLayerPath: string;
>   // ? Name this onLayerListClicked? and make it optional with '?' suffix?
> ```

Would be a good thing
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/geochart-state.ts` line 27 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723#-Np57Z0l2-EY4BTX_J-W:-Np57Z0l2-EY4BTX_J-X:b9bnuw7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aeaa445daeab038c75ecbc5348b0e4c3cba1d5ba/packages/geoview-core/src/core/stores/store-interface-and-intial-values/geochart-state.ts#L27)):*
> ```XML
>   const init = {
>     geochartChartsConfig: {},
>     // geochartLayers: {},
> ```

Do we need to keep dead code in this file?
___
*[`packages/geoview-geochart/src/geochart.tsx` line 49 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723#-Np57pj06L13ePXDjk8k:-Np57pj06L13ePXDjk8l:b2tvxrm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aeaa445daeab038c75ecbc5348b0e4c3cba1d5ba/packages/geoview-geochart/src/geochart.tsx#L49)):*
> ```XML
>   const defaultColors: GeoChartDefaultColors = {
>     backgroundColor: theme.palette.background.default,
>     borderColor: 'black', // theme.palette.primary,
> ```

We seems to not have a border primary color.... we should crate the theme property or use another one.... or delete
___
*[`packages/geoview-geochart/src/geochart-panel.tsx` line 68 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723#-Np58EyQC1yr8u0dXnbQ:-Np58EyQC1yr8u0dXnbR:b1bkrn0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aeaa445daeab038c75ecbc5348b0e4c3cba1d5ba/packages/geoview-geochart/src/geochart-panel.tsx#L68)):*
> ```XML
>     (layer: TypeLayerData): string => {
>       const numOfFeatures = layer.features?.length ?? 0;
>       return `${numOfFeatures} ${t('details.feature')}${numOfFeatures > 1 ? 's' : ''}`;
> ```

We should use a translation from chart plugin, not details. We should have: x chart ...
___
*[`packages/geoview-geochart/src/geochart-panel.tsx` line 230 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723#-Np59uS87gf4IygelTcP:-Np59uS87gf4IygelTcQ:b75409q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aeaa445daeab038c75ecbc5348b0e4c3cba1d5ba/packages/geoview-geochart/src/geochart-panel.tsx#L230)):*
> ```XML
>     // Loading UI
>     return <Typography>{t('chartPanel.panel.loadingUI')}</Typography>;
>     // return <CircularProgress isLoaded={false} />;
> ```

Do we need dead code?
___
*[`packages/geoview-geochart/src/geochart-style.ts` line 4 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723#-Np5AB0wDkTwkV-WQ-jM:-Np5AB0wDkTwkV-WQ-jN:b-v32h3u) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aeaa445daeab038c75ecbc5348b0e4c3cba1d5ba/packages/geoview-geochart/src/geochart-style.ts#L4)):*
> ```XML
> 
> export const getSxClasses = (theme: Theme) => ({
>   detailsInstructionsTitle: {
> ```

Changer details for Chart
___
*[`packages/geoview-geochart/src/index.tsx` line 40 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723#-Np5ASoXEZ9yN5o0FMus:-Np5ASoXEZ9yN5o0FMut:bnkcfzd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aeaa445daeab038c75ecbc5348b0e4c3cba1d5ba/packages/geoview-geochart/src/index.tsx#L40)):*
> ```XML
>       geochart: {
>         title: 'Chart',
>         panel: {
> ```

### geochart.chartPanel.noLayers
The variable use in the instruction is not in the dictionary

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 16 of 24 files at r1, 4 of 6 files at r2, 11 of 11 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723)* status: all files reviewed, 9 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/common/layout.tsx` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723#-Np56Fmf1QQ5ElUarq1Y:-Np5I_m_C-PYENFXsLvx:b-l34jjk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aeaa445daeab038c75ecbc5348b0e4c3cba1d5ba/packages/geoview-core/src/core/components/common/layout.tsx#L17)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Would be a good thing
</blockquote></details>

Transformed to a TODO
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/geochart-state.ts` line 27 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723#-Np57Z0l2-EY4BTX_J-W:-Np5Ivu8-9qCEZEB7xVL:ba3dfob) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aeaa445daeab038c75ecbc5348b0e4c3cba1d5ba/packages/geoview-core/src/core/stores/store-interface-and-intial-values/geochart-state.ts#L27)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we need to keep dead code in this file?
</blockquote></details>

Removed
___
*[`packages/geoview-geochart/src/geochart.tsx` line 49 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723#-Np57pj06L13ePXDjk8k:-Np5JLWu8yZtj18xXqC2:b-br6q29) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aeaa445daeab038c75ecbc5348b0e4c3cba1d5ba/packages/geoview-geochart/src/geochart.tsx#L49)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We seems to not have a border primary color.... we should crate the theme property or use another one.... or delete
</blockquote></details>

Not sure, but I updated it to use same as color for now
___
*[`packages/geoview-geochart/src/geochart-panel.tsx` line 68 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723#-Np58EyQC1yr8u0dXnbQ:-Np5K0PyBsVMr2lb2ebC:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aeaa445daeab038c75ecbc5348b0e4c3cba1d5ba/packages/geoview-geochart/src/geochart-panel.tsx#L68)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should use a translation from chart plugin, not details. We should have: x chart ...
</blockquote></details>

Done.
___
*[`packages/geoview-geochart/src/geochart-panel.tsx` line 230 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723#-Np59uS87gf4IygelTcP:-Np5K2c61RPiUXzkFpi6:btns0hv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aeaa445daeab038c75ecbc5348b0e4c3cba1d5ba/packages/geoview-geochart/src/geochart-panel.tsx#L230)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we need dead code?
</blockquote></details>

That's because, I would kind of like to see a spinning circle when the tabs are being rendered the first time. Something across all footer tabs. I've remove for now.
___
*[`packages/geoview-geochart/src/geochart-style.ts` line 4 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723#-Np5AB0wDkTwkV-WQ-jM:-Np5KUgPDT3VrvlEapVP:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aeaa445daeab038c75ecbc5348b0e4c3cba1d5ba/packages/geoview-geochart/src/geochart-style.ts#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Changer details for Chart
</blockquote></details>

Done.
___
*[`packages/geoview-geochart/src/index.tsx` line 40 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723#-Np5ASoXEZ9yN5o0FMus:-Np5LvaTBUnHGpQ2bG5d:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aeaa445daeab038c75ecbc5348b0e4c3cba1d5ba/packages/geoview-geochart/src/index.tsx#L40)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

### geochart.chartPanel.noLayers
The variable use in the instruction is not in the dictionary
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/package-footer-panel-geochart.html` line 43 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723#-Np55bkC6zRoHoiS_wtM:-Np5Mb9eD6b5CZRa-bh8:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aeaa445daeab038c75ecbc5348b0e4c3cba1d5ba/packages/geoview-core/public/templates/package-footer-panel-geochart.html#L43)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we uncomment?
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/package-time-slider.html` line 56 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723#-Np55exY4PYW-P33uxFE:-Np5MbUZ8S0pnCftOKet:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/aeaa445daeab038c75ecbc5348b0e4c3cba1d5ba/packages/geoview-core/public/templates/package-time-slider.html#L56)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we uncomment?
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 6 of 11 files at r4, 2 of 2 files at r5, 1 of 2 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 11 files at r4, 1 of 2 files at r6, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1723)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Pull request merged**
