### PR TITLE
feat(navbar): basemap selector added to navbar

### LINKED ISSUE #64: Add simple core basemap switcher
We should have a core basemap switcher to use our default basemap. The switcher will be able to even switch projection from LCC to WM.

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #64

# Description

Basemap selector added to nav bar.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/02-basemap-LCC-SL.json - Has default in panel as basemap defined in config is not one of defaults

https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/02-basemap-LCC-SL.json - No default as basemap is one of defaults

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2371)

### CODE REVIEW

**Review by Alex-NRCan — APPROVED** [review]
:lgtm_strong: Nice PR

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2371#-:-O1vc2jx5_1i8Nm95rNN:b-15q66m)* status: all files reviewed, 3 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts` line 67 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2371#-O1vbQTR17FZmrbHOIYL:-O1vbQTR17FZmrbHOIYM:b-h5u4bt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c5696a30f4f9782eae276a7a6ee02a37e09f70ca/packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts#L67)):*
> ```XML
>     removeHighlightedFeature: (feature: TypeFeatureInfoEntry | 'all') => void;
>     reorderLayer: (layerPath: string, move: number) => void;
>     resetBaseMap: () => Promise<void>;
> ```

Minor
I believe the standard is "basemap" or "Basemap", but not "BaseMap".

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2371)* status: all files reviewed, 4 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts` line 182 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2371#-O1vcQvb5rBnNJh9iGTF:-O1vcQvb5rBnNJh9iGTG:bswa3ep) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c5696a30f4f9782eae276a7a6ee02a37e09f70ca/packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts#L182)):*
> ```XML
>        * @returns {Promise<void>}
>        */
>       createBaseMapFromOptions: (basemapOptions: TypeBasemapOptions): Promise<void> => {
> ```

(same here, `createBasemapFromOption`?)

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2371)* status: 11 of 14 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 680 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2371#-O1v_0D88PaqUqMAodG-:-O1vpOaE1ekE2ck0yRUL:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c5696a30f4f9782eae276a7a6ee02a37e09f70ca/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L680)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank line before if
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/nav-bar/buttons/basemap-select.tsx` line 55 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2371#-O1va1zpBjqL3pq0A1BT:-O1vpPab3pwJRhsNb1ln:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c5696a30f4f9782eae276a7a6ee02a37e09f70ca/packages/geoview-core/src/core/components/nav-bar/buttons/basemap-select.tsx#L55)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we put this props with the panel props at the bottom so they are together
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts` line 182 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2371#-O1vcQvb5rBnNJh9iGTF:-O1vpTSj7X3k0fngV7cp:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c5696a30f4f9782eae276a7a6ee02a37e09f70ca/packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts#L182)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

(same here, `createBasemapFromOption`?)
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2371)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

**Pull request merged**
