### PR TITLE
refactor(store): Refactor north arrow and hover tooltip plus cleaning

### LINKED ISSUE #1476: [REFACTOR] Hover Tooltip Store
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The hover tooltip is still using the api event all query info done.

### Expected Behavior

Need to use the store property

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1476

# Description

Refactor north arrow and hover tooltip component to rely on the store

Fixes #1476

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://jolevesq.github.io/geoview/raw-feature-info-1.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1478)

### CODE REVIEW

**Review by DamonU2 — APPROVED** [review]
> Reviewed 33 of 33 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1478)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1478)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/export/export-modal.tsx` line 45 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1478#-Nion1jL4wATqfrO2UaF:-Nion1jL4wATqfrO2UaG:b86yixd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fac94c6ea15275ba8c1ab43c47a5834b2f6dbad0/packages/geoview-core/src/core/components/export/export-modal.tsx#L45)):*
> ```XML
>   };
> 
>   return (
> ```

Replace quoted code with:

  const exportMap \= ((event): void \=> {
    exportPNG(mapId);
    closeModal(event);
  }) as MouseEventHandler<HTMLButtonElement\>;



_Code quote:_
```XML
  // TODO: fix any type
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const exportMap = (event: any): void => {
    exportPNG(mapId);
    closeModal(event);
  };

  return (
```

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 33 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1478)* status: 32 of 33 files reviewed, 1 unresolved discussion (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/src/core/components/export/export-modal.tsx` line 45 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1478#-Nion1jL4wATqfrO2UaF:-NioqhqO6EjRwz68mfwe:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fac94c6ea15275ba8c1ab43c47a5834b2f6dbad0/packages/geoview-core/src/core/components/export/export-modal.tsx#L45)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Replace quoted code with:

  const exportMap \= ((event): void \=> {
    exportPNG(mapId);
    closeModal(event);
  }) as MouseEventHandler<HTMLButtonElement\>;
</blockquote></details>

Done.

**Review by ychoquet — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1478)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
