### PR TITLE
refactor(legend) Use store action for layers details panel

### LINKED ISSUE #1555: [REFACTOR] Use Store for Legend Action
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

This issue is a sub issue of#1526... It will take care of
Zoom to layer button should propagate to the map
Make sure the visibility icons also toggles layers on the map and legend
Make sure the visibility icons also toggles layers on the map and legend
Table View icon should open the DataTable in a modal **

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1555

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1555

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://jolevesq.github.io/geoview/raw-legend-2.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565)

### CODE REVIEW

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565)* status: all files reviewed, 4 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 120 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWFBi390G6nvrLy3vO:-NkWFBi390G6nvrLy3vP:b-ap3yp6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L120)):*
> ```XML
>         //! may not work with group items ... see if Yves work will make this simplier
>         const layerId: string[] = layerPath.split('/');
>         api.maps[get().mapId].layer.geoviewLayers[layerId[0]]!.setVisible(layer?.isVisible === 'yes', layerPath);
> ```

Change the quoted code to __isVisible !== 'no'__
The layer is visible when the visibility flag is 'yes' or 'always'.



_Code quote:_
```XML
isVisible === 'yes'
```
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 174 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWQPDS1BIGqxtQcdcl:-NkWQPDTDKMBmD5-eTTC:blgtsbk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L174)):*
> ```XML
>               item.isVisible = visibility; // eslint-disable-line no-param-reassign
> 
>               // assign value to registered layer. Thisis use by applyFilter function to set visibility
> ```

Thisis => This is



_Code quote:_
```XML
Thisis
```
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 181 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWR2EX9ZQYGSL1h_8V:-NkWR2EX9ZQYGSL1h_8W:b6iatjk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L181)):*
> ```XML
>           });
>           layer.allItemsChecked = visibility === 'yes';
>           layer.isVisible = visibility;
> ```

We should set this property to undefined when we have at least one item visibility set to always. If layer.isVisible is undefined, we hide the layer visibility icon.



_Suggestion:_
```XML
layer.isVisible = visibility;
```
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 195 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWSpFE9ww3yf8YvOVT:-NkWSpFF7wtf0LeqqzEY:bodr2b0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L195)):*
> ```XML
>         // TODO: we can have always item.... we cannot set visibility so if present we will need to trap. Need more use case
>         const layerId: string[] = layerPath.split('/');
>         api.maps[get().mapId].layer.geoviewLayers[layerId[0]]!.setVisible(visibility === 'yes', layerPath);
> ```

This line of code only set the visibility flag of the layer, not the one of each item categories.



_Code quote:_
```XML
api.maps[get().mapId].layer.geoviewLayers[layerId[0]]!.setVisible(visibility === 'yes', layerPath);
```

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 166 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWhTnU-_bvN30iGZEO:-NkWhTnU-_bvN30iGZEP:b6kiksz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L166)):*
> ```XML
> 
>         // TODO: find the best place to calculate layers item and assign
>         setTimeout(() => {
> ```

Why do we have a timeout here?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/layers/types.ts` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWiBtZ8BJFrCyBbfRs:-NkWiBtZ8BJFrCyBbfRt:bz9xpvx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/components/layers/types.ts#L79)):*
> ```XML
> 
> export interface TypeLegendLayer {
>   bounds: Extent | undefined;
> ```

Make this `bounds?: Extent`

In this way you dont have to add it in helpers or future definations of layers.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/layers/hooks/helpers.ts` line 68 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWiUx-DbepKWvfQyqF:-NkWiUx0CsS7Ji95plFI:b-gq95g) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/components/layers/hooks/helpers.ts#L68)):*
> ```XML
>     const legendLayers: TypeLegendLayer[] = [
>       {
>         bounds: undefined,
> ```

Once we have done `bounds?: Extent`.. we can remove this. Optional.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 47 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWj3a-4ced0WgEx2_h:-NkWj3a-4ced0WgEx2_i:b-jotz6u) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L47)):*
> ```XML
> 
>   const handleOpenTable = () => {
>     openModal({ activeElementId: 'layerDatatable', callbackElementId: `test` });
> ```

Can we change `test` to something else?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 122 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWjEup0d5ntzSbXddl:-NkWjEuq7Hjp6pieMJ4s:bc1wtwc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L122)):*
> ```XML
>     return (
>       <Box sx={{ display: 'flex', flexDirection: 'row', alignItems: 'center', gap: '15px' }}>
>         <IconButton id="test" tooltip="legend.tableDetails" sx={{ backgroundColor: '#F6F6F6' }} onClick={handleOpenTable}>
> ```

id `test` is too generic. We can change it.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 120 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWFBi390G6nvrLy3vO:-NkWkGKlC_dBFhF273Eh:b-c0njbf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L120)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Change the quoted code to __isVisible !== 'no'__
The layer is visible when the visibility flag is 'yes' or 'always'.
</blockquote></details>

Yep, not sure about this too. We should discuss with Yves. I was hoping layerIds would have to be modified to access anything in the backend or in the store.

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565)* status: all files reviewed, 8 unresolved discussions (waiting on @cphelefu and @ychoquet)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 166 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWhTnU-_bvN30iGZEO:-NkWkJqd8jWWI27M8jFr:bc8od33) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L166)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Why do we have a timeout here?
</blockquote></details>

Because ol layer does not exist when we get there. This is why there is the todo. https://github.com/Canadian-Geospatial-Platform/geoview/issues/1566
___
*[`packages/geoview-core/src/core/components/layers/types.ts` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWiBtZ8BJFrCyBbfRs:-NkWlW9N7uvpp-FINZJN:b8h3tw6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/components/layers/types.ts#L79)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Make this `bounds?: Extent`

In this way you dont have to add it in helpers or future definations of layers.
</blockquote></details>

But I do not want it optional, it should always be there and if undefined, we will modify the UI. Having mandatory is more explicit
___
*[`packages/geoview-core/src/core/components/layers/hooks/helpers.ts` line 68 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWiUx-DbepKWvfQyqF:-NkWlf459JwA-k_ZyMTo:b-33b6k6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/components/layers/hooks/helpers.ts#L68)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Once we have done `bounds?: Extent`.. we can remove this. Optional.
</blockquote></details>

See comment above
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 47 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWj3a-4ced0WgEx2_h:-NkWm16B8V6v_JIMF4by:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L47)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Can we change `test` to something else?
</blockquote></details>

Done
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 122 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWjEup0d5ntzSbXddl:-NkWm2XQ6W-Bnwx918T4:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L122)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

id `test` is too generic. We can change it.
</blockquote></details>

Done
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 120 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWFBi390G6nvrLy3vO:-NkWfGJq1GxyuV3_zISj:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L120)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Change the quoted code to __isVisible !== 'no'__
The layer is visible when the visibility flag is 'yes' or 'always'.
</blockquote></details>

Done
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 174 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWQPDS1BIGqxtQcdcl:-NkWfMAeBpLV1I1-18gf:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L174)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Thisis => This is
</blockquote></details>

Done
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 181 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWR2EX9ZQYGSL1h_8V:-NkWiUlB4l5r6E6mlJ9K:b-n4d3f7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L181)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

We should set this property to undefined when we have at least one item visibility set to always. If layer.isVisible is undefined, we hide the layer visibility icon.
</blockquote></details>

We cant because it is not part of the type. We will need some refactor once layers backend is done. 
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 195 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWSpFE9ww3yf8YvOVT:-NkWieF44YYjz4lUH1qj:bnorckz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L195)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

This line of code only set the visibility flag of the layer, not the one of each item categories.
</blockquote></details>

Done

But there is more test to do e.g. if we disable all item, then click on visibility twice and re enable all items. It is not working

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/layers/types.ts` line 79 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWiBtZ8BJFrCyBbfRs:-NkWo-fr3RR_V0JQ4AK6:bxvb527) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/components/layers/types.ts#L79)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

But I do not want it optional, it should always be there and if undefined, we will modify the UI. Having mandatory is more explicit
</blockquote></details>

The two things accomplish the same thing. The only difference is that with `bounds?` - it is assigned undefined it if it not defined

**Review by cphelefu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565)* status: 18 of 23 files reviewed, 4 unresolved discussions (waiting on @ychoquet)

**Review by ychoquet — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 181 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWR2EX9ZQYGSL1h_8V:-NkWruGi9KEXws17gC41:bnz81n2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L181)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We cant because it is not part of the type. We will need some refactor once layers backend is done.
</blockquote></details>

We should be able using the layerPath and the style of the registered layer. If you want, you can comment a TODO and we'll resolve this issue later.
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts` line 195 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565#-NkWSpFE9ww3yf8YvOVT:-NkWsvWw3jNTpbJ01FkA:b-jgu31v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/48959a567b487f452e46708dbc02b143e4032c14/packages/geoview-core/src/core/stores/store-interface-and-intial-values/layer-state.ts#L195)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Done

But there is more test to do e.g. if we disable all item, then click on visibility twice and re enable all items. It is not working
</blockquote></details>

We sould be able to do that using the layer path and the style of the registered layer. If you want, you can comment a TODO and we'll resolve this issue later.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 18 of 22 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565)* status: 22 of 23 files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1565)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @jolevesq)

**Pull request merged**
