### PR TITLE
refactor(store): Use configuration from the store

### LINKED ISSUE #1560: [REFACTOR] Store, Add Table Availability
Add is a data table is available for a layer in the layer-state section. Do this from the back end when we load a layer....

- [ ] Display layers modal datatable button only when available
- [ ] Use availability from datatable to create layer list panel instead of doing it inside data-table api

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1560

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Remove as I can the use of map class configuration and replace by the store. Next step is to make sure config store the good version then every files access the store. When we reload the config the store one is use. Issue #1580
Fixes #1560 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Because it touches many components, I have tested many demo like basemap, basemap paackage, default config, feature info, ...
https://jolevesq.github.io/geoview/index.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1584)

### CODE REVIEW

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 23 of 30 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1584)* status: 29 of 30 files reviewed, 1 unresolved discussion (waiting on @DamonU2, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/public/templates/default-config.html` line 279 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1584#-NkvQp3C4undTHwigFSY:-NkvQp3C4undTHwigFSZ:b-i68pke) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/345ee83f5948719d4dcdf09c5b5c7c4c022425a9/packages/geoview-core/public/templates/default-config.html#L279)):*
> ```HTML
>               }`);
>           }
>         }, 10000);
> ```

1) I seem to recall, couple months ago, that init() was being called with something like mapId = "ALLMAPS" or something like that, when all maps were initialized? Maybe that's not true anymore?

2) If this is temporary code, it's alright, but is there any chance of using utilities.whenThisThenThat() maybe at least instead of a 10 seconds delay?

**Review by jolevesq — COMMENTED** [review]
> Reviewed 30 of 30 files at r1, 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1584)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/public/templates/default-config.html` line 279 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1584#-NkvQp3C4undTHwigFSY:-NkvUcfJ99cjpXNyjKtg:b-o2r3qf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/345ee83f5948719d4dcdf09c5b5c7c4c022425a9/packages/geoview-core/public/templates/default-config.html#L279)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

1) I seem to recall, couple months ago, that init() was being called with something like mapId = "ALLMAPS" or something like that, when all maps were initialized? Maybe that's not true anymore?

2) If this is temporary code, it's alright, but is there any chance of using utilities.whenThisThenThat() maybe at least instead of a 10 seconds delay?
</blockquote></details>

Yeah, the allmaps is coming but it is not true. We should have a chat about the this then that to make sure I use it in the proper way

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 25 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1584)* status: all files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1584#-NkvMPy34MpliIqDWB2V:-NkvMPy34MpliIqDWB2W:bb5l7o9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e568590077388826efbab95f0f2cc7c8f31a04f5/packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts#L17)):*
> ```XML
>   // Static functions for Typescript files to access store actions
>   // **********************************************************
>   //! Typescript MUST always use storte action to modify store - NEVER use setState!
> ```

storte > store
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts` line 18 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1584#-NkvNswYButMA82IYj9R:-NkvNswYButMA82IYj9S:b-hvh6c) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e568590077388826efbab95f0f2cc7c8f31a04f5/packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts#L18)):*
> ```XML
>   // **********************************************************
>   //! Typescript MUST always use storte action to modify store - NEVER use setState!
>   //! Some action does state modfication AND map actions.
> ```

modfication > modification
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1584#-NkvOzgL8J1hg-Ao9Spg:-NkvOzgL8J1hg-Ao9Sph:bb5l7o9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e568590077388826efbab95f0f2cc7c8f31a04f5/packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts#L17)):*
> ```XML
>   // Static functions for Typescript files to access store actions
>   // **********************************************************
>   //! Typescript MUST always use storte action to modify store - NEVER use setState!
> ```

storte > store

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1584)* status: all files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1584#-NkvMPy34MpliIqDWB2V:-NkvVMQv3FE8BcA2UXVC:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e568590077388826efbab95f0f2cc7c8f31a04f5/packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts#L17)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

storte > store
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts` line 18 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1584#-NkvNswYButMA82IYj9R:-NkvVX198MQSa4tU4xOI:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e568590077388826efbab95f0f2cc7c8f31a04f5/packages/geoview-core/src/api/event-processors/event-processor-children/app-event-processor.ts#L18)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

modfication > modification
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1584#-NkvOzgL8J1hg-Ao9Spg:-NkvVYPT3BGaSPoEW5Wp:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e568590077388826efbab95f0f2cc7c8f31a04f5/packages/geoview-core/src/api/event-processors/event-processor-children/ui-event-processor.ts#L17)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

storte > store
</blockquote></details>

Done.

**Review by DamonU2 — APPROVED** [review]
> Reviewed 5 of 30 files at r1, 4 of 6 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1584)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 6 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1584)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @ychoquet)

**Review by jolevesq — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1584#-:-Nkvp9p5Eov5s0AQQKbb:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1584)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @ychoquet)

**Pull request merged**
