### PR TITLE
refactor(store): Use the new pattern for store

### LINKED ISSUE #1446: [REFACTOR] Store Map State (Footer Bar)
Refactor store map state with the new approach (interface, initializer, selector, attributes/actions).

- Regroup map events  from ol in the store
- Create initializer function to be called by ts files
- refactor ui components in footer bar, north arrow, mouse position and attribution with new logic.
     - Move logic outside of component

### PR DESCRIPTION
**Pull request by jolevesq**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1446 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://jolevesq.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1457)

### CODE REVIEW

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/api/eventProcessors/map-event-processor.ts` line 121 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1457#-NiGjX-O7rD3o1vetUvA:-NiGjTmb1jTGMMxjTG-T:b-2v2vh6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8890e798e03218e2a4b4df8addd84037cb8ae36c/packages/geoview-core/src/api/eventProcessors/map-event-processor.ts#L121)):*
> ```XML
>     map.on('singleclick', store.getState().mapState.onMapSingleClick);
>     map.getView().on('change:resolution', store.getState().mapState.onMapZoomEnd);
>     map.getView().on('change:rotation', store.getState().mapState.onMapRotation);
> ```

The `on` events are not in `mapState.actions`? .. maybe `mapState.events`?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/attribution/attribution.tsx` line 88 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1457#-NiGk1E23EQnhk8G_MJj:-NiGk1E23EQnhk8G_MJk:bnz664p) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8890e798e03218e2a4b4df8addd84037cb8ae36c/packages/geoview-core/src/core/components/attribution/attribution.tsx#L88)):*
> ```XML
> 
>   // get store values
>   const mapElement = useStore(getGeoViewStore(mapId), (state) => state.mapState.mapElement);
> ```

mapElement is still using useStore..

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/crosshair/crosshair.tsx` line 41 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1457#-NiGkEF11MQTppa0NJiI:-NiGkEF11MQTppa0NJiJ:bmf9765) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8890e798e03218e2a4b4df8addd84037cb8ae36c/packages/geoview-core/src/core/components/crosshair/crosshair.tsx#L41)):*
> ```XML
>   const projection = useStore(store, (state) => state.mapState.currentProjection);
>   const mapCoord = useStore(store, (state) => state.mapState.centerCoordinates);
>   const mapElement = useStore(store, (state) => state.mapState.mapElement);
> ```

Still have to migrate these three?

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1457)* status: all files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @jolevesq, @kaminderpal, and @ychoquet)

___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-fixnorth-switch.tsx` line 25 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1457#-NiGu_6yBbXdp-yB71nZ:-NiGu_6yBbXdp-yB71n_:b-lh8x6q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8890e798e03218e2a4b4df8addd84037cb8ae36c/packages/geoview-core/src/core/components/footer-bar/footer-bar-fixnorth-switch.tsx#L25)):*
> ```XML
> 
>   // get the expand or collapse from store
>   // const expanded = useStore(getGeoViewStore(mapId), (state) => state.footerBarState.expanded);
> ```

Need to keep comment in?
___
*[`packages/geoview-core/src/core/components/north-arrow/north-arrow.tsx` line 20 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1457#-NiGvlxuCPuXM7KxNnM4:-NiGvlxuCPuXM7KxNnM5:b-bez8xq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8890e798e03218e2a4b4df8addd84037cb8ae36c/packages/geoview-core/src/core/components/north-arrow/north-arrow.tsx#L20)):*
> ```XML
> 
> // // The north pole position use for north arrow marker and get north arrow rotation angle
> // // north value (set longitude to be half of Canada extent (142° W, 52° W)) - projection central meridian is -95
> ```

Double commented out

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1457)* status: 18 of 35 files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @kaminderpal, and @ychoquet)

___
*[`packages/geoview-core/src/core/components/attribution/attribution.tsx` line 88 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1457#-NiGk1E23EQnhk8G_MJj:-NiHFet_EEDTwX-2xMBz:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8890e798e03218e2a4b4df8addd84037cb8ae36c/packages/geoview-core/src/core/components/attribution/attribution.tsx#L88)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

mapElement is still using useStore..
</blockquote></details>

Done
___
*[`packages/geoview-core/src/core/components/crosshair/crosshair.tsx` line 41 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1457#-NiGkEF11MQTppa0NJiI:-NiHGIG6Be8-yLlVF1-W:b-st1ann) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8890e798e03218e2a4b4df8addd84037cb8ae36c/packages/geoview-core/src/core/components/crosshair/crosshair.tsx#L41)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Still have to migrate these three?
</blockquote></details>

Done but still needs refactoring
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-fixnorth-switch.tsx` line 25 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1457#-NiGu_6yBbXdp-yB71nZ:-NiHGq5Y05eCuDi3Te6t:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8890e798e03218e2a4b4df8addd84037cb8ae36c/packages/geoview-core/src/core/components/footer-bar/footer-bar-fixnorth-switch.tsx#L25)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Need to keep comment in?
</blockquote></details>

Done
___
*[`packages/geoview-core/src/core/components/north-arrow/north-arrow.tsx` line 20 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1457#-NiGvlxuCPuXM7KxNnM4:-NiHH-LF1JaaJSr_Tzfo:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8890e798e03218e2a4b4df8addd84037cb8ae36c/packages/geoview-core/src/core/components/north-arrow/north-arrow.tsx#L20)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Double commented out
</blockquote></details>

Done
___
*[`packages/geoview-core/src/api/eventProcessors/map-event-processor.ts` line 121 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1457#-NiGjX-O7rD3o1vetUvA:-NiHDtO20Rb3AOsrBR2f:bddbxe) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8890e798e03218e2a4b4df8addd84037cb8ae36c/packages/geoview-core/src/api/eventProcessors/map-event-processor.ts#L121)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

The `on` events are not in `mapState.actions`? .. maybe `mapState.events`?
</blockquote></details>

No because it is not an action to call. We can put them in a new categories events for naming convention

**Review by DamonU2 — APPROVED** [review]
> Reviewed 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1457)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @kaminderpal, and @ychoquet)

**Pull request closed without merging**
