### PR TITLE
Fix position of hover tooltip + Layer fixes

### LINKED ISSUE #2156: [BUG] Fixes in layers panel
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

image
bad alignment in layers panel layer list

image
Typo size too small for attribution left panel

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### LINKED ISSUE #2158: [BUG] Fix Position Of Tooltip On Map Edges
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- [ ] The hover tooltip does not detect the top/right edges of the map. When you hover over a point at the top or far right of the map - the HoverTooltip is not fully visible.
image

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### LINKED ISSUE #2160: [BUG] Animate notifications bell when a new notification is added.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a new notification is added - nothing changes.

### Expected Behavior

We need to animate the bell when a new notification added.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

This PR fixes the issues with the hover tooltip. Add animation to notification bell.

Fixes #2156 
Fixes #2158 
Fixes #2160 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://cphelefu.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159)

### CODE REVIEW

**Review by kaminderpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159#-NyWEsqV9dcr_yL18dO0:-NyWEsqV9dcr_yL18dO1:b2jwdlu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/33919b54168677e66dcbd904699528ce3122728b/packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx#L37)):*
> ```XML
>   const hoverFeatureInfo = useMapHoverFeatureInfo();
>   const pointerPosition = useMapPointerPosition();
>   const mapElem = document.getElementById(`mapTargetElement-${mapId}`) as HTMLElement;
> ```

We need to use store hook `useAppGeoviewHTMLElement()` instead of document.getElementId
___
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 40 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159#-NyWG8Me8Q76k0r9zmZW:-NyWG8Me8Q76k0r9zmZX:b-9mbfuv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/33919b54168677e66dcbd904699528ce3122728b/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L40)):*
> ```XML
> import { ArrowDownwardIcon, ArrowUpIcon, TableViewIcon } from '@/ui/icons';
> import { Divider } from '@/ui/divider/divider';
> import { Typography } from '@/ui/typography/typography';
> ```

this can be written as `import { Typography } from '@/ui';`
___
*[`packages/geoview-core/src/core/components/notifications/notifications.tsx` line 65 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159#-NyWGJ7H04zPj9f2mQ3s:-NyWGJ7H04zPj9f2mQ3t:bfhzfta) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/33919b54168677e66dcbd904699528ce3122728b/packages/geoview-core/src/core/components/notifications/notifications.tsx#L65)):*
> ```XML
>   const { removeNotification } = useAppStoreActions();
> 
>   useEffect(() => {
> ```

can u please add log like `logger.logTraceUseEffect('Export Modal - mount');`
___
*[`packages/geoview-core/src/core/components/notifications/notifications.tsx` line 74 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159#-NyWG_0t92RxBlIKe7WG:-NyWG_0t92RxBlIKe7WH:bfhzfta) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/33919b54168677e66dcbd904699528ce3122728b/packages/geoview-core/src/core/components/notifications/notifications.tsx#L74)):*
> ```XML
> 
>   useEffect(() => {
>     if (hasNewNotification) {
> ```

can u please add log like `logger.logTraceUseEffect('Export Modal - mount');`
___
*[`packages/geoview-core/src/core/components/notifications/notifications.tsx` line 156 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159#-NyWGdQg5gcdu_vfEBHY:-NyWGdQg5gcdu_vfEBHZ:b-t07t04) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/33919b54168677e66dcbd904699528ce3122728b/packages/geoview-core/src/core/components/notifications/notifications.tsx#L156)):*
> ```XML
>           >
>             {!hasNewNotification && (
>               <div>
> ```

Can u please replace div with `Box`

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159#-NyWEsqV9dcr_yL18dO0:-NyWTKrOBz_p2BwT4MAC:bmgzzdz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daa24aa5236392cb61356060a319e1c442f37c03/packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx#L37)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

We need to use store hook `useAppGeoviewHTMLElement()` instead of document.getElementId
</blockquote></details>

This returns a different element. I basically used what is used across other components for getting map element

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @jolevesq and @kaminderpal)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 40 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159#-NyWG8Me8Q76k0r9zmZW:-NyWTVZn8DEDiQw-Gr5C:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daa24aa5236392cb61356060a319e1c442f37c03/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L40)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

this can be written as `import { Typography } from '@/ui';`
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/notifications/notifications.tsx` line 65 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159#-NyWGJ7H04zPj9f2mQ3s:-NyWTWfd5DSz2u65AzLy:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daa24aa5236392cb61356060a319e1c442f37c03/packages/geoview-core/src/core/components/notifications/notifications.tsx#L65)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

can u please add log like `logger.logTraceUseEffect('Export Modal - mount');`
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/notifications/notifications.tsx` line 74 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159#-NyWG_0t92RxBlIKe7WG:-NyWTXHj9sJmQ7Y-2H9T:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daa24aa5236392cb61356060a319e1c442f37c03/packages/geoview-core/src/core/components/notifications/notifications.tsx#L74)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

can u please add log like `logger.logTraceUseEffect('Export Modal - mount');`
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/notifications/notifications.tsx` line 156 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159#-NyWGdQg5gcdu_vfEBHY:-NyWTXw60j2odiR4PXM4:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daa24aa5236392cb61356060a319e1c442f37c03/packages/geoview-core/src/core/components/notifications/notifications.tsx#L156)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

Can u please replace div with `Box`
</blockquote></details>

Done.

**Review by kaminderpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159#-NyWEsqV9dcr_yL18dO0:-NyWYCMa9awOfgFuaFUO:b-o5mzf0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daa24aa5236392cb61356060a319e1c442f37c03/packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx#L37)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

This returns a different element. I basically used what is used across other components for getting map element
</blockquote></details>

u can do like this `useAppGeoviewHTMLElement().querySelector('\[id^="`mapTargetElement-${mapId}`-"\]')

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @jolevesq and @kaminderpal)

___
*[`packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159#-NyWEsqV9dcr_yL18dO0:-NyWqR5X7O2_mWLPc-tw:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/daa24aa5236392cb61356060a319e1c442f37c03/packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx#L37)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

u can do like this `useAppGeoviewHTMLElement().querySelector('\[id^="`mapTargetElement-${mapId}`-"\]')
</blockquote></details>

Done.

**Review by kaminderpal — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159#-:-NyWrV2h6WmYNrNo78U4:bnfp4nl)* status: 0 of 5 files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 2 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2159)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
