### PR TITLE
feat(icon-stack): Icon stack component to display a group of icons

### LINKED ISSUE #1305: [FEATURE] Implement the group icon (stack of icons) component
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

_No response_

### User Story

Currently, in legend tab we show a group of icons on the left hand side of layer list (screenshot below). 
We need to have a stand alone component for this feature, so we can also display the group of icons in Details tab in layer list.

Review the existing functionality and try to have it as a separate component, might need some cleaning or optimization.

image

### Implementation UI

_No response_

### LINKED ISSUE #1404: [BUG] Swiper is over footer-bar
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The swiper is set in the div containing the footer-bar, instead of just the map, this leads to an offset of the layers shown/hidden.

### Expected Behavior

Swiper should be in the map div and properly divide layers

### Steps To Reproduce

Go to https://canadian-geospatial-platform.github.io/geoview/public/package-swiper.html and look at the first map

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by amir-azma**
# Description

We need to have a stand alone component, so we can also display the group of icons for each layer. It can be used in Details, Layers, and Data Table tabs in footer.
Fixes #1305 
Fixes #1404

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://amir-azma.github.io/geoview/raw-feature-info-1.html
https://amir-azma.github.io/geoview/package-swiper.html
https://amir-azma.github.io/geoview/package-time-slider.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1491)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1491)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @amir-azma)

___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 130 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1491#-NjD68ve5ZYFbwbYgozm:-NjD68ve5ZYFbwbYgozn:be4igc3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fb6fc213fdf0e77a5734ad827ad080dc5f01bd1f/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L130)):*
> ```XML
>                   >
>                     <ListItemIcon>
>                       <IconStack layerPath={layerKey} />
> ```

Add to time slider panel as well
___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 545 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1491#-NjD6-cY3hx-ETNJRTsU:-NjD6-cZ0bPbXsBSz1Bh:b-c471q2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fb6fc213fdf0e77a5734ad827ad080dc5f01bd1f/packages/geoview-core/src/core/components/legend/legend-item.tsx#L545)):*
> ```XML
>             )}
>             {!isLegendOpen && (
>               <IconStack layerPath="esriFeatureLYR4/8" onIconClick={handleLegendClick} onStackIconClick={(e) => handleStackIcon(e)} />
> ```

Why layer path is hardcoded?

**Review by ychoquet — APPROVED** [review]
> Reviewed 1 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1491)* status: all files reviewed, 2 unresolved discussions (waiting on @amir-azma)

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1491)* status: 3 of 13 files reviewed, 2 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 130 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1491#-NjD68ve5ZYFbwbYgozm:-NjF2dtM-r2Ku4E-MuPH:bu5fina) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fb6fc213fdf0e77a5734ad827ad080dc5f01bd1f/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L130)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add to time slider panel as well
</blockquote></details>

I fixed the time slider regarding to Icon Stack
___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 545 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1491#-NjD6-cY3hx-ETNJRTsU:-NjF1npj9mXL3qD-VX7g:b-xlwhlm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fb6fc213fdf0e77a5734ad827ad080dc5f01bd1f/packages/geoview-core/src/core/components/legend/legend-item.tsx#L545)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why layer path is hardcoded?
</blockquote></details>

That's in the old legend that we will remove it soon, it's just for demo purpose.

**Review by jolevesq — APPROVED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1491)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amir-azma)

**Pull request merged**
