### PR TITLE
refactor(layerOrder): move layerOrder to store

### LINKED ISSUE #805: Export not working with XYZ source
CORS issues are not allowing maps with XYZ layers to be exported - cross origin causes canvas to be tainted, which disallows use of `toDataURL()`

### LINKED ISSUE #1552: [BUG] Details panel will have to be able to work with undefined geometry
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is an issue in details tab left panel layers, in seems some layers have undefined geometry that causes issue when we click on layer name on left panel.

Please visit this page review the issue: https://canadian-geospatial-platform.github.io/geoview/public/package-time-slider.html

image

### Expected Behavior

We should handle the case when a selected layer has undefined geometry.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### LINKED ISSUE #1581: [Refactor] move layerOrder to map state store
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Geoview team

### User Story

As a developer, I would like to have easy access to the order of layers on the map.

### Implementation UI

_No response_

### LINKED ISSUE #1582: [FEATURE] Add visible layer array to map state store
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Geoview team

### User Story

As a developer, I would like access to a list of the currently visible layers on the map

### Implementation UI

_No response_

### LINKED ISSUE #1583: [FEATURE] Feature info layer set should be in the same order as store legend item in layer-state
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

_No response_

### User Story

We should have feature info layer set to be in the same order as store legend item in layer-state

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #805
Closes #1581
Closes #1582 
Closes #1583
Closes #1552
Fixes some of the items in #1526

# Description

- adds layerOrder and visibleLayers (in order) to map state store
- links these to legend, details, data-table, and time-slider
- updates them according to changes to legendLayers - movement, visibility changes, and add/remove
- adds new XYZ tile source, replacing missing source
- fixes issue with XYZ tile layer export
- fixes error when trying to select WMS feature
- adds extent box around highlighted features
- restores layer visibility if layer deletion is cancelled
There are issues anywhere there is a group layer at the base level, as the indexes for the sublayers and root layers get mixed up.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Removed GeoJSON layer from raw-feature-info.html to test layer movement, others tested through types of layers and other pages

https://damonu2.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1617)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 14 of 21 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1617)* status: all files reviewed, 3 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 150 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1617#-NlyMW0-B7D4f1OPyhm6:-NlyMW00-nP74DheLExS:b2771sd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/47ce81af910fed0ee9f99965279285fbf334c535/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L150)):*
> ```XML
> 
>     api.event.once(
>       api.eventNames.MAP.EVENT_MAP_LOADED,
> ```

Do use the event.  add your logic inside the setMapLoaded event... will be cleaner
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 358 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1617#-NlyNAwt6bUWjG7Epl5_:-NlyNAwt6bUWjG7Epl5a:bvjqku1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/47ce81af910fed0ee9f99965279285fbf334c535/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L358)):*
> ```XML
>   }
> 
>   static getLayerPathsFromLegendsArray(legendsArray: TypeLegendLayer[]): string[] {
> ```

Should it be a geoUtilities function... will it be reuse somewhere else?
___
*[`packages/geoview-core/src/core/components/layers/left-panel/left-panel.tsx` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1617#-NlyOEYh8KAEburY6Ofv:-NlyOEYh8KAEburY6Ofw:bil4l14) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8f05e185e4ab6dedeada0639b4911a4c86da2843/packages/geoview-core/src/core/components/layers/left-panel/left-panel.tsx#L2)):*
> ```XML
> import { Dispatch, SetStateAction, useEffect } from 'react';
> import { useLayerStoreActions, useLayersList, useSelectedLayer } from '@/core/stores/store-interface-and-intial-values/layer-state';
> ```

We should keep the end point of the import, it helped to know what is from where

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1617)* status: all files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 150 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1617#-NlyMW0-B7D4f1OPyhm6:-NlyyR_b9Nans6Y9fZqO:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/47ce81af910fed0ee9f99965279285fbf334c535/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L150)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do use the event.  add your logic inside the setMapLoaded event... will be cleaner
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 358 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1617#-NlyNAwt6bUWjG7Epl5_:-NlyyTBe7vEFQ9Deqxyv:b6wd7ik) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/47ce81af910fed0ee9f99965279285fbf334c535/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L358)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should it be a geoUtilities function... will it be reuse somewhere else?
</blockquote></details>

I don't think it will be reused - the orderedLayers and visibleLayers are available in the store, and that's all it would be needed for.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/left-panel.tsx` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1617#-NlyOEYh8KAEburY6Ofv:-Nlyyzdo6mTIj30ZN60P:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8f05e185e4ab6dedeada0639b4911a4c86da2843/packages/geoview-core/src/core/components/layers/left-panel/left-panel.tsx#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should keep the end point of the import, it helped to know what is from where
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 5 of 6 files at r3, 6 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1617)* status: 26 of 27 files reviewed, all discussions resolved

**Review by jolevesq — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r4, 11 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1617#-:-Nm2sadT5e3Go3Jk484O:bnfp4nl)* status: 29 of 30 files reviewed, all discussions resolved (waiting on @DamonU2)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1617)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
