### PR TITLE
refactor(attribution): Remove OL control and replace by store info

### LINKED ISSUE #1531: [FEATURE] Store for attribution
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

As a developer, I would like to use the store for attribution and not rely on OL attribution control.

### Implementation UI

We should populate attribution information when a layer is loaded and set it to layers store array. Then attribution component can remove the OL control and rely on the store.

We should add the layer attribution inside the layers panel and only keep basemap attribution in footerbar

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1531

# Description

Remove OL attribution control and use store for attribution. Split map and layer attribution. Map is in the footer bar pop over and layer are in their respective layer right panel.

Fixes #1531

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://jolevesq.github.io/geoview/raw-feature-info-1.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1543)

### CODE REVIEW

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1543)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/attribution/attribution.tsx` line 49 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1543#-NkLc13DAKnxfA-VYJdv:-NkLc13E0gDTCQNNLQgd:b-ev09fp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3da808f4afa13df86de0cea07c7f34b76f05f7be/packages/geoview-core/src/core/components/attribution/attribution.tsx#L49)):*
> ```XML
>         className={open ? 'active' : ''}
>         tooltipPlacement="top"
>         tooltip={t('mapctrl.attribution.tooltip')!}
> ```

You don't need to use t(.....)  , just pass like this  tooltip="mapctrl.attribution.tooltip"  , 
because IconButton component already takes care of the translation inside it

**Review by jolevesq — COMMENTED** [review]
> Reviewed 18 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1543)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @amir-azma)

___
*[`packages/geoview-core/src/core/components/attribution/attribution.tsx` line 49 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1543#-NkLc13DAKnxfA-VYJdv:-NkLdK0u9sgi72yttzYo:b-896fjx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3da808f4afa13df86de0cea07c7f34b76f05f7be/packages/geoview-core/src/core/components/attribution/attribution.tsx#L49)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

You don't need to use t(.....)  , just pass like this  tooltip="mapctrl.attribution.tooltip"  , 
because IconButton component already takes care of the translation inside it

</blockquote></details>

Done

**Review by amir-azma — APPROVED** [review]
> Reviewed 1 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1543)* status: 18 of 19 files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by amir-azma — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1543)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
