### PR TITLE
refactor to allow custom temporal dimension into time slider

### PR DESCRIPTION
**Pull request by mayurmarakana89**
# Description

Allows custom temporal dimension to existing layer path (single layer)

Fixes # ([1540](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1540))

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://mayurmarakana89.github.io/geoview/package-time-slider.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @kaminderpal, @mayurmarakana89, and @ychoquet)

___
*[`packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json` line 15 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-NqZ8K7K41ZlwyfdjjPL:-NqZ8K7LDKQuR0_Xw_xg:b-90d090) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e3c9ab991b3ace0b17add29df6fb5206c2b61b/packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json#L15)):*
> ```JSON
>       "locked": true,
>       "reversed": true,
>       "defaultValue": "",
> ```

Like you said at the scrum... we may not need this and use the one from the dimension
___
*[`packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json` line 18 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-NqZ7Unn72rTlQ2IjKLc:-NqZ7Unn72rTlQ2IjKLd:bh4xd4i) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e3c9ab991b3ace0b17add29df6fb5206c2b61b/packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json#L18)):*
> ```JSON
>       "temporalDimension": {
>         "field": "datetime",
>         "default": "1696-01-01T05:00:00Z",
> ```

Use array for default as it is dual handle [1950-01-01T05:00:00Z, 1970-01-01T05:00:00Z]
Set date from 1900-01-01T05:00:00Z to 2000-01-01T05:00:00Z and just put these 2 values
___
*[`packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json` line 63 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-NqZ7w_rBdu-j1aivBBr:-NqZ7w_rBdu-j1aivBBs:bgdxo8k) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e3c9ab991b3ace0b17add29df6fb5206c2b61b/packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json#L63)):*
> ```JSON
>           "2016-01-01T04:47:32Z"
>         ],
>         "nearestValues": "discrete",
> ```

Should maybe be absolute
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts` line 179 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-NqZ8b3l9Q8c9yZ_2lUj:-NqZ8b3l9Q8c9yZ_2lUk:b-90n4cm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e3c9ab991b3ace0b17add29df6fb5206c2b61b/packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts#L179)):*
> ```XML
>       },
>       // #endregion ACTIONS
>       setTemporalDimension(layerPath: string, temporalDimension: TemporalDimensionProps | null): void {
> ```

The temporal dimension is set on the layer itself

https://canadian-geospatial-platform.github.io/geoview/public/package-time-slider.html
cgpv.api.maps['mapWM1'].layer.registeredLayers['historical-flood/0'].geoviewLayerInstance.layerTemporalDimension['historical-flood/0']

**Review by mayurmarakana89 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @jolevesq, @kaminderpal, and @ychoquet)

___
*[`packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json` line 15 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-NqZ8K7K41ZlwyfdjjPL:-NqmGD2RASqrnf6c-yMe:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e3c9ab991b3ace0b17add29df6fb5206c2b61b/packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json#L15)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Like you said at the scrum... we may not need this and use the one from the dimension
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json` line 18 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-NqZ7Unn72rTlQ2IjKLc:-NqmGDot8P8yQK9nKnIF:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e3c9ab991b3ace0b17add29df6fb5206c2b61b/packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json#L18)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use array for default as it is dual handle [1950-01-01T05:00:00Z, 1970-01-01T05:00:00Z]
Set date from 1900-01-01T05:00:00Z to 2000-01-01T05:00:00Z and just put these 2 values
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json` line 63 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-NqZ7w_rBdu-j1aivBBr:-NqmGEgk7UzBcRu34Fs8:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e3c9ab991b3ace0b17add29df6fb5206c2b61b/packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json#L63)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should maybe be absolute
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts` line 179 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-NqZ8b3l9Q8c9yZ_2lUj:-NqmGFQRA5so6QD3gZz7:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e3c9ab991b3ace0b17add29df6fb5206c2b61b/packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts#L179)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The temporal dimension is set on the layer itself

https://canadian-geospatial-platform.github.io/geoview/public/package-time-slider.html
cgpv.api.maps['mapWM1'].layer.registeredLayers['historical-flood/0'].geoviewLayerInstance.layerTemporalDimension['historical-flood/0']
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @kaminderpal, @mayurmarakana89, and @ychoquet)

___
*[`packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json` line 21 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-Nqmblx97EPMgPwzMVLh:-Nqmblx97EPMgPwzMVLi:b7b3srf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e03e41b8f899981e1bb6dba8ce8715f0f63a759a/packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json#L21)):*
> ```JSON
>         "range": {
>           "type": "absolute",
>           "range": [
> ```

Just put [1900-01-01T05:00:00Z to 2000-01-01T05:00:00Z] for range

**Review by mayurmarakana89 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @jolevesq, @kaminderpal, and @ychoquet)

___
*[`packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json` line 21 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-Nqmblx97EPMgPwzMVLh:-Nr5HkiQDJJvNSSEp5sm:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e03e41b8f899981e1bb6dba8ce8715f0f63a759a/packages/geoview-core/public/configs/package-time-slider2-config-time-slider.json#L21)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Just put [1900-01-01T05:00:00Z to 2000-01-01T05:00:00Z] for range
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 2 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @kaminderpal, @mayurmarakana89, and @ychoquet)

___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts` line 11 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-Nr5Xl_77Kq3pLuSCw63:-Nr5Xl_77Kq3pLuSCw64:b-4a2144) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f98bbd16bb5b475d12f4c7522edad54d077b559/packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts#L11)):*
> ```XML
> };
> 
> // #region INTERFACES
> ```

Please, the start of region is few line above
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1503 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-Nr5Xt5n6cyaDb5BLsDA:-Nr5Xt5n6cyaDb5BLsDB:bte32uj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f98bbd16bb5b475d12f4c7522edad54d077b559/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1503)):*
> ```XML
> 
>   /** ***************************************************************************************************************************
>    * Change the layer phase property and emit an event to update existing layer sets.
> ```

This line is not the good definition for the function

**Review by mayurmarakana89 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @jolevesq, @kaminderpal, and @ychoquet)

___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts` line 11 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-Nr5Xl_77Kq3pLuSCw63:-Nr5xKDb5BoJlt71sq0p:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f98bbd16bb5b475d12f4c7522edad54d077b559/packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Please, the start of region is few line above
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1503 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-Nr5Xt5n6cyaDb5BLsDA:-Nr5xL7_3N8QcW69utRZ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f98bbd16bb5b475d12f4c7522edad54d077b559/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1503)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This line is not the good definition for the function
</blockquote></details>

Done.

**Comment by mayurmarakana89** [comment]
> > Reviewed 1 of 4 files at r2, 2 of 4 files at r4, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799)_ status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @kaminderpal, @mayurmarakana89, and @ychoquet)
> 
> _[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts` line 11 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-Nr5Xl_77Kq3pLuSCw63:-Nr5Xl_77Kq3pLuSCw64:b-4a2144) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f98bbd16bb5b475d12f4c7522edad54d077b559/packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts#L11)):_
> 
> > ```
> > };
> > 
> > // #region INTERFACES
> > ```
> 
> Please, the start of region is few line above
> 
> _[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1503 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-Nr5Xt5n6cyaDb5BLsDA:-Nr5Xt5n6cyaDb5BLsDB:bte32uj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f98bbd16bb5b475d12f4c7522edad54d077b559/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1503)):_
> 
> > ```
> >   /** ***************************************************************************************************************************
> >    * Change the layer phase property and emit an event to update existing layer sets.
> > ```
> 
> This line is not the good definition for the function

Done!

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @kaminderpal, @mayurmarakana89, and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1508 at r6](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-NrHRsbe8abnkw2g6t0b:-NrHRsbe8abnkw2g6t0c:b-lm0z0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9f727a4773b3bb2478ea367ae6ed20ac95050457/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1508)):*
> ```XML
>    * @param {TimeDimension} temporalDimension The value to assign to the layer temporal dimension property.
>    */
>   setTemporalDimension(layerPath: string, temporalDimension: TimeDimension, override: boolean): void {
> ```

Add your new param with description to JSDOC function descriptoin
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1510 at r6](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-NrHSR0G0g1WROVu0c2X:-NrHSR0G0g1WROVu0c2Y:brm8omk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9f727a4773b3bb2478ea367ae6ed20ac95050457/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1510)):*
> ```XML
>   setTemporalDimension(layerPath: string, temporalDimension: TimeDimension, override: boolean): void {
>     layerPath = layerPath || this.layerPathAssociatedToTheGeoviewLayer;
>     if (override) {
> ```

Shold not be the reverse... override would be when we pass custom dimension. Maybe use custom instead of overide for param anme

**Review by mayurmarakana89 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @jolevesq, @kaminderpal, and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1508 at r6](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-NrHRsbe8abnkw2g6t0b:-NrHUKVNAYX4Z_-7ogrg:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9f727a4773b3bb2478ea367ae6ed20ac95050457/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1508)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add your new param with description to JSDOC function descriptoin
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1510 at r6](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-NrHSR0G0g1WROVu0c2X:-NrHUKGaEegRcZSDASzH:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9f727a4773b3bb2478ea367ae6ed20ac95050457/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1510)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Shold not be the reverse... override would be when we pass custom dimension. Maybe use custom instead of overide for param anme
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @kaminderpal, @mayurmarakana89, and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1511 at r7](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799#-NrHUEt835WffdqMMxf8:-NrHUEt835WffdqMMxf9:b4zdcip) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd8401bca7ff1d7fca60f53af412e2b3ff4df62/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1511)):*
> ```XML
>   setTemporalDimension(layerPath: string, temporalDimension: TimeDimension, custom: boolean): void {
>     layerPath = layerPath || this.layerPathAssociatedToTheGeoviewLayer;
>     if (custom) {
> ```

Should you look for !custom? because the way it is, your code will ends up in the old code. Can you re build and host...

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1799)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan, @amir-azma, @cphelefu, @DamonU2, @kaminderpal, and @ychoquet)

**Pull request merged**
