### PR TITLE
refactor: removes localized string

### PR DESCRIPTION
**Pull request by DamonU2**
# Description

Removes localized strings from code. dataAccessPath will be removed in another PR

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://damonu2.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 30 of 149 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572)* status: 30 of 149 files reviewed, 4 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/public/configs/navigator/21-ogc-feature-api.json` line 16 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAZFb6j3iV3owFAvNwQ:-OAZFb6kAiOq7UYuPHsi:b-di9k74) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/public/configs/navigator/21-ogc-feature-api.json#L16)):*
> ```JSON
>       {
>         "geoviewLayerId": "ogcFeatureLYR1",
>         "geoviewLayerName": "Large Lakes",
> ```

Trailing whitespace... thought it would be remove by the build (with format)
___
*[`packages/geoview-core/public/configs/navigator/21-ogc-feature-api.json` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAZFlXUD5pICT54H2uX:-OAZFlXUD5pICT54H2uY:b-kr2j44) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/public/configs/navigator/21-ogc-feature-api.json#L17)):*
> ```JSON
>         "geoviewLayerId": "ogcFeatureLYR1",
>         "geoviewLayerName": "Large Lakes",
>         "metadataAccessPath": "https://b6ryuvakk5.execute-api.us-east-1.amazonaws.com/dev",
> ```

Trailing whitespace
___
*[`packages/geoview-core/public/configs/navigator/22-static-image.json` line 16 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAZFpjyAHEQG1V068T5:-OAZFpjyAHEQG1V068T6:bl45hz9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/public/configs/navigator/22-static-image.json#L16)):*
> ```JSON
>       {
>         "geoviewLayerId": "staticLYR10",
>         "geoviewLayerName": "Static Image",
> ```

Trailing whitespace...  Maybe do a search in json file for coma-space.
___
*[`packages/geoview-core/public/configs/navigator/22-static-image.json` line 23 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAZG2ftDKLy1gEF8Jjn:-OAZG2ftDKLy1gEF8Jjo:b-kr2j44) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/public/configs/navigator/22-static-image.json#L23)):*
> ```JSON
>             "layerName": "Static Image",
>             "source": {
>               "dataAccessPath": "https://datacube-prod-data-public.s3.ca-central-1.amazonaws.com/store/imagery/aerial/napl/napl-ring-of-fire/napl-ring-of-fire-1954-08-07-60k-thumbnail.png",
> ```

Trailing whitespace

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 149 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572)* status: 33 of 149 files reviewed, 6 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/public/configs/navigator/24-vector-tile.json` line 15 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAZGCaZ6uCJJxH3_t-p:-OAZGCaZ6uCJJxH3_t-q:b-kr2j44) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/public/configs/navigator/24-vector-tile.json#L15)):*
> ```JSON
>       {
>         "geoviewLayerId": "vectorTilesLYR1",
>         "geoviewLayerName": "new basemap",
> ```

Trailing whitespace
___
*[`packages/geoview-core/public/configs/navigator/24-vector-tile.json` line 23 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAZGDax23Q3FQdIsQko:-OAZGDax23Q3FQdIsQkp:b-kr2j44) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/public/configs/navigator/24-vector-tile.json#L23)):*
> ```JSON
>             "initialSettings": { "minZoom": 3, "maxZoom": 18 },
>             "source": {
>               "dataAccessPath": "https://tiles.arcgis.com/tiles/HsjBaDykC1mjhXz9/arcgis/rest/services/CBMT_CBCT_3978_V_OSM/VectorTileServer/tile/{z}/{y}/{x}.pbf"
> ```

Trailing whitespace

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 19 of 149 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572)* status: 52 of 149 files reviewed, 7 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/public/templates/default-config.html` line 263 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAZHvmv9PPLgRBICY0u:-OAZHvmv9PPLgRBICY0v:b-fg2l2u) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/public/templates/default-config.html#L263)):*
> ```HTML
>                 'listOfGeoviewLayerConfig': [{
>                   'geoviewLayerId': 'wmsLYR1',
>                   'geoviewLayerName': 'earthquakes',
> ```

Trailing white space in html too

**Review by jolevesq — COMMENTED** [review]
> Reviewed 16 of 149 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572)* status: 68 of 149 files reviewed, 7 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/public/templates/demos/demo-osdp-non-currated.html` line 158 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAZIgnFEpz3pJE9NWEQ:-OAZIgnFEpz3pJE9NWER:b-s6mpus) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6ec776906da7477e907864e248bd23426d9d4b7d/packages/geoview-core/public/templates/demos/demo-osdp-non-currated.html#L158)):*
> ```HTML
>               {
>                 'layerId': 'ECCC-CURATED-1-349208FB-DAA5-4A20-B08A-012F1ED32B3A_en',
>                 'layerName': { 
> ```

We add these trailing white spaace before.... nerver trapped

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 81 of 149 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572)* status: all files reviewed, 12 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/public/templates/layers/layerlib.js` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAZJUDW0LSCGp5UfudP:-OAZJUDX6u3jOt6mCxxs:bsxn4l5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6ec776906da7477e907864e248bd23426d9d4b7d/packages/geoview-core/public/templates/layers/layerlib.js#L5)):*
> ```JavaScript
> // cgpv is not define, it is part of window object, we escape the no-undef globally...
> // Many functions name needs the eslint escape no-unused-vars.
> // It is an utilities file for demo purpose. It is the reason why we keep it global...
> ```

No need for this anymore?
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 497 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAbUgbi7MiPTtLjQrkK:-OAbUgbi7MiPTtLjQrkL:bg1121j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/src/api/config/config-api.ts#L497)):*
> ```XML
>       geoviewLayerConfig = toJsonObject({
>         geoviewLayerId: generateId(),
>         geoviewLayerName: 'unknown',
> ```

Should we use translation here to have the fr value when French. We may be able to use our i18n thing
___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 69 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAbVpfZAQsqTZuhRJQu:-OAbVpfZAQsqTZuhRJQv:b49uto5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6ec776906da7477e907864e248bd23426d9d4b7d/packages/geoview-core/src/api/config/uuid-config-reader.ts#L69)):*
> ```XML
> 
>           if (layerType === CV_CONST_LAYER_TYPES.ESRI_DYNAMIC && !isFeature) {
>             const geoviewLayerConfig = toJsonObject({
> ```

Can you put a TODO here, this whole if/else can be reduce I think... there is a lot of duplication
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 467 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAbWcga07w9OZcWE_ZS:-OAbWcga07w9OZcWE_ZT:b-ak9r7e) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L467)):*
> ```XML
>     const convertUserConfigToInternalConfig = (listOfLayerEntryConfig: TypeJsonArray): TypeJsonArray => {
>       return listOfLayerEntryConfig.map((sublayer): TypeJsonObject => {
>         // We disable the eslint no-param-reassign because we want to keep the modifications made to the object passed as parameter.
> ```

Because we remove the eslint, we may want to remove the comment?
___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 11 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAbX_bh1KI9ezACKjaL:-OAbX_bh1KI9ezACKjaM:b9jc0uk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/src/core/utils/config/config-validation.ts#L11)):*
> ```XML
> 
> import { TypeDisplayLanguage } from '@config/types/map-schema-types';
> // import { layerEntryIsGroupLayer } from '@config/types/type-guards';
> ```

Can we remove the dead import?

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572)* status: 144 of 150 files reviewed, 12 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/configs/navigator/21-ogc-feature-api.json` line 16 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAZFb6j3iV3owFAvNwQ:-OAcJejU3_y7dPI82EJG:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/public/configs/navigator/21-ogc-feature-api.json#L16)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing whitespace... thought it would be remove by the build (with format)
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/configs/navigator/21-ogc-feature-api.json` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAZFlXUD5pICT54H2uX:-OAcJeycDQJ_Swl1aRn4:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/public/configs/navigator/21-ogc-feature-api.json#L17)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing whitespace
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/configs/navigator/22-static-image.json` line 16 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAZFpjyAHEQG1V068T5:-OAcJfWr5rrr2sd65Lhk:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/public/configs/navigator/22-static-image.json#L16)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing whitespace...  Maybe do a search in json file for coma-space.
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/configs/navigator/22-static-image.json` line 23 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAZG2ftDKLy1gEF8Jjn:-OAcJfry76VWfyk0ih2T:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/public/configs/navigator/22-static-image.json#L23)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing whitespace
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/configs/navigator/24-vector-tile.json` line 15 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAZGCaZ6uCJJxH3_t-p:-OAcJgQaDa70T2uXu5Ja:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/public/configs/navigator/24-vector-tile.json#L15)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing whitespace
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/configs/navigator/24-vector-tile.json` line 23 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAZGDax23Q3FQdIsQko:-OAcJgkL7_uGwyJNa6X5:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/public/configs/navigator/24-vector-tile.json#L23)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing whitespace
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/default-config.html` line 263 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAZHvmv9PPLgRBICY0u:-OAcJhHBAn9Bs-_Vm2tg:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/public/templates/default-config.html#L263)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white space in html too
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/layers/layerlib.js` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAZJUDW0LSCGp5UfudP:-OAcHQUxAXLd_m7RFO1i:b-58uja6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6ec776906da7477e907864e248bd23426d9d4b7d/packages/geoview-core/public/templates/layers/layerlib.js#L5)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

No need for this anymore?
</blockquote></details>

Maybe a new issue to go through and remove all uses? I don't want to make this any bigger
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 497 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAbUgbi7MiPTtLjQrkK:-OAcJjaR-yS0yailBxV7:bejfxpn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/src/api/config/config-api.ts#L497)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we use translation here to have the fr value when French. We may be able to use our i18n thing
</blockquote></details>

Keep it simple like this to avoid import for this one spot?
___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 69 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAbVpfZAQsqTZuhRJQu:-OAcK-1A24g4BAG4iJI1:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6ec776906da7477e907864e248bd23426d9d4b7d/packages/geoview-core/src/api/config/uuid-config-reader.ts#L69)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put a TODO here, this whole if/else can be reduce I think... there is a lot of duplication
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 467 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAbWcga07w9OZcWE_ZS:-OAcK-gA21Lt__WpiJWD:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L467)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Because we remove the eslint, we may want to remove the comment?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 11 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-OAbX_bh1KI9ezACKjaL:-OAcK0Hv-EzXRadgABbJ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc67ca43b59b1de3207327fecefb46488bebed37/packages/geoview-core/src/core/utils/config/config-validation.ts#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we remove the dead import?
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
:lgtm: 

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2572#-:-OAcRWqSB_IeThR_EGSi:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
