### PR TITLE
1128 run init for all maps

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Using the Type Of Layers template and the chrome devtools to trace and debug the code. A display field has been inserted beside the mao title to show the map layer's status.

URL of my deploy is : https://ychoquet.github.io/GeoView/type-of-layers.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 25 files at r1, 1 of 36 files at r3, 4 of 55 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179)* status: 6 of 59 files reviewed, 1 unresolved discussion (waiting on @amir-azma, @cphelefu, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/public/templates/layers/esri-dynamic.html` line 768 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaCk99K2-woOC2vr78M:-NaCk99K2-woOC2vr78N:b3w6jib) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/public/templates/layers/esri-dynamic.html#L768)):*
> ```HTML
>         if (geoviewLayers) {
>           const output = Object.keys(cgpv.api.maps?.LYR1?.layer?.geoviewLayers).reduce((outputValue, layerId) => {
>             const stateValue = cgpv.api.maps?.LYR1?.layer?.geoviewLayers[layerId].allLayerEntryConfigProcessed() ? 'Processed' : 'Not totaly processed';
> ```

Can we have processed / inProgress / error .... In one word to make string comparison easier?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 25 files at r1, 6 of 55 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179)* status: 14 of 59 files reviewed, 2 unresolved discussions (waiting on @amir-azma, @cphelefu, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/api/events/payloads/layer-set-payload.ts` line 142 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaCrTut78VSSlR1D8pQ:-NaCrTut78VSSlR1D8pR:bwamy8l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/src/api/events/payloads/layer-set-payload.ts#L142)):*
> ```XML
>    * @param {string | null} handlerName the handler Name
>    * @param {string} layerPath the layer path to add to the inventory
>    * @param {'add' | 'remove' | undefined} action the kind of layer registration (default: add)
> ```

Why do you have undefined? Should we enforce it to be add or remove?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 55 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179)* status: 16 of 59 files reviewed, 3 unresolved discussions (waiting on @amir-azma, @cphelefu, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx` line 89 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaCrs2k0jDYIKkdVLV3:-NaCrs2k0jDYIKkdVLV4:b-artzzx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx#L89)):*
> ```XML
> 
>           // eslint-disable-next-line no-restricted-syntax
>           for (const [, value] of Object.entries(resultSets)) {
> ```

Tooltip fopr Water Monitoring ESRI Dynamic is failing
geoview-renderer.ts:81 Uncaught (in promise) Error: Features must have a geometry type.
    at A (geoview-renderer.ts:81:28)
    at geoview-renderer.ts:574:28
    at new Promise (<anonymous>)
    at e.value (geoview-renderer.ts:573:28)
    at abstract-geoview-layers.ts:1202:34
    at new Promise (<anonymous>)
    at abstract-geoview-layers.ts:1199:13
    at Array.forEach (<anonymous>)
    at abstract-geoview-layers.ts:1197:18
    at new Promise (<anonymous>)

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179)* status: 16 of 59 files reviewed, 4 unresolved discussions (waiting on @amir-azma, @cphelefu, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/public/templates/layers/esri-feature.html` line 376 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaCsGpJBKtNuAMFD09z:-NaCsGpK7PdpCF1oDnpb:bwogfn9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/public/templates/layers/esri-feature.html#L376)):*
> ```HTML
>       );
> 
>       const LegendsLayerSet2 = cgpv.api.getLegendsLayerSet('LYR2');
> ```

LAyer with filter on alberta and Manitoba is failing
geoview-renderer.ts:1553 Uncaught Error: Invalid vector layer filter (Invalid Date (convertToUTC)).
    at e.value (geoview-renderer.ts:1553:13)
    at e.value (geoview-renderer.ts:968:16)
    at e.value (geoview-renderer.ts:549:57)
    at style (abstract-geoview-vector.ts:220:34)
    at L (VectorLayer.js:683:20)
    at m.prepareFrame (VectorLayer.js:705:7)
    at o.loader_ (VectorImageLayer.js:134:28)
    at o.load (ImageCanvas.js:80:12)
    at I.prepareFrame (VectorImageLayer.js:168:13)
    at k.render (Layer.js:370:23)

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179)* status: 16 of 59 files reviewed, 6 unresolved discussions (waiting on @cphelefu, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/public/templates/layers/esri-dynamic.html` line 780 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaCtd8b6DGd-g0RHvyr:-NaCtd8b6DGd-g0RHvys:b1hhr64) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/public/templates/layers/esri-dynamic.html#L780)):*
> ```HTML
>         if (geoviewLayers) {
>           const output = Object.keys(cgpv.api.maps?.LYR2?.layer?.geoviewLayers).reduce((outputValue, layerId) => {
>             const stateValue = cgpv.api.maps?.LYR2?.layer?.geoviewLayers[layerId].allLayerEntryConfigProcessed() ? 'Processed' : 'Not totaly processed';
> ```

Typo in totaly 
Do we need to use the translation for the texts "Processed" and "Not totally processed" ?

**Review by cphelefu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179)* status: 48 of 59 files reviewed, 13 unresolved discussions (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/public/templates/layers/vector-tiles.html` line 214 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaDNr4iDE845qJBDVNb:-NaDNr4j46vtdMlWyWa-:b-ym53td) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/public/templates/layers/vector-tiles.html#L214)):*
> ```HTML
>         if (geoviewLayers) {
>           const output = Object.keys(cgpv.api.maps?.LYR2?.layer?.geoviewLayers).reduce((outputValue, layerId) => {
>             const stateValue = cgpv.api.maps?.LYR2?.layer?.geoviewLayers[layerId].allLayerEntryConfigProcessed() ? 'Processed' : 'Not totaly processed';
> ```

May have to use translation as @amir-azma already pointed out. Also type in the word 'totally'.

**Review by cphelefu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179)* status: 48 of 59 files reviewed, 14 unresolved discussions (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/public/templates/layers/wms.html` line 660 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaDOS5y51dRlAdis0KC:-NaDOS5y51dRlAdis0KD:be02zoe) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/public/templates/layers/wms.html#L660)):*
> ```HTML
>                 const numberOfErrors = cgpv.api.maps?.LYR2?.layer?.geoviewLayers[layerId].countErrorStatus();
>                 let errorIndicator = '';
>                 if (numberOfErrors) errorIndicator = numberOfErrors === 1 ? ' (1 error)' : ` (${numberOfErrors} errors)`;
> ```

This code seems to be repeating, can we make it a reusable function (probably passing the layerId)?

**Review by jolevesq — COMMENTED** [review]
> Reviewed 5 of 55 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179)* status: 53 of 59 files reviewed, 14 unresolved discussions (waiting on @amir-azma, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/public/templates/layers/vector-tiles.html` line 214 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaDNr4iDE845qJBDVNb:-NaDOcmy2ghXW1_FLCkS:b-5813ua) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/public/templates/layers/vector-tiles.html#L214)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

May have to use translation as @amir-azma already pointed out. Also type in the word 'totally'.
</blockquote></details>

This is for demo purpose only on html page. So translation is not needed. But everything in our component folder needs.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 55 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179)* status: 55 of 59 files reviewed, 14 unresolved discussions (waiting on @amir-azma, @cphelefu, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/public/templates/layers/wms.html` line 660 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaDOS5y51dRlAdis0KC:-NaDOuHM6jddW4shybj9:bdphzxb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/public/templates/layers/wms.html#L660)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

This code seems to be repeating, can we make it a reusable function (probably passing the layerId)?
</blockquote></details>

This would be a good ides but it is only on demo html page. We should keep it this way for now.

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 18 of 55 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179)* status: all files reviewed, 14 unresolved discussions (waiting on @cphelefu and @ychoquet)

___
*[`packages/geoview-core/src/geo/utils/utilities.ts` line 59 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaDY6l99HeB4kTDIQU9:-NaDY6l99HeB4kTDIQUA:b-vwz555) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/src/geo/utils/utilities.ts#L59)):*
> ```XML
> 
>   /**
>    * Returns the WKT representation of a given geoemtry
> ```

*geometry

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179)* status: all files reviewed, 14 unresolved discussions (waiting on @cphelefu, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/public/templates/layers/esri-dynamic.html` line 768 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaCk99K2-woOC2vr78M:-NaDgkgL2CE2mbl9cS5B:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/public/templates/layers/esri-dynamic.html#L768)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we have processed / inProgress / error .... In one word to make string comparison easier?
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/layers/esri-dynamic.html` line 780 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaCtd8b6DGd-g0RHvyr:-NaDgtNn8NelKD-5fAwO:b-msca1v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/public/templates/layers/esri-dynamic.html#L780)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

Typo in totaly 
Do we need to use the translation for the texts "Processed" and "Not totally processed" ?
</blockquote></details>

replace with processed and inprogress as proposed by Johann.
___
*[`packages/geoview-core/public/templates/layers/esri-feature.html` line 376 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaCsGpJBKtNuAMFD09z:-NaDhCdA7VG-W1TFsGw4:b-1yoh7k) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/public/templates/layers/esri-feature.html#L376)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

LAyer with filter on alberta and Manitoba is failing
geoview-renderer.ts:1553 Uncaught Error: Invalid vector layer filter (Invalid Date (convertToUTC)).
    at e.value (geoview-renderer.ts:1553:13)
    at e.value (geoview-renderer.ts:968:16)
    at e.value (geoview-renderer.ts:549:57)
    at style (abstract-geoview-vector.ts:220:34)
    at L (VectorLayer.js:683:20)
    at m.prepareFrame (VectorLayer.js:705:7)
    at o.loader_ (VectorImageLayer.js:134:28)
    at o.load (ImageCanvas.js:80:12)
    at I.prepareFrame (VectorImageLayer.js:168:13)
    at k.render (Layer.js:370:23)
</blockquote></details>

Wrong deployment, I made a new rush host.
___
*[`packages/geoview-core/public/templates/layers/geocore.html` line 200 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaCsozU3RwLbHyxkfyu:-NaDb0rz1NhjBbkT1_w7:b42h0gb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/public/templates/layers/geocore.html#L200)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

White spaces

Page loads but not able to expand section at the bottom, no tooltip
</blockquote></details>

Wrong deplyment, I redone the rush host.
___
*[`packages/geoview-core/public/templates/layers/vector-tiles.html` line 214 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaDNr4iDE845qJBDVNb:-NaDacB7DB30M7X7KPcm:b-pbdsks) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/public/templates/layers/vector-tiles.html#L214)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This is for demo purpose only on html page. So translation is not needed. But everything in our component folder needs.
</blockquote></details>

Agree!.
___
*[`packages/geoview-core/public/templates/layers/wms.html` line 660 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaDOS5y51dRlAdis0KC:-NaDaq671uIGyDQa6aYu:bqog7yy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/public/templates/layers/wms.html#L660)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This would be a good ides but it is only on demo html page. We should keep it this way for now.
</blockquote></details>

Agree!
___
*[`packages/geoview-core/src/api/events/payloads/layer-set-payload.ts` line 142 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaCrTut78VSSlR1D8pQ:-NaDbsBg63UXxM1I6cOv:bukijyn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/src/api/events/payloads/layer-set-payload.ts#L142)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why do you have undefined? Should we enforce it to be add or remove?
</blockquote></details>

Correction made!
___
*[`packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx` line 89 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaCrs2k0jDYIKkdVLV3:-NaDcGZw54GLdfZHqkUa:b42h0gb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx#L89)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Tooltip fopr Water Monitoring ESRI Dynamic is failing
geoview-renderer.ts:81 Uncaught (in promise) Error: Features must have a geometry type.
    at A (geoview-renderer.ts:81:28)
    at geoview-renderer.ts:574:28
    at new Promise (<anonymous>)
    at e.value (geoview-renderer.ts:573:28)
    at abstract-geoview-layers.ts:1202:34
    at new Promise (<anonymous>)
    at abstract-geoview-layers.ts:1199:13
    at Array.forEach (<anonymous>)
    at abstract-geoview-layers.ts:1197:18
    at new Promise (<anonymous>)
</blockquote></details>

Wrong deplyment, I redone the rush host.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 8 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaD3KGbBUVYcbDNqkD_:-NaDdQ1hAWDDoK8lyjRB:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L8)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use @/core
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 17 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaD3OOaCSgX8Fp8scRF:-NaDhb_f9dy9-wNPOP2b:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L17)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use @/core
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 25 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaD3P8b8ZrF0MwvtnmM:-NaDdUfG1q5gTuMHeG6Y:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L25)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use @/api
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts` line 130 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaD4Z2z8F3AKcganM9U:-NaDdqdN-xaldbDhlPyG:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts#L130)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It is not image static, but geopackages
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/map/map.ts` line 160 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaD5CE307VqlFl6qYnY:-NaDfUPWDm2u0ljULjRf:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/src/geo/map/map.ts#L160)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Need to keep dataTable, it is the the new component
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 8 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaD5U4a0jBloXPsVTQX:-NaDffZQ2G60ecCYWu0c:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/src/geo/utils/layer-set.ts#L8)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use @/api
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/utils/utilities.ts` line 59 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1179#-NaDY6l99HeB4kTDIQU9:-NaDfxYUEt4ZZeHUutGd:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4cccf2c1ac9dbe3a7d3244995e81f143a5e3c991/packages/geoview-core/src/geo/utils/utilities.ts#L59)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

*geometry
</blockquote></details>

Done.

**Pull request merged**
