### PR TITLE
2373-Documentation rework about packages

### PR DESCRIPTION
**Pull request by guichoquette**
# Description

I added 2 new files that can be accessed form the original file (packages.md). the two new files are:
- packages-core.md: containing the doc on how to create a core package
- packages-JS.md: containing the old doc that was present in packages.md

I think I touched everything about the creation of a core package. If it is missing something you can tell me and i'll add it.

Fixes # (2373)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

I looked at the interface with crtl+shift+v.

[__Add the URL for your deploy!__](https://guichoquette.github.io/geoview/)

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394)

### CODE REVIEW

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394)* status: all files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @guichoquette, and @jolevesq)

___
*[`docs/app/packages-core.md` line 192 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394#-O2W-_Qs1efeglWHwh4P:-O2W-_Qs1efeglWHwh4Q:b-rxqfr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc5e9a5b6c17442d47b5acc4cc5be78b1326033b/docs/app/packages-core.md#L192)):*
> ```Markdown
> If you need a new Icon that does not extist in packages/geoview-core/src/ui/icons/index.ts, you can explore [predefined material UI icons](https://mui.com/material-ui/material-icons/) and chose one from those available. You must add a line in packages/geoview-core/src/ui/icons/index.ts as follow:
> ```
> CropOriginal as AoiIcon,CropOriginal as AoiIcon,
> ```

Duplication
___
*[`docs/app/packages-core.md` line 199 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394#-O2W-hQ12qHx3RZZFSng:-O2W-hQ12qHx3RZZFSnh:b-wzic63) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc5e9a5b6c17442d47b5acc4cc5be78b1326033b/docs/app/packages-core.md#L199)):*
> ```Markdown
> - After updating rush.json, run rush update to update the monorepo's dependencies and integrate the new package.
> - Use rush build to build the package along with the other packages in the monorepo.
> - To test the code will working on it you can always use the **rush serve** command.
> ```

End of file blank line
___
*[`docs/app/packages-JS.md` line 205 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394#-O2W0GqM3zLjLtoF0xOm:-O2W0GqM3zLjLtoF0xOn:b-673sua) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc5e9a5b6c17442d47b5acc4cc5be78b1326033b/docs/app/packages-JS.md#L205)):*
> ```Markdown
> ```
> 
> Available package ids `aoi-panel`, `basemap-panel`, `swiper`, `time-slider`, `geochart`
> ```

End line

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394)* status: all files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan and @guichoquette)

___
*[`docs/app/packages-core.md` line 52 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394#-O2W046e5iAdmwbLzAg_:-O2W046e5iAdmwbLzAga:bpfulud) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc5e9a5b6c17442d47b5acc4cc5be78b1326033b/docs/app/packages-core.md#L52)):*
> ```Markdown
> ## Modifying webpack.common.js
> 
> When working with a monorepo using Webpack, adding a new package requires updating the Webpack configuration to ensure the new package is properly bundled and its dependencies are managed. Here's an explanation of why you had to add that specific line to webpack.common.js:
> ```

Previous section there were no skip line... check other files and apply standard
___
*[`docs/app/packages-JS.md` line 29 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394#-O2W0zua9dO99gHRyYHS:-O2W0zua9dO99gHRyYHT:b-ckzp6g) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc5e9a5b6c17442d47b5acc4cc5be78b1326033b/docs/app/packages-JS.md#L29)):*
> ```Markdown
> (function () {
>   class Test {
>     translations = {
> ```

Add a piece for translation in core package index section

OR

Mention in core package index.ts  to read the other package section for translation, added hook, export package. 
___
*[`docs/app/packages-JS.md` line 205 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394#-O2W1V1-4ouHs0itk9cE:-O2W1V1-4ouHs0itk9cF:b-wc95dj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc5e9a5b6c17442d47b5acc4cc5be78b1326033b/docs/app/packages-JS.md#L205)):*
> ```Markdown
> ```
> 
> Available package ids `aoi-panel`, `basemap-panel`, `swiper`, `time-slider`, `geochart`
> ```

This should be in core package file

**Review by guichoquette — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`docs/app/packages-core.md` line 52 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394#-O2W046e5iAdmwbLzAg_:-O2_27K80dYNBLIsyNKu:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc5e9a5b6c17442d47b5acc4cc5be78b1326033b/docs/app/packages-core.md#L52)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Previous section there were no skip line... check other files and apply standard
</blockquote></details>

Done.
___
*[`docs/app/packages-core.md` line 192 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394#-O2W-_Qs1efeglWHwh4P:-O2_2LCm7IT56iPZpCAj:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc5e9a5b6c17442d47b5acc4cc5be78b1326033b/docs/app/packages-core.md#L192)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Duplication
</blockquote></details>

Done.
___
*[`docs/app/packages-core.md` line 199 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394#-O2W-hQ12qHx3RZZFSng:-O2Zxh--48oYQfhirPmL:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc5e9a5b6c17442d47b5acc4cc5be78b1326033b/docs/app/packages-core.md#L199)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

End of file blank line
</blockquote></details>

Done.
___
*[`docs/app/packages-JS.md` line 29 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394#-O2W0zua9dO99gHRyYHS:-O2_1aH-6g6S_3ueNMAh:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc5e9a5b6c17442d47b5acc4cc5be78b1326033b/docs/app/packages-JS.md#L29)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add a piece for translation in core package index section

OR

Mention in core package index.ts  to read the other package section for translation, added hook, export package.
</blockquote></details>

Done.
___
*[`docs/app/packages-JS.md` line 205 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394#-O2W0GqM3zLjLtoF0xOm:-O2ZxfeZ73WstkTVhcNN:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc5e9a5b6c17442d47b5acc4cc5be78b1326033b/docs/app/packages-JS.md#L205)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

End line
</blockquote></details>

Done.
___
*[`docs/app/packages-JS.md` line 205 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394#-O2W1V1-4ouHs0itk9cE:-O2ZzvmI4s6L5OS2NT6c:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc5e9a5b6c17442d47b5acc4cc5be78b1326033b/docs/app/packages-JS.md#L205)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This should be in core package file
</blockquote></details>

Done.

**Review by DamonU2 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394#-:-O2_EoyP4XBFxrGs0SBZ:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2394)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Pull request merged**
