### PR TITLE
Readme Doc for AOI

### PR DESCRIPTION
**Pull request by guichoquette**
# Description

I Updated the AOI Readme file and doc. 

Fixes # (2374)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

I looked at what was the output of the Readme file using ctrl+shift+V will in the Readme file.

[__Add the URL for your deploy!__](https://canadian-geospatial-platform.github.io/geoview/)

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @guichoquette)

___
*[`docs/app/packages.md` line 7 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387#-O26Fx-F8yXfWqqpVo6U:-O26Fx-F8yXfWqqpVo6V:bnsav09) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b3c1663314d6554cfa4c04d08175115498ef810/docs/app/packages.md#L7)):*
> ```Markdown
> The viewer allows loading packages to extend the viewer's functionalities.
> 
> The viewer also supports few core packages such as a area of interest, basemap panel, details panel, layers panel, overview map.
> ```

We can remove details-panel, overview map and layer-panel as they are not package anymore. You can add geoChart, swiper and time-slider
___
*[`docs/app/packages.md` line 214 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387#-O26GCvF9q5Mmk7Ly9Az:-O26GCvF9q5Mmk7Ly9B-:b-620zh5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b3c1663314d6554cfa4c04d08175115498ef810/docs/app/packages.md#L214)):*
> ```Markdown
> ```
> 
> Available package ids `basemap-panel`, `swiper`, `time-slider`, `geochart`
> ```

Add your aoi-panel here
___
*[`packages/geoview-aoi-panel/README.md` line 24 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387#-O26GkqKDXK4G4HCug1K:-O26GkqLB5Ee9_R5dQZe:b-km9ctp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b3c1663314d6554cfa4c04d08175115498ef810/packages/geoview-aoi-panel/README.md#L24)):*
> ```Markdown
> ### Configuration
> 
> The user can add its own configuration by creating a config file that will replace the default one used on the map. To do so the new config file must have the same file name as the config file used by the map and append the package name to it.
> ```

Can you add a snippet with both sample config file name

Add also a snippet were you set it in the appBar config section
___
*[`packages/geoview-aoi-panel/README.md` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387#-O26H8oG1CMQUJqzZUCv:-O26H8oH58hEm3XffuTb:bewwyvj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b3c1663314d6554cfa4c04d08175115498ef810/packages/geoview-aoi-panel/README.md#L60)):*
> ```Markdown
> ### Removing an Area of Interest
> 
> The curent only way to remove the **AOI** is by manualy deleting the entry in the file for the concerned AOI.
> ```

There an aoi call to remove the plugins see the sample with loadinh un loading package

**Review by guichoquette — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @guichoquette and @jolevesq)

___
*[`docs/app/packages.md` line 7 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387#-O26Fx-F8yXfWqqpVo6U:-O26KjId4T2Qd1ybDFZs:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b3c1663314d6554cfa4c04d08175115498ef810/docs/app/packages.md#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We can remove details-panel, overview map and layer-panel as they are not package anymore. You can add geoChart, swiper and time-slider
</blockquote></details>

Done.
___
*[`docs/app/packages.md` line 214 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387#-O26GCvF9q5Mmk7Ly9Az:-O26Ktk01iWm2COIsSh3:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b3c1663314d6554cfa4c04d08175115498ef810/docs/app/packages.md#L214)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add your aoi-panel here
</blockquote></details>

Done.
___
*[`packages/geoview-aoi-panel/README.md` line 24 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387#-O26GkqKDXK4G4HCug1K:-O26OmZlE86_nA1nhrxQ:bs7wumb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b3c1663314d6554cfa4c04d08175115498ef810/packages/geoview-aoi-panel/README.md#L24)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add a snippet with both sample config file name

Add also a snippet were you set it in the appBar config section
</blockquote></details>

Done.
___
*[`packages/geoview-aoi-panel/README.md` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387#-O26H8oG1CMQUJqzZUCv:-O26OmEe9aBXLbSg_uCU:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3b3c1663314d6554cfa4c04d08175115498ef810/packages/geoview-aoi-panel/README.md#L60)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There an aoi call to remove the plugins see the sample with loadinh un loading package
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @guichoquette)

___
*[`packages/geoview-aoi-panel/README.md` line 46 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387#-O29vaQs8WSxKnszyHpA:-O29vaQs8WSxKnszyHpB:b-qpli71) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e0b1031afd2ece37634ca90108294e7e11b8efe7/packages/geoview-aoi-panel/README.md#L46)):*
> ```Markdown
>   "appBar": {
>     "tabs": {
>       "core": ["aoi-panel"]
> ```

 put a comment // This is were Geoview knows it needs to load the package
___
*[`packages/geoview-aoi-panel/README.md` line 52 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387#-O29vA4A8W1jVB2TPy0c:-O29vA4A8W1jVB2TPy0d:bbcz2dh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e0b1031afd2ece37634ca90108294e7e11b8efe7/packages/geoview-aoi-panel/README.md#L52)):*
> ```Markdown
> ```
> 
> The file containing the AOI must be named **myMap-aoi-panel.json** as described in the following section.
> ```

must be name <config-file-name>-<package-name>, i.e. "myMap-aoi-panel.json. 

If we sayjust must people may think the whole must this.
___
*[`packages/geoview-aoi-panel/README.md` line 91 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387#-O29w1QK0CYxxA-scth-:-O29w1QK0CYxxA-scth0:bqhzpp1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e0b1031afd2ece37634ca90108294e7e11b8efe7/packages/geoview-aoi-panel/README.md#L91)):*
> ```Markdown
> 
> ```
> cgpv.api.plugin.removePlugin('aoi-panel', 'myMap');
> ```

Were myMap is the mapId.... I think the parameter is the map id

**Review by guichoquette — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @guichoquette and @jolevesq)

___
*[`packages/geoview-aoi-panel/README.md` line 46 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387#-O29vaQs8WSxKnszyHpA:-O2ABE0FExfilHATe5UY:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e0b1031afd2ece37634ca90108294e7e11b8efe7/packages/geoview-aoi-panel/README.md#L46)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

put a comment // This is were Geoview knows it needs to load the package
</blockquote></details>

Done.
___
*[`packages/geoview-aoi-panel/README.md` line 52 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387#-O29vA4A8W1jVB2TPy0c:-O2AEmtjCvbgqOJXCATg:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e0b1031afd2ece37634ca90108294e7e11b8efe7/packages/geoview-aoi-panel/README.md#L52)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

must be name <config-file-name>-<package-name>, i.e. "myMap-aoi-panel.json. 

If we sayjust must people may think the whole must this.
</blockquote></details>

Done.
___
*[`packages/geoview-aoi-panel/README.md` line 91 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387#-O29w1QK0CYxxA-scth-:-O2AElIV5epWZyCGNgR5:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e0b1031afd2ece37634ca90108294e7e11b8efe7/packages/geoview-aoi-panel/README.md#L91)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Were myMap is the mapId.... I think the parameter is the map id
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2387)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @guichoquette)

**Pull request merged**
