### PR TITLE
Synchronous version of the new schema

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

Modification of the new config API to accept the new structure of the schema.

Fixes # 2103

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using Chrome Devtools.

__Deploy URL__: https://ychoquet.github.io/GeoView/config-sandbox.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 8 of 13 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104)* status: 10 of 14 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/config-constants.ts` line 148 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxO9Arm20Ix0p6q1BIQ:-NxO9Arm20Ix0p6q1BIR:b94jcte) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6662e0eb1ec3fe73038681e693f2aedc2aab6576/packages/geoview-core/src/api/config/types/config-constants.ts#L148)):*
> ```XML
>       enableRotation: true,
>       rotation: 0,
>       minZoom: 0,
> ```

These 3 attributes are still on viewSettings with default values I think... Especially maxExtent
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 643 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxO9v2z6ttBPsIUWZ1o:-NxO9v2z6ttBPsIUWZ1p:bg2o4t9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d06a8aee16efe638d36d4848b293ea053f4d2ec/packages/geoview-core/src/api/config/types/config-validation-schema.json#L643)):*
> ```JSON
>           "description": "Maximum number of records to fetch (default: 0)."
>         },
>         "layerFilter": {
> ```

layerFilter should only be on vaector and esriDynamic... same for maxREcordCount. Seems riht in map-schema-type
___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 126 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOACu02j0P5sYjEDw4:-NxOACu1CfX0L_1nlJx0:bi27vtn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d06a8aee16efe638d36d4848b293ea053f4d2ec/packages/geoview-core/src/api/config/types/map-schema-types.ts#L126)):*
> ```XML
>   alias: string;
>   type: TypeOutfieldsType;
>   domaine: unknown[];
> ```

Typo domain
___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 239 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOASk7C5qJPctCtDhE:-NxOASk7C5qJPctCtDhF:byfmwce) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d06a8aee16efe638d36d4848b293ea053f4d2ec/packages/geoview-core/src/api/config/types/map-schema-types.ts#L239)):*
> ```XML
>  * Initial settings for WMS image sources.
>  */
> export interface TypeSourceImageEsriInitialConfig extends TypeBaseSourceImageInitialConfig {
> ```

maxRecord will have no effect on WMS... layer filter will work (my mistake for my comment in file upper)
___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 455 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOAf8M1ZMdQM36pF8l:-NxOAf8M1ZMdQM36pF8m:b-5mv7du) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6662e0eb1ec3fe73038681e693f2aedc2aab6576/packages/geoview-core/src/api/config/types/map-schema-types.ts#L455)):*
> ```XML
>    * Default [-125, 30, -60, 89].
>    */
>   maxExtent?: Extent;
> ```

There 2 attributes should stay in viewSetting as it is max extent and min/max zoom to constrain the view
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 298 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOAoa6EvDSdCUWDxEY:-NxOAoa6EvDSdCUWDxEZ:bbxgkzp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6662e0eb1ec3fe73038681e693f2aedc2aab6576/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L298)):*
> ```XML
>       : CV_DEFAULT_MAP_FEATURE_CONFIG.schemaVersionUsed!;
> 
>     const minZoom = this.map.viewSettings.minZoom!;
> ```

Same comment as above
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 356 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOAqxD3EdhmJv-eTgU:-NxOAqxD3EdhmJv-eTgV:b59evjy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6662e0eb1ec3fe73038681e693f2aedc2aab6576/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L356)):*
> ```XML
>    * @private
>    */
>   #validateMaxExtent(): void {
> ```

Same comment as above. If not maxExtent provided, we need the default one
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts` line 21 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOBHnaEePIxU4MjnjU:-NxOBHnaEePIxU4MjnjV:bbs4yks) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6662e0eb1ec3fe73038681e693f2aedc2aab6576/packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts#L21)):*
> ```XML
> export class EsriDynamicLayerEntryConfig extends AbstractBaseLayerEntryConfig {
>   /** Filter to apply on feature of this layer. */
>   layerFilter?: string;
> ```

If I understand correctly, this is now part of the source info

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 13 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104)* status: 12 of 14 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 3 of 13 files at r1, 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104)* status: all files reviewed, 9 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 59 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOHcke92nY1HFvKCT1:-NxOHcke92nY1HFvKCT2:b-74lsr5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cf829217d774cf6fcf4ee2df42eb4f9d0ef52ddc/packages/geoview-core/src/api/config/uuid-config-reader.ts#L59)):*
> ```XML
>           if (layerType === CV_CONST_LAYER_TYPES.ESRI_DYNAMIC && !isFeature) {
>             const geoviewLayerConfig: TypeJsonObject = {
>               geoviewLayerId: `${id}` as TypeJsonObject,
> ```

Here and in other places similar, to clarify, maybe best to create de json object without all the casting for each prop and do 1 single cast as TypeJsonObejct for the geoviewLayerConfig instead?
Example:



_Code snippet:_
```XML
const geoviewLayerConfig = {
  geoviewLayerId: `${id}`,
  geoviewLayerName: createLocalizedString(name as string),
  metadataAccessPath: createLocalizedString(url as string),
  geoviewLayerType: CV_CONST_LAYER_TYPES.ESRI_DYNAMIC,
} as unknown as TypeJsonObject;
```
___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 161 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOGO6F9fwWh6RbkmSI:-NxOGO6F9fwWh6RbkmSJ:b-lko5g0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cf829217d774cf6fcf4ee2df42eb4f9d0ef52ddc/packages/geoview-core/src/api/config/uuid-config-reader.ts#L161)):*
> ```XML
> 
>     // Return the parsed response
>     return this.getLayerConfigFromResponse(result, lang);
> ```

Here, I notice that it's not parsing the information related to the GeoChart anymore, that's intended?
GeoChart will not work on GeoCore layers if not.
It's not a change that happened in this current PR, but it's been removed at some point. It's still in the original configuration file.

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104)* status: all files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 161 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOGO6F9fwWh6RbkmSI:-NxOJ1HuBBkKLWif8o5h:bzido3m) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cf829217d774cf6fcf4ee2df42eb4f9d0ef52ddc/packages/geoview-core/src/api/config/uuid-config-reader.ts#L161)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Here, I notice that it's not parsing the information related to the GeoChart anymore, that's intended?
GeoChart will not work on GeoCore layers if not.
It's not a change that happened in this current PR, but it's been removed at some point. It's still in the original configuration file.
</blockquote></details>

I dontknow if it should stay here in the readr or be responsability of layersAPI to get metadata for the plugins... This reader has been added in last PR to be able to load layer by url. It will need some more thingking. The original is still accessible and wont be removed until it is working

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104)* status: all files reviewed, 9 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 59 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOHcke92nY1HFvKCT1:-NxOK9k36rorbnoPkAyu:bt76y2k) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cf829217d774cf6fcf4ee2df42eb4f9d0ef52ddc/packages/geoview-core/src/api/config/uuid-config-reader.ts#L59)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Here and in other places similar, to clarify, maybe best to create de json object without all the casting for each prop and do 1 single cast as TypeJsonObejct for the geoviewLayerConfig instead?
Example:
</blockquote></details>

Actually, even better if possible. Use the LayerEntryConfig typing instead of working with a TypeJsonObject which is basically an 'any' in disguise.

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104)* status: all files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 59 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOHcke92nY1HFvKCT1:-NxOs5JV3HaygTzQIPNz:bgh6d1t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cf829217d774cf6fcf4ee2df42eb4f9d0ef52ddc/packages/geoview-core/src/api/config/uuid-config-reader.ts#L59)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Actually, even better if possible. Use the LayerEntryConfig typing instead of working with a TypeJsonObject which is basically an 'any' in disguise.
</blockquote></details>

Done. I used the Cast<T>(value) which is essentially the same thing as  unknown as TypeJsonObject.
___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 161 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOGO6F9fwWh6RbkmSI:-NxPLgDD-jyRuqbVJcEW:b3w0afp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cf829217d774cf6fcf4ee2df42eb4f9d0ef52ddc/packages/geoview-core/src/api/config/uuid-config-reader.ts#L161)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I dontknow if it should stay here in the readr or be responsability of layersAPI to get metadata for the plugins... This reader has been added in last PR to be able to load layer by url. It will need some more thingking. The original is still accessible and wont be removed until it is working
</blockquote></details>

If it has to be restored, i'll do. However, I'm not sure it is part of the config.
___
*[`packages/geoview-core/src/api/config/types/config-constants.ts` line 148 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxO9Arm20Ix0p6q1BIQ:-NxOut4C0wjtOqfXiOKT:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6662e0eb1ec3fe73038681e693f2aedc2aab6576/packages/geoview-core/src/api/config/types/config-constants.ts#L148)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

These 3 attributes are still on viewSettings with default values I think... Especially maxExtent
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 643 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxO9v2z6ttBPsIUWZ1o:-NxOv2aU9X9kUME8RfNN:b-k2ijzy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d06a8aee16efe638d36d4848b293ea053f4d2ec/packages/geoview-core/src/api/config/types/config-validation-schema.json#L643)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

layerFilter should only be on vaector and esriDynamic... same for maxREcordCount. Seems riht in map-schema-type
</blockquote></details>

Done. This is the case.
___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 126 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOACu02j0P5sYjEDw4:-NxOw24w0rivd_qMuC3n:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d06a8aee16efe638d36d4848b293ea053f4d2ec/packages/geoview-core/src/api/config/types/map-schema-types.ts#L126)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo domain
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 239 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOASk7C5qJPctCtDhE:-NxOwBpv0IbFmCV5Zejr:bmhmxhp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8d06a8aee16efe638d36d4848b293ea053f4d2ec/packages/geoview-core/src/api/config/types/map-schema-types.ts#L239)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

maxRecord will have no effect on WMS... layer filter will work (my mistake for my comment in file upper)
</blockquote></details>

Done.  The error is in the header. This is the ESRI source definition.
___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 455 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOAf8M1ZMdQM36pF8l:-NxPJyC9ANjBATVUu_nx:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6662e0eb1ec3fe73038681e693f2aedc2aab6576/packages/geoview-core/src/api/config/types/map-schema-types.ts#L455)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There 2 attributes should stay in viewSetting as it is max extent and min/max zoom to constrain the view
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 298 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOAoa6EvDSdCUWDxEY:-NxPKg609DyT48IF4HHq:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6662e0eb1ec3fe73038681e693f2aedc2aab6576/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L298)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same comment as above
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 356 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOAqxD3EdhmJv-eTgU:-NxPL3JBC9ig8GctoHCH:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6662e0eb1ec3fe73038681e693f2aedc2aab6576/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L356)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same comment as above. If not maxExtent provided, we need the default one
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts` line 21 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOBHnaEePIxU4MjnjU:-NxPLOS20Krps5igWqWR:bb77ufg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6662e0eb1ec3fe73038681e693f2aedc2aab6576/packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts#L21)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If I understand correctly, this is now part of the source info
</blockquote></details>

Yes.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 7 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 161 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOGO6F9fwWh6RbkmSI:-NxPbA2w-CIcRhImBD5d:b-pnwpfh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cf829217d774cf6fcf4ee2df42eb4f9d0ef52ddc/packages/geoview-core/src/api/config/uuid-config-reader.ts#L161)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

If it has to be restored, i'll do. However, I'm not sure it is part of the config.
</blockquote></details>

It may be part of this uuid reader file like before. We will do in another PR

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104)* status: 5 of 15 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 161 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104#-NxOGO6F9fwWh6RbkmSI:-NxPfBjE1PmmDAmk2Ucv:b2nhlkw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cf829217d774cf6fcf4ee2df42eb4f9d0ef52ddc/packages/geoview-core/src/api/config/uuid-config-reader.ts#L161)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It may be part of this uuid reader file like before. We will do in another PR
</blockquote></details>

Ok!

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 8 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2104)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

**Pull request merged**
