### PR TITLE
fix(ui): font updates and upgrade legend to MUIv5

### LINKED ISSUE #556: Update Theme to MUI v5
MUI has been updated to v5 but some section of the theme are not working anymore like font familly...

Investigate all modification.

Sample for typo: https://github.com/mui/material-ui/issues/28633

### PR DESCRIPTION
**Pull request by dayc-mapdev**
closes #556 
Needs a new epic to remove makeStyles from the rest of the components

- - -
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/641)

### CODE REVIEW

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/641)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @dayc-mapdev)

___
*[`packages/geoview-core/src/core/components/legend/legend.tsx` line 27 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/641#-NGrYtrn2Nnk-gS2707s:-NGrYtro2m-Mi1tVAMuD:b-r849pn) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/b864d440aee0e73fbe48ab4c2e3c8541fa78a042/packages/geoview-core/src/core/components/legend/legend.tsx#L27)):*
> ```XML
>     return (
>       <div>
>         <List sx={sxStyles.legend}>
> ```

What sx stands for?

**Review by jolevesq — COMMENTED** [review]
https://canadian-geospatial-platform.github.io/geoview/556-mui5-upgrade/legend.html, map 2 is not working

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/641#-:-NGvOd0oAbSVaGSR8MMi:boav9o9)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/641)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/641)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Pull request merged**
