### PR TITLE
feat-91-sample-page-vector closes #91

### LINKED ISSUE #91: Vector sample page
Add all vector function (from previous single page sample) to a sample page.

### PR DESCRIPTION
**Pull request by melzeiny1980**
## Checklist

* [ ] Commit message follow the guidelines
* [ ] PR targets the correct release version
* [ ] Deploy has been done
* [ ] Check styling
* [ ] _Help files and documentation have been updated_
* [ ] ~Release notes have been updated~

## What's to look for styling
* Use camelCase for identifier names (variables and functions)
* Use PascalCase for type names
* Do not use "I" as a prefix for interface names
* Do not export types/functions unless you need to share it across multiple components
* All names start with a letter
* Always put spaces around operators ( = + - * / ), and after colon:
* Remove all trailing white spaces
* Look for bad indentation
* Carriage return are mandatory
  * Before comments
  * Before if condition
  * After if condition
  * Before properties
  * Before classes
  * Before functions

The use of Prettier Visual Studio Code extension let's you format automatically your code to remove most of the styling issues like white space and indentation.

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @melzeiny1980)

___
*[public/templates/vector.html, line 199 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVM2nT406tis2cEzPQv:-MVM2nT406tis2cEzPQw:b-7kmav9) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6e0437ea94002eac2a7f670811993e35e386722e/public/templates/vector.html#L199)):*
> ```HTML
> 
>                 // used to store the created polyline geometry
>                 var polyline = null;
> ```

Do you really need this?
___
*[public/templates/vector.html, line 202 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVM2GYY9S7GPapNcwev:-MVM2GYZ97b7meazQYEr:bcv8rlx) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6e0437ea94002eac2a7f670811993e35e386722e/public/templates/vector.html#L202)):*
> ```HTML
> 
>                 // check if a group already exists
>                 cgpv.api.map('mapWM').createGeometryGroup('myGroup');
> ```

Add this to the code snippet section
___
*[public/templates/vector.html, line 239 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVM2U6zBz7IgiKirrl8:-MVM2U6zBz7IgiKirrl9:b2pljml) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6e0437ea94002eac2a7f670811993e35e386722e/public/templates/vector.html#L239)):*
> ```HTML
>                 var deleteGeomtryGroup = document.getElementsByClassName('delete-group-btn')[0];
> 
>                 // add polyline btn click event handler
> ```

Not the good comment
___
*[public/templates/vector.html, line 240 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVM2W3t0SVs3WRqa-fB:-MVM2W3t0SVs3WRqa-fC:bcv8rlx) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6e0437ea94002eac2a7f670811993e35e386722e/public/templates/vector.html#L240)):*
> ```HTML
> 
>                 // add polyline btn click event handler
>                 deleteGeomtryGroup.addEventListener('click', function (e) {
> ```

Add this to the code snippet section
___
*[public/templates/vector.html, line 241 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVM2XmpAuKb0C6Q6-1U:-MVM2XmpAuKb0C6Q6-1V:b2pljml) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6e0437ea94002eac2a7f670811993e35e386722e/public/templates/vector.html#L241)):*
> ```HTML
>                 // add polyline btn click event handler
>                 deleteGeomtryGroup.addEventListener('click', function (e) {
>                     // call an api function to draw a polyline
> ```

Not the good comment

**Review by melzeiny1980 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @jolevesq)

___
*[public/templates/vector.html, line 199 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVM2nT406tis2cEzPQv:-MVMZ8BGApBux_VlKml5:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6e0437ea94002eac2a7f670811993e35e386722e/public/templates/vector.html#L199)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do you really need this?
</blockquote></details>

Done.
___
*[public/templates/vector.html, line 202 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVM2GYY9S7GPapNcwev:-MVMZ9UQ5XSwKugprVPo:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6e0437ea94002eac2a7f670811993e35e386722e/public/templates/vector.html#L202)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add this to the code snippet section
</blockquote></details>

Done.
___
*[public/templates/vector.html, line 239 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVM2U6zBz7IgiKirrl8:-MVMc9uv3JY6_bkh1a2g:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6e0437ea94002eac2a7f670811993e35e386722e/public/templates/vector.html#L239)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Not the good comment
</blockquote></details>

Done.
___
*[public/templates/vector.html, line 240 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVM2W3t0SVs3WRqa-fB:-MVMc9NR4QU8_EiNuj3Q:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6e0437ea94002eac2a7f670811993e35e386722e/public/templates/vector.html#L240)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add this to the code snippet section
</blockquote></details>

Done.
___
*[public/templates/vector.html, line 241 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVM2XmpAuKb0C6Q6-1U:-MVMcC5z4NnflRkD98Kk:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/6e0437ea94002eac2a7f670811993e35e386722e/public/templates/vector.html#L241)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Not the good comment
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @jolevesq and @melzeiny1980)

___
*[public/templates/vector.html, line 72 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVMgELpCO1FHA06IyQm:-MVMgELpCO1FHA06IyQn:bhzhwkh) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/171b58f8a4d5549a17f1c7113369d8d54c3b02fa/public/templates/vector.html#L72)):*
> ```HTML
>             // call an api function to delete the geometry group <br />
>             cgpv.api.map('mapWM').deleteGeometryGroup('myGroup');<br />
>             }); <br />function addPolyline(map) {<br />
> ```

Put a carriage return, hard to read from html page.
___
*[public/templates/vector.html, line 88 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVMfoxz8VdpB3s8JhnD:-MVMfoxz8VdpB3s8JhnE:b-uvy1iz) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/171b58f8a4d5549a17f1c7113369d8d54c3b02fa/public/templates/vector.html#L88)):*
> ```HTML
>             <br />
>             <br />
>             // check if a group already exists if not , create one <br />
> ```

Don't need this, You created the group previously and you know it is there. Remove those check if group exist - if not - create it 
___
*[public/templates/vector.html, line 113 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVMg2nz8BcnNBb5GhTf:-MVMg2nz8BcnNBb5GhTg:b-uvy1iz) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/171b58f8a4d5549a17f1c7113369d8d54c3b02fa/public/templates/vector.html#L113)):*
> ```HTML
>             <br />
>             <br />
>             // check if a group already exists if not , create one <br />
> ```

Don't need this, You created the group previously and you know it is there. Remove those check if group exist - if not - create it 
___
*[public/templates/vector.html, line 130 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVMg3a_7rxLIqylnnkN:-MVMg3a_7rxLIqylnnkO:b-uvy1iz) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/171b58f8a4d5549a17f1c7113369d8d54c3b02fa/public/templates/vector.html#L130)):*
> ```HTML
>             <br />
>             <br />
>             // check if a group already exists if not , create one <br />
> ```

Don't need this, You created the group previously and you know it is there. Remove those check if group exist - if not - create it 
___
*[public/templates/vector.html, line 147 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVMg5Tc7uP-bVAKgOLE:-MVMg5Tc7uP-bVAKgOLF:b-uvy1iz) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/171b58f8a4d5549a17f1c7113369d8d54c3b02fa/public/templates/vector.html#L147)):*
> ```HTML
>             <br />
>             <br />
>             // check if a group already exists if not , create one <br />
> ```

Don't need this, You created the group previously and you know it is there. Remove those check if group exist - if not - create it

**Review by melzeiny1980 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @jolevesq and @melzeiny1980)

___
*[public/templates/vector.html, line 72 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVMgELpCO1FHA06IyQm:-MVMhu5V944qOQRL5R6S:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/171b58f8a4d5549a17f1c7113369d8d54c3b02fa/public/templates/vector.html#L72)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put a carriage return, hard to read from html page.
</blockquote></details>

Done.
___
*[public/templates/vector.html, line 88 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVMfoxz8VdpB3s8JhnD:-MVMh7LEAn8EKMWeCpW_:bfemttg) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/171b58f8a4d5549a17f1c7113369d8d54c3b02fa/public/templates/vector.html#L88)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Don't need this, You created the group previously and you know it is there. Remove those check if group exist - if not - create it 
</blockquote></details>

this is actually is a fix for a bug. one i click the delete group button. the group will be deleted. any subsequent add actions will create geometries in some unknown group . then user will not be able to use the delete button anymore

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @jolevesq and @melzeiny1980)

___
*[public/templates/vector.html, line 88 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVMfoxz8VdpB3s8JhnD:-MVMiIqIEHjK-gywEhLA:bflwy0b) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/171b58f8a4d5549a17f1c7113369d8d54c3b02fa/public/templates/vector.html#L88)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

this is actually is a fix for a bug. one i click the delete group button. the group will be deleted. any subsequent add actions will create geometries in some unknown group . then user will not be able to use the delete button anymore 
</blockquote></details>

Ok.... will have to solve this. We should have 2 separate functions delete the whole group or delete geometries from the group. Having these conditions all over the place are not intuitive.

**Review by melzeiny1980 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @jolevesq)

___
*[public/templates/vector.html, line 113 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVMg2nz8BcnNBb5GhTf:-MVMic7jCyKz0ANRSS2U:b-9rw26w) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/171b58f8a4d5549a17f1c7113369d8d54c3b02fa/public/templates/vector.html#L113)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Don't need this, You created the group previously and you know it is there. Remove those check if group exist - if not - create it 
</blockquote></details>

 this is actually is a fix for a bug. one i click the delete group button. the group will be deleted. any subsequent add actions will create geometries in some unknown group . then user will not be able to use the delete button anymore
___
*[public/templates/vector.html, line 130 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVMg3a_7rxLIqylnnkN:-MVMifM43fHazYdY659v:b7dcqp8) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/171b58f8a4d5549a17f1c7113369d8d54c3b02fa/public/templates/vector.html#L130)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Don't need this, You created the group previously and you know it is there. Remove those check if group exist - if not - create it 
</blockquote></details>

this is actually is a fix for a bug. one i click the delete group button. the group will be deleted. any subsequent add actions will create geometries in some unknown group . then user will not be able to use the delete button anymore
___
*[public/templates/vector.html, line 147 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/138#-MVMg5Tc7uP-bVAKgOLE:-MVMigt6-5pZlGTzAFVd:b7dcqp8) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/171b58f8a4d5549a17f1c7113369d8d54c3b02fa/public/templates/vector.html#L147)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Don't need this, You created the group previously and you know it is there. Remove those check if group exist - if not - create it 
</blockquote></details>

this is actually is a fix for a bug. one i click the delete group button. the group will be deleted. any subsequent add actions will create geometries in some unknown group . then user will not be able to use the delete button anymore

**Pull request merged**
