### PR TITLE
feat(loading-plugins) Create the ability to load react templates as p…

### LINKED ISSUE #61: Create the ability to load a plugin using a react component
Right now creating a plugin to load content from outside such as creating a content for a panel is done by passing HTML elements, add the ability to create the content using a react component so that if a change happens in the state the content will update automatically

### PR DESCRIPTION
**Pull request by yass0016**
…lugins

Closes #61

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/73)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
Looks good, maybe just need a little bit of doc

> Reviewed 10 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/73#-:-MTGqU844nwenpQOF8fT:b-io67lv)* status: 10 of 14 files reviewed, 2 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[public/plugins/panel/panel-content.js, line 3 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/73#-MTGp-gGECM8kK1G981Z:-MTGp-gGECM8kK1G981_:bq53h3g) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/82ac31aa75b6a7859265e47d0f2018a329af8279/public/plugins/panel/panel-content.js#L3)):*
> ```JavaScript
> import React, { useEffect, useState } from 'react';
> 
> const PanelContent = (props) => {
> ```

Can add JSDOC with a little bit of explanation on what is does?

Can add a md file in our doc called plugins where you explain a little bit how we achieve simple plugin creation. Put a note about your thinking of load complex bundle plugin who is on out todo list.
___
*[src/api/api.ts, line 125 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/73#-MTGpAJZ2p0Gd3BtWMmG:-MTGpAJZ2p0Gd3BtWMmH:b-809dgf) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/82ac31aa75b6a7859265e47d0f2018a329af8279/src/api/api.ts#L125)):*
> ```XML
>      * Load a react component file from url
>      *
>      * @param {string} url the url of the react component file
> ```

Should props be in doc as well?

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/73)* status: 10 of 14 files reviewed, 2 unresolved discussions (waiting on @jolevesq and @melzeiny1980)

___
*[public/plugins/panel/panel-content.js, line 3 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/73#-MTGp-gGECM8kK1G981Z:-MTGqzCOEQNbKueUOg1t:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/82ac31aa75b6a7859265e47d0f2018a329af8279/public/plugins/panel/panel-content.js#L3)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can add JSDOC with a little bit of explanation on what is does?

Can add a md file in our doc called plugins where you explain a little bit how we achieve simple plugin creation. Put a note about your thinking of load complex bundle plugin who is on out todo list.
</blockquote></details>

Done.
___
*[src/api/api.ts, line 125 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/73#-MTGpAJZ2p0Gd3BtWMmG:-MTGqwhF-ScH6O04Un8d:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/82ac31aa75b6a7859265e47d0f2018a329af8279/src/api/api.ts#L125)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should props be in doc as well?
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 14 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/73)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @melzeiny1980 and @yass0016)

___
*[common/docs/app/plugins.md, line 9 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/73#-MTGxcWXDkFdSW-8xe3C:-MTGxcWXDkFdSW-8xe3D:be6bzxr) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e8fd2180b835ea914f25c21a5971068413d912a3/common/docs/app/plugins.md#L9)):*
> ```Markdown
> You can see an example plugin below
> 
> https://github.com/yass0016/GeoView/blob/%2361-loading-plugins/public/plugins/panel/panel-content.js
> ```

Can you put just where the file will be and not a link because it points to your branch.

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/73)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @jolevesq and @melzeiny1980)

___
*[common/docs/app/plugins.md, line 9 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/73#-MTGxcWXDkFdSW-8xe3C:-MTGyuEaDYPNlHQfEOO9:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e8fd2180b835ea914f25c21a5971068413d912a3/common/docs/app/plugins.md#L9)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put just where the file will be and not a link because it points to your branch.
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 14 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/73)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @melzeiny1980)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/73#-:-MTGz8snE_HgEAxF5Svz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @melzeiny1980)

**Pull request merged**
