### PR TITLE
881 wcag issue map

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description

Fix wcag issues for map, footer-tab, legends

Fixes # (881)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested locally, 
Also https://github.com/Canadian-Geospatial-Platform/geoview/issues/906 is not part of this.

# Checklist:

- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/907)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
Details tab is closing on click and it should not
Data tab is not working anymore

> Reviewed 2 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/907#-:-NOLpUub9ZlE-PAeuI_H:boxkilu)* status: 2 of 10 files reviewed, all discussions resolved

**Review by kaminderpal — COMMENTED** [review]
fixed.

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/907#-:-NON92Yw-j9-tP0X1QcO:blkwbqj)* status: 1 of 10 files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 6 of 10 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/907)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/map/map.tsx` line 59 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/907#-NOPH-IY17zQnn9G-vS_:-NOPH-IY17zQnn9G-vSa:bzbts0d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/913e0a817dad04131a2ce3b419029cbf537c1010/packages/geoview-core/src/core/components/map/map.tsx#L59)):*
> ```XML
> 
>   // get ref to div element
>   const mapElement = useRef<HTMLDivElement | null>();
> ```

Are you sure you need to remove | null?
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 258 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/907#-NOPGhEX2HeTF2zOPZvD:-NOPGhEX2HeTF2zOPZvE:bluxgez) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f029537a92461edffd1bb0f765382d3c36adeb0/packages/geoview-core/src/core/utils/utilities.ts#L258)):*
> ```XML
>  *  when focus is set to map and
>  * arrows and enter keys are used to navigate the map
>  * @param e
> ```

Miss param description and elem param

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/907)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/map/map.tsx` line 59 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/907#-NOPH-IY17zQnn9G-vS_:-NOPcK0zBDchGbZFdmLA:b-4yadkb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/913e0a817dad04131a2ce3b419029cbf537c1010/packages/geoview-core/src/core/components/map/map.tsx#L59)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Are you sure you need to remove | null?
</blockquote></details>

It's not recommended to use null by typescript, but i have added undefined for init value.
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 258 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/907#-NOPGhEX2HeTF2zOPZvD:-NOPaoy60GNsiu8o7aDv:b-7rl0jd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4f029537a92461edffd1bb0f765382d3c36adeb0/packages/geoview-core/src/core/utils/utilities.ts#L258)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Miss param description and elem param
</blockquote></details>

done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/907)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Pull request merged**
