### PR TITLE
2472-Config_API_for_WFS

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486)

### CODE REVIEW

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486)* status: all files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 1093 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486#-O742OSvA1XO6KcOqipp:-O74QZqR8RBGh4GND_Wp:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a3ac9db0f4f54cbc05a1681e807d12e6075a766e/packages/geoview-core/src/api/config/types/config-validation-schema.json#L1093)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It says WMS but it is WFS
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 1378 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486#-O742KV52H_qhsr1wt0B:-O74R5A_1Zwd7WnKOtSd:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a3ac9db0f4f54cbc05a1681e807d12e6075a766e/packages/geoview-core/src/api/config/types/config-validation-schema.json#L1378)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It says ESRI but it is WFS
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/vector/wfs-layer-entry-config.ts` line 111 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486#-O746nTj-5p-FPc1h2mr:-O74Rlyj8nqRJwY5Udns:b-369m18) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a3ac9db0f4f54cbc05a1681e807d12e6075a766e/packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/vector/wfs-layer-entry-config.ts#L111)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Shuold we 1000 instead or in our geocode 0 means all?
</blockquote></details>

The schema says that the default value is 0.
We have a comment in schemaESRIFeature.txt that says:
 "maxRecordCount": 0, // default 0 - if set it mean we may need a loop to load all features - FOR VECTOR
Do you want to change it for 1000.

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486)* status: all files reviewed, 8 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 221 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486#-O74rZfI2KeYOqfIVmRq:-O74rZfI2KeYOqfIVmRr:btornlk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a3ac9db0f4f54cbc05a1681e807d12e6075a766e/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L221)):*
> ```XML
>    *
>    * @returns {EntryConfigBaseClass} The subLayer created from the metadata.
>    * @private
> ```

Minor: `Should be @protected`
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/wms-group-layer-config.ts` line 33 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486#-O74tnJ10ir1-ErVn-e8:-O74tnJ10ir1-ErVn-e9:bqq40s2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a3ac9db0f4f54cbc05a1681e807d12e6075a766e/packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/wms-group-layer-config.ts#L33)):*
> ```XML
> 
>     // WMS service metadata contains the layer's metadata. We don't have to fetch again.
>     const layerMetadata = (this.getGeoviewLayerConfig() as WmsLayerConfig).findLayerMetadataEntry(this.layerId);
> ```

(view other comment)
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/raster/wms-layer-entry-config.ts` line 66 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486#-O74uGH61KA-Deh9kAsi:-O74uGH7CPdWmn1Fomhf:bqq40s2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a3ac9db0f4f54cbc05a1681e807d12e6075a766e/packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/raster/wms-layer-entry-config.ts#L66)):*
> ```XML
> 
>     // WMS service metadata contains the layer's metadata.
>     const layerMetadata = (this.getGeoviewLayerConfig() as WmsLayerConfig).findLayerMetadataEntry(this.layerId);
> ```

(view other comment)
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/vector/wfs-layer-entry-config.ts` line 75 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486#-O74tHeY96cZyGso3jin:-O74tHeY96cZyGso3jio:b-jgg4fo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a3ac9db0f4f54cbc05a1681e807d12e6075a766e/packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/vector/wfs-layer-entry-config.ts#L75)):*
> ```XML
> 
>     // WFS service metadata contains one part of the layer's metadata.
>     const fromGetCapabilities = (this.getGeoviewLayerConfig() as WfsLayerConfig).findLayerMetadataEntry(this.layerId);
> ```

Suggestion: The layer-entry-config sub classes should probably all expose an overridable (or a shadow) getter `getGeoviewLayerConfig()` which does the property type cast and return the typed object.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/vector/wfs-layer-entry-config.ts` line 140 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486#-O74qEXvD_Ml67P7m-Kk:-O74qEXw-KIcicGQnoSg:bfzl4iy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a3ac9db0f4f54cbc05a1681e807d12e6075a766e/packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/vector/wfs-layer-entry-config.ts#L140)):*
> ```XML
>    * Fetch the feature information from the service endpoint.
>    *
>    * @provate @async
> ```

Minor: Small typo `@private`

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486)* status: 22 of 27 files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts` line 221 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486#-O74rZfI2KeYOqfIVmRq:-O75-shB-KBb5OeFw7kK:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a3ac9db0f4f54cbc05a1681e807d12e6075a766e/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-layer-config.ts#L221)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Minor: `Should be @protected`
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/wms-group-layer-config.ts` line 33 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486#-O74tnJ10ir1-ErVn-e8:-O754UeC04UeFNvnOeIG:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a3ac9db0f4f54cbc05a1681e807d12e6075a766e/packages/geoview-core/src/api/config/types/classes/sub-layer-config/group-node/wms-group-layer-config.ts#L33)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

(view other comment)
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/raster/wms-layer-entry-config.ts` line 66 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486#-O74uGH61KA-Deh9kAsi:-O754ZJ25Hfra2Fv-k9z:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a3ac9db0f4f54cbc05a1681e807d12e6075a766e/packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/raster/wms-layer-entry-config.ts#L66)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

(view other comment)
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/vector/wfs-layer-entry-config.ts` line 75 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486#-O74tHeY96cZyGso3jin:-O753LFSBwPE0dY52g9y:bwq3vmt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a3ac9db0f4f54cbc05a1681e807d12e6075a766e/packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/vector/wfs-layer-entry-config.ts#L75)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Suggestion: The layer-entry-config sub classes should probably all expose an overridable (or a shadow) getter `getGeoviewLayerConfig()` which does the property type cast and return the typed object.
</blockquote></details>

Done. Super good idea!
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/vector/wfs-layer-entry-config.ts` line 140 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486#-O74qEXvD_Ml67P7m-Kk:-O754heJ10uQcGf9XiDv:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a3ac9db0f4f54cbc05a1681e807d12e6075a766e/packages/geoview-core/src/api/config/types/classes/sub-layer-config/leaf/vector/wfs-layer-entry-config.ts#L140)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Minor: Small typo `@private`
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 4 of 5 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2486)* status: all files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan)

**Pull request merged**
