### PR TITLE
fix(details): fix display of right panel when in details  closes2178

### LINKED ISSUE #2178: [BUG] Details Wait All to Finish
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we click on the map to get the details, the component is waiting to receive all the answer before proceeding to show the feature. This is happening even if the selected layer as answer very quickly

### Expected Behavior

If a layer is selected, as soon as we have an answer, the feature should be shown in the right panel

### Steps To Reproduce

1. Go to https://alex-nrcan.github.io/geoview/demos-navigator.html?config=./configs/navigator/16-esri-dynamic.json
2. Click on the map
3. The right panel is waiting for the temporal to answer before it display the content

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Fix the details right panel showing when layers are loading

Fixes #2178 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/demos-navigator.html?config=./configs/navigator/16-esri-dynamic.json

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2283)

### CODE REVIEW

**Review by cphelefu — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2283)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2283)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq and @kaminderpal)

___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 413 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2283#-O-lROnLDoAhq6PAwcVR:-O-lROnLDoAhq6PAwcVS:b-322u8t) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f670d756ed10969dad6566c32e9f003b34c192e8/packages/geoview-core/src/core/components/details/details-panel.tsx#L413)):*
> ```XML
> 
>   /**
>    * Check all layers sttaus is processing while querying
> ```

sttaus > status

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2283)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @cphelefu, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 413 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2283#-O-lROnLDoAhq6PAwcVR:-O-lSGIN5h5uNxaB20Tz:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f670d756ed10969dad6566c32e9f003b34c192e8/packages/geoview-core/src/core/components/details/details-panel.tsx#L413)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

sttaus > status
</blockquote></details>

Done.

**Review by DamonU2 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2283)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
