### PR TITLE
feat(footerbar): timeslider  #closes2232

### LINKED ISSUE #2232: [FEATURE] Timeslider No Layer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

We need to have same view for time slider then the other panel (left-no layer / right-guide). For the moment there nothing

### Implementation UI

image

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
1) Fix the size of tabs in footer bar
2) Add guide feature for time slider plugin

Fixes #2232 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/add-layers.html
https://kaminderpal.github.io/geoview/demos-navigator.html?config=./configs/navigator/06-basic-footer.json

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244)

### CODE REVIEW

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts` line 34 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244#-O-H8n0z7SAFa-W8yOa-:-O-H8n0z7SAFa-W8yOa0:b-4oi6mb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0753645fdb4a4bf44cb431e2b4b87931461162f5/packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts#L34)):*
> ```XML
>       margin: '0.5rem',
>       minHeight: 0,
>     },
> ```

Maybe we can add this styling to ui/styles/themeOptionsGenerator (under components) so that this styling is applied to all Tabs components used in the application.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/ui/tabs/tabs-style.ts` line 22 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244#-O-H9GERBb_MvoaR7G2J:-O-H9GERBb_MvoaR7G2K:b-kqeklt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0753645fdb4a4bf44cb431e2b4b87931461162f5/packages/geoview-core/src/ui/tabs/tabs-style.ts#L22)):*
> ```XML
>     fontWeight: 'bold',
>     minWidth: 'min(4vw, 24px)',
>     padding: '8px 2%',
> ```

can change to 0.5rem. Optional.

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts` line 34 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244#-O-H8n0z7SAFa-W8yOa-:-O-HF4V2Dp7J00uRfU33:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0753645fdb4a4bf44cb431e2b4b87931461162f5/packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts#L34)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Maybe we can add this styling to ui/styles/themeOptionsGenerator (under components) so that this styling is applied to all Tabs components used in the application.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/tabs/tabs-style.ts` line 22 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244#-O-H9GERBb_MvoaR7G2J:-O-HF7Wn2D1CnM-vQBrx:b-7rl0jd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0753645fdb4a4bf44cb431e2b4b87931461162f5/packages/geoview-core/src/ui/tabs/tabs-style.ts#L22)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

can change to 0.5rem. Optional.
</blockquote></details>

done.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 161 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244#-O-HH6-m2wgDne3a1OC0:-O-HH6-m2wgDne3a1OC1:b-7gqer0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b8a6a75eae85132f7ce8126f96fe4c62f9a50e85/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L161)):*
> ```XML
>       return { ...prevState, ...newTab };
>     });
>   }, []);
> ```

Did you mean to remove `[tabsList]` here?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts` line 34 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244#-O-H8n0z7SAFa-W8yOa-:-O-HHZw20eh7NiupyoE7:b-ml56db) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0753645fdb4a4bf44cb431e2b4b87931461162f5/packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts#L34)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hmm. my bad. If we do this it will make every flexContainer have 56px.. maybe I was wrong. This can be dangerous if we ever add another tab component. My apologies.

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 161 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244#-O-HH6-m2wgDne3a1OC0:-O-HMKzGEl8zvAPldar4:b-n3h6e9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b8a6a75eae85132f7ce8126f96fe4c62f9a50e85/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L161)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Did you mean to remove `[tabsList]` here?
</blockquote></details>

this callback dnt need `tabsList` as dep, bcz we are using prevState callback to update the state.

**Review by cphelefu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244#-:-O-HYs8t62jwxd3AW9tJ:bnfp4nl)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @jolevesq and @kaminderpal)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 3 of 5 files at r1, 2 of 3 files at r2, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @cphelefu and @kaminderpal)

___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 161 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244#-O-HH6-m2wgDne3a1OC0:-O-HhE-i1JsTGBFNRQVU:b-qvjrco) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b8a6a75eae85132f7ce8126f96fe4c62f9a50e85/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L161)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

this callback dnt need `tabsList` as dep, bcz we are using prevState callback to update the state.
</blockquote></details>

Do you need to ad a eslint to remove the warning?

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 161 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244#-O-HH6-m2wgDne3a1OC0:-O-HiG4V55hvJuZgDM2C:bddwzjz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b8a6a75eae85132f7ce8126f96fe4c62f9a50e85/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L161)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do you need to ad a eslint to remove the warning?
</blockquote></details>

We dnt need to add `eslint` warning, because `handleAddTab` function doesnt need `tabsList` state. State will be update with useState hook callback pattern.

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts` line 34 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244#-O-H8n0z7SAFa-W8yOa-:-O-Hjt0Y-93IUWoUCC_t:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0753645fdb4a4bf44cb431e2b4b87931461162f5/packages/geoview-core/src/core/components/footer-bar/footer-bar-style.ts#L34)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Hmm. my bad. If we do this it will make every flexContainer have 56px.. maybe I was wrong. This can be dangerous if we ever add another tab component. My apologies.
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2244)* status: all files reviewed, 2 unresolved discussions (waiting on @cphelefu)

**Pull request merged**
