### PR TITLE
feat(samples): Generate Code Snippet

### LINKED ISSUE #139: Samples page code snippet
Find a way to build automatically the code snippet from the html script tag like what is is done for config. Do not include the script use to generate the config snippet.

At the same time format the code so the indentation are right. to help, use the <code> html tag

### PR DESCRIPTION
**Pull request by melzeiny1980**
closes #139

## Checklist

* [ ] Commit message follow the guidelines
* [ ] PR targets the correct release version
* [ ] Deploy has been done
* [ ] Check styling
* [ ] _Help files and documentation have been updated_
* [ ] ~Release notes have been updated~

## What's to look for styling
* Use camelCase for identifier names (variables and functions)
* Use PascalCase for type names
* Do not use "I" as a prefix for interface names
* Do not export types/functions unless you need to share it across multiple components
* All names start with a letter
* Always put spaces around operators ( = + - * / ), and after colon:
* Remove all trailing white spaces
* Look for bad indentation
* Carriage return are mandatory
  * Before comments
  * Before if condition
  * After if condition
  * Before properties
  * Before classes
  * Before functions

The use of Prettier Visual Studio Code extension let's you format automatically your code to remove most of the styling issues like white space and indentation.

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/146)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
Because you reuse createCodeSnippet and crateConfig Snippet in all pages, can you create those 2 funstions in a js file and add the script to all pages instead of duplicate?

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/146#-:-MVXWQ7w0E_CLqFIPT8o:byiaxnm)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @melzeiny1980 and @yass0016)

___
*[public/templates/add-panels.html, line 75 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/146#-MVXW14q5nXVHd1oQwF8:-MVXW14q5nXVHd1oQwF9:b-lf2rq9) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/399bd8e6a53c40e1cb37791f8c3cb0a3c2a7cf03/public/templates/add-panels.html#L75)):*
> ```HTML
>             }
> 
>             function createConfigSnippet() {
> ```

The code block doesn't appear for this page

**Review by jolevesq — CHANGES_REQUESTED** [review]
This is clean, will make all pages easier to maintain

> Reviewed 12 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/146#-:-MVaYBzZ6aka0H_ksZx7:b-tamnym)* status: all files reviewed, 1 unresolved discussion (waiting on @melzeiny1980 and @yass0016)

___
*[public/templates/usecases.html, line 192 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/146#-MVaXkNO1D7wXUwrA0ya:-MVaXkNO1D7wXUwrA0yb:bh5vvip) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/104b16f956aee01f69c3ab3c303e2b91a518af8c/public/templates/usecases.html#L192)):*
> ```HTML
> 
>                 //add polygon to map
>                 addPolygon('UC1');
> ```

The code block appears at the bottom of the page. Should be just below config snippet block of map 1

**Review by melzeiny1980 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/146)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @jolevesq and @yass0016)

___
*[public/templates/usecases.html, line 192 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/146#-MVaXkNO1D7wXUwrA0ya:-MVaf81d2gqtd__fchMT:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/104b16f956aee01f69c3ab3c303e2b91a518af8c/public/templates/usecases.html#L192)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The code block appears at the bottom of the page. Should be just below config snippet block of map 1
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/146#-:-MVajReT7xPhtSI_tBRh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yass0016)

**Pull request merged**
