### PR TITLE
refactor(responsive-ui): Make the UI Responsive

### LINKED ISSUE #2: Make the UI responsive
Make sure we have a nice transition from mobile to desktop using threshold for small, medium and large device. Large device should include everything. When we downsize we start to remove/modify some of the components

Large:
* Nav bar
* Scale
* Mouse position
* Attribution
* App bar
* Overview map

Small and Medium:
* Nav bar
* Scale
* App bar

The threshold should be part of theme. So this issue is related with #3

### PR DESCRIPTION
**Pull request by yass0016**
Closes #2

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/37)

### CODE REVIEW

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/37)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @jolevesq)

___
*[src/components/appbar/app-bar.tsx, line 23 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/37#-MR_gZ-FDwUaQUcMJnRF:-MR_jQ3KEzXKYlILrvTx:b-v50o05) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/99583f22372384d77d4b080c5ab559dc9df04b50/src/components/appbar/app-bar.tsx#L23)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we have border inside theme as well?
</blockquote></details>

I looked that up with theming when I was doing issue #3 but we can only use borders when we doing them inline. It doesn't exist in theming as far as I know
___
*[src/components/appbar/buttons/layers.tsx, line 14 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/37#-MR_h-Ef-J6ZzATCouTO:-MR_ka6x697scw3zf93z:bopwcxw) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/99583f22372384d77d4b080c5ab559dc9df04b50/src/components/appbar/buttons/layers.tsx#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can all this be in appbar/buttons.tsx. Every button/panel for appbar should behaves the same way and we do not want to have to duplicate it inside each buttons.
</blockquote></details>

We have to specify a props validation for each component, its actually not meant to be duplicated, we simply don't have other props that we are passing. This is a requirement of typescript and eslint, we can create a a shared type / interface and import it, if thats what you want, but I believe this is the right way
___
*[src/components/layers/layers-panel.tsx, line 6 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/37#-MR_hW6j6tqji6t-zCvH:-MR_liShEYtCg5M2doH9:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/99583f22372384d77d4b080c5ab559dc9df04b50/src/components/layers/layers-panel.tsx#L6)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same here, can it be inside appbar.panel.tsx
</blockquote></details>

Done.
___
*[src/components/map/map.tsx, line 43 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/37#-MR_hqBy5ffZX732kpVC:-MR_lhfc-SCgqayhzbQi:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/99583f22372384d77d4b080c5ab559dc9df04b50/src/components/map/map.tsx#L43)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put a more meaningful const name e.g. deviceSizeMdUp
</blockquote></details>

Done.

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/37)* status: 3 of 8 files reviewed, 4 unresolved discussions (waiting on @jolevesq)

___
*[src/components/appbar/app-bar.tsx, line 23 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/37#-MR_gZ-FDwUaQUcMJnRF:-MR_oSZu3vN7erb1QqHz:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/99583f22372384d77d4b080c5ab559dc9df04b50/src/components/appbar/app-bar.tsx#L23)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

I looked that up with theming when I was doing issue #3 but we can only use borders when we doing them inline. It doesn't exist in theming as far as I know
</blockquote></details>

Done.
___
*[src/components/appbar/buttons/layers.tsx, line 14 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/37#-MR_h-Ef-J6ZzATCouTO:-MR_mJmuAuxoE94rZqv3:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/99583f22372384d77d4b080c5ab559dc9df04b50/src/components/appbar/buttons/layers.tsx#L14)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

We have to specify a props validation for each component, its actually not meant to be duplicated, we simply don't have other props that we are passing. This is a requirement of typescript and eslint, we can create a a shared type / interface and import it, if thats what you want, but I believe this is the right way
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 4 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/37)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jolevesq — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/37#-:-MR_sVJm7Rrtf-uZAu5A:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
