### PR TITLE
fix(core): Upgrade to React 18

### LINKED ISSUE #1075: [REFACTOR] Upgrade to React 18
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently we use React version 17. A new version has been launch and brings breaking changes. There is no more ReactDom.render function we need to change the import to reactdom-client and use the create root function.

From some quick test, the React elements rendered this way access their useEffect prior to the api.(mapId).map element is created. Because the the map element is undefined, all components rendering are failing.

### Expected Behavior

Investigate and find a suitable solution. For the ReactDom export from the api, try to minimize the breaking change.

https://react.dev/reference/react-dom/client/createRoot

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1075

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Upgrade React version to 18.

Fixes # 1075

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Test if all demo pages are working as expected and if problems still persist, crate issue. Everything is fine but the reload is tricky because of the new create root way of doing.

https://jolevesq.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1195)

### CODE REVIEW

**Review by cphelefu — APPROVED** [review]
> Reviewed 51 of 51 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1195)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amir-azma, @DamonU2, @kaminderpal, and @ychoquet)

**Review by amir-azma — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1195#-:-NaIyLip6XPAUf5Z1PF6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamonU2, @kaminderpal, and @ychoquet)

**Review by amir-azma — APPROVED** [review]
> Reviewed 51 of 51 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1195)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamonU2, @kaminderpal, and @ychoquet)

**Review by DamonU2 — APPROVED** [review]
> Reviewed 51 of 51 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1195)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kaminderpal and @ychoquet)

**Pull request merged**
