### PR TITLE
refactor(highlight): highlight functionality utilizes store

### LINKED ISSUE #1350: [REFACTOR] Feature Highlight Store
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The feature highlight events is inside the component.

### Expected Behavior

Use store to manage highlight state (on/off), array of features to highlights...

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #1350

# Description

Moves highlight functionality out of component and adds store values to track highlights.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested with various layers and geolocator searches.

https://damonu2.github.io/geoview/package-footer-panel.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 11 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514)* status: 11 of 13 files reviewed, 6 unresolved discussions (waiting on @amir-azma and @DamonU2)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 77 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-Njm0X_Y6gx84EJITWLj:-Njm0X_Y6gx84EJITWLk:b-1h1r35) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd5fd76537c9d429a5f595c24a9dba8a0175165/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L77)):*
> ```XML
>           );
>           for (let i = 0; i < newFeatures.length; i++) api.maps[mapId].layer.featureHighlight.highlightFeature(newFeatures[i]);
>         } else if (curFeatures.length < prevFeatures.length) {
> ```

Should we redo the highlight not based on length but uuid.  If we send two time the array with same nb of items but different uuid it will not work
___
*[`packages/geoview-core/src/core/components/data-table/map-data-table.tsx` line 283 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-Njm1tNu7yLbVOv7ZDN8:-Njm1tNu7yLbVOv7ZDN9:bnkuu1u) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd5fd76537c9d429a5f595c24a9dba8a0175165/packages/geoview-core/src/core/components/data-table/map-data-table.tsx#L283)):*
> ```XML
>       const row = data.features[Number(idx)];
>       if (row) {
>         addSelectedFeature(row);
> ```

Can we do, part of this PR, a difference between the highlight. (animation and no animation). This way, when called by datatable, we have a geometry highlight (maybe green like RAMPS) but no animation.
___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 122 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-Njm3-d9Dp9glXqrkhDo:-Njm3-d9Dp9glXqrkhDp:b-doe9tw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd5fd76537c9d429a5f595c24a9dba8a0175165/packages/geoview-core/src/core/components/details/details-panel.tsx#L122)):*
> ```XML
>     setCurrentFeatureIndex(0);
>     setSelectedLayerPath(layerData.layerPath);
>     setIsLayersPanelVisible(false);
> ```

This function is in slider, details and table  layerlist item. Can we have all of them build same way with the handleLayerChange  function so it is standard? 
___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 207 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-Njm3Tip6qu_lnNhGPTH:-Njm3TiqChj57kAPMMpA:b-s7xp84) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd5fd76537c9d429a5f595c24a9dba8a0175165/packages/geoview-core/src/core/components/details/details-panel.tsx#L207)):*
> ```XML
>                         tooltip="details.previousFeatureBtn"
>                         tooltipPlacement="top"
>                         onClick={() => handleFeatureNavigateChange(-1)}
> ```

I like the naming convention of the handle... for onClick item. I think Alex has this as welll in chart.
___
*[`packages/geoview-core/src/core/components/details/feature-info-new.tsx` line 68 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-Njm3oGA2rm7ZcU8vc_J:-Njm3oGA2rm7ZcU8vc_K:b-g8abwb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd5fd76537c9d429a5f595c24a9dba8a0175165/packages/geoview-core/src/core/components/details/feature-info-new.tsx#L68)):*
> ```XML
>   const handleZoomIn = (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
>     e.stopPropagation();
>     api.maps[mapId].zoomToExtent(feature.extent);
> ```

Add a function zoomToExtent in map-state (similar to zoomInitialExtent) and remove api call
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-Njm5PO3BIe7cVyykXDZ:-Njm5PO3BIe7cVyykXD_:bwrz1vl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd5fd76537c9d429a5f595c24a9dba8a0175165/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L78)):*
> ```XML
>    */
>   const zoomToLocation = (coords: [number, number], bbox?: [number, number, number, number]): void => {
>     const { currentProjection } = api.maps[mapId];
> ```

All this block can be in map-state
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 94 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-Njm4kRAA752Zd1LWyBS:-Njm4kRAA752Zd1LWyBT:b-z5cooq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd5fd76537c9d429a5f595c24a9dba8a0175165/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L94)):*
> ```XML
>         duration: OL_ZOOM_DURATION,
>       });
>       api.maps[mapId].layer.featureHighlight.highlightGeolocatorBBox(convertedExtent);
> ```

We should remove api call. We can use a function in map state to trigger the highlight

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514)* status: 6 of 16 files reviewed, 6 unresolved discussions (waiting on @amir-azma and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 77 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-Njm0X_Y6gx84EJITWLj:-NjmPiEI19usBVreEM94:b-j2n3s6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd5fd76537c9d429a5f595c24a9dba8a0175165/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L77)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we redo the highlight not based on length but uuid.  If we send two time the array with same nb of items but different uuid it will not work
</blockquote></details>

The only way to change the array was to add one, remove one, or remove all, so I had it this way, but it's more future proof to do it by uid. Done!
___
*[`packages/geoview-core/src/core/components/data-table/map-data-table.tsx` line 283 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-Njm1tNu7yLbVOv7ZDN8:-Njn04GA9V_txJZP7QHt:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd5fd76537c9d429a5f595c24a9dba8a0175165/packages/geoview-core/src/core/components/data-table/map-data-table.tsx#L283)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we do, part of this PR, a difference between the highlight. (animation and no animation). This way, when called by datatable, we have a geometry highlight (maybe green like RAMPS) but no animation.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 122 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-Njm3-d9Dp9glXqrkhDo:-Njn98UJ0_rysTivTGbZ:b-3drkm4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd5fd76537c9d429a5f595c24a9dba8a0175165/packages/geoview-core/src/core/components/details/details-panel.tsx#L122)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This function is in slider, details and table  layerlist item. Can we have all of them build same way with the handleLayerChange  function so it is standard?
</blockquote></details>

I updated the time-slider one to match, but left the one in data-panel.tsx mostly unchanged.
___
*[`packages/geoview-core/src/core/components/details/feature-info-new.tsx` line 68 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-Njm3oGA2rm7ZcU8vc_J:-NjnBO116NaV3X5ZcIJg:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd5fd76537c9d429a5f595c24a9dba8a0175165/packages/geoview-core/src/core/components/details/feature-info-new.tsx#L68)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add a function zoomToExtent in map-state (similar to zoomInitialExtent) and remove api call
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-Njm5PO3BIe7cVyykXDZ:-NjnHaKt98Twb6WIANvP:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd5fd76537c9d429a5f595c24a9dba8a0175165/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L78)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

All this block can be in map-state
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 94 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-Njm4kRAA752Zd1LWyBS:-NjnHa_W7L5zTPKTsWXm:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fdd5fd76537c9d429a5f595c24a9dba8a0175165/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L94)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should remove api call. We can use a function in map state to trigger the highlight
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514)* status: 15 of 17 files reviewed, 1 unresolved discussion (waiting on @amir-azma and @DamonU2)

___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 118 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-NjnNoKO-QRYx-mrxI-i:-NjnNoKO-QRYx-mrxI-j:b7pamc7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bd679982c3efc95c49fb3109ebf44e0db090d017/packages/geoview-core/src/core/components/details/details-panel.tsx#L118)):*
> ```XML
>     setCurrentFeatureIndex(0);
>     setSelectedLayerPath(layerData.layerPath);
>     setIsLayersPanelVisible(true);
> ```

This should be false, if not  when resize we loose layer selection. We should always goes layers selection when resize

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r2, 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514)* status: 19 of 21 files reviewed, 4 unresolved discussions (waiting on @amir-azma and @DamonU2)

___
*[`packages/geoview-core/src/core/components/click-marker/click-marker.tsx` line 46 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-Njr4QQr1MRvWMHfmZPO:-Njr4QQr1MRvWMHfmZPP:behdcxd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b3e8a5ec21043b307966136f8d95f30f8059de87/packages/geoview-core/src/core/components/click-marker/click-marker.tsx#L46)):*
> ```XML
>     const selectedLayerDataEntry = layerDataArray.filter((layerData) => layerData.layerPath === selectedLayerPath)[0];
>     if (
>       selectedLayerDataEntry != null &&
> ```

Should it be !==
___
*[`packages/geoview-core/src/core/components/click-marker/click-marker.tsx` line 48 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-Njr4N1JE_z39Vk-ff-T:-Njr4N1JE_z39Vk-ff-U:bysqzoy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b3e8a5ec21043b307966136f8d95f30f8059de87/packages/geoview-core/src/core/components/click-marker/click-marker.tsx#L48)):*
> ```XML
>       selectedLayerDataEntry != null &&
>       selectedLayerDataEntry.features?.length &&
>       selectedLayerDataEntry.features[0].geoviewLayerType !== 'ogcWms'
> ```

Why are we testing for wms?
___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 118 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-NjnNoKO-QRYx-mrxI-i:-Njr4iUf0McuALb_iVKY:bi6g64y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bd679982c3efc95c49fb3109ebf44e0db090d017/packages/geoview-core/src/core/components/details/details-panel.tsx#L118)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This should be false, if not  when resize we loose layer selection. We should always goes layers selection when resize
</blockquote></details>

Still not working properly for details panel when resizing.
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts` line 391 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-Njr4zWQ6_MuZPJyvgr5:-Njr4zWQ6_MuZPJyvgr6:bgprb38) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bd679982c3efc95c49fb3109ebf44e0db090d017/packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts#L391)):*
> ```XML
>       },
>       zoomToGeoLocatorLocation: (coords: [number, number], bbox?: [number, number, number, number]): void => {
>         const { currentProjection } = api.maps[get().mapId];
> ```

You can have this value directly in the store. One of our next issue will be to clean up these info attach to the map object

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514)* status: 19 of 21 files reviewed, 4 unresolved discussions (waiting on @amir-azma and @DamonU2)

___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 118 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514#-NjnNoKO-QRYx-mrxI-i:-NjrWo2L6TXWN5ttqnD4:b5fap2g) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/bd679982c3efc95c49fb3109ebf44e0db090d017/packages/geoview-core/src/core/components/details/details-panel.tsx#L118)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Still not working properly for details panel when resizing.
</blockquote></details>

We will keep it like this for now and fix later when components are stabilized

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 5 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1514)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amir-azma)

**Pull request merged**
