### PR TITLE
Fixes to add layer UI

### LINKED ISSUE #1795: [BUG] Fix UI displaying layer status in layers
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

UI is not inconsistent in how it handlers layer status in the layers panel. Especially in how we handle layer status loading/processing.

### Expected Behavior

When layer has the following status - loading/processing we should show a spinner and a greenish background.

When the layer an error we should show a delete button and back a reddish background on the layer.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### LINKED ISSUE #1796: [BUG] Fix the light and dark theme
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since we centralized the colors we need to make sure colors for the light and dark theme also make sense.

- [ ]  Add colors to for the light theme.
- [ ]  the loading effect... in the other tab, it is different (orange background), we need to standardize
- [ ] Fix the zebra for all colors in the details tab

### Expected Behavior

* Define colors theme for each theme.
* Adjust colors to make sure each color make sense across all theme.
* Go through different components/tabs and make sure the colors make sense for each theme.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1795 
Fixes #1796

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://cphelefu.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1797)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1797)* status: 10 of 22 files reviewed, 2 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/src/core/components/details/details-style.ts` line 23 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1797#-NqdQKdQ8IqRQpDo9YXR:-NqdQKdQ8IqRQpDo9YXS:b-sioqy0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/27e292f0dedbe3b20429ad3060a261f0671e78c1/packages/geoview-core/src/core/components/details/details-style.ts#L23)):*
> ```XML
>     border: `2px solid ${theme.palette.geoViewColor.primary.main}`,
>     borderRadius: '5px',
>     // backgroundColor: theme.palette.geoViewColor.white,
> ```

Remove dead code

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 9 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1797)* status: 19 of 22 files reviewed, 7 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 421 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1797#-NqdQdij2ulCDe28euMh:-NqdQdik0RPwN5rJLw2b:b-wnqr6d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/27e292f0dedbe3b20429ad3060a261f0671e78c1/packages/geoview-core/src/core/components/details/details-panel.tsx#L421)):*
> ```XML
>                       onClick={() => handleFeatureNavigateChange(1)}
>                       disabled={!memoSelectedLayerData?.features || currentFeatureIndex + 1 >= memoSelectedLayerData!.features!.length}
>                       color="primary"
> ```

We do not use theme...geoviewColor.primary?
___
*[`packages/geoview-core/src/core/components/export/export-modal-button.tsx` line 31 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1797#-NqdQbbK1ejzol-w3HQ-:-NqdQbbK1ejzol-w3HQ0:b-wnqr6d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/27e292f0dedbe3b20429ad3060a261f0671e78c1/packages/geoview-core/src/core/components/export/export-modal-button.tsx#L31)):*
> ```XML
>       onClick={() => openModal({ activeElementId: 'export', callbackElementId: `${mapId}-export-btn` })}
>       className={className}
>       color="primary"
> ```

We do not use theme...geoviewColor.primary?
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 447 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1797#-NqdQUVrBuB7hYgcbY81:-NqdQUVrBuB7hYgcbY82:b-wnqr6d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/27e292f0dedbe3b20429ad3060a261f0671e78c1/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L447)):*
> ```XML
>               onClick={handleDynamicFocus}
>               tooltip={isFocusToMap ? 'footerBar.focusToMap' : 'footerBar.focusToFooter'}
>               color="primary"
> ```

We do not use theme...geoviewColor.primary?
___
*[`packages/geoview-core/src/core/components/notifications/notifications.tsx` line 103 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1797#-NqdQjdS2LewypD_nd5P:-NqdQjdS2LewypD_nd5Q:b-wnqr6d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/27e292f0dedbe3b20429ad3060a261f0671e78c1/packages/geoview-core/src/core/components/notifications/notifications.tsx#L103)):*
> ```XML
>           onClick={handleOpenPopover}
>           className={open ? 'style1' : ''}
>           color="primary"
> ```

We do not use theme...geoviewColor.primary?
___
*[`packages/geoview-core/src/ui/style/themeOptionsGenerator.ts` line 63 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1797#-NqdQoUu8_i6MEJTeG2i:-NqdQoUu8_i6MEJTeG2j:b-f1tzko) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/27e292f0dedbe3b20429ad3060a261f0671e78c1/packages/geoview-core/src/ui/style/themeOptionsGenerator.ts#L63)):*
> ```XML
>         paper: geoViewColors.bgColor.light[600],
>         default: geoViewColors.bgColor.light[500],
>         // grey: '#eeeeee',
> ```

Do we need dead code here and below?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/public/locales/fr/translation.json` line 113 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1797#-NqY5CClBMmVH6gmHUsH:-NqdR_KDEbWOHutH08u9:b-ds3mui) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/937a866ef68f4f560f1a008f7df75f24a5e6fd6e/packages/geoview-core/public/locales/fr/translation.json#L113)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

When we add this layer we get added successfully but it is still in progress and in reality, it is in error. https://data.sac-isc.gc.ca/geomatics/rest/services/Donnees_Ouvertes-Open_Data/Community_Well_Being_Index_E/MapServer
</blockquote></details>

Changed it 'layerAdded'.. remove successfully.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 421 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1797#-NqdQdij2ulCDe28euMh:-NqdRg8S60auKqrqmo7b:b8xv2h8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/27e292f0dedbe3b20429ad3060a261f0671e78c1/packages/geoview-core/src/core/components/details/details-panel.tsx#L421)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We do not use theme...geoviewColor.primary?
</blockquote></details>

These are hardcorded mui colors.. that basically defined the color/hover/active state of a button.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/details/details-style.ts` line 23 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1797#-NqdQKdQ8IqRQpDo9YXR:-NqdS5NRAdMSXmJYXxRY:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/27e292f0dedbe3b20429ad3060a261f0671e78c1/packages/geoview-core/src/core/components/details/details-style.ts#L23)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove dead code
</blockquote></details>

Done.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/export/export-modal-button.tsx` line 31 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1797#-NqdQbbK1ejzol-w3HQ-:-NqdS7I5COJvQhdiWHgo:bnsdiv6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/27e292f0dedbe3b20429ad3060a261f0671e78c1/packages/geoview-core/src/core/components/export/export-modal-button.tsx#L31)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We do not use theme...geoviewColor.primary?
</blockquote></details>

reply above

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/notifications/notifications.tsx` line 103 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1797#-NqdQjdS2LewypD_nd5P:-NqdjXELEjMqrUZ0nNZs:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/27e292f0dedbe3b20429ad3060a261f0671e78c1/packages/geoview-core/src/core/components/notifications/notifications.tsx#L103)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We do not use theme...geoviewColor.primary?
</blockquote></details>

Done.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/ui/style/themeOptionsGenerator.ts` line 63 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1797#-NqdQoUu8_i6MEJTeG2i:-NqdjZup9YK-fNV_fwrG:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/27e292f0dedbe3b20429ad3060a261f0671e78c1/packages/geoview-core/src/ui/style/themeOptionsGenerator.ts#L63)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we need dead code here and below?
</blockquote></details>

Done.

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1797)* status: 13 of 22 files reviewed, 7 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 447 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1797#-NqdQUVrBuB7hYgcbY81:-NqdSAYU49bzaep049fG:bbkri1f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/27e292f0dedbe3b20429ad3060a261f0671e78c1/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L447)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We do not use theme...geoviewColor.primary?
</blockquote></details>

setting color="primary"

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 17 files at r2, 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1797)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
