### PR TITLE
1913-Remove_layerPhase_property

### LINKED ISSUE #1913: Remove layerPhase property
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

Since the creation of the logger, the layerPhase property is no longer usefull.

### Implementation

Remove the layerPhase property from the viewer code.

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

Remove layerPhase property from the entire viewer code.

Fixes #1913-Remove_layerPhase_property

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using Chrome Devtools.

__Deploy URL__: https://ychoquet.github.io/GeoView/index.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1916)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 18 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1916)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @ychoquet)

___
*[`packages/geoview-core/src/core/utils/config/validation-classes/abstract-base-layer-entry-config.ts` line 81 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1916#-Nsm_JwfBCtO5facJa2W:-Nsm_JwfBCtO5facJa2X:b43ph0i) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d464a263453a0197fa7a3a0ff96be32dbc97f843/packages/geoview-core/src/core/utils/config/validation-classes/abstract-base-layer-entry-config.ts#L81)):*
> ```XML
>         const loadEndListener = () => {
>           this.loadedFunction();
>           this.layerStatus = 'loaded';
> ```

Is this still kind of a function behind the scene so when set it does thing? If so we need a TODO: refactor to say it needs to change to a real function

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1916)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/utils/config/validation-classes/abstract-base-layer-entry-config.ts` line 81 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1916#-Nsm_JwfBCtO5facJa2W:-NsmrWcLAiv6JqmNzl5X:b-m3ntxw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d464a263453a0197fa7a3a0ff96be32dbc97f843/packages/geoview-core/src/core/utils/config/validation-classes/abstract-base-layer-entry-config.ts#L81)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this still kind of a function behind the scene so when set it does thing? If so we need a TODO: refactor to say it needs to change to a real function
</blockquote></details>

The Setter and Getter functions will be replaced by a public method acting on a private property to make it clear that additional work is being done at the same time as we set the property. However, separating the listening functions is not a good idea. This merging of olLayer assignment and listener creation has been done to avoid developers spreading listeners all over the code as was done before. 
The existence of listener functions is intimately linked to the olLayer. The setters/getters will be redefined when we separate the validation and instantiation of the layers. In the meantime, I've put a TODO to mark our intention to do so.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1916)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1916)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
