### PR TITLE
1154 - implement hightlight feature

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Implement highlight feature on map when any row is selected in data table.

Fixes # ([1154](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1154))

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
1) Open the url listed below.
2) Click on `Create data table from Map` button
3) Select any row from data table 
4) Highlight feature will be displayed on the map.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/raw-data-table.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1265)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1265)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/data-table/json-export-button.tsx` line 33 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1265#-NdaVcvO85QIRhN7ohGJ:-NdaVcvP3rza5UIQDS-V:b-ofwv2b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a013be45de6656b25a20e6f8f5c5fead2f90492a/packages/geoview-core/src/core/components/data-table/json-export-button.tsx#L33)):*
> ```XML
>    */
>   const buildGeometry = (geometry: Geometry) => {
>     if (geometry instanceof Polygon) {
> ```

Why not using if then else to set return and only return at the end of the function?

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1265)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/data-table/json-export-button.tsx` line 33 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1265#-NdaVcvO85QIRhN7ohGJ:-NdabWqh06ff9xPve8Fn:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a013be45de6656b25a20e6f8f5c5fead2f90492a/packages/geoview-core/src/core/components/data-table/json-export-button.tsx#L33)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why not using if then else to set return and only return at the end of the function?
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1265)* status: 1 of 3 files reviewed, all discussions resolved

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1265)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Pull request merged**
