### PR TITLE
feat(sample-pages) Create basemap page

### LINKED ISSUE #80: Sample Basemap
Create the basemap sample page. Look #7

### PR DESCRIPTION
**Pull request by melzeiny1980**
Closes #80

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[public/index.html, line 32 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85#-MTlqgyKBxAK0WAozQNv:-MTlqgyKBxAK0WAozQNw:b-6o0051) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ca9490cdb05b532c84d7d5c3b5c307c0a500ecf2/public/index.html#L32)):*
> ```HTML
>                     </tr>
>                     <tr>
>                         <h1 class="center"><strong>Plateforme Géospatiale Canadienne (PGC1)</strong></h1>
> ```

Remove the 1
___
*[public/templates/basemaps.html, line 3 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85#-MTlr4AsCAg4ScqdFwOc:-MTlr4At0JQEnNpUk-5L:bb8h9fe) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ca9490cdb05b532c84d7d5c3b5c307c0a500ecf2/public/templates/basemaps.html#L3)):*
> ```HTML
> <!DOCTYPE html>
> <html lang="en">
>     <head>
> ```

Can you put all map in English, update description, we will have a page to show case French and English. Anywhere else put English
___
*[public/templates/basemaps.html, line 115 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85#-MTlq6T1-4PNpJOVSfTZ:-MTlq6T1-4PNpJOVSfT_:bv00a3k) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ca9490cdb05b532c84d7d5c3b5c307c0a500ecf2/public/templates/basemaps.html#L115)):*
> ```HTML
>                 id="BM2"
>                 class="llwp-map"
>                 data-leaflet="{'name': 'Web Mercator', 'projection': 3978, 'zoom': 4, 'center': [60,-100], 'language': 'en-CA', 'basemapOptions': { 'id': 'simple', 'shaded': false, 'labeled': false } ,
> ```

Can you put labeled: true
___
*[public/templates/basemaps.html, line 118 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85#-MTlqEIz6Rlw25-jewnF:-MTlqEIz6Rlw25-jewnG:b1oj4bo) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ca9490cdb05b532c84d7d5c3b5c307c0a500ecf2/public/templates/basemaps.html#L118)):*
> ```HTML
>             'layers':[]}"
>             ></div>
>             <p>This map is in LLC projection with Simple basemap, with shaded background and no labeling</p>
> ```

Change description, shaded false and label true
___
*[public/templates/basemaps.html, line 139 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85#-MTlqQO1CIN7dOeIQPWh:-MTlqQO1CIN7dOeIQPWi:bkf06xf) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ca9490cdb05b532c84d7d5c3b5c307c0a500ecf2/public/templates/basemaps.html#L139)):*
> ```HTML
>             cgpv.init(function () {
>                 console.log('api is ready');
>                 // inject cofiguration snippet insdie panel
> ```

Typo inside

**Review by melzeiny1980 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[public/index.html, line 32 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85#-MTlqgyKBxAK0WAozQNv:-MTltYtzCUuyHVJHIagm:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ca9490cdb05b532c84d7d5c3b5c307c0a500ecf2/public/index.html#L32)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove the 1
</blockquote></details>

Done.
___
*[public/templates/basemaps.html, line 115 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85#-MTlq6T1-4PNpJOVSfTZ:-MTltZEK3BanmUhpAclb:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ca9490cdb05b532c84d7d5c3b5c307c0a500ecf2/public/templates/basemaps.html#L115)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put labeled: true
</blockquote></details>

Done.
___
*[public/templates/basemaps.html, line 118 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85#-MTlqEIz6Rlw25-jewnF:-MTltZf2DO39-2kmWZuf:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ca9490cdb05b532c84d7d5c3b5c307c0a500ecf2/public/templates/basemaps.html#L118)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Change description, shaded false and label true
</blockquote></details>

Done.
___
*[public/templates/basemaps.html, line 139 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85#-MTlqQO1CIN7dOeIQPWh:-MTlt_6e00849TnzAY45:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ca9490cdb05b532c84d7d5c3b5c307c0a500ecf2/public/templates/basemaps.html#L139)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo inside
</blockquote></details>

Done.

**Review by melzeiny1980 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[public/templates/basemaps.html, line 3 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85#-MTlr4AsCAg4ScqdFwOc:-MTltbPS-u62qMEpNpDM:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ca9490cdb05b532c84d7d5c3b5c307c0a500ecf2/public/templates/basemaps.html#L3)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put all map in English, update description, we will have a page to show case French and English. Anywhere else put English
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[public/index.html, line 32 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85#-MTlqgyKBxAK0WAozQNv:-MTlzi-J6ybrG0Pdq9JW:b6vj59v) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ca9490cdb05b532c84d7d5c3b5c307c0a500ecf2/public/index.html#L32)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Weird, I can still the 1 in reviewable and in your branch: https://github.com/melzeiny1980/GeoView/blob/80-Sample-Basemap/public/index.html. 
___
*[public/templates/basemaps.html, line 3 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85#-MTlr4AsCAg4ScqdFwOc:-MTp7pie3JhqN_16nbtJ:bu55npc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ca9490cdb05b532c84d7d5c3b5c307c0a500ecf2/public/templates/basemaps.html#L3)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done, Shaded still in Franch
___
*[public/templates/basemaps.html, line 118 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85#-MTp7x0917j5wruAn46C:-MTp7x0917j5wruAn46D:b-8t8p4h) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/663d438b87190e1deb82377ece9166a18a9ec570/public/templates/basemaps.html#L118)):*
> ```HTML
>             'layers':[]}"
>             ></div>
>             <p>This map is in LLC projection with Simple basemap, with shaded background and labeling</p>
> ```

The background is not shaded, please update

**Review by melzeiny1980 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[public/templates/basemaps.html, line 118 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85#-MTp7x0917j5wruAn46C:-MTpotgu3huK3nXkK-hi:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/663d438b87190e1deb82377ece9166a18a9ec570/public/templates/basemaps.html#L118)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The background is not shaded, please update
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @melzeiny1980 and @yass0016)

___
*[public/templates/basemaps.html, line 118 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85#-MTp7x0917j5wruAn46C:-MTpwHXF0gJIYywuXeKU:bcjweqt) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/663d438b87190e1deb82377ece9166a18a9ec570/public/templates/basemaps.html#L118)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why did you changed the basemap settings. shaded was false (ok) but description was wrong. The comment was on description line, not config. You need to apply the comment at the right place.

**Comment by melzeiny1980** [comment]
___
*[public/templates/basemaps.html, line 118 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85#-MTp7x0917j5wruAn46C:-MTpxzCA-dmxQfY4JF9B:b2znnn3) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/663d438b87190e1deb82377ece9166a18a9ec570/public/templates/basemaps.html#L118)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why did you changed the basemap settings. shaded was false (ok) but description was wrong. The comment was on description line, not config. You need to apply the comment at the right place.
</blockquote></details>

i misunderstood , sorry

**Review by jolevesq — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85#-:-MTpz9mX9HcQJ0OCsOJx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yass0016)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yass0016)

**Pull request merged**
