### PR TITLE
Cleaning up imports paths

### LINKED ISSUE #1961: [BUG] Further Improvements To Imports
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- [ ] Remove all `../` imports, replace with use of `@/...`.
- [ ] Remove all imports from `@/core/types/cgpv-types`.
- [ ] In `@/core/types/cgpv-types` remove all the references index. Copy them to this file and delete - so we can one file for external.
- [ ] Remove cyclic imports were necessary.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

This PR cleans up imports across our files.
* Removes imports that start with '../'
* Removes imports to index files that dont need to be there.
* Remove imports from `@/core/types/cgpv-types`;

Fixes #1961 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://cphelefu.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1962)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 81 of 87 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1962)* status: 81 of 87 files reviewed, 3 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1962#-Ntq7in9DKcBeRi-zF1V:-Ntq7inA4oFfn_FLUU2T:bx8wswd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/000c4eb59cae44c839351f938bd30a41cd72e5a2/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L1)):*
> ```XML
> import {} from '@/geo'; // TODO what is causing an error when removing this import?
> ```

You have not found the problem with import?
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 12 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1962#-Ntq7qds2QbaNuovxddS:-Ntq7qds2QbaNuovxddT:by28q0z) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/000c4eb59cae44c839351f938bd30a41cd72e5a2/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L12)):*
> ```XML
> } from '@/geo/layer/geoview-layers/abstract-geoview-layers';
> import { TypeLegendResultSetEntry } from '@/geo/utils/legends-layer-set';
> import { api, getLocalizedValue, ILayerState } from '@/app';
> ```

getLoca... LayerState, I do not think they are on app
___
*[`packages/geoview-core/src/api/plugin/appbar-plugin.ts` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1962#-Ntq8xGt2aRPrN0yP6Mg:-Ntq8xGt2aRPrN0yP6Mh:b7zje5y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/000c4eb59cae44c839351f938bd30a41cd72e5a2/packages/geoview-core/src/api/plugin/appbar-plugin.ts#L1)):*
> ```XML
> import { TypeButtonPanel, TypeIconButtonProps, TypePanelProps } from '@/ui';
> ```

We should use the proper place in ui '@/ui/panel/panel-types', same for button

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/api/plugin/appbar-plugin.ts` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1962#-Ntq8xGt2aRPrN0yP6Mg:-NtqlHuK3D_mMq8PbkNT:b-36y2vf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/000c4eb59cae44c839351f938bd30a41cd72e5a2/packages/geoview-core/src/api/plugin/appbar-plugin.ts#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should use the proper place in ui '@/ui/panel/panel-types', same for button
</blockquote></details>

Fixed this one.. but their are lots of places in the code where we are importing from '@/ui'. didnt change them. I think we should leave for UI stuff.. but am okay to change it if you insist

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1962)* status: 79 of 90 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1962#-Ntq7in9DKcBeRi-zF1V:-Ntql9TECpBYBaKbNZAC:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/000c4eb59cae44c839351f938bd30a41cd72e5a2/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You have not found the problem with import?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 12 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1962#-Ntq7qds2QbaNuovxddS:-NtqlAqm4Jr2X1ctuAYa:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/000c4eb59cae44c839351f938bd30a41cd72e5a2/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L12)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

getLoca... LayerState, I do not think they are on app
</blockquote></details>

Done.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/app.tsx` line 14 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1962#-NtrCU8qA09As4bTJV63:-NtrEPwA2ZFb_wflvGfh:b-xvox1o) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a9736bbef7a4a7c0b9c27e2b3dbc1b58ceae8ede/packages/geoview-core/src/app.tsx#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we do this, this is a whole re import of everything?
</blockquote></details>

Yes, almost removed it.. but its used in line 243 to make the `cgpv` object.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/types/global-types.ts` line 13 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1962#-NtrDPJ06Dk_fE8zwJJS:-NtrFhxEB7RjwR3pCvTr:bdmiij7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a9736bbef7a4a7c0b9c27e2b3dbc1b58ceae8ede/packages/geoview-core/src/core/types/global-types.ts#L13)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This export, we need it?
</blockquote></details>

oh yes. this is another landmine!  Removing it causes things to explode. I will fix this in my next PR. Already investigating it.

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1962)* status: 93 of 95 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/api.ts` line 16 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1962#-NtrCqWZ18Oz5mDKo4I9:-NtrFF7a4A8w6ZXYiP-X:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a9736bbef7a4a7c0b9c27e2b3dbc1b58ceae8ede/packages/geoview-core/src/api/api.ts#L16)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should not use import from external-type in our repo... this thing is in app.tsx. If it needs to be typed somewhere global, we can use global types.ts
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 11 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1962)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
