### PR TITLE
refactor(visibility): layer visibility moved out of legend

### LINKED ISSUE #1289: [BUG] Layer disappears
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we load the footer page sample, the water quality layer appears and then few seconds later it disappears. Plus when we set visibility from the eye icon, it is not working anymore. The layer remember the the state of class visibility. So when they are all off, turning visibility on/off does nothing.

### Expected Behavior

When visibility is no, it should not appear at all and the set visibility icon should work. If they are off they should be all toggle on.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by DamonU2**
# Description

Moves initial visibility handling out of legend to be completely handled at layer creation. Also changes feature visibility handling from legend menus to more expected behaviour.

Fixes #1289 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested with old legend in package-footer-panel.html and new version in raw-legend-2.html

https://damonu2.github.io/geoview/raw-legend-2.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1414)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1414)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 678 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1414#-Nh85qsW14PysgtC1xNT:-Nh85qsW14PysgtC1xNU:b-n2qnyt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0f2a7e18510e3f775ccdb0ca2879686408b08430/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L678)):*
> ```XML
>             if (baseLayer) {
>               baseLayer.setVisible(
>                 listOfLayerEntryConfig[0].initialSettings?.visible === 'yes' ||
> ```

I had a question for Yves about the hardcoded 0 index.... this will not let the function access the second entry of the list? What would happen?

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1414)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 678 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1414#-Nh85qsW14PysgtC1xNT:-Nh86skW-F4gElWuerWZ:b-s2u7p1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0f2a7e18510e3f775ccdb0ca2879686408b08430/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L678)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I had a question for Yves about the hardcoded 0 index.... this will not let the function access the second entry of the list? What would happen?
</blockquote></details>

In this case there is only one layer entry - line 639: if (listOfLayerEntryConfig.length === 1) multiple entries are handled below

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 678 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1414#-Nh85qsW14PysgtC1xNT:-Nh87UUb8qeXB4TCiX9w:b5feuwg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0f2a7e18510e3f775ccdb0ca2879686408b08430/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L678)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

In this case there is only one layer entry - line 639: if (listOfLayerEntryConfig.length === 1) multiple entries are handled below
</blockquote></details>

Here we can just use `...visible !== 'no'`

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1414)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
