### PR TITLE
863 file load

### LINKED ISSUE #863: [FEATURE] Load file from layers panel add layer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

As a user, I would like to load local file from my computer (GeoJSON, Geopackages) in the viewer.

### Implementation UI

In the layers panel, add a choice to drag and drop a file (plus open file explorer) or add a url and allowed file url.

Sample
image

If the UI implementation misses important back end development, please create issue.

### PR DESCRIPTION
**Pull request by DamonU2**
# Description

Added file uploading to layer step with file browser and drag and drop.

Fixes #863 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested english/French, drag and drop .gpkg and .geojson, load .gpkg and .geojson. Dragged non-supported files, upload with .json that was not geojson.

# Checklist:

- [X] I have connected the issues(s) to this PR
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/923)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
Name in third step of add layer should be the file name

> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/923#-:-NP3PdkuDo71zIOtI1t1:bda22ll)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-layers-panel/src/layer-stepper.tsx` line 96 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/923#-NP3OqIU11aqRwQ37oiS:-NP3OqIU11aqRwQ37oiT:b-o216yj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3bf00ee7b2386155c48e42e39421d5ec09d25502/packages/geoview-layers-panel/src/layer-stepper.tsx#L96)):*
> ```XML
>    * Translations object to inject to the viewer translations
>    */
>   const translations = {
> ```

Good catch with the translation not being done
___
*[`packages/geoview-layers-panel/src/layer-stepper.tsx` line 192 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/923#-NP3Ne4n1kWMGbY9OQ7Z:-NP3Ne4n1kWMGbY9OQ7_:b-h3gr6b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3bf00ee7b2386155c48e42e39421d5ec09d25502/packages/geoview-layers-panel/src/layer-stepper.tsx#L192)):*
> ```XML
>       snackbarMessagePayload(api.eventNames.SNACKBAR.EVENT_SNACKBAR_OPEN, mapId, {
>         type: 'string',
>         value: `Only geoJSON and GeoPackage files can be used`,
> ```

Use translation object for the message. Needs to be English or French

**Review by DamonU2 — COMMENTED** [review]
Done!

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/923#-:-NP3leniE05gZtIe3f5i:b-896fja)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-layers-panel/src/layer-stepper.tsx` line 192 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/923#-NP3Ne4n1kWMGbY9OQ7Z:-NP3lk2556i7TKgss-5q:bs7ezcv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3bf00ee7b2386155c48e42e39421d5ec09d25502/packages/geoview-layers-panel/src/layer-stepper.tsx#L192)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use translation object for the message. Needs to be English or French
</blockquote></details>

Done! Also added translations for the other error messages, please take a close look at the French and how it fits together in the multiple part ones. I am not at all confident with my French or DeepL.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/923)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2)

___
*[`packages/geoview-layers-panel/src/layer-stepper.tsx` line 192 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/923#-NP3Ne4n1kWMGbY9OQ7Z:-NP42ip0CupaGVJy_J6l:b-1kzvj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3bf00ee7b2386155c48e42e39421d5ec09d25502/packages/geoview-layers-panel/src/layer-stepper.tsx#L192)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Done! Also added translations for the other error messages, please take a close look at the French and how it fits together in the multiple part ones. I am not at all confident with my French or DeepL.
</blockquote></details>

That is good, it will need to be translated for real before prod

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/923)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/923)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
