### PR TITLE
feat(UI): Initial UI updates for the app bar

### PR DESCRIPTION
**Pull request by kenchase**
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466)

### CODE REVIEW

**Review by yass0016 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466)* status: all files reviewed, 4 unresolved discussions (waiting on @kenchase)

___
*[`packages/geoview-core/src/core/components/appbar/app-bar.tsx` line 5 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N3f6-bB3y8nH9t6suOY:-N3f6-bCDK1R_nibp9lP:bcq47g2) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/a84c81b5b74e3e9e5bb7452bc560880a37152b9d/packages/geoview-core/src/core/components/appbar/app-bar.tsx#L5)):*
> ```XML
> import makeStyles from '@mui/styles/makeStyles';
> 
> import DetailsIcon from '@mui/icons-material/Details';
> ```

Can you move these to 

https://github.com/Canadian-Geospatial-Platform/GeoView/blob/4c03c19dab3a996e5f9354e9d4bc755dc0e97614/packages/geoview-core/src/ui/icons/index.ts#L1

And export them from that file, then they can be imported from ui instead like the other icons.
___
*[`packages/geoview-core/src/core/components/appbar/app-bar.tsx` line 170 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N3f6YzY7tldUp8Sj-pe:-N3f6YzY7tldUp8Sj-pf:b-58wb13) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/a84c81b5b74e3e9e5bb7452bc560880a37152b9d/packages/geoview-core/src/core/components/appbar/app-bar.tsx#L170)):*
> ```XML
>                   let iconMod;
> 
>                   // TODO -  KenChase - Where's the best place to place the icon values?
> ```

For these actually they need to be on the packages themselves. So instead of importing them in this file and using them like this, when creating the panel, and button 

https://github.com/Canadian-Geospatial-Platform/GeoView/blob/4c03c19dab3a996e5f9354e9d4bc755dc0e97614/packages/geoview-details-panel/src/index.tsx#L68

you pass the icon there and then in here you can acces it like
buttonPanel.button.icon instead of {iconMod}
___
*[`packages/geoview-core/src/ui/list/list-item.tsx` line 6 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N3f8QXL5FsByrp9IsaW:-N3f8QXL5FsByrp9IsaX:bg1wuht) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/a84c81b5b74e3e9e5bb7452bc560880a37152b9d/packages/geoview-core/src/ui/list/list-item.tsx#L6)):*
> ```XML
> import { TypeListItemProps } from '../../core/types/cgpv-types';
> 
> // TODO - KenChase - remove useStyles from here? This is too global. need to apply styling at a more specific levels. '//
> ```

This is the default list item style if a user does not pass their styling so we probably need this. If a user pass the prop className or style, it should override the default styling.
___
*[`packages/geoview-core/src/ui/style/theme.tsx` line 4 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N3f8pz43IQSUK56Qrx7:-N3f8pz43IQSUK56Qrx8:bk2byng) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/a84c81b5b74e3e9e5bb7452bc560880a37152b9d/packages/geoview-core/src/ui/style/theme.tsx#L4)):*
> ```XML
> 
> // needed for TypeScript when customizing a theme
> declare module '@mui/material/styles' {
> ```

Should we move the declare to here since we already declaring material ui elements?

https://github.com/Canadian-Geospatial-Platform/GeoView/blob/4c03c19dab3a996e5f9354e9d4bc755dc0e97614/packages/geoview-core/src/core/types/material-ui.d.ts#L12

**Review by yass0016 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466)* status: all files reviewed, 4 unresolved discussions (waiting on @kenchase)

___
*[`packages/geoview-core/src/core/components/appbar/app-bar.tsx` line 170 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N3f6YzY7tldUp8Sj-pe:-N3f9j1a-mjOhwrhbCSx:bqi9xdx) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/a84c81b5b74e3e9e5bb7452bc560880a37152b9d/packages/geoview-core/src/core/components/appbar/app-bar.tsx#L170)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

For these actually they need to be on the packages themselves. So instead of importing them in this file and using them like this, when creating the panel, and button 

https://github.com/Canadian-Geospatial-Platform/GeoView/blob/4c03c19dab3a996e5f9354e9d4bc755dc0e97614/packages/geoview-details-panel/src/index.tsx#L68

you pass the icon there and then in here you can acces it like
buttonPanel.button.icon instead of {iconMod}
</blockquote></details>

For example you should be able to access it from the packages side like this
cgpv.ui.elements.DetailsIcon after you export it from the ui/icons/index.ts file

**Review by kenchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @yass0016)

___
*[`packages/geoview-core/src/core/components/appbar/app-bar.tsx` line 5 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N3f6-bB3y8nH9t6suOY:-N3zlaS66hyzZlbp5h8d:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/a84c81b5b74e3e9e5bb7452bc560880a37152b9d/packages/geoview-core/src/core/components/appbar/app-bar.tsx#L5)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Can you move these to 

https://github.com/Canadian-Geospatial-Platform/GeoView/blob/4c03c19dab3a996e5f9354e9d4bc755dc0e97614/packages/geoview-core/src/ui/icons/index.ts#L1

And export them from that file, then they can be imported from ui instead like the other icons.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/appbar/app-bar.tsx` line 170 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N3f6YzY7tldUp8Sj-pe:-N3zltEB3941Kc4lWS9R:bqdiik) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/a84c81b5b74e3e9e5bb7452bc560880a37152b9d/packages/geoview-core/src/core/components/appbar/app-bar.tsx#L170)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

For example you should be able to access it from the packages side like this
cgpv.ui.elements.DetailsIcon after you export it from the ui/icons/index.ts file
</blockquote></details>

This involves a few commits, as well as changes to several files that weren't part of the initial request. I can make further adjustments while working on other UI issues.
___
*[`packages/geoview-core/src/ui/style/theme.tsx` line 4 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N3f8pz43IQSUK56Qrx7:-N3zllD2DniPzg1uv7YT:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/a84c81b5b74e3e9e5bb7452bc560880a37152b9d/packages/geoview-core/src/ui/style/theme.tsx#L4)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Should we move the declare to here since we already declaring material ui elements?

https://github.com/Canadian-Geospatial-Platform/GeoView/blob/4c03c19dab3a996e5f9354e9d4bc755dc0e97614/packages/geoview-core/src/core/types/material-ui.d.ts#L12

</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/list/list-item.tsx` line 6 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N3f8QXL5FsByrp9IsaW:-N3zloH3Dni76PRcbce0:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/a84c81b5b74e3e9e5bb7452bc560880a37152b9d/packages/geoview-core/src/ui/list/list-item.tsx#L6)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

This is the default list item style if a user does not pass their styling so we probably need this. If a user pass the prop className or style, it should override the default styling.
</blockquote></details>

Done.

**Review by yass0016 — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466)* status: all files reviewed, 7 unresolved discussions (waiting on @kenchase and @yass0016)

___
*[`packages/geoview-basemap-panel/src/index.tsx` line 13 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4DyvMl0rgc6RUcOaXy:-N4DyvMl0rgc6RUcOaXz:b-cnp2yl) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/363b96a33e64c20a1b7dcdf8c3112cf8d1e0d615/packages/geoview-basemap-panel/src/index.tsx#L13)):*
> ```XML
>   TypeJsonObject,
> } from 'geoview-core';
> import { MapIcon } from 'geoview-core/src/ui/icons';
> ```

Can you use cgpv.ui.elements.MapIcon from inside the added function below instead? We are trying to avoid accessing sub files from the core this way
___
*[`packages/geoview-basemap-panel/src/index.tsx` line 80 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4DzHm96C2p2Je4NIZu:-N4DzHm96C2p2Je4NIZv:b-4lmxnn) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/363b96a33e64c20a1b7dcdf8c3112cf8d1e0d615/packages/geoview-basemap-panel/src/index.tsx#L80)):*
> ```XML
>         tooltip: this.translations[language].basemapPanel as string,
>         tooltipPlacement: 'right',
>         children: <MapIcon />,
> ```

See my comment above, this can be accessed directly from cgpv.ui.elements
___
*[`packages/geoview-core/src/core/components/navbar/nav-bar.tsx` line 193 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4DzotOEVBYz6g4xJYd:-N4DzotOEVBYz6g4xJYe:b-fqtxr5) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/363b96a33e64c20a1b7dcdf8c3112cf8d1e0d615/packages/geoview-core/src/core/components/navbar/nav-bar.tsx#L193)):*
> ```XML
>                         tooltip={buttonPanel.button.tooltip}
>                         tooltipPlacement="left"
>                         className={classes.navBarButton}
> ```

Don't we need children prop here?
children={buttonPanel.button.children}
___
*[`packages/geoview-core/src/core/components/navbar/nav-bar.tsx` line 201 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4Dzznx2_WXIDIUOD2Z:-N4Dzznx2_WXIDIUOD2_:b-esmw5b) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/363b96a33e64c20a1b7dcdf8c3112cf8d1e0d615/packages/geoview-core/src/core/components/navbar/nav-bar.tsx#L201)):*
> ```XML
>                         id={buttonPanel.button.id}
>                         tooltip={buttonPanel.button.tooltip}
>                         tooltipPlacement="left"
> ```

same for this one, I think you removed the children, no icon would appear, try testing this in the add-panels.html template
___
*[`packages/geoview-details-panel/src/index.tsx` line 12 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4E-nPFABiHelxEAQJZ:-N4E-nPFABiHelxEAQJ_:buzzgk) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/363b96a33e64c20a1b7dcdf8c3112cf8d1e0d615/packages/geoview-details-panel/src/index.tsx#L12)):*
> ```XML
>   TypeWindow,
> } from 'geoview-core';
> import { DetailsIcon } from 'geoview-core/src/ui/icons';
> ```

Same as the basemap panel, you can access this below in the added function from cgpv.ui.elements
___
*[`packages/geoview-layers-panel/src/index.tsx` line 14 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4E-v0-8LhY3vGlkJSb:-N4E-v0-8LhY3vGlkJSc:buzzgk) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/363b96a33e64c20a1b7dcdf8c3112cf8d1e0d615/packages/geoview-layers-panel/src/index.tsx#L14)):*
> ```XML
>   TypeSchemaObject,
> } from 'geoview-core';
> import { LayersOutlinedIcon } from 'geoview-core/src/ui/icons';
> ```

Same as the basemap panel, you can access this below in the added function from cgpv.ui.elements

**Review by kenchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466)* status: 7 of 13 files reviewed, 6 unresolved discussions (waiting on @yass0016)

___
*[`packages/geoview-basemap-panel/src/index.tsx` line 13 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4DyvMl0rgc6RUcOaXy:-N4Y0cZaCDGLYAZcBEA7:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/363b96a33e64c20a1b7dcdf8c3112cf8d1e0d615/packages/geoview-basemap-panel/src/index.tsx#L13)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Can you use cgpv.ui.elements.MapIcon from inside the added function below instead? We are trying to avoid accessing sub files from the core this way
</blockquote></details>

Done.
___
*[`packages/geoview-basemap-panel/src/index.tsx` line 80 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4DzHm96C2p2Je4NIZu:-N4Y0dfjBix13Cnf3Tpr:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/363b96a33e64c20a1b7dcdf8c3112cf8d1e0d615/packages/geoview-basemap-panel/src/index.tsx#L80)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

See my comment above, this can be accessed directly from cgpv.ui.elements
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/navbar/nav-bar.tsx` line 193 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4DzotOEVBYz6g4xJYd:-N4Y0nF02GW3TX4L8PsD:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/363b96a33e64c20a1b7dcdf8c3112cf8d1e0d615/packages/geoview-core/src/core/components/navbar/nav-bar.tsx#L193)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Don't we need children prop here?
children={buttonPanel.button.children}
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/navbar/nav-bar.tsx` line 201 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4Dzznx2_WXIDIUOD2Z:-N4Y0oov2Mxf4YR2wpSd:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/363b96a33e64c20a1b7dcdf8c3112cf8d1e0d615/packages/geoview-core/src/core/components/navbar/nav-bar.tsx#L201)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

same for this one, I think you removed the children, no icon would appear, try testing this in the add-panels.html template
</blockquote></details>

Done.
___
*[`packages/geoview-details-panel/src/index.tsx` line 12 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4E-nPFABiHelxEAQJZ:-N4Y0vq7EuCaDhMIoDiH:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/363b96a33e64c20a1b7dcdf8c3112cf8d1e0d615/packages/geoview-details-panel/src/index.tsx#L12)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Same as the basemap panel, you can access this below in the added function from cgpv.ui.elements
</blockquote></details>

Done.
___
*[`packages/geoview-layers-panel/src/index.tsx` line 14 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4E-v0-8LhY3vGlkJSb:-N4Y0xrdC48lmFeB-KA0:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/363b96a33e64c20a1b7dcdf8c3112cf8d1e0d615/packages/geoview-layers-panel/src/index.tsx#L14)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Same as the basemap panel, you can access this below in the added function from cgpv.ui.elements
</blockquote></details>

Done.

**Review by yass0016 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466)* status: 12 of 13 files reviewed, 11 unresolved discussions (waiting on @kenchase and @yass0016)

___
*[`packages/geoview-basemap-panel/src/index.tsx` line 71 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4bY2uC2EsfNALwNc1W:-N4bY2uC2EsfNALwNc1X:b-4twl4o) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d5e70619e67058bf78915b03e0dab367a0bf92fa/packages/geoview-basemap-panel/src/index.tsx#L71)):*
> ```XML
>     if (cgpv) {
>       // access the api calls
>       const { api } = cgpv;
> ```

const {api, ui} = cgpv;
___
*[`packages/geoview-basemap-panel/src/index.tsx` line 73 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4bXyWc6kQs1Obtlj0b:-N4bXyWc6kQs1Obtlj0c:b-ye84im) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d5e70619e67058bf78915b03e0dab367a0bf92fa/packages/geoview-basemap-panel/src/index.tsx#L73)):*
> ```XML
>       const { api } = cgpv;
>       const { language } = api.map(mapId);
> ```

const { MapIcon } = ui.elements;
___
*[`packages/geoview-basemap-panel/src/index.tsx` line 79 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4bYEbFCfxu5tf43pRT:-N4bYEbFCfxu5tf43pRU:b-7ksjes) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d5e70619e67058bf78915b03e0dab367a0bf92fa/packages/geoview-basemap-panel/src/index.tsx#L79)):*
> ```XML
>         tooltip: this.translations[language].basemapPanel as string,
>         tooltipPlacement: 'right',
>         children: cgpv.react.createElement(cgpv.ui.elements.MapIcon),
> ```

Since you are writing the code in JSX you don't need to use createElement. Can you try this?
children: <MapIcon />,
For add-panel.html its the right thing to use createElement because its vanilla HTML it does not accept JSX but for jsx/tsx you can simply pass it as a component, if it doesn't work try without the <> like this
children: MapIcon,
___
*[`packages/geoview-details-panel/src/index.tsx` line 67 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4bZFFYDgLhiCsjl4lZ:-N4bZFFYDgLhiCsjl4l_:b-hv9vgy) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d5e70619e67058bf78915b03e0dab367a0bf92fa/packages/geoview-details-panel/src/index.tsx#L67)):*
> ```XML
>       tooltip: this.translations[language].detailsPanel as string,
>       tooltipPlacement: 'right',
>       children: cgpv.react.createElement(cgpv.ui.elements.DetailsIcon),
> ```

Same as the other one
___
*[`packages/geoview-layers-panel/src/index.tsx` line 81 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4bZIIv6yfpgcDuIsa3:-N4bZIIv6yfpgcDuIsa4:bqujbyh) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d5e70619e67058bf78915b03e0dab367a0bf92fa/packages/geoview-layers-panel/src/index.tsx#L81)):*
> ```XML
>       tooltip: this.translations[language].layersPanel as string,
>       tooltipPlacement: 'right',
>       children: cgpv.react.createElement(cgpv.ui.elements.LayersOutlinedIcon),
> ```

Here too

**Review by kenchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466)* status: 10 of 13 files reviewed, 11 unresolved discussions (waiting on @yass0016)

___
*[`packages/geoview-basemap-panel/src/index.tsx` line 71 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4bY2uC2EsfNALwNc1W:-N4cZ7FG8JtcpvVcwJcx:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d5e70619e67058bf78915b03e0dab367a0bf92fa/packages/geoview-basemap-panel/src/index.tsx#L71)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

const {api, ui} = cgpv;
</blockquote></details>

Done.
___
*[`packages/geoview-basemap-panel/src/index.tsx` line 73 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4bXyWc6kQs1Obtlj0b:-N4cZ7ha86bdMs39D5xO:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d5e70619e67058bf78915b03e0dab367a0bf92fa/packages/geoview-basemap-panel/src/index.tsx#L73)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

const { MapIcon } = ui.elements;
</blockquote></details>

Done.
___
*[`packages/geoview-basemap-panel/src/index.tsx` line 79 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4bYEbFCfxu5tf43pRT:-N4cZ9M38_F5pnTN_QNl:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d5e70619e67058bf78915b03e0dab367a0bf92fa/packages/geoview-basemap-panel/src/index.tsx#L79)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Since you are writing the code in JSX you don't need to use createElement. Can you try this?
children: <MapIcon />,
For add-panel.html its the right thing to use createElement because its vanilla HTML it does not accept JSX but for jsx/tsx you can simply pass it as a component, if it doesn't work try without the <> like this
children: MapIcon,
</blockquote></details>

Done.
___
*[`packages/geoview-details-panel/src/index.tsx` line 67 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4bZFFYDgLhiCsjl4lZ:-N4cZEQ27qSedS-XCW-J:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d5e70619e67058bf78915b03e0dab367a0bf92fa/packages/geoview-details-panel/src/index.tsx#L67)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Same as the other one
</blockquote></details>

Done.
___
*[`packages/geoview-layers-panel/src/index.tsx` line 81 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466#-N4bZIIv6yfpgcDuIsa3:-N4cZGpj7irb_saWJjAM:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d5e70619e67058bf78915b03e0dab367a0bf92fa/packages/geoview-layers-panel/src/index.tsx#L81)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Here too
</blockquote></details>

Done.

**Review by yass0016 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/466)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kenchase)

**Pull request merged**
