### PR TITLE
refactor(layers) - Part 2

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

This PR is part of a series of PR and has a dependency on PR: https://github.com/Canadian-Geospatial-Platform/geoview/pull/1941

This particular one focuses on work surrounding layer querying and layer-sets. _Lots more to come in upcoming PRs on this._

- Removed the `QUERY_LAYER`, `QUERY_ALL_FEATURES`, `ALL_QUERIES_DONE` and  `QUERY_RESULT` generic events;
- Removed the `ALL_QUERIES_DONE` handlers in the templates. Some code left in comment in the template on purpose for upcoming PRs;
- Commented the code about ALL_QUERIES_DONE in hover-tooltip as agreed with Johann in meeting;
- Started removing some generic events registrations from abstract-geoview-layers class. In this PR, removed `queryLayer`;
- Started work on the LayerApi and its layer-data-sets, now referred to as the 'orchestrator' as discussed in a previous meeting;
- The layer-set now receives the LayerApi in the constructor, instead of having to refetch it via the api.maps[mapId] all the time;
- The layer-set now has a reusable function to query layers for the children classes to use;
- Cleaned up the generic events from all layers-sets as they don't need to listen on themselves or ping-pong with abstract-geoview-layer anymore.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Currently hosting the finally of the layers refactoring here: https://alex-nrcan.github.io/geoview

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 48 of 76 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942)* status: 48 of 76 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/geo/utils/all-feature-info-layer-set.ts` line 144 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942#-NtNBtZY5UlaI5ZnQKdS:-NtNBtZY5UlaI5ZnQKdT:bhqxcop) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/20a28cc194aff7494f067d35da800dd85a0994e1/packages/geoview-core/src/geo/utils/all-feature-info-layer-set.ts#L144)):*
> ```XML
> 
>       // Query and event types of what we're doing
>       const eventType = 'all-features';
> ```

Is it still an event, not only a direct call?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 76 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942)* status: 49 of 76 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/geo/utils/hover-feature-info-layer-set.ts` line 4 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942#-NtNDBX7CTS-Qf88nYMn:-NtNDBX7CTS-Qf88nYMo:b14j7qf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/20a28cc194aff7494f067d35da800dd85a0994e1/packages/geoview-core/src/geo/utils/hover-feature-info-layer-set.ts#L4)):*
> ```XML
> 
> import Feature from 'ol/Feature';
> import { Coordinate } from 'ol/coordinate';
> ```

This whole file can be remove when we finish the hover refactor to the store and we have the function to get info direct on the layer

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942)* status: 49 of 76 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 227 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942#-NtNDgNiBGksvWUFldjb:-NtNDgNiBGksvWUFldjc:bt9lqj9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/20a28cc194aff7494f067d35da800dd85a0994e1/packages/geoview-core/src/geo/utils/layer-set.ts#L227)):*
> ```XML
> }
> 
> export type EventType = 'click' | 'hover' | 'crosshaire-enter' | 'all-features';
> ```

I dont know if it is in this refactor but many of the query stuff should be direct call in my mind

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 59 of 76 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942)* status: 51 of 76 files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/public/templates/layers/esri-feature.html` line 520 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942#-NtN07ZU5WUMAJoX3kDy:-NtN07ZU5WUMAJoX3kDz:bzbs8dr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a44de480f225dbea1961655f7f44be75c1e1e2b8/packages/geoview-core/public/templates/layers/esri-feature.html#L520)):*
> ```HTML
>       //   },
>       //   'LYR3/click/FeatureInfoLayerSet'
>       // );
> ```

If it is obsolete, do we have to keep dead code or it will be reused in the upcoming PR. If not, we should delete the dead code.



_Code quote:_
```HTML
      // Note: ALL_QUERIES_DONE is obsolete, a replacement is coming (upcoming PR)
      // cgpv.api.event.on(
      //   cgpv.api.eventNames.GET_FEATURE_INFO.ALL_QUERIES_DONE,
      //   (payload) => {
      //     const { layerSetId, resultSet, eventType } = payload;
      //     createInfoTable('LYR3', 'ResultSetId3', resultSet, eventType);
      //   },
      //   'LYR3/click/FeatureInfoLayerSet'
      // );
```
___
*[`packages/geoview-core/src/geo/utils/feature-info-layer-set.ts` line 125 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942#-NtNDXos0-tmdmIrsBqk:-NtNDXos0-tmdmIrsBql:b9umym2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/20a28cc194aff7494f067d35da800dd85a0994e1/packages/geoview-core/src/geo/utils/feature-info-layer-set.ts#L125)):*
> ```XML
>     // TODO: REFACTOR - Watch out for code reentrancy between queries!
>     // ! Each query should be distinct as far as the resultSet goes! The 'reinitialization' below isn't sufficient.
>     // ! As it is (and was like this befor events refactor), the this.resultSet is mutating between async calls.
> ```

Can we use a semaphore to prevent reentrance?



_Code quote:_
```XML
    // TODO: REFACTOR - Watch out for code reentrancy between queries!
    // ! Each query should be distinct as far as the resultSet goes! The 'reinitialization' below isn't sufficient.
    // ! As it is (and was like this befor events refactor), the this.resultSet is mutating between async calls.
```

**Review by jolevesq — COMMENTED** [review]
> Reviewed 5 of 76 files at r1, 22 of 22 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942)* status: all files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan)

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942)* status: all files reviewed, 5 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/public/templates/layers/esri-feature.html` line 520 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942#-NtN07ZU5WUMAJoX3kDy:-NtNI3r06tkV7mnUmys2:b-foqmj9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a44de480f225dbea1961655f7f44be75c1e1e2b8/packages/geoview-core/public/templates/layers/esri-feature.html#L520)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

If it is obsolete, do we have to keep dead code or it will be reused in the upcoming PR. If not, we should delete the dead code.
</blockquote></details>

I've left it there with the note on purpose and will get cleaned up in subsequent PR, yes
___
*[`packages/geoview-core/src/geo/utils/all-feature-info-layer-set.ts` line 144 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942#-NtNBtZY5UlaI5ZnQKdS:-NtNIIu35pL5gXvS8KPy:bg3p4ay) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/20a28cc194aff7494f067d35da800dd85a0994e1/packages/geoview-core/src/geo/utils/all-feature-info-layer-set.ts#L144)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is it still an event, not only a direct call?
</blockquote></details>

The variable should be renamed yeah. I think they might even totally disappear eventually. I can name the variable in my PR13 if that,s alright
___
*[`packages/geoview-core/src/geo/utils/feature-info-layer-set.ts` line 125 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942#-NtNDXos0-tmdmIrsBqk:-NtNITim2JKn6sUscBkk:b-c6pfe5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/20a28cc194aff7494f067d35da800dd85a0994e1/packages/geoview-core/src/geo/utils/feature-info-layer-set.ts#L125)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Can we use a semaphore to prevent reentrance?
</blockquote></details>

semaphores aren't useful in JavaScript browser development as JavaScript running in browser is single-threaded
___
*[`packages/geoview-core/src/geo/utils/hover-feature-info-layer-set.ts` line 4 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942#-NtNDBX7CTS-Qf88nYMn:-NtNIjTbEvmzc1czACfY:b-vp3gc5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/20a28cc194aff7494f067d35da800dd85a0994e1/packages/geoview-core/src/geo/utils/hover-feature-info-layer-set.ts#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This whole file can be remove when we finish the hover refactor to the store and we have the function to get info direct on the layer
</blockquote></details>

Sounds good, but I've maintained it nonetheless in this PR and the upcoming ones. It still 'basically' works. No objection to remove it later though :thumbsup: 
___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 227 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942#-NtNDgNiBGksvWUFldjb:-NtNIvEZ6zq5uqSD9Nfn:b-eoxe62) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/20a28cc194aff7494f067d35da800dd85a0994e1/packages/geoview-core/src/geo/utils/layer-set.ts#L227)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I dont know if it is in this refactor but many of the query stuff should be direct call in my mind
</blockquote></details>

Yeah, `eventType` should be named and probably just deleted as they much be pretty redundant now (and even more in upcoming PRs). I'll take a look in PR13.

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942)* status: all files reviewed, 5 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/geo/utils/feature-info-layer-set.ts` line 125 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1942#-NtNDXos0-tmdmIrsBqk:-NtNJRdZ8Y-DoKKg20hH:bfywy0o) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/20a28cc194aff7494f067d35da800dd85a0994e1/packages/geoview-core/src/geo/utils/feature-info-layer-set.ts#L125)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

semaphores aren't useful in JavaScript browser development as JavaScript running in browser is single-threaded
</blockquote></details>

but yeah, we can do something in that vein, however we wouldn't want to hold up all the queries before reentrancy... probably want to only 'watch' per layerpath or something

**Pull request merged**
