### PR TITLE
feat(geolocator): fix geolocator filters  #closes2190

### LINKED ISSUE #2190: [BUG] Filters not appearing on geolocator search
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Occasionally the filters do not show up after a geolocator search. Seems to happen when pressing enter triggers search instead of the auto search

### Expected Behavior

Filters should always be there

### Steps To Reproduce

Go to: https://canadian-geospatial-platform.github.io/geoview/public/demos-navigator.html?config=./configs/navigator/06-basic-footer.json
Do a geolocator search and press enter before automatic results show up

### Anything else?

image

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Fix geolocator filters show/hide when keyboard enter is pressed while searching any value in search box.

Fixes #2190 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/demos-navigator.html?config=./configs/navigator/07-basic-appbar.json

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2262)

### CODE REVIEW

**Review by cphelefu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2262#-:-O-M0jq-5DFJv7Cy4bq3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2262)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @cphelefu and @kaminderpal)

___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 57 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2262#-O-a2FfL0tdPX5_oo7vd:-O-a2FfL0tdPX5_oo7ve:btb4ebg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1cb89d6c73a27ec3e1d9e6d9bebacc5d3cf60137/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L57)):*
> ```XML
>   const transformListTitle = useCallback((_title: string, _searchValue: string, province: string): JSX.Element | string => {
>     // Log
>     logger.logTraceUseCallback('GEOLOCATOR - geolist - transformListTitle', _title, _searchValue, province);
> ```

We can keep it, just comment it out with message fired to often. Same for the logger getTooltipTitle...

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2262)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 57 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2262#-O-a2FfL0tdPX5_oo7vd:-O-aIckW53v7b8sY1Qf8:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1cb89d6c73a27ec3e1d9e6d9bebacc5d3cf60137/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L57)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We can keep it, just comment it out with message fired to often. Same for the logger getTooltipTitle...
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2262)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @cphelefu)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2262)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
