### PR TITLE
954-Filter-by-date-(Vector-and-Raster)

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

This PR resolve the date problem related to the vector layers and the esri dynamic layer. The WMS layer will be treated in a separate PR.
Fixes # 954

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

A lot of tracing using the devtools and the type-of-layers template.

# Checklist:

- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 22 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038)* status: 19 of 35 files reviewed, 9 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/public/geojson/polygons.json` line 65 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038#-NURZcAF68A5JLspvgMG:-NURZcAF68A5JLspvgMH:bfo6dhs) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f0ec4a6c8b2660abc29930093b44c0597ba042fd/packages/geoview-core/public/geojson/polygons.json#L65)):*
> ```JSON
>       "properties": {
>         "Province": "Alberta",
>         "creationDate": "02/15/2021T13:00:00"
> ```

This is not ISO date format, you can use it whiteout using the service input format?
___
*[`packages/geoview-core/public/templates/layers/esri-dynamic.html` line 92 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038#-NURc1nP28LHYYzH321u:-NURc1nP28LHYYzH321v:b-ruofii) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f0ec4a6c8b2660abc29930093b44c0597ba042fd/packages/geoview-core/public/templates/layers/esri-dynamic.html#L92)):*
> ```HTML
>                 'geoviewLayerName': { 'en': 'Historical Flood Events (HFE)' },
>                 'serviceDateFormat': 'mm/dd/yyyy',
>                 'outputDateFormat': 'mm/dd/yyyy hh:mm:ss+00:00',
> ```

Can we decide to change the output to real ISO
 date or it should follow the service format?
___
*[`packages/geoview-core/src/core/utils/date-mgt.ts` line 203 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038#-NURd6P9Aaw8V2-kpzmJ:-NURd6P9Aaw8V2-kpzmK:b-acs90h) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f0ec4a6c8b2660abc29930093b44c0597ba042fd/packages/geoview-core/src/core/utils/date-mgt.ts#L203)):*
> ```XML
> 
>     // output as local by default
>     return dayjs(date).utc(false).format(pattern);
> ```

Are we not dealing everything as UTC? Why do we put it false?
___
*[`packages/geoview-core/src/core/utils/date-mgt.ts` line 469 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038#-NURe-j85k5JxQxwABhE:-NURe-j85k5JxQxwABhF:b198zra) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f0ec4a6c8b2660abc29930093b44c0597ba042fd/packages/geoview-core/src/core/utils/date-mgt.ts#L469)):*
> ```XML
>         if (['/', '-', ' ', 'T', '+'].includes(dateFormat[i].toUpperCase())) dateFragmentsOrder[2].push(dateFormat[i]);
>       }
>       if (
> ```

Can you add   come comment to explain the different if statement.
___
*[`packages/geoview-core/src/core/utils/date-mgt.ts` line 480 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038#-NUReoIY99I9JnLv4gjJ:-NUReoIY99I9JnLv4gjK:b-djtmho) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f0ec4a6c8b2660abc29930093b44c0597ba042fd/packages/geoview-core/src/core/utils/date-mgt.ts#L480)):*
> ```XML
>         throw new Error(`The string "${dateFormat}" is an invalid date format.`);
>       const dateTimeFragments = dateFormat.replaceAll(' ', 'T').toUpperCase().split('T');
>       const dateFragments = dateTimeFragments[0].replaceAll('/', '-').toUpperCase().split('-');
> ```

Why are you replacing ISO separator / by -
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 474 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038#-NURnFm_1XsHuvbm_0IU:-NURnFm_1XsHuvbm_0IV:b-cg8x5d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f0ec4a6c8b2660abc29930093b44c0597ba042fd/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L474)):*
> ```XML
>    * @returns {number[]} An array that gives the field order to use to build the query tree.
>    */
>   private sortFieldOfTheSameValue(styleSettings: TypeUniqueValueStyleConfig, fieldOfTheSameValue: TypeFieldOfTheSameValue[][]): number[] {
> ```

This is for internal purpose or it reorder fields in a different way of the service unique value field order?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 576 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038#-NURnhYDDahh46ezCz-S:-NURnhYDDahh46ezCz-T:bv300s7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f0ec4a6c8b2660abc29930093b44c0597ba042fd/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L576)):*
> ```XML
>    * @param {number[]} fieldOrder The field order to use for solving the tree.
>    * @param {TypeUniqueValueStyleConfig} styleSettings The unique value style settings to evaluate.
>    * @param {TypeFeatureInfoLayerConfig} sourceFeatureInfo The source feature informationthat knows the field type.
> ```

Typo spaces informationthat
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 461 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038#-NURpWMO5l7fM6rM5YjJ:-NURpWMO5l7fM6rM5YjK:b-8bzt4e) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f0ec4a6c8b2660abc29930093b44c0597ba042fd/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L461)):*
> ```XML
>    * @param {string | TypeLayerEntryConfig | null} layerPathOrConfig Optional layer path or configuration.
>    */
>   setLayerFilter2(filterValue: string, layerPathOrConfig: string | TypeLayerEntryConfig | null = this.activeLayer) {
> ```

Why function name suffix 2?
___
*[`packages/geoview-core/src/geo/renderer/geoview-renderer.ts` line 1766 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038#-NURqKEI26f_csCo5yqv:-NURqKEI26f_csCo5yqw:b9i0xf3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f0ec4a6c8b2660abc29930093b44c0597ba042fd/packages/geoview-core/src/geo/renderer/geoview-renderer.ts#L1766)):*
> ```XML
>    */
>   analyzeLayerFilter(filterNodeArrayType: FilterNodeArrayType, dateFragmentsOrder: TypeDateFragments): FilterNodeArrayType {
>     /*
> ```

Does comment still needed?

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038)* status: 19 of 35 files reviewed, 8 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/geojson/polygons.json` line 65 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038#-NURZcAF68A5JLspvgMG:-NUSYxqK5NEZc3Hcs7JZ:b-22gg1r) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f0ec4a6c8b2660abc29930093b44c0597ba042fd/packages/geoview-core/public/geojson/polygons.json#L65)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This is not ISO date format, you can use it whiteout using the service input format?
</blockquote></details>

The way the code works internally is:
- if you use a number and:
    - you have not specified a `serviceDateFormat` in the config file, the date is assumed to be a UTC date/time (time zone 00:00 or Z) and is used as is;
    - you have specified a `serviceDateFormat` in the config file, the date will be converted to UTC date/time using the time zone provided in the format when read;
- if you use a string, it will be converted to a number of miliseconds after having done the following conversions:
    - you have not specified a `serviceDateFormat` in the config file, the date is assumed to be a UTC date/time and missing fields are set to their minimum value (MM=01, DD=01, HH:mm:ss=00:00:00 and time zone Z);
    - you have specified a `serviceDateFormat` in the config file, the string must respect the format specified and missing fields are set to their minimum value (MM=01, DD=01, HH:mm:ss=00:00:00 and time zone equal to the one specified in the `serviceDateFormat`) and the date will be converted to UTC date/time using the time zone provided in the format when read;.

In all cases, the final date is stored as a number of miliseconds.
___
*[`packages/geoview-core/public/templates/layers/esri-dynamic.html` line 92 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038#-NURc1nP28LHYYzH321u:-NUShVCH0oM9TYU9MdnR:b-ixdw6c) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f0ec4a6c8b2660abc29930093b44c0597ba042fd/packages/geoview-core/public/templates/layers/esri-dynamic.html#L92)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we decide to change the output to real ISO
 date or it should follow the service format?
</blockquote></details>

For the moment, the configuration must use the same patern otherwise there will be invalid dates error in the console and the layer will not be updated properly. In addition, even if it was possible, it would be confusing for the user. However, it could be done with more analysis and development. Shuld we create an issue for that?
___
*[`packages/geoview-core/src/core/utils/date-mgt.ts` line 203 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038#-NURd6P9Aaw8V2-kpzmJ:-NUSkiXdBQbfcLSwsP19:bcz2lnx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f0ec4a6c8b2660abc29930093b44c0597ba042fd/packages/geoview-core/src/core/utils/date-mgt.ts#L203)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Are we not dealing everything as UTC? Why do we put it false?
</blockquote></details>

We must use false if we want to do the time zone shift.
___
*[`packages/geoview-core/src/core/utils/date-mgt.ts` line 469 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038#-NURe-j85k5JxQxwABhE:-NUT7a-A9qi1DttSl-UK:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f0ec4a6c8b2660abc29930093b44c0597ba042fd/packages/geoview-core/src/core/utils/date-mgt.ts#L469)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add   come comment to explain the different if statement.
</blockquote></details>

Done.



_Code quote:_
```XML
(dateFragmentsOrder[2].length > 3 && !['+', '-'].includes(dateFragmentsOrder[2][3]))
```
___
*[`packages/geoview-core/src/core/utils/date-mgt.ts` line 480 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038#-NUReoIY99I9JnLv4gjJ:-NUT887f7h0vSfJz-AN6:bc7ftlk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f0ec4a6c8b2660abc29930093b44c0597ba042fd/packages/geoview-core/src/core/utils/date-mgt.ts#L480)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why are you replacing ISO separator / by -
</blockquote></details>

[The separator used between date values (year, month, week, and day) is the hyphen, while the colon is used as the separator between time values (hours, minutes, and seconds).](https://en.wikipedia.org/wiki/ISO_8601#:~:text=The%20separator%20used%20between%20date,%2C%20minutes%2C%20and%20seconds).)
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 474 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038#-NURnFm_1XsHuvbm_0IU:-NUTB2SS4-2YGHfGW63v:b8m8046) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f0ec4a6c8b2660abc29930093b44c0597ba042fd/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L474)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This is for internal purpose or it reorder fields in a different way of the service unique value field order?
</blockquote></details>

This is only for internal use. It has no impact on the look and feel of the viewer.



_Code quote:_
```XML
informationthat
```
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 461 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038#-NURpWMO5l7fM6rM5YjJ:-NUTBJkD9acof6bxyxWX:bz5c1br) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f0ec4a6c8b2660abc29930093b44c0597ba042fd/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L461)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why function name suffix 2?
</blockquote></details>

It is dead code. I removed it.
___
*[`packages/geoview-core/src/geo/renderer/geoview-renderer.ts` line 1766 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038#-NURqKEI26f_csCo5yqv:-NUTB_7i-6yqdFx0bP_A:bz5c1br) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f0ec4a6c8b2660abc29930093b44c0597ba042fd/packages/geoview-core/src/geo/renderer/geoview-renderer.ts#L1766)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Does comment still needed?
</blockquote></details>

It is dead code. I removed it.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 6 of 35 files at r1, 2 of 6 files at r2, 3 of 8 files at r3, 1 of 2 files at r5, 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038)* status: 26 of 35 files reviewed, 4 unresolved discussions

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 6 files at r2, 1 of 8 files at r3, 1 of 1 files at r4, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 2 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038)* status: 33 of 35 files reviewed, 1 unresolved discussion

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038)* status: 34 of 35 files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038#-:-NUXGhl-Bur5fwneRITY:bnfp4nl)* status: 34 of 35 files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1038)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
