### PR TITLE
fixes to dark theme in timeslider

### LINKED ISSUE #2084: [BUG] Dark Mode - Some text and icons are not readable
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The windows related to the following tools has not been converted to dark mode. The result is white text on white backdrop, hence invisible text:

- Guide: all detail boxes are white, resulting in text - also white - not readable:
    image
   => Once windows will be dark, watch for black icons which will become hard to see (see 3rd point below).

- Time slider: can't read the time stamps nor the animation time delay: 
   image

- Many icons are black in some menus (Layers, Details, Data Table, etc.), making them are too see:
    image   
image

### Expected Behavior

All boxes and windows should be dark with white text.

Black icons should be converted to white.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

Dark theme is having issues in the guide tab and also in time slider.

Fixes #2084 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://cphelefu.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2130)

### CODE REVIEW

**Review by kaminderpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2130)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/common/responsive-grid.tsx` line 59 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2130#-NxsolPL50DxwjNzpMFx:-NxsolPM8y5hMHB3iXE1:b-xu0fxd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ea35d5a4192c3f6887c173ee043a16a09a7b245b/packages/geoview-core/src/core/components/common/responsive-grid.tsx#L59)):*
> ```XML
> const ResponsiveGridLeftPanel = forwardRef(
>   (
>     { children, className, isRightPanelVisible = false, sxProps = {}, isEnlarged, fullWidth = false, ...rest }: ResponsiveGridPanelProps,
> ```

in `ResponsiveGridPanelProps` type `className` is optional, can u add default prop like `sxProps` and `fullWidth`
___
*[`packages/geoview-core/src/core/components/common/responsive-grid.tsx` line 114 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2130#-Nxsp3s7DkBTjeeje_NX:-Nxsp3s7DkBTjeeje_NY:b-xu0fxd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ea35d5a4192c3f6887c173ee043a16a09a7b245b/packages/geoview-core/src/core/components/common/responsive-grid.tsx#L114)):*
> ```XML
> const ResponsiveGridRightPanel = forwardRef(
>   (
>     { children, className, isRightPanelVisible = false, sxProps = {}, isEnlarged, fullWidth = false, ...rest }: ResponsiveGridPanelProps,
> ```

in `ResponsiveGridPanelProps` type `className` is optional, can u add default prop like `sxProps` and `fullWidth`

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2130)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @jolevesq and @kaminderpal)

___
*[`packages/geoview-core/src/core/components/common/responsive-grid.tsx` line 59 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2130#-NxsolPL50DxwjNzpMFx:-Nxstjo48qOTPz8oVTrd:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ea35d5a4192c3f6887c173ee043a16a09a7b245b/packages/geoview-core/src/core/components/common/responsive-grid.tsx#L59)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

in `ResponsiveGridPanelProps` type `className` is optional, can u add default prop like `sxProps` and `fullWidth`
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/common/responsive-grid.tsx` line 114 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2130#-Nxsp3s7DkBTjeeje_NX:-NxstlED0nx0Uu5tmAcT:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ea35d5a4192c3f6887c173ee043a16a09a7b245b/packages/geoview-core/src/core/components/common/responsive-grid.tsx#L114)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

in `ResponsiveGridPanelProps` type `className` is optional, can u add default prop like `sxProps` and `fullWidth`
</blockquote></details>

Done.

**Review by kaminderpal — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2130)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2130)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
