### PR TITLE
feat(api-rendering) Call api's after rendering is ready

### LINKED ISSUE #56: Find a way to make API calls after maps are ready
Currently we can make API calls from outside our app (specifically from index.html at the moment)
The problem is that some API calls requires a leaflet map instance to be ready and we are creating this map instance using react leaflet when we render MapContainer
The issue is that rendering is taking few seconds and running API calls will be called earlier and cause an error or return undefined because they are being called on an undefined object since the Map is not ready yet.
We need to find a way to make those API calls after the map is ready

### PR DESCRIPTION
**Pull request by yass0016**
Closes #56

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/60)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/60)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[public/index.html, line 51 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/60#-MSciwhl-xP65LoB4f08:-MSciwhm5Ho6c0U8Iw1l:bmokhdz) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1755d358907314a5314b970a9a4567601e5e99a6/public/index.html#L51)):*
> ```HTML
>                 <button class="add-circle-btn">Add Circle</button>
>                 <button class="add-circle-marker-btn">Add Circle Marker</button>
>                 <button class="delete-polyline-btn">Delete Polyline</button>
> ```

Good choice, it was confusing
___
*[public/index.html, line 177 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/60#-MScjDsa-RU_g7Xp6O1z:-MScjDsa-RU_g7Xp6O2-:blyyxg7) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1851a851ae9098694328e4509c64aa3ab89cf992/public/index.html#L177)):*
> ```HTML
> 
>             // initialize cgpv and api events, a callback is optional, used if calling api's after the rendering is ready
>             cgpv.init(function () {
> ```

Is there use case where we do not need to make sure rendering is ready?
___
*[src/app.tsx, line 26 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/60#-MScjN5w3oaX0Tgp1-98:-MScjN5w3oaX0Tgp1-99:b-4ytxpr) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1851a851ae9098694328e4509c64aa3ab89cf992/src/app.tsx#L26)):*
> ```XML
> /**
>  * initialize the cgpv and render it to root element
>  */
> ```

Should we have JSDOC for the callback function?
___
*[src/api/api.ts, line 63 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/60#-MScjaRuClfn4tX1fC8t:-MScjaRuClfn4tX1fC8u:b-m2asb1) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1851a851ae9098694328e4509c64aa3ab89cf992/src/api/api.ts#L63)):*
> ```XML
>             // Run the callback
>             if (this.readyCallback) this.readyCallback();
>         }, 1000);
> ```

Is this will make the rendering slower because we have a timeout? Can have an issue where a map is not created before the time out ends and we get undefined?

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/60)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @jolevesq and @melzeiny1980)

___
*[public/index.html, line 177 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/60#-MScjDsa-RU_g7Xp6O1z:-MSck6UlB9b0KrBEunCU:b-htlmmk) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1851a851ae9098694328e4509c64aa3ab89cf992/public/index.html#L177)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is there use case where we do not need to make sure rendering is ready?
</blockquote></details>

If the user just want to use the app is a viewer to view the maps with their passed in layers in the config array, they dont need to call any API functions
___
*[src/app.tsx, line 26 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/60#-MScjN5w3oaX0Tgp1-98:-MSckjVCC0Kp-WThYksb:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1851a851ae9098694328e4509c64aa3ab89cf992/src/app.tsx#L26)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we have JSDOC for the callback function?
</blockquote></details>

Done.
___
*[src/api/api.ts, line 63 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/60#-MScjaRuClfn4tX1fC8t:-MScktll1SmSwtWtzXjH:b-5x8cus) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1851a851ae9098694328e4509c64aa3ab89cf992/src/api/api.ts#L63)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this will make the rendering slower because we have a timeout? Can have an issue where a map is not created before the time out ends and we get undefined?
</blockquote></details>

this shouldn't stop the rendering or slow it down, rendering will continue regardless. It simply gives the api functions time before they are called. I think 1 second is more than enough here

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/60)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @melzeiny1980 and @yass0016)

___
*[src/api/api.ts, line 63 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/60#-MScjaRuClfn4tX1fC8t:-MScmZOE9dG8IT-Fkwqq:b-jlc6yc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1851a851ae9098694328e4509c64aa3ab89cf992/src/api/api.ts#L63)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

this shouldn't stop the rendering or slow it down, rendering will continue regardless. It simply gives the api functions time before they are called. I think 1 second is more than enough here
</blockquote></details>

So the api can't be ready before 1 second? If so, can you just put a TODO to say we may want to investigate later to run it without a timeout to speed up the launch. The viewer best quality should be is rendering speed

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/60)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @jolevesq and @melzeiny1980)

___
*[src/api/api.ts, line 63 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/60#-MScjaRuClfn4tX1fC8t:-MScnvOPEIldzQZUlo2F:bjdqlsq) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1851a851ae9098694328e4509c64aa3ab89cf992/src/api/api.ts#L63)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

So the api can't be ready before 1 second? If so, can you just put a TODO to say we may want to investigate later to run it without a timeout to speed up the launch. The viewer best quality should be is rendering speed
</blockquote></details>

this shouldn't effect rendering speed at all, the timer only gets called after all maps are ready, rendering will be it's usual performance dependent on device specs

**Review by jolevesq — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/60#-:-MScqHVN3lvobcXAjHAe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @melzeiny1980)

**Pull request merged**
