### PR TITLE
feat(#88) Sample Page Responsive Pages

### PR DESCRIPTION
**Pull request by melzeiny1980**
## Checklist

* [ ] Commit message follow the guidelines
* [ ] PR targets the correct release version
* [ ] Deploy has been done
* [ ] Check styling
* [ ] _Help files and documentation have been updated_
* [ ] ~Release notes have been updated~

## What's to look for styling
* Use camelCase for identifier names (variables and functions)
* Use PascalCase for type names
* Do not use "I" as a prefix for interface names
* Do not export types/functions unless you need to share it across multiple components
* All names start with a letter
* Always put spaces around operators ( = + - * / ), and after colon:
* Remove all trailing white spaces
* Look for bad indentation
* Carriage return are mandatory
  * Before comments
  * Before if condition
  * After if condition
  * Before properties
  * Before classes
  * Before functions

The use of Prettier Visual Studio Code extension let's you format automatically your code to remove most of the styling issues like white space and indentation.

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
check png doesn't load

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-:-MU9-hLH60_tFP0jn08y:b-bwx1oo)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[public/index.html, line 49 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU9-a36BdmSvfxsd6Ys:-MU9-a36BdmSvfxsd6Yt:b-z6hv4p) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/index.html#L49)):*
> ```HTML
>                     </tr>
>                     <tr>
>                         <td><a class="samplePage-Text" href="./responsive_pages.html">Responsive Pages</a></td>
> ```

There is only one page, do you need a s to page?
___
*[public/templates/responsive_pages.html, line 142 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU90IKNBsWOK6nid8tJ:-MU90IKNBsWOK6nid8tK:b-jwz4nj) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/templates/responsive_pages.html#L142)):*
> ```HTML
>     </head>
> 
>     <body>
> ```

Would need the same header - logo - title

Link to get to 3 maps and a link to go back to main
___
*[public/templates/responsive_pages.html, line 146 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU90Rmk3vuxtiqt4xQs:-MU90Rmk3vuxtiqt4xQt:b-7p70xb) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/templates/responsive_pages.html#L146)):*
> ```HTML
>         <br />
>         <h2>1. Smart Phone</h2>
>         <p>Small Screen Size 640px of width or less</p>
> ```

For the iphone sample, can you put only 10px for margin and height as the view height so we do not have scrollbar
___
*[public/templates/responsive_pages.html, line 164 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU90hjUDURJ-jjQdkmA:-MU90hjUDURJ-jjQdkmB:bnis05j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/templates/responsive_pages.html#L164)):*
> ```HTML
>         <br />
>         <h2>3. Desktop</h2>
>         <p>Big Screen Size 960px of width or up</p>
> ```

Change map height so there is no scrollbar

**Comment by melzeiny1980** [comment]
___
*[public/index.html, line 49 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU9-a36BdmSvfxsd6Ys:-MU92uhO7dxj8sE34Y5X:bvzls47) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/index.html#L49)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There is only one page, do you need a s to page?
</blockquote></details>

in order to get the device experience , i host the it in i frame , in the frame i wanted to host a page with simple map that is not one of the sample pages just in case we change that sample , the experience does not get affected

**Comment by melzeiny1980** [comment]
___
*[public/templates/responsive_pages.html, line 142 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU90IKNBsWOK6nid8tJ:-MU93LZ_82a1md7KU0_i:b8yd7bk) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/templates/responsive_pages.html#L142)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Would need the same header - logo - title

Link to get to 3 maps and a link to go back to main
</blockquote></details>

by 3 maps you mean the other three sample pages ?

**Comment by melzeiny1980** [comment]
___
*[public/index.html, line 49 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU9-a36BdmSvfxsd6Ys:-MU94_6O1HD3jl2tRxxw:b8f88qy) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/index.html#L49)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

in order to get the device experience , i host the it in i frame , in the frame i wanted to host a page with simple map that is not one of the sample pages just in case we change that sample , the experience does not get affected 
</blockquote></details>

sorry , i misunderstood, thought you mean second instead of the s to pages

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[public/index.html, line 49 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU9-a36BdmSvfxsd6Ys:-MU96gA030tJ81cCIybe:b-frmez0) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/index.html#L49)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

sorry , i misunderstood, thought you mean second instead of the s to pages
</blockquote></details>

Just because for the user it is one page, not many pages
___
*[public/templates/responsive_page_map.html, line 78 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU96rxnCzCXmyFKL-tJ:-MU96rxo-VQFsUyFj-id:b-yi9l6l) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/templates/responsive_page_map.html#L78)):*
> ```HTML
>         </div>
>         <script>
>             // initialize cgpv and api events, a callback is optional, used if calling api's after the rendering is ready
> ```

Do you need this section?
___
*[public/templates/responsive_pages.html, line 142 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU90IKNBsWOK6nid8tJ:-MU96wP0DYQuVKahNx4Y:b-8kurvl) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/templates/responsive_pages.html#L142)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

by 3 maps you mean the other three sample pages ?
</blockquote></details>

Mean like in your other pages... link on top to go to the right sample, link back to top, link to go to main. Page should looks like the other sample page.

**Comment by melzeiny1980** [comment]
___
*[public/templates/responsive_page_map.html, line 78 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU96rxnCzCXmyFKL-tJ:-MU9G9FjE1uTyRm71NaN:boga9nr) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/templates/responsive_page_map.html#L78)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do you need this section?
</blockquote></details>

i dont need the part to inject the code snippet. but still would need the initialization of the api

**Comment by melzeiny1980** [comment]
___
*[public/index.html, line 49 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU9-a36BdmSvfxsd6Ys:-MU9GJlw0Zm3VtvzL6Nd:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/index.html#L49)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Just because for the user it is one page, not many pages
</blockquote></details>

Done.

**Comment by melzeiny1980** [comment]
___
*[public/templates/responsive_page_map.html, line 78 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU96rxnCzCXmyFKL-tJ:-MU9GLD90WraWez2lvjD:bojxx49) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/templates/responsive_page_map.html#L78)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

i dont need the part to inject the code snippet. but still would need the initialization of the api
</blockquote></details>

i removed the config injection code

**Comment by melzeiny1980** [comment]
___
*[public/templates/responsive_pages.html, line 164 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU90hjUDURJ-jjQdkmA:-MU9bZfQCka5vdQZp5-N:b-poctp5) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/templates/responsive_pages.html#L164)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Change map height so there is no scrollbar
</blockquote></details>

does that mean change the style.css file ? the height seems hard coded in there?

**Comment by melzeiny1980** [comment]
___
*[public/templates/responsive_pages.html, line 146 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU90Rmk3vuxtiqt4xQs:-MU9syNO6Nm9nLmUSgCo:bwqbui7) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/templates/responsive_pages.html#L146)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

For the iphone sample, can you put only 10px for margin and height as the view height so we do not have scrollbar
</blockquote></details>

The margin is coming from the map page , i can reduce that but it would show on all other devices since they reference the same page

**Comment by melzeiny1980** [comment]
___
*[public/templates/responsive_pages.html, line 142 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU90IKNBsWOK6nid8tJ:-MU9UWkO9JBy81-A7jCh:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/templates/responsive_pages.html#L142)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Mean like in your other pages... link on top to go to the right sample, link back to top, link to go to main. Page should looks like the other sample page.
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[public/templates/responsive_pages.html, line 142 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU90IKNBsWOK6nid8tJ:-MUADE330YKgAdJ6ML-M:b-lu07eu) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/templates/responsive_pages.html#L142)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Your top of the page link should be be below the title like in the other pages
___
*[public/templates/responsive_pages.html, line 146 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU90Rmk3vuxtiqt4xQs:-MUADUcT0TBPBwpSc3u3:b-yepxv9) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/templates/responsive_pages.html#L146)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

The margin is coming from the map page , i can reduce that but it would show on all other devices since they reference the same page
</blockquote></details>

Ok, we should do it for every page then. It looks ugly on the phone size at the moment
___
*[public/templates/responsive_pages.html, line 164 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU90hjUDURJ-jjQdkmA:-MUADcCRDiKwfq9mJKFO:b-cuhnv9) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/templates/responsive_pages.html#L164)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

does that mean change the style.css file ? the height seems hard coded in there? 
</blockquote></details>

It is set by #mapid.

**Comment by melzeiny1980** [comment]
___
*[public/templates/responsive_pages.html, line 164 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU90hjUDURJ-jjQdkmA:-MUAEId99df5Hs2acdWJ:b7jpzkx) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/templates/responsive_pages.html#L164)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It is set by #mapid. 
</blockquote></details>

i have changed it to 100px to test , found that map still spills over the height limit to the original height set by the style.css

**Comment by melzeiny1980** [comment]
___
*[public/templates/responsive_pages.html, line 164 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU90hjUDURJ-jjQdkmA:-MUAUiNZAFmXpVSiJcDM:bbwjjyj) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/templates/responsive_pages.html#L164)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

i have changed it to 100px to test , found that map still spills over the height limit to the original height set by the style.css
</blockquote></details>

i have published the version , please check and advise because i seem to be doing something wrong

**Comment by melzeiny1980** [comment]
___
*[public/templates/responsive_pages.html, line 142 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU90IKNBsWOK6nid8tJ:-MUAUyeo6l6rNENopZxY:bb6un1j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/templates/responsive_pages.html#L142)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Your top of the page link should be be below the title like in the other pages
</blockquote></details>

Done

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[public/templates/responsive_pages.html, line 164 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MU90hjUDURJ-jjQdkmA:-MUDvJAmBtthURo4jrEl:b-a2acfv) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/32a18e682ad977771cd47ad0a084af4cd641ddbe/public/templates/responsive_pages.html#L164)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

i have published the version , please check and advise because i seem to be doing something wrong
</blockquote></details>

It modified the map height of all samples. Just the phone, tablet and desktop size (from responsive page) needed to be modified to device height

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, 7 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[public/templates/responsive_page.html, line 191 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MUFSUji-gaq0LjDXRJn:-MUFSUji-gaq0LjDXRJo:b7oaofv) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c48d71f5279203cadf1fb43fab72b6eb119cd124/public/templates/responsive_page.html#L191)):*
> ```HTML
>         <div class="device tabletframe">
>             <div class="tablet">
>                 <iframe name="iframe2" src="responsive_page_map.html" style="width: 100%; border: none; height: 100%"> </iframe>
> ```

Can you put the map height as  full height like the phone sample
___
*[public/templates/responsive_page.html, line 197 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MUFSfB3B9P0TAFSodcy:-MUFSfB3B9P0TAFSodcz:b7oaofv) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c48d71f5279203cadf1fb43fab72b6eb119cd124/public/templates/responsive_page.html#L197)):*
> ```HTML
>         <h3 id="HRP3">3. Desktop</h3>
>         <a href="#top">Top of the page</a>
>         <p>Big Screen Size 960px of width or up</p>
> ```

Can you put the map height as  full height like the phone sample

**Review by melzeiny1980 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101)* status: 7 of 11 files reviewed, 2 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[public/templates/responsive_page.html, line 191 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MUFSUji-gaq0LjDXRJn:-MUFXhmr88o4gldaSWag:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c48d71f5279203cadf1fb43fab72b6eb119cd124/public/templates/responsive_page.html#L191)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put the map height as  full height like the phone sample
</blockquote></details>

Done.
___
*[public/templates/responsive_page.html, line 197 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-MUFSfB3B9P0TAFSodcy:-MUFXi4MCLEDIqtV2izT:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c48d71f5279203cadf1fb43fab72b6eb119cd124/public/templates/responsive_page.html#L197)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put the map height as  full height like the phone sample
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101#-:-MUFkBz06zQwyrpwXxdU:bnfp4nl)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @jolevesq and @yass0016)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yass0016)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 34 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/101)* status: 9 of 41 files reviewed, all discussions resolved (waiting on @yass0016)

**Pull request closed without merging**
