### PR TITLE
fix(appbar-accessibility): Fix app bar accessibility

### LINKED ISSUE #1792: [FEATURE] AppBar accessibility
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

_No response_

### User Story

__AppBar__
- [ ] Notification
- [ ] About
- [ ] Geolocator
- [ ] Basemap Panel
- [ ] Export

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by amir-azma**
# Description

Fix some accessibility features in app bar:

__AppBar__
- [ ] Notification
- [ ] About
- [ ] Geolocator
- [ ] Basemap Panel
- [ ] Export

Fixes #1792 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://amir-azma.github.io/geoview/raw-feature-info.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867)

### CODE REVIEW

**Comment by kmansoor713** [comment]
Observation 1- In the search list, User keep tabbing the search result and when user select arrow keys, it goes into the map and map is scrolling up and down
 
image

Observation 2: Initially, the focus is not capturing the search button, instead it continue to go to map’s footer panel functionalities and then when we do Shift +TAB then focus come to the Search Icon (Left panel of map) 
Observation 3:
A-when you search, then if you hit Esc key on keyboard or click on X icon, it is closing the panel as expected
B-Arrow keys is using to move the map section and tab is used for focus on different basemaps
C-As you shared about basemap in chat that arrow key is used to select up and down, so whether
it is accepted or not. Kindly confirm
 
image



Observation 3: 
In Google Chrome-By selecting CNTR +Q= Exit the map
In MS Edge-By selecting CNTR +Q giving search option= Enter a Keyword like “tabs” or “Windows” to find an action
 
image

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @amir-azma)

___
*[`packages/geoview-core/src/core/components/common/focus-trap-element.tsx` line 1 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867#-NruTCr8EhyFZhqTh8jt:-NruTCr8EhyFZhqTh8ju:b-tw5o4k) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/181cbcaa112d6610704f5cec112e22482c7fa6d1/packages/geoview-core/src/core/components/common/focus-trap-element.tsx#L1)):*
> ```XML
> /* eslint-disable react/require-default-props */
> ```

No global eslint disable
___
*[`packages/geoview-core/src/core/components/common/focus-trap-element.tsx` line 61 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867#-NruTLKD8tfStEvq5pVZ:-NruTLKD8tfStEvq5pV_:byv3fgf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/181cbcaa112d6610704f5cec112e22482c7fa6d1/packages/geoview-core/src/core/components/common/focus-trap-element.tsx#L61)):*
> ```XML
>   return (
>     <FocusTrap open={basic ? active : id === focusItem.activeElementId}>
>       {!basic ? (
> ```

What does basic do, add comment
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 113 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867#-NruTzvB9_MrAV9V7QoY:-NruTzvC-Hb4HBdXq2--:b-70mv2a) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/181cbcaa112d6610704f5cec112e22482c7fa6d1/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L113)):*
> ```XML
> 
>   const handleKeyDown = (event: KeyboardEvent) => {
>     if (event.key === 'Escape') {
> ```

This whole listener on esc should be in a focus trap utility function an reuse everywhere
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 114 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867#-NruVHL7Bpb9gfQl5z60:-NruVHL7Bpb9gfQl5z61:bs446ip) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/181cbcaa112d6610704f5cec112e22482c7fa6d1/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L114)):*
> ```XML
>   const handleKeyDown = (event: KeyboardEvent) => {
>     if (event.key === 'Escape') {
>       setGeolocatorActive(false);
> ```

Focus goes back to geolocator but I have to press enter twice to get back in
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 119 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867#-NruVW9C18e122kScT4V:-NruVW9C18e122kScT4W:b-k7eui) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/181cbcaa112d6610704f5cec112e22482c7fa6d1/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L119)):*
> ```XML
>     if (ARROW_KEY_CODES.includes(event.code)) {
>       // TODO stop moving the map here
>       event.preventDefault();
> ```

Doesnnot wrk, using arrow still move themaps. This arrow, ont moving the map should be handle at the same place as the crosshair on map focus. The arrow hould move map only when focus
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 130 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867#-NruUAs18mjCCdPLMJut:-NruUAs18mjCCdPLMJuu:bmdgrwh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/181cbcaa112d6610704f5cec112e22482c7fa6d1/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L130)):*
> ```XML
> 
>     if (active) {
>       document.addEventListener('keydown', handleKeyDown);
> ```

Listener is added every time it is active but remove only on unmount, we may end up with many listener I think...

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/common/focus-trap-element.tsx` line 1 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867#-NruTCr8EhyFZhqTh8jt:-NrvoyET1kJ3yw2xDt5m:b2q6qxk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/181cbcaa112d6610704f5cec112e22482c7fa6d1/packages/geoview-core/src/core/components/common/focus-trap-element.tsx#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

No global eslint disable
</blockquote></details>

Removed the eslint disable, added defaultProps to component 
___
*[`packages/geoview-core/src/core/components/common/focus-trap-element.tsx` line 61 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867#-NruTLKD8tfStEvq5pVZ:-Nrvl-qV4dX9ET3Xjq9C:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/181cbcaa112d6610704f5cec112e22482c7fa6d1/packages/geoview-core/src/core/components/common/focus-trap-element.tsx#L61)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

What does basic do, add comment
</blockquote></details>

Done
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 113 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867#-NruTzvB9_MrAV9V7QoY:-Nrvu4SH5QtiTGOkd7PJ:b-wlqn8b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/181cbcaa112d6610704f5cec112e22482c7fa6d1/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L113)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This whole listener on esc should be in a focus trap utility function an reuse everywhere
</blockquote></details>

Once we call setGeolocatorActive(false); it set active to be false to close the search panel, then since active is false, the focus trap disables allowing to continue tab to other sections, the purpose of this Esc event listener is not disabling focus trap at the beginning, that's my idea
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 114 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867#-NruVHL7Bpb9gfQl5z60:-Nrvu_h768PvhYkxX39i:bokes9c) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/181cbcaa112d6610704f5cec112e22482c7fa6d1/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L114)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Focus goes back to geolocator but I have to press enter twice to get back in
</blockquote></details>

That's a little tricky, need to check
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 119 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867#-NruVW9C18e122kScT4V:-NrvukUeDvbAZq72659W:b-5y8ll3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/181cbcaa112d6610704f5cec112e22482c7fa6d1/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L119)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Doesnnot wrk, using arrow still move themaps. This arrow, ont moving the map should be handle at the same place as the crosshair on map focus. The arrow hould move map only when focus
</blockquote></details>

I am reviewing it
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 130 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867#-NruUAs18mjCCdPLMJut:-Nrvvm4WEyCJhBqeEmGS:b-deq1zj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/181cbcaa112d6610704f5cec112e22482c7fa6d1/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L130)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Listener is added every time it is active but remove only on unmount, we may end up with many listener I think...
</blockquote></details>

In this case in component unmount, we remove the "handleKeyDown" listener for sure, I checked that by console.log, when we press Esc, then 'active' becomes false, closing panel, component unmounts, then pressing Esc again doesn't call event "handleKeyDown" since it's cleared inside the useEffect return ()..

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @amir-azma)

___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 114 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867#-NruVHL7Bpb9gfQl5z60:-Nsj00n23lgMnh3FGxfv:b-9u7hnt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/181cbcaa112d6610704f5cec112e22482c7fa6d1/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L114)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

That's a little tricky, need to check
</blockquote></details>

Not solved
___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 119 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867#-NruVW9C18e122kScT4V:-Nsj05sC7Cg8xqOeHWFk:b-x4f2ox) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/181cbcaa112d6610704f5cec112e22482c7fa6d1/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L119)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

I am reviewing it
</blockquote></details>

Not working

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 119 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867#-NruVW9C18e122kScT4V:-NskBwPsBZuztflAmXpz:b-nmfztp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/181cbcaa112d6610704f5cec112e22482c7fa6d1/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L119)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Not working
</blockquote></details>

Applied the fix please check host url

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 114 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867#-NruVHL7Bpb9gfQl5z60:-NskCIxO1zUSSxkCOl0Y:bbx20w6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/181cbcaa112d6610704f5cec112e22482c7fa6d1/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L114)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Not solved
</blockquote></details>

Once we hit Esc, the geolocator icon is active (shows the tooltip) but first hit enter doesn't open it, then the second enter opens, I still don't know why if the button is active why hitting enter doesn't open the panel

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @amir-azma)

___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 157 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867#-NsmXYSDC0oJGV8BMxmZ:-NsmXYSDC0oJGV8BMxm_:brhuei7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cb2c2b9ea4762c02bc1a6b33ede8f368f1697ecf/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L157)):*
> ```XML
>   const handleKeyDown = (event: KeyboardEvent) => {
>     // disables map interactions (arrow keys won't move the map)
>     setMapKeyboardPanInteractions(0);
> ```

This need to be in a the crosshair component. Keyboard pan interaction are on when crosshair is enable. This way it will work everything. In your case, you do notput back interaction when crosshair is enable again

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 157 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1867#-NsmXYSDC0oJGV8BMxmZ:-NsprCfm5_ipSZFM1g09:b-ltsrmz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cb2c2b9ea4762c02bc1a6b33ede8f368f1697ecf/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L157)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This need to be in a the crosshair component. Keyboard pan interaction are on when crosshair is enable. This way it will work everything. In your case, you do notput back interaction when crosshair is enable again
</blockquote></details>

I moved this logic to Crosshair component

**Comment by jolevesq** [comment]
We close as we will deal with this later

**Pull request closed without merging**
