### PR TITLE
feat(UI): Updates to the panel's UI

### LINKED ISSUE #460: Panel UI
Implement as per Ken's mockups.

### PR DESCRIPTION
**Pull request by kenchase**
Closes #460

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/470)

### CODE REVIEW

**Review by yass0016 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/470)* status: all files reviewed, 3 unresolved discussions (waiting on @kenchase)

___
*[`packages/geoview-core/src/ui/panel/panel.tsx` line 208 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/470#-N50Tjjy-3CkcK9M0nyR:-N50Tjjy-3CkcK9M0nyS:b-k2p139) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/85fea2101c6ce8a4a6fd4b5b333437f6208653fa/packages/geoview-core/src/ui/panel/panel.tsx#L208)):*
> ```XML
>                 size="small"
>               >
>                 {typeof actionButton.icon === 'string' ? (
> ```

Can you take a look at the template loading-packages.html, click on icons on the map, the details panel will open, you will notice the action buttons at the top in the panel header beside the close button. Can you fix the styling for the action buttons colors?
___
*[`packages/geoview-core/src/ui/panel/panel.tsx` line 291 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/470#-N50THkg1nPQwSSNW-ro:-N50TGCT7sbxfAAHm4tU:b2ycbc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/30bd6e7a75cb8cbec4b783165cc5830d5b8881ef/packages/geoview-core/src/ui/panel/panel.tsx#L291)):*
> ```XML
>                   tooltip={t('general.close')}
>                   tooltipPlacement="right"
>                   className="cgpv-panel-close"
> ```

We are using this class in the details panel, can you add it back?



_Code quote:_
```XML
cgpv-panel-close
```
___
*[`packages/geoview-core/src/ui/style/theme.tsx` line 25 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/470#-N50UU06C2QGEyI75Wlt:-N50UU06C2QGEyI75Wlu:b9868g5) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/85fea2101c6ce8a4a6fd4b5b333437f6208653fa/packages/geoview-core/src/ui/style/theme.tsx#L25)):*
> ```XML
>   },
>   typography: {
>     /* TODO - KenChase. Reverting to default MUI styles. To be reviewed and deleted if unused. 
> ```

We are using most of them, I think we should keep all default values even if we dont use them

**Review by kenchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/470)* status: 3 of 9 files reviewed, 3 unresolved discussions (waiting on @yass0016)

___
*[`packages/geoview-core/src/ui/panel/panel.tsx` line 208 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/470#-N50Tjjy-3CkcK9M0nyR:-N56C34oCWXAOpLwKiRV:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/85fea2101c6ce8a4a6fd4b5b333437f6208653fa/packages/geoview-core/src/ui/panel/panel.tsx#L208)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Can you take a look at the template loading-packages.html, click on icons on the map, the details panel will open, you will notice the action buttons at the top in the panel header beside the close button. Can you fix the styling for the action buttons colors?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/panel/panel.tsx` line 291 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/470#-N50THkg1nPQwSSNW-ro:-N56CCqu9MbcAFh6SEIY:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/30bd6e7a75cb8cbec4b783165cc5830d5b8881ef/packages/geoview-core/src/ui/panel/panel.tsx#L291)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

We are using this class in the details panel, can you add it back?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/ui/style/theme.tsx` line 25 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/470#-N50UU06C2QGEyI75Wlt:-N56CGuC4prlQpDRbeR8:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/85fea2101c6ce8a4a6fd4b5b333437f6208653fa/packages/geoview-core/src/ui/style/theme.tsx#L25)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

We are using most of them, I think we should keep all default values even if we dont use them
</blockquote></details>

Done.

**Review by kenchase — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/470)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @yass0016)

___
*[`packages/geoview-core/src/api/events/payloads/panel-payload.ts` line 27 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/470#-N56wtoADz9HFLCLng-7:-N5AUAxz0IGORbSZ6L-4:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/119094807db4cf36c087b41d4ebc63b31e5c4c60/packages/geoview-core/src/api/events/payloads/panel-payload.ts#L27)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

See comment on this below
</blockquote></details>

Done.

**Review by yass0016 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/470)* status: all files reviewed, 1 unresolved discussion (waiting on @kenchase)

___
*[`packages/geoview-core/src/ui/panel/panel-api.ts` line 138 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/470#-N5Ajosp-I1eAuD_NFqX:-N5Ajosp-I1eAuD_NFqY:bcwkblz) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/eedb3497b460c8a3d7321b5d70849ba051d39699/packages/geoview-core/src/ui/panel/panel-api.ts#L138)):*
> ```XML
>    * @returns {Panel} the panel
>    */
>   addActionButton = (id: string, title: string, children: React.ReactNode, action: () => void): PanelApi => {
> ```

children here should also take the same type. Isn't eslint complaining? :)

**Review by yass0016 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/470)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kenchase)

**Review by yass0016 — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/470)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kenchase)

**Pull request merged**
