### PR TITLE
Fix translation, Fix console logs, Code refactor

### LINKED ISSUE #1622: [BUG] Import from @/App
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is a weird behavior in our import. When we use VS Code to add the import automatically, it propose the import from the real location and the import from @/app. To have the intelissence back, we need to remove the import from app then it will find the good location.

### Expected Behavior

We should always have the import from the real location.

Clean the imports to make sure it use the right location.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### LINKED ISSUE #1842: [BUG] Text hardcoded and not translated
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

image

The text highlighted in the image is not translated.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

My code reduces uses of '@/app' import. 
Also fixes a translation issues on the data page.

Fixes issues in #1842 
Fixes #1622 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://cphelefu.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1903)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 19 of 22 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1903)* status: 20 of 22 files reviewed, 1 unresolved discussion (waiting on @cphelefu)

___
*[`packages/geoview-core/src/ui/icon-button/icon-button.tsx` line 34 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1903#-NsUebMcBlQa67rvx0AE:-NsUebMd3wFTrAXtiX2h:bzfpwsb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/dfff233383ea63e02b9b6db2d0d7b27f2ba542b8/packages/geoview-core/src/ui/icon-button/icon-button.tsx#L34)):*
> ```XML
> 
>   if(disabled) {
>     return (<MaterialIconButton
> ```

This whole return is the same, just removeing the tooltip. CAn we make a a function with the button that you call with or without the tooltip to reduce duplication?

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 22 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1903)* status: all files reviewed, 1 unresolved discussion (waiting on @cphelefu)

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1903)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/ui/icon-button/icon-button.tsx` line 34 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1903#-NsUebMcBlQa67rvx0AE:-NsUha97DHfi7jUn1Vlv:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/dfff233383ea63e02b9b6db2d0d7b27f2ba542b8/packages/geoview-core/src/ui/icon-button/icon-button.tsx#L34)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This whole return is the same, just removeing the tooltip. CAn we make a a function with the button that you call with or without the tooltip to reduce duplication?
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1903)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Review by jolevesq — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1903)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
