### PR TITLE
51 toast

### PR DESCRIPTION
**Pull request by jolevesq**
## Checklist

* [ ] Commit message follow the guidelines
* [ ] PR targets the correct release version
* [ ] Deploy has been done
* [ ] Check styling
* [ ] _Help files and documentation have been updated_
* [ ] ~Release notes have been updated~

## What's to look for styling
* Use camelCase for identifier names (variables and functions)
* Use PascalCase for type names
* Do not use "I" as a prefix for interface names
* Do not export types/functions unless you need to share it across multiple components
* All names start with a letter
* Always put spaces around operators ( = + - * / ), and after colon:
* Remove all trailing white spaces
* Look for bad indentation
* Carriage return are mandatory
  * Before comments
  * Before if condition
  * After if condition
  * Before properties
  * Before classes
  * Before functions

The use of Prettier Visual Studio Code extension let's you format automatically your code to remove most of the styling issues like white space and indentation.

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/131)

### CODE REVIEW

**Review by yass0016 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/131)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[src/core/app-start.tsx, line 62 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/131#-MUtChI08mQdHTXyUrge:-MUtChI19xBJzd45-7Io:b-32kx0r) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/014fd8d20b1de6cccc3290ed592ae7d54f84d40d/src/core/app-start.tsx#L62)):*
> ```XML
>                         // eslint-disable-next-line react/jsx-props-no-spreading
>                         <div {...attributesToProps(domNode.attribs)}>
>                             <SnackbarProvider
> ```

Are you able to move this below on the main return statement, this can apply to any map in the future when we add map config from URL or from passing config in init. Try below ThemeProvider above Suspense or if not work maybe under Suspense

**Review by yass0016 — COMMENTED** [review]
> Reviewed 4 of 9 files at r1, 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/131)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

**Review by yass0016 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/131)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yass0016 — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/131)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jolevesq — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/131#-:-MUtyJj86H4YSpk4WItq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jolevesq — COMMENTED** [review]
> Reviewed 4 of 9 files at r1, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/131)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @jolevesq and @yass0016)

**Review by jolevesq — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/131#-:-MUtzJzD-z0CQb-FmxOR:bnfp4nl)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @jolevesq and @yass0016)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/131)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/core/app-start.tsx, line 62 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/131#-MUtChI08mQdHTXyUrge:-MUtzUGNBtIcIM-P4WR0:b-gpxsez) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/014fd8d20b1de6cccc3290ed592ae7d54f84d40d/src/core/app-start.tsx#L62)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Are you able to move this below on the main return statement, this can apply to any map in the future when we add map config from URL or from passing config in init. Try below ThemeProvider above Suspense or if not work maybe under Suspense
</blockquote></details>

Moved it to map.tsx to solve fullscreen problem

**Pull request merged**
