### PR TITLE
feat(Datatable): left right panel datatable - 1286 

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Create left and right panel for all layers of the map.

Fixes # ([1286](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1286))

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
1) Visit https://kaminderpal.github.io/geoview/raw-data-table.html
2) Wait for map to be loaded
3) Data table will be displayed on the bottom on map.
image

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/raw-data-table.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343)* status: all files reviewed, 2 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343#-NfGb3Lb8g5-qzKOyZGL:-NfGb3Lb8g5-qzKOyZGM:bj1aqzs) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b909373e406532a47bc26d4231201ebafd2871d9/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L2)):*
> ```XML
> import React, { useState, useRef, useCallback, useEffect } from 'react';
> import ChevronRightIcon from '@mui/icons-material/ChevronRight';
> ```

Import from icon in ui
___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343#-NfGb5msCWC_r6pVi5sr:-NfGb5msCWC_r6pVi5ss:b-nhoxou) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b909373e406532a47bc26d4231201ebafd2871d9/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L3)):*
> ```XML
> import React, { useState, useRef, useCallback, useEffect } from 'react';
> import ChevronRightIcon from '@mui/icons-material/ChevronRight';
> import SendIcon from '@mui/icons-material/Send';
> ```

Import from icon in ui... if not there add it.

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343)* status: all files reviewed, 2 unresolved discussions (waiting on @amir-azma, @cphelefu, and @jolevesq)

___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343#-NfGb3Lb8g5-qzKOyZGL:-NfGgtlB7K2OYfOmgwq7:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b909373e406532a47bc26d4231201ebafd2871d9/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Import from icon in ui
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343#-NfGb5msCWC_r6pVi5sr:-NfGh6Ze0ElNVcSNsxuM:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b909373e406532a47bc26d4231201ebafd2871d9/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L3)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Import from icon in ui... if not there add it.
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @amir-azma, @cphelefu, and @kaminderpal)

___
*[`packages/geoview-core/src/ui/icons/index.ts` line 64 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343#-NfGhy6zD2ZFNjqs1smO:-NfGhy6zD2ZFNjqs1smP:b-2sv93e) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/788fa92834573c94b4d33b45953db7db33c07095/packages/geoview-core/src/ui/icons/index.ts#L64)):*
> ```XML
>   ZoomIn as ZoomInSearchIcon,
>   ZoomOut as ZoomOutSearchIcon,
>   Send as SendIcon,
> ```

Put it at right place in alphabetical order

**Comment by cphelefu** [comment]
*[`packages/geoview-core/public/templates/raw-data-table.html` line 78 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343#-NfGkN6U6GU_2C3odO_S:-NfGkN6U6GU_2C3odO_T:bkj73zi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81790ef7d5354482007b994f7b21f306a8e35c63/packages/geoview-core/public/templates/raw-data-table.html#L78)):*
> ```HTML
> 
>       cgpv.api.event.on(cgpv.api.eventNames.MAP.EVENT_MAP_LOADED, (payload) => {
>         renderDataTableFromMap();
> ```

Can we get mapLoaded from store?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 53 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343#-NfGpSMU1E1EOFPiWhRs:-NfGpSMU1E1EOFPiWhRt:bv7zlte) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81790ef7d5354482007b994f7b21f306a8e35c63/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L53)):*
> ```XML
>   const renderList = useCallback(
>     () => (
>       <List sx={{ color: 'text.primary', marginLeft: '1rem', width: '100%', paddingRight: '2rem' }}>
> ```

OPTIONAL FOR THIS PR:
 Most of the SX is inline. Making it harder to centralize when we want to move it to theme. Consider moving it into objects.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 56 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343#-NfGpmPxBeb3-_Yugu3K:-NfGpmPxBeb3-_Yugu3L:b-b7vuio) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81790ef7d5354482007b994f7b21f306a8e35c63/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L56)):*
> ```XML
>         {layerKeys.map((layerKey, index) => (
>           <Paper
>             sx={{ marginBottom: '1rem', height: '67px', border: selectedLayerIndex === index ? '2px solid #515BA5' : 'none' }}
> ```

OPTIONAL: Most of the SX code is inline.. which may be problematic when trying to move it to themes. Having it in objects will be easier.

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @cphelefu, @jolevesq, and @kaminderpal)

___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 98 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343#-NfGvWzo1kG8VWX_T60g:-NfGvWzp10gMqnu2FUaT:bx7dp2i) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81790ef7d5354482007b994f7b21f306a8e35c63/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L98)):*
> ```XML
>         <Grid item xs={3}>
>           <Typography component="p" sx={{ fontSize: '1.125rem', fontWeight: 'bold' }}>
>             Available Categories
> ```

We can put this text "Available Categories" in translation file, then later we can change it from there.
___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 104 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343#-NfGvkSo2s_00nN50_uu:-NfGvkSo2s_00nN50_uv:b6ncqb6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81790ef7d5354482007b994f7b21f306a8e35c63/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L104)):*
> ```XML
>         <Grid item xs={9}>
>           <Typography component="p" sx={{ fontSize: '1.125rem', fontWeight: 'bold' }}>
>             Selected Category
> ```

Same thing for this text "Selected Category"

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @amir-azma, @cphelefu, and @jolevesq)

___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 98 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343#-NfGvWzo1kG8VWX_T60g:-NfGxgoDCk8UnSOeyrb6:bsyeipe) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81790ef7d5354482007b994f7b21f306a8e35c63/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L98)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

We can put this text "Available Categories" in translation file, then later we can change it from there.
</blockquote></details>

its part of issue #1309   
___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 104 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343#-NfGvkSo2s_00nN50_uu:-NfGxmrA3TiBvGFgmtmu:bsyeipe) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81790ef7d5354482007b994f7b21f306a8e35c63/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L104)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

Same thing for this text "Selected Category"
</blockquote></details>

its part of issue #1309

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1343)* status: all files reviewed, 2 unresolved discussions (waiting on @amir-azma and @cphelefu)

**Pull request merged**
