### PR TITLE
Creation of three synchronous configurations

### LINKED ISSUE #2135: Create three synchronous config
Create three synchronous configurations:
- One simple feature with temporal dimension;
- One uniqueValue which has two layers and creates à group on the fly;
- one classBreaks with only one layer.

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

Create three synchronous configurations:
- One simple feature with temporal dimension;
- One uniqueValue which has two layers and creates à group on the fly;
- one classBreaks with only one layer.

Fixes #2135 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using Chrome Devtools to traCE AND DEBUG THE CODE.

__Deploy URL__: https://ychoquet.github.io/GeoView/config-sandbox.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2136)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 16 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2136)* status: 16 of 17 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/public/templates/config-sandbox.html` line 332 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2136#-Nxw2yjx7C-t_cDrespC:-Nxw2yjx7C-t_cDrespD:be2hkpa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/af6d8421131ad453937874341bce0e2c0e2b3828/packages/geoview-core/public/templates/config-sandbox.html#L332)):*
> ```HTML
> }
> `;
>     const uniqueValueSnippet = `{
> ```

You should add a folder in public/configs called validator and read the content from there to keep html smaller and further modification to config will be easier.
___
*[`packages/geoview-core/src/core/utils/date-mgt.ts` line 72 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2136#-Nxw4OoS1bOLSBBJ04uQ:-Nxw4OoS1bOLSBBJ04uR:bs0mq04) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/af6d8421131ad453937874341bce0e2c0e2b3828/packages/geoview-core/src/core/utils/date-mgt.ts#L72)):*
> ```XML
> type TimePrecision = 'hour' | 'minute' | 'second';
> 
> // GV: CONFIG EXTRACTION
> ```

Can you just export/import the type instead of copying?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 227 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2136#-Nxw4g8x-2WgD_3rl4D2:-Nxw4g8x-2WgD_3rl4D3:b-tlwxta) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/af6d8421131ad453937874341bce0e2c0e2b3828/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L227)):*
> ```XML
>  * @param {boolean} singleHandle True for ESRI Image
>  */
> // TODO: There is a bug with the temporal dimension returned by service URL:
> ```

We should crate an issue for this

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2136)* status: 16 of 17 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/public/templates/config-sandbox.html` line 332 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2136#-Nxw2yjx7C-t_cDrespC:-NxxrMmkElgbGn71VMUL:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/af6d8421131ad453937874341bce0e2c0e2b3828/packages/geoview-core/public/templates/config-sandbox.html#L332)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You should add a folder in public/configs called validator and read the content from there to keep html smaller and further modification to config will be easier.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/date-mgt.ts` line 72 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2136#-Nxw4OoS1bOLSBBJ04uQ:-NxwXqmuDwQU5PzVljCD:b3iwjbw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/af6d8421131ad453937874341bce0e2c0e2b3828/packages/geoview-core/src/core/utils/date-mgt.ts#L72)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you just export/import the type instead of copying?
</blockquote></details>

Done. However, this breaks the rule that says if a type is defined in the schema, then it should have its equivalent typescript type defined in the map-schema-types file or in a config validation class.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 227 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2136#-Nxw4g8x-2WgD_3rl4D2:-NxwXdS55J-rx8heMhVV:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/af6d8421131ad453937874341bce0e2c0e2b3828/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L227)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should crate an issue for this
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 10 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2136)* status: 19 of 20 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/config-base-class.ts` line 133 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2136#-Nxy2Bld4BPCmttw5p1A:-Nxy2Bld4BPCmttw5p1B:b-e7musk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/be966ebfb465fbcd24651a42a74ecab3303d16d5/packages/geoview-core/src/api/config/types/classes/sub-layer-config/config-base-class.ts#L133)):*
> ```XML
>    * @returns {string} The json string corresponding to the map feature configuration.
>    */
>   getJsonString(): string {
> ```

Why do you have same function in 2 different classes?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 227 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2136#-Nxw4g8x-2WgD_3rl4D2:-Nxy2Ovk1xpvIrZF_OW-:b7ejtzn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/af6d8421131ad453937874341bce0e2c0e2b3828/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L227)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

CAn you add theissue number to the comment for reference
___
*[`packages/geoview-core/src/core/utils/date-mgt.ts` line 72 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2136#-Nxw4OoS1bOLSBBJ04uQ:-Nxy2Xok4NQ9KlNPEFJZ:b-uicytg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/af6d8421131ad453937874341bce0e2c0e2b3828/packages/geoview-core/src/core/utils/date-mgt.ts#L72)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Done. However, this breaks the rule that says if a type is defined in the schema, then it should have its equivalent typescript type defined in the map-schema-types file or in a config validation class.
</blockquote></details>

Like I said in the meeting, we can move it but I would like to be removed from data-mgt and use from the new place everywhere

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2136)* status: 19 of 20 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/config-base-class.ts` line 133 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2136#-Nxy2Bld4BPCmttw5p1A:-Nxy3-umD7xdHKaGUcPC:b-hhfz9l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/be966ebfb465fbcd24651a42a74ecab3303d16d5/packages/geoview-core/src/api/config/types/classes/sub-layer-config/config-base-class.ts#L133)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why do you have same function in 2 different classes?
</blockquote></details>

Because when you compile a map against the schema, errors can be generated at the geoview layer or at the layer entry level. Sublayers inform the geoview layer that there is an error and geoview layer, if the are part of a map config,  inform the map config that there is an error.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 227 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2136#-Nxw4g8x-2WgD_3rl4D2:-Nxy41nFBoeoOZM0p1_r:bim0tsc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/af6d8421131ad453937874341bce0e2c0e2b3828/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L227)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

CAn you add theissue number to the comment for reference
</blockquote></details>

Ok, will do that in the next PR.
___
*[`packages/geoview-core/src/core/utils/date-mgt.ts` line 72 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2136#-Nxw4OoS1bOLSBBJ04uQ:-Nxy3wtAE7ZHI5ZTtXFx:bim0tsc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/af6d8421131ad453937874341bce0e2c0e2b3828/packages/geoview-core/src/core/utils/date-mgt.ts#L72)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Like I said in the meeting, we can move it but I would like to be removed from data-mgt and use from the new place everywhere
</blockquote></details>

Ok, will do that in the next PR.

**Pull request merged**
