### PR TITLE
1165 adding notification center

### LINKED ISSUE #1165: [FEATURE] Notification Center
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

As a user, I would like to be able to see message in a centralized place. For the moment, we are using Snack bar but it is  not convenient.

### Implementation UI

Add a button on the AppBar at the bottom. It will be on top of the new About button (#1112).

Whenever we are using the Snack bar, replace it by this new component and remove the Notistack package from package.json and remove Snack bar component from the core.

The Notification panel should have a visual indicator for new notification. It should list all the messages and use can set them read and delete the message if needed.

To add a message, this need to be available trough an api function for the notification component so external user can use it.

### PR DESCRIPTION
**Pull request by cphelefu**
Closes #1165

# Description

This PR add a notification popover in the left panel of the panel. It will eventually replace snackbars.

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 7 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203)* status: 13 of 16 files reviewed, 11 unresolved discussions (waiting on @amir-azma, @cphelefu, and @DamonU2)

___
*[`packages/geoview-core/src/core/components/app-bar/buttons/notifications.tsx` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHcG_J8XqmLJYKOimI:-NaHcG_J8XqmLJYKOimJ:bvlb5k1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/core/components/app-bar/buttons/notifications.tsx#L2)):*
> ```XML
> import { MouseEventHandler } from 'react';
> import { IconButton, NotificationsIcon, Badge } from '../../../../ui';
> ```

Use @/ui
___
*[`packages/geoview-core/src/core/components/notifications/notifications-api.ts` line 1 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHbztn5FfnLiTOBjs3:-NaHbztn5FfnLiTOBjs4:b-hqmzp9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/core/components/notifications/notifications-api.ts#L1)):*
> ```XML
> import { api } from '../../../app';
> ```

Do we have @/app?
___
*[`packages/geoview-core/src/core/components/notifications/notifications-api.ts` line 3 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHbwKE6nwmyu8pZdCO:-NaHbwKE6nwmyu8pZdCP:b-f2zdzn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/core/components/notifications/notifications-api.ts#L3)):*
> ```XML
> import { api } from '../../../app';
> 
> import { EVENT_NAMES } from '../../../api/events/event-types';
> ```

Use @/api
___
*[`packages/geoview-core/src/core/components/notifications/notifications-api.ts` line 5 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHbzNJ36alPfYy_34s:-NaHbzNJ36alPfYy_34t:b-f2zdzn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/core/components/notifications/notifications-api.ts#L5)):*
> ```XML
> import { EVENT_NAMES } from '../../../api/events/event-types';
> 
> import { notificationPayload, NotificationType } from '../../../api/events/payloads/notification-payload';
> ```

Use @/api
___
*[`packages/geoview-core/src/core/components/notifications/notifications-api.ts` line 11 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHc22vEzgjsoOcbFbW:-NaHc22vEzgjsoOcbFbX:b-c5gw8q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/core/components/notifications/notifications-api.ts#L11)):*
> ```XML
>   message: string;
>   description?: string;
> };
> ```

Blank line before comment block
___
*[`packages/geoview-core/src/core/components/notifications/notifications-popover.tsx` line 7 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHcN0y0vpWAFeBA3Ps:-NaHcN0y0vpWAFeBA3Pt:b-f2zdzn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/core/components/notifications/notifications-popover.tsx#L7)):*
> ```XML
> import { api } from '../../../app';
> 
> import { EVENT_NAMES } from '../../../api/events/event-types';
> ```

Use @/api
___
*[`packages/geoview-core/src/core/components/notifications/notifications-popover.tsx` line 8 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHcPGG0cXtoqKDuuI0:-NaHcPGG0cXtoqKDuuI1:b-f2zdzn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/core/components/notifications/notifications-popover.tsx#L8)):*
> ```XML
> 
> import { EVENT_NAMES } from '../../../api/events/event-types';
> import { notificationPayload, NotificationPayload, payloadIsANotification } from '../../../api/events/payloads/notification-payload';
> ```

Use @/api
___
*[`packages/geoview-core/src/core/components/notifications/notifications-popover.tsx` line 10 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHcR745-tFC6LgSEAC:-NaHcR745-tFC6LgSEAD:bvlb5k1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/core/components/notifications/notifications-popover.tsx#L10)):*
> ```XML
> import { notificationPayload, NotificationPayload, payloadIsANotification } from '../../../api/events/payloads/notification-payload';
> 
> import { Box, Popover, InfoIcon, ErrorIcon, WarningIcon, CheckCircleIcon, CloseIcon, IconButton } from '../../../ui';
> ```

Use @/ui

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203)* status: 11 of 16 files reviewed, 12 unresolved discussions (waiting on @amir-azma, @cphelefu, and @jolevesq)

___
*[`packages/geoview-core/src/core/components/notifications/notifications-popover.tsx` line 21 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHe6ToEtPPGPqhHtQr:-NaHe6ToEtPPGPqhHtQs:b-wlzlcy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/core/components/notifications/notifications-popover.tsx#L21)):*
> ```XML
>  * The NotificationPopover component is used to display a list of tabs and their content.
>  *
>  * @returns {JSX.Element} returns the Footer Tabs component
> ```

Just "returns the notification component" - not in the footer tabs

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203)* status: 11 of 16 files reviewed, 12 unresolved discussions (waiting on @amir-azma, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/public/templates/events.html` line 196 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHUdI50YCrMZrhdj-9:-NaHciry7J4TPSGSut-X:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/public/templates/events.html#L196)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Trailing white spaces
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/events/constants/notifications.ts` line 11 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHUjSa5qF7ehJOUigb:-NaHd8lI-3dwNXLprqQa:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/api/events/constants/notifications.ts#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Wrong description, no FOOTER TAB involved
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/app-bar/buttons/notifications.tsx` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHcG_J8XqmLJYKOimI:-NaHdZgw8ykYTJS06MTz:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/core/components/app-bar/buttons/notifications.tsx#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use @/ui
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/notifications/notifications-api.ts` line 1 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHbztn5FfnLiTOBjs3:-NaHdvVM1SzRSJTol6Pc:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/core/components/notifications/notifications-api.ts#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we have @/app?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/notifications/notifications-api.ts` line 3 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHbwKE6nwmyu8pZdCO:-NaHe4hC6kWazw7p0qZU:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/core/components/notifications/notifications-api.ts#L3)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use @/api
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/notifications/notifications-api.ts` line 5 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHbzNJ36alPfYy_34s:-NaHe5WKBrrdFdeNKVcr:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/core/components/notifications/notifications-api.ts#L5)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use @/api
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/notifications/notifications-api.ts` line 11 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHc22vEzgjsoOcbFbW:-NaHeIBRB3Jty4gczbv_:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/core/components/notifications/notifications-api.ts#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank line before comment block
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/notifications/notifications-popover.tsx` line 7 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHcN0y0vpWAFeBA3Ps:-NaHeK-BBIFrzhsjgmDl:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/core/components/notifications/notifications-popover.tsx#L7)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use @/api
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/notifications/notifications-popover.tsx` line 8 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHcPGG0cXtoqKDuuI0:-NaHeKZfCFLBybZhcITl:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/core/components/notifications/notifications-popover.tsx#L8)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use @/api
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/notifications/notifications-popover.tsx` line 10 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHcR745-tFC6LgSEAC:-NaHeL7QCP3rwBsc9TtM:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/core/components/notifications/notifications-popover.tsx#L10)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use @/ui
</blockquote></details>

Done.

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203)* status: 11 of 16 files reviewed, 12 unresolved discussions (waiting on @amir-azma, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/core/components/notifications/notifications-popover.tsx` line 21 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHe6ToEtPPGPqhHtQr:-NaHfKRl7dlf-qgiEX25:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e807217d2fda59051ce648cb1bbc293114ac9134/packages/geoview-core/src/core/components/notifications/notifications-popover.tsx#L21)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Just "returns the notification component" - not in the footer tabs
</blockquote></details>

Done.

**Review by amir-azma — COMMENTED** [review]
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203)* status: 10 of 16 files reviewed, 15 unresolved discussions (waiting on @cphelefu, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/core/components/notifications/notifications-api.ts` line 59 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHsVL64NqboLWrHPrw:-NaHsVL64NqboLWrHPrx:b-rlrwrk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9c924c91c60286606656fd414ae60c27441b585f/packages/geoview-core/src/core/components/notifications/notifications-api.ts#L59)):*
> ```XML
> 
>   /**
>    * Remove notification by index
> ```

It can be: Remove notification by message
___
*[`packages/geoview-core/src/core/components/notifications/notifications-api.ts` line 66 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHrvlh55FvNXvhJWxO:-NaHrvlh55FvNXvhJWxP:b-rda1vg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9c924c91c60286606656fd414ae60c27441b585f/packages/geoview-core/src/core/components/notifications/notifications-api.ts#L66)):*
> ```XML
>     // find the notification to be removed
>     const notifToRemove = this.notificationsList.find(
>       (notif) => notif.message === notificationProps.message && notificationProps.notificationType === notif.notificationType
> ```

I am not sure, but is it possible to have 2 notifications with the same message? if we have this case, what happens if we delete the first one, does the second one get deleted? because we are finding the notification by its message, I think just the first one get deleted
___
*[`packages/geoview-core/src/core/components/notifications/notifications-api.ts` line 72 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHtvu-6IARuIeuLIsr:-NaHtvu-6IARuIeuLIss:b-m4pmvx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9c924c91c60286606656fd414ae60c27441b585f/packages/geoview-core/src/core/components/notifications/notifications-api.ts#L72)):*
> ```XML
>       // remove the notification from the notifications array
>       this.notificationsList = this.notificationsList.filter(
>         (notif) => !(notif.message === notificationProps.message && notificationProps.notificationType === notif.notificationType)
> ```

Can you try this 



_Code snippet:_
```XML
notif.message !== notificationProps.message && notificationProps.notificationType === notif.notificationType
```

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203)* status: 13 of 16 files reviewed, 11 unresolved discussions (waiting on @cphelefu, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/core/components/app-bar/buttons/notifications.tsx` line 126 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHz8p62G8P10AiD3rx:-NaHz8p62G8P10AiD3ry:b-ki9b09) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8583290fba3c356dd60f97111285259a7c55ef69/packages/geoview-core/src/core/components/app-bar/buttons/notifications.tsx#L126)):*
> ```XML
>   function renderNotification(notification: NotificationDetailsType, index: number) {
>     return (
>       <Box sx={{ display: 'flex', flexDirection: 'row', alignItems: 'center', gap: '8px', borderBottom: '1px solid #474747' }} key={index}>
> ```

Can you try to change the theme from 'dark' to 'light' in event.html file in 'data-config'  to see if the borderBottom color #474747 looks good?

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203)* status: 13 of 16 files reviewed, 11 unresolved discussions (waiting on @amir-azma, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/core/components/notifications/notifications-api.ts` line 59 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHsVL64NqboLWrHPrw:-NaHzkhhDIkEveFuyZ_j:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9c924c91c60286606656fd414ae60c27441b585f/packages/geoview-core/src/core/components/notifications/notifications-api.ts#L59)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

It can be: Remove notification by message
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/notifications/notifications-api.ts` line 66 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHrvlh55FvNXvhJWxO:-NaHzVxB4__46Dc01F4Q:b-81l7tc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9c924c91c60286606656fd414ae60c27441b585f/packages/geoview-core/src/core/components/notifications/notifications-api.ts#L66)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

I am not sure, but is it possible to have 2 notifications with the same message? if we have this case, what happens if we delete the first one, does the second one get deleted? because we are finding the notification by its message, I think just the first one get deleted
</blockquote></details>

Yes, its possible. In this case we only delete one. Mentioned this to @jolevesq am sure we will likely have to improve how we handle this scenario as the app evolves
___
*[`packages/geoview-core/src/core/components/notifications/notifications-api.ts` line 72 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203#-NaHtvu-6IARuIeuLIsr:-NaHznZQ1b3I8XWD19Jc:b-lhbkm5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9c924c91c60286606656fd414ae60c27441b585f/packages/geoview-core/src/core/components/notifications/notifications-api.ts#L72)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

Can you try this 
</blockquote></details>

This request may be invalid

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 4 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203)* status: all files reviewed, 2 unresolved discussions (waiting on @cphelefu and @DamonU2)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203)* status: all files reviewed, 2 unresolved discussions (waiting on @cphelefu and @DamonU2)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203)* status: all files reviewed, 2 unresolved discussions (waiting on @cphelefu and @DamonU2)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 15 files at r2.
> Dismissed @DamonU2 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @cphelefu and @DamonU2)

**Review by jolevesq — COMMENTED** [review]
> Dismissed @amir-azma from a discussion.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203)* status: 15 of 16 files reviewed, all discussions resolved (waiting on @DamonU2)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1203)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
