### PR TITLE
refactor(core): Refactor config loadin and store usage to set default

### LINKED ISSUE #1569: [REFACTOR] Centralize Config in Store
Centralize initialization of configuration in the store to be reuse.

Remove direct access to mapFeaturesConfig store on map element. U/se the atomic store selector and action to interact configuration.

At the same time, do the modification for export button in data table

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1569-store-config

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

From now on we have a single point of access to create a map, the inline and create from div use the same set of functions.
We do not have config attach to the context anymore and context is only use to grab mapId for useGeoViewStore hook.
useContext removed from all components and component does not rely on config but on store.

There is still the config attach to map viewer and will be take care of in #1566

Fixes #1569 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://jolevesq.github.io/geoview/index.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1589)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1589)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1589)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/src/app.tsx` line 131 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1589#-Nl3xBZIB2LHHVbTfE3Z:-Nl3xs-qEtP-9XyRA7MD:b-pyqnhk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f5bebc3acedda08377dc63ebae91d9d5901590e5/packages/geoview-core/src/app.tsx#L131)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

My suggestion for the implementation of the below function without the es-lint warnings.
It is true than awaiting in a loop is, most of the time, bad design or needs to be carefully implemented with a Promise.all. In this case, just not necessary to await at all from the looks of it. So I'd turn everything 'non async' (even if the code executes in fact 'async').
</blockquote></details>

That said, I'd like that init function to eventually return something, and become a 'real' async method that returns a result when all maps have been rendered.

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1589)* status: 56 of 57 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/app.tsx` line 131 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1589#-Nl3xBZIB2LHHVbTfE3Z:-Nl40XCC4uW783peqctX:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f5bebc3acedda08377dc63ebae91d9d5901590e5/packages/geoview-core/src/app.tsx#L131)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

That said, I'd like that init function to eventually return something, and become a 'real' async method that returns a result when all maps have been rendered.
</blockquote></details>

Done.

**Review by DamonU2 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1589)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1589)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1589)* status: all files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 191 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1589#-Nl4QRkIA4xH2c1wAoil:-Nl4XU3f93fm6s_vl4iH:bb8xbcj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f5bebc3acedda08377dc63ebae91d9d5901590e5/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L191)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

To avoid the ***createNewLegendEntries*** from being async, I think this code should be placed at the end of the layers loading process. You know, in the 
vectorSource.once('featuresloadend', featuresLoadEndHandler); ***<= for vector***
or the
layerEntryConfig.olLayer!.get('source').once(\`${layerType}loadend\`, loadEndHandler); ***<= for the raster***
This way, you are sure the bounds are calculated when the data is loaded and we can initialize the property to undefined at the beginning of the layer's process.

If you agree, you can update the TODO to leave a trace of the proposed solution and implement the correction later.
</blockquote></details>

Yes we can do this later, I will let TODO
___
*[`packages/geoview-core/src/core/components/app-bar/app-bar.tsx` line 24 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1589#-Nl4VIt_7LbquKT3U2VG:-Nl4X_p_CYJa3w4QIvql:b-9vr48n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f5bebc3acedda08377dc63ebae91d9d5901590e5/packages/geoview-core/src/core/components/app-bar/app-bar.tsx#L24)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Wouldn't it be clearer if we use getGeoViewMapId instead?
</blockquote></details>

Naming convention for atomic selector is use<state><variable>
We use actions set and get when there is process in place (actions and state togheter)

**Pull request merged**
