### PR TITLE
refactor(subscriptions-and-layer-sets) - Refactored a couple subscriptions and layer-sets processing

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

Removed couple subscriptions to orderedLayerInfo from the event processors
Replaced some store subscribe for hooks in some component tsx files

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Hosting, April 24th, 23h15: https://alex-nrcan.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2033)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2033)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 124 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2033#-NvqBxzH7snSVJf05P_w:-NvqBxzH7snSVJf05P_x:b-wmbuyi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/928e63b3f25f079739525675f6cef06421071b08/packages/geoview-core/src/geo/utils/layer-set.ts#L124)):*
> ```XML
>       this.onRegisterLayer(geoviewLayer, layerPath);
> 
>       // Register for TimeSlider
> ```

Why do we have a specific action for time slider but not the other?
___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 167 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2033#-NvqDjOX8r-JUivN7U9M:-NvqDjOX8r-JUivN7U9N:b7hitkm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/928e63b3f25f079739525675f6cef06421071b08/packages/geoview-core/src/geo/utils/layer-set.ts#L167)):*
> ```XML
>    * @private
>    */
>   #reorderLayerInfoStore(layerConfig: TypeLayerEntryConfig): void {
> ```

If I understand, now this were the layer set are reordered instead of each one of them listening on their own?

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2033)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 124 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2033#-NvqBxzH7snSVJf05P_w:-NvqK3Y1B9iMdwQLT8jS:b-69ymkt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/928e63b3f25f079739525675f6cef06421071b08/packages/geoview-core/src/geo/utils/layer-set.ts#L124)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why do we have a specific action for time slider but not the other?
</blockquote></details>

We would have to see how we can push the PR further if we want to centralize that behavior too. Right now, the propagation in the respective stores continue working the way it was with a listener on the status changed, a listener on map-click, the validation/check if a layer is queryable, etc.. and for GeoChart, its propagation of its store happens elsewhere too (the first time when the plugin is initialized and the second time every time a GeoCore layer is added.
Basically, yeah, either we pursue the PR further or I can put a TODO of lesser priority.
___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 167 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2033#-NvqDjOX8r-JUivN7U9M:-NvqM4la4-iKraFEtmHj:b-82aw0w) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/928e63b3f25f079739525675f6cef06421071b08/packages/geoview-core/src/geo/utils/layer-set.ts#L167)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If I understand, now this were the layer set are reordered instead of each one of them listening on their own?
</blockquote></details>

Kind of yeah. Here's the summary.
The place where we had subscriptions on`orderLayerInfo` array: `DataTableProcessor, FeatureInfoProcessor, GeoChartProcessor, and SwiperProcessor` they were only subscribing to `orderLayerInfo` to execute code to remove the layer from their respective store. So that code was moved in the respective 'unregisterFromXXXX` in the layer-set.

Only `TimeSlider's` subscription on `orderLayerInfo` array was used to both _add_  and _remove_ the layer in its store - which is why that one as both a _register_ and _unregister_ function.

So, that logic is essentially the same, except, the `reorderLayerInfoStore` is only executed on layer registration/unregistration now. I haven't looked where the listeners are to modify/maintain the `orderLayerInfo` array and how that store maintains its order when layers are reordered by the user.

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 13 of 13 files at r1, 13 of 13 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2033)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 124 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2033#-NvqBxzH7snSVJf05P_w:-NwILTVq-EjGOi2rRLYd:b8kw7hi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a32c2dfed617399d83091eacabd884f2e02f8369/packages/geoview-core/src/geo/utils/layer-set.ts#L124)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

We would have to see how we can push the PR further if we want to centralize that behavior too. Right now, the propagation in the respective stores continue working the way it was with a listener on the status changed, a listener on map-click, the validation/check if a layer is queryable, etc.. and for GeoChart, its propagation of its store happens elsewhere too (the first time when the plugin is initialized and the second time every time a GeoCore layer is added.
Basically, yeah, either we pursue the PR further or I can put a TODO of lesser priority.
</blockquote></details>

I've further modified this now. Moved some non layer-set related stuff outside of the layer-set and abstracting the onRegister and onUnregister logics.
___
*[`packages/geoview-core/src/geo/utils/layer-set.ts` line 167 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2033#-NvqDjOX8r-JUivN7U9M:-NwILlu5878GOOO7WPjc:b-kp9ya3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a32c2dfed617399d83091eacabd884f2e02f8369/packages/geoview-core/src/geo/utils/layer-set.ts#L167)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Kind of yeah. Here's the summary.
The place where we had subscriptions on`orderLayerInfo` array: `DataTableProcessor, FeatureInfoProcessor, GeoChartProcessor, and SwiperProcessor` they were only subscribing to `orderLayerInfo` to execute code to remove the layer from their respective store. So that code was moved in the respective 'unregisterFromXXXX` in the layer-set.

Only `TimeSlider's` subscription on `orderLayerInfo` array was used to both _add_  and _remove_ the layer in its store - which is why that one as both a _register_ and _unregister_ function.

So, that logic is essentially the same, except, the `reorderLayerInfoStore` is only executed on layer registration/unregistration now. I haven't looked where the listeners are to modify/maintain the `orderLayerInfo` array and how that store maintains its order when layers are reordered by the user.
</blockquote></details>

Some comment as above. This was mostly moved to layerApi class.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 10 of 13 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2033)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 519 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2033#-NwLNc_i2R0XTPNmRXNc:-NwLNc_i2R0XTPNmRXNd:b-7byqa2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66bbbb204c2eb980c82f6181b1d550137a92e6fe/packages/geoview-core/src/geo/layer/layer.ts#L519)):*
> ```XML
>   #registerForLayerInfo(layerConfig: TypeLayerEntryConfig): void {
>     // Update the ordered layer info
>     if (MapEventProcessor.getMapIndexFromOrderedLayerInfo(this.mapId, layerConfig.layerPath) === -1) {
> ```

CAn we add a bit of spacing and a bit of comment in this function

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2033)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 519 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2033#-NwLNc_i2R0XTPNmRXNc:-NwLRqZ51vW16eqf5I63:b-cueu3n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66bbbb204c2eb980c82f6181b1d550137a92e6fe/packages/geoview-core/src/geo/layer/layer.ts#L519)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

CAn we add a bit of spacing and a bit of comment in this function
</blockquote></details>

Yeah, I wasn't sure what it was doing (copied code) and didn't have time to add comments on it.
Now that it's already merged, it can be done in another PR.

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2033)* status: 18 of 19 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 519 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2033#-NwLNc_i2R0XTPNmRXNc:-NwLZYqw2Dt8CTP3WQo1:b-ln2yri) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66bbbb204c2eb980c82f6181b1d550137a92e6fe/packages/geoview-core/src/geo/layer/layer.ts#L519)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Yeah, I wasn't sure what it was doing (copied code) and didn't have time to add comments on it.
Now that it's already merged, it can be done in another PR.
</blockquote></details>

Nevermind, it was another PR that got merged(!).
I've added comments on this PR then.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2033)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Pull request merged**
