### PR TITLE
update footer bar components

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description

Update footer bar component to make wcag compatible.

Fixes # (848)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/872)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/872)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-rotation-button.tsx` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/872#-NNDeQ1W9Go7wUdLDNXb:-NNDeQ1X3B76mT7M7GZL:b-r3wlsg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a49c24cff26b6ad973a31f046ee3de3f1e1531ea/packages/geoview-core/src/core/components/footer-bar/footer-bar-rotation-button.tsx#L17)):*
> ```XML
> const sxClasses = {
>   rotationButton: {
>     height: 25,
> ```

Text below rotation button has not the right size
___
*[`packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx` line 194 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/872#-NNDeZO9BWslfBWktcex:-NNDeZO9BWslfBWktcey:bfiuoff) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a49c24cff26b6ad973a31f046ee3de3f1e1531ea/packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx#L194)):*
> ```XML
> 
>   useEffect(() => {
>     let opacityTimeout: string | number | NodeJS.Timeout | undefined;
> ```

Can we use transition instead of timeout
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 30 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/872#-NNDenXO5g29V4-ug9Io:-NNDenXO5g29V4-ug9Ip:b-t3hulw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a49c24cff26b6ad973a31f046ee3de3f1e1531ea/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L30)):*
> ```XML
>     position: 'absolute',
>     right: theme.spacing(5),
>     bottom: 80,
> ```

Should not be fixed, it should move with the expand

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/872)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx` line 194 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/872#-NNDeZO9BWslfBWktcex:-NNDgSI6ESq3Di4uRZAP:b-1t73ox) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a49c24cff26b6ad973a31f046ee3de3f1e1531ea/packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx#L194)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we use transition instead of timeout
</blockquote></details>

i have tried `transition`, but it was  not working for mouse position

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/872)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-rotation-button.tsx` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/872#-NNDeQ1W9Go7wUdLDNXb:-NNDlXwqCg9DYbUu2LvB:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a49c24cff26b6ad973a31f046ee3de3f1e1531ea/packages/geoview-core/src/core/components/footer-bar/footer-bar-rotation-button.tsx#L17)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Text below rotation button has not the right size
</blockquote></details>

Done.

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/872)* status: 6 of 10 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 30 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/872#-NNDenXO5g29V4-ug9Io:-NNDp6IY3_QzQ0PhJ-xZ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a49c24cff26b6ad973a31f046ee3de3f1e1531ea/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L30)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should not be fixed, it should move with the expand
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/872)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @kaminderpal)

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/872)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 30 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/872#-NNDenXO5g29V4-ug9Io:-NNHWwmU4zMTRt-AWjvh:b-7rl0kd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a49c24cff26b6ad973a31f046ee3de3f1e1531ea/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L30)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should be a transition (same as the expand footer), not a jump.
</blockquote></details>

done
___
*[`packages/geoview-core/src/core/components/scale/scale.tsx` line 5 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/872#-NNH7oPI0RBsKviVlY13:-NNHWyZG7QQCQjYASQbn:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b62b927d1e7283d4cc1cad0450fcbb2b50bc6c64/packages/geoview-core/src/core/components/scale/scale.tsx#L5)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should have spacing between scale and resolution
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
:lgtm:

> Reviewed 1 of 9 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/872#-:-NNI563o47I-Azju5ymb:bnfp4nl)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @kaminderpal)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/872)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Pull request merged**
