### PR TITLE
refactor(layers) - Part 13

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

This PR is part of a series of PR and has a dependency on PR https://github.com/Canadian-Geospatial-Platform/geoview/pull/1953

- Some "final" cleaning up of some now obsolete events payloads
- Fixes a bug with the time-slider-processor where it was listening to the MAP_LOADED event, but that event kept changing its behavior (being raised when the layers were registered/processed/loaded etc and sometimes a setTimeout on setMapLoaded was helping save the situation about it). Now the time-slider truly waits for the layers to be processed before acting on them. The time-slider needs to wait for the processed, because the layers need to have their metadata processed for the time-slider to work with them;
- Removed the MAP_LOADED event in the MapEventProcessor for now, to not confuse it with the other logic happening when the Map is actually being instantiated and then throwing more precise and specific events (and added a TODO surrounding that);
- Now that things are working, turned all class-event handlers properties private as they should be, everywhere;
- Renamed 'Geometry' to 'GeometryApi' to align with the other Api classes there and not confuse it with an actual 'Geometry';
- Removed the layer-set 'ids' as they aren't necessary anymore and cleaned the constructors;
- layer-set getLegend() events management refactored. Simplified after Johann's idea;
- Added some ad-hoc merging comments received by peers on this PR series throughout;

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Currently hosting the finally of the layers refactoring here: https://alex-nrcan.github.io/geoview

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 28 of 37 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954)* status: 29 of 37 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts` line 25 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVotSB9u67bdZOIq21:-NtVotSB9u67bdZOIq22:b3o61pw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts#L25)):*
> ```XML
>     const { mapId } = store.getState();
> 
>     // TODO: Check - Do we want to switch the order of MapViewer instantiation vs store instantiation/initialization?
> ```

This is because the viewer is using the store config to start the init. Store creates a copy of it for reload and then viewer use the store init value to remove passing of object config. We should discuss the modification to do to switch creation later. If we move event to classes 
(map, layer) and these 2 classes (only) can call store function to set values, maybe doing this may be a good idea. Will need more discussion, time evaluation.
___
*[`packages/geoview-core/src/api/events/event.ts` line 174 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVpvQB2ImenDN0xVVb:-NtVpvQB2ImenDN0xVVc:bc2hx2w) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/api/events/event.ts#L174)):*
> ```XML
>         } else {
>           // Log an error as that shouldn't be possible
>           // TODO: Refactor - When all generic events are gone, remove the checkCallback, move some types here, remove bunch of payload files
> ```

I agree, it should our next step and event-type key because use only once can be hard coded in their event as well
___
*[`packages/geoview-core/src/api/events/event-helper.ts` line 6 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVq2MB1UUS_kC6D7QD:-NtVq2MB1UUS_kC6D7QE:b-vd2mjb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/api/events/event-helper.ts#L6)):*
> ```XML
>  */
> export default class EventHelper {
>   // TODO: Document - Add how we use that EventHandler to create class-event in the documentation.
> ```

Very important to do as all backend dev s know how to use
___
*[`packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts` line 161 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVryFKB0qbTvtfzGxk:-NtVryFKB0qbTvtfzGxl:b-iyfdos) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts#L161)):*
> ```XML
>       this._layerStatus = newLayerStatus;
>       // TODO: Refactor - Suggestion to hold the layer status elsewhere than in a configuration file. Can it be on the layer itself?
>       // TO.DOCONT: It'd be "nicer" to have a configuration file that doesn't raise events
> ```

Exactly, config process/fetch then give result. No events
___
*[`packages/geoview-core/src/geo/interaction/select.ts` line 77 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVsZ5MDRyNPmJv0Lx9:-NtVsZ5MDRyNPmJv0LxA:b-l6y0k3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/geo/interaction/select.ts#L77)):*
> ```XML
>    * @returns {Collection<Feature<Geometry>>} The selected features
>    */
>   public getFeatures(): Collection<Feature<Geometry>> {
> ```

Good function to publish!
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 110 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVtmqC9gq5ZPCZOD6X:-NtVtmqD7VCRR2tAPw6c:bv41k2v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/geo/map/map-viewer.ts#L110)):*
> ```XML
> 
>   // Keep all callback delegates references
>   #onMapInitHandlers: MapInitDelegate[] = [];
> ```

If I remember correctly, in other files, your delegate stuff is at the bottom?
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 264 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVu2O-BZLeld6itSK6:-NtVu2O-BZLeld6itSK7:bc32kv9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/geo/map/map-viewer.ts#L264)):*
> ```XML
>    * Function called to monitor when the map has its layers in processed state.
>    */
>   #checkMapLayersProcessed(): void {
> ```

We should put a minimum of 1500 ms before we show the map. It is not that long and may solve some weird synching issue. We may revise later when we cleaned a bit more.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954)* status: 29 of 37 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 435 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVuM8043zt4mbxsmve:-NtVuM8043zt4mbxsmvf:b-14n5qf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/geo/map/map-viewer.ts#L435)):*
> ```XML
>   emitMapLayersProcessed = () => {
>     // Emit the event for all handlers
>     EventHelper.emitEvent(this, this.#onMapLayersProcessedHandlers, undefined);
> ```

Like you said in your comments, the cleaning for store map event, the subscribe for map event processor may came here like these events to emit to outside world. It will reduce complexity of store/event processor. But we should restrict event emit to map-viewer and layer class....

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954)* status: 29 of 37 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/geo/utils/all-feature-info-layer-set.ts` line 80 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVw0WEBZbko2s7-DLt:-NtVw0WEBZbko2s7-DLu:bfnm0b4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/geo/utils/all-feature-info-layer-set.ts#L80)):*
> ```XML
>   protected onProcessLayerStatusChanged(config: ConfigBaseClass, layerPath: string, layerStatus: TypeLayerStatus): void {
>     // TODO: Refactor - This function (and the same function in feature-info-layer-set and hover-feature-info-layer-set) are all very similar if not identical
>     // TO.DOCONT: Move the code to the mother class. Be mindful of legends-layer-set that also has a onProcessLayerStatusChanged which is different though.
> ```

Yes, the status of layers should not matters to child layer set (all feature, feature, hover). The layer set is the one who decide who goes in and out of these 3 sets. So he knows the status of the layer and if not loaded he does not add the layer to the sets. If a layer becomes unstable and get in error, layer set will remove the layers from al feature, feature and hover set.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 37 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954)* status: 34 of 37 files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-time-slider/src/index.tsx` line 121 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVxhYX1GYvdWdyrPmn:-NtVxhYX1GYvdWdyrPmo:btyjv5f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-time-slider/src/index.tsx#L121)):*
> ```XML
>         // TO.DOCONT: the later will override the plugin settings (can be tested by adding fake delays).
>         // TO.DOCONT: If this Plugin has temporal dimension settings, for various layers, those should be set in synch with the layers
>         // TO.DOCONT: using event listeners, not at Plugin creation.
> ```

We need to test this because the setting of the dimension here is to have a custom one (overwrite the layer time dimension). Will need investigation and more explicit flow

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954)* status: 34 of 37 files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts` line 25 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVotSB9u67bdZOIq21:-NtW0rW40vLUr4J31Id6:b-fkc2mi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts#L25)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This is because the viewer is using the store config to start the init. Store creates a copy of it for reload and then viewer use the store init value to remove passing of object config. We should discuss the modification to do to switch creation later. If we move event to classes 
(map, layer) and these 2 classes (only) can call store function to set values, maybe doing this may be a good idea. Will need more discussion, time evaluation.
</blockquote></details>

I'll copy over this comment in the code. It's interesting. Yeah, I didn't want to change that off the bat, but thought of writing this to explain the little acrobatics I had to do on the next line.
___
*[`packages/geoview-core/src/api/events/event.ts` line 174 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVpvQB2ImenDN0xVVb:-NtW1Ymg8FSgcvWAInPJ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/api/events/event.ts#L174)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I agree, it should our next step and event-type key because use only once can be hard coded in their event as well
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/events/event-helper.ts` line 6 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVq2MB1UUS_kC6D7QD:-NtW1cyx1yybYZj9TXyC:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/api/events/event-helper.ts#L6)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Very important to do as all backend dev s know how to use
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts` line 161 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVryFKB0qbTvtfzGxk:-NtW1hI4E4WGd6OOneic:b-np6bpv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts#L161)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Exactly, config process/fetch then give result. No events
</blockquote></details>

lol I had forgotten about that TODO, I've only added it in PR13? :)
___
*[`packages/geoview-core/src/geo/interaction/select.ts` line 77 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVsZ5MDRyNPmJv0Lx9:-NtW1pbC9kOw-7HHmp54:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/geo/interaction/select.ts#L77)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Good function to publish!
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 110 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVtmqC9gq5ZPCZOD6X:-NtW1tbG9bbapvzaVGBq:btm5vxw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/geo/map/map-viewer.ts#L110)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If I remember correctly, in other files, your delegate stuff is at the bottom?
</blockquote></details>

You mean the order among the class attributes themselves? I personally don't have much preference on that particular aspect. I'll move those down. The others are maybe at the bottom, by chance, because they were new?
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 264 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVu2O-BZLeld6itSK6:-NtW2Xr93PUVnpRXUtvK:bgnl1ho) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/geo/map/map-viewer.ts#L264)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should put a minimum of 1500 ms before we show the map. It is not that long and may solve some weird synching issue. We may revise later when we cleaned a bit more.
</blockquote></details>

Yes, I'll add a TODO.
I'll ALSO add a TODO about rewriting those checkMapReady, checkMapLayersProcessed and checkMapLayersLoaded to remove the setInterval and make it better.
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 435 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVuM8043zt4mbxsmve:-NtW8KYoDGwP4AMo2fbl:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/geo/map/map-viewer.ts#L435)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Like you said in your comments, the cleaning for store map event, the subscribe for map event processor may came here like these events to emit to outside world. It will reduce complexity of store/event processor. But we should restrict event emit to map-viewer and layer class....
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/utils/all-feature-info-layer-set.ts` line 80 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVw0WEBZbko2s7-DLt:-NtW3kRn6arzRlJbgNx4:b-wlnria) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/geo/utils/all-feature-info-layer-set.ts#L80)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Yes, the status of layers should not matters to child layer set (all feature, feature, hover). The layer set is the one who decide who goes in and out of these 3 sets. So he knows the status of the layer and if not loaded he does not add the layer to the sets. If a layer becomes unstable and get in error, layer set will remove the layers from al feature, feature and hover set.
</blockquote></details>

I've copied that comment over in the TODO.
___
*[`packages/geoview-time-slider/src/index.tsx` line 121 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVxhYX1GYvdWdyrPmn:-NtW8GGS1_MBLxSKmi8F:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-time-slider/src/index.tsx#L121)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We need to test this because the setting of the dimension here is to have a custom one (overwrite the layer time dimension). Will need investigation and more explicit flow
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 3 of 37 files at r1, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954)* status: 34 of 37 files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan)

**Review by ychoquet — COMMENTED** [review]
> Reviewed 36 of 37 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954)* status: 34 of 37 files reviewed, 10 unresolved discussions

___
*[`packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts` line 161 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtVryFKB0qbTvtfzGxk:-NtWElQA5aBQDXTUZM-j:b-8wom18) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts#L161)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

lol I had forgotten about that TODO, I've only added it in PR13? :)
</blockquote></details>

This setter will disappear. The work done on state event sequencing will make this patch obsolete.
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 319 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1954#-NtWGfQv1RPd8eo5D0mj:-NtWGfQv1RPd8eo5D0mk:bg505in) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/26420ab1449f4fc3a135837499828afbbdaa10cf/packages/geoview-core/src/geo/layer/layer.ts#L319)):*
> ```XML
>     // TO.DOCONT: The layer class should receive an instance of configuration in is constructor.
>     // TO.DOCONT: Here the function sends the config to this class to get the structure to use to generate layers.
>     // TO.DOCONT: We should not have link to config anymore...
> ```

Yes, this is something important!



_Code quote:_
```XML
    // TODO: Refactor - We should not create a new config here.
    // TO.DOCONT: The layer class should receive an instance of configuration in is constructor.
    // TO.DOCONT: Here the function sends the config to this class to get the structure to use to generate layers.
    // TO.DOCONT: We should not have link to config anymore...
```

**Pull request merged**
