### PR TITLE
811 overviewer in ft

### LINKED ISSUE #811: Overview map minimize
The overview map minimizer button is not working on footer panel demo page

### PR DESCRIPTION
**Pull request by dennisfu**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #811
## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [X] I have connected the issues(s) to this PR
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/852)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/852)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @dennisfu)

___
*[`packages/geoview-footer-panel/src/data-item.tsx` line 2 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/852#-NN1jShVEUk0SHY0qDzl:-NN1jShVEUk0SHY0qDzm:bhes4aa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1d1ca1c7317bfbdb60ba6064f708f7c3b780042b/packages/geoview-footer-panel/src/data-item.tsx#L2)):*
> ```XML
> /* eslint-disable react/require-default-props */
> // import { DetailedReactHTMLElement, JSXElementConstructor, ReactElement } from 'react';
> ```

Remove dead code
___
*[`packages/geoview-footer-panel/src/index.tsx` line 80 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/852#-NN1jd0gAUdI2TdnRg59:-NN1jd0gAUdI2TdnRg5A:bb924ob) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1d1ca1c7317bfbdb60ba6064f708f7c3b780042b/packages/geoview-footer-panel/src/index.tsx#L80)):*
> ```XML
>     const { cgpv } = w;
> 
>     // if (cgpv) {
> ```

Why do you need to remove the if?

**Comment by dennisfu** [comment]
rebased and done.

for the cgpv if, was just a test and reverted

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/852)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dennisfu)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/852#-:-NN8A31hBZEUjRb5FVz0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dennisfu)

**Pull request merged**
