### PR TITLE
adding styling to layers and scrollbars

### LINKED ISSUE #1841: [BUG] Style scrollbars
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Our currently scrollbars need styling.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

- [ ] Centralize styling for layers (with different status)
- [ ] Styling the scrollbars
- [ ] Fixing icon buttons in disabled layers
- [ ] Fix the notifications to group by count.
- [ ] Fix the notifications panel to not move with the page (replace with Popper)
- [ ] Centralize layer icons across the three tabs.

Fixes #1841 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1854)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 10 of 17 files at r1, 10 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1854)* status: 20 of 23 files reviewed, 2 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/src/core/components/common/layout.tsx` line 95 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1854#-Nrb_dbDA7OQxz6LUzl_:-Nrb_dbDA7OQxz6LUzla:bmd5xbp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ec0aa0d9f6bea91fd023328e14e3d65926b454b8/packages/geoview-core/src/core/components/common/layout.tsx#L95)):*
> ```XML
>         {!fullWidth && (
>           <ResponsiveGrid.Left isLayersPanelVisible={isLayersPanelVisible} isEnlarged={isEnlarged}>
>             {null}
> ```

Do we need null or we can self close />
___
*[`packages/geoview-core/src/ui/popper/popper.tsx` line 10 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1854#-NrbacJ49EgKkO_sWy9t:-NrbacJ53qW1JAO4ow-d:b-21qi1i) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ec0aa0d9f6bea91fd023328e14e3d65926b454b8/packages/geoview-core/src/ui/popper/popper.tsx#L10)):*
> ```XML
>  * @returns {JSX.Element} returns popover component
>  */
> export function Popper(props: PopperProps): JSX.Element {
> ```

What is the difference between popper and popover?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1854)* status: 20 of 24 files reviewed, 4 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/src/core/components/app-bar/buttons/version.tsx` line 48 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1854#-NrfsDXvCIRxoqZ1wJI1:-NrfsDXvCIRxoqZ1wJI2:bf42i9i) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2aaa143417af22766f36891c38e5fff20074c6de/packages/geoview-core/src/core/components/app-bar/buttons/version.tsx#L48)):*
> ```XML
> 
>   const sxClasses = {
>     versionInfoPanel: {
> ```

Should it be in popper style for reusability, like notification popper
___
*[`packages/geoview-core/src/core/components/notifications/notifications-style.ts` line 4 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1854#-NrfrysQ811SFMllgzvU:-NrfrysQ811SFMllgzvV:b-9fuc3b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2aaa143417af22766f36891c38e5fff20074c6de/packages/geoview-core/src/core/components/notifications/notifications-style.ts#L4)):*
> ```XML
> 
> export const getSxClasses = (theme: Theme) => ({
>   notificationPanel: {
> ```

Is this and motificationPanell reuse in version. I think it should be ui popper so every popper have same style

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/app-bar/buttons/version.tsx` line 48 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1854#-NrfsDXvCIRxoqZ1wJI1:-Nrfv6JR4M8m4tCZup8X:bfgiye9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2aaa143417af22766f36891c38e5fff20074c6de/packages/geoview-core/src/core/components/app-bar/buttons/version.tsx#L48)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should it be in popper style for reusability, like notification popper
</blockquote></details>

I thought about that; and it was only two lines that are common between the two.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/common/layout.tsx` line 95 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1854#-Nrb_dbDA7OQxz6LUzl_:-NrfvFIY9tHcWmPefDuQ:b-bn5rcq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ec0aa0d9f6bea91fd023328e14e3d65926b454b8/packages/geoview-core/src/core/components/common/layout.tsx#L95)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we need null or we can self close />
</blockquote></details>

Very interesting this. If I remove this null the UI gets messed up.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/notifications/notifications-style.ts` line 4 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1854#-NrfrysQ811SFMllgzvU:-NrfvPSnCUdILZOA-R2G:bnifyys) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2aaa143417af22766f36891c38e5fff20074c6de/packages/geoview-core/src/core/components/notifications/notifications-style.ts#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this and motificationPanell reuse in version. I think it should be ui popper so every popper have same style
</blockquote></details>

Not a lot of reusable elments; except backgroundColor and borderRadius.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/ui/popper/popper.tsx` line 10 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1854#-NrbacJ49EgKkO_sWy9t:-Nrfvgne1vf16ZnepIvi:b-83tnsg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ec0aa0d9f6bea91fd023328e14e3d65926b454b8/packages/geoview-core/src/ui/popper/popper.tsx#L10)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

What is the difference between popper and popover?
</blockquote></details>

Popper can scroll with the page. Can also specify position of modal.
Popover is not suppose to preventing page scrolling - but in our case it was scrolling with page (causing the error).

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 17 files at r1, 1 of 11 files at r2, 1 of 3 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1854)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
