### PR TITLE
[FEATURE+FIX] GeoCore implementation update

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

GeoCore implementation update
Add-Layer fix when adding GeoCore layer with uuid
GeoChart linkage with GeoCore

Fixes: #790 #1499 #1806 
Commented: #793 
Related to: #43 #1214

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Hosted here as of Feb 19th 17h: [https://alex-nrcan.github.io/geoview/](https://alex-nrcan.github.io/geoview/)

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1828)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
> Reviewed 21 of 21 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1828)* status: all files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 70 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1828#-Nr6y462CNLcdgRscAv9:-Nr6y463EjICD53By3z1:b1x0ghw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ce9bf2cb556fe149a18cb5dfb381b137fd565c48/packages/geoview-core/src/core/utils/config/config-validation.ts#L70)):*
> ```XML
>   // TODO: Refactor - Environment - How to edit this configuration easily per environment?
>   /** The default geocore url */
>   static CONFIG_GEOCORE_URL = 'https://geocore-stage.api.geo.ca';
> ```

To we should keep it packages\geoview-core\src\core\utils\constant.ts like other constant for the moment
___
*[`packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts` line 26 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1828#-Nr6yQOiErHKFDdIk8L_:-Nr6yQOiErHKFDdIk8La:b-ym0ba8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ce9bf2cb556fe149a18cb5dfb381b137fd565c48/packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts#L26)):*
> ```XML
> import { logger } from '@/core/utils/logger';
> 
> // The GeoChart Json object coming out of the GeoCore response
> ```

Should packages configuration (i.e. gechart) as may not only be geocart

Or wrapped the whole type thing in a region with the package comment
___
*[`packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts` line 326 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1828#-Nr6zbZQ9j3yOiHWy8JW:-Nr6zbZR9aUK2aF1_DZl:b-ib0mmm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ce9bf2cb556fe149a18cb5dfb381b137fd565c48/packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts#L326)):*
> ```XML
>     return listOfGeoviewLayerConfig;
>   }
> ```

Wrap geochart config in a region
___
*[`packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts` line 354 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1828#-Nr70RNd0LB7zdS1OR__:-Nr70RNd0LB7zdS1OR_a:b-4q2n93) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ce9bf2cb556fe149a18cb5dfb381b137fd565c48/packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts#L354)):*
> ```XML
> 
>   /**
>    * Generates GeoView layers and geocharts configurations, from GeoCore API, using a list of UUIDs.
> ```

package configuration (i.e. geochart)
___
*[`packages/geoview-core/src/geo/layer/other/geocore.ts` line 124 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1828#-Nr70xB957UkGGQrErLB:-Nr70xB957UkGGQrErLC:b-5k873w) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ce9bf2cb556fe149a18cb5dfb381b137fd565c48/packages/geoview-core/src/geo/layer/other/geocore.ts#L124)):*
> ```XML
> 
>       // Generate the url
>       // TODO: Check - Is the metadataAccessPath still used? Because it seems to be incompatible with the rest now?
> ```

It is but this is not he atttribute name when you call geocore url

**Review by DamonU2 — APPROVED** [review]
> Reviewed 20 of 21 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1828)* status: 20 of 22 files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan, @jolevesq, and @ychoquet)

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1828)* status: all files reviewed, 5 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 70 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1828#-Nr6y462CNLcdgRscAv9:-Nr74LolC9l5oU9cvIqi:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ce9bf2cb556fe149a18cb5dfb381b137fd565c48/packages/geoview-core/src/core/utils/config/config-validation.ts#L70)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

To we should keep it packages\geoview-core\src\core\utils\constant.ts like other constant for the moment
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts` line 26 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1828#-Nr6yQOiErHKFDdIk8L_:-Nr74Wv9ClmibsLukYme:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ce9bf2cb556fe149a18cb5dfb381b137fd565c48/packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts#L26)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should packages configuration (i.e. gechart) as may not only be geocart

Or wrapped the whole type thing in a region with the package comment
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts` line 326 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1828#-Nr6zbZQ9j3yOiHWy8JW:-Nr74XFg6TkrTXKf8Oqg:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ce9bf2cb556fe149a18cb5dfb381b137fd565c48/packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts#L326)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Wrap geochart config in a region
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts` line 354 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1828#-Nr70RNd0LB7zdS1OR__:-Nr75FLzDeS-snLviAKO:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ce9bf2cb556fe149a18cb5dfb381b137fd565c48/packages/geoview-core/src/core/utils/config/reader/uuid-config-reader.ts#L354)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

package configuration (i.e. geochart)
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/other/geocore.ts` line 124 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1828#-Nr70xB957UkGGQrErLB:-Nr75pGt9AaBYkRLJ6o2:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ce9bf2cb556fe149a18cb5dfb381b137fd565c48/packages/geoview-core/src/geo/layer/other/geocore.ts#L124)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It is but this is not he atttribute name when you call geocore url
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 5 of 5 files at r5, 1 of 1 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1828)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1828)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1828)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
