### PR TITLE
fix(footer): fix map height console error

### LINKED ISSUE #1995: [BUG] Map height
**Is there an existing issue for this?**
Please search to see if an issue already exists for the bug you encountered.

**Current Behavior**
A concise description of what you're experiencing.

We have this warning when we create the map:
console.js:52 No map visible because the map container's width or height are 0.

**Expected Behavior**
A concise description of what you expected to happen.

We need to set the size of the map from the map div

**Steps To Reproduce**
1. Go to https://canadian-geospatial-platform.github.io/geoview/public/esri-dynamic.html
2. Click on console
3. Scroll down to the message

**Anything else?**
References? Anything that will give us more context about the issue you are encountering and if applicable, add screenshots to help explain your problem.

### LINKED ISSUE #2050: [BUG] Legend error: <div> cannot appear as a descendant of <p>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error on all legends in localhost: Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
Comes from legend-layer.tsx - getSecondaryText where we have added in the buttons to what is expected to be only text.

image

image

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Fix map height when map is loaded and legend validate dom nesting error.

Fixes #1995 
Fixes #2050 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/raw-feature-info.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 55 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044#-NwPsmaE2Nq7EOXwsdlq:-NwPsmaE2Nq7EOXwsdlr:b-g1a57j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/450dd8683307bec9efaec507cdfcc35241cc9962/packages/geoview-core/src/core/containers/shell.tsx#L55)):*
> ```XML
> 
>   const { mapViewer } = props;
>   const defaultHeight = 853;
> ```

humm not sure about this... height should come from the div

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 280 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044#-NwPtGL9223HmqInFpwr:-NwPtGL9223HmqInFpws:b-1pxqba) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/450dd8683307bec9efaec507cdfcc35241cc9962/packages/geoview-core/src/core/containers/shell.tsx#L280)):*
> ```XML
>   }, [mapViewer, handleMapRemoveComponent, handleModalOpen]);
> 
>   // console.log('mapViewer', mapViewer);
> ```

Can we remove dead code

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 226 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044#-NwPsIeg8eYb_NIVXFQg:-NwPzC_C3G8e_IpWaS6u:b-ra69yk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/92d9a3c5566680d85e554d6613f9d2efba0afe6d/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L226)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this issue now fix? if se we need to link to PR
</blockquote></details>

I dnt think its a issue here, this comments was add  as NOTE so that we dnt add if we do any refactoring.
___
*[`packages/geoview-core/src/core/containers/containers-style.ts` line 94 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044#-NwPsYF83uyHzczaOTHu:-NwQBbe4CLlfOptrPaSE:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/450dd8683307bec9efaec507cdfcc35241cc9962/packages/geoview-core/src/core/containers/containers-style.ts#L94)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

humm hardcoded height, is it a good idea
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 55 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044#-NwPsmaE2Nq7EOXwsdlq:-NwQBfOHCdb81ZDSOVOX:b-qssebl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/450dd8683307bec9efaec507cdfcc35241cc9962/packages/geoview-core/src/core/containers/shell.tsx#L55)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

humm not sure about this... height should come from the div
</blockquote></details>

fixed.
___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 170 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044#-NwPswsG1phz2WZRmGN2:-NwPyeRY4JYsBtTBpTZM:btlv0uf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/450dd8683307bec9efaec507cdfcc35241cc9962/packages/geoview-core/src/core/containers/shell.tsx#L170)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should come from map div.... if not provided we apply default
</blockquote></details>

This resize values was sitting before in footer-bar, now i have decoupled from footer bar and map will calculate its own and footer bar will calculate its own when we r on mapFullscreen.
___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 280 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044#-NwPtGL9223HmqInFpwr:-NwPyS2t8F5nROf371XR:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/450dd8683307bec9efaec507cdfcc35241cc9962/packages/geoview-core/src/core/containers/shell.tsx#L280)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we remove dead code
</blockquote></details>

Done.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/containers/shell.tsx` line 254 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044#-NwQEkTK-SZrpv2ZddUf:-NwQEkTK-SZrpv2ZddUg:b-ew777c) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9464b26d14224ef9e46038ff10a54bb83033805f/packages/geoview-core/src/core/containers/shell.tsx#L254)):*
> ```XML
> 
>     if (isMapFullScreen && isFooterBarCollapsed && mapContainerRef.current && mapShellContainerRef.current) {
>       mapContainerRef.current.style.minHeight = `${window.screen.height - 72}px`;
> ```

What is 72px here for?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/containers/shell.tsx` line 212 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044#-NwQG2X_BnfB1DW2wefs:-NwQG2X_BnfB1DW2weft:bgtwz1g) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9464b26d14224ef9e46038ff10a54bb83033805f/packages/geoview-core/src/core/containers/shell.tsx#L212)):*
> ```XML
>       const { mapId } = mapViewer;
>       const mapDiv = document.getElementById(mapId)!;
>       setOrigHeight(mapDiv!.clientHeight + 55);
> ```

You might want to leave a comment above this line explaining why we adding 55px.

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044)* status: 3 of 8 files reviewed, 7 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 212 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044#-NwQG2X_BnfB1DW2wefs:-NwQKTmP34NmrggSWqrR:b89kxyi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9464b26d14224ef9e46038ff10a54bb83033805f/packages/geoview-core/src/core/containers/shell.tsx#L212)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

You might want to leave a comment above this line explaining why we adding 55px.
</blockquote></details>

Honestly, even i dnt know why we use 55, i have copy it from footerbar.tsx file.
___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 254 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044#-NwQEkTK-SZrpv2ZddUf:-NwQKGtPBJiz8TO9ms61:b-v0r2bv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9464b26d14224ef9e46038ff10a54bb83033805f/packages/geoview-core/src/core/containers/shell.tsx#L254)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

What is 72px here for?
</blockquote></details>

72 was height of FooterTab container, but now i have update to get the value through getElementById.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044)* status: all files reviewed, 3 unresolved discussions (waiting on @cphelefu and @kaminderpal)

___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 201 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044#-NwQR82s2eQW3LHvGU3o:-NwQR82s2eQW3LHvGU3p:b524ths) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8ad4c71554fd1d49ebd1c9b57a447a44be02c06a/packages/geoview-core/src/core/containers/shell.tsx#L201)):*
> ```XML
>     logger.logTraceUseEffect('SHELL - mapViewer', mapViewer);
> 
>     const mapDiv = document.getElementById(mapId)!;
> ```

We have a store value to get the div. I think we should it then search for what is needed like 
  const geoviewElement = useAppGeoviewHTMLElement().querySelector('\[id^="mapTargetElement-"\]') as HTMLElement;

This way we search inside the map div, not whole document

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2044)* status: all files reviewed, 2 unresolved discussions (waiting on @cphelefu)

**Pull request merged**
