### PR TITLE
2434 point markers

### LINKED ISSUE #2434: [FEATURE] Add functions to add points to the map
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

OSDP

### User Story

Add functions to add/remove points to the map, that don't get removed on click like the click marker. Nice to have multiple styles to use. Grouped by style, able to zoom to one set, all sets, or one point.

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by DamonU2**
# Description

Added point markers to be added to map. They can be added through map config or API calls.

Fixes #2434

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://damonu2.github.io/geoview/demo-function-event.html
Buttons to add and remove markers, and zoom to subset of marker group.

https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/06-basic-footer.json
Markers added through config.

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2447)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2447)* status: all files reviewed, 6 unresolved discussions (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/public/configs/navigator/06-basic-footer.json` line 12 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2447#-O5JP8KK7mTm5yc49zr2:-O5JP8KK7mTm5yc49zr3:b-liudb5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e2001f2c9de9cceaa8b44ddc272d82630d0812d/packages/geoview-core/public/configs/navigator/06-basic-footer.json#L12)):*
> ```JSON
>       "labeled": true
>     },
>     "pointMarkers": {
> ```

Instead of focusing only on point marker, should we have a section geometries and there we can include all type? 

We can put a TODO to add other type, but encapsulating pointMarker in a more global container can be a good idea now
___
*[`packages/geoview-core/public/templates/demos/demo-function-event.html` line 663 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2447#-O5JPTL08L50VxrPb3m3:-O5JPTL08L50VxrPb3m4:bjm95ex) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e2001f2c9de9cceaa8b44ddc272d82630d0812d/packages/geoview-core/public/templates/demos/demo-function-event.html#L663)):*
> ```HTML
>         cgpv.api.maps.Map1.layer.featureHighlight.pointMarkers.zoomToPointMarkersOrGroup('group1', ['1', '3']);
>       });
>   
> ```

White spaces
___
*[`packages/geoview-core/src/api/api.ts` line 135 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2447#-O5JPWAJAn4E9C_x0d3m:-O5JPWAJAn4E9C_x0d3n:b-xjcv7a) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e2001f2c9de9cceaa8b44ddc272d82630d0812d/packages/geoview-core/src/api/api.ts#L135)):*
> ```XML
> 
>   /**
>    * Registers a layer added event handler.
> ```

Description does not match the function title... map vs layers
___
*[`packages/geoview-core/src/core/components/point-markers/point-markers.ts` line 88 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2447#-O5JR6Wu0erOYTrqkWhQ:-O5JR6Wu0erOYTrqkWhR:behmy5v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e2001f2c9de9cceaa8b44ddc272d82630d0812d/packages/geoview-core/src/core/components/point-markers/point-markers.ts#L88)):*
> ```XML
>    * Remove the point markers from the map.
>    */
>   #removePointMarkersFromMap(): void {
> ```

Because this function is  private we should add @private at the end of function description
___
*[`packages/geoview-core/src/core/components/point-markers/point-markers.ts` line 111 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2447#-O5JRLc23JVkQVWVtcRe:-O5JRLc23JVkQVWVtcRf:b2zdb35) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e2001f2c9de9cceaa8b44ddc272d82630d0812d/packages/geoview-core/src/core/components/point-markers/point-markers.ts#L111)):*
> ```XML
>    * @param {string[] | Coordinate[]} idsOrCoordinates - The id or coordinate of the marker to remove.
>    */
>   removePointMarkersOrGroup(group: string, idsOrCoordinates?: string[] | Coordinate[]): void {
> ```

I am not a big fan of function with or. It reduce the number of line but sometimes make it more difficult to understand. I really like when it is explicit. We should have a team discussion about this... We can keep for now but we should be careful in the future
___
*[`packages/geoview-core/src/core/components/point-markers/point-markers.ts` line 147 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2447#-O5JRsp46YeW9j9DqDoR:-O5JRsp46YeW9j9DqDoS:b-rupqyd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e2001f2c9de9cceaa8b44ddc272d82630d0812d/packages/geoview-core/src/core/components/point-markers/point-markers.ts#L147)):*
> ```XML
>   /**
>    * Get the extent of point markers.
>    * @param {string[]} ids - The ids of markers to get the extents of.
> ```

Missing return attribute

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2447)* status: 7 of 18 files reviewed, 6 unresolved discussions (waiting on @jolevesq, @Private, and @ychoquet)

___
*[`packages/geoview-core/public/configs/navigator/06-basic-footer.json` line 12 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2447#-O5JP8KK7mTm5yc49zr2:-O5JbXATDAhhoAgbxRyQ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e2001f2c9de9cceaa8b44ddc272d82630d0812d/packages/geoview-core/public/configs/navigator/06-basic-footer.json#L12)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Instead of focusing only on point marker, should we have a section geometries and there we can include all type? 

We can put a TODO to add other type, but encapsulating pointMarker in a more global container can be a good idea now
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/api.ts` line 135 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2447#-O5JPWAJAn4E9C_x0d3m:-O5JdLSQBT28_x-XslGr:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e2001f2c9de9cceaa8b44ddc272d82630d0812d/packages/geoview-core/src/api/api.ts#L135)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Description does not match the function title... map vs layers
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/point-markers/point-markers.ts` line 88 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2447#-O5JR6Wu0erOYTrqkWhQ:-O5JfUX83mCfyDE5npoN:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e2001f2c9de9cceaa8b44ddc272d82630d0812d/packages/geoview-core/src/core/components/point-markers/point-markers.ts#L88)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Because this function is  private we should add @private at the end of function description
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/point-markers/point-markers.ts` line 111 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2447#-O5JRLc23JVkQVWVtcRe:-O5JfjlE8zBcB6HqMBsH:b-ldpjwu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e2001f2c9de9cceaa8b44ddc272d82630d0812d/packages/geoview-core/src/core/components/point-markers/point-markers.ts#L111)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I am not a big fan of function with or. It reduce the number of line but sometimes make it more difficult to understand. I really like when it is explicit. We should have a team discussion about this... We can keep for now but we should be careful in the future
</blockquote></details>

Split into two functions
___
*[`packages/geoview-core/src/core/components/point-markers/point-markers.ts` line 147 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2447#-O5JRsp46YeW9j9DqDoR:-O5JfjaB0LzRNAgRc4ME:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e2001f2c9de9cceaa8b44ddc272d82630d0812d/packages/geoview-core/src/core/components/point-markers/point-markers.ts#L147)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Missing return attribute
</blockquote></details>

Done.

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2447)* status: 7 of 18 files reviewed, 6 unresolved discussions (waiting on @jolevesq, @Private, and @ychoquet)

___
*[`packages/geoview-core/public/templates/demos/demo-function-event.html` line 663 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2447#-O5JPTL08L50VxrPb3m3:-O5JjzpuEEYjVsOBvmeO:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e2001f2c9de9cceaa8b44ddc272d82630d0812d/packages/geoview-core/public/templates/demos/demo-function-event.html#L663)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

White spaces
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 10 of 11 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2447)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
