### PR TITLE
2425 config api for wms

### LINKED ISSUE #2425: Config API for WMS
This PR is for the first implementation phase of the WMS Config API code.

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

Implementation of the WMS in the config API.

Fixes #2425

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using Chrome Devtools to trace an debug the code with the https://ychoquet.github.io/GeoView/config-sandbox.html template.

__Deploy URL__: https://ychoquet.github.io/GeoView/config-sandbox.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457)* status: all files reviewed, 8 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 1081 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61fL9l4m35sJzHcPsX:-O61fL9m6o9FivLywSxt:bbhkzlu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/config-validation-schema.json#L1081)):*
> ```JSON
>         },
>         "crossOrigin": {
>           "description": "The crossOrigin attribute if needed to load the data (default: Anonymous).",
> ```

If we have default, should it be in the schema as default value?
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 1790 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61fnwo3JPvqoTjjpzS:-O61fnwo3JPvqoTjjpzT:b-8khri6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/config-validation-schema.json#L1790)):*
> ```JSON
>             },
>             "crossOrigin": {
>               "description": "The crossOrigin attribute for loaded images (default: Anonymous). Note that you must provide a crossOrigin value if you want to access pixel data with the Canvas renderer.",
> ```

If default, should we have a default value in the schema
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts` line 14 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61jKMM46_0gF2lpn-r:-O61jKMM46_0gF2lpn-s:b7x47i3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts#L14)):*
> ```XML
> 
> import { logger } from '@/core/utils/logger';
> import { xmlToJson } from '@/app';
> ```

Is the path really @app
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts` line 47 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61joEpE6mNu_qTEqrv:-O61joEpE6mNu_qTEqrw:bhae7my) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts#L47)):*
> ```XML
>   constructor(geoviewLayerConfig: TypeJsonObject, language: TypeDisplayLanguage) {
>     super(geoviewLayerConfig, language);
>     const metadataAccessPathItems = this.metadataAccessPath.split('?Layers=');
> ```

Should it be ?Layers || &Layer car il pourrait avoir version dans le metadata access path. Est ce que c'est case insensitive?
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts` line 55 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61kAGE0Z_sXSMEA9BA:-O61kAGE0Z_sXSMEA9BB:blgipsx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts#L55)):*
> ```XML
>       if (this.listOfLayerEntryConfig.length) {
>         this.setErrorDetectedFlag();
>         logger.logError('When an WMS metadataAccessPath ends with a layer index, the listOfLayerEntryConfig must be  empty.');
> ```

Not sure, if we ask for layers in getCap and we cant have a listOfLAyerEntry... how can we apply user settings
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts` line 89 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61kR1M7VE7MkddcPWl:-O61kR1M7VE7MkddcPWm:b5au8kq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts#L89)):*
> ```XML
>    * @param {TypeDisplayLanguage} language The initial language to use when interacting with the geoview layer.
>    * @param {AbstractGeoviewLayerConfig} geoviewConfig The GeoView instance that owns the sublayer.
>    * @param {EntryConfigBaseClass} parentNode The The parent node that owns this layer or undefined if it is the root layer..
> ```

Double ..
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts` line 110 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61kWRfEA46UfA41-ZA:-O61kWRfEA46UfA41-ZB:b5au8kq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts#L110)):*
> ```XML
>    * @param {TypeDisplayLanguage} language The initial language to use when interacting with the geoview layer.
>    * @param {AbstractGeoviewLayerConfig} geoviewConfig The GeoView instance that owns the sublayer.
>    * @param {EntryConfigBaseClass} parentNode The The parent node that owns this layer or undefined if it is the root layer..
> ```

Double ..
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts` line 340 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61mC7m2l_EaHL_Yibk:-O61mC7m2l_EaHL_Yibl:bh99xe6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts#L340)):*
> ```XML
>    * This method fetch the service metadata using a getCapabilities&Layers= request. To allow geomet service metadata to be
>    * retrieved using the "Layers" parameter in the request URL, we need to process each layer individually and merge all layer
>    * metadata at the end. Even though the "Layers" parameter is ignored by other WMS servers, the drawback of this method is
> ```

CAn geomet has more then one layers in in LAYERS parameter?

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457)* status: 25 of 27 files reviewed, 8 unresolved discussions (waiting on @app and @jolevesq)

___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 1081 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61fL9l4m35sJzHcPsX:-O62p0cT1Dd1kfKOhOW9:b-yw1v8f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/config-validation-schema.json#L1081)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If we have default, should it be in the schema as default value?
</blockquote></details>

Done. I also corrected all other defaults
___
*[`packages/geoview-core/src/api/config/types/config-validation-schema.json` line 1790 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61fnwo3JPvqoTjjpzS:-O62p7P55XR5kZMtxph5:b-yw1v8f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/config-validation-schema.json#L1790)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If default, should we have a default value in the schema
</blockquote></details>

Done. I also corrected all other defaults
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts` line 14 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61jKMM46_0gF2lpn-r:-O62_GBE1HyFqvzJmPM0:bi600qo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is the path really @app
</blockquote></details>

Done. The path is @/core/utils/utilities.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts` line 47 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61joEpE6mNu_qTEqrv:-O62V9JvDvsbaVDJNImX:b-k2d8zb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts#L47)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should it be ?Layers || &Layer car il pourrait avoir version dans le metadata access path. Est ce que c'est case insensitive?
</blockquote></details>

I use  ***?Layers=*** because ***?*** is the separator between the URL and the parameters section.
The ***?Layers=*** is removed to keep only the service URL in the metadataAccessPath. The layerId folowing ***?Layers=*** is transferred to the listOfLayerEntryConfig. All these frills are coded to handle the huge geomet service metadata that would otherwise crash the viewer.

Maybe I should use a regex to make the detection case insensitive.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts` line 55 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61kAGE0Z_sXSMEA9BA:-O62_rV15px0c2uHNIMs:b-iy20du) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts#L55)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Not sure, if we ask for layers in getCap and we cant have a listOfLAyerEntry... how can we apply user settings
</blockquote></details>

These are two seperate use cases. The user should only add ***?Layers=*** to the metadataAccessPath when using ***Add New Layer*** in the UI, to avoid the one-and-a-half-minute response time and subsequent GeoView crash  when calculating and displaying the layer tree. In other cases, this parameter is handled entirely by the code, so the user doesn't have to worry about this detail.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts` line 89 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61kR1M7VE7MkddcPWl:-O62frzDCHHx0jyOT4aZ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts#L89)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Double ..
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts` line 110 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61kWRfEA46UfA41-ZA:-O62g8cCBzx6B0NfYyEf:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts#L110)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Double ..
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts` line 340 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61mC7m2l_EaHL_Yibk:-O62gBjwBJ4tPkOHTWZu:b8cn8vk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts#L340)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

CAn geomet has more then one layers in in LAYERS parameter?
</blockquote></details>

No, I tried and got an error message saying that use of more than one layer is not supported for the moment.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts` line 47 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61joEpE6mNu_qTEqrv:-O62tnrE5iLLk_zuDkEo:b-4ep81y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts#L47)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I use  ***?Layers=*** because ***?*** is the separator between the URL and the parameters section.
The ***?Layers=*** is removed to keep only the service URL in the metadataAccessPath. The layerId folowing ***?Layers=*** is transferred to the listOfLayerEntryConfig. All these frills are coded to handle the huge geomet service metadata that would otherwise crash the viewer.

Maybe I should use a regex to make the detection case insensitive.
</blockquote></details>

I think so because if I have url?service=WMS&layers=myLayer it will not work

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457)* status: 26 of 27 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts` line 47 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61joEpE6mNu_qTEqrv:-O64Z0UG5Lvvxjx4VeCP:bs4tnck) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts#L47)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think so because if I have url?service=WMS&layers=myLayer it will not work
</blockquote></details>

Done. It now uses a regex.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457)* status: 26 of 27 files reviewed, 1 unresolved discussion (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts` line 47 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61joEpE6mNu_qTEqrv:-O66gUF_9pVDmmaevoi5:b-kzlv0u) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts#L47)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Done. It now uses a regex.
</blockquote></details>

What if url?service=WMS&layers=test&request=getCapabilities

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457)* status: 26 of 27 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts` line 47 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457#-O61joEpE6mNu_qTEqrv:-O66vrZxBrLFpCzjvABq:b-84zk1f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e106402e6919bb61c62fb4ee0f2ce3e884b29f8b/packages/geoview-core/src/api/config/types/classes/geoview-config/raster-config/wms-config.ts#L47)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

What if url?service=WMS&layers=test&request=getCapabilities
</blockquote></details>

You don't have to provide service=WMS and/or request=getCapabilities. This is done internally by the code.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2457)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
