### PR TITLE
refactor(layerOrder): add flags to layerOrder

### LINKED ISSUE #1621: [FEATURE] Layer No Remove
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

As a map creator, I would like to have layers on the but that are not removable

### Implementation UI

Add a layer flag to the schema to say a layer is not removable. When this flag is set to true, the layer item is disable when we are in remove mode. On the right panel, there is explanation for disable mode.

This flag should be in the store and we should have action in store layer-state to change this flag for a layer path. This function should use the legend event processor and and be available on layers object

Layer removal flag should be apply at group and children level....
- group and children removable
- group removable only
- no removable

### LINKED ISSUE #1722: [REFACTOR] Combine layerOrder & Visibility
**Is there an existing issue for this?**
Please search to see if an issue already exists for the bug you encountered.
no

**Current Behavior**
A concise description of what you're experiencing.
We have 2 array to manage order and visibility

**Expected Behavior**
A concise description of what you expected to happen.
We need one array in the mapState store that has the order of layers path and flag associated wit it.
[ "layerPath": "visibile": true, "removable": true, "queryable": true, "hoverable": true ,...]

This array is use by legend, details, and other component to know the order, state and capacity of each of the layer path...

**Steps To Reproduce**

**Anything else?**
References? Anything that will give us more context about the issue you are encountering and if applicable, add screenshots to help explain your problem.

### LINKED ISSUE #1781: [BUG] layers added through the add-layers panel not added to layer-order
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a layer is added through the add layers panel in the layers tab, it is not added to the layer order

### Expected Behavior

Layer should be added in layer order in the first spot

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #1781
Closes #1722
Closes #1621 

# Description

layerOrder and visibleLayers in map state are combined in orderedLayerInfo, an ordered list of objects with layerPath, visible, queryable, removable properties. Layers added through add-layers are added to the front of the list, and are removed if the layer is removed. Layers tagged with removable: false can not be removed. Geocore layers are not currently added to the array.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested reordering, adding and reordering layers in various maps.

https://damonu2.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
> Reviewed 8 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831)* status: 8 of 31 files reviewed, 4 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/schema.json` line 589 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831#-NrB3dHUB4KcdXJvJGV9:-NrB3dHUB4KcdXJvJGVA:bi3cvqg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2c79ed0575779ac08021c83d96a919494998bc4e/packages/geoview-core/schema.json#L589)):*
> ```JSON
>           "type": "boolean",
>           "description": "Is the layer hoverable."
>         }
> ```

We should add query able to schema?
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 196 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831#-NrB6u5V65GoVNCMk7VV:-NrB6u5W3XEjs-h16Eto:b-x3ynn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc1b7b62eb2cb8c9baa61912a1770c0406d3e571/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L196)):*
> ```XML
>           styleConfig: legendResultsSetEntry.data?.styleConfig,
>           type: legendResultsSetEntry.data?.type,
>           isVisible: layerConfig.initialSettings?.visible || 'yes',
> ```

This was the link for UI to toggle icon I think
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 395 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831#-NrB7A9v49Jc90g88BR7:-NrB7A9v49Jc90g88BR8:bxrsdrl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2c79ed0575779ac08021c83d96a919494998bc4e/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L395)):*
> ```XML
> 
>   static setMapHoverable(mapId: string, layerPath: string, hoverable: boolean): void {
>     this.getMapStateProtected(mapId).actions.setHoverable(layerPath, hoverable);
> ```

Should we need setMapLayerRemovable  should all be named mapLayer"state" because it is related to a layer on the map
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 407 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831#-NrB7iO92pzYRw2U2LQz:-NrB7iO92pzYRw2U2LR-:b-avc4ym) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2c79ed0575779ac08021c83d96a919494998bc4e/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L407)):*
> ```XML
> 
>   static setOrToggleMapVisibilty(mapId: string, layerPath: string, newValue?: TypeVisibilityFlags): void {
>     this.getMapStateProtected(mapId).actions.setOrToggleLayerVisibility(layerPath, newValue);
> ```

Having visibility not a boolean and not acting like other is confusing. We should have visible state true/false and .... visibilityFreeze true or false to let ui decide if visibility can be toggle from ui.

What do you think?

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831)* status: 4 of 33 files reviewed, 4 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/schema.json` line 589 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831#-NrB3dHUB4KcdXJvJGV9:-NrBpixcBnS_6EymwJy5:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2c79ed0575779ac08021c83d96a919494998bc4e/packages/geoview-core/schema.json#L589)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should add query able to schema?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 395 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831#-NrB7A9v49Jc90g88BR7:-NrBptG167Eq_xkB4Fxc:b-qc7k06) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2c79ed0575779ac08021c83d96a919494998bc4e/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L395)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we need setMapLayerRemovable  should all be named mapLayer"state" because it is related to a layer on the map
</blockquote></details>

I don't think we'll need removable, it seems like it would be set in config and never changed. I've updated the names of the others.

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831)* status: 4 of 33 files reviewed, 4 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts` line 407 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831#-NrB7iO92pzYRw2U2LQz:-NrCBg8A3pmjF9R8Oiz_:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2c79ed0575779ac08021c83d96a919494998bc4e/packages/geoview-core/src/api/event-processors/event-processor-children/map-event-processor.ts#L407)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Having visibility not a boolean and not acting like other is confusing. We should have visible state true/false and .... visibilityFreeze true or false to let ui decide if visibility can be toggle from ui.

What do you think?
</blockquote></details>

Done.

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831)* status: all files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 833 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831#-NrCHODl2WTiVn5y3h6q:-NrCJDJa2BTOnOwtUGFf:b-r1la1v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ab4542742a90f1cb29b341e47618a16afe135ec3/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L833)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

We probably want to add this call where we process the layers that are added via the api core functions (instead of just via this user interface). Maybe move this call inside addGeoviewLayer (called just above)?
</blockquote></details>

I process the layers from the config before they are added to the map, to keep them in the config order. They would be called twice if added to addGeoviewLayer.

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831)* status: all files reviewed, 7 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 833 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831#-NrCHODl2WTiVn5y3h6q:-NrCOSEP-K1z3M5pPlBD:b-ne4p5m) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ab4542742a90f1cb29b341e47618a16afe135ec3/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L833)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

I process the layers from the config before they are added to the map, to keep them in the config order. They would be called twice if added to addGeoviewLayer.
</blockquote></details>

Ok, though I'm curious to see how it's "kept in the config order" when a layer is added outside of the add-new-layer UI.
If it's tested then ignore me.

Also, make sure to add the call in the `else if` as well (5 lines below once you've rebased).

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831)* status: 28 of 33 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 833 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831#-NrCHODl2WTiVn5y3h6q:-NrCjvch7Lynk3sRWxgg:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ab4542742a90f1cb29b341e47618a16afe135ec3/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L833)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Ok, though I'm curious to see how it's "kept in the config order" when a layer is added outside of the add-new-layer UI.
If it's tested then ignore me.

Also, make sure to add the call in the `else if` as well (5 lines below once you've rebased).
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 858 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831#-NrCHg_vDNHoq4aVjjgn:-NrCjwAJ7cYG27ljptwW:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ab4542742a90f1cb29b341e47618a16afe135ec3/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L858)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Same comment as above, don't know if should be insde `addToMap` instead of `addGeoviewLayer` here? Ideally in one place if possible.
</blockquote></details>

Done.

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831)* status: all files reviewed, 5 unresolved discussions (waiting on @DamonU2 and @jolevesq)

**Review by DamonU2 — COMMENTED** [review]
Me too!

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831#-:-NrCpWCF61hFMKMH6rhU:b6k8ys0)* status: all files reviewed, 5 unresolved discussions (waiting on @jolevesq)

**Review by jolevesq — APPROVED** [review]
> Reviewed 8 of 31 files at r1, 7 of 9 files at r3, 10 of 13 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2)

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831)* status: 21 of 33 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts` line 67 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831#-NrCGb8R300zZV25A9-N:-NrHioIR3-yCpmCkVT4U:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ab4542742a90f1cb29b341e47618a16afe135ec3/packages/geoview-core/src/core/stores/store-interface-and-intial-values/map-state.ts#L67)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

As discussed, maybe we want a 'visibleLayers' somewhere that only triggers when actual visibility has changed. If not in this PR, maybe add a TODO were applicable.
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 5 of 7 files at r6, 7 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831)* status: 23 of 33 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 7 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831)* status: 30 of 33 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 7 files at r6, 1 of 8 files at r8.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1831)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

**Pull request merged**
