### PR TITLE
fix(config): fixed bug with config validation

### LINKED ISSUE #2632: [BUG] Zoom to Extent from Config Failed - JIRA 1852
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we try to refresh a map and use initial view extent setting, it fails because it tries to get the zoomAndCenter and it does not exist. Try this initial setting
```
 "viewSettings": {
      "initialView": { "extent": [ -63.17068832713632, 47.54397873973516, -47.11323060823711, 48.06148308033754 ] },
      "enableRotation": true,
      "rotation": 0,
      "minZoom": 0,
      "maxZoom": 50,
      "maxExtent": [ -135, 25, -50, 89 ],
      "projection": 3978
    }
```

It will have this error
```
hook.js:608 08:27:39.403 ConfigApi.createMapConfig - An error occured TypeError: Cannot read properties of undefined (reading '1')
    at e.qn (map-feature-config.ts:247:53)
```

### Expected Behavior

We should be able to only use the extent initial setting

### Steps To Reproduce

1. Go to https://canadian-geospatial-platform.github.io/geoview/public/sandbox.html
2. Set the setting above
3. See the error

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #2632

# Description

Config validation was assuming values for zoomAndCenter in config, this is no longer assumed. Also removed mapId value from createMapConfigFromMapState to better line up with what is expected in reload.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://damonu2.github.io/geoview/sandbox.html
With:
{
"mapId": "mapWM",
"map": {
"basemapOptions": {
"basemapId": "transport",
"shaded": true,
"labeled": true
},
"interaction": "dynamic",
"listOfGeoviewLayerConfig": [],
"highlightColor": "black",
"overlayObjects": { "pointMarkers": {} },
"viewSettings": {
"initialView": { "extent": [ -63.17068832713632, 47.54397873973516, -47.11323060823711, 48.06148308033754 ] },
"enableRotation": true,
"rotation": 0,
"minZoom": 0,
"maxZoom": 50,
"maxExtent": [ -135, 25, -50, 89 ],
"projection": 3978
}
},
"theme": "[GEO.ca Language Selection - GEO.CA](http://geo.ca/) ",
"navBar": [ "zoom", "fullscreen", "home", "basemap-select" ],
"footerBar": {
"tabs": {
"core": [ "legend", "layers", "details", "data-table" ],
"custom": []
},
"collapsed": false,
"selectedTab": "legend"
},
"appBar": {
"tabs": { "core": [ "geolocator" ] },
"selectedTab": "",
"collapsed": false
},
"overviewMap": { "hideOnZoom": 0 },
"components": [ "north-arrow", "overview-map" ],
"corePackages": [],
"externalPackages": [],
"serviceUrls": {
"geocoreUrl": "https://geocore.api.geo.ca/",
"geolocator": "[https://geolocator.api.geo.ca?keys=geonames,nominatim,locate](https://geolocator.api.geo.ca/?keys=geonames,nominatim,locate)",
"proxyUrl": "https://maps.canada.ca/wmsproxy/ws/wmsproxy/executeFromProxy"
},
"schemaVersionUsed": "1.0"
}

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2635)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2635)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 216 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2635#-ODN8nY-CJ4wUZjEaPSD:-ODN8nY00mbHriat04dM:bkl4j6d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9859c4fd4bd6220b904ab43dc5e47221e826a755/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L216)):*
> ```XML
>         : CV_DEFAULT_MAP_FEATURE_CONFIG.map.viewSettings.projection;
> 
>     // TODO: add validation for extent and layerIds
> ```

Is it something we can do quick as part of this PR?
___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 63 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2635#-ODN970xCLIkgWQTyd-0:-ODN970xCLIkgWQTyd-1:b-lflfnx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9859c4fd4bd6220b904ab43dc5e47221e826a755/packages/geoview-core/src/api/config/types/map-schema-types.ts#L63)):*
> ```XML
>   | 'data-table'
>   | 'layers'
>   | '';
> ```

We can put empty string or it is for when the array is empty?

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2635)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 63 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2635#-ODN970xCLIkgWQTyd-0:-ODNDT_k6mh3LN9rDYQ2:b-ioamqj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9859c4fd4bd6220b904ab43dc5e47221e826a755/packages/geoview-core/src/api/config/types/map-schema-types.ts#L63)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We can put empty string or it is for when the array is empty?
</blockquote></details>

With enum, the array cannot be empty. It's basically just to simplify creating the config from state

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2635)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2635)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2)

**Review by jolevesq — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2635#-:-ODNb-FWAJmwWywy_d7b:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2635)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
