### PR TITLE
refactor(theme): Create a custom theme

### LINKED ISSUE #3: Create a custom theme
Create a custom theme for the application to reuse in the different components (https://material-ui.com/customization/theming/)

[ ] Palette
[ ] Typography
[ ] Spacing
[ ] Breakpoints for UI
[ ] z-index
[ ] Globals

We can have any values for some of the classes like we do care which typo we will use for the moment. Pick one and we will modify later. The important thing here is to have those values inside a global theme and this theme will be use trough the application. When we will modify the theme later, the values will apply automatically to the element.

Part of this issue or may be extract on is own, we will need  documentation page to explain how to use it inside the component.

### PR DESCRIPTION
**Pull request by yass0016**
Closes #3

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
Can you apply a margin right to the navbar group of buttons. If I compare to my demo page, the margin has been lost (https://jolevesq.github.io/GeoView/index.html).

> Reviewed 13 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34#-:-MRVbg0eCl00iAUTh5kI:b-3v4baq)* status: 13 of 15 files reviewed, 4 unresolved discussions (waiting on @yass0016)

___
*[public/index.html, line 14 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34#-MRVXQ9q8hhwl1MCE5zo:-MRVXQ9rDFrNthzFQnP7:bhocq81) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2f7b4a464762cf054ddf88f220ca85f36fbb99a1/public/index.html#L14)):*
> ```HTML
>         />
> 
>         <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
> ```

Instead of having this link inside index.html, can bundle it with Webpack? 
___
*[public/css/style.css, line 11 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34#-MRVajmv5a072Ox0MgQ_:-MRVajmv5a072Ox0MgQa:bdk8gxk) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2f7b4a464762cf054ddf88f220ca85f36fbb99a1/public/css/style.css#L11)):*
> ```CSS
> .leaflet-container {
>     display: flex;
>     width: 100%;
> ```

Can you put the map not 100%. Make it difficult to scroll. 90% or 80% should be fine.
___
*[src/assests/style/theme.tsx, line 65 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34#-MRVYK6x9wq_xTLzjG_d:-MRVYK6yA7RUGFRCEXFo:bkl7660) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2f7b4a464762cf054ddf88f220ca85f36fbb99a1/src/assests/style/theme.tsx#L65)):*
> ```XML
>     zIndex: {
>         mobileStepper: 1000,
>         speedDial: 1050,
> ```

Is this used? Same for snackBar?
___
*[src/components/navbar/button.tsx, line 11 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34#-MRVa4U_EMnI-Bd5GhGh:-MRVa4Ua13XSKZbwggIv:buz0nmn) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2f7b4a464762cf054ddf88f220ca85f36fbb99a1/src/components/navbar/button.tsx#L11)):*
> ```XML
> 
> const useStyles = makeStyles((theme) =>
>     createStyles({
> ```

For my information, what is the difference between makeStyle and createStyle and why are you using it here?

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34)* status: 10 of 15 files reviewed, 4 unresolved discussions (waiting on @jolevesq)

___
*[public/index.html, line 14 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34#-MRVXQ9q8hhwl1MCE5zo:-MRVf-_NAzbklKp6RhaZ:b-3voouh) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2f7b4a464762cf054ddf88f220ca85f36fbb99a1/public/index.html#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Instead of having this link inside index.html, can bundle it with Webpack? 
</blockquote></details>

I am not sure what you mean by bundle it with webpack, isn't index.html already distributed from webpack. We are also importing the Roboto font just above this line
___
*[public/css/style.css, line 11 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34#-MRVajmv5a072Ox0MgQ_:-MRVfy333WSgqSbPSlyl:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2f7b4a464762cf054ddf88f220ca85f36fbb99a1/public/css/style.css#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put the map not 100%. Make it difficult to scroll. 90% or 80% should be fine.
</blockquote></details>

Done.
___
*[src/assests/style/theme.tsx, line 65 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34#-MRVYK6x9wq_xTLzjG_d:-MRVdBnt6IV1RjAEQQe2:bt32ae5) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2f7b4a464762cf054ddf88f220ca85f36fbb99a1/src/assests/style/theme.tsx#L65)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this used? Same for snackBar?
</blockquote></details>

No but they are the default values from zIndex. They are there if we need them later. Lets see if I need them when I do issue #2
___
*[src/components/navbar/button.tsx, line 11 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34#-MRVa4U_EMnI-Bd5GhGh:-MRVeJ0BC1cBBN0QRLRq:b-yrm95f) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2f7b4a464762cf054ddf88f220ca85f36fbb99a1/src/components/navbar/button.tsx#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

For my information, what is the difference between makeStyle and createStyle and why are you using it here?
</blockquote></details>

createStyle is not required here. I was part of the code from panel.tsx so I used it here but I read now, its not required. I will probably take it out here and in panel.tsx

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34)* status: 10 of 15 files reviewed, 4 unresolved discussions (waiting on @jolevesq)

___
*[public/index.html, line 14 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34#-MRVXQ9q8hhwl1MCE5zo:-MRVgUW-7oE4FC9Vc6qp:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2f7b4a464762cf054ddf88f220ca85f36fbb99a1/public/index.html#L14)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

I am not sure what you mean by bundle it with webpack, isn't index.html already distributed from webpack. We are also importing the Roboto font just above this line
</blockquote></details>

Done.
___
*[src/assests/style/theme.tsx, line 65 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34#-MRVYK6x9wq_xTLzjG_d:-MRVgSlf1F2vo07sbVpH:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2f7b4a464762cf054ddf88f220ca85f36fbb99a1/src/assests/style/theme.tsx#L65)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

No but they are the default values from zIndex. They are there if we need them later. Lets see if I need them when I do issue #2
</blockquote></details>

Done.
___
*[src/components/navbar/button.tsx, line 11 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34#-MRVa4U_EMnI-Bd5GhGh:-MRVgRih2-nW4trh6gA9:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2f7b4a464762cf054ddf88f220ca85f36fbb99a1/src/components/navbar/button.tsx#L11)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

createStyle is not required here. I was part of the code from panel.tsx so I used it here but I read now, its not required. I will probably take it out here and in panel.tsx
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 15 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34)* status: 13 of 15 files reviewed, 2 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[public/index.html, line 14 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34#-MRVXQ9q8hhwl1MCE5zo:-MRVgCzMCFpWprHLN0RE:b-cbfufk) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2f7b4a464762cf054ddf88f220ca85f36fbb99a1/public/index.html#L14)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Index page is just a sample page and may not be use in distribution. App dependencies are part of the bundle, I just wonder is this can be the case. If not we should document needed dependencies on html page when we create one.

**Review by yass0016 — COMMENTED** [review]
I updated the margin

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34#-:-MRVh4SR3sr7p4rG09Ph:bcigtby)* status: 13 of 16 files reviewed, 2 unresolved discussions (waiting on @jolevesq and @yass0016)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 15 files at r1, 1 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/34)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
