### PR TITLE
feat(ESRI Feature): query optimization

### LINKED ISSUE #2396: [FEATURE] Fetch ESRI Features in parallel
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Geoview team

### User Story

Update the fetch for features from ESRI Feature service to run in parallel

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #2396

# Description

Updates ESRI feature loader to do multiple concurrent fetches. Number of fetches and features fetched can be modified.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://damonu2.github.io/geoview/outlier-ESRI-maxRecordCount.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2397)

### CODE REVIEW

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2397)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 279 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2397#-O2VolLj7I0ie4ucbOYq:-O2VolLk-C9wZWWXshpJ:bo4ljo0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/405dbbf79a19f7096307138d416cde984e5afc2e/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L279)):*
> ```XML
>    * @param {string} url - The base url for the service.
>    * @param {number} featureCount - The number of features in the layer.
>    * @param {number} featureLimit - The maximum number of features to fetch per query.
> ```

Could you add 'maxRecordCount' as @param comments?

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2397)* status: all files reviewed, 2 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 291 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2397#-O2Vs3116VMPlrC0LtYw:-O2Vs3116VMPlrC0LtYx:bzgwck4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/405dbbf79a19f7096307138d416cde984e5afc2e/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L291)):*
> ```XML
>     url: string,
>     featureCount: number,
>     maxRecordCount?: number,
> ```

Not sure how I feel about having an optional parameter by 4th and then having optional/defaulted parameters by 5th and 6th. I think this can lead to errors/confusion when method is called. Could maxRecordCount be 6th parameter?

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2397)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @jolevesq, and @param)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 279 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2397#-O2VolLj7I0ie4ucbOYq:-O2W-8XR6MVyp-ZydQyn:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/405dbbf79a19f7096307138d416cde984e5afc2e/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L279)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Could you add 'maxRecordCount' as @param comments?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 291 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2397#-O2Vs3116VMPlrC0LtYw:-O2W-90D3n0RD_hgPFNe:b-kkhnjg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/405dbbf79a19f7096307138d416cde984e5afc2e/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L291)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Not sure how I feel about having an optional parameter by 4th and then having optional/defaulted parameters by 5th and 6th. I think this can lead to errors/confusion when method is called. Could maxRecordCount be 6th parameter?
</blockquote></details>

Typescript forces this, it gives errors the other way.

**Review by jolevesq — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2397)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @param)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2397)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @param)

**Pull request merged**
