### PR TITLE
fix(layer-selection) Pre select the previously selected layer in left panel

### LINKED ISSUE #1376: {REFACTOR} Details use store
Create a store interface for details component

### PR DESCRIPTION
**Pull request by amir-azma**
# Description

We need to use store management in our Details tab. Also, the left panel selected layer should be the same as our previous layer selected.

Fixes #1376 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://amir-azma.github.io/geoview/raw-feature-info-1.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @amir-azma and @cphelefu)

___
*[`packages/geoview-core/src/core/components/details/details.tsx` line 26 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhWUga3-v2COqy8xhsj:-NhWUga3-v2COqy8xhsk:b-kw4yvc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1f51512e1faff6dd681beef8982977d360172bc/packages/geoview-core/src/core/components/details/details.tsx#L26)):*
> ```XML
> export function DetailsFooter({ arrayOfLayerData, mapId }: TypeDetailsProps): JSX.Element | null {
>   const store = getGeoViewStore(mapId);
>   const { storeArrayOfLayerData } = useStore(store, (state) => state.detailsState);
> ```

It is better to not use deconstruction like this: const expanded = useStore(store, (state) => state.footerBarState.expanded);
___
*[`packages/geoview-core/src/core/components/details/layers-list-footer.tsx` line 59 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhWVPtODG8J9Z4O4zK2:-NhWVPtODG8J9Z4O4zK3:b4ojp4h) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1f51512e1faff6dd681beef8982977d360172bc/packages/geoview-core/src/core/components/details/layers-list-footer.tsx#L59)):*
> ```XML
> 
>   const store = getGeoViewStore(mapId);
>   const { storeCurrentFeatureIndex, storeSelectedLayerPath, setStoreCurrentFeatureIndex } = useStore(store, (state) => state.detailsState);
> ```

No object deconstruction: https://stackoverflow.com/questions/68609189/fetching-multiple-states-with-zustand-react-shorthand-syntax
___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 96 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhWWhAC3BJf2RYwWx20:-NhWWhAC3BJf2RYwWx21:b1ur8jg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1f51512e1faff6dd681beef8982977d360172bc/packages/geoview-core/src/core/stores/geoview-store.ts#L96)):*
> ```XML
>   storeArrayOfLayerData: TypeArrayOfLayerData;
>   storeSelectedLayerPath: string;
>   setStoreCurrentFeatureIndex: (newFeatureIndex: number) => void;
> ```

I do not think you need this function, you can set the value storeCurrentFEatureIndex directly

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/details/details.tsx` line 26 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhWUga3-v2COqy8xhsj:-NhWvuLb79dNtcE14SwQ:b-ms0ald) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1f51512e1faff6dd681beef8982977d360172bc/packages/geoview-core/src/core/components/details/details.tsx#L26)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It is better to not use deconstruction like this: const expanded = useStore(store, (state) => state.footerBarState.expanded);
</blockquote></details>

@jolevesq I think this is possible; it can be done in zunstand according to the documentation.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/details/layers-list-footer.tsx` line 59 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhWVPtODG8J9Z4O4zK2:-NhWwFBu2C9VDBhjRJmI:b-fwpg7a) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1f51512e1faff6dd681beef8982977d360172bc/packages/geoview-core/src/core/components/details/layers-list-footer.tsx#L59)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

No object deconstruction: https://stackoverflow.com/questions/68609189/fetching-multiple-states-with-zustand-react-shorthand-syntax
</blockquote></details>

Can we also remove setStoreFeatureIndex from the store? Whydo we need it in the store?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 96 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhWWhAC3BJf2RYwWx20:-NhWwZ8VELUTmAdrCnWb:b8c56sg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1f51512e1faff6dd681beef8982977d360172bc/packages/geoview-core/src/core/stores/geoview-store.ts#L96)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I do not think you need this function, you can set the value storeCurrentFEatureIndex directly
</blockquote></details>

No need to start every variables with `store`. Rename to currentFeatureIndex, arrayOfLayerData, selectedLayerPath.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhWwteR-oV21Ph-0iXu:-NhWwteR-oV21Ph-0iXv:bychwn9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1f51512e1faff6dd681beef8982977d360172bc/packages/geoview-core/src/core/stores/geoview-store.ts#L17)):*
> ```XML
> import { TypeMapFeaturesConfig, TypeValidMapProjectionCodes } from '@/core/types/global-types';
> import { TypeLegendItemProps } from '../components/legend-2/types';
> import { TypeArrayOfLayerData } from '../components/details/details';
> ```

The store does not need to depend on component for anything. This type should be in the store file or in another location, but not in a component file. We may need to discuss this one (maybe we need a central `types` folder).

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 209 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhWxSMw2x9udg21_4fz:-NhWxSMw2x9udg21_4g-:b-xxkqhl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1f51512e1faff6dd681beef8982977d360172bc/packages/geoview-core/src/core/stores/geoview-store.ts#L209)):*
> ```XML
>           detailsState: {
>             ...get().detailsState,
>             storeCurrentFeatureIndex: newFeatureIndex,
> ```

This method can be removed from the store.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @amir-azma and @cphelefu)

___
*[`packages/geoview-core/src/core/components/details/details.tsx` line 26 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhWUga3-v2COqy8xhsj:-NhWzHs07nP8Q0SKYC8T:b942mny) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1f51512e1faff6dd681beef8982977d360172bc/packages/geoview-core/src/core/components/details/details.tsx#L26)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

@jolevesq I think this is possible; it can be done in zunstand according to the documentation.
</blockquote></details>

But the store will listen to changes in the whole interface detailsState, it is best practice to specify the attribute.
https://github.com/pmndrs/zustand#fetching-everything
https://stackoverflow.com/questions/68609189/fetching-multiple-states-with-zustand-react-shorthand-syntax

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/details/details.tsx` line 26 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhWUga3-v2COqy8xhsj:-NhX4xC3BFylmpPSuSC3:b-x8v2at) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1f51512e1faff6dd681beef8982977d360172bc/packages/geoview-core/src/core/components/details/details.tsx#L26)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

But the store will listen to changes in the whole interface detailsState, it is best practice to specify the attribute.
https://github.com/pmndrs/zustand#fetching-everything
https://stackoverflow.com/questions/68609189/fetching-multiple-states-with-zustand-react-shorthand-syntax
</blockquote></details>

I was going to pass 'shallow' as third param to useState, but vs code gives me warning that using 'shallow' is deprecated', like this 
but the main reason to use object deconstruction is the main detailsState is holding an object of states, if it was primitives like string or boolean, then yes we didn't need deconstruction, then we could use like this :  const nuts \= useBearStore((state) \=> state.nuts)

'

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 96 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhWWhAC3BJf2RYwWx20:-NhXG6sU0t85EOGucs7p:byjrnb5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1f51512e1faff6dd681beef8982977d360172bc/packages/geoview-core/src/core/stores/geoview-store.ts#L96)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

No need to start every variables with `store`. Rename to currentFeatureIndex, arrayOfLayerData, selectedLayerPath.
</blockquote></details>

I though we needed to know where this variable is coming from, if it's from useState() or it's coming from store, yeah I can remove the store prefix

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 209 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhWxSMw2x9udg21_4fz:-NhXGl3V2ZMbfFpuqNJq:b-gso9g1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1f51512e1faff6dd681beef8982977d360172bc/packages/geoview-core/src/core/stores/geoview-store.ts#L209)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

This method can be removed from the store.
</blockquote></details>

I think we can discuss about what needs to be in store, because in dataTable store, we have so many functions and states, but the main concept of store is to use the state in store in other components, I mean if the state X can be used in other components, then we add X to store

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhWwteR-oV21Ph-0iXu:-NhXIGRD7r-uNPJ_rJlY:bcomva1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1f51512e1faff6dd681beef8982977d360172bc/packages/geoview-core/src/core/stores/geoview-store.ts#L17)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

The store does not need to depend on component for anything. This type should be in the store file or in another location, but not in a component file. We may need to discuss this one (maybe we need a central `types` folder).
</blockquote></details>

Yes, I agree, there are some types that are defined inside the component, we may need to move it outside

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/details/layers-list-footer.tsx` line 59 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhWVPtODG8J9Z4O4zK2:-NhXy2WlBigIwFYqAOZO:b-li2klu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1f51512e1faff6dd681beef8982977d360172bc/packages/geoview-core/src/core/components/details/layers-list-footer.tsx#L59)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Can we also remove setStoreFeatureIndex from the store? Whydo we need it in the store?
</blockquote></details>

Removed setStoreFeatureIndex and related states.
___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhWwteR-oV21Ph-0iXu:-NhXyCKe9qJZVEwYzqJT:b-u5kgqx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1f51512e1faff6dd681beef8982977d360172bc/packages/geoview-core/src/core/stores/geoview-store.ts#L17)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

Yes, I agree, there are some types that are defined inside the component, we may need to move it outside
</blockquote></details>

For now we keep the type in component, we discussed in standup today that we're going to clean the types from components in future.

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 96 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhWWhAC3BJf2RYwWx20:-NhY-MSUC7rNXzbFY-O-:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1f51512e1faff6dd681beef8982977d360172bc/packages/geoview-core/src/core/stores/geoview-store.ts#L96)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

I though we needed to know where this variable is coming from, if it's from useState() or it's coming from store, yeah I can remove the store prefix
</blockquote></details>

Done
___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 209 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhWxSMw2x9udg21_4fz:-NhY-KiBB5lr_oAhx7tM:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1f51512e1faff6dd681beef8982977d360172bc/packages/geoview-core/src/core/stores/geoview-store.ts#L209)):*
<details><summary><i>Previously, amir-azma wrote…</i></summary><blockquote>

I think we can discuss about what needs to be in store, because in dataTable store, we have so many functions and states, but the main concept of store is to use the state in store in other components, I mean if the state X can be used in other components, then we add X to store
</blockquote></details>

Done

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432)* status: all files reviewed, 3 unresolved discussions (waiting on @amir-azma and @cphelefu)

___
*[`packages/geoview-core/src/core/components/details/layers-list-footer.tsx` line 147 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhY0KLOAZMmJ6WtmvsN:-NhY0KLOAZMmJ6WtmvsO:b-e1tvaq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2be27be6453cc7ae4b10e5185735d8b74e402f71/packages/geoview-core/src/core/components/details/layers-list-footer.tsx#L147)):*
> ```XML
>   useEffect(() => {
>     if (arrayOfLayerData.length > 0) {
>       // Check if have the previouse selected layer path in incoming arrayOfLayerData
> ```

Typo previous

**Review by cphelefu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432)* status: all files reviewed, 1 unresolved discussion (waiting on @amir-azma)

**Review by amir-azma — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/details/layers-list-footer.tsx` line 147 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432#-NhY0KLOAZMmJ6WtmvsN:-NhY2cl-EBs02y7VbNbL:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2be27be6453cc7ae4b10e5185735d8b74e402f71/packages/geoview-core/src/core/components/details/layers-list-footer.tsx#L147)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Typo previous
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1432)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amir-azma)

**Pull request merged**
