### PR TITLE
849 turn on off layer feature

### LINKED ISSUE #849: [FEATURE] Turn on and off layer's feature from style
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

As a user, I would like to be able to turn on and off features inside a layer from their style information.

The PR #827 and #837 added the back end functionalities. There is sample on https://canadian-geospatial-platform.github.io/geoview/public/layers.html#HLYR3 and https://canadian-geospatial-platform.github.io/geoview/public/layers.html#HLYR5. The information should be part of the legend event. Use it to build the ui in the legend core component so it is reusable in footer panel and layers panel.

### Implementation UI

Actual implementation
image

Add the check box toggle visibility of inner style to core legend component (section in red)

### PR DESCRIPTION
**Pull request by dennisfu**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #849

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

got to footer panel, in legend tab, exptend the footer panel, click the visible icon beside item icon/lebal, would toggle the icon and theshowing/hide the lengend item on map

# Checklist:

- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

some extra time for the rebase confliction solving and the layer indetification

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/909)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
Like in the issue, the toggle visibility for layer sub item should be a checkbox

Issue on toggling. Go to footer-panel page, on map 3. Turn of layer visibility then toggle the first sub item fresh net. Both fresh net and unknown are now visible. Should only be fresh net.

> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/909#-:-NOPHcVC6tqWxm5mlyRJ:b336i8l)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @dennisfu and @ychoquet)

___
*[`packages/geoview-core/src/core/components/legend/legend-item.tsx` line 194 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/909#-NOPJdY_EsZXlYmkKsIq:-NOPJdY_EsZXlYmkKsIr:bhes4aa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/601935da60f7e32a2685b4c03e26992bd4538fca/packages/geoview-core/src/core/components/legend/legend-item.tsx#L194)):*
> ```XML
>     geoviewLayerInstance?.getLegend(subLayerId).then((layerLegend) => {
>       const { geoviewLayerId } = geoviewLayerInstance;
>       // console.log(layerLegend, geoviewLayerInstance);
> ```

Remove dead code

**Comment by dennisfu** [comment]
1. removed the comment line
2. fixed the toggle issues. the reason is in some config, it showing the defaultvalue as the last item ( like the polygon in map1)

**Comment by dennisfu** [comment]
rebased

**Comment by dennisfu** [comment]
@jolevesq The issue is from ESRI layer config, in the style, the default value and label are undefined instead of unknown or null, so it doesn't loaded into the label list, also cannot find the image info to put into the icon list.  So I think we should merge this for now and create a new issue.

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/909)* status: all files reviewed, 2 unresolved discussions (waiting on @dennisfu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/legend/legend-icon-list.tsx` line 65 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/909#-NOk6IG16sLlUPnvZDU3:-NOk6IG22Wv4RUOQTm9S:b-8fbtck) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/28d1dc3f5fdb100f6bd21902fda600f27bf35a38/packages/geoview-core/src/core/components/legend/legend-icon-list.tsx#L65)):*
> ```XML
>   const [isChecked, setChecked] = useState<boolean[]>(isParentVisible === true ? allChecked : allUnChecked);
>   const [checkedCount, setCheckCount] = useState<number>(isParentVisible === true ? iconImages.length : 0);
>   const [initPV, setInitPV] = useState(isParentVisible);
> ```

The project best practice mention that we should avoid usage of acronyms in the variable and function names. So, it is preferable to say initParentVisible and setInitParentVisible. PV is ambiguous. It can means Panel Visibility, or Plain Validation or many other things. Someone new to the project can't know easily what initPV refers to.

**Comment by dennisfu** [comment]
done

**Comment by dennisfu** [comment]
rebased

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 3 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/909)* status: all files reviewed, 1 unresolved discussion (waiting on @dennisfu)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/909)* status: all files reviewed, 1 unresolved discussion (waiting on @dennisfu)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/909)* status: all files reviewed, 1 unresolved discussion (waiting on @dennisfu)

**Review by ychoquet — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/909)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dennisfu)

**Pull request merged**
