### PR TITLE
Issue #2488 - Refresh GeoCore Layers on Language Change

### PR DESCRIPTION
**Pull request by MatthewMuehlhauserNRCan**
# Description

Added functionality to the setLanguage function in the map-view to reset the GeoCore layers so they are reloaded in the correct language when available. 

Also added a Reset layers check box to the navigator page to test through the UI.

Fixes # 2488

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Tested using the new Checkbox and also in the command line. 

Note: Legend order isn't maintained, however; the layer order in the layer tab is.
New Issue: #2611 setMapOrderedLayerInfo isn't applying the visibility to the map 

[Navigator - GeoCore Config](https://matthewmuehlhausernrcan.github.io/geoview/demos-navigator.html?config=./configs/navigator/27-geocore-custom.json)
[Navigator - All Layers Config](https://matthewmuehlhausernrcan.github.io/geoview/demos-navigator.html?config=./configs/navigator/13-all-layers.json)

# Checklist:

- [X] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [X] I have connected the issues(s) to this PR
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @DamonU2 and @MatthewMuehlhauserNRCan)

___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 933 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCEneDREFsMPIEJLePI:-OCEneDSDZbgKqlTfG4O:bxy0h4f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc1eb882e9b9a16218f14cd557047bb7e25d4d63/packages/geoview-core/src/geo/map/map-viewer.ts#L933)):*
> ```XML
>       const promise = AppEventProcessor.setDisplayLanguage(this.mapId, displayLanguage);
> 
>       // if flag is true, check if config support the layers change and apply
> ```

Wew canc hange the comment as we do not support language in config, just say if flag to reset layer is true
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 936 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCEnDVwDrKX6ciafT0d:-OCEnDVwDrKX6ciafT0e:bcsv0sk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc1eb882e9b9a16218f14cd557047bb7e25d4d63/packages/geoview-core/src/geo/map/map-viewer.ts#L936)):*
> ```XML
> 
>       if (resetLayer) {
>         const re = /[\w\d]{8}-[\w\d]{4}-[\w\d]{4}-[\w\d]{4}-[\w\d]{12}/;
> ```

What is this for? From your comment it is to filter the geoCore layer type. There is a layerType in layerConfig with the geoCore value. You may want to use this instead/
___
*[`packages/geoview-core/src/ui/style/style.css` line 42 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCEn8idDV1-nUjl-8XI:-OCEn8ieA_hI1XNQEc2c:bufk95n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc1eb882e9b9a16218f14cd557047bb7e25d4d63/packages/geoview-core/src/ui/style/style.css#L42)):*
> ```CSS
> 
> /* smooth data table scrolling */
> .MuiTableContainer-root {
> ```

Nice add on, the scrolling is much better and faster

**Review by jolevesq — COMMENTED** [review]
vs



I think you need to unregister layer from layer set first and then re add them.. The remove layer should do it but seems in problem. Plus i first image, the firts layer has not change...

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-:-OCEoDa79wZzVisrc-tL:bwujksx)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @DamonU2 and @MatthewMuehlhauserNRCan)

**Review by MatthewMuehlhauserNRCan — COMMENTED** [review]
I think that the Major Projects Inventory layer is working as intended. I don't think there's a translation for it:

Here is the request for that UUID:
https://geocore.api.geo.ca/vcs?lang=fr&id=ea4c0bdb-a63f-49a4-b14a-09c1560aad0b

And this is the WMS that it gives you:
https://openmaps.gov.bc.ca/geo/pub/WHSE_HUMAN_CULTURAL_ECONOMIC.MPI_ECON_MAJOR_PROJECTS_POINT/ows?request=GetCapabilities&service=WMS

And this is the title for the layer:


> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-:-OCEyE_YEaYjcBhsEsc1:brucaqk)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 933 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCEneDREFsMPIEJLePI:-OCF-1ND5S_j0YS5ecXR:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc1eb882e9b9a16218f14cd557047bb7e25d4d63/packages/geoview-core/src/geo/map/map-viewer.ts#L933)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Wew canc hange the comment as we do not support language in config, just say if flag to reset layer is true
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 936 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCEnDVwDrKX6ciafT0d:-OCF0FlU5ZAqYLp8BjLi:b-qh1gpi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc1eb882e9b9a16218f14cd557047bb7e25d4d63/packages/geoview-core/src/geo/map/map-viewer.ts#L936)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

What is this for? From your comment it is to filter the geoCore layer type. There is a layerType in layerConfig with the geoCore value. You may want to use this instead/
</blockquote></details>

That's correct. I'm currently looking in the configs from the "getLayerEntryConfigs()" and I'm not seeing a layerType or any geoCore value. Should I be looking somewhere else?

**Comment by MatthewMuehlhauserNRCan** [comment]
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 955 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCFb5xbADR3dvlRWCXC:-OCFb5xbADR3dvlRWCXD:bpwjg71) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc1eb882e9b9a16218f14cd557047bb7e25d4d63/packages/geoview-core/src/geo/map/map-viewer.ts#L955)):*
> ```XML
>               const uuid = config.geoviewLayerConfig.geoviewLayerId.match(re)![0];
>               this.layer.removeLayerUsingPath(config.layerPath);
>               return this.layer.addGeoviewLayerByGeoCoreUUID(uuid);
> ```

Because I'm adding the layer directly after, could this be causing some of the odd behaviors? Maybe it hasn't fully finished removing the layer and it's already starting the processes to add it back in, which may explain the variety of different possible behaviors? What would be the best way to deal with this? Is there an event or something I can wait for?

**Review by DamonU2 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610)* status: all files reviewed, 3 unresolved discussions (waiting on @jolevesq and @MatthewMuehlhauserNRCan)

___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 936 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCEnDVwDrKX6ciafT0d:-OCJRlEG5HVHZN8aMQwO:b-86saq0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc1eb882e9b9a16218f14cd557047bb7e25d4d63/packages/geoview-core/src/geo/map/map-viewer.ts#L936)):*
<details><summary><i>Previously, MatthewMuehlhauserNRCan wrote…</i></summary><blockquote>

That's correct. I'm currently looking in the configs from the "getLayerEntryConfigs()" and I'm not seeing a layerType or any geoCore value. Should I be looking somewhere else?
</blockquote></details>

There is a function in the config-api for this: isValidUUID
You can use api.config.isValidUUID(config.geoviewLayerConfig.geoviewLayerId)
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 955 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCFb5xbADR3dvlRWCXC:-OCJSl1d8qHRE7O8YtoM:b61s7bo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc1eb882e9b9a16218f14cd557047bb7e25d4d63/packages/geoview-core/src/geo/map/map-viewer.ts#L955)):*
<details><summary><i>Previously, MatthewMuehlhauserNRCan wrote…</i></summary><blockquote>

Because I'm adding the layer directly after, could this be causing some of the odd behaviors? Maybe it hasn't fully finished removing the layer and it's already starting the processes to add it back in, which may explain the variety of different possible behaviors? What would be the best way to deal with this? Is there an event or something I can wait for?
</blockquote></details>

You could test this with a timeout, if it is what's causing issues, you can listen to onLayerRemoved

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @MatthewMuehlhauserNRCan)

___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 936 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCEnDVwDrKX6ciafT0d:-OCcbiVW-VRbPI_4GOHR:b-uc2upe) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc1eb882e9b9a16218f14cd557047bb7e25d4d63/packages/geoview-core/src/geo/map/map-viewer.ts#L936)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

There is a function in the config-api for this: isValidUUID
You can use api.config.isValidUUID(config.geoviewLayerConfig.geoviewLayerId)
</blockquote></details>

You need to go to parent level to get layerType. entry config is the layer entry and does not have the info

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @DamonU2 and @MatthewMuehlhauserNRCan)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 569 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCcc1gu9bPxhjtQ2gA3:-OCcc1gvCGrxPDBxEylC:bstomu4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7fa9e4a887a01775c16199af3890610eb18169f6/packages/geoview-core/src/geo/layer/layer.ts#L569)):*
> ```XML
>    */
>   refreshGeocoreLayers(): Promise<void> {
>     const configs = this.getLayerEntryConfigs();
> ```

From the layerEntryConfig you can have access to the parent config who as thelayerType

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610)* status: all files reviewed, 5 unresolved discussions (waiting on @DamonU2 and @MatthewMuehlhauserNRCan)

___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 933 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCEneDREFsMPIEJLePI:-OCmpBMk90aLhaOucypa:b-unv6w7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc1eb882e9b9a16218f14cd557047bb7e25d4d63/packages/geoview-core/src/geo/map/map-viewer.ts#L933)):*
<details><summary><i>Previously, MatthewMuehlhauserNRCan wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Modify comment for // If flag is true, reload geocore layers
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 566 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCmph90AEfV8YrmEISu:-OCmph90AEfV8YrmEISv:b-1yp5b9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5e673249964c1f0323cc2de461173f88a17055e2/packages/geoview-core/src/geo/layer/layer.ts#L566)):*
> ```XML
>    * @returns {Promise<void>} A promise which resolves when done refreshing
>    */
>   refreshGeocoreLayers(): Promise<void> {
> ```

Would call it reloadGeocoreLayer as it remove and add. We have a refresh function who just reinit states.
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 934 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCmqlujDeBEByuUGZVp:-OCmqlujDeBEByuUGZVq:bg381pf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5e673249964c1f0323cc2de461173f88a17055e2/packages/geoview-core/src/geo/map/map-viewer.ts#L934)):*
> ```XML
> 
>       // if flag is true, check if config support the layers change and apply
>       if (resetLayer) {
> ```

Same comment as above for naming. We should call the flag reload

**Review by MatthewMuehlhauserNRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610)* status: 8 of 11 files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 566 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCmph90AEfV8YrmEISu:-OCnhke_EhVFYCx3PPfg:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5e673249964c1f0323cc2de461173f88a17055e2/packages/geoview-core/src/geo/layer/layer.ts#L566)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Would call it reloadGeocoreLayer as it remove and add. We have a refresh function who just reinit states.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 933 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCEneDREFsMPIEJLePI:-OCnhte8-o3GALGxc9yz:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc1eb882e9b9a16218f14cd557047bb7e25d4d63/packages/geoview-core/src/geo/map/map-viewer.ts#L933)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Modify comment for // If flag is true, reload geocore layers
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 936 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCEnDVwDrKX6ciafT0d:-OCniMeh-7Gl0p78Bwbx:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc1eb882e9b9a16218f14cd557047bb7e25d4d63/packages/geoview-core/src/geo/map/map-viewer.ts#L936)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You need to go to parent level to get layerType. entry config is the layer entry and does not have the info
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 955 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCFb5xbADR3dvlRWCXC:-OCniYcW0lyfZcGAMSd9:b-co03mh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fc1eb882e9b9a16218f14cd557047bb7e25d4d63/packages/geoview-core/src/geo/map/map-viewer.ts#L955)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

You could test this with a timeout, if it is what's causing issues, you can listen to onLayerRemoved
</blockquote></details>

Was an issue with layers not being unregistered from the layer path array in the layerSets. There is a new issue with the visibility not being updated in the map which is likely being caused by the 'MapEventProcessor.setMapOrderedLayerInfo(this.getMapId(), originalMapOrderedLayerInfo);' being called before the layers are fully loaded. There is another issue for this.
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 934 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCmqlujDeBEByuUGZVp:-OCniAoI7za4IXeBJMaJ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5e673249964c1f0323cc2de461173f88a17055e2/packages/geoview-core/src/geo/map/map-viewer.ts#L934)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same comment as above for naming. We should call the flag reload
</blockquote></details>

Done.

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 7 files at r2, 7 of 8 files at r3, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610)* status: 9 of 11 files reviewed, 7 unresolved discussions (waiting on @DamonU2, @jolevesq, and @MatthewMuehlhauserNRCan)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 586 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCnV3tY5Gq0HWqF34c-:-OCnV3tY5Gq0HWqF34c0:byb9toc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5e673249964c1f0323cc2de461173f88a17055e2/packages/geoview-core/src/geo/layer/layer.ts#L586)):*
> ```XML
>       });
> 
>     return Promise.allSettled(promisesOfGeoCoreGeoviewLayers)
> ```

When using `allSettled()` Promise, be mindful that the objects being promised include both `PromiseFulfilledResult` and `PromiseRejectedResult` types.

Which means, if you want to `map` on the results, you shouldn't force cast any `promise`object to a `PromiseFulfilledResult<>` necessarily. If you only want the promises which fulfilled *and ignore the others*, I'd suggest that you filter the promises ahead of time.

You may take a look at the other `allSettled()` call in the same file, in function `loadListOfGeoviewLayer` where a `.filter((promise) 
 => promise.status === 'fulfilled')` is made before the `map`.
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 927 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCnYhph0-yL7duiBooS:-OCnYhph0-yL7duiBooT:b-4y2w5v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5e673249964c1f0323cc2de461173f88a17055e2/packages/geoview-core/src/geo/map/map-viewer.ts#L927)):*
> ```XML
>    * @returns {Promise<[void, void]>}
>    */
>   setLanguage(displayLanguage: TypeDisplayLanguage, resetLayer?: boolean | false): Promise<[void, void]> {
> ```

That comment isn't related to this PR in itself, but I'd suggest adding a TODO to eventually fix this: `Promise<[void, void]>` which looks like a code smell to me.
Indeed, I fail to see a reason we'd want to carry an array of void elements. Should likely be switched to return a simple Promise<void> inside `AppEventProcessor.setDisplayLanguage()` instead. It'd fix some odd writing of `[undefined, undefined]` that you had to do.

**Review by MatthewMuehlhauserNRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610)* status: 9 of 11 files reviewed, 7 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 586 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCnV3tY5Gq0HWqF34c-:-OCnwPv8-1zwzmEp3tDR:b-kdp64s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5e673249964c1f0323cc2de461173f88a17055e2/packages/geoview-core/src/geo/layer/layer.ts#L586)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

When using `allSettled()` Promise, be mindful that the objects being promised include both `PromiseFulfilledResult` and `PromiseRejectedResult` types.

Which means, if you want to `map` on the results, you shouldn't force cast any `promise`object to a `PromiseFulfilledResult<>` necessarily. If you only want the promises which fulfilled *and ignore the others*, I'd suggest that you filter the promises ahead of time.

You may take a look at the other `allSettled()` call in the same file, in function `loadListOfGeoviewLayer` where a `.filter((promise) 
 => promise.status === 'fulfilled')` is made before the `map`.
</blockquote></details>

Added the filter in as well. This was partly due to testing and trying to figure out why the layers weren't being added back in properly. While working on Issue 2611, I can look into simplifying this section as well as looking into your other comment.
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 927 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610#-OCnYhph0-yL7duiBooS:-OCnyWh_7gvM30ftOdn_:bxikn90) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5e673249964c1f0323cc2de461173f88a17055e2/packages/geoview-core/src/geo/map/map-viewer.ts#L927)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

That comment isn't related to this PR in itself, but I'd suggest adding a TODO to eventually fix this: `Promise<[void, void]>` which looks like a code smell to me.
Indeed, I fail to see a reason we'd want to carry an array of void elements. Should likely be switched to return a simple Promise<void> inside `AppEventProcessor.setDisplayLanguage()` instead. It'd fix some odd writing of `[undefined, undefined]` that you had to do.
</blockquote></details>

Will look into this while working on Issue 2611

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2610)* status: all files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

**Pull request merged**
