### PR TITLE
663 details comp fixing

### PR DESCRIPTION
**Pull request by dennisfu**
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r2, 3 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: 4 of 16 files reviewed, 3 unresolved discussions (waiting on @dennisfu)

___
*[`packages/geoview-core/src/core/components/details/details.tsx` line 18 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJewHcY0MjUS9Kiunwb:-NJewHcY0MjUS9Kiunwc:bhsv723) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/details.tsx#L18)):*
> ```XML
> 
> /**
>  * The Details component is used to display a list of layers and their content.
> ```

We should modify the definition. It is more to display selected features information
___
*[`packages/geoview-core/src/core/components/details/details-api.ts` line 35 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJewglq2yfzY7tlsqKb:-NJewglq2yfzY7tlsqKc:b-ax0jog) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/details-api.ts#L35)):*
> ```XML
> 
>   /**
>    * Create a data grid
> ```

Change for details
___
*[`packages/geoview-core/src/core/components/details/details-api.ts` line 41 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJex453AiaicIEBiAb_:-NJex453AiaicIEBiAba:b1u2luo) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/details-api.ts#L41)):*
> ```XML
>    *
>    */
>   createDetails = (mapId: string, detailsElements: TypeArrayOfLayerData) => {
> ```

You need to add the return type of the function... : ReactElement

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: 4 of 16 files reviewed, 5 unresolved discussions (waiting on @dennisfu)

___
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 2 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJexFVo4uif90sFdtqL:-NJexFVo4uif90sFdtqM:bhes4aa) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/feature-info.tsx#L2)):*
> ```XML
> import React, { useState } from 'react';
> // import { useTranslation } from 'react-i18next';
> ```

Remove dead code
___
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 4 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJexJ1yEN1J7MgVN_Zj:-NJexJ1yEN1J7MgVN_Zk:b3d65wj) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/feature-info.tsx#L4)):*
> ```XML
> // import { useTranslation } from 'react-i18next';
> import Box from '@mui/material/Box';
> import makeStyles from '@mui/styles/makeStyles';
> ```

I think make style is deprecated @dayc-mapdev may help if you have question. We need to use sxClasses like layers and data-grid

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: 4 of 16 files reviewed, 5 unresolved discussions (waiting on @dennisfu)

___
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 4 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJexJ1yEN1J7MgVN_Zj:-NJexyhX20k8KWkuYhPv:b-2nsbk4) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/feature-info.tsx#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think make style is deprecated @dayc-mapdev may help if you have question. We need to use sxClasses like layers and data-grid
</blockquote></details>

I see you are using sxClasses, just remove the makeStyle import

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: 4 of 16 files reviewed, 8 unresolved discussions (waiting on @dennisfu)

___
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 22 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJey951-UAcqKBh83Yz:-NJey951-UAcqKBh83Z-:bhes4aa) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/feature-info.tsx#L22)):*
> ```XML
>   details: {
>     width: '100%',
>     // maxWidth: 350, // for testing panel width
> ```

Remove dead code
___
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 29 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJeyR-M3cLRubUhDVZX:-NJeyR-M3cLRubUhDVZY:b5llp3m) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/feature-info.tsx#L29)):*
> ```XML
>   },
>   expandableGroup: {
>     paddingRight: 0,
> ```

Do we have these information in our theme as the component look and feel should be pretty similar to the layer component @dayc-mapdev? If not we will create an issue for it.
___
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 45 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJeyiOrDKM_vENnyeaz:-NJeyiOrDKM_vENnyeb-:b-vqul77) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/feature-info.tsx#L45)):*
> ```XML
> };
> 
> const useStyles = makeStyles(() => ({
> ```

Make style is deprecated

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: 4 of 16 files reviewed, 10 unresolved discussions (waiting on @dennisfu)

___
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 107 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJeyqVs9MNlrDy4g1J5:-NJeyqVs9MNlrDy4g1J6:b-1kvurl) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/feature-info.tsx#L107)):*
> ```XML
> export function FeatureInfo(props: TypeFeatureProps): JSX.Element {
>   const { feature } = props;
>   const featureId = 'OBJECTID' in feature.featureInfo ? feature.featureInfo.OBJECTID : feature.featureKey;
> ```

We should not use OBJECTID in key as only ESRI has it. We should use our own custom key value
___
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 127 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJezHOlDniXy1s2lSRV:-NJezHOlDniXy1s2lSRW:bco1zhc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/feature-info.tsx#L127)):*
> ```XML
>             {
>               // loop through each layer in the map server
>               Object.keys(feature.featureInfo).map((featureKey, index) => {
> ```

Can we make this with loop like https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/packages/geoview-core/src/core/components/legend/legend-item.tsx#L423 and avoid return statement inside the return

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: 5 of 16 files reviewed, 13 unresolved discussions (waiting on @dennisfu)

___
*[`packages/geoview-core/src/core/components/details/layers-list.tsx` line 3 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJezYeP5nEEOn0fMHha:-NJezYeP5nEEOn0fMHhb:bhes4aa) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/layers-list.tsx#L3)):*
> ```XML
> /* eslint-disable react/require-default-props */
> import React, { useState } from 'react';
> // import { useTranslation } from 'react-i18next';
> ```

Remove dead code
___
*[`packages/geoview-core/src/core/components/details/layers-list.tsx` line 4 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJezhOt9CHHXRVhh3OJ:-NJezhOt9CHHXRVhh3OK:b9j1dbi) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/layers-list.tsx#L4)):*
> ```XML
> import React, { useState } from 'react';
> // import { useTranslation } from 'react-i18next';
> import Box from '@mui/material/Box';
> ```

Do we have this component in our ui component? If not we should create an issue to add it.
___
*[`packages/geoview-core/src/core/components/details/layers-list.tsx` line 44 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJezsP_24rA0rTVP73m:-NJezsP_24rA0rTVP73n:bfre4qn) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/layers-list.tsx#L44)):*
> ```XML
>   },
> };
> interface TypeLayersListProps {
> ```

Add blank line between const and interface

**Review by dayc-mapdev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: 5 of 16 files reviewed, 13 unresolved discussions (waiting on @dayc-mapdev, @dennisfu, and @jolevesq)

___
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 4 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJexJ1yEN1J7MgVN_Zj:-NJeycuw9h0dDD2B-1A7:b-13lifb) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/feature-info.tsx#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I see you are using sxClasses, just remove the makeStyle import
</blockquote></details>

Yes, move the makeStyles into sxClasses. Then change divs and spans like this



_Code snippet:_
```XML
<div className=classname> ==>  <Box sx=sxclassname> 
and
 <span className=classname> ==> <Box component="span" sx=sxclassname>
```
___
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 29 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJeyR-M3cLRubUhDVZX:-NJf-pCrANuGpix8QTkl:bh0l8xq) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/feature-info.tsx#L29)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we have these information in our theme as the component look and feel should be pretty similar to the layer component @dayc-mapdev? If not we will create an issue for it.
</blockquote></details>

No, lets create an issue for it. We could possibly move it into List/ListItem UI elements or the theme.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: 5 of 16 files reviewed, 15 unresolved discussions (waiting on @dayc-mapdev and @dennisfu)

___
*[`packages/geoview-core/src/core/components/details/layers-list.tsx` line 55 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJezzHn8_18LcHO_Jcs:-NJezzHn8_18LcHO_Jct:bhes4aa) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/layers-list.tsx#L55)):*
> ```XML
> export function LayersList(props: TypeLayersListProps): JSX.Element {
>   const { arrayOfLayerData } = props;
>   // const { t, i18n } = useTranslation<string>();
> ```

Remove dead code
___
*[`packages/geoview-core/src/core/components/details/layers-list.tsx` line 57 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJf0Yyg2YCp9MZIqSPk:-NJf0Yyg2YCp9MZIqSPl:bhes4aa) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/layers-list.tsx#L57)):*
> ```XML
>   // const { t, i18n } = useTranslation<string>();
>   const [layerSetOpen, setLayerSetOpen] = useState<string>('');
>   // const [layerOpen, setLayerOpen] = useState<string>('');
> ```

Remove dead code

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: 6 of 16 files reviewed, 19 unresolved discussions (waiting on @dayc-mapdev and @dennisfu)

___
*[`packages/geoview-footer-panel/src/details-item.tsx` line 22 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJf1gJF70ypQ5_zkIdo:-NJf1gJF70ypQ5_zkIdp:bteexty) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-footer-panel/src/details-item.tsx#L22)):*
> ```XML
>   const { useState, useEffect } = react;
> 
>   const [details, setDetails] = useState<TypeArrayOfLayerData>([{ layerPath: '', layerName: '', features: [] }]);
> ```

You can reuse the type you are using in your real detail component, this was just added for testing purpose.
___
*[`packages/geoview-footer-panel/src/details-item.tsx` line 44 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJf1yaX7_mX7EksLKYG:-NJf1yaX7_mX7EksLKYH:buo9nmt) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-footer-panel/src/details-item.tsx#L44)):*
> ```XML
>             setDetails(newDetails);
>           } else {
>             setDetails([{ layerPath: '', layerName: '', features: [] }]);
> ```

Same here
___
*[`packages/geoview-footer-panel/src/details-item.tsx` line 59 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJf257U9WB_sCvJUaNc:-NJf257U9WB_sCvJUaNd:bhes4aa) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-footer-panel/src/details-item.tsx#L59)):*
> ```XML
>   }, []);
> 
>   // useEffect(() => {
> ```

Remove dead code

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: 6 of 16 files reviewed, 23 unresolved discussions (waiting on @dayc-mapdev and @dennisfu)

___
*[`packages/geoview-footer-panel/src/index.tsx` line 96 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJf2Cs53gBhPdE5Rcsa:-NJf2Cs53gBhPdE5Rcsb:b-jgnclf) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-footer-panel/src/index.tsx#L96)):*
> ```XML
> 
>       // create the listener to return the details
>       // TODO: layer path are not define when layer is created, no result are assigned
> ```

Remove as it is solve now
___
*[`packages/geoview-footer-panel/src/index.tsx` line 97 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJf2FBs6vDuDq9vdY2S:-NJf2FBs6vDuDq9vdY2T:bhes4aa) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-footer-panel/src/index.tsx#L97)):*
> ```XML
>       // create the listener to return the details
>       // TODO: layer path are not define when layer is created, no result are assigned
>       // const myLayerSet = api.createFeatureInfoLayerSet(mapId, `${mapId}resultSetId`);
> ```

Remove dead code
___
*[`packages/geoview-footer-panel/src/index.tsx` line 138 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJf2Mf17eD4q1y0wpDO:-NJf2Mf17eD4q1y0wpDP:bakakg5) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-footer-panel/src/index.tsx#L138)):*
> ```XML
>    */
>   removed(): void {
>     // const { mapId } = this.pluginProps;
> ```

Keep code, remove //
___
*[`packages/geoview-footer-panel/src/index.tsx` line 145 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJf2SHU7jrMuhzS4x3s:-NJf2SHU7jrMuhzS4x3t:bakakg5) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-footer-panel/src/index.tsx#L145)):*
> ```XML
>     if (cgpv) {
>       // access the api calls
>       // const { api } = cgpv;
> ```

Keep code, remove //

**Review by dayc-mapdev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: 6 of 16 files reviewed, 23 unresolved discussions (waiting on @dayc-mapdev, @dennisfu, and @jolevesq)

___
*[`packages/geoview-core/src/core/components/details/layers-list.tsx` line 4 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJezhOt9CHHXRVhh3OJ:-NJf2teqEtekYKxRWtZ0:by93rh) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/layers-list.tsx#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we have this component in our ui component? If not we should create an issue to add it.
</blockquote></details>

Yes, it is in our ui/layout

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: 10 of 16 files reviewed, 25 unresolved discussions (waiting on @dayc-mapdev, @dennisfu, @param, and @ychoquet)

___
*[`packages/geoview-core/src/core/components/details/layers-list.tsx` line 4 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747#-NJezhOt9CHHXRVhh3OJ:-NJf_5A0DY54gpQXarOr:b1wery1) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5613df11d7d92dd4616d6210bd74902aff3cc374/packages/geoview-core/src/core/components/details/layers-list.tsx#L4)):*
<details><summary><i>Previously, dayc-mapdev (Chris Day) wrote…</i></summary><blockquote>

Yes, it is in our ui/layout
</blockquote></details>

Dennis, can you use the one from our ui.

**Comment by dennisfu** [comment]
> 

@jolevesq committed updates for the commends changing required, please review

**Comment by dennisfu** [comment]
> > 
> 
> @jolevesq committed updates for the commends changing required, please review

@jolevesq Done

**Comment by dennisfu** [comment]
@jolevesq Done

**Review by ychoquet — COMMENTED** [review]
> Reviewed 2 of 6 files at r4, 5 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: all files reviewed, 25 unresolved discussions (waiting on @dayc-mapdev, @dennisfu, @jolevesq, and @param)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 6 files at r4, 3 of 6 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: all files reviewed, 5 unresolved discussions (waiting on @dennisfu)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 14 files at r3, 1 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: all files reviewed, 4 unresolved discussions (waiting on @dennisfu)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 14 files at r3, 1 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: all files reviewed, 2 unresolved discussions (waiting on @dennisfu)

**Review by ychoquet — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dennisfu)

**Comment by dennisfu** [comment]
added #750 fixing and rebased

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 14 files at r3, 6 of 21 files at r7, 1 of 7 files at r8, 3 of 15 files at r9.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: 11 of 23 files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> Reviewed 12 of 15 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/747)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dennisfu)

**Pull request merged**
