### PR TITLE
1016-Improve-loading-time

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

This PR eliminates the spinning wheel. Layers are displayed as soon as they are loaded. However, the code only applies to successfully loaded layers.A new issue "Run init for all maps #1128" was created to handle loading error.

Fixes:
#1016 Improve loading time
#1064 [BUG] Loading big layer ( > 10 seconds )

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using the chrome devTools to trace the loading of all layers to make sure the layerState and layerPhase are set properly. All layer's template have been updated to display le layer's phase above the map, beside the title.

URL to my deploy: https://ychoquet.github.io/GeoView/type-of-layers.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
- [x] I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 33 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129)* status: 33 of 35 files reviewed, 10 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/public/templates/layers/esri-dynamic.html` line 69 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZa-Xxl80JfObYCQesY:-NZa-Xxl80JfObYCQesZ:b-520uxy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e697c4f8074961d87fb47d79a369d396517b92/packages/geoview-core/public/templates/layers/esri-dynamic.html#L69)):*
> ```HTML
>     <div class="map-title-holder">
>       <h4 id="HLYR1">1. Many ESRI Dynamic Layers with legend settings in the config</h4>
>       &nbsp;<h5 id="HLYR1-state">(undefined)</h5>
> ```

Weird problem.... until first click hover does not work properly. Mouse location is not at the mouse cursor. On first click the click marker is offset lower the cursor. After first click it is working fine.
___
*[`packages/geoview-core/public/templates/layers/esri-feature.html` line 406 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZ_xCo7ABicj_oegZIV:-NZ_xCo7ABicj_oegZIW:b-405ul0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e697c4f8074961d87fb47d79a369d396517b92/packages/geoview-core/public/templates/layers/esri-feature.html#L406)):*
> ```HTML
>         'LYR3/$LegendsLayerSet$'
>       );
>       
> ```

Remove white spaces. Should have been modified by the prettier run on rush build...
___
*[`packages/geoview-core/public/templates/layers/geojson.html` line 247 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZ_xR663NRYkpfzSCh3:-NZ_xR663NRYkpfzSCh4:b-vjv3mt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e697c4f8074961d87fb47d79a369d396517b92/packages/geoview-core/public/templates/layers/geojson.html#L247)):*
> ```HTML
>         'LYR1/$LegendsLayerSet$'
>       );
>       
> ```

Remove white spaces
___
*[`packages/geoview-core/public/templates/layers/geopackage.html` line 231 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZ_xUv39fR8f7b1vhp-:-NZ_xUv39fR8f7b1vhp0:b-vjv3mt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e697c4f8074961d87fb47d79a369d396517b92/packages/geoview-core/public/templates/layers/geopackage.html#L231)):*
> ```HTML
>         'LYR1/$LegendsLayerSet$'
>       );
>       
> ```

Remove white spaces
___
*[`packages/geoview-core/public/templates/layers/image-static.html` line 159 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZ_xWK84QN-sYfcMBsN:-NZ_xWK84QN-sYfcMBsO:b-vjv3mt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e697c4f8074961d87fb47d79a369d396517b92/packages/geoview-core/public/templates/layers/image-static.html#L159)):*
> ```HTML
>         'LYR1/$LegendsLayerSet$'
>       );
>       
> ```

Remove white spaces
___
*[`packages/geoview-core/public/templates/layers/ogc-feature.html` line 164 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZ_xYv64GIZVnRNa6eV:-NZ_xYv64GIZVnRNa6eW:b-vjv3mt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e697c4f8074961d87fb47d79a369d396517b92/packages/geoview-core/public/templates/layers/ogc-feature.html#L164)):*
> ```HTML
>         'LYR1/$LegendsLayerSet$'
>       );
>       
> ```

Remove white spaces
___
*[`packages/geoview-core/public/templates/layers/wms.html` line 426 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZ_y8PR9tQoi9gyhzb1:-NZ_y8PR9tQoi9gyhzb2:bbgxw6s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e697c4f8074961d87fb47d79a369d396517b92/packages/geoview-core/public/templates/layers/wms.html#L426)):*
> ```HTML
>     <div class="map-title-holder">
>       <h4 id="HLYR4">4. Automatic group creation from metadata information</h4>
>       &nbsp;<h5 id="HLYR4-state">(undefined)</h5>
> ```

Layer hydro does not load but state is addToMap instead of error. I don't know if it is related, but all collapsible item on the are not working. Layer style dropdown not working as well.

Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
___
*[`packages/geoview-core/public/templates/layers/xyz.html` line 121 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZ_zsSj0fUf-MhMkUxR:-NZ_zsSj0fUf-MhMkUxS:bb1uuck) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e697c4f8074961d87fb47d79a369d396517b92/packages/geoview-core/public/templates/layers/xyz.html#L121)):*
> ```HTML
>         }
>       });
>       
> ```

Remove white spaces. This section is in all your sample, would it be better to put it in your js layerlib file with all the script?
___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 23 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZa0FXa2P4Ru3nRf4t5:-NZa0FXa2P4Ru3nRf4t6:bue4yn8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f23da888cd190b5847375154e465b6e8e3d4647d/packages/geoview-core/src/core/containers/shell.tsx#L23)):*
> ```XML
> import { EVENT_NAMES } from '../../api/events/event-types';
> 
> import { CircularProgress, Modal, Snackbar } from '../../ui';
> ```

Should we keep it if some pieces is longer to load like base map. For the moment maps loads quickly but footer bar tooks 2 seconds. There no circular progress anymore and the maps load without the indicator and without the footer bar. It appears after and looks weird.
___
*[`packages/geoview-core/src/core/types/cgpv-types.ts` line 80 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZa0bPFAJJg9JJ6bbzl:-NZa0bPFAJJg9JJ6bbzm:b-t5yv7j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f23da888cd190b5847375154e465b6e8e3d4647d/packages/geoview-core/src/core/types/cgpv-types.ts#L80)):*
> ```XML
> export * from '../../api/events/payloads/map-config-payload';
> export * from '../../api/events/payloads/map-payload';
> export * from '../../api/events/payloads/map-slingle-click-payload';
> ```

We should have both single click and mouse move? The single click for the real click on the map?

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129)* status: 33 of 35 files reviewed, 10 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/layers/esri-dynamic.html` line 69 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZa-Xxl80JfObYCQesY:-NZaDg7f47HlAladDFet:b-rsuhff) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e697c4f8074961d87fb47d79a369d396517b92/packages/geoview-core/public/templates/layers/esri-dynamic.html#L69)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Weird problem.... until first click hover does not work properly. Mouse location is not at the mouse cursor. On first click the click marker is offset lower the cursor. After first click it is working fine.
</blockquote></details>

I've suspected a problem with the hover functionality. I think we should create an issue for tis.
___
*[`packages/geoview-core/public/templates/layers/esri-feature.html` line 406 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZ_xCo7ABicj_oegZIV:-NZaC1CBArd_W8qlMjIN:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e697c4f8074961d87fb47d79a369d396517b92/packages/geoview-core/public/templates/layers/esri-feature.html#L406)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove white spaces. Should have been modified by the prettier run on rush build...
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/layers/geojson.html` line 247 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZ_xR663NRYkpfzSCh3:-NZa6qpN5TtkUg9yQhgu:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e697c4f8074961d87fb47d79a369d396517b92/packages/geoview-core/public/templates/layers/geojson.html#L247)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove white spaces
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/layers/geopackage.html` line 231 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZ_xUv39fR8f7b1vhp-:-NZa7-zq3gjtO5VTsiqg:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e697c4f8074961d87fb47d79a369d396517b92/packages/geoview-core/public/templates/layers/geopackage.html#L231)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove white spaces
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/layers/image-static.html` line 159 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZ_xWK84QN-sYfcMBsN:-NZa76h_Av4RR1sOF-fs:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e697c4f8074961d87fb47d79a369d396517b92/packages/geoview-core/public/templates/layers/image-static.html#L159)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove white spaces
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/layers/ogc-feature.html` line 164 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZ_xYv64GIZVnRNa6eV:-NZa7DYi97kXHwZXDg5C:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e697c4f8074961d87fb47d79a369d396517b92/packages/geoview-core/public/templates/layers/ogc-feature.html#L164)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove white spaces
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/layers/wms.html` line 426 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZ_y8PR9tQoi9gyhzb1:-NZaCqR501pJ-7W44NAX:b1qj6ky) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e697c4f8074961d87fb47d79a369d396517b92/packages/geoview-core/public/templates/layers/wms.html#L426)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Layer hydro does not load but state is addToMap instead of error. I don't know if it is related, but all collapsible item on the are not working. Layer style dropdown not working as well.

Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
</blockquote></details>

This is a problem related to issue #1130 (Add error handling to promises). When the service is available, everything is working. Issue #1128 (Run init for all maps) will also resolve this problem.  
___
*[`packages/geoview-core/public/templates/layers/xyz.html` line 121 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZ_zsSj0fUf-MhMkUxR:-NZa7zev32esxvjz4PXz:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/52e697c4f8074961d87fb47d79a369d396517b92/packages/geoview-core/public/templates/layers/xyz.html#L121)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove white spaces. This section is in all your sample, would it be better to put it in your js layerlib file with all the script?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/containers/shell.tsx` line 23 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZa0FXa2P4Ru3nRf4t5:-NZa88dj-8E6gkup8T32:b-3f3x3i) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f23da888cd190b5847375154e465b6e8e3d4647d/packages/geoview-core/src/core/containers/shell.tsx#L23)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we keep it if some pieces is longer to load like base map. For the moment maps loads quickly but footer bar tooks 2 seconds. There no circular progress anymore and the maps load without the indicator and without the footer bar. It appears after and looks weird.
</blockquote></details>

If we leave circularProgress as before, the spinning wheel will remain displayed over the maps until all layers are loaded and we're back to square one. We need to find an alternative method to displaying the spinning wheel on top of the maps.
___
*[`packages/geoview-core/src/core/types/cgpv-types.ts` line 80 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-NZa0bPFAJJg9JJ6bbzl:-NZa9nf92jfJiWEJaODC:b-ucjy9c) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f23da888cd190b5847375154e465b6e8e3d4647d/packages/geoview-core/src/core/types/cgpv-types.ts#L80)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should have both single click and mouse move? The single click for the real click on the map?
</blockquote></details>

We differentiate the mouse click and the mouse move using the EventStringId.
EVENT\_NAMES.MAP.EVENT\_MAP\_SINGLE\_CLICK for mouse click
and
EVENT\_NAMES.MAP.EVENT\_MAP\_POINTER\_MOVE for mouse move

**Review by jolevesq — APPROVED** [review]
:lgtm:

> Reviewed 1 of 35 files at r1, 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129#-:-NZbJ7FoDi5Kqo6TQghL:bnfp4nl)* status: 33 of 35 files reviewed, 1 unresolved discussion

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 35 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129)* status: 34 of 35 files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1129)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ychoquet)

**Pull request merged**
