### PR TITLE
1579 use only layer path phase 2

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

Second phase of the restructuration to use layerPath whenever we have to use geoview layer public methods.

Fixes # 1579

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using Chrome Devtools to trace and debug the code.

__Deploy URL:__ https://ychoquet.github.io/GeoView/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 53 of 53 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614)* status: all files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/public/templates/layers-temporal.html` line 243 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-NldxnFD3g3THbDAk4ci:-NldxnFD3g3THbDAk4cj:b-95k1mi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/public/templates/layers-temporal.html#L243)):*
> ```HTML
>           );
>           timeConsoleLyr2.textContent = JSON.stringify(
>             cgpv.api.maps['LYR2'].layer.geoviewInstance('esriDynamicLYR3/0').getTemporalDimension(),
> ```

Why not geoviewLayer anymore
___
*[`packages/geoview-core/public/templates/layers/esri-dynamic.html` line 1063 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle2ApQ0QORCj-zgazo:-Nle2ApR2RJ3P3kTOQMl:bhp2eb9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/public/templates/layers/esri-dynamic.html#L1063)):*
> ```HTML
>           createTableOfFilter('LYR3');
> 
>           /*
> ```

Can we remove dead code?
___
*[`packages/geoview-core/public/templates/layers/wms.html` line 610 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle37uC5ZcXq-wCnHkL:-Nle37uC5ZcXq-wCnHkM:bdlb8ir) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/public/templates/layers/wms.html#L610)):*
> ```HTML
>             const layerConfig = cgpv.api.maps.LYR1.layer.registeredLayers['wmsLYR1-spatiotemporel/RADAR_1KM_RSNO'];
>             const temporalData =
>               cgpv.api.maps.LYR1.layer.geoviewInstance('wmsLYR1-spatiotemporel/RADAR_1KM_RSNO').getTemporalDimension();
> ```

Please add in the map description something to say this layer is temporal and change automatically
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 275 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle4VHxAHMIh0E0zPwa:-Nle4VHy4RujwhYSr3Ig:b-il9vpr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/layer.ts#L275)):*
> ```XML
>    * @param {string} layerPath The layer path to the layer's configuration.
>    *
>    * @returns {AbstractGeoViewLayer} Returns the geoview instance associated to the layer path.
> ```

We should call geoview layer instance. geoview instance is kind of the viewer itself
We may want to set geoviewLayers a private object and use this new instance to access.... if not it is confusing to have similar object for different purpose
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 255 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle57WJ8aPQp9PdX2Fp:-Nle57WJ8aPQp9PdX2Fq:brbgwx4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L255)):*
> ```XML
> 
>   /** Original map layer configuration */
>   originalMapLayerConfig: TypeGeoviewLayerConfig;
> ```

This info is available from the store.... we should use only on object. Good to read, not to modify
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 385 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle5Tsx-j_rXY24kodb:-Nle5Tsx-j_rXY24kodc:b-xvb6vv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L385)):*
> ```XML
>    * @param {string} layerPath The layer path to the layer's configuration affected by the change.
>    */
>   setLayerStatus(layerStatus: TypeLayerStatus, layerPath?: string) {
> ```

Like the renaming from change to set...
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1068 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle6CcKAnABA3wpA-q-:-Nle6CcKAnABA3wpA-q0:b-tg49l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1068)):*
> ```XML
>    */
>   getExtent(layerPath?: string): Extent | undefined {
>     layerPath = layerPath || api.maps[this.mapId].layer.layerPathAssociatedToTheGeoviewInstance;
> ```

What is this layerpathassoci....
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1439 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle6pZx81F-oKW1Vz8u:-Nle6pZx81F-oKW1Vz8v:boomi1z) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1439)):*
> ```XML
>    * @param {string} errorMessage The error message.
>    */
>   setAllLayerStatusToError(listOfLayerEntryConfig: TypeListOfLayerEntryConfig, errorMessage: string) {
> ```

Good to move to from geoUtilities to here
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle7piYAWlEvzBXXWrq:-Nle7piYAWlEvzBXXWrr:bt1m63h) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L1)):*
> ```XML
> /* eslint-disable @typescript-eslint/no-unused-vars, no-console */
> ```

Always better to put the disable for the specific line.. easier to trap and resolve later
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 275 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle8WA54sT7SQFzBAuD:-Nle8WA54sT7SQFzBAuE:b9dig3q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts#L275)):*
> ```XML
>   }
> 
>   // TODO: This section needs documentation (a header at least). Also, is it normal to have things hardcoded like that?
> ```

Vector tile is still in development, it should not at the end, good to add a TODO
___
*[`packages/geoview-layers-panel/src/layers-list.tsx` line 238 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-NleAciSCCIjyD893rsX:-NleAciSCCIjyD893rsY:bpqw2nf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-layers-panel/src/layers-list.tsx#L238)):*
> ```XML
>     setLayerOpacity((state) => ({ ...state, [data.geoviewLayerId]: value }));
>     const opacity = layerVisibility[data.geoviewLayerId] ? value / 100 : 0;
>     data.setOpacity(opacity); // ! needs a layerPath
> ```

This is deprecated and will be remove soon

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614)* status: 50 of 53 files reviewed, 8 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/public/templates/layers-temporal.html` line 243 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-NldxnFD3g3THbDAk4ci:-NleMPQy5rH_eYOLSfgw:b-gmob6f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/public/templates/layers-temporal.html#L243)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why not geoviewLayer anymore
</blockquote></details>

I've hesitated, let's change that to geoviewLayer.
___
*[`packages/geoview-core/public/templates/layers/esri-dynamic.html` line 1063 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle2ApQ0QORCj-zgazo:-NleOXZ0AwokiW1Byjym:bpjc5ud) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/public/templates/layers/esri-dynamic.html#L1063)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we remove dead code?
</blockquote></details>

I restored it.
___
*[`packages/geoview-core/public/templates/layers/wms.html` line 610 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle37uC5ZcXq-wCnHkL:-NlePYuD9Na1Goy0n-Zg:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/public/templates/layers/wms.html#L610)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Please add in the map description something to say this layer is temporal and change automatically
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 275 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle4VHxAHMIh0E0zPwa:-NleQ01fEBuyepsO913G:b-2cam4w) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/layer.ts#L275)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should call geoview layer instance. geoview instance is kind of the viewer itself
We may want to set geoviewLayers a private object and use this new instance to access.... if not it is confusing to have similar object for different purpose
</blockquote></details>

I've just renamed this method to geoviewLayer. The method returns the geoview instance associated to any layerPath and cache the layerPath so it can be used by any get/set PUBLIC method associated to the geoview instance that has a layerPath parameter. To use the cahe value, simply use an undefined or empty string '' layerPath. This has the benifit of shortening the code.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 255 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle57WJ8aPQp9PdX2Fp:-NleSDxq3-9N8JVFlN1T:b6gg1k5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L255)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This info is available from the store.... we should use only on object. Good to read, not to modify
</blockquote></details>

The original MapLayerConfig is an unaltered copy of the initial configuration. We've often said that the code should be modified so as not to alter the initial configuration. However, the code in its current state would have to undergo extensive refactoring to apply this rule. The simplest way to keep a configuration unchanged is to copy it into a property that will never be modified. Whether this is useful, time will tell.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 385 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle5Tsx-j_rXY24kodb:-NleWeQI7r3VL3weZe_s:bv289t0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L385)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Like the renaming from change to set...
</blockquote></details>

Yes, this is what we used everywhere else.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1068 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle6CcKAnABA3wpA-q-:-NleUlSv5hdGyu6H3_-X:b-sl3top) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1068)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

What is this layerpathassoci....
</blockquote></details>

It is the property used to cache the layerPath used to get the geoview instance using the geoviewLayer method. This littler tric allows us to write:
api.maps[mapId].layer.geoviewLayer(layerPath).setVisible(true);
instead of:
api.maps[mapId].layer.geoviewLayers[layerPath.split('/')[0]].setVisible(true, layerPath);
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1439 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle6pZx81F-oKW1Vz8u:-NleWwas7pAsIs18MzJF:b-vahrm2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1439)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Good to move to from geoUtilities to here
</blockquote></details>

Yes, because this method is related to the layers.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle7piYAWlEvzBXXWrq:-NleXSIqB7rN3RuBWYuG:b-px0ud6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Always better to put the disable for the specific line.. easier to trap and resolve later
</blockquote></details>

Yes, but sometimes it is all over the place and it is simpler and faster to place it at the top of the file (Philosophical debate)
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts` line 275 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle8WA54sT7SQFzBAuD:-NleYSP57eZ5QahyGvtL:bqog7yy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/raster/vector-tiles.ts#L275)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Vector tile is still in development, it should not at the end, good to add a TODO
</blockquote></details>

Agree!

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 53 of 53 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614)* status: 37 of 53 files reviewed, 14 unresolved discussions (waiting on @DamonU2, @jolevesq, and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 40 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle41Wt-7eIToz8_5To:-Nle41Wt-7eIToz8_5Tp:b8bmcpy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L40)):*
> ```XML
>  * @returns {Promise<void>} A promise that the execution is completed.
>  */
> export async function commonGetServiceMetadata(this: EsriDynamic | EsriFeature) {
> ```

I would explicitly sign the method with a return of `Promise<void>` here. Especially since, (1) the method is exported and (2) not all code paths are awaited either. It'll help understand the intent of the method.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 325 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle691zBnudla--MT28:-Nle691zBnudla--MT29:b-ya81ng) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L325)):*
> ```XML
>  * @returns {Promise<void>} A promise that the layer configuration has its metadata processed.
>  */
> export async function commonProcessLayerMetadata(this: EsriDynamic | EsriFeature, layerConfig: TypeLayerEntryConfig) {
> ```

Same as above
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 112 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nlegr2H0cGhD3QsevnD:-Nlegr2H0cGhD3QsevnE:b9ork37) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L112)):*
> ```XML
>    * @returns {Promise<void>} A promise that the execution is completed.
>    */
>   protected async getServiceMetadata(): Promise<void> {
> ```

General comment, applies for some others in this PR: is this method really used to 'get' something (in reference to a get/set pattern)?
Maybe name the function `processServiceMetadata()` (as 'process' seems to be another prefix that is used in many places here) or `fetchServiceMetadata()` or `setServiceMetadata()`?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 208 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-NleihCtEjeTwfZU-MRN:-NleihCtEjeTwfZU-MRO:b-nf44s5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L208)):*
> ```XML
>    * @returns {Promise<void>} A promise that the execution is completed.
>    */
>   private async getXmlServiceMetadata(metadataUrl: string): Promise<void> {
> ```

Same as above, maybe name it `processXmlServiceMetadata()` as it seems to be 'setting' ` dataAccessPath` more than 'getting' anything?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 257 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-NlefdNU2yZ2OSsgNX9H:-NlefdNVE8TWOg-ip0kM:b-wute2q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L257)):*
> ```XML
>    */
>   // eslint-disable-next-line @typescript-eslint/no-unused-vars
>   protected async getFeatureInfoAtPixel(location: Pixel, layerPath: string): Promise<TypeArrayOfFeatureInfoEntries> {
> ```

Based on the pattern you seem to want in other examples in this PR, this one should probably return a `Promise<TypeArrayOfFeatureInfoEntries | null>`?
Actually, no, after looking at `formatFeatureInfoResult()`, you probably want to return `[]` here in `getFeatureInfoAtPixel` instead of `null` in the catch.
One or the other.
___
*[`packages/geoview-core/src/geo/utils/utilities.ts` line 36 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-NleXKCp8Cg1oyzUSWNV:-NleXKCp8Cg1oyzUSWNW:b-l50y48) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/utils/utilities.ts#L36)):*
> ```XML
>   geometryToWKT = (geometry: Geometry): string | null => {
>     // TODO: Refactoring - This method should be static, but since it goes through the api instance to be importable
>     // TODO  afterwards it loses non static methods. For this reason, I've left it like this.
> ```

General comment applying to this whole file.
The reason I had the TODO on 1 line was because this is 1x TODO, not 3x.

Writing it with a TODO per-line like you've done grows the TODO list for nothing (both in the user interface and when searching for the remaining TODOs).
Can we put it back on 1 line or not use TODO on each line, just use another tag for continuation or something? I've sometimes used something like "// TO.DO.CONT", personally, on this project.

See the green list on the left side on this screenshot for what I mean:

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614)* status: 37 of 54 files reviewed, 14 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 40 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle41Wt-7eIToz8_5To:-NlfwAY04FM7y6Ij4PPL:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L40)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I would explicitly sign the method with a return of `Promise<void>` here. Especially since, (1) the method is exported and (2) not all code paths are awaited either. It'll help understand the intent of the method.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 325 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nle691zBnudla--MT28:-NlfwDVG94MomEId00EN:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L325)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Same as above
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 112 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-Nlegr2H0cGhD3QsevnD:-Nlfx9V29lZrS-NbbHJ4:bndzsrv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L112)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

General comment, applies for some others in this PR: is this method really used to 'get' something (in reference to a get/set pattern)?
Maybe name the function `processServiceMetadata()` (as 'process' seems to be another prefix that is used in many places here) or `fetchServiceMetadata()` or `setServiceMetadata()`?
</blockquote></details>

Yes, fetch is better here than get. Modification Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 208 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-NleihCtEjeTwfZU-MRN:-NlfyNwgCwAJUgHcYmsI:b-rr1re1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L208)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Same as above, maybe name it `processXmlServiceMetadata()` as it seems to be 'setting' ` dataAccessPath` more than 'getting' anything?
</blockquote></details>

Changed the name to fetchXmlServiceMetadata.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 257 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-NlefdNU2yZ2OSsgNX9H:-NlfzRRG-StgWYxUMPHJ:b-v9gbgd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L257)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Based on the pattern you seem to want in other examples in this PR, this one should probably return a `Promise<TypeArrayOfFeatureInfoEntries | null>`?
Actually, no, after looking at `formatFeatureInfoResult()`, you probably want to return `[]` here in `getFeatureInfoAtPixel` instead of `null` in the catch.
One or the other.
</blockquote></details>

Well, null is used to signal an error and [] to indicate that there is no feature around the pixel position. Made the correction.
___
*[`packages/geoview-core/src/geo/utils/utilities.ts` line 36 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614#-NleXKCp8Cg1oyzUSWNV:-Nlg05e67eEE03_vxWxU:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3cdeccfe9b31e76b7c26098fd21d938a8590696a/packages/geoview-core/src/geo/utils/utilities.ts#L36)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

General comment applying to this whole file.
The reason I had the TODO on 1 line was because this is 1x TODO, not 3x.

Writing it with a TODO per-line like you've done grows the TODO list for nothing (both in the user interface and when searching for the remaining TODOs).
Can we put it back on 1 line or not use TODO on each line, just use another tag for continuation or something? I've sometimes used something like "// TO.DO.CONT", personally, on this project.

See the green list on the left side on this screenshot for what I mean:


</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 10 of 14 files at r3, 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1614)* status: all files reviewed, 6 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

**Pull request merged**
