### PR TITLE
refactor(scale): Refactor scale and footer to use store

### LINKED ISSUE #1303: [REFACTOR] Use Store for Scale
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We currently use map event to know map changed.

### Expected Behavior

Use store to manage map moveend event and use store.state from sclae component. In sclae component, remove ol and geoview events

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1303

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1303 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Check many pages and play with footerbar
https://jolevesq.github.io/geoview/projections.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321)

### CODE REVIEW

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321)* status: all files reviewed, 1 unresolved discussion (waiting on @amir-azma, @cphelefu, @DamonU2, @jolevesq, and @kaminderpal)

___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321#-NeoEqCfDi9kSFCco9V1:-NeoEqCfDi9kSFCco9V2:b7boftv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1a1fdc2ad0e2ad6140365df95748a6c752735a0/packages/geoview-core/src/core/stores/geoview-store.ts#L51)):*
> ```XML
> export interface IGeoViewState {
>   mapId: string;
>   mapConfig: TypeMapFeaturesConfig | undefined;
> ```

I had to include the mapConfig in the mapContext. It is not fully tested yet. Maybe the store is a better place to keep it?



_Code quote:_
```XML
mapConfig: TypeMapFeaturesConfig | undefined;
```

**Review by DamonU2 — APPROVED** [review]
> Reviewed 10 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321)* status: all files reviewed, 1 unresolved discussion (waiting on @amir-azma, @cphelefu, @jolevesq, and @kaminderpal)

**Review by kaminderpal — APPROVED** [review]

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 92 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321#-NepimbPEaRktOLi9MA4:-NepimbQ3xTsrU_Cwa5l:btdvko1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1a1fdc2ad0e2ad6140365df95748a6c752735a0/packages/geoview-core/src/core/stores/geoview-store.ts#L92)):*
> ```XML
>           mapState: {
>             ...get().mapState,
>             scaleGraphic: document.getElementById(`${event.map.get('mapId')}-scaleControlLine`)?.querySelector('.ol-scale-line-inner')
> ```

Store code should not be aware HTML elements or structure, it should just save values it is given. We want to move all `document.getElementById` to components code.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-expand-button.tsx` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321#-Nepkf1S4-usVfvCJjkc:-Nepkf1T0TjAqNCUkTsr:bbeygw4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1a1fdc2ad0e2ad6140365df95748a6c752735a0/packages/geoview-core/src/core/components/footer-bar/footer-bar-expand-button.tsx#L60)):*
> ```XML
>     });
> 
>     api.event.emit(booleanPayload(EVENT_NAMES.FOOTERBAR.EVENT_FOOTERBAR_EXPAND_COLLAPSE, mapId, true));
> ```

This event.emit and setState cant co-exist.

Create a new eventProcessor file, footerEventProcessor. This event should be fired from that file if the footerBarState.expanded changes.


If you have more time you can also remove all listeners of this event in components and basically get value from the store.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-expand-button.tsx` line 85 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321#-NeplbhED_6UgvEz1pbN:-NeplbhED_6UgvEz1pbO:btam3sj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1a1fdc2ad0e2ad6140365df95748a6c752735a0/packages/geoview-core/src/core/components/footer-bar/footer-bar-expand-button.tsx#L85)):*
> ```XML
>     });
> 
>     api.event.emit(booleanPayload(EVENT_NAMES.FOOTERBAR.EVENT_FOOTERBAR_EXPAND_COLLAPSE, mapId, false));
> ```

Save as above, this event has to be removed.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/map/map.tsx` line 184 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321#-NepmlyX7--Koru7o-Nd:-NepmlyX7--Koru7o-Ne:bb445rt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1a1fdc2ad0e2ad6140365df95748a6c752735a0/packages/geoview-core/src/core/components/map/map.tsx#L184)):*
> ```XML
>         cgpvMap.on('moveend', store.getState().mapState.onMapMoveEnd);
>         store.setState({
>           mapState: { ...store.getState().mapState, onMapMoveEnd: (fakeMapEvent) => fakeMapEvent },
> ```

You cant set an event, onMapMoveEnd is an event.. you can call it.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/map/map.tsx` line 182 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321#-Nepn5gsAIkTp_oBWyXG:-Nepn5gsAIkTp_oBWyXH:by8igtn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1a1fdc2ad0e2ad6140365df95748a6c752735a0/packages/geoview-core/src/core/components/map/map.tsx#L182)):*
> ```XML
>         // initialize store OpenLayers events
>         const store = getGeoViewStore(mapId);
>         cgpvMap.on('moveend', store.getState().mapState.onMapMoveEnd);
> ```

I think we want to move all the code in store back here..

```
const currentMapCenterCoordinates = ...;
const scaleGraphic = ...;
const scaleNumeric: = ...;
const scaleLineWidth = ...;

store.setState({
  mapState: {
    ... store.getState().mapState,
   scaleGraphic, scaleNumeric, scaleLineWidth
});
```

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 19 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321#-NepocZeBr0SGNSa75pc:-NepocZeBr0SGNSa75pd:b-sxhiit) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1a1fdc2ad0e2ad6140365df95748a6c752735a0/packages/geoview-core/src/core/stores/geoview-store.ts#L19)):*
> ```XML
>   scaleNumeric: string;
>   scaleGraphic: string;
>   scaleLineWidth: string;
> ```

Did we replace where these values are used with getting it from store (if necessary)?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321#-NeoEqCfDi9kSFCco9V1:-NeporSe1vD1ryW5HZXS:bvqv6xm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1a1fdc2ad0e2ad6140365df95748a6c752735a0/packages/geoview-core/src/core/stores/geoview-store.ts#L51)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I had to include the mapConfig in the mapContext. It is not fully tested yet. Maybe the store is a better place to keep it?
</blockquote></details>

Yes, we already have it in the store. We call it mapConfig in the store.

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321)* status: 7 of 15 files reviewed, 7 unresolved discussions (waiting on @amir-azma, @cphelefu, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-expand-button.tsx` line 60 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321#-Nepkf1S4-usVfvCJjkc:-NesE6VCBQlpeVaz5fJV:bcpm294) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1a1fdc2ad0e2ad6140365df95748a6c752735a0/packages/geoview-core/src/core/components/footer-bar/footer-bar-expand-button.tsx#L60)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

This event.emit and setState cant co-exist.

Create a new eventProcessor file, footerEventProcessor. This event should be fired from that file if the footerBarState.expanded changes.


If you have more time you can also remove all listeners of this event in components and basically get value from the store.
</blockquote></details>

I removed it completely. Just add a TODO in the payload file to see if we keep it and create an event processor for it
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-expand-button.tsx` line 85 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321#-NeplbhED_6UgvEz1pbN:-NesEGGa9jcRH65UnzQg:b-ya81ng) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1a1fdc2ad0e2ad6140365df95748a6c752735a0/packages/geoview-core/src/core/components/footer-bar/footer-bar-expand-button.tsx#L85)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Save as above, this event has to be removed.
</blockquote></details>

Same as above
___
*[`packages/geoview-core/src/core/components/map/map.tsx` line 182 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321#-Nepn5gsAIkTp_oBWyXG:-NesEUyx5tvOGWv8cseJ:b993oqh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1a1fdc2ad0e2ad6140365df95748a6c752735a0/packages/geoview-core/src/core/components/map/map.tsx#L182)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

I think we want to move all the code in store back here..

```
const currentMapCenterCoordinates = ...;
const scaleGraphic = ...;
const scaleNumeric: = ...;
const scaleLineWidth = ...;

store.setState({
  mapState: {
    ... store.getState().mapState,
   scaleGraphic, scaleNumeric, scaleLineWidth
});
```
</blockquote></details>

Removed the scale store value as it is internal to the component.
___
*[`packages/geoview-core/src/core/components/map/map.tsx` line 184 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321#-NepmlyX7--Koru7o-Nd:-NesEOK4DOmFbzliBtss:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1a1fdc2ad0e2ad6140365df95748a6c752735a0/packages/geoview-core/src/core/components/map/map.tsx#L184)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

You cant set an event, onMapMoveEnd is an event.. you can call it.
</blockquote></details>

Done
___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 19 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321#-NepocZeBr0SGNSa75pc:-NesEnjo9OwjJwuPRBPv:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1a1fdc2ad0e2ad6140365df95748a6c752735a0/packages/geoview-core/src/core/stores/geoview-store.ts#L19)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Did we replace where these values are used with getting it from store (if necessary)?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321#-NeoEqCfDi9kSFCco9V1:-NesEpXDDeAD2WeKwnmz:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1a1fdc2ad0e2ad6140365df95748a6c752735a0/packages/geoview-core/src/core/stores/geoview-store.ts#L51)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Yes, we already have it in the store. We call it mapConfig in the store.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/stores/geoview-store.ts` line 92 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321#-NepimbPEaRktOLi9MA4:-NesEqMO8zSNgq0MvgGr:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/f1a1fdc2ad0e2ad6140365df95748a6c752735a0/packages/geoview-core/src/core/stores/geoview-store.ts#L92)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Store code should not be aware HTML elements or structure, it should just save values it is given. We want to move all `document.getElementById` to components code.
</blockquote></details>

Done

**Review by cphelefu — COMMENTED** [review]
> Reviewed 7 of 15 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321)* status: all files reviewed, 7 unresolved discussions (waiting on @amir-azma and @ychoquet)

**Review by cphelefu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1321)* status: all files reviewed, 1 unresolved discussion (waiting on @amir-azma and @ychoquet)

**Pull request merged**
