### PR TITLE
feat(projections) Create projection capabilities

### LINKED ISSUE #25: Create projection capabilities
For the moment, we are using proj4 to manage our projection. We support Web Mercator and LCC. We need a function to project a geometry or array of geometries
[ ] LCC to WM
[ ] WM to LCC
[ ] Lat/Lng to WM or LCC
[ ] WM or LCC to LatLng

Those functions needs to be accessible from inside the viewer and the outside with the api

At the same time, to validate the concept, make the geoJSON file loads in the LCC map.

### PR DESCRIPTION
**Pull request by yass0016**
Closes #25

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 4 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53)* status: 4 of 14 files reviewed, 5 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[public/index.html, line 125 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53#-MSYJUATE6R59YwBsq1B:-MSYJUATE6R59YwBsq1C:b-r9pcse) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/520aead216a2f5b9cd162ee9eca02fdc8f9b528f/public/index.html#L125)):*
> ```HTML
>                 });
>             });
>         </script>
> ```

Can you just add a function sample here. Button who project a lat.long coord to LCC?
___
*[src/app.tsx, line 4 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53#-MSYJiEyDY0Xv8pcDtnG:-MSYJiEyDY0Xv8pcDtnH:b-377iig) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/520aead216a2f5b9cd162ee9eca02fdc8f9b528f/src/app.tsx#L4)):*
> ```XML
> import ReactDOM from 'react-dom';
> 
> import proj4 from 'proj4';
> ```

I would put proj4 import below Leaflet (as it is use by Leaflet so it is less important). Not mandatory but make it cleaner... maybe just in my mind :-).
___
*[src/api/event.ts, line 8 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53#-MSYKYos7-ecy7xWRgmw:-MSYKYos7-ecy7xWRgmx:bfgbl27) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/520aead216a2f5b9cd162ee9eca02fdc8f9b528f/src/api/event.ts#L8)):*
> ```XML
>  * constant contains event names
>  */
> export const EVENT_NAMES = {
> ```

Not in this PR but we may even want to make different type of event (map, layer, panel, legend, ...). Can you create an issue?
___
*[src/api/projection.ts, line 31 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53#-MSYMLH_DRmI6KkDg7rm:-MSYMLHa1lUMwdS3dOqU:b900yad) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/520aead216a2f5b9cd162ee9eca02fdc8f9b528f/src/api/projection.ts#L31)):*
> ```XML
>      * @param {string} toProj projection to be converted to
>      */
>     transformPoints = (points: unknown, fromProj: string, toProj: string): Array<Array<number> | number> => {
> ```

Is this provate and only une by inside function?
___
*[src/common/layers/layer.ts, line 97 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53#-MSYPOVE7r2tGEQ0g5rs:-MSYPOVE7r2tGEQ0g5rt:b-7l7mej) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/520aead216a2f5b9cd162ee9eca02fdc8f9b528f/src/common/layers/layer.ts#L97)):*
> ```XML
> 
>         // listen to outside events to remove layers
>         api.event.on(EVENT_NAMES.EVENT_REMOVE_LAYER, (payload) => {
> ```

Can you add a button to remove the added geoJSON layer?

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53)* status: 4 of 14 files reviewed, 5 unresolved discussions (waiting on @jolevesq and @melzeiny1980)

___
*[public/index.html, line 125 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53#-MSYJUATE6R59YwBsq1B:-MSYR_go7E_E5iozUCF8:bfphicw) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/520aead216a2f5b9cd162ee9eca02fdc8f9b528f/public/index.html#L125)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you just add a function sample here. Button who project a lat.long coord to LCC?
</blockquote></details>

Done. For this one you will notice the button I added will also add the geojson on the WM map because I didn't have add to a specific map implemented, its implemented in issue #24 
___
*[src/app.tsx, line 4 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53#-MSYJiEyDY0Xv8pcDtnG:-MSYQ_Wy0ddL3kf9yIpU:b-3m0b5r) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/520aead216a2f5b9cd162ee9eca02fdc8f9b528f/src/app.tsx#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I would put proj4 import below Leaflet (as it is use by Leaflet so it is less important). Not mandatory but make it cleaner... maybe just in my mind :-).
</blockquote></details>

This is no longer needed in this file, I will remove it
___
*[src/api/event.ts, line 8 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53#-MSYKYos7-ecy7xWRgmw:-MSYSiic1OKW78XvZ7F4:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/520aead216a2f5b9cd162ee9eca02fdc8f9b528f/src/api/event.ts#L8)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Not in this PR but we may even want to make different type of event (map, layer, panel, legend, ...). Can you create an issue?
</blockquote></details>

Done.
___
*[src/api/projection.ts, line 31 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53#-MSYMLH_DRmI6KkDg7rm:-MSYSpFz9VlRThcBjlRk:bp6r5ms) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/520aead216a2f5b9cd162ee9eca02fdc8f9b528f/src/api/projection.ts#L31)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this provate and only une by inside function?
</blockquote></details>

No, it can also be accessed from the API if someone wants to transform points from outside
___
*[src/common/layers/layer.ts, line 97 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53#-MSYPOVE7r2tGEQ0g5rs:-MSYU4L59Ccfvy0ltvHz:bj0pmpo) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/520aead216a2f5b9cd162ee9eca02fdc8f9b528f/src/common/layers/layer.ts#L97)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add a button to remove the added geoJSON layer?
</blockquote></details>

since we are dynamically generating layer IDs, currently in this branch we don't have access to the layers that have been created from outside, this is fixed in #24, we will be able to call functions from outside to get all layers from each map and possibly delete a specific layer

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53)* status: 5 of 14 files reviewed, 1 unresolved discussion (waiting on @melzeiny1980 and @yass0016)

___
*[src/api/projection.ts, line 31 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53#-MSYMLH_DRmI6KkDg7rm:-MSYXAge1c_Cx5V1cxt3:b-z9q0dm) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/520aead216a2f5b9cd162ee9eca02fdc8f9b528f/src/api/projection.ts#L31)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

No, it can also be accessed from the API if someone wants to transform points from outside
</blockquote></details>

Should he use one of the available function like latLngToLCC?

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53)* status: 5 of 14 files reviewed, 1 unresolved discussion (waiting on @jolevesq and @melzeiny1980)

___
*[src/api/projection.ts, line 31 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53#-MSYMLH_DRmI6KkDg7rm:-MSYYBCF0w-F3ClzakaO:b73258v) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/520aead216a2f5b9cd162ee9eca02fdc8f9b528f/src/api/projection.ts#L31)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should he use one of the available function like latLngToLCC?
</blockquote></details>

Yes, but this is function is optional if they want to create a plugin that can transform to different projections that we don't have now

**Review by jolevesq — APPROVED** [review]
:lgtm:

> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53#-:-MSYYo_q34757ITMAmff:bnfp4nl)* status: 6 of 14 files reviewed, all discussions resolved (waiting on @melzeiny1980)

**Review by jolevesq — APPROVED** [review]
> Reviewed 6 of 14 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/53)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @melzeiny1980)

**Pull request merged**
