### PR TITLE
adding new layer

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

This PR is about adding a new layer.

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://cphelefu.github.io/geoview/raw-data-table.html/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644)* status: 11 of 12 files reviewed, 9 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/src/core/components/layers/layers-panel.tsx` line 88 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644#-NnojenD7Ap8nqduhm7D:-NnojenD7Ap8nqduhm7E:b6qud5j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/116b7ff144bfdd28fe5b2191436042d57f63f18d/packages/geoview-core/src/core/components/layers/layers-panel.tsx#L88)):*
> ```XML
>         </Paper>
>       );
>       /* eslint-enable react/no-danger */
> ```

Why you have to bypass this rule? I think we have a function to set html in utilities. It isuse by the footer tab custom tab
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 75 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644#-Nnom_jOCCxtQzorkRHp:-Nnom_jOCCxtQzorkRHq:b-qp9m58) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/116b7ff144bfdd28fe5b2191436042d57f63f18d/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L75)):*
> ```XML
>   /*
> 
>   // eslint-disable-next-line @typescript-eslint/no-explicit-any
> ```

Do we need to keep code, if so add a TODO
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 534 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644#-NnonHCeCgPPoObewRKV:-NnonHCeCgPPoObewRKW:buiycnx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/116b7ff144bfdd28fe5b2191436042d57f63f18d/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L534)):*
> ```XML
> 
>   /**
>    * Handle the behavior of the 'Finish' button in the Stepper UI
> ```

Same function description as the one above
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 538 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644#-NnonP0M3_T_WHn4WAH6:-NnonP0N7jaP441B2NpL:b-gzwvxf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/116b7ff144bfdd28fe5b2191436042d57f63f18d/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L538)):*
> ```XML
>   const handleStepLast = () => {
>     setIsLoading(true);
>     /* api.event.on(  //WHY?
> ```

If needed, put a TODO
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 551 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644#-NnonV965A4uAcEYyDut:-NnonV965A4uAcEYyDuu:bfa5u03) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/116b7ff144bfdd28fe5b2191436042d57f63f18d/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L551)):*
> ```XML
>     const name = layerName;
>     let url = layerURL;
>     if (layerType === ESRI_DYNAMIC || layerType === ESRI_FEATURE) {
> ```

Blank line before if
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 554 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644#-NnonYrqEFZuXwZwZV_b:-NnonYrqEFZuXwZwZV_c:bfa5u03) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/116b7ff144bfdd28fe5b2191436042d57f63f18d/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L554)):*
> ```XML
>       url = geoUtilities.getMapServerUrl(layerURL);
>     }
>     if (layerType === WMS) {
> ```

Blank line before if
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 561 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644#-Nnonb6R9vU8d1mfqCHe:-Nnonb6R9vU8d1mfqCHf:b-4vwcjo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/116b7ff144bfdd28fe5b2191436042d57f63f18d/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L561)):*
> ```XML
>       valid = false;
>       emitErrorEmpty(isMultiple() ? t('layers.layer') : t('layers.name'));
>     }
> ```

Blank line after if
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 604 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644#-NnoniW8-pSEH_-qHZ70:-NnoniW8-pSEH_-qHZ71:bsoief6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/116b7ff144bfdd28fe5b2191436042d57f63f18d/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L604)):*
> ```XML
>       }
> 
>       /* if (layerConfig.geoviewLayerId) {
> ```

IF dead code needed, add a TODO
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 658 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644#-NnontdbAkPWNRtGeOzY:-NnontdbAkPWNRtGeOzZ:b45ud3l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/116b7ff144bfdd28fe5b2191436042d57f63f18d/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L658)):*
> ```XML
>    * @param {SelectChangeEvent} event TextField event
>    */
>   const handleSelectType = (event: SelectChangeEvent<unknown>) => {
> ```

Overall comment, regroup functions of the same type inside #region for readability as this file is pretty huge

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644)* status: 10 of 12 files reviewed, 9 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 75 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644#-Nnom_jOCCxtQzorkRHp:-NntVjQt1RrPl254NtzI:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/efe60f631916621a5cf6a68c28c2b51c7eff2820/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L75)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we need to keep code, if so add a TODO
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 534 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644#-NnonHCeCgPPoObewRKV:-NntVk7eBaFG5j-AokVT:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/efe60f631916621a5cf6a68c28c2b51c7eff2820/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L534)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same function description as the one above
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 538 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644#-NnonP0M3_T_WHn4WAH6:-NntVkkCAmwBs8dXE6xY:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/efe60f631916621a5cf6a68c28c2b51c7eff2820/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L538)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If needed, put a TODO
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 551 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644#-NnonV965A4uAcEYyDut:-NntVlO4DxwmvIH7ob2z:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/efe60f631916621a5cf6a68c28c2b51c7eff2820/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L551)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank line before if
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 554 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644#-NnonYrqEFZuXwZwZV_b:-NntVlq96-aTy3YQEuQo:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/efe60f631916621a5cf6a68c28c2b51c7eff2820/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L554)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank line before if
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 561 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644#-Nnonb6R9vU8d1mfqCHe:-NntVmHb17b485Ll-W06:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/efe60f631916621a5cf6a68c28c2b51c7eff2820/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L561)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank line after if
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 604 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644#-NnoniW8-pSEH_-qHZ70:-NntVnre3rd_XmKGBzyB:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/efe60f631916621a5cf6a68c28c2b51c7eff2820/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L604)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

IF dead code needed, add a TODO
</blockquote></details>

Done.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 658 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644#-NnontdbAkPWNRtGeOzY:-NntVr6V2J5lr2go309t:b-8xxh1s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/efe60f631916621a5cf6a68c28c2b51c7eff2820/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L658)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Overall comment, regroup functions of the same type inside #region for readability as this file is pretty huge
</blockquote></details>

Currently reviewing this code and removing or re-writing what we dont need.

**Review by jolevesq — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @cphelefu)

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644)* status: 10 of 12 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/layers-panel.tsx` line 88 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644#-NnojenD7Ap8nqduhm7D:-Nnu0RvQ2OoDOhI2YZhT:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/efe60f631916621a5cf6a68c28c2b51c7eff2820/packages/geoview-core/src/core/components/layers/layers-panel.tsx#L88)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why you have to bypass this rule? I think we have a function to set html in utilities. It isuse by the footer tab custom tab
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1644)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
