### PR TITLE
fix(feature info): repairs feature info for geocore layers

### LINKED ISSUE #563: Check WMS getFeatureInfo format support
For the moment we only support text/xml. We should try to see how we can support in some way html like table element and parse it to looks like text/xml. It was done in RAMPS for BC services. Investigate.

### LINKED ISSUE #2210: [BUG] WMS feature info not appearing in details
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When clicking on a WMS layer, we are getting data returned, but it is not appearing in the details

### Expected Behavior

WMS returns feature info in different formats. We want to be able to handle the most common formats and allow the user to provide a code snippet to handle their specific format.

### Steps To Reproduce

Go to https://canadian-geospatial-platform.github.io/geoview/public/wms.html#HLYR4
Click on map
No info in details

### Anything else?

_No response_

### LINKED ISSUE #2593: [BUG] 16 - Can't query the features of layers [OSDP-1801]  (16 layers)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For the following UUIDs, the feature query (getFeature Info) does not work when clicking a feature in the map. Nothing is returned in the Details tab. Same result as clicking anywhere on the map.

image

Concerned UUIDs:

18f71c8f-09a3-4d91-bd74-481d17260492
5fc1052f-54a7-4832-8afc-6c8b84090d1b
6433173f-bca8-44e6-be8e-3e8a19d3c299
b6abc000-a647-4a9a-a573-dc3575b0fc7f
d8805d53-40d6-4e13-bbc0-93677c0c9c7f
52baeb21-9dc2-42f7-b944-8bbe4b4b66a0
83d09a07-542a-4d52-97b2-2e475c808806
cdab7073-728d-47f0-b967-51b96f5680c8
631c3d02-e456-4bcf-a272-e511a791edf0
40381c35-4849-4f17-a8f3-707aa6a53a9d
8fafd919-fcbe-43a3-a911-3d9461273441
92dbea79-f644-4a62-b25e-8eb993ca0264
5fb7cb08-f91e-4cb5-bd71-4cfd84db91e1
f04ea1cf-0821-4d65-8613-8dabfd1e94de
ad303082-90ec-4685-9574-0cadc60f9588
7da4ce6d-4c7a-4eee-8206-3062c4e750f3

### Expected Behavior

When clicking on a feature, we should get the details (attributes) for this specific item.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #2593
Closes #2210
Closes #563

# Description

Fixes some issues with getting the feature info for some geocore layers. Adds support for html response from WMS getFeatureInfo.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://damonu2.github.io/geoview/add-layers.html
HTML WMS: 6433173f-bca8-44e6-be8e-3e8a19d3c299

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2631)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2631)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2)

___
*[`packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts` line 255 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2631#-ODLue3t5xLwSpibGUST:-ODLue3t5xLwSpibGUSU:b-aoss9d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/58691fe70c3d7fc32949285a1fb6106b1ca63bc2/packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts#L255)):*
> ```XML
> 
>       // If queryable
>       if (layerConfig.source?.featureInfo?.queryable === false) {
> ```

Why the previous was not working?

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2631)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts` line 255 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2631#-ODLue3t5xLwSpibGUST:-ODM1o7q7lVsnYggnpWm:b-yrublz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/58691fe70c3d7fc32949285a1fb6106b1ca63bc2/packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts#L255)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why the previous was not working?
</blockquote></details>

It essentially turns the condition to `false` when source?.queryable is undefined instead of `true` by default when it's undefined.
Btw, should probably edit the comment just above the if.

**Comment by DamonU2** [comment]
Only WMS layer I know of with HTML return on feature info: 6433173f-bca8-44e6-be8e-3e8a19d3c299

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2631)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts` line 255 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2631#-ODLue3t5xLwSpibGUST:-ODMQVGpCqeAoEs7gncx:b-78jsa0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/58691fe70c3d7fc32949285a1fb6106b1ca63bc2/packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts#L255)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

It essentially turns the condition to `false` when source?.queryable is undefined instead of `true` by default when it's undefined.
Btw, should probably edit the comment just above the if.
</blockquote></details>

We shuold have the warning even when undefined.... should we revert

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2631)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts` line 255 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2631#-ODLue3t5xLwSpibGUST:-ODMQkFn25rVw1PjzD7v:b-9eqknv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/58691fe70c3d7fc32949285a1fb6106b1ca63bc2/packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts#L255)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We shuold have the warning even when undefined.... should we revert
</blockquote></details>

If we need to continue when undefined, we need a GV comment to explain why we should do this

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2631)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts` line 255 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2631#-ODLue3t5xLwSpibGUST:-ODML6lS9XqppBHBPFuw:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/58691fe70c3d7fc32949285a1fb6106b1ca63bc2/packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts#L255)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

It essentially turns the condition to `false` when source?.queryable is undefined instead of `true` by default when it's undefined.
Btw, should probably edit the comment just above the if.
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2631)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2631)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts` line 255 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2631#-ODLue3t5xLwSpibGUST:-ODl57lVBr6t3K1uoQI3:b-9x77e3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/58691fe70c3d7fc32949285a1fb6106b1ca63bc2/packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts#L255)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

GV need to be capitalize letter.... Do we want logger.error? Just looger.warning should be enough?
</blockquote></details>

Done. Small gv actually works the same.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2631)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2)

**Pull request merged**
