### PR TITLE
feat(ui): Add slider component

### LINKED ISSUE #304: Slider Component
Develop a slider component to be reuse in different packages. For the moment, Chart and Range-Slider are using a slider component who is duplicate. Create this component in the core with event accessible so it can be reuse.

In RAMP, we are using noUi-slider. See if there is an opportunity to switch to MUI slider to reduce support on third party library.

The slider must
- [ ] support dates with hours
- [ ] support dates
- [ ] support months
- [ ] support hours
- [ ] number
- [ ] static value (number, dates, text)
- [ ] one or 2 handles
- ...

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #304

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/422)

### CODE REVIEW

**Review by yass0016 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/422)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[`packages/geoview-core/public/templates/ui-components.html` line 106 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/422#-N1OmauS1PogkeIdKuiC:-N1OmauS1PogkeIdKuiD:bc811ih) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/51d7c2848338c0a63dd50d70c9c1bfe2dc435df8/packages/geoview-core/public/templates/ui-components.html#L106)):*
> ```HTML
>             // TODO: add the ability to bypass the MAP ID (should be assign to the UI component ID)
>             cgpv.types.sliderPayload(cgpv.api.eventNames.SLIDER.EVENT_SLIDER_SET_VALUES, 'PRJ1', { value: 8 })
>           );
> ```

See my comment in the file Slider.tsx about this event, you can add an extra parameter here to emit to specefic slider if you pass an id, see https://github.com/Canadian-Geospatial-Platform/GeoView/blob/294ecfb79f77aa8d2e1ded366a7e0fa10c19f02b/packages/geoview-core/src/ui/panel/panel-api.ts#L78
___
*[`packages/geoview-core/src/core/components/map/map.tsx` line 107 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/422#-N1Ok9AWCQLVv6o45sm8:-N1Ok9AXCRl33nWkXT_F:b3y2ruq) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/51d7c2848338c0a63dd50d70c9c1bfe2dc435df8/packages/geoview-core/src/core/components/map/map.tsx#L107)):*
> ```XML
> 
>   return (
>     <><MapContainer
> ```

Do we need this empty fragment?
___
*[`packages/geoview-core/src/ui/slider/slider.tsx` line 62 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/422#-N1OlRQn94Lrb7zK1cJs:-N1OlRQoELM3Dk0yoKfh:bhyf3k5) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/51d7c2848338c0a63dd50d70c9c1bfe2dc435df8/packages/geoview-core/src/ui/slider/slider.tsx#L62)):*
> ```XML
>   useEffect(() => {
>     // on set min/max, update slider
>     api.event.on(
> ```

What if you have two sliders on the page, is there a way to listen on event per slider? Currently if an event is emitted to set minmax it will apply to all sliders linked with the mapId. Maybe when you create the slider ui component pass an additional sliderId and emit to that specefic slider. See this for example .on event
https://github.com/Canadian-Geospatial-Platform/GeoView/blob/294ecfb79f77aa8d2e1ded366a7e0fa10c19f02b/packages/geoview-core/src/ui/panel/panel.tsx#L169

**Review by yass0016 — COMMENTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/422)* status: 9 of 11 files reviewed, 3 unresolved discussions (waiting on @jolevesq and @yass0016)

**Review by yass0016 — COMMENTED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/422)* status: all files reviewed, 3 unresolved discussions (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/422)* status: 7 of 11 files reviewed, 3 unresolved discussions (waiting on @yass0016)

___
*[`packages/geoview-core/public/templates/ui-components.html` line 106 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/422#-N1OmauS1PogkeIdKuiC:-N1Pvri_8h9XO_Bb-IBm:b-ilpwwo) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/51d7c2848338c0a63dd50d70c9c1bfe2dc435df8/packages/geoview-core/public/templates/ui-components.html#L106)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

See my comment in the file Slider.tsx about this event, you can add an extra parameter here to emit to specefic slider if you pass an id, see https://github.com/Canadian-Geospatial-Platform/GeoView/blob/294ecfb79f77aa8d2e1ded366a7e0fa10c19f02b/packages/geoview-core/src/ui/panel/panel-api.ts#L78
</blockquote></details>

Make it work only with the slider id, no map involve as it is not really connected to a map. If we do we do it with the mapId props. I have id on my type for slider but I can build one without it... how to enforce?
___
*[`packages/geoview-core/src/core/components/map/map.tsx` line 107 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/422#-N1Ok9AWCQLVv6o45sm8:-N1PeW_Z86a3taR6wmI2:bkhcd3h) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/51d7c2848338c0a63dd50d70c9c1bfe2dc435df8/packages/geoview-core/src/core/components/map/map.tsx#L107)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Do we need this empty fragment?
</blockquote></details>

Will remove
___
*[`packages/geoview-core/src/ui/slider/slider.tsx` line 62 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/422#-N1OlRQn94Lrb7zK1cJs:-N1Pw469CVQLpyjHsGfW:b-ktopkc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/51d7c2848338c0a63dd50d70c9c1bfe2dc435df8/packages/geoview-core/src/ui/slider/slider.tsx#L62)):*
> Make it work only with the slider id, no map involve as it is not really connected to a map. If we do we do it with the mapId props

**Review by yass0016 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/422)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[`packages/geoview-core/public/templates/ui-components.html` line 106 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/422#-N1OmauS1PogkeIdKuiC:-N1d3CGF3NqLRCgcBfgn:b-yrcbmn) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/51d7c2848338c0a63dd50d70c9c1bfe2dc435df8/packages/geoview-core/public/templates/ui-components.html#L106)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Make it work only with the slider id, no map involve as it is not really connected to a map. If we do we do it with the mapId props. I have id on my type for slider but I can build one without it... how to enforce?
</blockquote></details>

If the slider does not change anything in the map then you can pass null instead of the mapId. When listening to the event, you don't need to pass the mapId in the last parameter of the .on. Ex: ".on(eventName,callback)". Also if you want to control another slider from this slider then you can pass a slider id when emitting, for example

          // null instead of mapId, "mySliderId" additional parameter to control a specefic slider
          cgpv.api.event.emit( cgpv.types.sliderPayload(cgpv.api.eventNames.SLIDER.EVENT_SLIDER_SET_VALUES, null, { value: 8 }), "mySliderId"
          );

Here is a simple example of doing this with emit and on

// listen to a custom event called "test" for a slider with slider id "slider1"
cgpv.api.on("test", function(props) {
    console.log(props.testProps);
}, "slider1");

// emit a custom event not connected to a map, an event that will emit to control another slider with id "slider1"
cgpv.api.emit({
    event: "test",  // event name
    handlerName: null, // mapId, null as we don't want to connect it to a mapId
    testProps: "my prop test" // custom props
}, "slider1")

If you need to pass a handlerName (mapId) above then you need to update the above to look like this

// emit an event on map with map id "mapWM" and slider id "slider1"
cgpv.api.emit({
    event: "test",  // event name
    handlerName: "mapWM", // mapId
    testProps: "my prop test" // custom props
}, "slider1")

// listen to a custom event called "test" for a slider with slider id "slider1" that is connected with a map using map id "mapWM"
cgpv.api.on("test", function(props) {
    console.log(props.testProps);
}, "mapWM", "slider1");

**Review by yass0016 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/422)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/ui/slider/slider.tsx` line 62 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/422#-N1OlRQn94Lrb7zK1cJs:-N1dERcv2rLpzktT0cgR:b-ctrph2) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/51d7c2848338c0a63dd50d70c9c1bfe2dc435df8/packages/geoview-core/src/ui/slider/slider.tsx#L62)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

> Make it work only with the slider id, no map involve as it is not really connected to a map. If we do we do it with the mapId props
</blockquote></details>

See above comment

**Review by yass0016 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/422)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by yass0016 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/422)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
