### PR TITLE
GeoView-GeoChart prerequisites PR for the GeoView-GeoChart plugin PR

### PR DESCRIPTION
**Pull request by Alex-NRCan**
This PR list a couple adjustments in GeoView Core for the upcoming GeoView-GeoChart PR.

- New TypeFeatureInfoEntryPartial type
- New Esri-related common functions
- Turned the styling of select-style theme usage as optional values (because there are no themes when importing a cgpv ui component in an external package where there are no maps and no ThemeProvider - discuss)
- Tweaked the checkbox-list-enhanced.tsx to align with a pattern in select.tsx (part of this commit too)
- I couldn't find out how to make the MenuItemProps.content property work when passed via TypeMenuItemProps. The Component was failing to unpack. So, I'm directly injecting the component prop - more explicitly - and this works fine.
- Exposing more props to the slider-base, like : orientation, valueLabelFormat, getAriaValueText
- Added a useEffect to the slider component so that it listens when the parent component wants to update the content (because the value was using a state internally and would never change ulteriorly)
- Added some TODOs

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1443)

### CODE REVIEW

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1443)* status: all files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan, @jolevesq, and @kaminderpal)

___
*[`packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1443#-NiA1Vm26kaowoFcZXQp:-NiA1Vm26kaowoFcZXQq:b-nou6g8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b37c7ba7297369d8ccc5b966b4340c5078248d49/packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts#L78)):*
> ```XML
>  * to add more information on one or the other and keep things loosely linked together.
>  */
> export type TypeFeatureInfoEntryPartial = Pick<TypeFeatureInfoEntry, 'fieldInfo'>;
> ```

This will probably have to be moved in the store because the team wants to avoid direct acces to the layer sets and its events from the components
___
*[`packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts` line 87 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1443#-NiA19-mC8jqLQJC65fl:-NiA19-mC8jqLQJC65fm:b-k8pbfd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b37c7ba7297369d8ccc5b966b4340c5078248d49/packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts#L87)):*
> ```XML
> 
> // TODO: Refactor - Should probably call this a 'ResultsSet' instead of 'ResultSets' to avoid confusion, because it's a single set of results, not multiple sets of result(s).
> export type TypeFeatureInfoResultSets = {
> ```

It is plural because each layer path is a feature info result set and there can be many layer path in the object.
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 54 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1443#-NiA3pY18Q99yG0zV2PZ:-NiA3pY18Q99yG0zV2P_:b-9iavr7) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b37c7ba7297369d8ccc5b966b4340c5078248d49/packages/geoview-core/src/geo/layer/layer.ts#L54)):*
> ```XML
>   /** Layers with valid configuration for this map. */
>   registeredLayers: { [layerEntryConfigId: string]: TypeLayerEntryConfig } = {};
>   // TODO: Refactor - Export the custom type written above as an official type
> ```

If neeeded, we can create the TypeRegisteredLayers.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 365 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1443#-NiA7pSm4un4CG_BWmUB:-NiA7pSm4un4CG_BWmUC:bbiezyb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b37c7ba7297369d8ccc5b966b4340c5078248d49/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L365)):*
> ```XML
> }
> 
> /**
> ```

Is the following function usefull for all other type of GeoView layers? If yes, we should place it in a class higher in the inheritance tree.

Also, it may have to be linked to the store data type instead of the layerSet one.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 373 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1443#-NiA5KK-31v-BdAN5aBH:-NiA5KK-31v-BdAN5aBI:btoy8sw) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b37c7ba7297369d8ccc5b966b4340c5078248d49/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L373)):*
> ```XML
>  */
> export function parseFeatureInfoEntries(results: TypeJsonObject[]): TypeFeatureInfoEntryPartial[] {
>   // Loop on the Esri results
> ```

The GeoView github section dedicated to programmers mentions that we should use long variable names wherever possible to be as descriptive as possible. The variable ***fieldInformation*** is preferred to ***fi*** which can mean firstIteration, formatInformation, etc. I know that in this section of the code this is fairly obvious, but in other cases it isn't and it's best to develop this habit everywhere when coding.

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1443)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @jolevesq, @kaminderpal, and @ychoquet)

___
*[`packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1443#-NiA1Vm26kaowoFcZXQp:-NiAVVUZ--bhy4OAIIZR:b1ahyit) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b37c7ba7297369d8ccc5b966b4340c5078248d49/packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts#L78)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

This will probably have to be moved in the store because the team wants to avoid direct acces to the layer sets and its events from the components
</blockquote></details>

That's fine with me. That new type should follow wherever TypeFeatureInfoEntry goes. It's kind of why I purposely 'loosely linked' them together.
___
*[`packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts` line 87 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1443#-NiA19-mC8jqLQJC65fl:-NiAVgqABPr4I-GbcmQV:bzb66mt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b37c7ba7297369d8ccc5b966b4340c5078248d49/packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts#L87)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

It is plural because each layer path is a feature info result set and there can be many layer path in the object.
</blockquote></details>

I understand the results are plural for sure, because you have multiple results in multiple layer paths results. However, the type is just 'an object' like you said above, not a 'list'. When I started using the type in my development, I was expecting more like an array of sets which was slightly confusing to me so I noted it down at the time.

That said, it's not a breaking issue at all, just a TODO.
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 54 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1443#-NiA3pY18Q99yG0zV2PZ:-NiAWfFZDsnU9jQNHruY:bf17bwm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b37c7ba7297369d8ccc5b966b4340c5078248d49/packages/geoview-core/src/geo/layer/layer.ts#L54)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

If neeeded, we can create the TypeRegisteredLayers.
</blockquote></details>

Yes, that's why I put the TODO there. Should I do it as part of this PR or just leave the TODO?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 365 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1443#-NiA7pSm4un4CG_BWmUB:-NiAWsPE2LThks1MrgHO:b-sopk80) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b37c7ba7297369d8ccc5b966b4340c5078248d49/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L365)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Is the following function usefull for all other type of GeoView layers? If yes, we should place it in a class higher in the inheritance tree.

Also, it may have to be linked to the store data type instead of the layerSet one.
</blockquote></details>

When I implemented the queries on Esri related records. I kept in mind the logic that exists in the different types of layers being abstracted as a 'TypeFeatureInfoEntry'. In the sense that we're going to want to support different types of 'related records' not just Esri and they all will return 'TypeFeatureInfoEntryPartial[]'.

This particular function parses Esri results payload, due to the existance of the 'attributes' property (line 381) which exists on Esri responses payloads, but not necessarily for another type of 'related records' payload.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 373 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1443#-NiA5KK-31v-BdAN5aBH:-NiAZ70k8lg8dvcztnU3:b-lx3brk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b37c7ba7297369d8ccc5b966b4340c5078248d49/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L373)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

The GeoView github section dedicated to programmers mentions that we should use long variable names wherever possible to be as descriptive as possible. The variable ***fieldInformation*** is preferred to ***fi*** which can mean firstIteration, formatInformation, etc. I know that in this section of the code this is fairly obvious, but in other cases it isn't and it's best to develop this habit everywhere when coding.
</blockquote></details>

That's fine. I'll update the inner variable.

**Review by ychoquet — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1443)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq and @kaminderpal)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 54 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1443#-NiA3pY18Q99yG0zV2PZ:-NiB6gak5EJtbrvEoSMf:b-rumugt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b37c7ba7297369d8ccc5b966b4340c5078248d49/packages/geoview-core/src/geo/layer/layer.ts#L54)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Yes, that's why I put the TODO there. Should I do it as part of this PR or just leave the TODO?
</blockquote></details>

Leave the TODO

**Review by jolevesq — APPROVED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1443)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Pull request merged**
