### PR TITLE
styling legend tab

### LINKED ISSUE #1363: [BUG] Legend - Fix issue of how we select maps
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Fix issue below.
image

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### LINKED ISSUE #1410: [BUG] Legend - Hiding legend items should also remove them from the Legend Overview
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When visibility of a layer is turned OFF we can see it in the LegendOverview.

### Expected Behavior

When a legend item visibility is turned OFF; it should dissapear from the LegendOverview.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### LINKED ISSUE #1465: Implement UI for the new Legend

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

Improvements to legend tab styling

Fixes #1465 
Fixes #1410 
Fixes #1363 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://cphelefu.github.io/geoview/raw-legend-2.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1490)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1490)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @cphelefu)

___
*[`packages/geoview-core/src/core/components/legend-2/legend-layer.tsx` line 94 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1490#-NiuWblC-gBYtvfZnA74:-NiuWblC-gBYtvfZnA75:b-ismuha) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6896c6ca66fae332ad54c6a06b0b7a8ba7418d14/packages/geoview-core/src/core/components/legend-2/legend-layer.tsx#L94)):*
> ```XML
>       return (
>         <IconButton sx={{ color: 'red' }}>
>           <ErrorIcon />
> ```

Vlad UX doc as also a bacground color for error
___
*[`packages/geoview-core/src/core/components/legend-2/legend-layer.tsx` line 101 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1490#-NiuWhlc2opBa3ZeiS0T:-NiuWhlc2opBa3ZeiS0U:b-u688zh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6896c6ca66fae332ad54c6a06b0b7a8ba7418d14/packages/geoview-core/src/core/components/legend-2/legend-layer.tsx#L101)):*
> ```XML
>       return (
>         <IconButton sx={{ color: 'gray' }}>
>           <DownloadingIcon />
> ```

Vald UX doc has a circular progress animation for this icon. CAn wee use the one we have in ui?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/legend-2/legend-layer.tsx` line 101 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1490#-NiuWhlc2opBa3ZeiS0T:-NiuXAlc1TmmALSw3BE7:bazsqu3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6896c6ca66fae332ad54c6a06b0b7a8ba7418d14/packages/geoview-core/src/core/components/legend-2/legend-layer.tsx#L101)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Vald UX doc has a circular progress animation for this icon. CAn wee use the one we have in ui?
</blockquote></details>

Yep, all those changes are for another task. Coming your way soon.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/legend-2/legend-layer.tsx` line 94 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1490#-NiuWblC-gBYtvfZnA74:-NiuXIrKDpEAYVFB3hYR:b-kn8dsl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6896c6ca66fae332ad54c6a06b0b7a8ba7418d14/packages/geoview-core/src/core/components/legend-2/legend-layer.tsx#L94)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Vlad UX doc as also a bacground color for error
</blockquote></details>

We have a different task for dealing with icon colors and states.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1490)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @cphelefu)

**Review by jolevesq — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1490)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @cphelefu)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1490#-:-Niu_hrr-3spRmtPDVk-:bnfp4nl)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @cphelefu)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1490)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
