### PR TITLE
feat(geolocator): implement geolocator filters #closes1679

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Implement filters `province` and `type` for Geolocator component.

Fixes # ([1679](https://app.zenhub.com/workspaces/geoview-web-team-6332f4560a41153d1fefbcbc/issues/gh/canadian-geospatial-platform/geoview/1679))

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
Light version - https://kaminderpal.github.io/geoview/raw-data-table.html
Dark version - https://kaminderpal.github.io/geoview/loading-packages.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1698)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1698)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/geolocator/geolocator-result.tsx` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1698#-NoRiyyLCbDchAXcLQ1k:-NoRiyyLCbDchAXcLQ1l:b-snsnlc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/28edf465a6b218035dd90488782ca93462eefb4b/packages/geoview-core/src/core/components/geolocator/geolocator-result.tsx#L78)):*
> ```XML
>     if (province || type) {
>       const filterData = geoLocationData.filter((item) => {
>         if (province && !type) {
> ```

Should it be if then else loop as it can only be one thing?
___
*[`packages/geoview-core/src/core/utils/constant.ts` line 24 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1698#-NoRlUXl9uuluwnQukoI:-NoRlUXl9uuluwnQukoJ:b-gz0vmo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/28edf465a6b218035dd90488782ca93462eefb4b/packages/geoview-core/src/core/utils/constant.ts#L24)):*
> ```XML
> };
> 
> export const PROVINCES = [
> ```

You also need it for French map....

Maybe we should do like Type and extract provinces automatically from result and clear filter on new search

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1698)* status: 2 of 11 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/geolocator/geolocator-result.tsx` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1698#-NoRiyyLCbDchAXcLQ1k:-Np006_oCiR50MF-ChhT:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d878ec6a705b23792e8e06511cfd9a21f913a305/packages/geoview-core/src/core/components/geolocator/geolocator-result.tsx#L78)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should it be if then else loop as it can only be one thing?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/constant.ts` line 24 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1698#-NoRlUXl9uuluwnQukoI:-Np007O8A_IqF5UJDfh9:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d878ec6a705b23792e8e06511cfd9a21f913a305/packages/geoview-core/src/core/utils/constant.ts#L24)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You also need it for French map....

Maybe we should do like Type and extract provinces automatically from result and clear filter on new search
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r2, 3 of 4 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1698)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 92 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1698#-Np0AudeEGjn_5xZe1vl:-Np0Audf5bJfev1PWSJi:b-931j8r) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5fbf478d505b006fe7a7aede7c20997fc235cda7/packages/geoview-core/src/core/utils/config/config-validation.ts#L92)):*
> ```XML
>     serviceUrls: {
>       keys: 'https://geocore.api.geo.ca',
>       geolocator: 'https://yh57qxljujd5dj33pqqahfjhyu0amqtn.lambda-url.ca-central-1.on.aws/?keys=geonames,nominatim,locate',
> ```

CAn you jujst put a TODO: replace for the old url and keep it in comment

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1698)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/utils/config/config-validation.ts` line 92 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1698#-Np0AudeEGjn_5xZe1vl:-Np0FhapBdJ4CERONfrv:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/5fbf478d505b006fe7a7aede7c20997fc235cda7/packages/geoview-core/src/core/utils/config/config-validation.ts#L92)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

CAn you jujst put a TODO: replace for the old url and keep it in comment
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1698)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Pull request merged**
