### PR TITLE
feature(Swiper) - Using new Swiper store, small guide fix, better info logs, some other fixes and comments

### LINKED ISSUE #1820: [REFACTOR] Swiper use store
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

As a developer I would like to access swiper with store

Like the time slider and chart, we should have a store (state/event processor). to keep swiper state and provide function from api, when swiper is there to add/remove layers from it.

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

Stores created
Style class created and separated from component
Fix for the path for the guide panel
Swiper, working state
Swiper improved
Moved the addEventListener and removeEventListener from the rendering phase to a useEffect mount hook.
Better logs and comments
Swiper working
Had to use async afterall to retrieve the OpenLayers layers
Adjusting the swiper template configs to use layer path
Finalizing
Cleanup

Fixes #1820

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Hosted here as of Feb. 26 15h: https://alex-nrcan.github.io/geoview/package-swiper.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1858)

### CODE REVIEW

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1858)* status: 16 of 22 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/swiper-event-processor.ts` line 23 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1858#-Nrap2Pk65VB571H5Lro:-Nratza98d0FJIye33pA:bb4ti0q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cce9c134f4edffe52115e5b9a08e0db0e0555084/packages/geoview-core/src/api/event-processors/event-processor-children/swiper-event-processor.ts#L23)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think the onInit method should be before the big block of comments as it is not static
</blockquote></details>

True! Done.
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 64 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1858#-NrapqFU2YjYDunBObXe:-Nrav4VY3Pfgchihkc2-:bklb0vk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cce9c134f4edffe52115e5b9a08e0db0e0555084/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L64)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Hum this should be relative to the location of main.js file.... ./locales/help/help.md We may need a specific issue if requires too much work
</blockquote></details>

True, that might work. Let me try that in the host I'm doing when I push this.
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 529 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1858#-NraqOkXDdIlBscaPJTM:-Nrav9AiAvo4azqtLjl1:b-94x5m1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cce9c134f4edffe52115e5b9a08e0db0e0555084/packages/geoview-core/src/geo/layer/layer.ts#L529)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we call getOLLayer... to have ol in the name for clarity?
</blockquote></details>

Yep, sounds good to me. Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1858)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1858)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1858)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Pull request merged**
