### PR TITLE
feat(exportTemplate): export template  #closes795

### LINKED ISSUE #795: Create export template
https://github.com/fgpv-vpgf/fgpv-vpgf/tree/master/packages/ramp-core/src/app/ui/export

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Implement export template view before downloaded the map and legend layers as image png.

Fixes #795 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/raw-feature-info.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/package.json` line 52 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911#-Nt0xWInEPRAn3fcYdo6:-Nt0xWInEPRAn3fcYdo7:b-dchhkz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c0fef5061d6ef26dbde188451acf1d601b69f30c/packages/geoview-core/package.json#L52)):*
> ```JSON
>     "@emotion/styled": "^11.11.0",
>     "@mui/base": "5.0.0-beta.37",
>     "@mui/lab": "5.0.0-alpha.168",
> ```

What does this dependency
___
*[`packages/geoview-core/package.json` line 91 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911#-Nt0xsM87TxR_ocXpx44:-Nt0xsM87TxR_ocXpx45:byx8b3r) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c0fef5061d6ef26dbde188451acf1d601b69f30c/packages/geoview-core/package.json#L91)):*
> ```JSON
>     "react-dropzone": "^14.2.3",
>     "markdown-to-jsx": "~7.4.0",
>     "html2canvas": "^1.4.1"
> ```

From npm readme
```
The script is still in a very experimental state, so I don't recommend using it in a production environment nor start building applications with it yet, as there will be still major changes made.
```

Do we have a library more stable we can use. It has not been touched in 2 years.

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/package.json` line 52 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911#-Nt0xWInEPRAn3fcYdo6:-NtMSjZkCWZyRUrqZgUf:b-ajnr8d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c0fef5061d6ef26dbde188451acf1d601b69f30c/packages/geoview-core/package.json#L52)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

What does this dependency
</blockquote></details>

There are some experimental features provided by Material UI. 
https://mui.com/material-ui/react-button/#loading-button
I have use it for `Loading Button` that i use for exporting the image.
___
*[`packages/geoview-core/package.json` line 91 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911#-Nt0xsM87TxR_ocXpx44:-NtMT1lDASDHe4LmAo4T:b-v3egkp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c0fef5061d6ef26dbde188451acf1d601b69f30c/packages/geoview-core/package.json#L91)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

From npm readme
```
The script is still in a very experimental state, so I don't recommend using it in a production environment nor start building applications with it yet, as there will be still major changes made.
```

Do we have a library more stable we can use. It has not been touched in 2 years.
</blockquote></details>

Fill find new one.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911)* status: 5 of 13 files reviewed, 1 unresolved discussion (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/export/export-modal.tsx` line 10 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911#-NtWa1GD9vm06AuhrIq3:-NtWa1GE-rZM1fRkknNI:bvlzfjb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a50a7e40462884372254d887384134d8b7a07238/packages/geoview-core/src/core/components/export/export-modal.tsx#L10)):*
> ```XML
> import { useUIActiveFocusItem, useUIStoreActions } from '@/core/stores/store-interface-and-intial-values/ui-state';
> import { useGeoViewMapId } from '@/core/stores/geoview-store';
> import { NorthArrowIcon, api, useMapAttribution, useMapNorthArrow, useMapScale } from '@/app';
> ```

 do not import from app import from right place

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911)* status: 5 of 13 files reviewed, 2 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/export/export-modal.tsx` line 25 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911#-NtWaXckBOBx2dhGlU9h:-NtWaXckBOBx2dhGlU9i:b-kyt2zf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a50a7e40462884372254d887384134d8b7a07238/packages/geoview-core/src/core/components/export/export-modal.tsx#L25)):*
> ```XML
>   const theme = useTheme();
> 
>   const { map } = api.maps[mapId];
> ```

Put TODO: we should not access the api in component.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 3 of 9 files at r1, 3 of 5 files at r2, 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @kaminderpal)

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/export/export-modal.tsx` line 10 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911#-NtWa1GD9vm06AuhrIq3:-NtWexKJCoMPiNciZZu6:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a50a7e40462884372254d887384134d8b7a07238/packages/geoview-core/src/core/components/export/export-modal.tsx#L10)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

do not import from app import from right place
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/export/export-modal.tsx` line 25 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911#-NtWaXckBOBx2dhGlU9h:-NtWeyGk6oSVmJ274GRD:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a50a7e40462884372254d887384134d8b7a07238/packages/geoview-core/src/core/components/export/export-modal.tsx#L25)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put TODO: we should not access the api in component.
</blockquote></details>

Done.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/export/export-modal.tsx` line 65 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911#-NtWolEx3Ykb5ke55ZK-:-NtWolEx3Ykb5ke55ZK0:b3163cs) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2c9274e889a10903347b4a96d98943e434c822d6/packages/geoview-core/src/core/components/export/export-modal.tsx#L65)):*
> ```XML
>       exportTitleRef.current.innerHTML = exportTitle;
>       setIsMapExporting(true);
>       htmlToImage.toPng(exportContainerRef.current, { backgroundColor: theme.palette.common.white }).then((dataUrl) => {
> ```

How do we handle errors that happen during exporting?

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/export/export-modal.tsx` line 65 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911#-NtWolEx3Ykb5ke55ZK-:-NtWpRU3Eif_0F4Ck3bV:b-4phdpx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2c9274e889a10903347b4a96d98943e434c822d6/packages/geoview-core/src/core/components/export/export-modal.tsx#L65)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

How do we handle errors that happen during exporting?
</blockquote></details>

Added catch block.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/ui/button/loading-button.tsx` line 8 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911#-NtWqZGS7I7W5nCTy6jP:-NtWqZGS7I7W5nCTy6jQ:bih301h) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2c9274e889a10903347b4a96d98943e434c822d6/packages/geoview-core/src/ui/button/loading-button.tsx#L8)):*
> ```XML
> }
> 
> export function LoadingButton({ children, ...rest }: LoadingButtonType) {
> ```

I am really not sure about this component. I think we can build our own. we dont really need a whole package for that. This can just be a button with a spinner inside it and text.

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911)* status: 12 of 13 files reviewed, 4 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/ui/button/loading-button.tsx` line 8 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911#-NtWqZGS7I7W5nCTy6jP:-NtWrJq3CYqtetFsDx16:b6oilun) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2c9274e889a10903347b4a96d98943e434c822d6/packages/geoview-core/src/ui/button/loading-button.tsx#L8)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

I am really not sure about this component. I think we can build our own. we dont really need a whole package for that. This can just be a button with a spinner inside it and text.
</blockquote></details>

I understand for now its just one component, but in future we can add from components from `@mui/lab`, so that we re invent the wheel.

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/ui/button/loading-button.tsx` line 8 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911#-NtWqZGS7I7W5nCTy6jP:-NtWs640CNZsXzJz89LU:b-sdji6l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2c9274e889a10903347b4a96d98943e434c822d6/packages/geoview-core/src/ui/button/loading-button.tsx#L8)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

I understand for now its just one component, but in future we can add from components from `@mui/lab`, so that we re invent the wheel.
</blockquote></details>

i have checked the package size, gzip file size is 6kb for export modal

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911)* status: all files reviewed, 1 unresolved discussion (waiting on @cphelefu and @kaminderpal)

___
*[`packages/geoview-core/src/ui/button/loading-button.tsx` line 8 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1911#-NtWqZGS7I7W5nCTy6jP:-NtWsK-QBrW16ll3jzY-:b-svejh0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2c9274e889a10903347b4a96d98943e434c822d6/packages/geoview-core/src/ui/button/loading-button.tsx#L8)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

i have checked the package size, gzip file size is 6kb for export modal
</blockquote></details>

Will keep for now and see later. The size is small

**Pull request merged**
