### PR TITLE
refactor(store): Moved OL events in the store

### LINKED ISSUE #1328: [REFACTOR] Move OL event (zoom, click) in store
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For the moment, the events are in map.tsx. Use map.ts to hold events

### Expected Behavior

Store will manage the events

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1328

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (#1328 )

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
Tested on many pages that map click, mouse position, scale, ... events are still working
https://jolevesq.github.io/geoview/index.html
__Add the URL for your deploy!__

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1351)

### CODE REVIEW

**Review by DamonU2 — APPROVED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1351)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amir-azma, @cphelefu, @kaminderpal, and @ychoquet)

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/click-marker/click-marker.tsx` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1351#-NfR7fMi0_lf80B5Yr_O:-NfR7fMi0_lf80B5Yr_P:b5sgo6l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6aca2494910b7a6a923e44af3deecb3e255046a6/packages/geoview-core/src/core/components/click-marker/click-marker.tsx#L50)):*
> ```XML
>     position: [-1, -1],
>     positioning: 'center-center',
>     offset: [-18, -32],
> ```

Why did we change the offset here?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/overview-map/overview-map.tsx` line 138 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1351#-NfR8Rix834i-zXzWGIh:-NfR8Rix834i-zXzWGIi:bu3k49p) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6aca2494910b7a6a923e44af3deecb3e255046a6/packages/geoview-core/src/core/components/overview-map/overview-map.tsx#L138)):*
> ```XML
>   useEffect(() => {
>     // if zoom changed, view change:resolution event has been triggered
>     const unsubMapZoom = getGeoViewStore(mapId).subscribe(
> ```

You have a subscribe inside a useEffect? I think the two are doing the same thing

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1351)* status: all files reviewed, 2 unresolved discussions (waiting on @amir-azma, @cphelefu, @kaminderpal, and @ychoquet)

___
*[`packages/geoview-core/src/core/components/click-marker/click-marker.tsx` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1351#-NfR7fMi0_lf80B5Yr_O:-NfRAnSO4gTSm_UNzQ5g:b-kmu1fi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6aca2494910b7a6a923e44af3deecb3e255046a6/packages/geoview-core/src/core/components/click-marker/click-marker.tsx#L50)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Why did we change the offset here?
</blockquote></details>

Because the pointer is not at the tip of the icon
___
*[`packages/geoview-core/src/core/components/overview-map/overview-map.tsx` line 138 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1351#-NfR8Rix834i-zXzWGIh:-NfRAsDgAa1A-oujOnPX:b-ubpkvi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6aca2494910b7a6a923e44af3deecb3e255046a6/packages/geoview-core/src/core/components/overview-map/overview-map.tsx#L138)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

You have a subscribe inside a useEffect? I think the two are doing the same thing
</blockquote></details>

All my subscribe are in useEffect I think..... it should moved out?

**Pull request merged**
