### PR TITLE
feat(details-panel) Create a details panel to show feature,layers info

### LINKED ISSUE #18: Add details panel
Create a panel to hold the get info when a user click on the map. The return value may contain multiple layers and multiple features for each of the layers. We need to manage both.

Do not add internal field to the panel like SHAPE or OBJECTID

Make it WCAG. If not done, start an issue for WCAG to have something like in the current viewer for clicking the map

### PR DESCRIPTION
**Pull request by yass0016**
Closes #18

## Checklist

* [ ] Commit message follow the guidelines
* [ ] PR targets the correct release version
* [ ] Deploy has been done
* [ ] Check styling
* [ ] _Help files and documentation have been updated_
* [ ] ~Release notes have been updated~

## What's to look for styling
* Use camelCase for identifier names (variables and functions)
* Use PascalCase for type names
* Do not use "I" as a prefix for interface names
* Do not export types/functions unless you need to share it across multiple components
* All names start with a letter
* Always put spaces around operators ( = + - * / ), and after colon:
* Remove all trailing white spaces
* Look for bad indentation
* Carriage return are mandatory
  * Before comments
  * Before if condition
  * After if condition
  * Before properties
  * Before classes
  * Before functions

The use of Prettier Visual Studio Code extension let's you format automatically your code to remove most of the styling issues like white space and indentation.

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 10 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158)* status: 10 of 16 files reviewed, 5 unresolved discussions (waiting on @yass0016)

___
*[src/common/layers/wms.ts, line 87 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWUb4fW-RgoWlVN2xOm:-MWUb4fW-RgoWlVN2xOn:b-bq0rv7) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c7eb73e4843b844316daacce123a640986b7ab4a/src/common/layers/wms.ts#L87)):*
> ```XML
>                      * Get feature info url from a lat lng point
>                      *
>                      * @param latlng a latlng point to generate the feature url from
> ```

Put type in { }
___
*[src/common/layers/wms.ts, line 122 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWUbGS729QBTI2XP0vc:-MWUbGS729QBTI2XP0vd:b-bq0rv7) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c7eb73e4843b844316daacce123a640986b7ab4a/src/common/layers/wms.ts#L122)):*
> ```XML
>                      * Convert an XML document object into a json object
>                      *
>                      * @param xml the XML document object
> ```

Put type in { }
___
*[src/common/layers/wms.ts, line 129 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWUbLTnCHoXNCOJX1V4:-MWUbLTnCHoXNCOJX1V5:b-9x0zpb) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c7eb73e4843b844316daacce123a640986b7ab4a/src/common/layers/wms.ts#L129)):*
> ```XML
>                         let obj: Record<string, any> = {};
> 
>                         if (xml.nodeType === 1) {
> ```

Can you add a comment about node type to explain what it is
___
*[src/common/ui/button.ts, line 13 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWUbaJJ5ilpQ4qATcyr:-MWUbaJJ5ilpQ4qATcys:b-vn1jva) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c7eb73e4843b844316daacce123a640986b7ab4a/src/common/ui/button.ts#L13)):*
> ```XML
>     // optional callback function to run on button click
>     callback?: () => void;
>     // should the button be displayed in the appbar/navbar?
> ```

Crosshair should not be in navbar. It is visible only when user has keyboard focus on the map
___
*[src/components/mapctrl/crosshair.tsx, line 74 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWUcEQsCIXjcZJcLYsD:-MWUcEQsCIXjcZJcLYsE:b-f3bwfe) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c7eb73e4843b844316daacce123a640986b7ab4a/src/components/mapctrl/crosshair.tsx#L74)):*
> ```XML
>     // tracks if the last action was done through a keyboard (map navigation) or mouse (mouse movement)
>     const [isCrosshairsActive, setCrosshairsActive] = useState(false);
>     const [panelButtonId, setPanelButtonId] = useState<string>();
> ```

Do not add to nav bar, only visible when user focus the map with keyboard

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158)* status: 10 of 18 files reviewed, 5 unresolved discussions (waiting on @jolevesq)

___
*[src/common/layers/wms.ts, line 87 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWUb4fW-RgoWlVN2xOm:-MWUfnYf5iw4vF7NQMOf:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c7eb73e4843b844316daacce123a640986b7ab4a/src/common/layers/wms.ts#L87)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put type in { }
</blockquote></details>

Done.
___
*[src/common/layers/wms.ts, line 122 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWUbGS729QBTI2XP0vc:-MWUfp5p2mW3uA5pBXnm:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c7eb73e4843b844316daacce123a640986b7ab4a/src/common/layers/wms.ts#L122)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put type in { }
</blockquote></details>

Done.
___
*[src/common/layers/wms.ts, line 129 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWUbLTnCHoXNCOJX1V4:-MWUfq1QEsLqsPqLqHiB:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c7eb73e4843b844316daacce123a640986b7ab4a/src/common/layers/wms.ts#L129)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add a comment about node type to explain what it is
</blockquote></details>

Done.
___
*[src/common/ui/button.ts, line 13 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWUbaJJ5ilpQ4qATcyr:-MWV-5gGDQ6pU9XSLO_8:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c7eb73e4843b844316daacce123a640986b7ab4a/src/common/ui/button.ts#L13)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Crosshair should not be in navbar. It is visible only when user has keyboard focus on the map
</blockquote></details>

Done.
___
*[src/components/mapctrl/crosshair.tsx, line 74 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWUcEQsCIXjcZJcLYsD:-MWV-6QODKIwnA4X2qNT:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c7eb73e4843b844316daacce123a640986b7ab4a/src/components/mapctrl/crosshair.tsx#L74)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do not add to nav bar, only visible when user focus the map with keyboard
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 16 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158)* status: all files reviewed, 4 unresolved discussions (waiting on @yass0016)

___
*[public/plugins/details-panel/details-panel.js, line 22 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWV9h_z7eevkEzt02xR:-MWV9h_z7eevkEzt02xS:b-fiehoy) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e670abd821f01f544e57507e53f0723807aff8e6/public/plugins/details-panel/details-panel.js#L22)):*
> ```JavaScript
>                 nothing_found: 'Nothing found',
>                 action_back: 'Back',
>                 activate_crosshair: 'Activate Crosshair',
> ```

Don't need this I think
___
*[public/plugins/details-panel/details-panel.js, line 28 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWV9lhZ4znTyrw0n_zY:-MWV9lhZ4znTyrw0n_zZ:b-fiehoy) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e670abd821f01f544e57507e53f0723807aff8e6/public/plugins/details-panel/details-panel.js#L28)):*
> ```JavaScript
>                 nothing_found: 'Aucun résultat',
>                 action_back: 'Retour',
>                 activate_crosshair: 'Activer le réticule',
> ```

Don't need this I think
___
*[public/plugins/details-panel/details-panel.js, line 249 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWV9ymZ8ZOV7cTlc0JZ:-MWV9ymZ8ZOV7cTlc0J_:b-p9slhs) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e670abd821f01f544e57507e53f0723807aff8e6/public/plugins/details-panel/details-panel.js#L249)):*
> ```JavaScript
>                         const data = props.layersData[dataKey];
> 
>                         return h(
> ```

Question, what is h?
___
*[public/plugins/details-panel/details-panel.js, line 866 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWVA_L0AVoADx-CTD3P:-MWVA_L0AVoADx-CTD3Q:b5bjb78) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e670abd821f01f544e57507e53f0723807aff8e6/public/plugins/details-panel/details-panel.js#L866)):*
> ```JavaScript
> 
>                             // try to add the legend image url for the WMS layer
>                             const legendImageUrl = `${mapLayer.layer._url}?request=GetLegendGraphic&version=1.0.0&Service=WMS&format=image/png&layer=0`;
> ```

Will not always be 0, it is the entries value for the layer.

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158)* status: all files reviewed, 4 unresolved discussions (waiting on @jolevesq)

___
*[public/plugins/details-panel/details-panel.js, line 22 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWV9h_z7eevkEzt02xR:-MWVDeqQCDDPmd0j0ejp:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e670abd821f01f544e57507e53f0723807aff8e6/public/plugins/details-panel/details-panel.js#L22)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Don't need this I think
</blockquote></details>

Done.
___
*[public/plugins/details-panel/details-panel.js, line 28 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWV9lhZ4znTyrw0n_zY:-MWVDgNmDYK62UpOWs1t:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e670abd821f01f544e57507e53f0723807aff8e6/public/plugins/details-panel/details-panel.js#L28)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Don't need this I think
</blockquote></details>

Done.
___
*[public/plugins/details-panel/details-panel.js, line 249 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWV9ymZ8ZOV7cTlc0JZ:-MWVDsJU9csPKIPKpN2-:b-9m7oro) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e670abd821f01f544e57507e53f0723807aff8e6/public/plugins/details-panel/details-panel.js#L249)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Question, what is h?
</blockquote></details>

It's a reference to createElement so we can create React elements, react will then handle converting them to HTML elements. There is a comment for this under the Component element.

// h is a reference to this.createElement
// createElement is a React function to create React HTML elements
// It takes 3 arguments, the tag element name, the attributes of the element and the content of the element
___
*[public/plugins/details-panel/details-panel.js, line 866 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWVA_L0AVoADx-CTD3P:-MWVENnB3fgEfSWoPQyl:b-flmy5s) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e670abd821f01f544e57507e53f0723807aff8e6/public/plugins/details-panel/details-panel.js#L866)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Will not always be 0, it is the entries value for the layer.
</blockquote></details>

For WMS it's not always 0? Can we have multiple WMS layers in the same Map Server?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @jolevesq and @yass0016)

___
*[public/plugins/details-panel/details-panel.js, line 866 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWVA_L0AVoADx-CTD3P:-MWVEnbP5XlokzfOgek0:b1nhrab) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e670abd821f01f544e57507e53f0723807aff8e6/public/plugins/details-panel/details-panel.js#L866)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

For WMS it's not always 0? Can we have multiple WMS layers in the same Map Server?
</blockquote></details>

Yes we can have multiple entries. They can be index number or text. Would you like to solve this before we merge?

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[public/plugins/details-panel/details-panel.js, line 866 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWVA_L0AVoADx-CTD3P:-MWVGeom0WV6jinQd2yQ:blnheio) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e670abd821f01f544e57507e53f0723807aff8e6/public/plugins/details-panel/details-panel.js#L866)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Yes we can have multiple entries. They can be index number or text. Would you like to solve this before we merge?
</blockquote></details>

I tried before to find the index from the loaded WMS layer but I couldn't find a solution to it. I tried with getFeatureInfo but it does not return the index of it. If you have a solution for this or know of a way to request / query the index I can fix it now, otherwise maybe you can take a look at it later

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158)* status: 16 of 18 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[public/plugins/details-panel/details-panel.js, line 866 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158#-MWVA_L0AVoADx-CTD3P:-MWVft4L5n6fW7W8u8Xg:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/e670abd821f01f544e57507e53f0723807aff8e6/public/plugins/details-panel/details-panel.js#L866)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

I tried before to find the index from the loaded WMS layer but I couldn't find a solution to it. I tried with getFeatureInfo but it does not return the index of it. If you have a solution for this or know of a way to request / query the index I can fix it now, otherwise maybe you can take a look at it later
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/158)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yass0016)

**Pull request merged**
