### PR TITLE
feat(details-tab): Fix style issue and re-factor details tab

### LINKED ISSUE #1334: [FEATURE] Fix styling issue in Details panel
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

_No response_

### User Story

Remove the text at top of the details panel.
Texts inside the right panel table are a little small, make them larger. Bold the key name similar to screenshot below.
Move clear all button outside the box in right panel, and place it next to Selected Features text.
Modify the feature info table to be able to see long texts in second column, you might need to merge 2 cells in one cell. You can see an example in screenshot below
image

https://search.open.canada.ca/openmap/fe83a604-aa5a-4e46-903c-685f8b0cc33c

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by amir-azma**
# Description

Fix styling issue and refactor the left and right panel in Details tab.

Fixes #1334 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://amir-azma.github.io/geoview/raw-feature-info-1.html

image

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1359)

### CODE REVIEW

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1359)* status: 0 of 9 files reviewed, 1 unresolved discussion

___
*[`packages/geoview-core/src/ui/style/default.ts` line 203 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1359#-NfwNpDQDzTKMmucoCDa:-NfwNpDQDzTKMmucoCDb:b5ibvh0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/2e9e302e268b4200c8b677171474bc5d05c1bd9e/packages/geoview-core/src/ui/style/default.ts#L203)):*
> ```XML
>     contentBg: '#F1F2F5 0% 0% no-repeat padding-box',
>     contentShadow: 'inset 0px 3px 6px #00000029',
>     titleFont: `normal normal 600 20px/27px ${font}`,
> ```

For now I added ${font}  , to use the default font we have  on line 3 , later we should see how to apply the correct font like Open Sans

**Review by jolevesq — APPROVED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1359)* status: all files reviewed, 1 unresolved discussion

**Review by jolevesq — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1359#-:-NfxFrYa3h8_tSlfHB7r:bg7igkv)* status: all files reviewed, 1 unresolved discussion

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1359)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amir-azma)

**Pull request merged**
