### PR TITLE
refactor(timeslider): update time slider to use store

### LINKED ISSUE #1453: [FEATURE] Update time slider to use store
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Geoview team

### User Story

Once list of visible layers is available int the geoview store, update the time slider to use it to update list of available layers.

Also create a specific interface to manage slider info when it needs to be accessible from outside

### Implementation UI

_No response_

### LINKED ISSUE #1576: [DEMO] Add Footer to all layer type
Add layers, details, data table footer tab component to all layer type demo page in a new map to help test all different layers type

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #1453
Closes #1576 

# Description

Refactored time slider to use the store. Also added a map with a footer panel to all of the layer type demo pages.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested to see if time slider functionality matched with pre-refactor version

https://damonu2.github.io/geoview/package-time-slider.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1578)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1578)* status: 18 of 21 files reviewed, 7 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts` line 13 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1578#-Nkq5Vs93q7_qFSUunT5:-Nkq5Vs93q7_qFSUunT6:bfbn8to) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ad27ba56409cc8274e68a61b782b1ce567db459f/packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts#L13)):*
> ```XML
>       api.eventNames.MAP.EVENT_MAP_LOADED,
>       () => {
>         const initialLegends = store.getState().layerState.legendLayers;
> ```

You can listen to legend layers array to get values instead of map loaded I think
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts` line 30 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1578#-Nkq4BM84SRrZ8wVecTb:-Nkq4BM84SRrZ8wVecTc:b-ybwwho) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ad27ba56409cc8274e68a61b782b1ce567db459f/packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts#L30)):*
> ```XML
>     const unsubLayerLegendLayers = store.subscribe(
>       (state) => state.layerState.legendLayers,
>       (curLegendLayers, prevLegendLayers) => {
> ```

This subscribe is trigger often because there is many modification to the object all the time... You may have all this inside the store as a compute actions were you use the value of legend layer in the action ...

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1578)* status: 18 of 21 files reviewed, 7 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts` line 13 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1578#-Nkq5Vs93q7_qFSUunT5:-NkqlzZqDT4Ek5GJM-JJ:b-6m8or) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ad27ba56409cc8274e68a61b782b1ce567db459f/packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts#L13)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You can listen to legend layers array to get values instead of map loaded I think
</blockquote></details>

I tried that initially, but had issues with it being completed before the time slider loaded, leaving no data until the legend layers array updated
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts` line 105 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1578#-Nkq2OKW9MSF5cVAd1vA:-Nkqc_vz63SpNupkLMvE:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ad27ba56409cc8274e68a61b782b1ce567db459f/packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts#L105)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You may combine set values with set filter as they work together. Only thing is to check if the slider is enable.
This way we make sure we do not set values and forget the apply filter.
</blockquote></details>

Done.
___
*[`packages/geoview-time-slider/src/time-slider-panel.tsx` line 34 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1578#-Nkq2w59-jwGB9gPB55f:-NkqbtXP2VXhrcObNWV1:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ad27ba56409cc8274e68a61b782b1ce567db459f/packages/geoview-time-slider/src/time-slider-panel.tsx#L34)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Use the store to get display language. It will be remove from the api. In fact most of static value will be remove and the store will be to only point of access.
</blockquote></details>

Done.

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1578)* status: 18 of 21 files reviewed, 7 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts` line 65 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1578#-Nkq1kSZ-A1J2dj7Taxg:-NkqmTZd-cKum38g3IK1:b-b9q033) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ad27ba56409cc8274e68a61b782b1ce567db459f/packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts#L65)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this needed in the store... can it be a useState inside the component as it is mostly internal and I doubt it may be use somewhere else
</blockquote></details>

If they are in a useState they value is lost when switching to a different tab or layer. I can pass values back to an object in the time-slider-panel (how it worked before) but this seemed much cleaner.

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1578)* status: 17 of 24 files reviewed, 7 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts` line 30 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1578#-Nkq4BM84SRrZ8wVecTb:-NkueNFxBWjK8xTF3ssE:bck2lao) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ad27ba56409cc8274e68a61b782b1ce567db459f/packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts#L30)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This subscribe is trigger often because there is many modification to the object all the time... You may have all this inside the store as a compute actions were you use the value of legend layer in the action ...
</blockquote></details>

Will update once layer order and visible layers are available in store.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 21 files at r1, 3 of 6 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1578)* status: all files reviewed, 2 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-time-slider/src/time-slider-panel.tsx` line 46 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1578#-NkvBSTT-4iINzV3xzl0:-NkvBSTT-4iINzV3xzl1:b-3ul9z9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d1cbd60670e48a99373fdf024456e8948f1f44af/packages/geoview-time-slider/src/time-slider-panel.tsx#L46)):*
> ```XML
> 
>   const store = getGeoViewStore(mapId);
>   const { displayLanguage } = store.getState();
> ```

You need to use the atomic selector to get store value from tsx file (useAppDisplayLanguage). May not be there yet. If not put a TODO for me to fix on rebase

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1578)* status: 22 of 24 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-time-slider/src/time-slider-panel.tsx` line 46 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1578#-NkvBSTT-4iINzV3xzl0:-NkvExJZCv8Yg9vsgtFE:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d1cbd60670e48a99373fdf024456e8948f1f44af/packages/geoview-time-slider/src/time-slider-panel.tsx#L46)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You need to use the atomic selector to get store value from tsx file (useAppDisplayLanguage). May not be there yet. If not put a TODO for me to fix on rebase
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1578)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
