### PR TITLE
adding zoom in button in details component

### LINKED ISSUE #813: Add zoom in button to details component
On the details component, add the zoom in to feature button

### PR DESCRIPTION
**Pull request by dennisfu**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #813

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Go to details panel or footer panel details tab, click on map, showing the details featureinfo, clicking the '+' (zoom in button) would center the map to the point clicked and zoom in the map 

# Checklist:

- [ x ] I have connected the issues(s) to this PR
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] My changes generate no new warnings
- [ x ] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
It is not working, the viewer zoom out instead of zooiming in and the icon is a plus sign instead of the magnifyer with a plus sign inside.



> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-:-NNC2YA25zkBBGhZ_6lK:b-j6tg7x)* status: 0 of 6 files reviewed, all discussions resolved

**Comment by dennisfu** [comment]
@jolevesq changed the icon and added the geometry to the featureinfo by feature.getGeometry() in vector class, but seems the the geometry is not right, I tried to get the center from the geometry, the point is not located to the feature. not sure what's the issue, the getGeometry() is not right or cann't get the center point like this?

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866)* status: all files reviewed, 6 unresolved discussions (waiting on @dennisfu and @jolevesq)

___
*[`packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts` line 18 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NOkDOU9BT1HYaedx5WF:-NOkDOU9BT1HYaedx5WG:b-ko52yz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts#L18)):*
> ```XML
> export type TypeQueryType = 'at pixel' | 'at coordinate' | 'at long lat' | 'using a bounding box' | 'using a polygon';
> 
> export type TypeFeatureInfoEntry = {
> ```

The TypeFeatureInfoEntry has changed a lot in the PR https://github.com/Canadian-Geospatial-Platform/geoview/pull/914.
These changes affect considerably the code of this PR. I think it is preferable to merge PR 914 before this one and adapt it to the new TypeFeatureInfoEntry structure.
___
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 101 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NOkEqLU99-yYkVdvOsJ:-NOkEqLU99-yYkVdvOsK:b4nzgjg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-core/src/core/components/details/feature-info.tsx#L101)):*
> ```XML
>   const [currentZoom, setCurrentZoom] = useState<boolean>(false);
> 
>   const getFeatureZoomCenter = (geometry: Geometry) => {
> ```

The new structure of TypeFeatureInfoEntry has the extent and the map has a zoomToExtent function that simplifies a lot the zoom operation. This code is too complicated and useless if we take into account the feature info capacities.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 233 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NOkFmrY9LO9JG1tTBbR:-NOkFmrY9LO9JG1tTBbS:b-6ouyba) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L233)):*
> ```XML
>           featureKey: keyCounter++,
>           featureInfo: {},
>           geometry: feature.getGeometry(),
> ```

This section of code has changed to addapt to the new TypeFeatureInfoEntry structure.
___
*[`packages/geoview-details-panel/src/details-item.tsx` line 68 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NOkJX_qEdyD40okppH2:-NOkJX_qEdyD40okppH3:b-nhxwqj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-details-panel/src/details-item.tsx#L68)):*
> ```XML
>       api.event.off(api.eventNames.GET_FEATURE_INFO.ALL_QUERIES_DONE, mapId);
>       api.event.off(api.eventNames.GET_FEATURE_INFO.QUERY_LAYER, mapId);
>     };
> ```

Humm! Not sure it is necessary. I think these calls do nothing. We should do some tests to see.



_Code quote:_
```XML
    return () => {
      api.event.off(api.eventNames.GET_FEATURE_INFO.ALL_QUERIES_DONE, mapId);
      api.event.off(api.eventNames.GET_FEATURE_INFO.QUERY_LAYER, mapId);
    };
```
___
*[`packages/geoview-footer-panel/src/details-item.tsx` line 69 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NOkJtVb4VyC5sRs4FWO:-NOkJtVb4VyC5sRs4FWP:b-nhxwqj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-footer-panel/src/details-item.tsx#L69)):*
> ```XML
>       api.event.off(api.eventNames.GET_FEATURE_INFO.ALL_QUERIES_DONE, mapId);
>       api.event.off(api.eventNames.GET_FEATURE_INFO.QUERY_LAYER, mapId);
>     };
> ```

Humm! Not sure it is necessary. I think these calls do nothing. We should do some tests to see.



_Code quote:_
```XML
    return () => {
      api.event.off(api.eventNames.GET_FEATURE_INFO.ALL_QUERIES_DONE, mapId);
      api.event.off(api.eventNames.GET_FEATURE_INFO.QUERY_LAYER, mapId);
    };
```
___
*[`packages/geoview-footer-panel/src/details-item.tsx` line 72 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NOkJpk20PdvkQ4o6NKD:-NOkJpk20PdvkQ4o6NKE:bz7fmvq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-footer-panel/src/details-item.tsx#L72)):*
> Humm! Not sure it is necessary. I think these calls do nothing.

**Comment by dennisfu** [comment]
Please review. would create a new issue for the marker showing

**Review by jolevesq — COMMENTED** [review]
When we click on the zoom, it closes the detail item. It should not.

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-:-NOuiTJY2tFXnxILyJCE:b-idchom)* status: 0 of 9 files reviewed, 6 unresolved discussions (waiting on @dennisfu and @ychoquet)

**Comment by dennisfu** [comment]
> 

For all the geometry related part, removed and using the rebased updating.

The "api.event.off ...", if you mean the event off, since it's from the original code, I believe it's a standard code logic, maybe it's not  necessary. if you mean the map single click, that's using to get the click position and handler name, which to keep the clicking marker showing, sine the panel expend would resizing the map, and hide the marker. created a new bug issue, if we can fix this from map api level, we should not need this  anymore

**Comment by dennisfu** [comment]
> > Reviewed 4 of 6 files at r1, 1 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866)_ status: all files reviewed, 6 unresolved discussions (waiting on @dennisfu and @jolevesq)
> 
> _[`packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts` line 18 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NOkDOU9BT1HYaedx5WF:-NOkDOU9BT1HYaedx5WG:b-ko52yz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts#L18)):_
> 
> > ```
> > export type TypeQueryType = 'at pixel' | 'at coordinate' | 'at long lat' | 'using a bounding box' | 'using a polygon';
> > 
> > export type TypeFeatureInfoEntry = {
> > ```
> 
> The TypeFeatureInfoEntry has changed a lot in the PR #914. These changes affect considerably the code of this PR. I think it is preferable to merge PR 914 before this one and adapt it to the new TypeFeatureInfoEntry structure.
> 
> _[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 101 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NOkEqLU99-yYkVdvOsJ:-NOkEqLU99-yYkVdvOsK:b4nzgjg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-core/src/core/components/details/feature-info.tsx#L101)):_
> 
> > ```
> >   const [currentZoom, setCurrentZoom] = useState<boolean>(false);
> > 
> >   const getFeatureZoomCenter = (geometry: Geometry) => {
> > ```
> 
> The new structure of TypeFeatureInfoEntry has the extent and the map has a zoomToExtent function that simplifies a lot the zoom operation. This code is too complicated and useless if we take into account the feature info capacities.
> 
> _[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 233 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NOkFmrY9LO9JG1tTBbR:-NOkFmrY9LO9JG1tTBbS:b-6ouyba) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L233)):_
> 
> > ```
> >           featureKey: keyCounter++,
> >           featureInfo: {},
> >           geometry: feature.getGeometry(),
> > ```
> 
> This section of code has changed to addapt to the new TypeFeatureInfoEntry structure.
> 
> _[`packages/geoview-details-panel/src/details-item.tsx` line 68 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NOkJX_qEdyD40okppH2:-NOkJX_qEdyD40okppH3:b-nhxwqj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-details-panel/src/details-item.tsx#L68)):_
> 
> > ```
> >       api.event.off(api.eventNames.GET_FEATURE_INFO.ALL_QUERIES_DONE, mapId);
> >       api.event.off(api.eventNames.GET_FEATURE_INFO.QUERY_LAYER, mapId);
> >     };
> > ```
> 
> Humm! Not sure it is necessary. I think these calls do nothing. We should do some tests to see.
> 
> _Code quote:_
> 
> ```
>     return () => {
>       api.event.off(api.eventNames.GET_FEATURE_INFO.ALL_QUERIES_DONE, mapId);
>       api.event.off(api.eventNames.GET_FEATURE_INFO.QUERY_LAYER, mapId);
>     };
> ```
> 
> _[`packages/geoview-footer-panel/src/details-item.tsx` line 69 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NOkJtVb4VyC5sRs4FWO:-NOkJtVb4VyC5sRs4FWP:b-nhxwqj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-footer-panel/src/details-item.tsx#L69)):_
> 
> > ```
> >       api.event.off(api.eventNames.GET_FEATURE_INFO.ALL_QUERIES_DONE, mapId);
> >       api.event.off(api.eventNames.GET_FEATURE_INFO.QUERY_LAYER, mapId);
> >     };
> > ```
> 
> Humm! Not sure it is necessary. I think these calls do nothing. We should do some tests to see.
> 
> _Code quote:_
> 
> ```
>     return () => {
>       api.event.off(api.eventNames.GET_FEATURE_INFO.ALL_QUERIES_DONE, mapId);
>       api.event.off(api.eventNames.GET_FEATURE_INFO.QUERY_LAYER, mapId);
>     };
> ```
> 
> _[`packages/geoview-footer-panel/src/details-item.tsx` line 72 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NOkJpk20PdvkQ4o6NKD:-NOkJpk20PdvkQ4o6NKE:bz7fmvq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-footer-panel/src/details-item.tsx#L72)):_
> 
> > Humm! Not sure it is necessary. I think these calls do nothing.
> 
For all the geometry related part, removed and using the rebased updating.

The "api.event.off ...", if you mean the event off, since it's from the original code, I believe it's a standard code logic, maybe it's not necessary. if you mean the map single click, that's using to get the click position and handler name, which to keep the clicking marker showing, sine the panel expend would resizing the map, and hide the marker. created a new bug issue, if we can fix this from map api level, we should not need this anymore

**Comment by dennisfu** [comment]
> When we click on the zoom, it closes the detail item. It should not.
> 
> > _[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-:-NOuiTJY2tFXnxILyJCE:b-idchom)_ status: 0 of 9 files reviewed, 6 unresolved discussions (waiting on @dennisfu and @ychoquet)

Done. prevented the parent clicking on zoom button clicking

**Comment by dennisfu** [comment]
@jolevesq rebased and pushed

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866)* status: 8 of 9 files reviewed, 10 unresolved discussions (waiting on @dennisfu and @ychoquet)

___
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 88 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NP2TIP80Kq1MAC0kPFI:-NP2TIP80Kq1MAC0kPFJ:bkmh86x) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-core/src/core/components/details/feature-info.tsx#L88)):*
> ```XML
> 
>   const featureId = `Feature Info ${feature.featureKey}`;
>   const featureGeoMetry = feature.geometry;
> ```

Typo GEoMetry should be Geometry
___
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 97 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NP2TOIt2F4atyFn8sL1:-NP2TOIt2F4atyFn8sL2:bhes4aa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-core/src/core/components/details/feature-info.tsx#L97)):*
> ```XML
>   const { zoom, center } = api.map(mapId).mapFeaturesConfig.map.viewSettings;
>   const projectionConfig = api.projection.projections[currentProjection];
>   // console.log(api.map(mapId).mapFeaturesConfig.map.viewSettings);
> ```

Remove dead code
___
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 130 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NP2TCWWE_MDECaFgAOp:-NP2TCWWE_MDECaFgAOq:bhes4aa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-core/src/core/components/details/feature-info.tsx#L130)):*
> ```XML
>     let zoomCenter = null;
>     if (featureGeoMetry !== undefined) {
>       // const geoviewLayers = api.map(mapId).layer.vector;
> ```

Remove dead code
___
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 149 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NP2U1b95Udsx-T89xPr:-NP2U1b95Udsx-T89xPs:bhes4aa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-core/src/core/components/details/feature-info.tsx#L149)):*
> ```XML
>       });
> 
>     // console.log(featureGeoMetry);
> ```

Remove dead code

**Review by dennisfu — COMMENTED** [review]
rebased and pushed

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-:-NP37YhhEEawJ-dUCXaH:bbr1l47)* status: 8 of 9 files reviewed, 10 unresolved discussions (waiting on @ychoquet)

**Comment by dennisfu** [comment]
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 101 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NOkEqLU99-yYkVdvOsJ:-NP3IBKC5zkXsVzhzNX3:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-core/src/core/components/details/feature-info.tsx#L101)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

The new structure of TypeFeatureInfoEntry has the extent and the map has a zoomToExtent function that simplifies a lot the zoom operation. This code is too complicated and useless if we take into account the feature info capacities.
</blockquote></details>

Done.

**Comment by dennisfu** [comment]
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 97 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NP2TOIt2F4atyFn8sL1:-NP3J7iw3Wv9hPJFl_sC:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-core/src/core/components/details/feature-info.tsx#L97)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove dead code
</blockquote></details>

Done.

**Comment by dennisfu** [comment]
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 130 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NP2TCWWE_MDECaFgAOp:-NP3JQjKDMIwIg-rv_Zi:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-core/src/core/components/details/feature-info.tsx#L130)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove dead code
</blockquote></details>

Done.

**Comment by dennisfu** [comment]
*[`packages/geoview-core/src/core/components/details/feature-info.tsx` line 149 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NP2U1b95Udsx-T89xPr:-NP3Jftu1Jaqx1uEDZF_:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-core/src/core/components/details/feature-info.tsx#L149)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove dead code
</blockquote></details>

Done.

**Comment by dennisfu** [comment]
*[`packages/geoview-footer-panel/src/details-item.tsx` line 69 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NOkJtVb4VyC5sRs4FWO:-NP3JjB35EgpvLQ2iXQH:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-footer-panel/src/details-item.tsx#L69)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Humm! Not sure it is necessary. I think these calls do nothing. We should do some tests to see.
</blockquote></details>

Done.

**Comment by dennisfu** [comment]
*[`packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts` line 18 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NOkDOU9BT1HYaedx5WF:-NP3JqBx82a5vFCV7oHr:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-core/src/api/events/payloads/get-feature-info-payload.ts#L18)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

The TypeFeatureInfoEntry has changed a lot in the PR https://github.com/Canadian-Geospatial-Platform/geoview/pull/914.
These changes affect considerably the code of this PR. I think it is preferable to merge PR 914 before this one and adapt it to the new TypeFeatureInfoEntry structure.
</blockquote></details>

Done.

**Comment by dennisfu** [comment]
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 233 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NOkFmrY9LO9JG1tTBbR:-NP3Jtkl3rm-MF3sEfFi:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L233)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

This section of code has changed to addapt to the new TypeFeatureInfoEntry structure.
</blockquote></details>

Done.

**Comment by dennisfu** [comment]
*[`packages/geoview-details-panel/src/details-item.tsx` line 68 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NOkJX_qEdyD40okppH2:-NP3Jx-AA15pRdksgbGl:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-details-panel/src/details-item.tsx#L68)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Humm! Not sure it is necessary. I think these calls do nothing. We should do some tests to see.
</blockquote></details>

Done.

**Review by ychoquet — COMMENTED** [review]
> Reviewed 3 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @jolevesq)

___
*[`packages/geoview-details-panel/src/details-item.tsx` line 68 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866#-NOkJX_qEdyD40okppH2:-NOuthGXCJNLBm6cZzb2:b-4d9svn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/b40a65a7fd6dcfc94d8cee7b59a290eff7138668/packages/geoview-details-panel/src/details-item.tsx#L68)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Humm! Not sure it is necessary. I think these calls do nothing. We should do some tests to see.
</blockquote></details>

I'll try to do some tests to confirm my tought.

**Review by ychoquet — APPROVED** [review]
> Reviewed 5 of 9 files at r4, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/866)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dennisfu)

**Pull request merged**
