### PR TITLE
527-First version of the getFeatureInfo

### PR DESCRIPTION
**Pull request by ychoquet**
This also complete the vector types at about 99%.

- - -
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/533)

### CODE REVIEW

**Review by ychoquet — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/533#-:-NCtxjBRB__MFsEzkzZw:bnfp4nl)* status: all files reviewed, 10 unresolved discussions (waiting on @github-code-scanning[bot] and @jolevesq)

___
*[`packages/geoview-core/public/geojson/metadata.json` line 2 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/533#-NCtgsJ55HTkn66512Ao:-NCuRIJw9y070GzMm744:bt2s489) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ecb51c1738d454d511eb9ff405de3e1194cd10d4/packages/geoview-core/public/geojson/metadata.json#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This copyrght is the same as the one provided by the basemap. We should have a check in the code to not duplicate attribution is already there. See layers.htmlk Geojson sample
</blockquote></details>

For sure we can code  a verification to avoid a duplicate attribution. However, if the attributiondiffers by only one character, it will be kept.
___
*[`packages/geoview-core/src/core/components/crosshair/crosshair.tsx` line 61 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/533#-NCtcMWN8k1uDuR9Wkvt:-NCuSJwe9LlHgXZ6XtkB:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ecb51c1738d454d511eb9ff405de3e1194cd10d4/packages/geoview-core/src/core/components/crosshair/crosshair.tsx#L61)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We had a bad comments, should be the crosshair component not the north arrow. Can you please adjust.
</blockquote></details>

Done.



_Code quote:_
```XML
the north arrow component
```
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 25 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/533#-NChs5mWCZJTtN6BHeF8-r1-25:-NCv-OljAB437qIPMmPM:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ecb51c1738d454d511eb9ff405de3e1194cd10d4/packages/geoview-core/src/core/utils/utilities.ts#L25)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Prototype-polluting assignment

This assignment may alter Object.prototype if a malicious '__proto__' string is injected from [library input](1).

[Show more details](https://github.com/Canadian-Geospatial-Platform/GeoView/security/code-scanning/38)
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 28 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/533#-NChs5mWCZJTtN6BHeF8-r1-28:-NCv-QNB1worVD2JpCxl:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ecb51c1738d454d511eb9ff405de3e1194cd10d4/packages/geoview-core/src/core/utils/utilities.ts#L28)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Prototype-polluting assignment

This assignment may alter Object.prototype if a malicious '__proto__' string is injected from [library input](1).

[Show more details](https://github.com/Canadian-Geospatial-Platform/GeoView/security/code-scanning/39)
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 32 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/533#-NChs5mWCZJTtN6BHeF8-r1-32:-NCv-Rg4ENVCsVgMkL87:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ecb51c1738d454d511eb9ff405de3e1194cd10d4/packages/geoview-core/src/core/utils/utilities.ts#L32)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Prototype-polluting assignment

This assignment may alter Object.prototype if a malicious '__proto__' string is injected from [library input](1).

[Show more details](https://github.com/Canadian-Geospatial-Platform/GeoView/security/code-scanning/40)
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 127 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/533#-NCtdCVM9MDPx7UszuGS:-NCv-mMv7cnmCy68FIl-:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ecb51c1738d454d511eb9ff405de3e1194cd10d4/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L127)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Type andf
</blockquote></details>

Done.



_Code quote:_
```XML
andf
```
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 484 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/533#-NCtfFU57TSm7GlwBJPj:-NCv874OEsfPe1Xky6Xo:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ecb51c1738d454d511eb9ff405de3e1194cd10d4/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L484)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add jsdoc for this function
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts` line 493 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/533#-NCtfMQs3SbCM_1lSu6Q:-NCv896X3OfE-hZtvSVJ:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ecb51c1738d454d511eb9ff405de3e1194cd10d4/packages/geoview-core/src/geo/layer/geoview-layers/vector/abstract-geoview-vector.ts#L493)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you add jsdoc for this function
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts` line 100 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/533#-NCtjXC_-yYY0lq2UBPo:-NCv8oCG8g28IhVONUmn:b-5edc9h) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ecb51c1738d454d511eb9ff405de3e1194cd10d4/packages/geoview-core/src/geo/layer/geoview-layers/vector/geojson.ts#L100)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

What happen if metadataAccessPath is define but no metadata.json file is provided?
</blockquote></details>

The metadataUrl is a full path to the metadata file. It can be something like ./geojson/metadata4floodDataset.json or http://domain-name/path/to/the/metadata.json. If the query returns an enpty json '{}', the the code throw an error with the message `Cant't read service metadata for layer ${this.layerId} of map ${this.mapId}.`
___
*[`packages/geoview-core/src/geo/renderer/esri-renderer.ts` line 35 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/533#-NCtki7k4dooi8tyH5v-:-NCvAMLD5XtCgWWvrnZ7:b-p9k5yf) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ecb51c1738d454d511eb9ff405de3e1194cd10d4/packages/geoview-core/src/geo/renderer/esri-renderer.ts#L35)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can this type be more standard because this is not only for ESRI it is [R, G, B, Alpha] format. Can be reuse by any other type.
</blockquote></details>

This type exists only for the esri-renderer.ts file. It is not exported. A global type exists for [R, G, B, Alpha] format and all the other variant used by Openlayers.

**Review by jolevesq — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/533)* status: all files reviewed, 3 unresolved discussions (waiting on @github-code-scanning[bot])

___
*[`packages/geoview-core/public/geojson/metadata.json` line 2 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/533#-NCtgsJ55HTkn66512Ao:-NCvCISW2vWmyjP-CZ-Z:b-yi8q9c) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ecb51c1738d454d511eb9ff405de3e1194cd10d4/packages/geoview-core/public/geojson/metadata.json#L2)):*
<details><summary><i>Previously, ychoquet wrote…</i></summary><blockquote>

For sure we can code  a verification to avoid a duplicate attribution. However, if the attributiondiffers by only one character, it will be kept.
</blockquote></details>

We create a new issue for this: https://github.com/Canadian-Geospatial-Platform/GeoView/issues/541

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/533)* status: all files reviewed, 3 unresolved discussions (waiting on @github-code-scanning[bot])

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/533)* status: all files reviewed, 3 unresolved discussions (waiting on @github-code-scanning[bot])

**Review by jolevesq — APPROVED** [review]
> Dismissed @github-code-scanning[bot] from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/533)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
