### PR TITLE
feat(add-panel-sample) Create a sample page to showcase adding panels

### LINKED ISSUE #111: Create a sample page to add panels
Re-add the add panels API calls in a sample page to showcase adding appbar panels and navbar buttons and panels

### PR DESCRIPTION
**Pull request by yass0016**
Closes #111

## Checklist

* [ ] Commit message follow the guidelines
* [ ] PR targets the correct release version
* [ ] Deploy has been done
* [ ] Check styling
* [ ] _Help files and documentation have been updated_
* [ ] ~Release notes have been updated~

## What's to look for styling
* Use camelCase for identifier names (variables and functions)
* Use PascalCase for type names
* Do not use "I" as a prefix for interface names
* Do not export types/functions unless you need to share it across multiple components
* All names start with a letter
* Always put spaces around operators ( = + - * / ), and after colon:
* Remove all trailing white spaces
* Look for bad indentation
* Carriage return are mandatory
  * Before comments
  * Before if condition
  * After if condition
  * Before properties
  * Before classes
  * Before functions

The use of Prettier Visual Studio Code extension let's you format automatically your code to remove most of the styling issues like white space and indentation.

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/113)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/113)* status: 3 of 7 files reviewed, 4 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[public/templates/add-panels.html, line 99 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/113#-MUJx6ksEWhRsDhju7lh:-MUJx6ksEWhRsDhju7li:b-85gvep) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/888c48ebd0b1372de0ab1e0a0ae2b7cde55a78a6/public/templates/add-panels.html#L99)):*
> ```HTML
>                 id="mapWM"
>                 class="llwp-map"
>                 data-leaflet="{ 'name': 'Web Mercator', 'projection': 3857, 'zoom': 4, 'center': [60,-100], 'language': 'en-CA',
> ```

The basemap doesn't show, I think the call for basemap had change since last time you use this config snippet
___
*[src/components/appbar/button.tsx, line 22 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/113#-MUJwc1c2sij_qQsTo1L:-MUJwc1dCIYwylJu4AGV:btdz2cn) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/888c48ebd0b1372de0ab1e0a0ae2b7cde55a78a6/src/components/appbar/button.tsx#L22)):*
> ```XML
>         },
>     },
>     icon: {
> ```

Is this style can be inside theme because it will be reuse?
___
*[src/components/navbar/button.tsx, line 24 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/113#-MUJwlka9SUb3LSlRNfv:-MUJwlka9SUb3LSlRNfw:b-cfdzc3) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/888c48ebd0b1372de0ab1e0a0ae2b7cde55a78a6/src/components/navbar/button.tsx#L24)):*
> ```XML
>         },
>     },
>     icon: {
> ```

Same for theme
___
*[src/components/panel/panel.tsx, line 124 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/113#-MUJwqY8Au-pIdZhUBrX:-MUJwqY8Au-pIdZhUBrY:b-y5q9o) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/888c48ebd0b1372de0ab1e0a0ae2b7cde55a78a6/src/components/panel/panel.tsx#L124)):*
> ```XML
>                 avatar={
>                     typeof panel.icon === 'string' ? (
>                         <HtmlToReact className={undefined} htmlContent={panel.icon} />
> ```

Why you set it as undefined?

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/113)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[src/components/appbar/button.tsx, line 22 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/113#-MUJwc1c2sij_qQsTo1L:-MUK2hIm8Exv8pI0IeqX:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/888c48ebd0b1372de0ab1e0a0ae2b7cde55a78a6/src/components/appbar/button.tsx#L22)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this style can be inside theme because it will be reuse?
</blockquote></details>

Done.
___
*[src/components/navbar/button.tsx, line 24 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/113#-MUJwlka9SUb3LSlRNfv:-MUK2izeA7dVSMgPiuIF:bb6un1j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/888c48ebd0b1372de0ab1e0a0ae2b7cde55a78a6/src/components/navbar/button.tsx#L24)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same for theme
</blockquote></details>

Done
___
*[src/components/panel/panel.tsx, line 124 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/113#-MUJwqY8Au-pIdZhUBrX:-MUK2ktc1zXotgxnTyPr:bb6un1j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/888c48ebd0b1372de0ab1e0a0ae2b7cde55a78a6/src/components/panel/panel.tsx#L124)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why you set it as undefined?
</blockquote></details>

Done

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/113)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @jolevesq and @melzeiny1980)

___
*[public/templates/add-panels.html, line 99 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/113#-MUJx6ksEWhRsDhju7lh:-MUK3sshEz1fn2BJyJzV:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/888c48ebd0b1372de0ab1e0a0ae2b7cde55a78a6/public/templates/add-panels.html#L99)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The basemap doesn't show, I think the call for basemap had change since last time you use this config snippet
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
:lgtm:

> Reviewed 1 of 7 files at r1, 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/113#-:-MUK9RS8Dadz83PwMdg5:bnfp4nl)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @jolevesq and @melzeiny1980)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/113)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @melzeiny1980)

**Pull request merged**
