### PR TITLE
fix(layers): fix layers data table  #closes1856

### LINKED ISSUE #1856: [BUG] Table in Layers Panel
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The show data table button on layer/layers panel is not working with latest refactor

### Expected Behavior

When we click on the data table button, records should be displayed. Only table that are part of the data table array should have this buttons in layers panel

### Steps To Reproduce

1. Go to https://canadian-geospatial-platform.github.io/geoview/public/raw-add-layers.html
2. Click Layers tab and select first layer
3. Click table icon in right panel, no table is shown

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Fix data table for each layers and display tableViewIcon when layer has features in allFeaturesDataArray.

Fixes #1856 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/raw-add-layers.html
# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 63 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877#-Nrq8bBhERtpfddTEahW:-Nrq8bBhERtpfddTEahX:bqqvohi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1db4004c3b0268907c84d0dc2b233afc90de59a4/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L63)):*
> ```XML
>   const selectedLayer = layersData.find((_layer) => _layer.layerPath === layerDetails?.layerPath);
> 
>   useEffect(() => {
> ```

This use effect is for what, please add comment

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 63 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877#-Nrq8bBhERtpfddTEahW:-NrqAk6CA92mS7lHYLSj:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/1db4004c3b0268907c84d0dc2b233afc90de59a4/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L63)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This use effect is for what, please add comment
</blockquote></details>

Done.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 33 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877#-NrqDYlY8zkhNkDFaeyZ:-NrqDYlY8zkhNkDFaey_:b-oqljxp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/379e19d00ce1d36e41836fcb72acf1061ce3c267/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L33)):*
> ```XML
> import { LayerIcon } from '../../common/layer-icon';
> import { logger } from '@/core/utils/logger';
> import { LAYER_STATUS, useDetailsStoreActions, useDetailsStoreAllFeaturesDataArray } from '@/app';
> ```

We cant import from '@/app' (because has everything). We need to import from the right folder.

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 33 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877#-NrqDYlY8zkhNkDFaeyZ:-NrqEdvx1zgpdPXyy8sl:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/379e19d00ce1d36e41836fcb72acf1061ce3c267/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L33)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

We cant import from '@/app' (because has everything). We need to import from the right folder.
</blockquote></details>

Done.

**Review by cphelefu — APPROVED** [review]
LGTM
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877#-:-NrqEyS31e47VOObsVV2:bb6ywmx)* status: 7 of 10 files reviewed, 3 unresolved discussions (waiting on @jolevesq and @kaminderpal)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @cphelefu)

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877)* status: all files reviewed, 2 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 68 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877#-NrqZ_4p-4k26CosD3SI:-NrqZ_4p-4k26CosD3SJ:b-egoa4e) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/32ce8c887a4c5400ef1d7816bcfd15f1c8d36cf6/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L68)):*
> ```XML
> 
>     // set the timer to fetch the features of layer when layer is selected.
>     let timer: NodeJS.Timeout;
> ```

Can you detail why you need to use a setTimeout with a comment (and possibly attach a TODO on it to think about coming back to it if you think it's a synchronization issue thing).
___
*[`packages/geoview-core/src/ui/select/select.tsx` line 20 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877#-NrqZumN8gJzt3k047sF:-NrqZumN8gJzt3k047sG:bikvksb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/32ce8c887a4c5400ef1d7816bcfd15f1c8d36cf6/packages/geoview-core/src/ui/select/select.tsx#L20)):*
> ```XML
>  * Custom MUI Select properties
>  */
> type TypeSelectProps = SelectProps & {
> ```

I have the rush update --full issue where it's telling me the props: 
label and labelId are missing.
Shouldn't they be added here?

I have this in my resolution attempt on my side:



_Code snippet:_
```XML
type TypeSelectProps = SelectProps & {
  labelId: string;
  menuItems: TypeMenuItemProps[];
  inputLabel: InputLabelProps;
  mapId?: string;
  fullWidth?: boolean;
  label?: JSX.Element;
  formControlProps?: FormControlProps;
};
```

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 2 of 4 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877)* status: all files reviewed, 3 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/ui/tabs/tabs.tsx` line 219 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877#-Nrq_uLD0bbd6Gs8_ezR:-Nrq_uLD0bbd6Gs8_ezS:bdr0gdu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/32ce8c887a4c5400ef1d7816bcfd15f1c8d36cf6/packages/geoview-core/src/ui/tabs/tabs.tsx#L219)):*
> ```XML
>                 menuItems={mobileTabsDropdownValues}
>                 value={value}
>                 onChange={(e) => updateTabPanel(e.target.value as number)}
> ```

You didn't have to change this line to:
`onChange={(e: SelectChangeEvent<unknown>) => updateTabPanel(e.target.value as number)}` to get through the rush update --full? I had to do this on my end

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877)* status: all files reviewed, 3 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/ui/select/select.tsx` line 20 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877#-NrqZumN8gJzt3k047sF:-Nrqa_TT57wzmSpFTLdR:b-oue1w9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/32ce8c887a4c5400ef1d7816bcfd15f1c8d36cf6/packages/geoview-core/src/ui/select/select.tsx#L20)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I have the rush update --full issue where it's telling me the props: 
label and labelId are missing.
Shouldn't they be added here?

I have this in my resolution attempt on my side:
</blockquote></details>

sorry, maybe that's more

`label?: string;`

actually, when I look at more code

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877)* status: all files reviewed, 2 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/ui/select/select.tsx` line 20 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877#-NrqZumN8gJzt3k047sF:-Nrqbz5_11l2BrYD4rJl:b4edsqd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/32ce8c887a4c5400ef1d7816bcfd15f1c8d36cf6/packages/geoview-core/src/ui/select/select.tsx#L20)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

sorry, maybe that's more

`label?: string;`

actually, when I look at more code
</blockquote></details>

Nevermind, label and labelId are in SelectProps and it's conflicting...

Ignore this comment please

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877)* status: 7 of 10 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 68 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877#-NrqZ_4p-4k26CosD3SI:-NrsCfY51QCMvJsGGQCV:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/32ce8c887a4c5400ef1d7816bcfd15f1c8d36cf6/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L68)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Can you detail why you need to use a setTimeout with a comment (and possibly attach a TODO on it to think about coming back to it if you think it's a synchronization issue thing).
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1877)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan)

**Pull request merged**
