### PR TITLE
feat(layer-panel): reorder layers ui

### LINKED ISSUE #677: Legend reorder layer item UI

### PR DESCRIPTION
**Pull request by dayc-mapdev**
Closes #677

- - -
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/752)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/752)* status: all files reviewed, 2 unresolved discussions (waiting on @dayc-mapdev)

___
*[`packages/geoview-core/src/ui/list/list-item.tsx` line 19 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/752#-NJkyTzSCOBFLGyjLEM7:-NJkyTzSCOBFLGyjLEM8:bll84gi) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0a62fbc33e63127a75cc8931d9ca05a783dd0ac7/packages/geoview-core/src/ui/list/list-item.tsx#L19)):*
> ```XML
>  * @returns {JSX.Element} the created List Item element
>  */
> export function ListItem(props: TypeListItemProps): JSX.Element {
> ```

Can you change the type in function description
___
*[`packages/geoview-layers-panel/src/reorder-layers-list.tsx` line 18 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/752#-NJkytJa6fliui8OhM1J:-NJkytJa6fliui8OhM1K:buztwz1) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0a62fbc33e63127a75cc8931d9ca05a783dd0ac7/packages/geoview-layers-panel/src/reorder-layers-list.tsx#L18)):*
> ```XML
>  * A react component that displays the reorderable layers list
>  *
>  * @returns {JSX.Element} A React JSX Element with the reor panel
> ```

Typo reor

**Review by dayc-mapdev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/752)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/ui/list/list-item.tsx` line 19 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/752#-NJkyTzSCOBFLGyjLEM7:-NJl-vUn2Y4DrUQllrKQ:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0a62fbc33e63127a75cc8931d9ca05a783dd0ac7/packages/geoview-core/src/ui/list/list-item.tsx#L19)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you change the type in function description
</blockquote></details>

Done.

**Review by dayc-mapdev — COMMENTED** [review]
Disabling scroll while drag is a bigger issue, I will create a separate issue for it

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/752#-:-NJl9SYy1Ix9wv0KUZqM:bt8gfpq)* status: 6 of 8 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-layers-panel/src/reorder-layers-list.tsx` line 91 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/752#-NJlJchh9J5sktz91aA9:-NJlJchi4FFQqrlXZmhk:b-74c985) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0536ca3e1520885e9c67ba080883d5da3d5dcf11/packages/geoview-layers-panel/src/reorder-layers-list.tsx#L91)):*
> ```XML
>                       <ListItemButton>
>                         <ListItemIcon>
>                           <HandleIcon sx={sxClasses.handleIcon} />
> ```

The whole ListItem is draggable. Focus on the IconButton didn't allow keyboard dragging so it was removed. See here for shortcuts https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/sensors/keyboard.md

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/752)* status: all files reviewed, 1 unresolved discussion (waiting on @dayc-mapdev)

___
*[`packages/geoview-layers-panel/src/reorder-layers-list.tsx` line 91 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/752#-NJlJchh9J5sktz91aA9:-NJpKyI147a53fH5X_qb:b-ucfko4) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/0536ca3e1520885e9c67ba080883d5da3d5dcf11/packages/geoview-layers-panel/src/reorder-layers-list.tsx#L91)):*
<details><summary><i>Previously, dayc-mapdev (Chris Day) wrote…</i></summary><blockquote>

The whole ListItem is draggable. Focus on the IconButton didn't allow keyboard dragging so it was removed. See here for shortcuts https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/sensors/keyboard.md
</blockquote></details>

Thanks

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/752)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @dayc-mapdev)

**Pull request merged**
