### PR TITLE
refactor export modal

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Refactor export modal and fix `cancel` and `export` button issue when modal opened second time.

Fixes # (904)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

# Checklist:

- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/947)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
There is a bug... when we access the modal with the keyboard, focus is not set to the modal element and we cant close it, even with the mouse

> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/947#-:-NQQ02q79NIP2WST068z:b-winu6)* status: 5 of 6 files reviewed, all discussions resolved

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/947)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/export-modal/export-modal.tsx` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/947#-NQQ0zGSAv4srj6YXOkq:-NQQ0zGSAv4srj6YXOkr:bi0tklx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/529d1c4969582b383bd30bcc22a91517a7614ef0/packages/geoview-core/src/core/components/export-modal/export-modal.tsx#L1)):*
> ```XML
> import { MouseEventHandler, useContext } from 'react';
> ```

We should name the folder export, not export modal. The component is export and other pieces will be added later.

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/947)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/export-modal/export-modal.tsx` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/947#-NQQ0zGSAv4srj6YXOkq:-NQVY_Mh5Vc-nnIrg7OJ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/529d1c4969582b383bd30bcc22a91517a7614ef0/packages/geoview-core/src/core/components/export-modal/export-modal.tsx#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should name the folder export, not export modal. The component is export and other pieces will be added later.
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/947)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Pull request merged**
