### PR TITLE
add legend layer images and fix details tab continous loading

### LINKED ISSUE #2304: [BUG] Appbar panel iare cut-off
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Appbar panels are cut-off.
http://localhost:8080/demos-navigator.html?config=./configs/navigator/07-basic-appbar.json

image

### Expected Behavior

The Appbar panels should have the same length as Appbar itself.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### LINKED ISSUE #2313: [BUG] In Default configuration - Details tab not showing guide first (shows un-ending skeleton)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In Default configurations - details tab is showing an un-ending animation instead of the guide tab.

image

Map 4
image

### Expected Behavior

When clicking details tab (in default configuration it should start with guide).

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### LINKED ISSUE #2339: [UI] Bigger Legend Image
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On the footer legend tab, image for legend item is too small

image

### Expected Behavior

We should have a way to see bigger legend image, here the options

- Open image in lightbox when click on
- Larger columns in legend tab

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

This PR fixes the following bugs

Fixes #2339 
Fixes #2313 
Fixes #2304 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://cphelefu.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2372)

### CODE REVIEW

**Review by kaminderpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2372)* status: 0 of 9 files reviewed, 3 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/lightbox/lightbox.tsx` line 36 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2372#-O25ETcJ1Y8qAe7hZmqq:-O25ETcJ1Y8qAe7hZmqr:b-c0gdj9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/75adedcd26f4b39601be0c12ad0933674be7ba67/packages/geoview-core/src/core/components/lightbox/lightbox.tsx#L36)):*
> ```XML
>   const { imgSrc, alt = '' } = props;
>   const [isOpen, setOpen] = useState(false);
>   const handleOpen = () => setOpen(true);
> ```


___
*[`packages/geoview-core/src/core/components/lightbox/lightbox.tsx` line 37 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2372#-O25EYkl0-w5Rl_Pc8sK:-O25EYkl0-w5Rl_Pc8sL:b-g0uk5r) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/75adedcd26f4b39601be0c12ad0933674be7ba67/packages/geoview-core/src/core/components/lightbox/lightbox.tsx#L37)):*
> ```XML
>   const [isOpen, setOpen] = useState(false);
>   const handleOpen = () => setOpen(true);
>   const handleClose = () => setOpen(false);
> ```


___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/app-state.ts` line 78 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2372#-O25ErW00DeNC6kBy1jD:-O25ErW00DeNC6kBy1jE:b-ki312w) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/75adedcd26f4b39601be0c12ad0933674be7ba67/packages/geoview-core/src/core/stores/store-interface-and-intial-values/app-state.ts#L78)):*
> ```XML
>       const lang = VALID_DISPLAY_LANGUAGE.includes(geoviewConfig.displayLanguage as TypeDisplayLanguage)
>         ? geoviewConfig.displayLanguage
>         : 'en';
> ```

Not sure if we have const for language or not, if not we should create const in `constant.ts` and use like LANGUAGE.EN

**Review by kaminderpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2372)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/ui/panel/panel.tsx` line 123 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2372#-O25ONf-7t0aQgLwKl5o:-O25ONf-7t0aQgLwKl5p:b-e0pe8r) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/75adedcd26f4b39601be0c12ad0933674be7ba67/packages/geoview-core/src/ui/panel/panel.tsx#L123)):*
> ```XML
>       panelContainerRef.current.style.height = `calc(100%  - ${mapInfoHeight}px)`;
>     }
>   }, [mapInfoExpanded, mapSize, open]);
> ```

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/app-state.ts` line 78 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2372#-O25ErW00DeNC6kBy1jD:-O25anBT6ibGI982bek4:bdevh8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/75adedcd26f4b39601be0c12ad0933674be7ba67/packages/geoview-core/src/core/stores/store-interface-and-intial-values/app-state.ts#L78)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

Not sure if we have const for language or not, if not we should create const in `constant.ts` and use like LANGUAGE.EN
</blockquote></details>

Not sure if this is a code idea.
But if we adopt it; it will have to be implemented in another PR - because we have 30 instances in the code where we use 'en'.

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2372)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @jolevesq and @kaminderpal)

___
*[`packages/geoview-core/src/core/components/lightbox/lightbox.tsx` line 36 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2372#-O25ETcJ1Y8qAe7hZmqq:-O25aiCo4SSi8hvXnpRf:b4kcyj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/75adedcd26f4b39601be0c12ad0933674be7ba67/packages/geoview-core/src/core/components/lightbox/lightbox.tsx#L36)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>


</blockquote></details>

Done. Removed code, code is unused.
___
*[`packages/geoview-core/src/ui/panel/panel.tsx` line 123 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2372#-O25ONf-7t0aQgLwKl5o:-O25b9x_ADQzoxeguaZc:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/75adedcd26f4b39601be0c12ad0933674be7ba67/packages/geoview-core/src/ui/panel/panel.tsx#L123)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>


</blockquote></details>

Done.

**Review by kaminderpal — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2372#-:-O25d3P-11qpAulN2hBE:bnfp4nl)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
