### PR TITLE
refactor(rendering): Update the startup rendering

### PR DESCRIPTION
**Pull request by yass0016**
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/32)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/32)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @yass0016)

___
*[public/index.html, line 54 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/32#-MRKr49a0VQKZp5uVcRU:-MRKr49a0VQKZp5uVcRV:bdop0zx) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fc07df98e844695dfd4b703ed7e914c76aa67246/public/index.html#L54)):*
> ```HTML
>             ></div>
>             <p>
>                 Cette carte est un exemple due carte créée à partir de Leaflet et React. La projection LCC est utilisée et l'interface est
> ```

Mofidy due by d'une
___
*[src/app.tsx, line 12 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/32#-MRKrpz0DRyk0xX2SFyk:-MRKrpz0DRyk0xX2SFyl:b6nrl1v) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fc07df98e844695dfd4b703ed7e914c76aa67246/src/app.tsx#L12)):*
> ```XML
> import '../public/css/style.css';
> 
> import AppStart from './appstart';
> ```

Rename appstart.tsx to app-start.tsx

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/32)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[public/index.html, line 54 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/32#-MRKr49a0VQKZp5uVcRU:-MRKz3lb84bCndmEglao:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fc07df98e844695dfd4b703ed7e914c76aa67246/public/index.html#L54)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Mofidy due by d'une
</blockquote></details>

Done.
___
*[src/app.tsx, line 12 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/32#-MRKrpz0DRyk0xX2SFyk:-MRKwt8XCAmqbb1qIQSo:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/fc07df98e844695dfd4b703ed7e914c76aa67246/src/app.tsx#L12)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Rename appstart.tsx to app-start.tsx
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 6 files at r1, 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/32#-:-MRL1pa36IUKXVipDRi3:bg7igkv)* status: 7 of 8 files reviewed, all discussions resolved

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/32)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
