### PR TITLE
fix(layers): fix default footertabid  closes2299

### LINKED ISSUE #2299: [BUG] Layers Tab First in List
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When layer tab is first in list it is not selected by default and the first click does not work. Only second click open the tab and default is on add instead of view even if there is layers in the panel

### Expected Behavior

By default the tab Layers should be selected and open on view, not add

### Steps To Reproduce

1.https://canadian-geospatial-platform.github.io/geoview/public/sandbox.html
2. set this config
 'footerBar': {
    'tabs': {
      'core': ['layers', 'details', 'data-table']
    }
  },
3. Create the map and click on layers

### Anything else?

_No response_

### LINKED ISSUE #2301: [BUG] <Footerbar when no legend exist>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When no legend exist in config file, first component is not selected like layers, it is automatically closed and when clicked on layers not working properly.

### Expected Behavior

_No response_

### Steps To Reproduce

1. https://canadian-geospatial-platform.github.io/geoview/public/sandbox.html
2.  Set this config
'footerBar': {
    'tabs': {
      'core': ['layers', 'details', 'data-table']
    }
  },
'appBar': {
    'tabs': {
      'core': ['export']
    }
  },
3. Create then export

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
1) Fix default footer tab id when no legend is present in config file.
2) Selection of `View` as default layers toolbar when no legend exist.

Fixes #2299 
Fixes #2301 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/sandbox.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2309)

### CODE REVIEW

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/layers/left-panel/left-panel.tsx` line 41 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2309#-O0Jk34r93RUt2mt-1Qp:-O0Jk34s6zR4qmADZ8f9:b1877qy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a26ca7532805e7b5c701ad2aadf6320531680cd5/packages/geoview-core/src/core/components/layers/left-panel/left-panel.tsx#L41)):*
> ```XML
> 
>   useEffect(() => {
>     if (displayState !== 'add' && !legendLayers.length && mapConfig?.footerBar?.tabs.core.includes('legend')) {
> ```

Not sure why we need this change in this file. Whether legend is added or not it should not affect layers tab or this functionality. Is there a reason for this?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2309)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @cphelefu and @kaminderpal)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 136 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2309#-O0Jlmw10AAOkaNdAwAI:-O0Jlmw10AAOkaNdAwAJ:b-vy2ari) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e329d37e76cd23ddd6e214406a8cf468318d6f54/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L136)):*
> ```XML
>   const { getRootProps, getInputProps, isDragActive } = useDropzone({ onDrop });
> 
>   const dropAreaSx = {
> ```

Where is this style now?

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2309)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/left-panel.tsx` line 41 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2309#-O0Jk34r93RUt2mt-1Qp:-O0JmEeh5Ae423mGJ5tA:b-pj63o6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a26ca7532805e7b5c701ad2aadf6320531680cd5/packages/geoview-core/src/core/components/layers/left-panel/left-panel.tsx#L41)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Not sure why we need this change in this file. Whether legend is added or not it should not affect layers tab or this functionality. Is there a reason for this?
</blockquote></details>

We have 2 cases now
1) when no layers are present on the map, then legendLayers will be empty.
2) when there are layers on the map, but legend doesnt exist in mapConfig file like below



_Code snippet:_
```XML
'footerBar': {
                'tabs': {
                  'core': ['layers', 'details', 'data-table']
                }
              },
```
___
*[`packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx` line 136 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2309#-O0Jlmw10AAOkaNdAwAI:-O0Jmk-N4DwPaZmWD_i3:banex1q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e329d37e76cd23ddd6e214406a8cf468318d6f54/packages/geoview-core/src/core/components/layers/left-panel/add-new-layer/add-new-layer.tsx#L136)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Where is this style now?
</blockquote></details>

it was commented code, so i have remove it.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2309)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @cphelefu)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/left-panel.tsx` line 41 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2309#-O0Jk34r93RUt2mt-1Qp:-O0JrVvG3KBVSJFvr2o9:b2v3zza) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a26ca7532805e7b5c701ad2aadf6320531680cd5/packages/geoview-core/src/core/components/layers/left-panel/left-panel.tsx#L41)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

We have 2 cases now
1) when no layers are present on the map, then legendLayers will be empty.
2) when there are layers on the map, but legend doesnt exist in mapConfig file like below
</blockquote></details>

CAn you add a comment to explain this if

**Review by cphelefu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2309#-:-O0JrnWo2xqhX-Wh-2Vt:bnfp4nl)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2309)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/left-panel.tsx` line 41 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2309#-O0Jk34r93RUt2mt-1Qp:-O0JspJBBhIlTwXNx2Dq:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a26ca7532805e7b5c701ad2aadf6320531680cd5/packages/geoview-core/src/core/components/layers/left-panel/left-panel.tsx#L41)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

CAn you add a comment to explain this if
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2309)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @cphelefu)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2309)* status: all files reviewed, 1 unresolved discussion (waiting on @cphelefu)

**Pull request merged**
