### PR TITLE
fix(footerBar): fix tab panels rendering  #closes1782

### LINKED ISSUE #1782: [BUG] Components used in the FooterTabs have their states desynching
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I was playing with the FooterBars components, I realized that whenever we set props to components displayed in the Footer, those props aren't updated. Then, I realized there was an unsync of the states in the FooterBars and after futher discussion with Kaminder, there might be an issue going down to the Tabs ui component as well.

I've created a branch to kick start troubleshooting of this issue. The branch uses a `color` state on the DetailsPanel which is basically changed from red to green (changing the details text) and it isn't turning green ever.

ALSO

When adding tabs via api or config, the store should show all the tabs. There seems to be a desynch on that also.

My branch: https://github.com/Alex-NRCan/geoview/tree/bug-footer-tabs-double-comps

### Expected Behavior

When setting props to a component, that component should re-render with the correct props.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Fix the tab panel issue when prop passed to component and component is not ren

Fixes #1782 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/package-time-slider.html
https://kaminderpal.github.io/geoview/package-footer-panel-geochart.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1800)

### CODE REVIEW

**Review by Alex-NRCan — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1800#-:-NqZ6sDY5zyLH1fMj6h4:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 86 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1800#-NqZ6VKX9Fs28ULum5Yr:-NqZ6VKX9Fs28ULum5Ys:blykhtj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3c7873d262142ae7db762e0a5a117283151defbb/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L86)):*
> ```XML
> 
>   const footerBarTabKeys = useMemo(() => {
>     return (footerBarTabsConfig?.tabs?.core ?? []).reduce((acc, curr) => {
> ```

Can you re-add the logger.logTranceUseMemo() in here?
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 108 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1800#-NqZ6QX57Z39UHdJ0BHs:-NqZ6QX57Z39UHdJ0BHt:blykhtj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3c7873d262142ae7db762e0a5a117283151defbb/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L108)):*
> ```XML
>   // Map the panels with footer bar tab keys.
>   const footerBarTabs = useMemo(() => {
>     const allTabs = { ...tabsList, ...tabs };
> ```

Can you re-add the logger.logTranceUseMemo() in here?

**Review by Alex-NRCan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1800)* status: all files reviewed, 3 unresolved discussions (waiting on @kaminderpal)

___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 177 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1800#-NqZ7AfLDKrqZurXs6wd:-NqZ7AfLDKrqZurXs6we:bbixgt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3c7873d262142ae7db762e0a5a117283151defbb/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L177)):*
> ```XML
>   const removeTab = useCallback((payload: FooterBarPayload) => {
>     // remove the tab from the list
>     setTabsList((prevState) => {
> ```

oh and can you add logUseCallback here

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1800)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 86 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1800#-NqZ6VKX9Fs28ULum5Yr:-NqZDNWh6kDQDPp4cXhN:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6967d6eec59fadb084e9860c917fa5f23551a91d/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L86)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Can you re-add the logger.logTranceUseMemo() in here?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 108 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1800#-NqZ6QX57Z39UHdJ0BHs:-NqZDNw58Ij2qrcLjm-u:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6967d6eec59fadb084e9860c917fa5f23551a91d/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L108)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Can you re-add the logger.logTranceUseMemo() in here?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 177 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1800#-NqZ7AfLDKrqZurXs6wd:-NqZDOF6AuTj3ekMML2i:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6967d6eec59fadb084e9860c917fa5f23551a91d/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L177)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

oh and can you add logUseCallback here
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1800)* status: all files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan)

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1800)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kaminderpal)

**Pull request merged**
