### PR TITLE
#62 button panels

### PR DESCRIPTION
**Pull request by yass0016**
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65)* status: 3 of 25 files reviewed, 8 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[src/api/event.ts, line 27 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT10Xuf1L_xlANL8fZb:-MT10Xuf1L_xlANL8fZc:b-cupiix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/api/event.ts#L27)):*
> ```XML
>      * Event triggered when a new appbar panel has been created
>      */
>     EVENT_APPBAR_PANEL_CREATE: 'appbar_panel/create',
> ```

Should we split event in multiple class (map, layer, panel, ...) Do we do it here or we have an issue for this?
___
*[src/common/ui/button-panel.ts, line 146 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT11aHZ5dBgMqMQnzJx:-MT11aHZ5dBgMqMQnzJy:b5k7dz9) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/common/ui/button-panel.ts#L146)):*
> ```XML
>      * @param {string} groupName group name to add the button panel to
>      */
>     createNavbarButtonPanel = (buttonProps: ButtonProps, panelProps: PanelProps, groupName: string): ButtonPanelType | null => {
> ```

This function is almost the same as the one above. Can we regroup all the common code into one function to reduce duplication
___
*[src/common/ui/button-panel.ts, line 201 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT11rYO5WvDUWtZjI8C:-MT11rYO5WvDUWtZjI8D:bi26rxa) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/common/ui/button-panel.ts#L201)):*
> ```XML
> 
>             // if group does not exist then create it
>             if (!this.navBarButtons[groupName]) {
> ```

Part of the code is the same for all the functions
___
*[src/common/ui/panel.ts, line 78 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT11zzYCLiYvBs6WCoO:-MT11zzYCLiYvBs6WCoP:b-k2e633) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/common/ui/panel.ts#L78)):*
> ```XML
>      */
>     open = (): void => {
>         api.event.emit(EVENT_NAMES.EVENT_PANEL_OPEN, api.selectedMapInstance.id, {
> ```

Look at issue #44. Do we solve this here or will do it on his own PR
___
*[src/components/appbar/app-bar.tsx, line 208 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT137k-Ab_TOwh6MSE5:-MT137k0C0FSm3xC5ECe:b-dj3p7d) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/components/appbar/app-bar.tsx#L208)):*
> ```XML
>                                     );
>                                 })}
>                                 {index > 1 && (
> ```

Divider not added
___
*[src/components/navbar/nav-bar.tsx, line 158 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT14FDZ1AM0LUj_gaVZ:-MT14FDZ1AM0LUj_gaV_:b-jpwbxu) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/components/navbar/nav-bar.tsx#L158)):*
> ```XML
>                                         key={buttonPanel.id}
>                                         tooltip={buttonPanel.tooltip}
>                                         icon={buttonPanel.icon}
> ```

Why is it call buttonPanel f there is no panel?
___
*[src/components/panel/default-panels.tsx, line 1 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT14WMS-TJIwhVPl94T:-MT14WMS-TJIwhVPl94U:bp4bgmn) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/components/panel/default-panels.tsx#L1)):*
> ```XML
> import { Typography } from '@material-ui/core';
> ```

Do we still need this class?Was a placeholder to show a layers panel.
___
*[src/components/panel/panel.tsx, line 47 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT14kcL8lquJdJZeDG1:-MT14kcL8lquJdJZeDG2:b-9oqr6y) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/components/panel/panel.tsx#L47)):*
> ```XML
> 
> /**
>  *
> ```

Can you put a description

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65)* status: 3 of 25 files reviewed, 8 unresolved discussions (waiting on @jolevesq and @melzeiny1980)

___
*[src/api/event.ts, line 27 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT10Xuf1L_xlANL8fZb:-MT154Z272kF0vCafz_x:b-fdw5ab) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/api/event.ts#L27)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we split event in multiple class (map, layer, panel, ...) Do we do it here or we have an issue for this?
</blockquote></details>

this is just for the name of the events that can be triggered, do we need to split them? I think it's ok for them to be in the same const
___
*[src/common/ui/button-panel.ts, line 146 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT11aHZ5dBgMqMQnzJx:-MT1AAJ92QOk-Kgzxl7N:b-xuq38p) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/common/ui/button-panel.ts#L146)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This function is almost the same as the one above. Can we regroup all the common code into one function to reduce duplication
</blockquote></details>

there isn't a lot of duplications, I would keep it as is for now
___
*[src/common/ui/button-panel.ts, line 201 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT11rYO5WvDUWtZjI8C:-MT1AjsRCwZc61bTXl5W:b7ahhcl) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/common/ui/button-panel.ts#L201)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Part of the code is the same for all the functions
</blockquote></details>

actually only the creation of the id and the gorup name is repeated, its like 3 lines of code, I don't think its worth putting it on it's own function
___
*[src/common/ui/panel.ts, line 78 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT11zzYCLiYvBs6WCoO:-MT17-c9-1Yn_pH1sUkD:b-whantf) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/common/ui/panel.ts#L78)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Look at issue #44. Do we solve this here or will do it on his own PR
</blockquote></details>

let's do it on it's own issue after #61 
___
*[src/components/appbar/app-bar.tsx, line 208 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT137k-Ab_TOwh6MSE5:-MT18nMgENUovcx7l-EK:b-191nxu) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/components/appbar/app-bar.tsx#L208)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Divider not added
</blockquote></details>

divider will show up when we have multiple groups, currently the buttons are added to the same group as the layers button, do you want it to show between each button instead of groups?
___
*[src/components/navbar/nav-bar.tsx, line 158 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT14FDZ1AM0LUj_gaVZ:-MT19PPZA8Amn2emhsxf:b7crls7) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/components/navbar/nav-bar.tsx#L158)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why is it call buttonPanel f there is no panel?
</blockquote></details>

button-panel.ts class combines either a button, or a button panel, thats why if you notice I am doing instantof button
___
*[src/components/panel/default-panels.tsx, line 1 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT14WMS-TJIwhVPl94T:-MT19ghX6ZLgtbB-7Wur:b-voyevx) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/components/panel/default-panels.tsx#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we still need this class?Was a placeholder to show a layers panel.
</blockquote></details>

yes, I am calling a function to add default buttons from button-panel
___
*[src/components/panel/panel.tsx, line 47 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT14kcL8lquJdJZeDG1:-MT1A1P_3H62hF28IEQI:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/components/panel/panel.tsx#L47)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put a description
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65)* status: 2 of 24 files reviewed, 3 unresolved discussions (waiting on @jolevesq, @melzeiny1980, and @yass0016)

___
*[src/common/ui/button-panel.ts, line 146 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT11aHZ5dBgMqMQnzJx:-MT1Cg5f0_fExjbLYdYS:b-xvh457) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/common/ui/button-panel.ts#L146)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

there isn't a lot of duplications, I would keep it as is for now
</blockquote></details>


Can you just add a TODO: look at code duplication. Will cover that later.
___
*[src/components/appbar/app-bar.tsx, line 208 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT137k-Ab_TOwh6MSE5:-MT1C73F4sRwGLUiHhA3:b-hloooq) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/components/appbar/app-bar.tsx#L208)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

divider will show up when we have multiple groups, currently the buttons are added to the same group as the layers button, do you want it to show between each button instead of groups?
</blockquote></details>

Yes, just to showcase it can be done

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65)* status: 2 of 24 files reviewed, 3 unresolved discussions (waiting on @jolevesq and @melzeiny1980)

___
*[src/common/ui/button-panel.ts, line 146 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT11aHZ5dBgMqMQnzJx:-MT1D81TABtZrCwFlHQT:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/common/ui/button-panel.ts#L146)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you just add a TODO: look at code duplication. Will cover that later.
</blockquote></details>

Done.
___
*[src/components/appbar/app-bar.tsx, line 208 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-MT137k-Ab_TOwh6MSE5:-MT1DUGH3hPLgR9cgpZO:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/1c4a211cd89ef5c60f1b44906b11b6126b839726/src/components/appbar/app-bar.tsx#L208)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Yes, just to showcase it can be done
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
:lgtm:

> Reviewed 21 of 25 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65#-:-MT1E_P48floG4nlwapP:bnfp4nl)* status: 22 of 24 files reviewed, all discussions resolved (waiting on @jolevesq and @melzeiny1980)

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/65)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @melzeiny1980)

**Pull request merged**
