### PR TITLE
183 geopackage support

### PR DESCRIPTION
**Pull request by DamonU2**
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/824)

### CODE REVIEW

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/824)* status: all files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts` line 45 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/824#-NMAMX3U7rIRqBu16kTX:-NMAMX3U7rIRqBu16kTY:bplz1mv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a051d7fb7fcf32969e33ab1fdd642a801567ba39/packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts#L45)):*
> ```XML
> 
> /** *****************************************************************************************************************************
>  * type guard function that redefines a TypeGeoviewLayerConfig as a TypeOgcFeatureLayerConfig if the geoviewLayerType attribute of
> ```

I think you should revise all the comments in this file. It appears that you use the OgcFeature file to create this GeoPackagefile. Most of the time, the code part is OK since if it was not the case the layer would not behave as expected. However, the comments  are not cover by the execution of the code. I often fall in the same trap and find wrong comments when I get back in the code later. 



_Code quote:_
```XML
TypeOgcFeatureLayerConfig 
```
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts` line 168 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/824#-NMAOqzx0tneNLbsXBe0:-NMAOqzx0tneNLbsXBe1:bsmxk5l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a051d7fb7fcf32969e33ab1fdd642a801567ba39/packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts#L168)):*
> ```XML
>       }
> 
>       // Note that the code assumes ogc-feature collections does not contains metadata layer group. If you need layer group,
> ```

OGC comment.



_Code quote:_
```XML
feature 
```
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts` line 176 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/824#-NMAPQKIED729iSyJ7eF:-NMAPQKIED729iSyJ7eG:buyh50h) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a051d7fb7fcf32969e33ab1fdd642a801567ba39/packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts#L176)):*
> ```XML
>           this.layerLoadError.push({
>             layer: Layer.getLayerPath(layerEntryConfig),
>             consoleMessage: `OGC feature layer not found (mapId:  ${this.mapId}, layerPath: ${Layer.getLayerPath(layerEntryConfig)})`,
> ```

OGC message.



_Code quote:_
```XML
consoleMessage: `OGC feature layer not found (mapId:  ${this.mapId}, layerPath: ${Layer.getLayerPath(layerEntryConfig)})`,
```

**Comment by DamonU2** [comment]
> > Reviewed 14 of 14 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/824)_ status: all files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @jolevesq)
> 
> _[`packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts` line 45 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/824#-NMAMX3U7rIRqBu16kTX:-NMAMX3U7rIRqBu16kTY:bplz1mv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a051d7fb7fcf32969e33ab1fdd642a801567ba39/packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts#L45)):_
> 
> > ```
> > /** *****************************************************************************************************************************
> >  * type guard function that redefines a TypeGeoviewLayerConfig as a TypeOgcFeatureLayerConfig if the geoviewLayerType attribute of
> > ```
> 
> I think you should revise all the comments in this file. It appears that you use the OgcFeature file to create this GeoPackagefile. Most of the time, the code part is OK since if it was not the case the layer would not behave as expected. However, the comments are not cover by the execution of the code. I often fall in the same trap and find wrong comments when I get back in the code later.
> 
> _Code quote:_
> 
> ```
> TypeOgcFeatureLayerConfig 
> ```
> 
> _[`packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts` line 168 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/824#-NMAOqzx0tneNLbsXBe0:-NMAOqzx0tneNLbsXBe1:bsmxk5l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a051d7fb7fcf32969e33ab1fdd642a801567ba39/packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts#L168)):_
> 
> > ```
> >       }
> > 
> >       // Note that the code assumes ogc-feature collections does not contains metadata layer group. If you need layer group,
> > ```
> 
> OGC comment.
> 
> _Code quote:_
> 
> ```
> feature 
> ```
> 
> _[`packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts` line 176 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/824#-NMAPQKIED729iSyJ7eF:-NMAPQKIED729iSyJ7eG:buyh50h) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/a051d7fb7fcf32969e33ab1fdd642a801567ba39/packages/geoview-core/src/geo/layer/geoview-layers/vector/geopackage.ts#L176)):_
> 
> > ```
> >           this.layerLoadError.push({
> >             layer: Layer.getLayerPath(layerEntryConfig),
> >             consoleMessage: `OGC feature layer not found (mapId:  ${this.mapId}, layerPath: ${Layer.getLayerPath(layerEntryConfig)})`,
> > ```
> 
> OGC message.
> 
> _Code quote:_
> 
> ```
> consoleMessage: `OGC feature layer not found (mapId:  ${this.mapId}, layerPath: ${Layer.getLayerPath(layerEntryConfig)})`,
> ```

Done!

**Review by jolevesq — COMMENTED** [review]
> Reviewed 14 of 14 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/824)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @ychoquet)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/824#-:-NMFeBCNDbR05kfIgD3N:bnfp4nl)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @ychoquet)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/824)* status: all files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @ychoquet)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/824)* status: all files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @ychoquet)

**Pull request merged**
