### PR TITLE
adding global style overrides

### LINKED ISSUE #1827: [BUG] Fix layers icon to look the same in the map tooltip + details tab
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The layers icon look different in map tooltip and in detail-tab.

### Expected Behavior

Make sure layer icon has a white square background.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

This PR fixes the layer icons in the map tooltip and details tab.

Fixes #1827

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://cphelefu.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1815)

### CODE REVIEW

**Review by kaminderpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1815)* status: 0 of 24 files reviewed, 4 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 252 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1815#-NrHjTEAB_uC2xoqHU5q:-NrHjTEAB_uC2xoqHU5r:bmasad3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/00027341e0dd9cd1cedeeadac0b230ea0b51483c/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L252)):*
> ```XML
>     if (layerChildIsSelected && !layerIsSelected && !isGroupOpen) {
>       result.push('selectedLayer');
>       result.push('bordered-primary');
> ```

this can be looks 

Also i know `selectedLayer` as name done before, but can we follow same pattern like dash `bordered-primary`, so that we dnt have mismatch.



_Code snippet:_
```XML
result.push('bordered-primary selectLayer');
```
___
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 257 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1815#-NrHkTfk5qmXG6jYiRxj:-NrHkTfl3gz88r7I9bjd:b-qv3dxa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/00027341e0dd9cd1cedeeadac0b230ea0b51483c/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L257)):*
> ```XML
>     if (layerIsSelected) {
>       result.push('selectedLayer');
>       result.push('bordered-primary');
> ```

same here above
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 179 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1815#-NrHiwQe1o49pCGFoA0S:-NrHiwQfBYZYr7YJU8rj:b-aqvrz0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/00027341e0dd9cd1cedeeadac0b230ea0b51483c/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L179)):*
> ```XML
>           {navBarComponents.includes('location') && <Location />}
>           {navBarComponents.includes('home') && <Home />}
>           {navBarComponents.includes('export') && <ExportButton sxDetails={sxClasses.navButton} className="" />}
> ```

Do we need className?
___
*[`packages/geoview-core/src/ui/style/themeOptionsGenerator.ts` line 212 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1815#-NrHjCGc9QgODj-rVivA:-NrHjCGc9QgODj-rVivB:b-gez9mu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/00027341e0dd9cd1cedeeadac0b230ea0b51483c/packages/geoview-core/src/ui/style/themeOptionsGenerator.ts#L212)):*
> ```XML
>         styleOverrides: {
>           root: {
>             '&.style1': {
> ```

R we still gonna use `style1`, `style2`, `style3` naming convention?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, 4 of 10 files at r2, 2 of 5 files at r3, 3 of 6 files at r4, 8 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1815)* status: 17 of 24 files reviewed, 6 unresolved discussions (waiting on @cphelefu and @kaminderpal)

___
*[`packages/geoview-core/src/ui/style/global-style-overrides.ts` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1815#-NrHuyf41c14712F_i8v:-NrHuyf54XNuQZmNtMaz:b-qg1zro) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d63b1f5d7c7b8b42a99b97b3624f9382ff28a066/packages/geoview-core/src/ui/style/global-style-overrides.ts#L17)):*
> ```XML
>   },
> 
>   '.subtitle': {
> ```

Was this use for layer left panel tooltip?
___
*[`packages/geoview-core/src/ui/style/themeOptionsGenerator.ts` line 216 at r4](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1815#-NrHvHSH0YsZsTN-Wgtp:-NrHvHSH0YsZsTN-Wgtq:b1elmyf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/349e2d6fec6766fd866d46ebda91e0fef965414e/packages/geoview-core/src/ui/style/themeOptionsGenerator.ts#L216)):*
> ```XML
>               color: `${geoViewColors.primary.main} !important`,
>               '&:hover, &:active, &.active': {
>                 backgroundColor: `${geoViewColors.primary.light[400]} !important`,
> ```

Kaminder's comment about important in this file, does this apply here? I see a lot of !important
___
*[`packages/geoview-core/src/ui/style/themeOptionsGenerator.ts` line 212 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1815#-NrHjCGc9QgODj-rVivA:-NrHv9q312ezoLt5iMKu:b3saa23) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/00027341e0dd9cd1cedeeadac0b230ea0b51483c/packages/geoview-core/src/ui/style/themeOptionsGenerator.ts#L212)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

R we still gonna use `style1`, `style2`, `style3` naming convention?
</blockquote></details>

Agree, should have a better name to reflect state or type of use?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/ui/style/global-style-overrides.ts` line 17 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1815#-NrHuyf41c14712F_i8v:-NrLHgGh4lvKFnbjYgPG:bhfmg9z) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d63b1f5d7c7b8b42a99b97b3624f9382ff28a066/packages/geoview-core/src/ui/style/global-style-overrides.ts#L17)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Was this use for layer left panel tooltip?
</blockquote></details>

Its used for the links in the details table.
Also links in the modal thats displayed you click on the icon in the appbar.

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/ui/style/themeOptionsGenerator.ts` line 212 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1815#-NrHjCGc9QgODj-rVivA:-NrLIcCu2XhG8xKuZvKn:b-i9k5k9) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/00027341e0dd9cd1cedeeadac0b230ea0b51483c/packages/geoview-core/src/ui/style/themeOptionsGenerator.ts#L212)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Agree, should have a better name to reflect state or type of use?
</blockquote></details>

Yes, will be renaming those later as I use them. Not sure what to name them yet.

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1815)* status: 14 of 25 files reviewed, 6 unresolved discussions (waiting on @jolevesq and @kaminderpal)

___
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 252 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1815#-NrHjTEAB_uC2xoqHU5q:-NrLHY_h31vdVK3wI8ri:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/00027341e0dd9cd1cedeeadac0b230ea0b51483c/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L252)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

this can be looks 

Also i know `selectedLayer` as name done before, but can we follow same pattern like dash `bordered-primary`, so that we dnt have mismatch.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx` line 257 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1815#-NrHkTfk5qmXG6jYiRxj:-NrLHZ6W3yHcNWyNAexo:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/00027341e0dd9cd1cedeeadac0b230ea0b51483c/packages/geoview-core/src/core/components/layers/left-panel/single-layer.tsx#L257)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

same here above
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx` line 179 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1815#-NrHiwQe1o49pCGFoA0S:-NrLH_QQ7Y2MnjgqLfXP:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/00027341e0dd9cd1cedeeadac0b230ea0b51483c/packages/geoview-core/src/core/components/nav-bar/nav-bar.tsx#L179)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

Do we need className?
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 6 files at r4, 2 of 12 files at r5, 5 of 6 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1815)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
