### PR TITLE
fix(data-table): UI freeze when big download

### LINKED ISSUE #2580: [BUG] Data table download/export freeze ui for large dataset
**Is there an existing issue for this?**
Please search to see if an issue already exists for the bug you encountered.
No

**Current Behavior**
A concise description of what you're experiencing.
When we try to download a huge data-table in GeoJSON, the UI freeze ans sometime JSON.Stringnify fails as it is too big.
We need to process by chunk and use a WebWorker to encapsulate the geometry reprojection in the download.

**Expected Behavior**
A concise description of what you expected to happen.
The download should not freeze the UI and user should be informed of the progress by the snackbar

**Steps To Reproduce**
1. Go to https://canadian-geospatial-platform.github.io/geoview/public/outlier-ESRI-maxRecordCount.html or https://canadian-geospatial-platform.github.io/geoview/public/outlier-elections-2019.html
2. Click on Data-Table then click on election dataset
3. Click download as GeoJSON
4. See UI freeze and error for the election 2019 as dataset is too big for the stringnify 

**Anything else?**
References? Anything that will give us more context about the issue you are encountering and if applicable, add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by jolevesq**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Create a worker architecture with a worker to generate the JSON to download so UI is not frozen

__Not ready to merge, need to incorporate latest esri dynamic change__

Fixes #2580

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Hosted, November 13th: 8:30am

https://jolevesq.github.io/geoview/outlier-ESRI-maxRecordCount.html
Open table and download JSON. See the UI is not frozen and we can switch tab.

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586)

### CODE REVIEW

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 22 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586)* status: 22 of 25 files reviewed, 6 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 345 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRWNNb5O85n2ALf2Vb:-OBRWNNb5O85n2ALf2Vc:bdd0m8s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/api/config/types/map-schema-types.ts#L345)):*
> ```XML
> // TODO: Refactor - Layers/Config refactoring. The values here have been renamed to lower case, make sure to lower here and adjust everywhere as part of config migration.
> // TODO.CONT: What is the fastest option... change config or all code, see what is the fastest
> export type TypeStyleGeometry = 'point' | 'linestring' | 'multilineString' | 'polygon' | 'multipolygon';
> ```

Also (1), because of the config refactor, there's also 2 `TypeStyleGeometry` types, in 2 different `map-schema-types.ts` files. Do we want to standardize?

Also (2), I see that the 2 new options were added here, but the function in `types\classes\geoview-config\abstract-geoview-esri-layer-config\convertEsriGeometryTypeToOLGeometryType()` still returns the old subset of possibilities only. Is it as expected?

___
*[`packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts` line 384 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRZ4v7C45t4S-ulPZP:-OBRZ4v7C45t4S-ulPZQ:bvoryji) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts#L384)):*
> ```XML
>   protected getFieldDomain(fieldName: string): null | codedValueType | rangeDomainType {
>     // Log
>     // logger.logWarning(`getFieldDomain is not implemented for ${fieldName} on layer path ${this.getLayerPath()}`);
> ```

Why removing the log warning here?
___
*[`packages/geoview-core/src/core/utils/logger.ts` line 193 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRZhDz4N2JZ71HW7L-:-OBRZhDz4N2JZ71HW7L0:b-6xt497) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/utils/logger.ts#L193)):*
> ```XML
>     if (!LOG_ACTIVE) return;
>     // Redirect
>     this.#logLevel(LOG_TRACE_WORKER, 'WORKER', 'pink', ...messages); // Not a typo, 5 characters for alignment
> ```

For alignment in the console output, can we write `WORKR` (5 characters long)
___
*[`packages/geoview-core/src/core/utils/logger.ts` line 475 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRZZ_9CsYB0QEcqrC-:-OBRZZ_9CsYB0QEcqrC0:b-g94s38) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/utils/logger.ts#L475)):*
> ```XML
> // logger.logTraceCoreAPIEvent('trace api event');
> // logger.logTraceCore('trace core');
> // logger.logTraceCore('trace worker');
> ```

Replace `logTraceCore` par  `logTraceWorker`?
___
*[`packages/geoview-core/src/core/components/index.ts` line 11 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRXXog-_mFOucyxecR:-OBRXXog-_mFOucyxecS:bx4bke8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/components/index.ts#L11)):*
> ```XML
> export * from './data-table/export-button';
> export * from './data-table/filter-map';
> export * from './data-table/json-export-button-ori';
> ```

Je déduis que c'était suite à des conflits entre branches que le json-export-button-ori a été créé?
Il ne manquerait pas `export * from './data-table/json-export-button';` si on veut avoir les 2 en parallèle? Ou bien cette duplication est temporaire?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1059 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRZ1fSDell_EMirL07:-OBRZ1fSDell_EMirL08:bvoryji) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1059)):*
> ```XML
>   protected getFieldDomain(fieldName: string, layerConfig: AbstractBaseLayerEntryConfig): null | codedValueType | rangeDomainType {
>     // Log
>     // logger.logWarning(`getFieldDomain is not implemented for ${fieldName} - ${layerConfig}`);
> ```

Why removing the log warning here?

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 3 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586)* status: all files reviewed, 9 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/core/workers/abstract-worker.ts` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRdpuW3Z9MVAS3vuKc:-OBRdpuW3Z9MVAS3vuKd:blzaxzi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/workers/abstract-worker.ts#L50)):*
> ```XML
>    */
>   #setupLogging(): void {
>     this.worker.onmessage = (event) => {
> ```

Suggestion to add comment on the registration of the callback here, as it's a pretty important step
___
*[`packages/geoview-core/src/core/workers/json-export-worker.ts` line 54 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRsNjXE1Knz1fRR3F-:-OBRsNjY0qj9AkHZwk-D:b-zh5skl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/workers/json-export-worker.ts#L54)):*
> ```XML
>    */
>   public async init(projectionInfo: TypeWorkerExportProjectionInfo): Promise<void> {
>     await this.proxy.init(projectionInfo);
> ```

Great implementation of the worker.
Can we simply `return this.proxy.init(projectionInfo);` here and remove `async` from the method signature?
___
*[`packages/geoview-core/src/core/workers/json-export-worker.ts` line 64 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRsCqZ6NnCWZqj9od7:-OBRsCqZ6NnCWZqj9od8:b-nqqhi0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/workers/json-export-worker.ts#L64)):*
> ```XML
>    */
>   public async process(chunk: TypeWorkerExportChunk[], isFirst: boolean): Promise<string> {
>     const result = await this.proxy.process(chunk, isFirst);
> ```

Can we simply `return this.proxy.process(chunk, isFirst)` here and remove `async` from the method signature?

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586)* status: all files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/core/components/index.ts` line 11 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRXXog-_mFOucyxecR:-OBWcs1A6MIuJKu2wffO:bcp84as) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/components/index.ts#L11)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Je déduis que c'était suite à des conflits entre branches que le json-export-button-ori a été créé?
Il ne manquerait pas `export * from './data-table/json-export-button';` si on veut avoir les 2 en parallèle? Ou bien cette duplication est temporaire?
</blockquote></details>

Temporaire, je dois remettre le code du dynamic dedans. Il y avait trop de conflit pour faire un live rebase

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586)* status: all files reviewed, 16 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 345 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBWiO8e7WdP6UV-1ivW:-OBWiO8e7WdP6UV-1ivX:bljznxa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/api/config/types/map-schema-types.ts#L345)):*
> ```XML
> // TODO: Refactor - Layers/Config refactoring. The values here have been renamed to lower case, make sure to lower here and adjust everywhere as part of config migration.
> // TODO.CONT: What is the fastest option... change config or all code, see what is the fastest
> export type TypeStyleGeometry = 'point' | 'linestring' | 'multilineString' | 'polygon' | 'multipolygon';
> ```

Do we want all lower case? The S in "multilineString" is capitalized
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 1198 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBWpq9KBfFF72baNdUb:-OBWpq9KBfFF72baNdUc:b-jmzwk8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/geo/map/map-viewer.ts#L1198)):*
> ```XML
>       this.layer.removeAllGeoviewLayers();
>       // eslint-disable-next-line @typescript-eslint/no-unused-vars
>     } catch (err) {
> ```

Should we just log this to use the variable and avoid the disable? Might be useful info at some point
___
*[`packages/geoview-core/src/core/workers/abstract-worker.ts` line 33 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBWn1sL8aWgve17LVlS:-OBWn1sL8aWgve17LVlT:bef28ch) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/workers/abstract-worker.ts#L33)):*
> ```XML
>   /**
>    * Creates an instance of AbstractWorker.
>    * @param {string} name - The Web Worker name for logging..
> ```

Extra "."
___
*[`packages/geoview-core/src/core/components/data-table/json-export-button.tsx` line 42 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBWjs8v9QR4ajAy-pmm:-OBWjs8v9QR4ajAy-pmn:bw5byb2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/components/data-table/json-export-button.tsx#L42)):*
> ```XML
>    *
>    * @param {Geometry} geometry - The geometry
>    * @returns {TypeJsonObject} The serialize geometry json
> ```

serialize -> serialized
___
*[`packages/geoview-core/src/core/components/data-table/json-export-button.tsx` line 72 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBWkOKl3bJKpIJTumNl:-OBWkOKl3bJKpIJTumNm:b8w2jby) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/components/data-table/json-export-button.tsx#L72)):*
> ```XML
>    */
>   const getJson = useCallback(
>     // eslint-disable-next-line func-names
> ```

Comment to explain eslint disable?
___
*[`packages/geoview-core/src/core/components/data-table/json-export-button.tsx` line 93 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBWl3Hz0ON7UwVTof2G:-OBWl3Hz0ON7UwVTof2H:bp11pzr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/components/data-table/json-export-button.tsx#L93)):*
> ```XML
>           const chunk = features.slice(i, i + chunkSize);
> 
>           // Use rowsIDSet to get features that needs to be ecxported, then serialize geometry
> ```

ecxported -> exported
___
*[`packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts` line 1223 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBWqNsM9n6k-upC90mZ:-OBWqNsM9n6k-upC90m_:brhun0a) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts#L1223)):*
> ```XML
>     }
>     return legendStyles;
>     // eslint-disable-next-line @typescript-eslint/no-unused-vars
> ```

Same here?

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586)* status: 17 of 28 files reviewed, 16 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 345 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBWiO8e7WdP6UV-1ivW:-OBWx55u8XvP4BDRxDWN:b-krqiky) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/api/config/types/map-schema-types.ts#L345)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Do we want all lower case? The S in "multilineString" is capitalized
</blockquote></details>

No lower case anymore, please Damon apply change  in your style PR
___
*[`packages/geoview-core/src/api/config/types/map-schema-types.ts` line 345 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRWNNb5O85n2ALf2Vb:-OBWxAgTAZnu6LUV6ZOt:b-ccv4sp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/api/config/types/map-schema-types.ts#L345)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Also (1), because of the config refactor, there's also 2 `TypeStyleGeometry` types, in 2 different `map-schema-types.ts` files. Do we want to standardize?

Also (2), I see that the 2 new options were added here, but the function in `types\classes\geoview-config\abstract-geoview-esri-layer-config\convertEsriGeometryTypeToOLGeometryType()` still returns the old subset of possibilities only. Is it as expected?

</blockquote></details>

This will need to be fix when we moved to new config.  I dont know why Yves does not use the multi geometry in is code....
___
*[`packages/geoview-core/src/core/utils/logger.ts` line 193 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRZhDz4N2JZ71HW7L-:-OBWu0-7AeQLmgL1kh63:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/utils/logger.ts#L193)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

For alignment in the console output, can we write `WORKR` (5 characters long)
</blockquote></details>

Done
___
*[`packages/geoview-core/src/core/utils/logger.ts` line 475 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRZZ_9CsYB0QEcqrC-:-OBWu8ph38Y3Tn8K9Hsc:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/utils/logger.ts#L475)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Replace `logTraceCore` par  `logTraceWorker`?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/workers/abstract-worker.ts` line 33 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBWn1sL8aWgve17LVlS:-OBWuFSGELfNtBTMYiju:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/workers/abstract-worker.ts#L33)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Extra "."
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/workers/abstract-worker.ts` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRdpuW3Z9MVAS3vuKc:-OBWv7yNDAGz2EmubScQ:b-fjks66) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/workers/abstract-worker.ts#L50)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Suggestion to add comment on the registration of the callback here, as it's a pretty important step
</blockquote></details>

Done I think
___
*[`packages/geoview-core/src/core/workers/json-export-worker.ts` line 54 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRsNjXE1Knz1fRR3F-:-OBWvEwl5hz93kQ_YuyY:b-8b87nn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/workers/json-export-worker.ts#L54)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Great implementation of the worker.
Can we simply `return this.proxy.init(projectionInfo);` here and remove `async` from the method signature?
</blockquote></details>

I think so but if further worker needs an async.. can it be added only by the instance and be removed from the abstract signature?
___
*[`packages/geoview-core/src/core/workers/json-export-worker.ts` line 64 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRsCqZ6NnCWZqj9od7:-OBWv_2cCOj1Pr5kn6Es:b-qmvobn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/workers/json-export-worker.ts#L64)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Can we simply `return this.proxy.process(chunk, isFirst)` here and remove `async` from the method signature?
</blockquote></details>

Will have to remove the promess return type as well. CAn this be added as signature even if not said in the abstract?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1059 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRZ1fSDell_EMirL07:-OBWvl2g7ITrvO6Nh_QO:be1hqeo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1059)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Why removing the log warning here?
</blockquote></details>

Because it gets triggrered 60 000 times when we build data table. I will put a comment
___
*[`packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts` line 384 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRZ4v7C45t4S-ulPZP:-OBWwAKs4Udp5ft-jdKc:b-ya81ng) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/geo/layer/gv-layers/abstract-gv-layer.ts#L384)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Why removing the log warning here?
</blockquote></details>

Same as above
___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 1198 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBWpq9KBfFF72baNdUb:-OBWwdEW-tR2YlhLv35G:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/geo/map/map-viewer.ts#L1198)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Should we just log this to use the variable and avoid the disable? Might be useful info at some point
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts` line 1223 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBWqNsM9n6k-upC90mZ:-OBWwoJgEofwfJIf4QxE:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts#L1223)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Same here?
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 9 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586)* status: 17 of 28 files reviewed, 16 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/core/components/data-table/json-export-button.tsx` line 42 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBWjs8v9QR4ajAy-pmm:-OB_kybD155Z5Y2paQO4:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/components/data-table/json-export-button.tsx#L42)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

serialize -> serialized
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/data-table/json-export-button.tsx` line 72 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBWkOKl3bJKpIJTumNl:-OB_qeFg5KS0FFi2Nvef:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/components/data-table/json-export-button.tsx#L72)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Comment to explain eslint disable?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/data-table/json-export-button.tsx` line 93 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBWl3Hz0ON7UwVTof2G:-OB_qkZn1qAp6iN39PDC:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/components/data-table/json-export-button.tsx#L93)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

ecxported -> exported
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 7 of 25 files at r1, 8 of 11 files at r2, 6 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586)* status: 27 of 30 files reviewed, 16 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

**Review by DamonU2 — APPROVED** [review]
> Reviewed 10 of 11 files at r2, 1 of 1 files at r3, 6 of 8 files at r4, 4 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586)* status: all files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan)

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r2, 6 of 8 files at r4, 4 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/workers/abstract-worker.ts` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRdpuW3Z9MVAS3vuKc:-OBbaaOq-xwpYUKZ34o0:bd3kzyp) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/workers/abstract-worker.ts#L50)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Done I think
</blockquote></details>

The added comments are good, but I meant comment the `this.worker.onmessage =` line :smile:
___
*[`packages/geoview-core/src/core/workers/json-export-worker.ts` line 54 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRsNjXE1Knz1fRR3F-:-OBbayPi9vlFytaSwPAD:bgh1rer) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/workers/json-export-worker.ts#L54)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think so but if further worker needs an async.. can it be added only by the instance and be removed from the abstract signature?
</blockquote></details>

The `async` keyword isn't part of the method signature in of itself. If I understand your concern, yes, the abstract signature can be signed without the async and one could still await on it. As long as a Promise is returned, one can await on it.
___
*[`packages/geoview-core/src/core/workers/json-export-worker.ts` line 64 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586#-OBRsCqZ6NnCWZqj9od7:-OBbbLRd9jExlENGDWh8:b-t3cirs) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d7b1dbfba62e2c4a30dcb92e9ef3a6c6144fa244/packages/geoview-core/src/core/workers/json-export-worker.ts#L64)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Will have to remove the promess return type as well. CAn this be added as signature even if not said in the abstract?
</blockquote></details>

See other comment I think

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 11 files at r2, 2 of 8 files at r4, 5 of 6 files at r5, 2 of 2 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2586)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq)

**Pull request merged**
