### PR TITLE
1379 time slider

### PR DESCRIPTION
**Pull request by DamonU2**
# Description

Added time slider package for layers that have a temporal dimension.

Fixes # 1379

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested with three layers with temporal data
https://damonu2.github.io/geoview/package-time-slider.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1438)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 9 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1438)* status: 9 of 15 files reviewed, 2 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/src/core/components/time-slider/time-slider.tsx` line 49 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1438#-Nhhh6jc5Q-kAL010zIp:-Nhhh6jd2B-dBuGNFBCm:b-g2w6v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4505ccf53fc1694e075940aa9aac18e6f74e5f0e/packages/geoview-core/src/core/components/time-slider/time-slider.tsx#L49)):*
> ```XML
> 
>   // Create list of layers that have a temporal dimension
>   const layersList: string[] = Object.keys(api.maps[mapId].layer.registeredLayers).filter(
> ```

Should both constant be in useEffect to minimize the call every time there is a rendering?
___
*[`packages/geoview-footer-panel/src/time-slider.tsx` line 41 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1438#-NhhhbGD2kd7AwpHtdn-:-NhhhbGD2kd7AwpHtdn0:bs4v0c1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4505ccf53fc1694e075940aa9aac18e6f74e5f0e/packages/geoview-footer-panel/src/time-slider.tsx#L41)):*
> ```XML
> 
>   useEffect(() => {
>     api.event.on(api.eventNames.MAP.EVENT_MAP_LOADED, getTimeSlider, mapId);
> ```

How will we be dealing with packages and store....

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1438)* status: 7 of 15 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/time-slider/time-slider.tsx` line 49 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1438#-Nhhh6jc5Q-kAL010zIp:-Nhhu5eJ6UwAV7WhQBQW:bpwwdyf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4505ccf53fc1694e075940aa9aac18e6f74e5f0e/packages/geoview-core/src/core/components/time-slider/time-slider.tsx#L49)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should both constant be in useEffect to minimize the call every time there is a rendering?
</blockquote></details>

Moved to api

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1438)* status: 7 of 15 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/time-slider/time-slider.tsx` line 49 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1438#-Nhhh6jc5Q-kAL010zIp:-NhhwNHR3AyMMlyK95B_:beorhjk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4505ccf53fc1694e075940aa9aac18e6f74e5f0e/packages/geoview-core/src/core/components/time-slider/time-slider.tsx#L49)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Moved to api
</blockquote></details>

Will be good to move back and put in useEffect once the store has a list of visible layers available that it can update from.

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1438)* status: 7 of 15 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-footer-panel/src/time-slider.tsx` line 41 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1438#-NhhhbGD2kd7AwpHtdn-:-Nhi2PiQ9sDPcwXyoQCU:b-im1zoo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/4505ccf53fc1694e075940aa9aac18e6f74e5f0e/packages/geoview-footer-panel/src/time-slider.tsx#L41)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

How will we be dealing with packages and store....
</blockquote></details>

This file is just a copy of the other tabs here with extras removed, I imagine we can probably tie them all to mapState.mapLoaded

**Review by jolevesq — COMMENTED** [review]
> Reviewed 5 of 15 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1438)* status: 13 of 15 files reviewed, all discussions resolved

**Review by jolevesq — COMMENTED** [review]
We should modify dates format to be ISO... always YYYY/MM/DD same for English and French

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1438#-:-Ni4fsUwE6R1mNGzXYc-:bptujcu)* status: 13 of 15 files reviewed, all discussions resolved

**Review by DamonU2 — COMMENTED** [review]
Fixed both

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1438#-:-Ni53JRtA2Ik1tPq0DQ2:b-yc3rzi)* status: 8 of 15 files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 2 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1438)* status: 11 of 15 files reviewed, all discussions resolved (waiting on @DamonU2)

**Review by jolevesq — APPROVED** [review]
> Reviewed 4 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1438)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
