### PR TITLE
2191-Early processing of geocore layers

### LINKED ISSUE #2191: Early processing of geocore layers
Geocore layers are not real GeoView layers. We need to intercept them at the very beginning of layer validation and convert them to their GeoView configuration as soon as possible.

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

This PR will process the GeoCore layers at the very beginning to get the GeoView layer definition before doing the internal schema validation.

Fixes #2191

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using Chrome Devtool to trace and debug the code.

__Deploy URL__: https://ychoquet.github.io/GeoView/geocore.html and https://ychoquet.github.io/GeoView/config-sandbox.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 213 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-Nz8Gvxs8auWKAuhtItR:-Nz8Gvxs8auWKAuhtItS:bsyfcky) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/87953fccdef0bd0f71a6e165fcbf10b6fdbc9b3c/packages/geoview-core/src/api/config/config-api.ts#L213)):*
> ```XML
>         const geocoreUrl = (providedMapFeatureConfig?.serviceUrls?.geocoreUrl ||
>           CV_DEFAULT_MAP_FEATURE_CONFIG.serviceUrls.geocoreUrl) as string;
>         providedMapFeatureConfig.map.listOfGeoviewLayerConfig.forEach((layerConfig, i) => {
> ```

CAn you add some blank line and comments for readability. I have a hard time to follow what is going on
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 219 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-Nz8HUzl5XgyG3suE0G_:-Nz8HUzl5XgyG3suE0Ga:bleh0wg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/87953fccdef0bd0f71a6e165fcbf10b6fdbc9b3c/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L219)):*
> ```XML
>       //   return new WmsLayerConfig(layerConfig);
>       case 'geocore':
>         logger.logError(`Unable to process Geocore layer (${layerConfig.geoviewLayerId}).`);
> ```

You add the error because at this point there should be no more geocore? If so, please add a comment

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 213 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-Nz8Gvxs8auWKAuhtItR:-NzAIKcC6KpHy4MuC5n_:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/87953fccdef0bd0f71a6e165fcbf10b6fdbc9b3c/packages/geoview-core/src/api/config/config-api.ts#L213)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

CAn you add some blank line and comments for readability. I have a hard time to follow what is going on
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/map-feature-config.ts` line 219 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-Nz8HUzl5XgyG3suE0G_:-NzAINve8amGAEVxMaXK:bg075oh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/87953fccdef0bd0f71a6e165fcbf10b6fdbc9b3c/packages/geoview-core/src/api/config/types/classes/map-feature-config.ts#L219)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You add the error because at this point there should be no more geocore? If so, please add a comment
</blockquote></details>

Done. Removed from here and moved to a central place in the ConfigApi.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 12 of 14 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 210 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzDSy9526f5qKfYBHry:-NzDSy9526f5qKfYBHrz:b-c0te0y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79ca7224683554f582101870494f4200ec5c7517/packages/geoview-core/src/api/config/config-api.ts#L210)):*
> ```XML
>   // GV: favor of their GeoView equivalent as soon as possible. Processing is based on the JSON representation of the config,
>   // GV: and requires a minimum of validation to ensure that the configuration of GeoCore layers is valid.
>   static async getMapConfig(mapConfig: string | TypeJsonObject, language: TypeDisplayLanguage): Promise<MapFeatureConfig> {
> ```

I think we should split this function in 2..... first you deal with the config then you have a function were you send the list of layers to be cleaned up from geocore with explicit name. This way function is doing one thing on name is more aligned
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 233 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzDTSV62mH8DNCO4vA1:-NzDTSV62mH8DNCO4vA2:bxqvwxy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79ca7224683554f582101870494f4200ec5c7517/packages/geoview-core/src/api/config/config-api.ts#L233)):*
> ```XML
> 
>       // Convert all geoviewLayerType containing the value 'geocore' to lowercase, regardless of the case used.
>       // We do this because we want the 'geocore' test to be case-insensitive.
> ```

Why this test, we do not do this for other type? Did we?

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @jolevesq)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 210 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzDSy9526f5qKfYBHry:-NzDlfAa05lifbpazJbT:b-dgb5s1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79ca7224683554f582101870494f4200ec5c7517/packages/geoview-core/src/api/config/config-api.ts#L210)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think we should split this function in 2..... first you deal with the config then you have a function were you send the list of layers to be cleaned up from geocore with explicit name. This way function is doing one thing on name is more aligned
</blockquote></details>

It is better to eliminate hte geocore layers at the very beginning because it allow us to have a schema that doesn't have a geoviewLayerType that contains the value 'geocore'. There's no reason to embed geocore layers deep in the code.
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 233 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzDTSV62mH8DNCO4vA1:-NzDnTIjA8k_6lq0jr1O:bn9ke7k) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/79ca7224683554f582101870494f4200ec5c7517/packages/geoview-core/src/api/config/config-api.ts#L233)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why this test, we do not do this for other type? Did we?
</blockquote></details>

As mentioned in the comment, we do this because we want the 'geocore' test to be case-insensitive. This will accept GeoCore, geoCore, GEOCORE, geocore and if the ID is good, the user wont get an error message saying the geoviewLayerType is invalid.

We don't do that with the other GeoView layerTypes because it is not possible to specify a case-insensitive domaine for a property in the schema. We have to keep in mind that the validation here is done well before the schema validation.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 210 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzDSy9526f5qKfYBHry:-NzDrv91AP6HEvLDuhAc:b-ffcfcy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fadb30e5875a9d39fa2fed96fab956332bb5cb51/packages/geoview-core/src/api/config/config-api.ts#L210)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

It is better to eliminate hte geocore layers at the very beginning because it allow us to have a schema that doesn't have a geoviewLayerType that contains the value 'geocore'. There's no reason to embed geocore layers deep in the code.
</blockquote></details>

This is not what I meant, I just say you can split this function in 2 to have them more align with one task.
getMapConfig - call - processLayers instead of having everything in a high level function that does everything. At the end it is the same code execution just easier to follow
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 233 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzDTSV62mH8DNCO4vA1:-NzDsSgs4NZfePgCtsAK:be3i8lv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fadb30e5875a9d39fa2fed96fab956332bb5cb51/packages/geoview-core/src/api/config/config-api.ts#L233)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

As mentioned in the comment, we do this because we want the 'geocore' test to be case-insensitive. This will accept GeoCore, geoCore, GEOCORE, geocore and if the ID is good, the user wont get an error message saying the geoviewLayerType is invalid.

We don't do that with the other GeoView layerTypes because it is not possible to specify a case-insensitive domaine for a property in the schema. We have to keep in mind that the validation here is done well before the schema validation.
</blockquote></details>

But we already have a geocore schema valid value like esriFeature. We can keep like this but I think checking the schema - parsing geocore - returning value would have been an easier flow.

**Review by DamonU2 — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 12 of 14 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 210 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzDSy9526f5qKfYBHry:-NzDzcEl6b9VWiQtqG9h:bo1kb0x) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fadb30e5875a9d39fa2fed96fab956332bb5cb51/packages/geoview-core/src/api/config/config-api.ts#L210)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This is not what I meant, I just say you can split this function in 2 to have them more align with one task.
getMapConfig - call - processLayers instead of having everything in a high level function that does everything. At the end it is the same code execution just easier to follow
</blockquote></details>

I'll do in the next PR.
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 233 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzDTSV62mH8DNCO4vA1:-NzDzUbk1H5r3Ph89kZu:bo1kb0x) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fadb30e5875a9d39fa2fed96fab956332bb5cb51/packages/geoview-core/src/api/config/config-api.ts#L233)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

But we already have a geocore schema valid value like esriFeature. We can keep like this but I think checking the schema - parsing geocore - returning value would have been an easier flow.
</blockquote></details>

I'll do in the next PR.

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 12 of 14 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192)* status: all files reviewed, 5 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/public/configs/validator/04-geocore.json` line 76 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzEBIKi-68Objpaiy3O:-NzEBIKi-68Objpaiy3P:b-a80s5u) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fadb30e5875a9d39fa2fed96fab956332bb5cb51/packages/geoview-core/public/configs/validator/04-geocore.json#L76)):*
> ```JSON
>     "overview-map"
>   ],
>   "corePackages": [],
> ```

can we add the geochart plugin in this template so that we can test if geocore works with geochart?
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 210 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzDSy9526f5qKfYBHry:-NzE9a7h0EJqtF08c91P:bxx71wa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fadb30e5875a9d39fa2fed96fab956332bb5cb51/packages/geoview-core/src/api/config/config-api.ts#L210)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I'll do in the next PR.
</blockquote></details>

Question.

I understand that the geocore layers processing happens here, asap, so that the configuration contains geoview layers exclusively. That's alright. My question is, does that mean the geochart configurations will also be "translated" into the map configuration so that we know what geochart configurations to apply on what layers?

Before, when a geochart configuration was found (when the processing was happening later) it was calling the GeoChartEventProcessor. Now I wonder if we'll (1) call the GeoChartEventProcessor like before (though it seems too early to do so) or (2) carry the configurations with us so that when ready, then we call the GeoChartEventProcessor.

I'm just questioning myself on how we're going to handle the geochart configurations coming from geocore. That information needs to carry over somehow (or we'll have to call geocore service twice).
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts` line 47 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzEBl2l0amkPc2gPgpX:-NzEBl2l0amkPc2gPgpY:b1t7b1s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fadb30e5875a9d39fa2fed96fab956332bb5cb51/packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts#L47)):*
> ```XML
>     super(layerConfig, initialSettings, language, geoviewLayerConfig, parentNode);
>     // Set default values.
>     this.source = defaultsDeep(this.source, { maxRecordCount: 0, format: 'png', featureInfo: { queryable: false } });
> ```

Question.

At what layerStatus is this code executed?

When this gets called and source is set with a featureInfo that is queryable 'false', **is it because it's certain that it's 'false' or can it change back to 'true' at some point?**

It's a concern, because when we track the layerStatuses in the layer-sets, in the Details/Data-Table layer-sets for example, when those find out that the queryable is set to 'false' they get removed from their layer-sets and they never show in the store/ui.

I thought it'd be `undefined` for as long as the queryable isn't, for a fact, determined to be true or false (not false by default). The layer-sets processing was waiting on the property to be set before deciding to effectively possibly remove, "forever", the layer from being tracked.

In other words, this depends on **when the layer statuses changes** (its lifecycle) vs when the code here is executed. Indeed, the layer-sets might have removed the layer from its set and wouldn't be added back in even if later the processing would turn the `featureInfo.queryable` to `true`.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/vector-leaf/esri-feature-layer-entry-config.ts` line 44 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzED1cM8hMdmO4xJz5o:-NzED1cNAo0Vqciu6fYd:b-80wp0l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fadb30e5875a9d39fa2fed96fab956332bb5cb51/packages/geoview-core/src/api/config/types/classes/sub-layer-config/vector-leaf/esri-feature-layer-entry-config.ts#L44)):*
> ```XML
>     super(layerConfig, initialSettings, language, geoviewLayerConfig, parentNode);
>     // Set default values.
>     this.source = defaultsDeep(this.source, { maxRecordCount: 0, format: 'EsriJSON', featureInfo: { queryable: false } });
> ```

Same question

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192)* status: all files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/public/configs/validator/04-geocore.json` line 76 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzEBIKi-68Objpaiy3O:-NzEUUvd74rEO3yH78yW:b-5m4bw4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fadb30e5875a9d39fa2fed96fab956332bb5cb51/packages/geoview-core/public/configs/validator/04-geocore.json#L76)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

can we add the geochart plugin in this template so that we can test if geocore works with geochart?
</blockquote></details>

We can add the geochart plugin to this template, but it will only change the same property in the resulting configuration. Configuration validation doesn't deal with the geochart plugin at the moment. I'll have to study the plugin code first, as this part of the code is a bit obscure to me. 
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 210 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzDSy9526f5qKfYBHry:-NzEQ1mu9TwTFgJxNyKO:b-3j8osk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fadb30e5875a9d39fa2fed96fab956332bb5cb51/packages/geoview-core/src/api/config/config-api.ts#L210)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Question.

I understand that the geocore layers processing happens here, asap, so that the configuration contains geoview layers exclusively. That's alright. My question is, does that mean the geochart configurations will also be "translated" into the map configuration so that we know what geochart configurations to apply on what layers?

Before, when a geochart configuration was found (when the processing was happening later) it was calling the GeoChartEventProcessor. Now I wonder if we'll (1) call the GeoChartEventProcessor like before (though it seems too early to do so) or (2) carry the configurations with us so that when ready, then we call the GeoChartEventProcessor.

I'm just questioning myself on how we're going to handle the geochart configurations coming from geocore. That information needs to carry over somehow (or we'll have to call geocore service twice).
</blockquote></details>

I find this way of integrating geoview layer definitions and chart definitions in the same geocore logic a little confusing. To me, it goes against the separation of concerns. 

Layers definitions from the geocore service has an **isGeocore** flag set to true. Is this enough to signal that a call should be made to get the chart config later.

How do you proceed when the layer doesn't come from the geocore service and a chart is associated with it? Can't the geocore configurations be translated in the same way?
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts` line 47 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzEBl2l0amkPc2gPgpX:-NzEKXDB57r2oLOl0r63:b-zakjcr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fadb30e5875a9d39fa2fed96fab956332bb5cb51/packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts#L47)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Question.

At what layerStatus is this code executed?

When this gets called and source is set with a featureInfo that is queryable 'false', **is it because it's certain that it's 'false' or can it change back to 'true' at some point?**

It's a concern, because when we track the layerStatuses in the layer-sets, in the Details/Data-Table layer-sets for example, when those find out that the queryable is set to 'false' they get removed from their layer-sets and they never show in the store/ui.

I thought it'd be `undefined` for as long as the queryable isn't, for a fact, determined to be true or false (not false by default). The layer-sets processing was waiting on the property to be set before deciding to effectively possibly remove, "forever", the layer from being tracked.

In other words, this depends on **when the layer statuses changes** (its lifecycle) vs when the code here is executed. Indeed, the layer-sets might have removed the layer from its set and wouldn't be added back in even if later the processing would turn the `featureInfo.queryable` to `true`.
</blockquote></details>

Yes,**the default values set here may change later if the metadata has a different value** and the original config that was parsed didn't have a value provided by the user. As long as the metadata hasn't been read, we connot assume the layer is queryable. The reason I set the default now is to allow the internal schema to be successful.

If you need the queryable flag to be undefined as a clue that the metadata fetch hasn't been done yet, I can do so.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/vector-leaf/esri-feature-layer-entry-config.ts` line 44 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzED1cM8hMdmO4xJz5o:-NzEOv6TELkHFkA95AH9:b-redf51) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fadb30e5875a9d39fa2fed96fab956332bb5cb51/packages/geoview-core/src/api/config/types/classes/sub-layer-config/vector-leaf/esri-feature-layer-entry-config.ts#L44)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Same question
</blockquote></details>

Same answer.

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192)* status: all files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 210 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzDSy9526f5qKfYBHry:-NzEeOtP3CgjQ_kGTESd:bt86x04) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fadb30e5875a9d39fa2fed96fab956332bb5cb51/packages/geoview-core/src/api/config/config-api.ts#L210)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I find this way of integrating geoview layer definitions and chart definitions in the same geocore logic a little confusing. To me, it goes against the separation of concerns. 

Layers definitions from the geocore service has an **isGeocore** flag set to true. Is this enough to signal that a call should be made to get the chart config later.

How do you proceed when the layer doesn't come from the geocore service and a chart is associated with it? Can't the geocore configurations be translated in the same way?
</blockquote></details>

I think with the flag to true, once layer is loaded geochart can call geocore with uuid to know if there is a chart or not. It will be a little bit longer but will separate the packakage from the core. Like if we defnie a chart in a config file ourselve

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192)* status: all files reviewed, 2 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/public/configs/validator/04-geocore.json` line 76 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzEBIKi-68Objpaiy3O:-NzEavWd36mgqU3rCAFJ:b4qfnv2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fadb30e5875a9d39fa2fed96fab956332bb5cb51/packages/geoview-core/public/configs/validator/04-geocore.json#L76)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

We can add the geochart plugin to this template, but it will only change the same property in the resulting configuration. Configuration validation doesn't deal with the geochart plugin at the moment. I'll have to study the plugin code first, as this part of the code is a bit obscure to me.
</blockquote></details>

Hmm okay. Well the geochart has to work for June release and I don't think the plan was to use the configuration classes before June, so it's okay I think.
___
*[`packages/geoview-core/src/api/config/config-api.ts` line 210 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzDSy9526f5qKfYBHry:-NzEbRlCETfipuehWHWI:b-rhucs4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fadb30e5875a9d39fa2fed96fab956332bb5cb51/packages/geoview-core/src/api/config/config-api.ts#L210)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think with the flag to true, once layer is loaded geochart can call geocore with uuid to know if there is a chart or not. It will be a little bit longer but will separate the packakage from the core. Like if we defnie a chart in a config file ourselve
</blockquote></details>

I guess it depends if we care for recalling the service once more later (and the geochart configuration never makes it way in the map config) or if we carry the information as part of the loading process.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts` line 47 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzEBl2l0amkPc2gPgpX:-NzEcnRe5r6DM2gtcYzW:b-nqr48b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fadb30e5875a9d39fa2fed96fab956332bb5cb51/packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts#L47)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Yes,**the default values set here may change later if the metadata has a different value** and the original config that was parsed didn't have a value provided by the user. As long as the metadata hasn't been read, we connot assume the layer is queryable. The reason I set the default now is to allow the internal schema to be successful.

If you need the queryable flag to be undefined as a clue that the metadata fetch hasn't been done yet, I can do so.
</blockquote></details>

To me, it'd make more sense to have it undefined until we know for sure, but I can adapt the layer-sets too. I'm open there.
The thing is, that's a change from the previous configurations, right? I don't see the `queryable: false` in the old configs. If so, that little change (that seems insignificant really) would have given us quite a surprise later when migrating from old configs to new configs. I'll leave it to Johann to decide and adjust. Good thing is I'm on the PR that's doing just that, coincidentally, and by chance I saw that PR just now and did 2+2.

**Review by Alex-NRCan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

___
*[`packages/geoview-core/src/api/config/config-api.ts` line 210 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzDSy9526f5qKfYBHry:-NzEj2j-DOA30doc0OPi:b-v00vsy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fadb30e5875a9d39fa2fed96fab956332bb5cb51/packages/geoview-core/src/api/config/config-api.ts#L210)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I guess it depends if we care for recalling the service once more later (and the geochart configuration never makes it way in the map config) or if we carry the information as part of the loading process.
</blockquote></details>

Let us think about it. We may find a good solution and implement it later.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts` line 47 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2192#-NzEBl2l0amkPc2gPgpX:-NzEiCL63aywfxm8nRly:b-gga4x6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/fadb30e5875a9d39fa2fed96fab956332bb5cb51/packages/geoview-core/src/api/config/types/classes/sub-layer-config/raster-leaf/esri-dynamic-layer-entry-config.ts#L47)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

To me, it'd make more sense to have it undefined until we know for sure, but I can adapt the layer-sets too. I'm open there.
The thing is, that's a change from the previous configurations, right? I don't see the `queryable: false` in the old configs. If so, that little change (that seems insignificant really) would have given us quite a surprise later when migrating from old configs to new configs. I'll leave it to Johann to decide and adjust. Good thing is I'm on the PR that's doing just that, coincidentally, and by chance I saw that PR just now and did 2+2.
</blockquote></details>

I'll leave it undefined as a signal that the metadata fetch hasn't been done yet.

**Pull request merged**
