### PR TITLE
feat(samples) clear-graphic

### LINKED ISSUE #148: Implement Clear Graphics
investigate the existence of a clear function in the API, create one if it does not and implement it vector sample page.

### PR DESCRIPTION
**Pull request by melzeiny1980**
closes #148

## Checklist

* [ ] Commit message follow the guidelines
* [ ] PR targets the correct release version
* [ ] Deploy has been done
* [ ] Check styling
* [ ] _Help files and documentation have been updated_
* [ ] ~Release notes have been updated~

## What's to look for styling
* Use camelCase for identifier names (variables and functions)
* Use PascalCase for type names
* Do not use "I" as a prefix for interface names
* Do not export types/functions unless you need to share it across multiple components
* All names start with a letter
* Always put spaces around operators ( = + - * / ), and after colon:
* Remove all trailing white spaces
* Look for bad indentation
* Carriage return are mandatory
  * Before comments
  * Before if condition
  * After if condition
  * Before properties
  * Before classes
  * Before functions

The use of Prettier Visual Studio Code extension let's you format automatically your code to remove most of the styling issues like white space and indentation.

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/151)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
Delete Group should delete geometry inside the group when push and no group is set. Or delete and recreate the default group

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/151#-:-MVq2Qfs6VduG4A7fTu0:bbgi7pz)* status: all files reviewed, 3 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[src/common/vectors/vector.ts, line 281 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/151#-MVq1qcbD4WeounvVLMT:-MVq1qcbD4WeounvVLMU:b-hxkwte) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5b6192d0e9790ecf412e9a13399436c27eea45af/src/common/vectors/vector.ts#L281)):*
> ```XML
>      * @param {GeometryType} layer the geometry to be added to the group
>      */
>     addToGeometryGroup = (layer: GeometryType, id: string): void => {
> ```

Is this should be an optional parameter? If so, add typescript optional notation and update the function param comment
___
*[src/common/vectors/vector.ts, line 312 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/151#-MVq25S02lWWk8jOXq_W:-MVq25S02lWWk8jOXq_X:b-fhzz98) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5b6192d0e9790ecf412e9a13399436c27eea45af/src/common/vectors/vector.ts#L312)):*
> ```XML
>      * @param {string} groupId the group id
>      */
>     deleteGeometryFromGroup = (geometryId: string, groupId: string): void => {
> ```

Is groupId should be an optional parameter? If so, add typescript optional notation and update the function param comment
___
*[src/common/vectors/vector.ts, line 334 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/151#-MVq29UR9dLJS4HttLpF:-MVq29UR9dLJS4HttLpG:b-fhzz98) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5b6192d0e9790ecf412e9a13399436c27eea45af/src/common/vectors/vector.ts#L334)):*
> ```XML
>     deleteGeometriesFromGroup = (id: string): void => {
>         // if group name not give, add to default group
>         const groupName = id || this.defaultGroupID;
> ```

Is groupId should be an optional parameter? If so, add typescript optional notation and update the function param comment

**Review by melzeiny1980 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/151)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[src/common/vectors/vector.ts, line 281 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/151#-MVq1qcbD4WeounvVLMT:-MVrMZL94MYwLk9Dj4Hi:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5b6192d0e9790ecf412e9a13399436c27eea45af/src/common/vectors/vector.ts#L281)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this should be an optional parameter? If so, add typescript optional notation and update the function param comment
</blockquote></details>

Done.
___
*[src/common/vectors/vector.ts, line 312 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/151#-MVq25S02lWWk8jOXq_W:-MVrMZjgC031N876mVRn:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5b6192d0e9790ecf412e9a13399436c27eea45af/src/common/vectors/vector.ts#L312)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is groupId should be an optional parameter? If so, add typescript optional notation and update the function param comment
</blockquote></details>

Done.
___
*[src/common/vectors/vector.ts, line 332 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/151#-MVrIMVq6ozAMYGJvLDZ:-MVrIMVq6ozAMYGJvLD_:b-k39mir) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5b6192d0e9790ecf412e9a13399436c27eea45af/src/common/vectors/vector.ts#L332)):*
> ```
> deleteGeometriesFromGroup 
> ```
___
*[src/common/vectors/vector.ts, line 334 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/151#-MVq29UR9dLJS4HttLpF:-MVrM_874cSLes3jDyNK:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5b6192d0e9790ecf412e9a13399436c27eea45af/src/common/vectors/vector.ts#L334)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is groupId should be an optional parameter? If so, add typescript optional notation and update the function param comment
</blockquote></details>

Done.

**Review by yass0016 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/151)* status: all files reviewed, 4 unresolved discussions (waiting on @jolevesq)

**Review by yass0016 — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/151)* status: all files reviewed, 4 unresolved discussions (waiting on @jolevesq)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/151#-:-MVurFO02hUFG_jW_Nya:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @melzeiny1980)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/151)* status: all files reviewed, 1 unresolved discussion (waiting on @melzeiny1980)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/151#-:-MVv1L__20HtRDpijAP0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @melzeiny1980)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/151)* status: all files reviewed, 1 unresolved discussion (waiting on @melzeiny1980)

___
*[src/common/vectors/vector.ts, line 332 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/151#-MVrIMVq6ozAMYGJvLDZ:-MVv1UaY2lXQgP0mPKLM:b-t2xiyk) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/5b6192d0e9790ecf412e9a13399436c27eea45af/src/common/vectors/vector.ts#L332)):*
<details><summary><i>Previously, melzeiny1980 wrote…</i></summary><blockquote>

> ```
> deleteGeometriesFromGroup 
> ```

</blockquote></details>

This comment is blocking the PR

**Pull request merged**
