### PR TITLE
adding tooltips to layers icons and deactivating layer items

### LINKED ISSUE #1660: [BUG] Add tooltips to visibility icons + deactivate layer items when layer is 'always' visible
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently there are no tooltips and for the visibility icons and also items in layers with 'always' visibility have a checkbox that can be toggled.

### Expected Behavior

Add tooltips to visibility icons + deactivate layer items when layer is 'always' visible.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cphelefu**
# Description

- [x] When layer visibility is 'always' items should reflect that (have deactivated checkboxes)
- [x] Add tooltips to layer icons.

Fixes #1660 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

https://cphelefu.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1659)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1659)* status: all files reviewed, 2 unresolved discussions (waiting on @cphelefu and @DamonU2)

___
*[`packages/geoview-core/public/locales/fr/translation.json` line 82 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1659#-NnOxiu24ku2ZC18BzT1:-NnOxiu24ku2ZC18BzT2:b262g8s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0023c8b5bc18be435f9ae1fdafff5fa4e0451d9b/packages/geoview-core/public/locales/fr/translation.json#L82)):*
> ```JSON
>     "reloadLayer": "Recharger la couche",
>     "toggleVisibility": "Basculer la visibilité",
>     "toggleCollapse": "Basculer l'effondrement"
> ```

basculer la fermeture
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 111 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1659#-NnOxyObA7BhZT7PmzTR:-NnOxyObA7BhZT7PmzTS:b-hi3t2p) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0023c8b5bc18be435f9ae1fdafff5fa4e0451d9b/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L111)):*
> ```XML
>       return null;
>     }
>     if (item.isVisible === 'always' || layerDetails.isVisible === 'always') {
> ```

What is layerDetails?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1659)* status: all files reviewed, 2 unresolved discussions (waiting on @cphelefu and @DamonU2)

___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 111 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1659#-NnOxyObA7BhZT7PmzTR:-NnOzdbp6FMxaa1JiNBu:b-id10uq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0023c8b5bc18be435f9ae1fdafff5fa4e0451d9b/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L111)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

What is layerDetails?
</blockquote></details>

Is it the list of all items (categories) inside a layer when renderer is unique value?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 111 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1659#-NnOxyObA7BhZT7PmzTR:-NnPLBoq655jRxH8Dx7L:b6v0qj0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d09ebb8bbd0312d23c5caf1f1659368bd1a4ec79/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L111)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is it the list of all items (categories) inside a layer when renderer is unique value?
</blockquote></details>

layerDetails is basically a prop passed to this component. It contains details about the layer. 
Condition here controls which checkbox is displayed for each item.

Didnt get your 2nd question

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1659)* status: all files reviewed, 2 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/public/locales/fr/translation.json` line 82 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1659#-NnOxiu24ku2ZC18BzT1:-NnPL8tY7Hc8gPTAl04Z:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d09ebb8bbd0312d23c5caf1f1659368bd1a4ec79/packages/geoview-core/public/locales/fr/translation.json#L82)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

basculer la fermeture
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1659)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
