### PR TITLE
refactor(hover): use store and map state

### LINKED ISSUE #1767: [REFACTOR] Hover Use Store
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The hover component is not using the dedicated array in the store.

### Expected Behavior

Hover should use the dedicated hoverDataArray. For the moment the array is in details state. It should be moved to mapState as hover may work even is there is no detail component.

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1767

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

refactor hover to move it to map-state and propagate to the store only the values, no result set.

Fixes #1767

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

hosted April, 3 - 5pm: https://jolevesq.github.io/geoview/raw-feature-info.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1985)

### CODE REVIEW

**Review by DamonU2 — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1985)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan and @ychoquet)

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1985)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1985#-Nucwb0U72Lj8Qw_fGqp:-Nucwb0V-XuxpmuMNhqE:b4qaxju) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e7c5b94d602a27cc584eff7cf9ca695df15d6a1b/packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx#L78)):*
> ```XML
>     logger.logTraceUseEffect('HOVER-TOOLTIP - mount');
> 
>     // if pointer position changed, reset tooltip
> ```

Maybe use the `useMapPointerPosition` hook instead of adding a subscribe in a tsx?

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1985)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1985#-Nucwb0U72Lj8Qw_fGqp:-NucynWG7MaWe5rfKykI:b-bt1y8d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e7c5b94d602a27cc584eff7cf9ca695df15d6a1b/packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx#L78)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Maybe use the `useMapPointerPosition` hook instead of adding a subscribe in a tsx?
</blockquote></details>

I use suubscribe because I do not only need the position, I need to reset the tooltip... I willl check If I can do it differently

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1985)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan, @DamonU2, and @ychoquet)

___
*[`packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx` line 78 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1985#-Nucwb0U72Lj8Qw_fGqp:-Nud5tly3nCIiyvfLDMG:b-896fjx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e7c5b94d602a27cc584eff7cf9ca695df15d6a1b/packages/geoview-core/src/core/components/hover-tooltip/hover-tooltip.tsx#L78)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I use suubscribe because I do not only need the position, I need to reset the tooltip... I willl check If I can do it differently
</blockquote></details>

Done

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1985)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ychoquet)

**Review by ychoquet — APPROVED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1985)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
