### PR TITLE
1884-[BUG] OSDP load errors.

### LINKED ISSUE #1884: [BUG] OSDP load errors.

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

Corrections to the loading process. Layers tested are OSDP demo and type of layers.

Fixes #1884

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using the Chrome Devtools.

__Deploy URL used to test__: https://ychoquet.github.io/GeoView/demo-osdp-society.html
                                                                             AND
                                               https://ychoquet.github.io/GeoView/all-layers.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 656 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885#-Nru9zJx1TEhTbaf0X_w:-Nru9zJx1TEhTbaf0X_x:b-wxoyuj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e850776734bf7349e0314f735f7b4a4dc1c3001/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L656)):*
> ```XML
>           // When we get here, we know that the metadata (if the service provide some) are processed.
>           // We need to signal to the layer sets that the 'processed' phase is done. Be aware that the
>           // layerStatus setter is doing a lot of things behind the scene.
> ```

Can you add a TODO: refactor - refactor this code to explicitly define what is going on behind the scene

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 12 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885)* status: 12 of 13 files reviewed, 11 unresolved discussions (waiting on @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 224 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885#-NruGtRg9eW_ZMjYUWOk:-NruGtRg9eW_ZMjYUWOl:b13v7er) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e850776734bf7349e0314f735f7b4a4dc1c3001/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L224)):*
> ```XML
>  *
>  * @param {EsriDynamic | EsriFeature} this The ESRI layer instance pointer.
>  * @param {TypeEsriFeatureLayerEntryConfig | TypeEsriDynamicLayerEntryConfig} layerConfig The layer entry to configure.
> ```

All layerEntryConfig are no more a type but a class, the Type has been remove from the name
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 240 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885#-NruHNCj93ZGRySmuue-:-NruHNCj93ZGRySmuue0:b19o5zq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e850776734bf7349e0314f735f7b4a4dc1c3001/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L240)):*
> ```XML
>       layerConfig.layerStatus = 'error';
>       throw new Error(
>         `The config whose layer path is ${layerPath} cannot set a layer as queryable because it does not have field definitions`
> ```

Do you have a sample url to test
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 296 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885#-NruHZrB3VWk3uV4TmpN:-NruHZrB3VWk3uV4TmpO:b-kou4yz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e850776734bf7349e0314f735f7b4a4dc1c3001/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L296)):*
> ```XML
>  *
>  * @param {EsriDynamic | EsriFeature | EsriImage} this The ESRI layer instance pointer.
>  * @param {TypeEsriFeatureLayerEntryConfig | TypeEsriDynamicLayerEntryConfig} layerConfig The layer entry to configure.
> ```

All layerEntryConfig are no more a type but a class, the Type has been remove from the name

EsriImageLayerEntryConfig has been added by Damon to be able to reuse functions for esri image
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 359 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885#-NruI51nBNP2FhO-M5jp:-NruI51o0J5Xsgh6AB2m:b-wghqks) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e850776734bf7349e0314f735f7b4a4dc1c3001/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L359)):*
> ```XML
>           if (renderer) layerConfig.style = getStyleFromEsriRenderer(renderer);
>         }
>         this.processFeatureInfoConfig(layerConfig as EsriDynamicLayerEntryConfig & EsriFeatureLayerEntryConfig & EsriImageLayerEntryConfig);
> ```

Is it as ... & ... & .... Should it be as ... | ... | ...?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 360 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885#-NruIF_m7-BRvElgIVon:-NruIF_m7-BRvElgIVoo:b-wghqks) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e850776734bf7349e0314f735f7b4a4dc1c3001/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L360)):*
> ```XML
>         }
>         this.processFeatureInfoConfig(layerConfig as EsriDynamicLayerEntryConfig & EsriFeatureLayerEntryConfig & EsriImageLayerEntryConfig);
>         this.processInitialSettings(layerConfig as EsriDynamicLayerEntryConfig & EsriFeatureLayerEntryConfig & EsriImageLayerEntryConfig);
> ```

Is it as ... & ... & .... Should it be as ... | ... | ...?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 194 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885#-NruLAg62lnZO19rhfpT:-NruLAg62lnZO19rhfpU:b13v7er) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e850776734bf7349e0314f735f7b4a4dc1c3001/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L194)):*
> ```XML
>    * This method verifies if the layer is queryable and sets the outfields and aliasFields of the source feature info.
>    *
>    * @param {TypeEsriDynamicLayerEntryConfig} layerConfig The layer entry to configure.
> ```

All layerEntryConfig are no more a type but a class, the Type has been remove from the name
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 204 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885#-NruLCJJ0DH3NihpW6_d:-NruLCJJ0DH3NihpW6_e:b13v7er) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e850776734bf7349e0314f735f7b4a4dc1c3001/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L204)):*
> ```XML
>    *
>    * @param {EsriDynamic} this The ESRI layer instance pointer.
>    * @param {TypeEsriDynamicLayerEntryConfig} layerConfig The layer entry to configure.
> ```

All layerEntryConfig are no more a type but a class, the Type has been remove from the name
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts` line 257 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885#-NruLX7R9dXexJZi2mq5:-NruLX7R9dXexJZi2mq6:b13v7er) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e850776734bf7349e0314f735f7b4a4dc1c3001/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts#L257)):*
> ```XML
>    * This method verifies if the layer is queryable and sets the outfields and aliasFields of the source feature info.
>    *
>    * @param {TypeEsriImageLayerEntryConfig} layerConfig The layer entry to configure.
> ```

All layerEntryConfig are no more a type but a class, the Type has been remove from the name
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/csv.ts` line 146 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885#-NruLecU2RmfKhMAYEZP:-NruLecU2RmfKhMAYEZQ:b-w2hqc5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/dcced26fc6ac6e51d0e8ae74ebb17d66aa8c63c6/packages/geoview-core/src/geo/layer/geoview-layers/vector/csv.ts#L146)):*
> ```XML
>    * Metadata is processed when parsing the file.
>    *
>    * ! This routine must imperatively ends with layerConfig.layerStatus = 'processed' or 'error' if an error happens.
> ```

This was part of your last PR when you changed stuff related to layerStatus. We need to make sure code we add is there to stay.... adding/removing means we were unsure in the architecture and needed more thinking to implement...
___
*[`packages/geoview-core/src/geo/renderer/esri-renderer.ts` line 347 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885#-NruMNOvDyMW-k8W1Qmp:-NruMNOvDyMW-k8W1Qmq:b-luqcdt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8e850776734bf7349e0314f735f7b4a4dc1c3001/packages/geoview-core/src/geo/renderer/esri-renderer.ts#L347)):*
> ```XML
> function convertEsriColor(color: TypeEsriColor): string {
>   if (color) return asString([color[0], color[1], color[2], color[3] / 255]);
>   return 'rgba(0,0,0,0)';
> ```

This color is transparent... We will not be able to see there is a problem. We may want to put red or at least a logger warning to say we are unable to convert the color

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885)* status: all files reviewed, 11 unresolved discussions (waiting on @ychoquet)

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885)* status: 9 of 14 files reviewed, 11 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/csv.ts` line 146 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885#-NruLecU2RmfKhMAYEZP:-NrusWWWC7k5SPQofehj:b-x0q8if) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/dcced26fc6ac6e51d0e8ae74ebb17d66aa8c63c6/packages/geoview-core/src/geo/layer/geoview-layers/vector/csv.ts#L146)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I don't understand your comment. Can you provide me more information?
</blockquote></details>

Ok, now I understand. I took a not and I'll cover that in the refactoring.

**Review by jolevesq — APPROVED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1885)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
