### PR TITLE
core(schema): Add schema to geoview-core package

### LINKED ISSUE #289: Create a configuration schema for geoview-core
For the RAMP viewer, we have an extensive configuration schema that contains every pieces of configuration. For GeoView, we will use a more modular approach. Each packages and plugins will have their own schema and default configuration.

For example, we can override default configuration for our overview map from a config file if provided.

This issue is related to #221 as each component would need such schema. We will start by geoview-core.

Old schema: https://github.com/fgpv-vpgf/fgpv-vpgf/blob/master/packages/ramp-core/schema.json

Currently we have only a basic configuration, it is a starting point:
```
<div
    id="mapLCC"
    class="llwp-map"
    data-leaflet="{ 'projection': 3978, 'zoom': 12, 'center': [45,-75], 'language': 'fr-CA', 'basemapOptions': { 'id': 'transport', 'shaded': true, 'labeled': true }, layers:[] }"
></div>
```

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #289

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303)

### CODE REVIEW

**Review by yass0016 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[packages/geoview-core/schema.json, line 476 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303#-Mwb6LI--GA5E3NylcGf:-Mwb6LI--GA5E3NylcGg:b-7e0gxv) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c82c66abd74963bcebe85f8078e0aaa78e0e743d/packages/geoview-core/schema.json#L476)):*
> ```JSON
>         },
> 
>         "legendPanel": {
> ```

Is this only a placeholder for now? should we have this schema in the legend panel package?
___
*[packages/geoview-core/schema.json, line 515 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303#-Mwb6_K-AOkpq_S13rhj:-Mwb6_K-AOkpq_S13rhk:b4ycuxk) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c82c66abd74963bcebe85f8078e0aaa78e0e743d/packages/geoview-core/schema.json#L515)):*
> ```JSON
>             "additionalProperties": false
>         },
>         "searchService": {
> ```

Same for this as the legend panel
___
*[packages/geoview-core/schema.json, line 562 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303#-Mwb6rHf-6s3klyD0cuM:-Mwb6rHf-6s3klyD0cuN:b77sik0) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c82c66abd74963bcebe85f8078e0aaa78e0e743d/packages/geoview-core/schema.json#L562)):*
> ```JSON
>             "items": {
>                 "type": "string",
>                 "enum": ["appbar", "navbar", "overview-map", "basemap-switcher", "layers", "details", "about", "geolocator"]
> ```

I think some of these are considered packages and some core components, maybe we need a new object in this schema for coreComponents and we can keep this for the packages like overview-map, basemap-switcher
___
*[packages/geoview-core/schema.json, line 568 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303#-Mwb74fMBWqIvpc0ByRL:-Mwb6D2j861P69iGW2jq:b-5ur76) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c82c66abd74963bcebe85f8078e0aaa78e0e743d/packages/geoview-core/schema.json#L568)):*
> ```JSON
>             "minItems": 0
>         },
>         "plugins": {
> ```

Should we keep plugins? I was thinking to simply name all plugins as packages

**Review by yass0016 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303)* status: all files reviewed, 4 unresolved discussions (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303)* status: all files reviewed, 4 unresolved discussions (waiting on @yass0016)

___
*[packages/geoview-core/schema.json, line 476 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303#-Mwb6LI--GA5E3NylcGf:-Mwb7eAW8gEJ_a-L_DVB:b-49x3re) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c82c66abd74963bcebe85f8078e0aaa78e0e743d/packages/geoview-core/schema.json#L476)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Is this only a placeholder for now? should we have this schema in the legend panel package?
</blockquote></details>

You are right, I create a schema in a packages folder and move content. Will create one for details parser needed by details panel and see how I can link them from different packages.
___
*[packages/geoview-core/schema.json, line 515 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303#-Mwb6_K-AOkpq_S13rhj:-Mwb8YJF0fXj1u4wweVk:b1tiltl) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c82c66abd74963bcebe85f8078e0aaa78e0e743d/packages/geoview-core/schema.json#L515)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Same for this as the legend panel
</blockquote></details>

You are right, I create a schema in a packages folder (not already there) and move content
___
*[packages/geoview-core/schema.json, line 562 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303#-Mwb6rHf-6s3klyD0cuM:-Mwb7pN742yJDlZAsNeh:bbjbpep) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c82c66abd74963bcebe85f8078e0aaa78e0e743d/packages/geoview-core/schema.json#L562)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

I think some of these are considered packages and some core components, maybe we need a new object in this schema for coreComponents and we can keep this for the packages like overview-map, basemap-switcher
</blockquote></details>

Good idea, I will create 2 types of object, one for core and one for package.
___
*[packages/geoview-core/schema.json, line 568 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303#-Mwb74fMBWqIvpc0ByRL:-Mwb7v-9A9n8xbcm2XAa:bkrpv2) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c82c66abd74963bcebe85f8078e0aaa78e0e743d/packages/geoview-core/schema.json#L568)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Should we keep plugins? I was thinking to simply name all plugins as packages
</blockquote></details>

Plugins is just a string with plugins needed to initialize on the map. For the moment in RAMP we have rv-plugin on the div. Do we keep it on the div or put in config so easier to modify? But to have plugin you need to edit html for script tag... or we have object plugins with url and we load on the fly. Any idea?

**Review by yass0016 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[packages/geoview-core/schema.json, line 568 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303#-Mwb74fMBWqIvpc0ByRL:-MwbA8kB2VyB8XifoX9M:b-g8z7v) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c82c66abd74963bcebe85f8078e0aaa78e0e743d/packages/geoview-core/schema.json#L568)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Plugins is just a string with plugins needed to initialize on the map. For the moment in RAMP we have rv-plugin on the div. Do we keep it on the div or put in config so easier to modify? But to have plugin you need to edit html for script tag... or we have object plugins with url and we load on the fly. Any idea?
</blockquote></details>

Currently we also have plugins in the div and like you said we have to edit the html to include the plugin in a script tag, I was thinking of renaming plugins in the div to packages. It will load either packages developed by us that is in the monorepo and external packages.

For the point of loading it by providing the url in the packages object, its a good idea, it will no longer be dependent for the user to modify an HTML page, they can simply provide the config and we load that and inject the script tags. Maybe its something we can add when I work on issue #8

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303)* status: all files reviewed, 1 unresolved discussion (waiting on @yass0016)

___
*[packages/geoview-core/schema.json, line 568 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303#-Mwb74fMBWqIvpc0ByRL:-MwbChU412DxafXcRWTx:b-8m5gui) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c82c66abd74963bcebe85f8078e0aaa78e0e743d/packages/geoview-core/schema.json#L568)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Currently we also have plugins in the div and like you said we have to edit the html to include the plugin in a script tag, I was thinking of renaming plugins in the div to packages. It will load either packages developed by us that is in the monorepo and external packages.

For the point of loading it by providing the url in the packages object, its a good idea, it will no longer be dependent for the user to modify an HTML page, they can simply provide the config and we load that and inject the script tags. Maybe its something we can add when I work on issue #8 

</blockquote></details>

Should we have in the schema
```
coreComponents... (array of enum for enable components)
corePackages... (array of enum for enable core packages)
outsidePackages... (array of object name, URL script and URL CSS). At  run time loop the array and inject.
```

This way we keep or div clean. Does this way of doing may have major impact on load time since we need to read the file before we load?

**Review by yass0016 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @yass0016)

___
*[packages/geoview-core/schema.json, line 476 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303#-Mwb6LI--GA5E3NylcGf:-Mwc6RDF0Vu95cxAdjjQ:bb6un1j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c82c66abd74963bcebe85f8078e0aaa78e0e743d/packages/geoview-core/schema.json#L476)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You are right, I create a schema in a packages folder and move content. Will create one for details parser needed by details panel and see how I can link them from different packages.
</blockquote></details>

Done
___
*[packages/geoview-core/schema.json, line 515 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303#-Mwb6_K-AOkpq_S13rhj:-Mwc6Q083cic1k16iSSJ:bb6un1j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c82c66abd74963bcebe85f8078e0aaa78e0e743d/packages/geoview-core/schema.json#L515)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

You are right, I create a schema in a packages folder (not already there) and move content
</blockquote></details>

Done
___
*[packages/geoview-core/schema.json, line 568 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303#-Mwb74fMBWqIvpc0ByRL:-Mwc6aHK3Y_vykNdX1yV:b-yczkmy) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/c82c66abd74963bcebe85f8078e0aaa78e0e743d/packages/geoview-core/schema.json#L568)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Good! I will do the modification later today and push my a new version/
</blockquote></details>

Please check if modification make sense

**Review by yass0016 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @jolevesq and @yass0016)

___
*[packages/geoview-core/schema.json, line 476 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303#-Mwc7t_e3UATLudvcWAw:-Mwc7t_e3UATLudvcWAx:b-35fzv4) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8c7dfc054512abdbbff0abd868c6e16890aedd31/packages/geoview-core/schema.json#L476)):*
> ```JSON
>         },
> 
>         "appBar": {
> ```

Should the properties for a specefic component be in the root of the schema or should we move it inside the components object below? Not sure whats the best way when it comes to parsing the schema for components

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @yass0016)

___
*[packages/geoview-core/schema.json, line 476 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303#-Mwc7t_e3UATLudvcWAw:-MwcLzZ36vwGHNvtOJ29:b7vl35b) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8c7dfc054512abdbbff0abd868c6e16890aedd31/packages/geoview-core/schema.json#L476)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Should the properties for a specefic component be in the root of the schema or should we move it inside the components object below? Not sure whats the best way when it comes to parsing the schema for components
</blockquote></details>

I think make it at the root will let the component array cleaner. Or we can let go of component array and have a Boolean on each component for enable disable.

What I like with separation is you can even skip the whole section of component  and add to the array for default behavior.

**Review by jolevesq — COMMENTED** [review]
Before we merge I will put a key object for layers. It is part of #8 I think. We need to be able to load layer by their metedata key.

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303#-:-MwcWb6I9t6QroRutL4U:bjlklk4)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @yass0016)

**Review by yass0016 — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by yass0016 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by yass0016 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/303)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
