### PR TITLE
feat(feature-info): Create a new panel demo page and recreate details…

### LINKED ISSUE #1144: [FEATURE] Raw Detail Component
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

As a developer, I would like to be able to build raw detail to easily asses problem and performance.

### Implementation UI

Create fake FeatureInfoLayer object on details panel page to select and create details standalone component from. Put result in div 400px, 800px and 1200px to test css responsiveness.

Create a brand new details component to accomplish this. Once ready, it will replace the one we have.

### PR DESCRIPTION
**Pull request by jolevesq**
… as feature info from small to big

Closes #1144

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

New page to test details (feature info) component. It is part of a refactoring from the details component. This is the first step (page, new basic component and fake data). Once optimized, we will create the panel structure around it and at the end we will link it with the map and layer set.

Fixes #1144

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
I created a new page where I use the api function to create components from fake GetFeatureInfo LayerSet structure object.

https://jolevesq.github.io/geoview/raw-feature-info.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1147)

### CODE REVIEW

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1147)* status: all files reviewed, 3 unresolved discussions (waiting on @amir-azma, @cphelefu, @jolevesq, @kaminderpal, and @ychoquet)

___
*[`packages/geoview-core/src/core/components/feature-info/feature-info.tsx` line 101 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1147#-N_5MXfG70Oa9U2HFqwX:-N_5MXfG70Oa9U2HFqwY:b-11jfk2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3f0d59685af5f21672c3f86ca764fcd93ddda5ab/packages/geoview-core/src/core/components/feature-info/feature-info.tsx#L101)):*
> ```XML
> 
>   // lightbox component state
>   const [isLightboxOpen, setIsLighboxOpen] = useState(false);
> ```

setIsLighBoxOpen > setIsLightBoxOpen  (missing t)
___
*[`packages/geoview-core/src/core/components/feature-info/feature-info.api.ts` line 25 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1147#-N_5NEeqC0nh3vhO1WZ1:-N_5NEer9yCtUQ6tYkGT:b-at9jl8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3f0d59685af5f21672c3f86ca764fcd93ddda5ab/packages/geoview-core/src/core/components/feature-info/feature-info.api.ts#L25)):*
> @param {string} mapId
___
*[`packages/geoview-core/src/core/components/feature-info/feature-info.api.ts` line 30 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1147#-N_5NR3fBDS633HySnuN:-N_5NR3fBDS633HySnuO:b-8nd5a6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3f0d59685af5f21672c3f86ca764fcd93ddda5ab/packages/geoview-core/src/core/components/feature-info/feature-info.api.ts#L30)):*
> ```XML
>     this.mapId = mapId;
> 
>     // the featureInfoLayerSet can be use to automatically build the components on map click
> ```

*used

**Review by ychoquet — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1147)* status: all files reviewed, 3 unresolved discussions (waiting on @amir-azma, @cphelefu, @jolevesq, and @kaminderpal)

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1147)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @amir-azma, @cphelefu, @DamonU2, and @kaminderpal)

___
*[`packages/geoview-core/src/core/components/feature-info/feature-info.tsx` line 101 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1147#-N_5MXfG70Oa9U2HFqwX:-N_5anULEn5XjRqmPJ-C:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3f0d59685af5f21672c3f86ca764fcd93ddda5ab/packages/geoview-core/src/core/components/feature-info/feature-info.tsx#L101)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

setIsLighBoxOpen > setIsLightBoxOpen  (missing t)
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/feature-info/feature-info.api.ts` line 25 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1147#-N_5NEeqC0nh3vhO1WZ1:-N_5ao0z1veeKvXRkgmu:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3f0d59685af5f21672c3f86ca764fcd93ddda5ab/packages/geoview-core/src/core/components/feature-info/feature-info.api.ts#L25)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

> @param {string} mapId
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/feature-info/feature-info.api.ts` line 30 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1147#-N_5NR3fBDS633HySnuN:-N_5aoQ42DRtb4OXVV73:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3f0d59685af5f21672c3f86ca764fcd93ddda5ab/packages/geoview-core/src/core/components/feature-info/feature-info.api.ts#L30)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

*used
</blockquote></details>

Done.

**Review by DamonU2 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1147)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @amir-azma, @cphelefu, and @kaminderpal)

**Review by kaminderpal — APPROVED** [review]

**Review by amir-azma — APPROVED** [review]
Looks good

**Review by ychoquet — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1147)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
