### PR TITLE
feat(data-table-icon) Optimization for the icon/canvas thing

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

Small optimization for the icon/canvas thing.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Hosted July 24, 13h45: https://alex-nrcan.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2403)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2403)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/core/components/data-table/data-table.tsx` line 348 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2403#-O2a-1JTCAjTr9ML94wh:-O2a-1JTCAjTr9ML94wi:bpia07c) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/dabc7e166d8e2acaca9e182b352d1c492e56d1fe/packages/geoview-core/src/core/components/data-table/data-table.tsx#L348)):*
> ```XML
>             component="img"
>             src={iconUrl}
>             // alt={iconUrl}
> ```

Should we remove dead code?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1289 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2403#-O2a-5ms4CBcgL5HrGBW:-O2a-5ms4CBcgL5HrGBX:b-kfq0xq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/dabc7e166d8e2acaca9e182b352d1c492e56d1fe/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1289)):*
> ```XML
>       // Will be executed when we have to use a default canvas for a particular feature
>       const callbackToFetchDataUrl = (): Promise<string | null> => {
>         // TODO: Fix - Don't take 'iconImage' below, it's always the same image...
> ```

This TODO is  good becaseu the function is broken. It should return different images but it is not.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2403)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

**Review by DamonU2 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2403)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan)

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2403)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/core/components/data-table/data-table.tsx` line 348 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2403#-O2a-1JTCAjTr9ML94wh:-O2aAbLi2fmnc63JldtG:b-g7oohv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/dabc7e166d8e2acaca9e182b352d1c492e56d1fe/packages/geoview-core/src/core/components/data-table/data-table.tsx#L348)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we remove dead code?
</blockquote></details>

I wasn't sure if it was necessary to have the alt property set, but it does seem to impact performance to have it. If it's not used, I'd remove it. I've now removed the line in this PR.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1289 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2403#-O2a-5ms4CBcgL5HrGBW:-O2aAo3647qdTRjPnsi9:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/dabc7e166d8e2acaca9e182b352d1c492e56d1fe/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1289)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This TODO is  good becaseu the function is broken. It should return different images but it is not.
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2403)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/core/components/data-table/data-table.tsx` line 348 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2403#-O2a-1JTCAjTr9ML94wh:-O2aBDku28oCPnjorlO7:b-isr5xd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/dabc7e166d8e2acaca9e182b352d1c492e56d1fe/packages/geoview-core/src/core/components/data-table/data-table.tsx#L348)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I wasn't sure if it was necessary to have the alt property set, but it does seem to impact performance to have it. If it's not used, I'd remove it. I've now removed the line in this PR.
</blockquote></details>

I think we can remove as the icon is not selectable

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2403)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/data-table/data-table.tsx` line 348 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2403#-O2a-1JTCAjTr9ML94wh:-O2aBWKh1DGYYFs-F8Rf:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/dabc7e166d8e2acaca9e182b352d1c492e56d1fe/packages/geoview-core/src/core/components/data-table/data-table.tsx#L348)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I think we can remove as the icon is not selectable
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2403)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Pull request merged**
