### PR TITLE
fix(demo): Fix demo page from refactor

### LINKED ISSUE #513: Update demo from refactor
With the migration to OpenLayers and the layer strategy and refactor (code + schema), many samples are now broken. We need to revise demo pages and clean them up.

The only file modified so far is layers.html. Take this file as the updated template.

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #513

- - -
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/530)

### CODE REVIEW

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 25 of 51 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/530)* status: 25 of 52 files reviewed, 5 unresolved discussions (waiting on @github-code-scanning[bot], @jolevesq, and @ychoquet)

___
*[`docs/app/loading-maps.md` line 134 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/530#-NCXrTpO2xQLELLeS6dT:-NCXrTpO2xQLELLeS6dU:b6nlzwu) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d7a67b1ef1c8f52c5e01f402645c032ac4e65be0/docs/app/loading-maps.md#L134)):*
> ```Markdown
>                     'corePackages': ['basemap-switcher', 'layers-panel', 'details-panel', 'geolocator'],
>                     'externalPackages': [],
>                     'suportedLanguages': ['en-CA', 'fr-CA']
> ```

When the English and French settings are the same, you can say supportedLanguage=en-CA and only specify the 'en': part of the bilingual fields. The config validation will copy the 'en': value in the 'fr': field. This reduce the length of the configuration.

**Review by ychoquet — COMMENTED** [review]
> Reviewed 25 of 51 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/530)* status: 51 of 52 files reviewed, 5 unresolved discussions (waiting on @jolevesq and @ychoquet)

**Review by ychoquet — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/530)* status: all files reviewed, 5 unresolved discussions (waiting on @jolevesq)

**Review by ychoquet — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/530)* status: all files reviewed, 4 unresolved discussions (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/530)* status: all files reviewed, 4 unresolved discussions (waiting on @github-code-scanning[bot])

___
*[`packages/geoview-core/public/templates/vector.html` line 199 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/530#-NCVjcsWzYoSoK0kOY0M-r1-199:-NC_-LNg3po7tAzpWwia:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8b9be16d093eb2c5eeff834640b70e3db4a19cf3/packages/geoview-core/public/templates/vector.html#L199)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## DOM text reinterpreted as HTML

[DOM text](1) is reinterpreted as HTML without escaping meta-characters.

[Show more details](https://github.com/Canadian-Geospatial-Platform/GeoView/security/code-scanning/34)
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/vector.html` line 209 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/530#-NCVjcsWzYoSoK0kOY0M-r1-209:-NC_-MF7D1GHkIda-F5j:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8b9be16d093eb2c5eeff834640b70e3db4a19cf3/packages/geoview-core/public/templates/vector.html#L209)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## DOM text reinterpreted as HTML

[DOM text](1) is reinterpreted as HTML without escaping meta-characters.

[Show more details](https://github.com/Canadian-Geospatial-Platform/GeoView/security/code-scanning/35)
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/config/reader/url-config-reader.ts` line 68 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/530#-NCVjcsWzYoSoK0kOY0T-r1-68:-NC_-NIg9s7QXevkpd2M:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8b9be16d093eb2c5eeff834640b70e3db4a19cf3/packages/geoview-core/src/core/utils/config/reader/url-config-reader.ts#L68)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Incomplete string escaping or encoding

This replaces only the first occurrence of '{{'.

[Show more details](https://github.com/Canadian-Geospatial-Platform/GeoView/security/code-scanning/36)
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/config/reader/url-config-reader.ts` line 68 at r2](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/530#-NCVjcsWzYoSoK0kOY0T-r2-68:-NC_-Neo10_II8mNmEaX:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/a84d36c767b9950cb9957a86d5e7e2e428c1bada/packages/geoview-core/src/core/utils/config/reader/url-config-reader.ts#L68)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Incomplete string escaping or encoding

This replaces only the first occurrence of /{{/.

[Show more details](https://github.com/Canadian-Geospatial-Platform/GeoView/security/code-scanning/37)
</blockquote></details>

Done.

**Review by ychoquet — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/530)* status: all files reviewed, 4 unresolved discussions (waiting on @github-code-scanning[bot])

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Dismissed @github-code-scanning[bot] from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/530)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by ychoquet — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/530)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/public/templates/vector.html` line 214 at r3](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/530#-NC_dQi730y5QGvxVPdc:-NC_dQi730y5QGvxVPdd:bb6un1j) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/d7a67b1ef1c8f52c5e01f402645c032ac4e65be0/packages/geoview-core/public/templates/vector.html#L214)):*
> ```HTML
>   </script>
> </body>
> ```

Done

**Review by ychoquet — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/530)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
