### PR TITLE
Adding store functionality

### LINKED ISSUE #1294: [FEATURE] Add use of stores to centralize data and reduce use of APIs (Code setup)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Christopher Phelefu

### User Story

* Add a store (zustand)
* Define architecture and add necessary files needed for us to adopt use of stores in our application.
* Within the code show how store will be adopted and used (modify the code to show how that works).

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by cphelefu**
Closes #1294 

# Description

This code adds the use zustand stores in the application. It modifies a few files as a demostration of how the whole adoption of store will work.

Host URL: https://cphelefu.github.io/geoview/

Fixes # (issue)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [C] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__

# Checklist:

- [X] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [X] I have connected the issues(s) to this PR
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1282)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 16 files at r1, 24 of 27 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1282)* status: 26 of 29 files reviewed, 3 unresolved discussions (waiting on @cphelefu and @DamonU2)

___
*[`packages/geoview-core/src/core/components/crosshair/crosshair.tsx` line 63 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1282#-NeErMATAJyfhnUKsaZA:-NeErMATAJyfhnUKsaZB:bfuwp6w) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/eb3c90a7403e32c1040bf94ad48b42f05b575483/packages/geoview-core/src/core/components/crosshair/crosshair.tsx#L63)):*
> ```XML
>   const projection = api.projection.projections[api.maps[mapId].currentProjection];
> 
>   // tracks if the last action was done through a keyboard (map navigation) or mouse (mouse movement)
> ```

Keep the message for the isCrosshairsActive const
___
*[`packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx` line 83 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1282#-NeErZQZ81bNHHK1wZXt:-NeErZQZ81bNHHK1wZXu:bv62unh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/655acd948a82198057747953150644fe37d4f9ab/packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx#L83)):*
> ```XML
> export function MousePosition(props: MousePositionProps): JSX.Element {
>   // variable is not used, thus causing an error, commeting it out for later
>   // const isCrosshairsActive = useGeoViewStore((state) => state.isCrosshairsActive);
> ```

Add TODO: for stuff to see later
___
*[`packages/geoview-core/src/geo/map/map.ts` line 391 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1282#-NeErhK_8BkAHQBN8nni:-NeErhK_8BkAHQBN8nnj:b-ya7qeq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/eb3c90a7403e32c1040bf94ad48b42f05b575483/packages/geoview-core/src/geo/map/map.ts#L391)):*
> ```XML
>         });
>         if (allGeoviewLayerReady) {
>           api.event.emit(mapPayload(EVENT_NAMES.MAP.EVENT_MAP_LOADED, this.mapId, this.map));
> ```

We should expose this new state to outside when it is happening. Should we emit from the store like the sample you showed us?

**Review by DamonU2 — APPROVED** [review]
> Reviewed 1 of 16 files at r1, 6 of 27 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1282)* status: all files reviewed, 3 unresolved discussions (waiting on @cphelefu)

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/geo/map/map.ts` line 391 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1282#-NeErhK_8BkAHQBN8nni:-NeFDNlj9gtyLOzYUBx3:b9ze4on) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/eb3c90a7403e32c1040bf94ad48b42f05b575483/packages/geoview-core/src/geo/map/map.ts#L391)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should expose this new state to outside when it is happening. Should we emit from the store like the sample you showed us?
</blockquote></details>

yes, this is already handled in the MapEventProcessor. When mapLoaded it updated - it fires a api event.

**Review by cphelefu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1282)* status: 27 of 29 files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/src/core/components/crosshair/crosshair.tsx` line 63 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1282#-NeErMATAJyfhnUKsaZA:-NeFDBFm0SCe0-0YWrgL:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/eb3c90a7403e32c1040bf94ad48b42f05b575483/packages/geoview-core/src/core/components/crosshair/crosshair.tsx#L63)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Keep the message for the isCrosshairsActive const
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx` line 83 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1282#-NeErZQZ81bNHHK1wZXt:-NeFDCsaAgAfgad-4WfP:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/655acd948a82198057747953150644fe37d4f9ab/packages/geoview-core/src/core/components/mouse-position/mouse-position.tsx#L83)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Add TODO: for stuff to see later
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 27 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1282)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Review by jolevesq — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1282#-:-NeK1VGD5-2GBWlSsdhL:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Review by jolevesq — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1282)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cphelefu)

**Pull request merged**
