### PR TITLE
feat(minimap-toggle) Add a minimap toggle

### LINKED ISSUE #30: Add toggle to minimap
Add a toggle control to be able to collapse and expand the minimap.

### PR DESCRIPTION
**Pull request by yass0016**
Closes #30

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40)* status: 3 of 9 files reviewed, 3 unresolved discussions (waiting on @yass0016)

___
*[package.json, line 45 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40#-MRzPu-d-nE6ZWav8e_A:-MRzPu-d-nE6ZWav8e_B:b-nnefjw) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2dd7d48e82d162890c0d3162bb6fc2f529975a28/package.json#L45)):*
> ```JSON
>     "esri-leaflet": "2.5.1",
>     "esri-leaflet-renderers": "2.0.6",
>     "eventemitter3": "^4.0.7",
> ```

Do you need this. It was added by your previous PR. Should have been added by your rebase?
___
*[src/api/api.ts, line 13 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40#-MRzQHLTDXMSBdyOWTlI:-MRzQHLTDXMSBdyOWTlJ:bfhkama) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8a7183190471c4f24f83ce57db3fd4f3416e5f19/src/api/api.ts#L13)):*
> ```XML
>      * Event triggered when when the overview map is toggled
>      */
>     EVENT_OVERVIEW_MAP_TOGGLE: 'overview_map_toggle',
> ```

Should not be more overviewmap/toggle to keep same formatting has map/moveend?
___
*[src/components/mapctrl/overview-map.tsx, line 92 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40#-MRzR5ny9JM8E5C_5CKf:-MRzR5ny9JM8E5C_5CKg:b7div4z) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8a7183190471c4f24f83ce57db3fd4f3416e5f19/src/components/mapctrl/overview-map.tsx#L92)):*
> ```XML
>     return (
>         <div ref={divRef} className={LEAFLET_POSITION_CLASSES.topright}>
>             <IconButton
> ```

The icon button stays in grey after click. We should put the same background as other button because it is hard to see with basemap under (check LCC). The minimap and tbutton should. have the same right margin as the navbar button. We can also use something similar to this: https://jolevesq.github.io/contributed-plugins/swiper/samples/swiper-index.html?sample=1

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40)* status: 3 of 9 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[package.json, line 45 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40#-MRzPu-d-nE6ZWav8e_A:-MRzT3zTAwu8D7keFvDz:bqmpti8) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2dd7d48e82d162890c0d3162bb6fc2f529975a28/package.json#L45)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do you need this. It was added by your previous PR. Should have been added by your rebase?
</blockquote></details>

Yes, it should of been rebased, will it cause any conflict?
___
*[src/api/api.ts, line 13 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40#-MRzQHLTDXMSBdyOWTlI:-MRzT-3GAA06cbRp17WQ:b-m11nia) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8a7183190471c4f24f83ce57db3fd4f3416e5f19/src/api/api.ts#L13)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should not be more overviewmap/toggle to keep same formatting has map/moveend?
</blockquote></details>

Yup you are right
___
*[src/components/mapctrl/overview-map.tsx, line 92 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40#-MRzR5ny9JM8E5C_5CKf:-MRzTbKq493W_QCe03PM:b-jx5qxn) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8a7183190471c4f24f83ce57db3fd4f3416e5f19/src/components/mapctrl/overview-map.tsx#L92)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The icon button stays in grey after click. We should put the same background as other button because it is hard to see with basemap under (check LCC). The minimap and tbutton should. have the same right margin as the navbar button. We can also use something similar to this: https://jolevesq.github.io/contributed-plugins/swiper/samples/swiper-index.html?sample=1
</blockquote></details>

I looked a lot for this icon on material ui yesterday, do you know which icon is it? are they creating a custom icon? I will try to make it a button with background

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[package.json, line 45 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40#-MRzPu-d-nE6ZWav8e_A:-MRzV3nYAZpQG-lYqpvI:b1pd827) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2dd7d48e82d162890c0d3162bb6fc2f529975a28/package.json#L45)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Yes, it should of been rebased, will it cause any conflict?
</blockquote></details>

It is weird that it is the only thing. Can you check inside your toggle minimap branch of code from the event is there? If so, maybe just put back the eventemiter inside your package.json will solve the problem.
___
*[src/components/mapctrl/overview-map.tsx, line 92 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40#-MRzR5ny9JM8E5C_5CKf:-MRzVjyF9flEwVf_W7FH:b-qpkni0) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8a7183190471c4f24f83ce57db3fd4f3416e5f19/src/components/mapctrl/overview-map.tsx#L92)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

I looked a lot for this icon on material ui yesterday, do you know which icon is it? are they creating a custom icon? I will try to make it a button with background
</blockquote></details>

It is chevron with a rotation (https://material-ui.com/components/material-icons/)

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[package.json, line 45 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40#-MRzPu-d-nE6ZWav8e_A:-MRzk03c32Y5eIwtHE3W:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/2dd7d48e82d162890c0d3162bb6fc2f529975a28/package.json#L45)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It is weird that it is the only thing. Can you check inside your toggle minimap branch of code from the event is there? If so, maybe just put back the eventemiter inside your package.json will solve the problem.
</blockquote></details>

Done.
___
*[src/api/api.ts, line 13 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40#-MRzQHLTDXMSBdyOWTlI:-MRzk2-zCv3Ywkw-0-Xy:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8a7183190471c4f24f83ce57db3fd4f3416e5f19/src/api/api.ts#L13)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Yup you are right
</blockquote></details>

Done.
___
*[src/components/mapctrl/overview-map.tsx, line 92 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40#-MRzR5ny9JM8E5C_5CKf:-MRzsCMm0NQwhE-1QS-w:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/8a7183190471c4f24f83ce57db3fd4f3416e5f19/src/components/mapctrl/overview-map.tsx#L92)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It is chevron with a rotation (https://material-ui.com/components/material-icons/)
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 5 files at r2, 6 of 6 files at r3, 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40#-:-MRzuAvp0dzI3CkOxcQP:bg7igkv)* status: 4 of 8 files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40)* status: 4 of 8 files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @jolevesq and @yass0016)

___
*[src/components/mapctrl/overview-map.tsx, line 24 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40#-MRzv5is0nFvi0his1rJ:-MRzv5is0nFvi0his1rK:b-1tahtr) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ba0db52ca1df600981cc8530c60f807ce872de4c/src/components/mapctrl/overview-map.tsx#L24)):*
> ```XML
> 
> const TOGGLE_BTN_SIZE = {
>     width: '35px',
> ```

Can this be same size as other button and be part of theme?
___
*[src/components/mapctrl/overview-map.tsx, line 223 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40#-MRzuXm36eLlvQFSG4f9:-MRzuXm36eLlvQFSG4fA:bmldl22) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ba0db52ca1df600981cc8530c60f807ce872de4c/src/components/mapctrl/overview-map.tsx#L223)):*
> ```XML
>                     console.log(theme.spacing(3));
> 
>                     cgpMap.getContainer().parentElement.style.margin = theme.spacing(3) + 'px';
> ```

Could you use string literal (https://www.javascripttutorial.net/es6/javascript-template-literals/). `${theme.spacing(3)px`.

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[src/components/mapctrl/overview-map.tsx, line 24 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40#-MRzv5is0nFvi0his1rJ:-MRzyYXtD2CNYeGVtT0M:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ba0db52ca1df600981cc8530c60f807ce872de4c/src/components/mapctrl/overview-map.tsx#L24)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can this be same size as other button and be part of theme?
</blockquote></details>

Done.
___
*[src/components/mapctrl/overview-map.tsx, line 223 at r4](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40#-MRzuXm36eLlvQFSG4f9:-MRzyZlp36TA7bI70xQz:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/ba0db52ca1df600981cc8530c60f807ce872de4c/src/components/mapctrl/overview-map.tsx#L223)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Could you use string literal (https://www.javascripttutorial.net/es6/javascript-template-literals/). `${theme.spacing(3)px`.
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/40#-:-MRzzGBk7k4_TZXl-dHg:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
