### PR TITLE
feat(internal-plugin) Added the ability to load a plugin internal fro…

### LINKED ISSUE #162: Create a way to load plugins as part of the core viewer
Currently we can load plugins as a vanilla javascript file from outside the viewer and we can't bundle it with the core viewer. Create a way to integrate and load plugins from the core viewer without impacting the size of the bundle and the performance of the viewer. 
Use Code Splitting / Lazy loading for this

https://reactjs.org/docs/code-splitting.html

### PR DESCRIPTION
**Pull request by yass0016**
…m the viewer

Closes #162

## Checklist

* [ ] Commit message follow the guidelines
* [ ] PR targets the correct release version
* [ ] Deploy has been done
* [ ] Check styling
* [ ] _Help files and documentation have been updated_
* [ ] ~Release notes have been updated~

## What's to look for styling
* Use camelCase for identifier names (variables and functions)
* Use PascalCase for type names
* Do not use "I" as a prefix for interface names
* Do not export types/functions unless you need to share it across multiple components
* All names start with a letter
* Always put spaces around operators ( = + - * / ), and after colon:
* Remove all trailing white spaces
* Look for bad indentation
* Carriage return are mandatory
  * Before comments
  * Before if condition
  * After if condition
  * Before properties
  * Before classes
  * Before functions

The use of Prettier Visual Studio Code extension let's you format automatically your code to remove most of the styling issues like white space and indentation.

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/166)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/166)* status: all files reviewed, 1 unresolved discussion (waiting on @yass0016)

___
*[src/api/plugin.ts, line 36 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/166#-MWZTzX88B_EwC5N-HaB:-MWZTzX9798hW4HtQtFz:bc1bfu) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/3faf03c2e8f926e5515c705e13c8d0f63d7a13e5/src/api/plugin.ts#L36)):*
> ```XML
>      */
>     loadInternalPlugins = () => {
>         this.addPlugin('test-plugin', null, {
> ```

This is hardcoded value, will you remove it with the next issue.... make details modular?

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/166)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[src/api/plugin.ts, line 36 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/166#-MWZTzX88B_EwC5N-HaB:-MWZVSyG70RbNMdKE8IG:b8jc0hx) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/3faf03c2e8f926e5515c705e13c8d0f63d7a13e5/src/api/plugin.ts#L36)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

This is hardcoded value, will you remove it with the next issue.... make details modular?
</blockquote></details>

This id has to always match the folder name of the plugin under src/plugins since its internal, we access it this way.

const InstanceConstructor = (await import(`../plugins/${id}/index.ts`)).default;

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/166)* status: all files reviewed, 1 unresolved discussion (waiting on @yass0016)

___
*[src/api/plugin.ts, line 36 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/166#-MWZTzX88B_EwC5N-HaB:-MWZW4qo5Oubp6oz4y8h:bxtkmay) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/3faf03c2e8f926e5515c705e13c8d0f63d7a13e5/src/api/plugin.ts#L36)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

This id has to always match the folder name of the plugin under src/plugins since its internal, we access it this way.

const InstanceConstructor = (await import(`../plugins/${id}/index.ts`)).default;
</blockquote></details>

Should it be pass as argument to the function and not hardcoded? Same for mapId?

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/166)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[src/api/plugin.ts, line 36 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/166#-MWZTzX88B_EwC5N-HaB:-MWZXfw07V17EYuwwXDW:buh8yw3) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/3faf03c2e8f926e5515c705e13c8d0f63d7a13e5/src/api/plugin.ts#L36)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should it be pass as argument to the function and not hardcoded? Same for mapId?
</blockquote></details>

Since we are loading them directly in plugin.ts we know the plugin name (folder name), we dont need to pass it in an argument. Internal plugins should ship with the main branch on the repo. Now if the user from outside want to load the plugin on runtime we might need to have a toolbar or a select option box so they can select and load it

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/166)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[src/api/plugin.ts, line 36 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/166#-MWZTzX88B_EwC5N-HaB:-MWZaf8Z8-CSFPfyTLI7:b-hq9nmh) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/3faf03c2e8f926e5515c705e13c8d0f63d7a13e5/src/api/plugin.ts#L36)):*
<details><summary><i>Previously, yass0016 (Saleh Yassin) wrote…</i></summary><blockquote>

Since we are loading them directly in plugin.ts we know the plugin name (folder name), we dont need to pass it in an argument. Internal plugins should ship with the main branch on the repo. Now if the user from outside want to load the plugin on runtime we might need to have a toolbar or a select option box so they can select and load it
</blockquote></details>

We will do an issue to load plugins passed from map config

**Review by jolevesq — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/166#-:-MWZbXxh0Bf--42ii7jN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yass0016)

**Pull request merged**
