### PR TITLE
BUG=raw-feature-info on load

### LINKED ISSUE #1772: [BUG] raw-feature-info load error
**Is there an existing issue for this?**
No

**Current Behavior**
The raw-feature-info.html has an error on first load.

**Expected Behavior**
A fix must be applied to correct this issue.

**Steps To Reproduce**
1. Load the raw-feature-info.html using the [Basic Details](https://canadian-geospatial-platform.github.io/geoview/public//raw-feature-info.html) link
2. look in the console, there should be an error saying: Uncaught TypeError: Cannot read properties of undefined (reading 'data')

**Anything else?**
No

### PR DESCRIPTION
**Pull request by ychoquet**
# Description

Correction for the load error on raw-feature-info.html template.

Fixes #1772

## Type of change

- x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Using Chrome Devtools to trace and debug..

__Deploy URL__: [Basic Details](https://ychoquet.github.io/GeoView/raw-feature-info.html)

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1773)

### CODE REVIEW

**Comment by ychoquet** [comment]
Closed because bug is still there.

**Comment by ychoquet** [comment]
Found what the bug is

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1773)* status: all files reviewed, 1 unresolved discussion (waiting on @ychoquet)

___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 211 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1773#-Nq90f7l0NrAzuI6CZG-:-Nq90f7l0NrAzuI6CZG0:b-rdifjx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81e7c2424c81aea9113ad7c2ab8d9783b11e5ff7/packages/geoview-core/src/geo/map/map-viewer.ts#L211)):*
> ```XML
>           this.mapFeaturesConfig.map.listOfGeoviewLayerConfig?.length === 0 || Object.keys(geoviewLayers).length !== 0;
>         Object.keys(geoviewLayers).forEach((geoviewLayerId) => {
>           const layerIsReady = geoviewLayers[geoviewLayerId].allLayerStatusAreIn(['processed', 'loading', 'error', 'loaded']);
> ```

Because you are not looking to layer stuck at process, https://ychoquet.github.io/GeoView/all-layers.html did not load

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1773)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/map/map-viewer.ts` line 211 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1773#-Nq90f7l0NrAzuI6CZG-:-NqA7fDR1o3PscBorjYu:b-k1m2ml) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81e7c2424c81aea9113ad7c2ab8d9783b11e5ff7/packages/geoview-core/src/geo/map/map-viewer.ts#L211)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Because you are not looking to layer stuck at process, https://ychoquet.github.io/GeoView/all-layers.html did not load
</blockquote></details>

Let's tackle this intermitent issue in a next PR.

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1773)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1773)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1773)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1773)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
