### PR TITLE
fix(wcag): Fix focus for modal

### LINKED ISSUE #1486: [REFACTOR] Store Appbar and Payload
**Is there an existing issue for this?**
No

**Current Behavior**
AppBar is using api event to add remove component...

**Expected Behavior**
Use the store

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #1486

# Description

Replace library for focus trap by MUI
New implementation of how we deal with modal and focus with keyboard navigation. Focus trap is set from the store and shared across the application
New implantation of focus trap for footer tab content

Fixes #1486

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Open export modal from app bar and nav bar in keyboard navigation mode.
Use keyboard navigation to access footer tab element and open it with keyboard to trap focus inside

https://jolevesq.github.io/geoview/raw-feature-info-1.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1523)

### CODE REVIEW

**Review by kaminderpal — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1523)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @amir-azma, @cphelefu, @DamonU2, @jolevesq, and @mayurmarakana89)

___
*[`packages/geoview-core/src/core/components/export/export-modal-button.tsx` line 18 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1523#-NjwxPjs3XHjSXxlOXOZ:-NjwxPjs3XHjSXxlOXO_:brpwc16) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/58ff01c05e43d3ed398f752a3b996c3165f3c39b/packages/geoview-core/src/core/components/export/export-modal-button.tsx#L18)):*
> ```XML
>  * @returns {JSX.Element} the export button
>  */
> export default function Export(props: ExportProps): JSX.Element {
> ```

Can we rename `Export` to more specific like `ExportButton`

**Comment by cphelefu** [comment]
*[`packages/geoview-core/package.json` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1523#-Njwxgth-OmYifWQrG7C:-Njwxgth-OmYifWQrG7D:b-kripnj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/58ff01c05e43d3ed398f752a3b996c3165f3c39b/packages/geoview-core/package.json#L51)):*
> ```JSON
>     "@emotion/react": "^11.11.0",
>     "@emotion/styled": "^11.11.0",
>     "@mui/base": "5.0.0-beta.24",
> ```

beta library? Is there a reason for this library?
Using beta libraries is really risky as they are still under lots of development

**Comment by cphelefu** [comment]
*[`packages/geoview-core/public/locales/en/translation.json` line 103 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1523#-Njwy-az8EIRuAnQISuY:-Njwy-az8EIRuAnQISuZ:bz2rglu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/58ff01c05e43d3ed398f752a3b996c3165f3c39b/packages/geoview-core/public/locales/en/translation.json#L103)):*
> ```JSON
>       }
>     },
>     "exitFocus": "Exit"
> ```

exit is a common word; I would put this in general with the key 'exit'.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1523)* status: 1 of 24 files reviewed, 3 unresolved discussions (waiting on @amir-azma, @cphelefu, @DamonU2, and @mayurmarakana89)

___
*[`packages/geoview-core/package.json` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1523#-Njwxgth-OmYifWQrG7C:-NjxSHBuAp8hW2X-BgTf:b-57ebls) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/58ff01c05e43d3ed398f752a3b996c3165f3c39b/packages/geoview-core/package.json#L51)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

beta library? Is there a reason for this library?
Using beta libraries is really risky as they are still under lots of development
</blockquote></details>

You are right, it is not fully done: https://github.com/mui/material-ui/milestone/46. The only component we are using is the focus trap who should not be modified a lot.
___
*[`packages/geoview-core/public/locales/en/translation.json` line 103 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1523#-Njwy-az8EIRuAnQISuY:-NjxRQ6rEOiINx-0nH0w:b-n6bjaa) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/58ff01c05e43d3ed398f752a3b996c3165f3c39b/packages/geoview-core/public/locales/en/translation.json#L103)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

exit is a common word; I would put this in general with the key 'exit'.
</blockquote></details>

What would you suggest?

**Review by DamonU2 — APPROVED** [review]
Looks like it fixes #1322 as well

> Reviewed 23 of 24 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1523#-:-NjxT4en3kuwJ3hAnZ9e:b9kldc7)* status: all files reviewed, 3 unresolved discussions (waiting on @amir-azma, @cphelefu, @jolevesq, and @mayurmarakana89)

**Review by jolevesq — COMMENTED** [review]
That is always good when we can close more then one bug at a time

> Reviewed 18 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1523#-:-NjxXLDN-AqDAURGS_FR:b97hhj7)* status: 18 of 24 files reviewed, 3 unresolved discussions (waiting on @amir-azma, @cphelefu, @DamonU2, @kaminderpal, and @mayurmarakana89)

___
*[`packages/geoview-core/src/core/components/export/export-modal-button.tsx` line 18 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1523#-NjwxPjs3XHjSXxlOXOZ:-NjxWunv0fw9ombHovnu:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/58ff01c05e43d3ed398f752a3b996c3165f3c39b/packages/geoview-core/src/core/components/export/export-modal-button.tsx#L18)):*
<details><summary><i>Previously, kaminderpal (Kamy) wrote…</i></summary><blockquote>

Can we rename `Export` to more specific like `ExportButton`
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1523)* status: 19 of 24 files reviewed, 3 unresolved discussions (waiting on @amir-azma, @cphelefu, @DamonU2, @kaminderpal, and @mayurmarakana89)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 4 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1523)* status: 23 of 24 files reviewed, all discussions resolved (waiting on @amir-azma, @cphelefu, @DamonU2, and @mayurmarakana89)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1523)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amir-azma, @cphelefu, and @mayurmarakana89)

**Pull request merged**
