### PR TITLE
#50 basemap switcher plugin

### PR DESCRIPTION
**Pull request by yass0016**
## Checklist

* [ ] Commit message follow the guidelines
* [ ] PR targets the correct release version
* [ ] Deploy has been done
* [ ] Check styling
* [ ] _Help files and documentation have been updated_
* [ ] ~Release notes have been updated~

## What's to look for styling
* Use camelCase for identifier names (variables and functions)
* Use PascalCase for type names
* Do not use "I" as a prefix for interface names
* Do not export types/functions unless you need to share it across multiple components
* All names start with a letter
* Always put spaces around operators ( = + - * / ), and after colon:
* Remove all trailing white spaces
* Look for bad indentation
* Carriage return are mandatory
  * Before comments
  * Before if condition
  * After if condition
  * Before properties
  * Before classes
  * Before functions

The use of Prettier Visual Studio Code extension let's you format automatically your code to remove most of the styling issues like white space and indentation.

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/108)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 19 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/108)* status: 19 of 22 files reviewed, 4 unresolved discussions (waiting on @melzeiny1980 and @yass0016)

___
*[public/locales/fr-CA/translation.json, line 28 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/108#-MUF8AWiC9kmGQTFokKB:-MUF8AWiC9kmGQTFokKC:bg400jc) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/a3a783077cd22b60a92c41e4d80e6f21b637e255/public/locales/fr-CA/translation.json#L28)):*
> ```JSON
>         "share": "Partager",
>         "version": "Accéder au repo sur GitHub",
>         "basemapSwitcher": "fond de carte"
> ```

Put capital F
___
*[public/plugins/basemap/basemap-switcher.js, line 274 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/108#-MUF9kDeBnhIb8PDmaGN:-MUF9kDeBnhIb8PDmaGO:bb1as6k) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/a3a783077cd22b60a92c41e4d80e6f21b637e255/public/plugins/basemap/basemap-switcher.js#L274)):*
> ```JavaScript
>                 }, []);
> 
>                 return h(
> ```

What is this h function?
___
*[public/templates/basemap-switcher.html, line 88 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/108#-MUFATDw7YQ8hAvAbuzZ:-MUFATDw7YQ8hAvAbuz_:butm5at) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/a3a783077cd22b60a92c41e4d80e6f21b637e255/public/templates/basemap-switcher.html#L88)):*
> ```HTML
>                         <td>
>                             This page is used to showcase the basemap switcher plugin. To add a basemap switcher you need to provide the
>                             'basemapSwitcher' property and set it to true in the map config, see config snippet below. If basemap switcher
> ```

There is no mention of basemap-switcher in the config snippet
___
*[src/api/event.ts, line 27 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/108#-MUFAhF-7gzAuBDPd8QO:-MUFAhF-7gzAuBDPd8QP:b-u9e005) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/a3a783077cd22b60a92c41e4d80e6f21b637e255/src/api/event.ts#L27)):*
> ```XML
>      * Event triggered when a new appbar panel has been created
>      */
>     EVENT_APPBAR_PANEL_CREATE: 'appbar/panel_create',
> ```

Why have you replaces the / by _

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/108)* status: 19 of 22 files reviewed, 4 unresolved discussions (waiting on @jolevesq and @melzeiny1980)

___
*[public/locales/fr-CA/translation.json, line 28 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/108#-MUF8AWiC9kmGQTFokKB:-MUFQdm68c1dw0sH4b_M:b-qao8n) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/a3a783077cd22b60a92c41e4d80e6f21b637e255/public/locales/fr-CA/translation.json#L28)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Put capital F
</blockquote></details>

Done, moved this to the plugin's translations
___
*[public/plugins/basemap/basemap-switcher.js, line 274 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/108#-MUF9kDeBnhIb8PDmaGN:-MUF_jIy-FNlUBBcUKuO:b-jh9sp5) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/a3a783077cd22b60a92c41e4d80e6f21b637e255/public/plugins/basemap/basemap-switcher.js#L274)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

What is this h function?
</blockquote></details>

I put some comments, it's also mentioned in the docs
___
*[public/templates/basemap-switcher.html, line 88 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/108#-MUFATDw7YQ8hAvAbuzZ:-MUF_rvjD1KduJXVQ2W3:b-896fix) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/a3a783077cd22b60a92c41e4d80e6f21b637e255/public/templates/basemap-switcher.html#L88)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

There is no mention of basemap-switcher in the config snippet
</blockquote></details>

Done.
___
*[src/api/event.ts, line 27 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/108#-MUFAhF-7gzAuBDPd8QO:-MUFa2_CEZR4raf7YP-r:b-v3zas6) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/a3a783077cd22b60a92c41e4d80e6f21b637e255/src/api/event.ts#L27)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why have you replaces the / by _
</blockquote></details>

To follow the other event names, component/event_name

**Review by jolevesq — APPROVED** [review]
:lgtm:

> Reviewed 1 of 22 files at r1, 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/108#-:-MUFb4zi2KDj6z0ogrbv:bnfp4nl)* status: 18 of 20 files reviewed, all discussions resolved (waiting on @jolevesq and @melzeiny1980)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/108)* status: 19 of 20 files reviewed, all discussions resolved (waiting on @jolevesq and @melzeiny1980)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/108#-:-MUFcNXH0NWNVhzefWrZ:bnfp4nl)* status: 19 of 20 files reviewed, all discussions resolved (waiting on @jolevesq and @melzeiny1980)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/108)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @melzeiny1980)

**Pull request merged**
