### PR TITLE
fix(UI): refactor UI component for performance   #closes2144

### LINKED ISSUE #2144: [Refactor] <Performance of UI Components 1>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Need to enhance the performance of following component's

1. details
2. export
3. footer-bar
4. geolocator
5. guide

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### LINKED ISSUE #2145: [Refactor] <Performance of UI Components 2>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Need to enhance the performance of following UI Components based 

1. Appbar
2. Attribution
3. Click Marker
4. Common
5. Crosshair

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Refactor the below UI component for performance..

1. details
2. export
3. footer-bar
4. geolocator
5. guide
6. Data table

Fixes #2144 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/demos-navigator.html?config=./configs/navigator/07-basic-appbar.json
https://kaminderpal.github.io/geoview/demos-navigator.html?config=./configs/navigator/06-basic-footer.json

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157)

### CODE REVIEW

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/data-table/data-table-type.ts` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NyRkrwF080cfVh9q9vF:-NyRkrwG3lC8DMK2NB07:bixhtyv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/data-table/data-table-type.ts#L1)):*
> ```XML
> import { TypeFieldEntry, TypeLayerData } from '@/geo/layer/layer-sets/abstract-layer-set';
> ```

Since this is multiple types/interfaces I think we can rename to 'data-table-types.ts'

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/data-table/export-button.tsx` line 39 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NyRlMPr2pQZ9ueg3OGc:-NyRlMPr2pQZ9ueg3OGd:bet9c3b) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/data-table/export-button.tsx#L39)):*
> ```XML
>    */
> 
>   const handleClick = useCallback((event: React.MouseEvent<HTMLButtonElement>) => {
> ```

Do need to use useCallback here?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/data-table/export-button.tsx` line 47 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NyRlV0s5w1EEkNlyXT4:-NyRlV0s5w1EEkNlyXT5:b-mtshmt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/data-table/export-button.tsx#L47)):*
> ```XML
>    */
> 
>   const handleClose = useCallback(() => {
> ```

Do we need to use useCallback here?

**Comment by cphelefu** [comment]
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 4 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NyRrd5m55rL81uniVTA:-NyRrd5m55rL81uniVTB:beqtgch) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L4)):*
> ```XML
> import { useTranslation } from 'react-i18next';
> import { useTheme } from '@mui/material/styles';
> import _delay from 'lodash/delay';
> ```

existing code uses`import _ from lodash;` and basically uses it like `_.delay(....)`.
You can follow the same strategy; I am personally also okay with `import { delay } ...`

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 26 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157)* status: 26 of 28 files reviewed, 16 unresolved discussions (waiting on @cphelefu and @kaminderpal)

___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 4 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NyRrd5m55rL81uniVTA:-NyS9YOt2ZVqfSsyhVAI:bex62vt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L4)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

existing code uses`import _ from lodash;` and basically uses it like `_.delay(....)`.
You can follow the same strategy; I am personally also okay with `import { delay } ...`
</blockquote></details>

We ahev one function here import { delay } from '@/core/utils/utilities'; if not ok, can we rework this function so we have one delay function?
___
*[`packages/geoview-core/src/core/components/data-table/hooks/useFeatureFieldInfos.tsx` line 11 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySAR888Sm20vRk5DPv:-NySAR888Sm20vRk5DPw:b-eyg0kn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/data-table/hooks/useFeatureFieldInfos.tsx#L11)):*
> ```XML
>  */
> export function useFeatureFieldInfos(layerData: TypeLayerData[]): MappedLayerDataType[] {
>   const mappedLayerData = useMemo(() => {
> ```

Can you continue to add the logger were you are using useMemo
___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 319 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySAFvj31N1zHLBr1P-:-NySAFvj31N1zHLBr1P0:b-u72z4s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/details/details-panel.tsx#L319)):*
> ```XML
>    * @param {-1 | 1} change The change to index number (-1 for back, 1 for forward)
>    */
>   const handleFeatureNavigateChange = useCallback(
> ```

Can you continue to add the logger were you are using useCallback
___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 335 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySAPaGBNTgnoMu4hwR:-NySAPaGBNTgnoMu4hwS:b-u72z4s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/details/details-panel.tsx#L335)):*
> ```XML
>    * @param {LayerListEntry} layerEntry The data of the newly selected layer
>    */
>   const handleLayerChange = useCallback(
> ```

Can you continue to add the logger were you are using useCallback
___
*[`packages/geoview-core/src/core/components/details/feature-detail-modal.tsx` line 34 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySA_kTCZqv10uRfu6M:-NySA_kTCZqv10uRfu6N:b-eyg0kn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/details/feature-detail-modal.tsx#L34)):*
> ```XML
>    * Build features list to displayed in table
>    */
>   const featureInfoList: TypeFieldEntry[] = useMemo(() => {
> ```

Can you continue to add the logger were you are using useMemo
___
*[`packages/geoview-core/src/core/components/details/feature-info-new.tsx` line 53 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySAd3C16Y0Di4gES05:-NySAd3C16Y0Di4gES06:b-eyg0kn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/details/feature-info-new.tsx#L53)):*
> ```XML
>    * Build feature list to be displayed inside table.
>    */
>   const featureInfoList: TypeFieldEntry[] = useMemo(() => {
> ```

Can you continue to add the logger were you are using useMemo
___
*[`packages/geoview-core/src/core/components/details/feature-info-new.tsx` line 68 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySAevWCurz9uTBXR44:-NySAevWCurz9uTBXR45:b-u72z4s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/details/feature-info-new.tsx#L68)):*
> ```XML
>    * Toggle feature selected.
>    */
>   const handleFeatureSelectedChange = useCallback(
> ```

Can you continue to add the logger were you are using useCallback
___
*[`packages/geoview-core/src/core/components/details/feature-info-table.tsx` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySAigR7QwjyOEeK28I:-NySAigSDSwr1CdFnQV9:b-eyg0kn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/details/feature-info-table.tsx#L37)):*
> ```XML
> 
>   // linkify options
>   const linkifyOptions = useMemo(() => {
> ```

Can you continue to add the logger were you are using useMemo
___
*[`packages/geoview-core/src/core/components/export/export-modal.tsx` line 125 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySB14c6auW3uiccbVe:-NySB14c6auW3uiccbVf:b-ex6fhq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/export/export-modal.tsx#L125)):*
> ```XML
>             .then((dataUrl) => {
>               setIsLegendLoading(false);
>               // Note: When legend is hidden in appbar
> ```

I think legend should always be there. Only layer not visible should be hidden
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 343 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySBAm9D-rN47eGLzb6:-NySBAm9D-rN47eGLzb7:b-u72z4s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L343)):*
> ```XML
> 
>   // Handle focus using dynamic focus button
>   const handleDynamicFocus = useCallback((): void => {
> ```

Can you continue to add the logger were you are using useCallback
___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 31 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySBDRk8o-M-DZIU64l:-NySBDRk8o-M-DZIU64m:b-u72z4s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L31)):*
> ```XML
>    * @returns {string} - tooltip title
>    */
>   const getTooltipTitle = useCallback(({ name, province, category }: tooltipProp): string => {
> ```

Can you continue to add the logger were you are using useCallback
___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySBEM76kgZgsC1JpOQ:-NySBEM76kgZgsC1JpOR:b-u72z4s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L51)):*
> ```XML
>    * @returns {JSX.Element}
>    */
>   const transformListTitle = useCallback((_title: string, _searchValue: string, province: string): JSX.Element | string => {
> ```

Can you continue to add the logger were you are using useCallback
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 80 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySBS-v3u-FNyM3_8-M:-NySBS-v3u-FNyM3_8-N:b-u72z4s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L80)):*
> ```XML
>    * @param {LayerListEntry} layer geoview layer.
>    */
>   const handleGuideItemClick = useCallback(
> ```

Can you continue to add the logger were you are using useCallback

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157)* status: 26 of 28 files reviewed, 16 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/data-table/data-panel.tsx` line 4 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NyRrd5m55rL81uniVTA:-NyVSXcACoFLbiDfcedM:b-ehwr7v) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/data-table/data-panel.tsx#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We ahev one function here import { delay } from '@/core/utils/utilities'; if not ok, can we rework this function so we have one delay function?
</blockquote></details>

@jolevesq existing function is wrapped inside Promise and this function can be used with async and await chaining. In my case i want to clear the timeout too, which can do by using delay from lodash.
@cphelefu i have update my code with ur suggestion.
___
*[`packages/geoview-core/src/core/components/data-table/data-table-type.ts` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NyRkrwF080cfVh9q9vF:-NyVTiVE6j5mZdBEnxzp:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/data-table/data-table-type.ts#L1)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Since this is multiple types/interfaces I think we can rename to 'data-table-types.ts'
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/data-table/data-table-type.ts` line 4 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NyRl1dn6umv_XsEkyen:-NyVTixHChugzId6y4zA:bgc1wve) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/data-table/data-table-type.ts#L4)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

change fieldInfos?: Record<string, TypeFieldEntry>
</blockquote></details>

in my case fieldInfo's will never be `optional` but can be empty object. so i have update the type to Partial.
___
*[`packages/geoview-core/src/core/components/data-table/export-button.tsx` line 39 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NyRlMPr2pQZ9ueg3OGc:-NyVY9x37VzPHMCWUDnr:b6axlt2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/data-table/export-button.tsx#L39)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Do need to use useCallback here?
</blockquote></details>

yes bcz we are passing handleClick as dependency to `IconButton` component.
___
*[`packages/geoview-core/src/core/components/data-table/export-button.tsx` line 47 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NyRlV0s5w1EEkNlyXT4:-NyVYJNm7VgiNohbZGQ0:baajxx6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/data-table/export-button.tsx#L47)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

Do we need to use useCallback here?
</blockquote></details>

yes bcz we are passing handleClick as dependency to `Menu` component.
___
*[`packages/geoview-core/src/core/components/data-table/hooks/useFeatureFieldInfos.tsx` line 11 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySAR888Sm20vRk5DPv:-NyVYNZH99jDlWht9I5Y:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/data-table/hooks/useFeatureFieldInfos.tsx#L11)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you continue to add the logger were you are using useMemo
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 319 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySAFvj31N1zHLBr1P-:-NyVaNMhDkmKPo4HK8_v:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/details/details-panel.tsx#L319)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you continue to add the logger were you are using useCallback
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details/details-panel.tsx` line 335 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySAPaGBNTgnoMu4hwR:-NyVaNbI2lJS5CzKyJkP:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/details/details-panel.tsx#L335)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you continue to add the logger were you are using useCallback
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details/feature-detail-modal.tsx` line 34 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySA_kTCZqv10uRfu6M:-NyVbJx2EnGX3uUqoI9i:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/details/feature-detail-modal.tsx#L34)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you continue to add the logger were you are using useMemo
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details/feature-info-new.tsx` line 68 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySAevWCurz9uTBXR44:-NyVbS107p27H4fFc5ji:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/details/feature-info-new.tsx#L68)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you continue to add the logger were you are using useCallback
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details/feature-info-table.tsx` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySAigR7QwjyOEeK28I:-NyVbXqK4gmh9HfJqz2J:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/details/feature-info-table.tsx#L37)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you continue to add the logger were you are using useMemo
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 343 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySBAm9D-rN47eGLzb6:-NyVbp1q0DSB5eoih-yi:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L343)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you continue to add the logger were you are using useCallback
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 31 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySBDRk8o-M-DZIU64l:-NyVc61i8p1LxAZT9DCq:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L31)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you continue to add the logger were you are using useCallback
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/geolocator/geo-list.tsx` line 51 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySBEM76kgZgsC1JpOQ:-NyVcEVp6laMX5FmFjOK:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/geolocator/geo-list.tsx#L51)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you continue to add the logger were you are using useCallback
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/guide/guide-panel.tsx` line 80 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NySBS-v3u-FNyM3_8-M:-NyVcQP8-PuIi3jh8bWR:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/guide/guide-panel.tsx#L80)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you continue to add the logger were you are using useCallback
</blockquote></details>

Done.

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157)* status: 13 of 29 files reviewed, 13 unresolved discussions (waiting on @cphelefu and @jolevesq)

___
*[`packages/geoview-core/src/core/components/data-table/export-button.tsx` line 39 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-NyRlMPr2pQZ9ueg3OGc:-NyVhr7h4Qva2fPjgLZJ:b-131iio) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/cc67825d26f9bfe0d979866722fdb865cc8f7be1/packages/geoview-core/src/core/components/data-table/export-button.tsx#L39)):*
<details><summary><i>Previously, cphelefu (Christopher Phelefu) wrote…</i></summary><blockquote>

why didnt we live this as just a function? how does it benefit the code?
</blockquote></details>

It will not trigger re render of Icon Button when cache version of dependency is passed.

**Review by cphelefu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-:-NyWCPMQE0OUvWiDUfH3:bnfp4nl)* status: all files reviewed, 13 unresolved discussions (waiting on @jolevesq and @kaminderpal)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 14 of 15 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157)* status: all files reviewed, 1 unresolved discussion (waiting on @cphelefu)

**Review by jolevesq — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2157#-:-NyWI2JV5hEI95_qt3G4:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @cphelefu)

**Pull request merged**
