### PR TITLE
refactor(layers) - Part 9

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

This PR is part of a series of PR and has a dependency on PR https://github.com/Canadian-Geospatial-Platform/geoview/pull/1949

This particular one focuses on rewriting the code for the `QUERY_LEGEND` and `LEGEND_INFO` events.
- Added 2 new class events in abstract-geoview-layers being raised when legend information gets queried and has been queried (both are raised via the queryLegend() method;
- Layer registration principles now take care of wiring on those 2 events;
- Cleaned up old registrations of layer-registering that was forgotten in earlier PR;
- Completely revamped the layer-sets and children classes to simplify the code over there. Using standard OO method overriding mechanisms instead of registering functions.

Side note: In this PR, there is code removed in `esri-layer-common` that I'm not sure of. It didn't seem to be necessary with the new logic mecanisms. To confirm..

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Currently hosting the finally of the layers refactoring here: https://alex-nrcan.github.io/geoview

# Checklist:

- [ ] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 11 of 97 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950)* status: 11 of 97 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 386 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRg4Jm7FXJSpVx70kB:-NtRg4Jm7FXJSpVx70kC:b-835re3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L386)):*
> ```XML
>    * @param {GeoViewLayerLegendQueryingEvent} event The event to emit
>    */
>   emitLegendQuerying = (event: GeoViewLayerLegendQueryingEvent) => {
> ```

Like we discuss in previous PR we should even use a direct call to query legend. This call should be done in the layer process creation and store on the layer object and store.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1006 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRg_bp4zf9PHWN2_8M:-NtRg_bp4zf9PHWN2_8N:b-odrupx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1006)):*
> ```XML
>    * This function raises legend querying and queried events.
>    */
>   queryLegend = async (layerPath: string) => {
> ```

We should just call this function when we need legend and this deal with the layer gathering is legend. We can get ride of the emit quering and emit queried

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950)* status: 11 of 97 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 420 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRhG3tAKHpD8LosDmo:-NtRhG3uEufGJ52GZ_o5:b-8gqmw6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L420)):*
> ```XML
>    * @param {AbstractBaseLayerEntryConfig} layerConfig The layer configurstion associated to the dynamic group.
>    */
>   private createGroupLayer(layer: TypeJsonObject, layerConfig: AbstractBaseLayerEntryConfig) {
> ```

createGroup is the same thing for all the layers type? group is a geoview structure. Should it be handle upper in abstract class to loop in structure and launch the creation of a leaf?

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 97 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950)* status: 12 of 97 files reviewed, 3 unresolved discussions (waiting on @Alex-NRCan)

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950)* status: 12 of 97 files reviewed, 4 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/geo/utils/all-feature-info-layer-set.ts` line 40 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRoaWG4IHfAjSuOEjz:-NtRoaWG4IHfAjSuOEk-:bo9w05y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/utils/all-feature-info-layer-set.ts#L40)):*
> ```XML
>    * @param {string} layerPath The layer path
>    */
>   protected onRegisterLayerCheck = (geoviewLayer: AbstractGeoViewLayer, layerPath: string): boolean => {
> ```

Again this whole thing can only be a direct function call and this thing to see if we can do it should be on layer class itself.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 4 of 97 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950)* status: 17 of 97 files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan)

___
*[`packages/geoview-core/src/geo/utils/hover-feature-info-layer-set.ts` line 96 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRpYWx7MBrD5yFVSnc:-NtRpYWx7MBrD5yFVSnd:bew8yc8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/utils/hover-feature-info-layer-set.ts#L96)):*
> ```XML
>       else {
>         // Call parent. After this call, this.resultSet?.[layerPath]?.layerStatus may have changed!
>         super.onProcessLayerStatusChanged(config, layerPath, layerStatus);
> ```

Same comment as above in feature info
___
*[`packages/geoview-core/src/geo/utils/legends-layer-set.ts` line 44 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRq71U4ZANI8Oq1kIT:-NtRq71U4ZANI8Oq1kIU:b-p0jntq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/utils/legends-layer-set.ts#L44)):*
> ```XML
>    * @param {string} layerPath The layer path
>    */
>   onRegisterLayer = (geoviewLayer: AbstractGeoViewLayer, layerPath: string): void => {
> ```

No need to manage event for legend in my mind, should be direct call and layer set can include in for legend/ui for store propagation
___
*[`packages/geoview-core/src/geo/utils/legends-layer-set.ts` line 82 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRqHLP1p1v6_9Ce_gg:-NtRqHLP1p1v6_9Ce_gh:b-ala0ay) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/utils/legends-layer-set.ts#L82)):*
> ```XML
> 
>     // Call parent. After this call, this.resultSet?.[layerPath]?.layerStatus may have changed!
>     super.onProcessLayerStatusChanged(config, layerPath, layerStatus);
> ```

Same comment no need for status change listener in legend
___
*[`packages/geoview-core/src/geo/utils/legends-layer-set.ts` line 97 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRqOcH2LrPIMHLytYU:-NtRqOcH2LrPIMHLytYV:b-kcw2u) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/utils/legends-layer-set.ts#L97)):*
> ```XML
>       }
> 
>       if (layerExists || layerStatus === 'loaded') {
> ```

Should be a direct function to layer and layer know is status, no need to have this logic. Layer status for parent should be dealt in layer set or layer api.

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed 18 of 97 files at r1, 79 of 79 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950)* status: all files reviewed, 10 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 386 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRg4Jm7FXJSpVx70kB:-NtRmO6d8ucr6nnMyInQ:bxwccfq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L386)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Like we discuss in previous PR we should even use a direct call to query legend. This call should be done in the layer process creation and store on the layer object and store.
</blockquote></details>

I think the legend creation should be done in the validation section at the same time we read the metadata. The legend is part of the metadata. The layer process should only deal with the load/instanciation of the layers on the map.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1006 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRg_bp4zf9PHWN2_8M:-NtRnQ_56odebNPzVJeP:bqog7yy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1006)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should just call this function when we need legend and this deal with the layer gathering is legend. We can get ride of the emit quering and emit queried
</blockquote></details>

Agree!
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 420 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRhG3tAKHpD8LosDmo:-NtRnx6M5czEkkEnSnCD:b-1ulten) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L420)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

createGroup is the same thing for all the layers type? group is a geoview structure. Should it be handle upper in abstract class to loop in structure and launch the creation of a leaf?
</blockquote></details>

This method is part of the validation. It is used during the metadata validation to create groups when the metadata (ESRI, WMS) define a group of layer. a get layerTree method will return the tree of layers to the caller (ex: add-new-layer) to allow the display and selection of layers to be loaded. A method will allow the users to select the layers to be displayed and a getSelectedLayers method will return the tree of layers to load on the map.
___
*[`packages/geoview-core/src/geo/utils/feature-info-layer-set.ts` line 91 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRowqz7Vyg4xucT7dB:-NtRqLwMA9515cE7girx:bndo901) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/utils/feature-info-layer-set.ts#L91)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is it not weird to pass a config to process a layerStatus. I will have to see what this function is really doing. We should not manage layer status for feature info. Only query status. Layer status will be apply to layer-set and propagate to store so ui knows. No need to deal with it twice.
</blockquote></details>

Config is not the entire configuration; it may be a leaf node whose variable name is config. Having said that, it doesn't mean that your comment isn't valid.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts` line 382 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRkoadA1wMjmiKexVX:-NtRkoae2nsL6o3QkKCr:b-kjcvmf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/074f65935ad2f049c8454b0c11659877988a5712/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts#L382)):*
> ```XML
> 
>       if (!bounds) bounds = [transformedBounds[0], transformedBounds[1], transformedBounds[2], transformedBounds[3]];
>       else bounds = getMinOrMaxExtents(bounds, transformedBounds);
> ```

When I rebase my PR, the rush build flags those two lines as errors:

      if (!bounds) bounds = [transformedBounds[0], transformedBounds[1], transformedBounds[2], transformedBounds[3]];
      else bounds = getMinOrMaxExtents(bounds, transformedBounds);

We need to use // eslint-disable-next-line no-param-reassign



_Suggestion:_
```XML
      // eslint-disable-next-line no-param-reassign
      if (!bounds) bounds = [transformedBounds[0], transformedBounds[1], transformedBounds[2], transformedBounds[3]];
      // eslint-disable-next-line no-param-reassign
      else bounds = getMinOrMaxExtents(bounds, transformedBounds);
      
```

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950)* status: all files reviewed, 10 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 386 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRg4Jm7FXJSpVx70kB:-NtRoeP46zRqta78eb18:b24i57s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L386)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I think the legend creation should be done in the validation section at the same time we read the metadata. The legend is part of the metadata. The layer process should only deal with the load/instanciation of the layers on the map.
</blockquote></details>

To Johann: the queryLegend() function is actually there, in this class, and it is called via the legend-layer-set. More comment below :thumbsup: 
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1006 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRg_bp4zf9PHWN2_8M:-NtRowWICDf3DvoL3Oxt:b428uqg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1006)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should just call this function when we need legend and this deal with the layer gathering is legend. We can get ride of the emit quering and emit queried
</blockquote></details>

True.  Even more straightforward. I can refactor that in PR13. I do think the class-events could remain though, even if don't use it, they don't hurt anyone and increases the capabilities of the framework/sdk in general.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 420 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRhG3tAKHpD8LosDmo:-NtRpW7j-h0FBl7hAMyb:b-9qzq8y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L420)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

createGroup is the same thing for all the layers type? group is a geoview structure. Should it be handle upper in abstract class to loop in structure and launch the creation of a leaf?
</blockquote></details>

I'll add this comment as a TODO in there, because I don't think I can integrate it as part of this PR series
___
*[`packages/geoview-core/src/geo/utils/all-feature-info-layer-set.ts` line 40 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRoaWG4IHfAjSuOEjz:-NtRplvy5VwKYhA4U5Mc:brrlsm8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/utils/all-feature-info-layer-set.ts#L40)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Again this whole thing can only be a direct function call and this thing to see if we can do it should be on layer class itself.
</blockquote></details>

Should discuss about this one, not sure I understand
___
*[`packages/geoview-core/src/geo/utils/feature-info-layer-set.ts` line 91 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRowqz7Vyg4xucT7dB:-NtRq9t31V4n7KXffNaL:b-jx3v3j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/utils/feature-info-layer-set.ts#L91)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Config is not the entire configuration; it may be a leaf node whose variable name is config. Having said that, it doesn't mean that your comment isn't valid.
</blockquote></details>

I pass the config, because atm the layerStatus is attached to a config and it made sense to me to keep them together. Also, I'd really like to get rid of the `this.layerApi.registeredLayers`call in this function and I was wondering if config received via parameters is the same as the refetching happening here `this.layerApi.registeredLayers[layerPath]`. Because if so, we would be able to remove yet another coupling!
Can discuss it further after lunch
___
*[`packages/geoview-core/src/geo/utils/hover-feature-info-layer-set.ts` line 96 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRpYWx7MBrD5yFVSnc:-NtRs0TY9taNwiMyHJPD:bb73xfv) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/utils/hover-feature-info-layer-set.ts#L96)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same comment as above in feature info
</blockquote></details>

Same
___
*[`packages/geoview-core/src/geo/utils/legends-layer-set.ts` line 44 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRq71U4ZANI8Oq1kIT:-NtRs8NX6VkpDCMg9OsC:b-xlyt4q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/utils/legends-layer-set.ts#L44)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

No need to manage event for legend in my mind, should be direct call and layer set can include in for legend/ui for store propagation
</blockquote></details>

Agreed. Same comment as above. For PR13.
___
*[`packages/geoview-core/src/geo/utils/legends-layer-set.ts` line 82 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRqHLP1p1v6_9Ce_gg:-NtRsLD87VeeHTXTTRfz:b61u2dn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/utils/legends-layer-set.ts#L82)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same comment no need for status change listener in legend
</blockquote></details>

Hmm, that's actually where the query of the legend is called and where the legend would be propagated to the store
___
*[`packages/geoview-core/src/geo/utils/legends-layer-set.ts` line 97 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRqOcH2LrPIMHLytYU:-NtRtAZEDS0Lky6ktvFx:b8gcr3q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/utils/legends-layer-set.ts#L97)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should be a direct function to layer and layer know is status, no need to have this logic. Layer status for parent should be dealt in layer set or layer api.
</blockquote></details>

Agreed that function can probably be somewhere else like layer or layer-api and the call to it should be in the mother class. I'll see if I can do it in PR13.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950)* status: all files reviewed, 10 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 386 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRg4Jm7FXJSpVx70kB:-NtRu9VP7sor-i_twuae:bohqym8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L386)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

To Johann: the queryLegend() function is actually there, in this class, and it is called via the legend-layer-set. More comment below :thumbsup:
</blockquote></details>

Will need to discuss about this. I see your point, the legend fetch can be outside but the one responsible for it would be layer in my mind

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950)* status: all files reviewed, 10 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1006 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRg_bp4zf9PHWN2_8M:-NtRui4vBcpp7wc54151:ba5gu41) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1006)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

True.  Even more straightforward. I can refactor that in PR13. I do think the class-events could remain though, even if don't use it, they don't hurt anyone and increases the capabilities of the framework/sdk in general.
</blockquote></details>

Yes they can remain I think

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950)* status: all files reviewed, 10 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 420 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRhG3tAKHpD8LosDmo:-NtRur5X8N0lznCQ-NPe:b-1ah81f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L420)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I'll add this comment as a TODO in there, because I don't think I can integrate it as part of this PR series
</blockquote></details>

I wouldlike our metadata fetching wms, esri dynamic, geojson, config structure to return a standard tree to be reuse in layer to create any kind of structure. Group is dealt in abstract layer or its own layer class if needed because group must deal with children visibility/order/merged bounds, ...

**Review by ychoquet — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950)* status: all files reviewed, 10 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 386 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRg4Jm7FXJSpVx70kB:-NtRux_J4BnBmh2yNQih:b-wxguqy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L386)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Will need to discuss about this. I see your point, the legend fetch can be outside but the one responsible for it would be layer in my mind
</blockquote></details>

Will need to discuss about this. In my mind the geoview layers does things related to the display and interaction with the data (visibility, opacity, getFeatureInfo, etc.), the layer class is the orchestror and the validation is reponsible for providing all the valid configuration andmetadata (to me, Legend is metadata). Let's set this discussion as satisfied for the moment, we will make a dessision later.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts` line 420 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRhG3tAKHpD8LosDmo:-NtRwyoq3lWz06BPGh6v:bl17mcx) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/layer/geoview-layers/raster/wms.ts#L420)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I wouldlike our metadata fetching wms, esri dynamic, geojson, config structure to return a standard tree to be reuse in layer to create any kind of structure. Group is dealt in abstract layer or its own layer class if needed because group must deal with children visibility/order/merged bounds, ...
</blockquote></details>

Will have to discuss about that too. We need to be on the same wave length.
___
*[`packages/geoview-core/src/geo/utils/feature-info-layer-set.ts` line 91 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1950#-NtRowqz7Vyg4xucT7dB:-NtRxLXHBFBGuMjNgN31:b-ovwawk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/542dc87ade133e5780341af1d3abcae22af9495c/packages/geoview-core/src/geo/utils/feature-info-layer-set.ts#L91)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

I pass the config, because atm the layerStatus is attached to a config and it made sense to me to keep them together. Also, I'd really like to get rid of the `this.layerApi.registeredLayers`call in this function and I was wondering if config received via parameters is the same as the refetching happening here `this.layerApi.registeredLayers[layerPath]`. Because if so, we would be able to remove yet another coupling!
Can discuss it further after lunch
</blockquote></details>

Good idea!

**Pull request merged**
