### PR TITLE
feature(esri-image): ESRI image layer support added

### LINKED ISSUE #1626: [FEATURE] Support ESRI Image Layer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

GeoView Team

### User Story

As a user I would like to consume ESRI Image layer type: https://www5.agr.gc.ca/atlas/rest/services/app_agclimate_agclimat/agclimate_tx/ImageServer

### Implementation UI

Check if we support this layer type, if not add support (class and schema)
Add support for time dimension
Add a type of layer demo page and add as a layer in time slider demo and swiper

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #1626

# Description

Support for ESRI Image layers added.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested with several layers, most in depth with the layers currently on https://damonu2.github.io/geoview/esri-image.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1734)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 12 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1734)* status: 12 of 14 files reviewed, 3 unresolved discussions (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 94 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1734#-NpKHzwi8YTxaRVgPEe2:-NpKHzwj9zY1HR1Qk6Yu:bxgdn7h) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba334c6e31005dadde494cbfd38815f85b36a0a9/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L94)):*
> ```XML
>       layerDetails.styleConfig?.Point?.styleType === 'simple' ||
>       layerDetails.styleConfig?.Polygon?.styleType === 'simple' ||
>       layerDetails.type === 'esriImage'
> ```

What is this for? Do we have to put layerType info directly in the component?
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 222 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1734#-NpKIEHS9rH3S_BiiC1d:-NpKIEHS9rH3S_BiiC1e:b-2u4il1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba334c6e31005dadde494cbfd38815f85b36a0a9/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L222)):*
> ```XML
>           <LayerOpacityControl layerDetails={layerDetails} />
>           <Box sx={{ marginTop: '20px' }}>
>             {layerDetails.items?.length > 0 && layerDetails.type !== 'esriImage' && renderItems()}
> ```

Same here.... this should be handle in the backend
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 340 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1734#-NpKIfJlAOD4s2XyMeP3:-NpKIfJlAOD4s2XyMeP4:bggnuul) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba334c6e31005dadde494cbfd38815f85b36a0a9/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L340)):*
> ```XML
>       const { data } = await axios.get<TypeJsonObject>(`${queryUrl}?f=pjson`);
>       // layers must have a fields attribute except if it is an metadata layer group.
>       if (!data?.fields && !(layerConfig as TypeLayerGroupEntryConfig).isMetadataLayerGroup && layerConfig.schemaTag !== 'esriImage') {
> ```

Why metadata group is not handle the same way as dynamic with the is?MetadataLayerGroup function?

**Review by ychoquet — APPROVED** [review]
I have the same comments Johann wrote.

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1734#-:-NpKe6wrBt1MVJ5b3xBr:b-pf19ma)* status: all files reviewed, 3 unresolved discussions (waiting on @DamonU2)

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1734)* status: 11 of 15 files reviewed, 3 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 94 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1734#-NpKHzwi8YTxaRVgPEe2:-NpLSrfs-YR2jje3YouK:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba334c6e31005dadde494cbfd38815f85b36a0a9/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L94)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

What is this for? Do we have to put layerType info directly in the component?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx` line 222 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1734#-NpKIEHS9rH3S_BiiC1d:-NpLSs-7A_Xo03v4-ss2:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba334c6e31005dadde494cbfd38815f85b36a0a9/packages/geoview-core/src/core/components/layers/right-panel/layer-details.tsx#L222)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Same here.... this should be handle in the backend
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts` line 340 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1734#-NpKIfJlAOD4s2XyMeP3:-NpLSsWv5u97qgyuZlsQ:b-6do1n6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/ba334c6e31005dadde494cbfd38815f85b36a0a9/packages/geoview-core/src/geo/layer/geoview-layers/esri-layer-common.ts#L340)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why metadata group is not handle the same way as dynamic with the is?MetadataLayerGroup function?
</blockquote></details>

It's not the group, it's because the image layers don't have to have fields in the data

**Review by jolevesq — APPROVED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1734)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1734)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
