### PR TITLE
fix(dynamic layers): fixed zoom issues in data table

### LINKED ISSUE #2592: [BUG] 11 - Zoom to feature from data table does not work. [OSDP-1801]  (11 layers)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When in the data table of a layer, if you try to click on the zoom icon nothing happens for any of the feature contained in the data table.
image

Concerned UUIDs:

274ede77-27b9-46b8-96c8-4d7d4a706f08
22abff18-6f9d-4926-b7de-3a80c178bf95
21b821cf-0f1c-40ee-8925-eab12d357668
039fbd92-43c2-4805-b210-d65703712e37
622a7f72-4a00-4f9e-b04f-af6551c77db3
1c61d457-4d03-4f3a-9005-9aabb5a201bb
5c670585-97ed-4e6a-a607-30fab940ff88
2163f792-d105-4e80-8150-08b49fab20c0
cfab1711-3566-4481-aebf-292ef56b216a
6ab784be-1197-4820-8bc2-fd20da32632c
87b08750-4180-4d31-9414-a9470eba9b42

### Expected Behavior

As for other layers, when clicking on the zoom icon from the data table, the viewer should lead you to the targeted feature.

### Steps To Reproduce

1. Load any the above UUID
2. Go into the Data Table tab and load the data table
3. Click on the zoom icon for any of the feature within the loaded data table.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #2592

# Description

Fixes issues with ESRI Dynamic zoom to feature in the data table.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://damonu2.github.io/geoview/add-layers.html

274ede77-27b9-46b8-96c8-4d7d4a706f08 - fixed
22abff18-6f9d-4926-b7de-3a80c178bf95 - fixed
21b821cf-0f1c-40ee-8925-eab12d357668 - no geometry returned - doesn't work in RAMP
039fbd92-43c2-4805-b210-d65703712e37 - no geometry returned - doesn't work in RAMP
622a7f72-4a00-4f9e-b04f-af6551c77db3 - fixed
1c61d457-4d03-4f3a-9005-9aabb5a201bb - no layers returned from geocore
5c670585-97ed-4e6a-a607-30fab940ff88 - no geometry returned - doesn't work in RAMP
2163f792-d105-4e80-8150-08b49fab20c0 - fixed
cfab1711-3566-4481-aebf-292ef56b216a - fixed
6ab784be-1197-4820-8bc2-fd20da32632c - wms layer, no data table
87b08750-4180-4d31-9414-a9470eba9b42 - fixed

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2649)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2649)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/core/components/data-table/data-table.tsx` line 304 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2649#-ODrR7u--TALJ6KD8lpl:-ODrR7u04Y-efi0TjiLK:bqu4v8q) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6fbdf942df95a383a593a569b837bfe10e1452d1/packages/geoview-core/src/core/components/data-table/data-table.tsx#L304)):*
> ```XML
>       // If there is no extent, the layer is ESRI Dynamic, get the feature extent using its OBJECTID
>       // GV: Some layers do not use OBJECTID, these are the other values seen so far.
>       const idFields = ['OBJECTID', 'OBJECTID_1', 'FID', 'STATION_NUMBER'];
> ```

We should put a TODO ot support the esriField type. This would be a more stable solution

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2649)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2649)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2649)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
