### PR TITLE
fix(legend): gets icons for default styles

### LINKED ISSUE #2072: [BUG] default styles not in icons
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Layers with default styling provided by geoview do not have icons in footer panel.

### Expected Behavior

Icons should be generated for default styles

### Steps To Reproduce

Go to https://canadian-geospatial-platform.github.io/geoview/public/raw-add-layers.html
Add https://canadian-geospatial-platform.github.io/geoview/public/datasets/geojson/points.json
Check legend

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #2072

# Description
Adds an event for style changes and emits it when a default style is created. The legend event processor listens to this, and updates the legend icon

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://damonu2.github.io/geoview/demos-navigator.html?config=./configs/navigator/20-wfs.json

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2197)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2197)* status: all files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts` line 218 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2197#-NzT30Fr0j1YmhbfLEg4:-NzT30Fr0j1YmhbfLEg5:bti9lwb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c0cb5870fe322577be781abd1235f5694d26f517/packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts#L218)):*
> ```XML
>    * @param {LayerStyleChangedEvent} event - The event to emit
>    */
>   emitLayerStyleChanged(event: LayerStyleChangedEvent): void {
> ```

Event should in layer, see comment below. Just put a TODO< and it will be merge in a next PR.
___
*[`packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts` line 1561 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2197#-NzT2Zhi-i5Y96lm8LL4:-NzT2Zhi-i5Y96lm8LL5:bvm5u1s) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c0cb5870fe322577be781abd1235f5694d26f517/packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts#L1561)):*
> ```XML
>     style = createDefaultStyle(geometryType, layerConfig as VectorLayerEntryConfig, language);
>     // Emit event to update legend icons
>     layerConfig.emitLayerStyleChanged({ layerPath: layerConfig.layerPath });
> ```

This emit should be private and activated be a setter like layer.setStyle. Can you add a TODO.... Alex is refactoring the layers and will just fix this later as we are removing the layerConfig to work mostly on the gv-layer itself.

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2197)* status: all files reviewed, 2 unresolved discussions (waiting on @DamonU2)

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2197)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts` line 218 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2197#-NzT30Fr0j1YmhbfLEg4:-NzTODzG8V0_Wb6Mq1DS:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c0cb5870fe322577be781abd1235f5694d26f517/packages/geoview-core/src/core/utils/config/validation-classes/config-base-class.ts#L218)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Event should in layer, see comment below. Just put a TODO< and it will be merge in a next PR.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts` line 1561 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2197#-NzT2Zhi-i5Y96lm8LL4:-NzTOEd-03Xu1cqNMwu0:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c0cb5870fe322577be781abd1235f5694d26f517/packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts#L1561)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

When we see the function name getFeatureStyle, the setter in here is not at the right place. getter should only return something and the caller is responsible to set.
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2197)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
