### PR TITLE
#247 refactor geo

### LINKED ISSUE #247: Refactor Geo
Continue refactoring Geo and clean up code

### PR DESCRIPTION
**Pull request by yass0016**
Closes #247

---
This change is [Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/255)

### CODE REVIEW

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/255)* status: 0 of 16 files reviewed, 1 unresolved discussion

___
*[Larry_Notes.txt, line 1 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/255#-MvQ6Bkp8v1A2Jc8vHXC:-MvQ6Bkq-A9oSOshrtTr:bxjtrwn) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/763260ed1cdec1004faeb7e1f7f466774fc8040a/Larry_Notes.txt#L1)):*
> ```help
> Larry's Notes
> ```

Do we need this? Or you added it just for testing purposes? If we don't need it, can you delete it?

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/255)* status: 0 of 16 files reviewed, 2 unresolved discussions

___
*[packages/geoview-core/src/geo/layer/layer.ts, line 9 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/255#-MvQ6qTC9msx1yLdO8Ie:-MvQ6qTC9msx1yLdO8If:b-y2lvfl) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/763260ed1cdec1004faeb7e1f7f466774fc8040a/packages/geoview-core/src/geo/layer/layer.ts#L9)):*
> ```XML
> import { GeoJSON } from "./file/geojson";
> import { Vector } from "./vector/vector";
> import { api } from "../../api/api";
> ```

Can you move the import of this and EVENT_NAMES below the imports of the layers? Imports are grouped to related things, add new lines between groups of imports

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/255)* status: 0 of 16 files reviewed, 3 unresolved discussions

___
*[packages/geoview-core/src/geo/layer/esri/esri-dynamic.ts, line 8 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/255#-MvQ7GV05dpkmvRx62Jx:-MvQ7GV05dpkmvRx62Jy:b-qw040y) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/763260ed1cdec1004faeb7e1f7f466774fc8040a/packages/geoview-core/src/geo/layer/esri/esri-dynamic.ts#L8)):*
> ```XML
> import { TypeLayerConfig } from "../../../core/types/cgpv-types";
> 
> import {api} from "../../../api/api";
> ```

Try saving this file to allow prettier to format it

**Review by yass0016 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/255)* status: 0 of 16 files reviewed, 5 unresolved discussions

___
*[packages/geoview-core/src/geo/map/map.ts, line 130 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/255#-MvQ7tUnDdxXs9EX-mg4:-MvQ7tUnDdxXs9EX-mg5:bkl42zm) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/763260ed1cdec1004faeb7e1f7f466774fc8040a/packages/geoview-core/src/geo/map/map.ts#L130)):*
> ```XML
> 
>     // check if geometries are provided from url
>     //this.loadGeometries();  //commented out for refactoring layer
> ```

Are we still able to load geometries from outside using the data-geometry-endpoint attribute, "<div data-geometry-endpoint='url...'?
___
*[packages/geoview-core/src/geo/utils/utilities.ts, line 5 at r1](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/255#-MvQ8G3JCX6Fo_9LtSRP:-MvQ8G3JCX6Fo_9LtSRQ:b-d1hzt5) ([raw file](https://github.com/canadian-geospatial-platform/geoview/blob/763260ed1cdec1004faeb7e1f7f466774fc8040a/packages/geoview-core/src/geo/utils/utilities.ts#L5)):*
> ```XML
> import { api } from "../../api/api";
> import { EVENT_NAMES } from "../../api/event";
> import { Cast, TypeCSSStyleDeclaration } from "../../core/types/cgpv-types";
> ```

Add a new line above to seperate importing groups

**Review by LarryWang888 — COMMENTED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/255)* status: 0 of 16 files reviewed, 5 unresolved discussions (waiting on @LarryWang888)

**Review by yass0016 — COMMENTED** [review]
> Reviewed 11 of 16 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/canadian-geospatial-platform/geoview/255)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yass0016)

**Pull request merged**
