### PR TITLE
fix(accordion): Fix accordion when we have multiple parent/child accordions

### LINKED ISSUE #1201: [BUG] Accordion and expanded nodes not working anymore
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Since I've synched up the Geoview core for usage in my Clip Zip Ship application, I have a new behavior with the accordion. When I expand a node, it automatically expands all the sibling nodes. I believe it could be caused by a recent change in the code with regards to storing an "isExpanded" state which is the same value used for all "AccordionItems" in the render loop [here](https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/packages/geoview-core/src/ui/accordion/accordion.tsx#L74)

#### For example:

Before expanding anything:
image

After 1 single click to expand "Agriculture, cons....", other sibling like "Fauna, flora" and "Hydrography" expand automatically
image

### Expected Behavior

Can we make it so that 1 accordion group can be expanded without auto-expanding the sibling nodes?
The expanded state should be automatically handled by the React Material UI, no?

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by amir-azma**
# Description

There was an issue when we have multiple accordion on the page either as parent or child, once we open one of them, all accordions will be opened. That's because we were sharing one single state to keep track of all accordions.

Fixes #1201 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

### Before fix:
https://github.com/Canadian-Geospatial-Platform/geoview/assets/138072320/8b0c581e-3916-4e51-9833-e4f4759ec374

### After fix:

https://github.com/Canadian-Geospatial-Platform/geoview/assets/138072320/c431c16d-7a4f-4699-a9c9-855fe7191cf4

https://amir-azma.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1235)

### CODE REVIEW

**Review by DamonU2 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1235)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cphelefu and @jolevesq)

**Review by cphelefu — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1235)* status: all files reviewed, 1 unresolved discussion (waiting on @amir-azma and @jolevesq)

___
*[`packages/geoview-core/src/ui/accordion/accordion.tsx` line 52 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1235#-NbZygEq5ch50FTSlq5e:-NbZygEq5ch50FTSlq5f:b-127f8d) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0d06859f132df9f3046c3e7208dc91a9a2f4346f/packages/geoview-core/src/ui/accordion/accordion.tsx#L52)):*
> ```XML
>   const [transitionStates, setTransitionStates] = useState<boolean[]>(Array(items.length).fill(false));
> 
>   const handleAccordionChange = (index: number) => (event: React.SyntheticEvent, expanded: boolean) => {
> ```

Is there a reason for us handling this in here?
We prefer al components in ui folder to be empty components (clone of materialUI) components.

**Review by cphelefu — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1235)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

**Review by amir-azma — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1235)* status: all files reviewed, 1 unresolved discussion (waiting on @amir-azma)

**Review by cphelefu — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1235)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amir-azma)

**Pull request merged**
