### PR TITLE
fix(appbar): fix wcag issue of appbar 

### LINKED ISSUE #2402: Fix wcag for Appbar.
When tabbing on appbar and panel focus goes out of panel, should be focus trapped inside.

### PR DESCRIPTION
**Pull request by kaminderpal**
# Description
Fix the wcag issues of appbar which includes focus trap of panels opened by appbar buttons.
This will be the series of PR which will handle diff core components in seperate PRs.
This will handle at the moment `AppBar`, also add aria-label for icon button used in appbar.
`Export-Button` is not included in this PR, will include in Modal component PR.

Fixes #2402 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

__Add the URL for your deploy!__
https://kaminderpal.github.io/geoview/demos-navigator.html?config=./configs/navigator/07-basic-appbar.json
# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2406)

### CODE REVIEW

**Review by cphelefu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2406#-:-O2abKRm9LDyBxBXxhX9:bnfp4nl)* status: 0 of 17 files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by kaminderpal — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2406)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/geolocator/geolocator.tsx` line 50 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2406#-O2aZfkl7IUdCoCAcAiv:-O2dxVxOEzgTDqn6_dyA:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9d9039c9478454499261ec8154cde96642f09066/packages/geoview-core/src/core/components/geolocator/geolocator.tsx#L50)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Dead code
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2406)* status: all files reviewed, 1 unresolved discussion (waiting on @kaminderpal)

**Review by jolevesq — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2406#-:-O2dxlfhCEB0jGI9_Qeb:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @kaminderpal)

**Pull request merged**
