### PR TITLE
feat(event): layer loaded event added

### LINKED ISSUE #1890: [FEATURE] Need a new event like LAYER.EVENT_LAYER_LOADED
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Naman Gera, CHN team, NRCan

### User Story

As a developer I would like an event that can detect when a layer is loaded, after talking to Damon, such an event already exists but is not part of the api. Previously I could use LAYER.EVENT_LAYER_ADDED for this but seems the functionality has changed. So an event like LAYER.EVENT_LAYER_LOADED in the api would be helpful. I am using this when a request is made to pygeo api but some layers take a while to load on the map so I want a loading wheel till the layer is loaded on the map. 

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #1890

# Description

Added event for layer being loaded onto the map

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Event notification added to demo-function-event.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1518 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323#-O0PNCJ6A9y_LiJAo1GU:-O0PNCJ6A9y_LiJAo1GV:b-y368wr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/788735c51fe30d9c7922e277ba71eb321c357b95/packages/geoview-core/src/geo/layer/layer.ts#L1518)):*
> ```XML
>    * @param {LayerLoadedDelegate} callback - The callback to be executed whenever the event is emitted
>    */
>   onLayerLoaded(callback: LayerLoadedDelegate): void {
> ```

What is the big difference between -   onLayerAdded et onLayerLoaded? The issue was about receving the content of the layer itself. Is it in the demo?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1436 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323#-O0PNYYw3q4ZyFoAOaWe:-O0PNYYw3q4ZyFoAOaWf:b5047qm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/788735c51fe30d9c7922e277ba71eb321c357b95/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1436)):*
> ```XML
> 
>     // Emit event from layer API
>     this.getMapViewer().layer.layerLoaded(layerConfig.layerPath);
> ```

Should the emit by private like other event?

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1518 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323#-O0PNCJ6A9y_LiJAo1GU:-O0POr0e2oUMl8wu3nK4:bobd6jb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/788735c51fe30d9c7922e277ba71eb321c357b95/packages/geoview-core/src/geo/layer/layer.ts#L1518)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

What is the big difference between -   onLayerAdded et onLayerLoaded? The issue was about receving the content of the layer itself. Is it in the demo?
</blockquote></details>

onLayerAdded is when the layer is first added to the map. onLayerLoaded is when the features are all loaded onto the map. Naman was having issues where he was listening to onLayerAdded on a complex layer, and none of the manipulation he was trying to do was happening because the features weren't loaded yet.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1436 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323#-O0PNYYw3q4ZyFoAOaWe:-O0PPuDN6tYg-JKtoHgD:b-bgctg6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/788735c51fe30d9c7922e277ba71eb321c357b95/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1436)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should the emit by private like other event?
</blockquote></details>

So this is what I have been struggling to understand with the events. The emit should be private in layer.ts, so this function is just a redirect. I need it to live in layer.ts so it can be listened to without knowledge of the layer, but emit it from here, so to keep the emit private, there is a function that does nothing but emit the event (although in the future the function could be useful for other things).

**Review by jolevesq — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1518 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323#-O0PNCJ6A9y_LiJAo1GU:-O0PtjSY5ACvsPe6ks7S:bsochi4) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/788735c51fe30d9c7922e277ba71eb321c357b95/packages/geoview-core/src/geo/layer/layer.ts#L1518)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

onLayerAdded is when the layer is first added to the map. onLayerLoaded is when the features are all loaded onto the map. Naman was having issues where he was listening to onLayerAdded on a complex layer, and none of the manipulation he was trying to do was happening because the features weren't loaded yet.
</blockquote></details>

CAn you just add the info in function description so we know the difference
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1436 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323#-O0PNYYw3q4ZyFoAOaWe:-O0PRlAHAZhXs8vmBvDc:bkh2uj2) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/788735c51fe30d9c7922e277ba71eb321c357b95/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1436)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

So this is what I have been struggling to understand with the events. The emit should be private in layer.ts, so this function is just a redirect. I need it to live in layer.ts so it can be listened to without knowledge of the layer, but emit it from here, so to keep the emit private, there is a function that does nothing but emit the event (although in the future the function could be useful for other things).
</blockquote></details>

The event should be emitted by the open layer onLoaded event, this should trigger this one.

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1518 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323#-O0PNCJ6A9y_LiJAo1GU:-O0Q9fnQ6apRuQkjXa-y:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/788735c51fe30d9c7922e277ba71eb321c357b95/packages/geoview-core/src/geo/layer/layer.ts#L1518)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

CAn you just add the info in function description so we know the difference
</blockquote></details>

Done.

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1436 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323#-O0PNYYw3q4ZyFoAOaWe:-O0QDoVw1W51dymDr6A8:b6ufwkg) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/788735c51fe30d9c7922e277ba71eb321c357b95/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1436)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

The event should be emitted by the open layer onLoaded event, this should trigger this one.
</blockquote></details>

```javascript
my_layer.getSource().on("featuresloadstart", function () {
   document.getElementById("my_loader").classList.add("loader");
});

my_layer.getSource().on("featuresloadend", function () {
  document.getElementById("my_loader").classList.remove("loader");
});
```

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1436 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323#-O0PNYYw3q4ZyFoAOaWe:-O0QDDmg4UFEGQ2fgbJL:b-jh7sq6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/788735c51fe30d9c7922e277ba71eb321c357b95/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1436)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

```javascript
my_layer.getSource().on("featuresloadstart", function () {
   document.getElementById("my_loader").classList.add("loader");
});

my_layer.getSource().on("featuresloadend", function () {
  document.getElementById("my_loader").classList.remove("loader");
});
```
</blockquote></details>

Here and in `abstract-gv-layer.ts` it'd be better to not emit an event of the `LayerApi`.

What Johann suggests here could work (though, featuresloadend is already what caused the `onLoaded` method to be called).
Also, in order to support all kinds of layer types (not just features), I'd raise a `layerLoaded` event here, in `onLoaded`. That event would be listened in `LayerApi` and re-raised from there to have a centralization of all layers loaded events as you seem to want to do.

That way, and alternatively, a developer could also listen to the `layerLoaded` event of the layer class itself if they rather do that. More specific than listening to a `layerLoaded` event coming from the `LayerApi`.

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts` line 1436 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323#-O0PNYYw3q4ZyFoAOaWe:-O0QiyTc8qfw5LYl2vy9:b-896fig) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/788735c51fe30d9c7922e277ba71eb321c357b95/packages/geoview-core/src/geo/layer/geoview-layers/abstract-geoview-layers.ts#L1436)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Here and in `abstract-gv-layer.ts` it'd be better to not emit an event of the `LayerApi`.

What Johann suggests here could work (though, featuresloadend is already what caused the `onLoaded` method to be called).
Also, in order to support all kinds of layer types (not just features), I'd raise a `layerLoaded` event here, in `onLoaded`. That event would be listened in `LayerApi` and re-raised from there to have a centralization of all layers loaded events as you seem to want to do.

That way, and alternatively, a developer could also listen to the `layerLoaded` event of the layer class itself if they rather do that. More specific than listening to a `layerLoaded` event coming from the `LayerApi`.
</blockquote></details>

Done?

**Review by Alex-NRCan — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)* status: all files reviewed, 2 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/public/templates/demos/demo-function-event.html` line 190 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323#-O0U2cu01TStpoIGQM5e:-O0U2cu14M-bxL0PDj8r:b-8r3qa3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d1556034c04af1fa56c79af000d5b6526e9e76b7/packages/geoview-core/public/templates/demos/demo-function-event.html#L190)):*
> ```HTML
>         });
> 
>         // listen to layer loaded event
> ```

Great stuff here, the 2 event listeners examples
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 690 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323#-O0U2lx0EPfCkcK5v_Z-:-O0U2lx0EPfCkcK5v_Z0:bqv3uyz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d1556034c04af1fa56c79af000d5b6526e9e76b7/packages/geoview-core/src/geo/layer/layer.ts#L690)):*
> ```XML
>               // Log
>               logger.logDebug(`${sender.layerPath} loaded on map ${this.getMapId()}`);
>               this.#emitLayersLoaded({ layerPath: sender.layerPath });
> ```

Here, it seems the `payload` and `sender` params are interverted.
`payload` is actually the `sender` and `sender` is actually the `payload` or `event` object, right?

Also, would it be cool if the LayerApi.emitLayersLoaded event would raise the actual layer along with the layerPath? Like: `this.#emitLayersLoaded({ layer: sender, layerPath: payload.layerPath });` (if the params were swapped/fixed).

**Review by Alex-NRCan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)* status: all files reviewed, 2 unresolved discussions (waiting on @DamonU2 and @jolevesq)

___
*[`packages/geoview-core/public/templates/demos/demo-function-event.html` line 192 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323#-O0U5KIO2tUvPENK22NF:-O0U5KIO2tUvPENK22NG:bufn1do) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d1556034c04af1fa56c79af000d5b6526e9e76b7/packages/geoview-core/public/templates/demos/demo-function-event.html#L192)):*
> ```HTML
>         // listen to layer loaded event
>         cgpv.api.maps.Map1.layer.onLayersLoaded((sender, payload) => {
>           cgpv.api.maps.Map1.notifications.addNotificationSuccess(payload.layerPath + ' loaded');
> ```

If my other comment is implemented with the actual loaded layer sent in the payload, here, payload.layer would represent the layer that got loaded.

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 690 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323#-O0U2lx0EPfCkcK5v_Z-:-O0U8yXJ4S0ZjHbJst08:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d1556034c04af1fa56c79af000d5b6526e9e76b7/packages/geoview-core/src/geo/layer/layer.ts#L690)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

Here, it seems the `payload` and `sender` params are interverted.
`payload` is actually the `sender` and `sender` is actually the `payload` or `event` object, right?

Also, would it be cool if the LayerApi.emitLayersLoaded event would raise the actual layer along with the layerPath? Like: `this.#emitLayersLoaded({ layer: sender, layerPath: payload.layerPath });` (if the params were swapped/fixed).
</blockquote></details>

Done.

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)* status: all files reviewed, 1 unresolved discussion (waiting on @jolevesq)

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1505 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323#-O0TgSd59B6bP_QLl2IJ:-O0TgSd63vMliFUVoyux:br2vm5n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d1556034c04af1fa56c79af000d5b6526e9e76b7/packages/geoview-core/src/geo/layer/layer.ts#L1505)):*
> ```XML
>   /**
>    * Emits an event to all handlers when the layer's features have been loaded on the map.
>    * @param {LayersLoadedEvent} event - The event to emit
> ```

Is it layer by layer or all layer with an s?

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1505 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323#-O0TgSd59B6bP_QLl2IJ:-O0V1KJI6S-V2Kfe_VoU:b-q8vg0g) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d1556034c04af1fa56c79af000d5b6526e9e76b7/packages/geoview-core/src/geo/layer/layer.ts#L1505)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is it layer by layer or all layer with an s?
</blockquote></details>

My understanding is that it is layer by layer indeed.
I believe Damon pluralized it to distinguish it better from the loaded event on the layer itself. Which I thought was a good idea when I reviewed it. That said, I can see how pluralizing it can also lead to confusion in the sense that one might expect a list of loaded layers in that event. I'm on the fence personally on that one. Essentially, that event is raised for multiple layers, yes, but one at a time, not an array of layers.

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)* status: all files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1505 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323#-O0TgSd59B6bP_QLl2IJ:-O0V2rs22a_NNr_Vfk7r:b4akquj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d1556034c04af1fa56c79af000d5b6526e9e76b7/packages/geoview-core/src/geo/layer/layer.ts#L1505)):*
<details><summary><i>Previously, Alex-NRCan (Alex) wrote…</i></summary><blockquote>

My understanding is that it is layer by layer indeed.
I believe Damon pluralized it to distinguish it better from the loaded event on the layer itself. Which I thought was a good idea when I reviewed it. That said, I can see how pluralizing it can also lead to confusion in the sense that one might expect a list of loaded layers in that event. I'm on the fence personally on that one. Essentially, that event is raised for multiple layers, yes, but one at a time, not an array of layers.
</blockquote></details>

Yep, that's right. Maybe it should have a more descriptive name. Change this to layerLoaded and the other to individualLayerLoaded?

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1505 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323#-O0TgSd59B6bP_QLl2IJ:-O0V7qva-W3IydDg27vP:b-bu91xm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/d1556034c04af1fa56c79af000d5b6526e9e76b7/packages/geoview-core/src/geo/layer/layer.ts#L1505)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Yep, that's right. Maybe it should have a more descriptive name. Change this to layerLoaded and the other to individualLayerLoaded?
</blockquote></details>

Updated

**Review by jolevesq — COMMENTED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)* status: all files reviewed, 1 unresolved discussion (waiting on @DamonU2)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2323)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
