### PR TITLE
fix(map): Fixed double config load and added function to create map

### LINKED ISSUE #905: [BUG] loadMapConfig Function trigger twice
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is a problem when we load the map from a function with loadMapConfig. The code is triggered twice (first for map creation from the empty div, and a second time for the map with the function div).

Problem is the viewer is lookin at the map divs on load and start map creation on them when the class "llwp-map" is there
```
<div id="LNG1" class="llwp-map" data-lang="fr"></div>
```
If the class is not there the map will never be created even if we run
```
cgpv.api.map('LNG1').loadMapConfig(config);
```

Even with inline config, i18nInstance is set twice once in French and once in English

### Expected Behavior

We should be able to create a map in any div without the llwp-map class (should be added on map creation) and the viewer should not run twice with the function call.

Repair language html page to use function loading instead of inline config.

### Steps To Reproduce

Go to language page and put a break point in app-start.tsx (i18nInstance)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #905

# Description

Fixed loading config into existing map, and added function to load map into any div.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Tested various map functions for both methods.

# Checklist:

- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/981)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/981)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/src/core/utils/create-map-from-config.tsx` line 14 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/981#-NRABDBu3MVNcQEN_LOx:-NRABDBu3MVNcQEN_LOy:b7927v8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1d06be3ec16d0b7b903030abadf6ca2352ac619/packages/geoview-core/src/core/utils/create-map-from-config.tsx#L14)):*
> ```XML
>   const mapDiv = document.getElementById(divId);
>   if (mapDiv) {
>     mapDiv.className = 'llwp-map';
> ```

If class already there would it duplicate?
___
*[`packages/geoview-core/src/core/utils/create-map-from-config.tsx` line 16 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/981#-NRAB5TXCOWTPXJoQO8q:-NRAB5TXCOWTPXJoQO8r:brg2x5n) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1d06be3ec16d0b7b903030abadf6ca2352ac619/packages/geoview-core/src/core/utils/create-map-from-config.tsx#L16)):*
> ```XML
>     mapDiv.className = 'llwp-map';
> 
>     // Erase comments in the config file.
> ```

I saw this function somewhere else. Can we have one copy in utilities and reuse?

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/981)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/utils/create-map-from-config.tsx` line 14 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/981#-NRABDBu3MVNcQEN_LOx:-NRANf9k1bML4_yJ4m04:b-iso6x6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1d06be3ec16d0b7b903030abadf6ca2352ac619/packages/geoview-core/src/core/utils/create-map-from-config.tsx#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If class already there would it duplicate?
</blockquote></details>

Good catch, actually caused a lot more problems. Fixed now.
___
*[`packages/geoview-core/src/core/utils/create-map-from-config.tsx` line 16 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/981#-NRAB5TXCOWTPXJoQO8q:-NRANo_i1nv1aPu-7ShE:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1d06be3ec16d0b7b903030abadf6ca2352ac619/packages/geoview-core/src/core/utils/create-map-from-config.tsx#L16)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

I saw this function somewhere else. Can we have one copy in utilities and reuse?
</blockquote></details>

Done.

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/981)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/utils/create-map-from-config.tsx` line 14 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/981#-NRABDBu3MVNcQEN_LOx:-NREL9GyAv9pvmbcrrg6:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1d06be3ec16d0b7b903030abadf6ca2352ac619/packages/geoview-core/src/core/utils/create-map-from-config.tsx#L14)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

To make it more clean I think you can use mapDiv.classList.add('llwp-map') and it will add only once. No need to test.
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/utils/utilities.ts` line 196 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/981#-NRDLZnF3JOmhZY0bbHB:-NRELAg35Plt3qX7c2pK:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/c5909d856c470ae922744cc0b9621fc909a7d87c/packages/geoview-core/src/core/utils/utilities.ts#L196)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Was it used somewhere else? If so can you remove it and replace at all places it is used
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 4 of 5 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/981)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
