### PR TITLE
refactor(style): update style to match new config

### LINKED ISSUE #2540: [FEATURE] Update style to match ew config
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Geoview team

### User Story

Update the style property to align with the new config schema. 

### Implementation UI

_No response_

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #2540

# Description

Style config updated throughout code. style renamed to layerStyle, format changed so all three style types use the same fields. 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://damonu2.github.io/geoview/

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 29 of 58 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614)* status: 28 of 59 files reviewed, 5 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 679 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJgcw8-ddWl9IxVezy:-OCJgcw8-ddWl9IxVezz:b-l4gyow) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7c17498eabdd1069843e5570715c6ecb5710256c/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L679)):*
> ```XML
>     const breakPoints = sortedBreaks.map(
>       (brk): ClassBreakPoint => ({
>         minValue: brk.values[1] as number,
> ```

Should it be 0
___
*[`packages/geoview-core/schema.json` line 121 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJWGnmC9QX8A3wl_oc:-OCJWGnmC9QX8A3wl_od:b7lfiph) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81b33d0841e26b4819b10b5ff837412d162c4d00/packages/geoview-core/schema.json#L121)):*
> ```JSON
>     },
>     "TypePolygonVectorConfig": {
>       "additionalProperties": false,
> ```

Why all these lines have been removed?
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts` line 252 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJeXHUENh-vAOCuAWk:-OCJeXHV3-pfReQqZ-qI:bfph8ze) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7c17498eabdd1069843e5570715c6ecb5710256c/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts#L252)):*
> ```XML
>     // TODO: Update with style refactor PR (function esriConvertEsriGeometryTypeToOLGeometryType gv-layer/util). Use only one function!
>     switch (esriGeometryType) {
>       case 'esriGeometryPoint':
> ```

We should put a TODO here to say we need to support all geometry type.... this is important has we have weird behaviour with the export data table
___
*[`packages/geoview-core/src/api/config/esri-renderer-parser.ts` line 606 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJdjNI4fboHc5ozvQK:-OCJdjNI4fboHc5ozvQL:b-lo16il) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7c17498eabdd1069843e5570715c6ecb5710256c/packages/geoview-core/src/api/config/esri-renderer-parser.ts#L606)):*
> ```XML
>  * @returns {TypeLayerStyleSettings | undefined} The Geoview style or undefined if it can not be created.
>  */
> // TODO: This will need an intermediate step to add back geometry types
> ```

Can you put more info on what is the problem
___
*[`packages/geoview-core/public/configs/validator/04-geocore.json` line 26 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJahGL2xkhD42Fya0a:-OCJahGL2xkhD42Fya0b:bq3j4fh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81b33d0841e26b4819b10b5ff837412d162c4d00/packages/geoview-core/public/configs/validator/04-geocore.json#L26)):*
> ```JSON
>           {
>             "layerId": "0",
>             "geometryType": "point",
> ```

Wedont use this... we are extracting it from the style or service metadata?

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 29 of 58 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614)* status: 56 of 59 files reviewed, 10 unresolved discussions (waiting on @Alex-NRCan and @DamonU2)

___
*[`packages/geoview-core/src/core/components/common/responsive-grid.tsx` line 87 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJnVVt5vqJJV3igB3D:-OCJnVVt5vqJJV3igB3E:bfsy7mt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81b33d0841e26b4819b10b5ff837412d162c4d00/packages/geoview-core/src/core/components/common/responsive-grid.tsx#L87)):*
> ```XML
>       </Grid>
>     );
>   },
> ```

That is weird... we have same prettier config but this never triggers for me
___
*[`packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts` line 379 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJoznE6ScWLZEC_czU:-OCJoznE6ScWLZEC_czV:b-t3wffh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81b33d0841e26b4819b10b5ff837412d162c4d00/packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts#L379)):*
> ```XML
>       }
> 
>       if (isClassBreakStyleConfig(styleSettings)) {
> ```

is this a function... is it still use? Why do we have a function before?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 625 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJo8rEEFhqCIAsVPyu:-OCJo8rEEFhqCIAsVPyv:b6zore1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7c17498eabdd1069843e5570715c6ecb5710256c/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L625)):*
> ```XML
>   ): TypeQueryTree {
>     const queryTree: TypeQueryTree = [];
>     styleSettings.info.forEach((styleEntry) => {
> ```

Seems a good cleanup as we do not have to specify stye anymore if not needed. Do you think this PR is a good simplification for style... at least a starting point
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1410 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJnoNt2v0QcqVNMjVq:-OCJnoNu7Q_XpkC5pYAh:bfimxqn) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7c17498eabdd1069843e5570715c6ecb5710256c/packages/geoview-core/src/geo/layer/layer.ts#L1410)):*
> ```XML
>       // Assign value to registered layer. This is use by applyFilter function to set visibility
>       // TODO: check if we need to refactor to centralize attribute setting....
>       // TODO: know issue when we toggle a default visibility item https://github.com/Canadian-Geospatial-Platform/geoview/issues/1564
> ```

Is this still an issue, I removed this from my PR if I remember
___
*[`packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts` line 811 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJpxUp3odkBHFETdbu:-OCJpxUp3odkBHFETdbv:bipjjt) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81b33d0841e26b4819b10b5ff837412d162c4d00/packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts#L811)):*
> ```XML
>     if (featureIsNotVisible(feature, filterEquation!)) return undefined;
> 
>   const settings = (isSimpleStyleConfig(styleSettings) ? styleSettings.settings : styleSettings) as TypeKindOfVectorSettings;
> ```

Are these functions removed from the imported file?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts` line 161 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJof_QCAo-UkyVASYz:-OCJof_RAQVFyKTvcstn:b186mdq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7c17498eabdd1069843e5570715c6ecb5710256c/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts#L161)):*
> ```XML
>         const styleInfo: TypeLayerStyleConfigInfo = {
>           label: info.label,
>           visible: true,
> ```

It was not set before?

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614)* status: 50 of 59 files reviewed, 10 unresolved discussions (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/schema.json` line 121 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJWGnmC9QX8A3wl_oc:-OCKf7lMBl8wSKq134CJ:bpb3mhm) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81b33d0841e26b4819b10b5ff837412d162c4d00/packages/geoview-core/schema.json#L121)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why all these lines have been removed?
</blockquote></details>

To match how it is done in the new config
___
*[`packages/geoview-core/public/configs/validator/04-geocore.json` line 26 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJahGL2xkhD42Fya0a:-OCKfTHbEDAaYZoRtdRy:b-6xwfyu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81b33d0841e26b4819b10b5ff837412d162c4d00/packages/geoview-core/public/configs/validator/04-geocore.json#L26)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Wedont use this... we are extracting it from the style or service metadata?
</blockquote></details>

Not used any more because it is back to the style object
___
*[`packages/geoview-core/src/api/config/esri-renderer-parser.ts` line 606 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJdjNI4fboHc5ozvQK:-OCKfi25BLQpg2jeIke1:b-s90att) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7c17498eabdd1069843e5570715c6ecb5710256c/packages/geoview-core/src/api/config/esri-renderer-parser.ts#L606)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can you put more info on what is the problem
</blockquote></details>

It's fixed, just forgot to remove the TODO, done
___
*[`packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts` line 252 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJeXHUENh-vAOCuAWk:-OCKgd11DdqgwqnjQgXV:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7c17498eabdd1069843e5570715c6ecb5710256c/packages/geoview-core/src/api/config/types/classes/geoview-config/abstract-geoview-esri-layer-config.ts#L252)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

We should put a TODO here to say we need to support all geometry type.... this is important has we have weird behaviour with the export data table
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts` line 679 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJgcw8-ddWl9IxVezy:-OCKggJ11NgoxZa0P4-e:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7c17498eabdd1069843e5570715c6ecb5710256c/packages/geoview-core/src/api/event-processors/event-processor-children/legend-event-processor.ts#L679)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should it be 0
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/common/responsive-grid.tsx` line 87 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJnVVt5vqJJV3igB3D:-OCKgit3-KpTRv0wIJ2P:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81b33d0841e26b4819b10b5ff837412d162c4d00/packages/geoview-core/src/core/components/common/responsive-grid.tsx#L87)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

That is weird... we have same prettier config but this never triggers for me
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/layer.ts` line 1410 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJnoNt2v0QcqVNMjVq:-OCKhCY99cxPkrHDZfAZ:ba3dfob) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7c17498eabdd1069843e5570715c6ecb5710256c/packages/geoview-core/src/geo/layer/layer.ts#L1410)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this still an issue, I removed this from my PR if I remember
</blockquote></details>

Removed
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 625 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJo8rEEFhqCIAsVPyu:-OCKhN7b5eYXbUD6SdgX:b-5hxr8k) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7c17498eabdd1069843e5570715c6ecb5710256c/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L625)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Seems a good cleanup as we do not have to specify stye anymore if not needed. Do you think this PR is a good simplification for style... at least a starting point
</blockquote></details>

Definitely a good start
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts` line 161 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJof_QCAo-UkyVASYz:-OCKjRce4v-XrIjP6MUO:b9fgpdf) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/7c17498eabdd1069843e5570715c6ecb5710256c/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-image.ts#L161)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

It was not set before?
</blockquote></details>

Required property now, but fixed to get correct value - this brings up another issue that I need to check though
___
*[`packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts` line 379 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJoznE6ScWLZEC_czU:-OCKhcw587PHFQa9e0BX:b-p1tzne) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81b33d0841e26b4819b10b5ff837412d162c4d00/packages/geoview-core/src/geo/layer/gv-layers/raster/gv-esri-dynamic.ts#L379)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

is this a function... is it still use? Why do we have a function before?
</blockquote></details>

The type wasn't easily available so there was a function for all types. They aren't needed so I got rid of them
___
*[`packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts` line 811 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCJpxUp3odkBHFETdbu:-OCKhxQt7utF_6Z3eY-y:b-1o4vys) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/81b33d0841e26b4819b10b5ff837412d162c4d00/packages/geoview-core/src/geo/utils/renderer/geoview-renderer.ts#L811)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Are these functions removed from the imported file?
</blockquote></details>

Yes, they are all gone

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Review by DamonU2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614)* status: all files reviewed, 1 unresolved discussion (waiting on @Alex-NRCan and @jolevesq)

___
*[`packages/geoview-core/public/templates/layers/layerlib.js` line 244 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614#-OCdmpn7Ci-xO_kd819E:-OCdqHO19ATcbnnNjPDf:binw0l3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/3bd35b918df109544d34dd0c60992cc4c85d727d/packages/geoview-core/public/templates/layers/layerlib.js#L244)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Why have you removed this. This is use in layers template html page
</blockquote></details>

Should still be fine

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2614)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Pull request merged**
