### PR TITLE
refactor(store): All state follow setterActions

### LINKED ISSUE #2148: [REFACTOR] setterActions missing in states
Some store state are missing the setterActions paradigm. Implement for all of them except layers.

### PR DESCRIPTION
**Pull request by jolevesq**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #2148

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

Hosted, May 21: 9AM: https://jolevesq.github.io/geoview/index.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2154)

### CODE REVIEW

**Review by Alex-NRCan — APPROVED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2154)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

___
*[`packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts` line 95 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2154#-NyQEzzY1YQCiRZj_zs-:-NyQEzzY1YQCiRZj_zs0:b-ybnivc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6a4f81a4e2bd571df496800dc981119a2e362faf/packages/geoview-core/src/api/event-processors/event-processor-children/time-slider-event-processor.ts#L95)):*
> ```XML
>     // Get the layer using the map event processor, If no temporal dimension OR layerPath, return undefined
>     if (!layerConfig.layerPath) return undefined;
>     const geoviewLayer = MapEventProcessor.getMapViewerLayerAPI(mapId).geoviewLayer(layerConfig.layerPath);
> ```

Quick note, after rebasing, this will be getGeoviewLayer()

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2154)* status: all files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts` line 56 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2154#-NyQWcG7BYzQjU62zABW:-NyQWcG7BYzQjU62zABX:b-wubmd8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6a4f81a4e2bd571df496800dc981119a2e362faf/packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts#L56)):*
> ```XML
>     setFiltering: (layerPath: string, filter: boolean) => void;
>     setLocked: (layerPath: string, locked: boolean) => void;
>     setReversed: (layerPath: string, locked: boolean) => void;
> ```

Most of these (setTitle, setDelay, setLocked, setReversed) are only used in ui, and ui only were left out of setter actions in map-state. Do we want to omit them here, or keep them so they can be available through API later?
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts` line 90 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2154#-NyQVEao37Fq5u62cIlE:-NyQVEao37Fq5u62cIlF:b1ax8mj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6a4f81a4e2bd571df496800dc981119a2e362faf/packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts#L90)):*
> ```XML
>       },
>       setFiltering(layerPath: string, filtering: boolean): void {
>         // Redirect to TimeSlidierEventProcessor
> ```

typo - TimeSlidier
___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts` line 107 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2154#-NyQVMbZEhNL6GHdSQ_7:-NyQVMbZEhNL6GHdSQ_8:b1ax8mj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6a4f81a4e2bd571df496800dc981119a2e362faf/packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts#L107)):*
> ```XML
>       },
>       setValues(layerPath: string, values: number[]): void {
>         // Redirect to TimeSlidierEventProcessor
> ```

typo - TimeSlidier

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2154)* status: all files reviewed, 3 unresolved discussions (waiting on @DamonU2)

___
*[`packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts` line 56 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2154#-NyQWcG7BYzQjU62zABW:-NyQXtXR3DU53udXbh8H:b8vl7rr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/6a4f81a4e2bd571df496800dc981119a2e362faf/packages/geoview-core/src/core/stores/store-interface-and-intial-values/time-slider-state.ts#L56)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Most of these (setTitle, setDelay, setLocked, setReversed) are only used in ui, and ui only were left out of setter actions in map-state. Do we want to omit them here, or keep them so they can be available through API later?
</blockquote></details>

I think it may be a good idea to have the entry point standardize d\so if it is set from api later it will still work

**Review by DamonU2 — APPROVED** [review]
> Reviewed 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2154)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Pull request merged**
