### PR TITLE
feat(geo): Add Static Image layer type

### LINKED ISSUE #953: [FEATURE] Layer Image (i.e. png) Support
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Who request this Feature

Geo.ca

### User Story

As a user, I would like to be able to add georeferenced images to the map. This image layer should be be a type raster and let us load images from extent. These thumbnails came come from a Stact browser when there is no thing to display out of the box. At least, user can see something

### Implementation UI

Add this layer type to our list of layers on layers.html

To help implementation, use

- PNG: http://datacube-prod-data-public.s3.ca-central-1.amazonaws.com/store/imagery/aerial/napl/napl-ring-of-fire/napl-ring-of-fire-1954-08-07-60k-thumbnail.png
- Metadata: https://datacube.services.geo.ca/api/collections/napl-ring-of-fire/items/napl-ring-of-fire-1954-08-07-60k?.asset=asset-thumbnail

OpenLayers sample: https://openlayers.org/en/latest/examples/static-image.html
```
new ImageLayer({
      source: new Static({
        attributions: '© <a href="https://xkcd.com/license.html">xkcd</a>',
        url: 'https://imgs.xkcd.com/comics/online_communities.png',
        projection: projection,
        imageExtent: extent,
      }),
    }),
```

### PR DESCRIPTION
**Pull request by jolevesq**
Closes #953

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR if needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010)

### CODE REVIEW

**Review by DamonU2 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010)* status: all files reviewed, 5 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/schema.json` line 569 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSGj252AnIuGzJvlt97:-NSGj252AnIuGzJvlt98:b-7ecc9l) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/schema.json#L569)):*
> ```JSON
>         "dataAccessPath": {
>           "$ref": "#/definitions/TypeLocalizedString",
>           "description": "The path (English/French) to reach the data to display. If not specified, metadatAccessPath will be assigne dto it."
> ```

Small typo - assigne dto it.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 103 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSGlYrA9IlhwzwWbufx:-NSGlYrA9IlhwzwWbufy:b-oniw04) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L103)):*
> ```XML
>    *
>    * @param {string} fieldName field name for which we want to get the type.
>    * @param {TypeLayerEntryConfig} layeConfig layer configuration.
> ```

layeConfig -> layerConfig
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 115 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSGlicC0pVigSmUnpMQ:-NSGlicC0pVigSmUnpMR:b-oniw04) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L115)):*
> ```XML
>    *
>    * @param {string} fieldName field name for which we want to get the domain.
>    * @param {TypeLayerEntryConfig} layeConfig layer configuration.
> ```

layeConfig -> layerConfig
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 262 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSGmuS57lamhCleraYJ:-NSGmuS57lamhCleraYK:b-olqdnd) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L262)):*
> ```XML
>       }
> 
>       // Note that Image Static metadata as we defined it does not contains metadata layer group. If you need geogson layer group,
> ```

geogjson -> geojson
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 299 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSGnuOG5FJlOZriGr4Y:-NSGnuOG5FJlOZriGr4Z:b-7hahfo) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L299)):*
> ```XML
>         url: getLocalizedValue(layerEntryConfig.source.dataAccessPath, this.mapId) || '',
>       };
>       if (layerEntryConfig.source.crossOrigin) sourceOptions.crossOrigin = layerEntryConfig.source.crossOrigin;
> ```

Export doesn't work, likely due to this. Try:
if (layerEntryConfig.source.crossOrigin) {
  sourceOptions.crossOrigin = layerEntryConfig.source.crossOrigin;
} else {
   sourceOptions.crossOrigin = 'Anonymous';
}

**Review by ychoquet — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010)* status: all files reviewed, 11 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/schema.json` line 581 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSM7Rqu6ZRzVWt0mFLZ:-NSM7Rqu6ZRzVWt0mFL_:b-2h6oxl) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/schema.json#L581)):*
> ```JSON
>         "featureInfo": {
>           "$ref": "#/definitions/TypeFeatureInfoLayerConfig"
>         },
> ```

I think this property does not apply to your situation. It is not possible to query a static image. Schema allow to mention that a property is not allowed using [not](https://json-schema.org/understanding-json-schema/reference/combining.html#not) and typescript has the equivalent with [never](https://www.scaler.com/topics/typescript/typescript-never/). One day, we will have to revise the way we use JSON schema because when we have an error, the output printed does not help us to track down the issue easily.



_Code quote:_
```JSON
        "featureInfo": {
          "$ref": "#/definitions/TypeFeatureInfoLayerConfig"
        },
```
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 109 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSMCDVH7iSLv0DbGdjf:-NSMCDVH7iSLv0DbGdjg:bogsk9i) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L109)):*
> ```XML
>   protected getFieldType(fieldName: string, layerConfig: TypeLayerEntryConfig): 'string' | 'date' | 'number' {
>     return 'string';
>   }
> ```

@jolevesq Remember the discussion we had the other day about abstract methods and overloading the methods of a parent, here is an example of code where it would be nice to not define the class as abstract in the parent and instead provide an implementation that returns null. Static images would not have to implement them and classes that need them would only have to override them to do the proper processing.

`getFieldType` will never be used by static images.



_Code quote:_
```XML
  protected getFieldType(fieldName: string, layerConfig: TypeLayerEntryConfig): 'string' | 'date' | 'number' {
    return 'string';
  }
```
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 121 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSMEdqRB6-LTUYdz4Ng:-NSMEdqRB6-LTUYdz4Nh:b-xda2gb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L121)):*
> ```XML
>   protected getFieldDomain(fieldName: string, layerConfig: TypeLayerEntryConfig): null | codedValueType | rangeDomainType {
>     return null;
>   }
> ```

Same as above, `getFieldDomain` will never be used by static images.



_Code quote:_
```XML
  protected getFieldDomain(fieldName: string, layerConfig: TypeLayerEntryConfig): null | codedValueType | rangeDomainType {
    return null;
  }
```
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 134 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSMF4E_25ohAaE3GkS6:-NSMF4E_25ohAaE3GkS7:b6ofj3j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L134)):*
> ```XML
>     });
>     return promisedExecution;
>   }
> ```

And here again! I initially declared it as abstract in the parent class, but I realize we should have this code in the parent instead so when a layer does not have metadata, we don't have to immplement this method.



_Code quote:_
```XML
  /** ***************************************************************************************************************************
   * This method reads the service metadata from the metadataAccessPath.
   *
   * @returns {Promise<void>} A promise that the execution is completed.
   */
  protected getServiceMetadata(): Promise<void> {
    const promisedExecution = new Promise<void>((resolve) => {
      // there is no metadata for static image layer type
      resolve();
    });
    return promisedExecution;
  }
```
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 260 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSMGldP0eOxa0TOfDfb:-NSMGldP0eOxa0TOfDfc:b-x3mypb) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L260)):*
> ```XML
>         api.map(this.mapId).layer.registerLayerConfig(layerEntryConfig);
>         return true;
>       }
> ```

The current implementation does not have metadata. If we don't plan to define a metadata structure for this type of layer, I think we should remove the metadata property from this class.



_Code quote:_
```XML
      if (!this.metadata) {
        api.map(this.mapId).layer.registerLayerConfig(layerEntryConfig);
        return true;
      }
```
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 336 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSMHuv8D1YjX2gNHhVv:-NSMHuv8D1YjX2gNHhVw:bgc5qp3) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L336)):*
> ```XML
>     });
>     return promisedExecution;
>   }
> ```

Same as discussed above. We should move it in the parent class. In short, all methods for which some layers do not need to implement should follow this rule. Some documentation must be writen on that topic though.



_Code quote:_
```XML
  /** ***************************************************************************************************************************
   * This method is used to process the layer's metadata. It will fill the empty fields of the layer's configuration (renderer,
   * initial settings, fields and aliases).
   *
   * @param {TypeVectorLayerEntryConfig} layerEntryConfig The layer entry configuration to process.
   *
   * @returns {Promise<void>} A promise that the layer configuration has its metadata processed.
   */
  protected processLayerMetadata(layerEntryConfig: TypeImageStaticLayerEntryConfig): Promise<void> {
    const promisedExecution = new Promise<void>((resolve) => {
      // there is no metadata for static image layer type
      resolve();
    });
    return promisedExecution;
  }
```

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010)* status: 3 of 26 files reviewed, 12 unresolved discussions (waiting on @DamonU2 and @ychoquet)

___
*[`packages/geoview-core/schema.json` line 569 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSGj252AnIuGzJvlt97:-NSGwEr8BOGf9LIGpftH:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/schema.json#L569)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Small typo - assigne dto it.
</blockquote></details>

Done.
___
*[`packages/geoview-core/schema.json` line 581 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSM7Rqu6ZRzVWt0mFLZ:-NSl4VUk9uTaJKDuam0S:b-3xyusu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/schema.json#L581)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

I think this property does not apply to your situation. It is not possible to query a static image. Schema allow to mention that a property is not allowed using [not](https://json-schema.org/understanding-json-schema/reference/combining.html#not) and typescript has the equivalent with [never](https://www.scaler.com/topics/typescript/typescript-never/). One day, we will have to revise the way we use JSON schema because when we have an error, the output printed does not help us to track down the issue easily.
</blockquote></details>

Created an issue for this
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 103 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSGlYrA9IlhwzwWbufx:-NSGxnMNAh57IkMtc1cx:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L103)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

layeConfig -> layerConfig
</blockquote></details>

Done
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 109 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSMCDVH7iSLv0DbGdjf:-NSl5Dy5CBT_6qd2PRMe:b33z04w) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L109)):*
> Created an issue for this
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 115 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSGlicC0pVigSmUnpMQ:-NSGyZSv0SvPZ6DhGlb3:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L115)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

layeConfig -> layerConfig
</blockquote></details>

Done
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 121 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSMEdqRB6-LTUYdz4Ng:-NSl5FaM69c4spmvRlu3:b-3xyusu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L121)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Same as above, `getFieldDomain` will never be used by static images.
</blockquote></details>

Created an issue for this
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 134 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSMF4E_25ohAaE3GkS6:-NSl5GNGA_2grLgBpI0T:b-3xyusu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L134)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

And here again! I initially declared it as abstract in the parent class, but I realize we should have this code in the parent instead so when a layer does not have metadata, we don't have to immplement this method.
</blockquote></details>

Created an issue for this
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 260 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSMGldP0eOxa0TOfDfb:-NSl5HFY5tlv8oQISHJM:b-3xyusu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L260)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

The current implementation does not have metadata. If we don't plan to define a metadata structure for this type of layer, I think we should remove the metadata property from this class.
</blockquote></details>

Created an issue for this
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 262 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSGmuS57lamhCleraYJ:-NSGysPp3CalD_-f2ECI:bb6un1j) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L262)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

geogjson -> geojson
</blockquote></details>

Done
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 299 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSGnuOG5FJlOZriGr4Y:-NSGzyOAEop6h5_oNtdF:bfy996u) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L299)):*
<details><summary><i>Previously, DamonU2 (Damon Ulmi) wrote…</i></summary><blockquote>

Export doesn't work, likely due to this. Try:
if (layerEntryConfig.source.crossOrigin) {
  sourceOptions.crossOrigin = layerEntryConfig.source.crossOrigin;
} else {
   sourceOptions.crossOrigin = 'Anonymous';
}
</blockquote></details>

Did the trick, thanks!
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts` line 336 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSMHuv8D1YjX2gNHhVv:-NSl5IFiBCQnXEZsJqxG:b-3xyusu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8c3afa8f72407beecfdfde22ef47fce4d7e14651/packages/geoview-core/src/geo/layer/geoview-layers/raster/image-static.ts#L336)):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

Same as discussed above. We should move it in the parent class. In short, all methods for which some layers do not need to implement should follow this rule. Some documentation must be writen on that topic though.
</blockquote></details>

Created an issue for this

**Review by jolevesq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010)* status: 3 of 26 files reviewed, 12 unresolved discussions (waiting on @DamonU2 and @ychoquet)

*[a discussion](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010#-NSMJMuYC9iz2hvQxAvB:-NSlGxo0-KuRWFPqD231:b-l9qmnp) (no related file):*
<details><summary><i>Previously, ychoquet (Yves Choquette) wrote…</i></summary><blockquote>

@jolevesq Since I'm the author of this section of code, do you want me revise and correct the abstract vs override behaviour of our inheriance tree in a new PR? (see comments below)
</blockquote></details>

Yes, issue created

___

**Review by jolevesq — COMMENTED** [review]
> Reviewed 3 of 13 files at r1, 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010)* status: all files reviewed, 12 unresolved discussions (waiting on @DamonU2 and @ychoquet)

**Review by ychoquet — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1010)* status: all files reviewed, 5 unresolved discussions (waiting on @DamonU2)

**Review by DamonU2 — APPROVED** [review]

**Pull request merged**
