### PR TITLE
fix(geocore): refactor layerOrder to keep geocore in proper order

### LINKED ISSUE #1852: [BUG] Geocore layers not following other layers structure
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A geocore layer with multiple layers in listOfLayerEntryConfig does not create a group layer containing the layers, but treats them each as separate layers. Also, layer ID and layerPath structure as a result differs from other layer types (ID issue in #683).

### Expected Behavior

Geocore layer structure should match other layer types.

### Steps To Reproduce

Go to https://canadian-geospatial-platform.github.io/geoview/public/geocore.html
The config has one geocore layer with four entries in listOfLayerEntryConfig, but we get four individual layers on the map.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by DamonU2**
Closes #1852

# Description

Layer order now maintains geocore layers in the proper location when they switch to the actual layer type.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

https://damonu2.github.io/geoview/all-layers.html
https://damonu2.github.io/geoview/geocore.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1861)

### CODE REVIEW

**Review by Alex-NRCan — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1861#-:-Nrg04IF6cfX1_Ty2qtn:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jolevesq)

**Review by jolevesq — APPROVED** [review]
> Reviewed 3 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1861)* status: 7 of 14 files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1861)* status: 7 of 14 files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1861)* status: 8 of 14 files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> Reviewed 3 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1861)* status: 8 of 14 files reviewed, all discussions resolved (waiting on @Alex-NRCan)

**Review by jolevesq — APPROVED** [review]
> Reviewed 1 of 11 files at r1, 6 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1861)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Review by jolevesq — APPROVED** [review]
> Reviewed 11 of 11 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1861)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @DamonU2)

**Pull request merged**
