### PR TITLE
feat(details-panels): Left and right panels in footer details

### LINKED ISSUE #463: Panel UI - Details
Implement as per Ken's mockups.

### PR DESCRIPTION
**Pull request by amir-azma**
# Description

Build new Details based on new design left/right panel. 
Layer list will be displayed on left panel.
Feature info for the selected layer will be displayed on right panel with highlight and zoom functionality.

Fixes #463 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Once we select a point on the map, we should be able to view the layer list and features in footer panel in Details tab.

__Add the URL for your deploy!__

# Checklist:

- [ ] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 3 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270)* status: 3 of 16 files reviewed, 22 unresolved discussions (waiting on @amir-azma, @cphelefu, and @ychoquet)

___
*[`packages/geoview-core/public/locales/fr/translation.json` line 64 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9fp5W3Y9jt8j54OGQ:-Ne9fp5W3Y9jt8j54OGR:b-e40413) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/public/locales/fr/translation.json#L64)):*
> ```JSON
>     "detailsView": "Vue détaillée",
>     "selectVisbleLayer": "Sélectionnez n'importe quelle couche visible sur la carte pour commencer",
>     "availableLayers": "Calques disponibles",
> ```

Couche instead of Calques
___
*[`packages/geoview-core/public/locales/fr/translation.json` line 65 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9fuqk1-gd7DWYArJq:-Ne9fuqk1-gd7DWYArJr:b-nbf6yu) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/public/locales/fr/translation.json#L65)):*
> ```JSON
>     "selectVisbleLayer": "Sélectionnez n'importe quelle couche visible sur la carte pour commencer",
>     "availableLayers": "Calques disponibles",
>     "selectedFeature": "Fonctionnalité sélectionnée"
> ```

Item instead of Fonctionnalité
___
*[`packages/geoview-core/public/templates/raw-feature-info-1.html` line 323 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9g8TLChGTyPqsNwnd:-Ne9g8TLChGTyPqsNwne:b-7wm6e6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/public/templates/raw-feature-info-1.html#L323)):*
> ```HTML
>         // import react and api from the core
>         const { createRoot, api } = cgpv;
>         
> ```

Remove trailing white space
___
*[`packages/geoview-core/public/templates/raw-feature-info-1.html` line 330 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9gIP19IiomMgEmDIq:-Ne9gIP19IiomMgEmDIr:bnu9pi) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/public/templates/raw-feature-info-1.html#L330)):*
> ```HTML
>                 const newDetails = [];
> 
>                 Object.keys(resultSets).forEach((layerPath) => {
> ```

The logic of looping and getting details should be in your api function. Here you should pass the whole result set to your api function
___
*[`packages/geoview-core/public/templates/raw-feature-info-1.html` line 347 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9g3A5CvAiHInUAUqZ:-Ne9g3A5CvAiHInUAUq_:b-7wm6e6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/public/templates/raw-feature-info-1.html#L347)):*
> ```HTML
>               'LYR2/$FeatureInfoLayerSet$'
>             );
>       
> ```

Remove trailing white space
___
*[`packages/geoview-core/src/core/components/details/details.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9hC8A4dw-_ue2DjQD:-Ne9hC8A4dw-_ue2DjQE:b-s5uuu6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details/details.tsx#L2)):*
> ```XML
> import React, { useEffect, useState } from 'react';
> import { Coordinate } from 'ol/coordinate';
> ```

Modification in details and you are working on detail-1. Can we revert?
___
*[`packages/geoview-core/src/core/components/details/details-api.ts` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9hAbz43Ca8aztHfN-:-Ne9hAc-1YPuf9SLbx6W:b-s5uuu6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details/details-api.ts#L3)):*
> ```XML
> import { createElement, ReactElement } from 'react';
> import { FeatureInfoLayerSet } from '@/geo/utils/feature-info-layer-set';
> import { api } from '@/app';
> ```

Modification in details and you are working on detail-1. Can we revert?
___
*[`packages/geoview-core/src/core/components/details/layers-list.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9h7i64psg-1mvzOEi:-Ne9h7i64psg-1mvzOEj:b-s5uuu6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details/layers-list.tsx#L2)):*
> ```XML
> /* eslint-disable prettier/prettier */
> /* eslint-disable react/require-default-props */
> ```

Modification in details and you are working on detail-1. Can we revert?
___
*[`packages/geoview-core/src/core/components/details/layers-list-footer.tsx` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9h0kdBr3m3gak4UZ1:-Ne9h0kdBr3m3gak4UZ2:b-s5uuu6) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details/layers-list-footer.tsx#L1)):*
> ```XML
> /* eslint-disable @typescript-eslint/no-unused-vars */
> ```

Modification in details and you are working on detail-1. Can we revert?
___
*[`packages/geoview-core/src/core/components/details-1/details.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9gtE02Srx1ZACwhTz:-Ne9gtE02Srx1ZACwhU-:b-a9ynve) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details-1/details.tsx#L2)):*
> ```XML
> import React, { useEffect, useState } from 'react';
> // import { Coordinate } from 'ol/coordinate';
> ```

Do we need dead import?
___
*[`packages/geoview-core/src/core/components/details-1/details.tsx` line 6 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9guJY3NJ_rm6djJIQ:-Ne9guJY3NJ_rm6djJIR:b6q5cnj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details-1/details.tsx#L6)):*
> ```XML
> import { LayersListFooter } from './layers-list-footer';
> 
> // export interface DetailsProps {
> ```

Do we still need?
___
*[`packages/geoview-core/src/core/components/details-1/details.tsx` line 32 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9gyD778mWRT3-_hxp:-Ne9gyD778mWRT3-_hxq:b-kekqvk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details-1/details.tsx#L32)):*
> ```XML
> export function DetailsFooter({ arrayOfLayerData, mapId }: TypeDetailsProps): JSX.Element | null {
>   // eslint-disable-next-line @typescript-eslint/no-unused-vars
>   // const { arrayOfLayerData, mapId } = props;
> ```

Do we still need
___
*[`packages/geoview-core/src/core/components/details-1/details-api.tsx` line 6 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9gpPw2WqgnwQsEZm1:-Ne9gpPw2WqgnwQsEZm2:b-a9ynve) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details-1/details-api.tsx#L6)):*
> ```XML
> 
> import { DetailsFooter, TypeArrayOfLayerData } from './details';
> // import { DetailsFooter } from './details-new';
> ```

Do we need dead import?
___
*[`packages/geoview-core/src/core/components/details-1/details-api.tsx` line 30 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9gnfBDYRz7xxc0Ekq:-Ne9gnfBDYRz7xxc0Ekr:b5au9uk) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details-1/details-api.tsx#L30)):*
> ```XML
> 
>   /**
>    * Create a details as as an element
> ```

Double as
___
*[`packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9iAkU7WaMEEyJT5ug:-Ne9iAkU7WaMEEyJT5uh:bcrzniq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx#L5)):*
> ```XML
> import React, { useEffect, useState, useRef } from 'react';
> import { useTranslation } from 'react-i18next';
> import { Paper, Typography } from '@mui/material';
> ```

Should came from our ui folder not material ui
___
*[`packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx` line 15 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9hIry4lQ-xaCQc04u:-Ne9hIry4lQ-xaCQc04v:bsk627f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx#L15)):*
> ```XML
> 
> const sxClasses = {
>   footerTopPanlePrimary: {
> ```

All font should come from the theme as reusable theme parameter
___
*[`packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9i_Xw5S7zQXbKuuKy:-Ne9i_Xw5S7zQXbKuuKz:b-rpgqlh) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx#L37)):*
> ```XML
> 
> /**
>  * layers list
> ```

Missing @param in function description
___
*[`packages/geoview-core/src/core/components/feature-info-new.ts/feature-info-new.tsx` line 4 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9iIdw5LmL_t-XURXQ:-Ne9iIdw5LmL_t-XURXR:b-673oi1) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/feature-info-new.ts/feature-info-new.tsx#L4)):*
> ```XML
> /* eslint-disable react/require-default-props */
> import React, { MutableRefObject, useEffect, useState } from 'react';
> import { useTheme, Theme } from '@mui/material/styles';
> ```

style is deprecated we should not use it
___
*[`packages/geoview-core/src/core/components/feature-info-new.ts/feature-info-new.tsx` line 6 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9iNKj7x0RYrWLj30x:-Ne9iNKj7x0RYrWLj30y:bcrzniq) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/feature-info-new.ts/feature-info-new.tsx#L6)):*
> ```XML
> import { useTheme, Theme } from '@mui/material/styles';
> import { useTranslation } from 'react-i18next';
> import { Paper } from '@mui/material';
> ```

Should came from our ui folder not material ui
___
*[`packages/geoview-core/src/core/components/feature-info-new.ts/feature-info-new.tsx` line 23 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9hlwQ0Z1GUgWGRTTZ:-Ne9hlwQ0Z1GUgWGRTT_:b8kl93y) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/feature-info-new.ts/feature-info-new.tsx#L23)):*
> ```XML
>     noWrap: true,
>     '& .MuiListItemText-primary': {
>       font: 'normal normal 600 20px/27px Roboto, Helvetica, Arial, sans-serif',
> ```

Text should came from theme
___
*[`packages/geoview-core/src/core/components/feature-info-new.ts/feature-info-new.tsx` line 74 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9iSNH9HdczzFmRnxz:-Ne9iSNH9HdczzFmRny-:b-neq972) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/feature-info-new.ts/feature-info-new.tsx#L74)):*
> ```XML
> 
> /**
>  * feature info for a layer list
> ```

Missing parameter @param in function description
___
*[`packages/geoview-core/src/core/components/feature-info-new.ts/feature-info-table.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9ioPO0mV9H16SfH5a:-Ne9ioPO0mV9H16SfH5b:b-u3b0n5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/feature-info-new.ts/feature-info-table.tsx#L2)):*
> ```XML
> /* eslint-disable @typescript-eslint/no-unused-vars */
> import React, { useState } from 'react';
> ```

Is this code use? It is not in details-1

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270)* status: 3 of 16 files reviewed, 22 unresolved discussions (waiting on @cphelefu, @jolevesq, @param, and @ychoquet)

___
*[`packages/geoview-core/public/locales/fr/translation.json` line 64 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9fp5W3Y9jt8j54OGQ:-Ne9latD6D6cEa8S1yK0:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/public/locales/fr/translation.json#L64)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Couche instead of Calques
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/locales/fr/translation.json` line 65 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9fuqk1-gd7DWYArJq:-Ne9lprBE7imiRGmoT9p:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/public/locales/fr/translation.json#L65)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Item instead of Fonctionnalité
</blockquote></details>

Done.
___
*[`packages/geoview-core/public/templates/raw-feature-info-1.html` line 323 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9g8TLChGTyPqsNwnd:-Ne9mJBB7wN0wPWwlFbQ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/public/templates/raw-feature-info-1.html#L323)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Remove trailing white space
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details/details.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9hC8A4dw-_ue2DjQD:-Ne9nx8S0BYohovUPLSM:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details/details.tsx#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Modification in details and you are working on detail-1. Can we revert?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details/details-api.ts` line 3 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9hAbz43Ca8aztHfN-:-Ne9o6Nc5vZUjAoUXLxS:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details/details-api.ts#L3)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Modification in details and you are working on detail-1. Can we revert?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details/layers-list.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9h7i64psg-1mvzOEi:-Ne9qlIc98zvMyk6FugP:b5fi3oc) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details/layers-list.tsx#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Modification in details and you are working on detail-1. Can we revert?
</blockquote></details>

I will revert it back.
___
*[`packages/geoview-core/src/core/components/details/layers-list-footer.tsx` line 1 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9h0kdBr3m3gak4UZ1:-Ne9rZ6y2qMsFMd6HWmr:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details/layers-list-footer.tsx#L1)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Modification in details and you are working on detail-1. Can we revert?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details-1/details.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9gtE02Srx1ZACwhTz:-Ne9rheX4dBS-jm0kljh:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details-1/details.tsx#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we need dead import?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details-1/details.tsx` line 6 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9guJY3NJ_rm6djJIQ:-Ne9rjIFEKNXaRyxt8Rb:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details-1/details.tsx#L6)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we still need?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details-1/details.tsx` line 32 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9gyD778mWRT3-_hxp:-Ne9t9M6Crvf4QqyXAga:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details-1/details.tsx#L32)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we still need
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details-1/details-api.tsx` line 6 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9gpPw2WqgnwQsEZm1:-Ne9tM7U-UkX3YbMtNMc:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details-1/details-api.tsx#L6)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Do we need dead import?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details-1/details-api.tsx` line 30 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9gnfBDYRz7xxc0Ekq:-Ne9tRBKBI_doIx67Rx4:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details-1/details-api.tsx#L30)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Double as
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx` line 15 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9hIry4lQ-xaCQc04u:-NeAsjnx3VIRC5npC1Ri:brcfpgz) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx#L15)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

All font should come from the theme as reusable theme parameter
</blockquote></details>

Sure, we will use the theme related to the new UI design after we implement the new theme. Per our discussion, we leave this change as is for now, later we will use the new theme in all new UI design. 
___
*[`packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx` line 37 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9i_Xw5S7zQXbKuuKy:-NeAshXt8hJqKgU5ThDw:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx#L37)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Missing @param in function description
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/feature-info-new.ts/feature-info-new.tsx` line 4 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9iIdw5LmL_t-XURXQ:-NeAu9pJBToJVZ29Lp8M:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/feature-info-new.ts/feature-info-new.tsx#L4)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

style is deprecated we should not use it
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/feature-info-new.ts/feature-info-new.tsx` line 23 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9hlwQ0Z1GUgWGRTTZ:-NeE6QksEa9HrC_jqPe6:b-nv7vnj) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/feature-info-new.ts/feature-info-new.tsx#L23)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Text should came from theme
</blockquote></details>

We plan to have a new theme for UI new design, I will make the changes based on the new theme
___
*[`packages/geoview-core/src/core/components/feature-info-new.ts/feature-info-new.tsx` line 74 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9iSNH9HdczzFmRnxz:-NeE7TT65oBA_LLBE8r2:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/feature-info-new.ts/feature-info-new.tsx#L74)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Missing parameter @param in function description
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/feature-info-new.ts/feature-info-table.tsx` line 2 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9ioPO0mV9H16SfH5a:-NeE7vs41t0t8JYIN481:b-bdumza) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/feature-info-new.ts/feature-info-table.tsx#L2)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Is this code use? It is not in details-1
</blockquote></details>

Yes this file feature-info-new.tsx   is suing   feature-info-table.tsx  ,   feature-info-new.tsx  is getting called from  details-1

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270)* status: 1 of 19 files reviewed, 22 unresolved discussions (waiting on @cphelefu, @jolevesq, @param, and @ychoquet)

___
*[`packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx` line 5 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-Ne9iAkU7WaMEEyJT5ug:-NeEsCzp1kuC6CZJQPd_:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/66fffa4a1f1ecf96188854d6d88ebecd5b48035b/packages/geoview-core/src/core/components/details-1/layers-list-footer.tsx#L5)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should came from our ui folder not material ui
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
:lgtm: 

> Reviewed 9 of 16 files at r1, 10 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270#-:-NeExUSz6v7NZLprTBtG:bg7igkv)* status: 17 of 19 files reviewed, 3 unresolved discussions (waiting on @cphelefu and @ychoquet)

**Review by jolevesq — COMMENTED** [review]
> Reviewed 2 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270)* status: all files reviewed, 3 unresolved discussions (waiting on @cphelefu and @ychoquet)

**Review by jolevesq — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1270)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cphelefu and @ychoquet)

**Pull request merged**
