### PR TITLE
feat(footer-bar): Refactor footer-bar, attribution and more

### LINKED ISSUE #1406: [BUG] map and footer-bar extend out of div at certain sizes
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

At certain sizes (between a window size of about 960-1090 pixels) the map and footer-bar extend outside of the div containing them, which cuts off the overview-map and footer-bar. This also causes some shaking when mousing over the map.

image

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by amir-azma**
# Description

Fixes issues in footer-bar that the map and footer-bar extend outside of the div containing them, which cuts off the overview-map and footer-bar. This also causes some shaking when mousing over the map.

Added 3 dots icon in small size pages that will open in popover component to display the attributions.

Fixes #1406 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please open footer-bar and try to resize the page in different sizes, the Fix North and Overview map should not get cut from the container div, we should not have shaking map in some areas if we hover the map, also we should be able to use popover content of attribution.

https://amir-azma.github.io/geoview/index.html

# Checklist:

- [x] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [x] I have connected the issues(s) to this PR
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1533)

### CODE REVIEW

**Review by jolevesq — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1533)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @amir-azma)

___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 25 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1533#-Nk0Z0CEEutIR1qP95Fa:-Nk0Z0CEEutIR1qP95Fb:b-p2wy73) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/08e72c209f24742e4e30c013fb14c34b3b4de3bc/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L25)):*
> ```XML
>   const mapConfig = useContext(MapContext);
>   const { mapId } = mapConfig;
>   const theme = useTheme();
> ```

Need a blank row before const theme
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 27 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1533#-Nk0Z4La8rvkOB7Ixz2b:-Nk0Z4La8rvkOB7Ixz2c:bcpffkr) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/08e72c209f24742e4e30c013fb14c34b3b4de3bc/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L27)):*
> ```XML
>   const theme = useTheme();
> 
>   // get store values
> ```

Store items should be after internal state (separated with  blank row
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-fixnorth-switch.tsx` line 23 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1533#-Nk1wLpKCZhqYRyhTocq:-Nk1wLpKCZhqYRyhTocr:b-163ee5) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0ef5c232f0175d3972b5f550205444eae87ea336/packages/geoview-core/src/core/components/footer-bar/footer-bar-fixnorth-switch.tsx#L23)):*
> ```XML
> export function FooterbarFixNorthSwitch(): JSX.Element {
>   const { t } = useTranslation<string>();
>   const theme = useTheme();
> ```

Blank row before theme
https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/docs/programming/best-practices.md#8--how-we-order-code-at-the-beginning-of-a-component

**Review by amir-azma — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1533)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @jolevesq)

___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 25 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1533#-Nk0Z0CEEutIR1qP95Fa:-Nk20tNZEVQopORGQh-t:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/08e72c209f24742e4e30c013fb14c34b3b4de3bc/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L25)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Need a blank row before const theme
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 27 at r1](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1533#-Nk0Z4La8rvkOB7Ixz2b:-Nk212dp1PfdVGmgkWiQ:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/08e72c209f24742e4e30c013fb14c34b3b4de3bc/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L27)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Store items should be after internal state (separated with  blank row
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar-fixnorth-switch.tsx` line 23 at r2](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1533#-Nk1wLpKCZhqYRyhTocq:-Nk21Ntk6QZIpiP5uSx4:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/0ef5c232f0175d3972b5f550205444eae87ea336/packages/geoview-core/src/core/components/footer-bar/footer-bar-fixnorth-switch.tsx#L23)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Blank row before theme
https://github.com/Canadian-Geospatial-Platform/geoview/blob/develop/docs/programming/best-practices.md#8--how-we-order-code-at-the-beginning-of-a-component
</blockquote></details>

Done.

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1533)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amir-azma)

**Review by jolevesq — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/1533)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @amir-azma)

**Pull request merged**
