### PR TITLE
Added new TypeScript rules

### PR DESCRIPTION
**Pull request by Alex-NRCan**
# Description

This PR adds new TypeScript rules to facilitate development and implement best practices.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Hosting May 9th 8h50: https://alex-nrcan.github.io/geoview/

# Checklist:

- [ ] I have build __(rush build)__ and deploy __(rush host)__ my PR
- [ ] I have connected the issues(s) to this PR
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have created new issue(s) related to the outcome of this PR is needed
-  ~~I have made corresponding changes to the documentation~~
-  ~~I have added tests that prove my fix is effective or that my feature works~~
-  ~~New and existing unit tests pass locally with my changes~~

- - -
This change is [Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106)

### CODE REVIEW

**Review by jolevesq — COMMENTED** [review]
> Reviewed 82 of 86 files at r1, 4 of 5 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 13 of 13 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106)* status: all files reviewed, 9 unresolved discussions (waiting on @Alex-NRCan and @ychoquet)

___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 117 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106#-NxOtus-1hYSECW4_cHL:-NxOtus-1hYSECW4_cHM:b-m5rxw8) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1e97d662ede24da83ced685d8136f913217adad/packages/geoview-core/src/api/config/uuid-config-reader.ts#L117)):*
> ```XML
>   }
> 
>   // TODO: Check - Commented out as not called anymore by method `getGVConfigFromUUIDs`, but maybe it should still?
> ```

Like we discuss it should be called, we will update in a next PR
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/config-base-class.ts` line 23 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106#-NxOu7lc5__LGl3B_phZ:-NxOu7ld52vjkOf-iLj0:b-kdjcow) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1e97d662ede24da83ced685d8136f913217adad/packages/geoview-core/src/api/config/types/classes/sub-layer-config/config-base-class.ts#L23)):*
> ```XML
> 
>   /** Used internally to distinguish layer groups derived from the metadata. */
>   // #isMetadataLayerGroup?: false;
> ```

Can we put a TODO so we do not loose dead code
___
*[`packages/geoview-core/src/core/components/common/layer-title.tsx` line 35 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106#-NxOuhsq8r6wqFmmCrtU:-NxOuhsq8r6wqFmmCrtV:b-8j00uy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8a4d29e002145d68100a57f52692e44972219897/packages/geoview-core/src/core/components/common/layer-title.tsx#L35)):*
> ```XML
> }
> 
> // TODO: Refactor - Remove defaltProps as it's no longer a good practice
> ```

typo defaultProps
___
*[`packages/geoview-core/src/core/components/common/layout.tsx` line 79 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106#-NxOunZ_0tQwmgQCrT3e:-NxOunZ_0tQwmgQCrT3f:b-8j00uy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8a4d29e002145d68100a57f52692e44972219897/packages/geoview-core/src/core/components/common/layout.tsx#L79)):*
> ```XML
> }
> 
> // TODO: Refactor - Remove defaltProps as it's no longer a good practice
> ```

typo defaultProps
___
*[`packages/geoview-core/src/core/components/common/responsive-grid.tsx` line 138 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106#-NxOupjL6GkVSq4EIj_N:-NxOupjL6GkVSq4EIj_O:b-8j00uy) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8a4d29e002145d68100a57f52692e44972219897/packages/geoview-core/src/core/components/common/responsive-grid.tsx#L138)):*
> ```XML
> };
> 
> // TODO: Refactor - Remove defaltProps as it's no longer a good practice
> ```

typo defaultProps
___
*[`packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx` line 326 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106#-NxOurZp5cGOSB-7s0V7:-NxOurZp5cGOSB-7s0V8:b-fh0p0i) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8a4d29e002145d68100a57f52692e44972219897/packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx#L326)):*
> ```XML
> ResponsiveGridLayout.displayName = 'ResponsiveGridLayout';
> 
> // TODO: Refactor - Remove defaltProps as it's no longer a good practice
> ```

replace all...
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 6 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106#-NxOv-Dk1NyXSbDsslnZ:-NxOv-Dk1NyXSbDssln_:b-t61h1r) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9c5f8b743dba45adc65fd2063496f67b717ff6de/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L6)):*
> ```XML
> 
> import { Box, IconButton, Tabs, TypeTabs, MoveDownRoundedIcon, MoveUpRoundedIcon } from '@/ui';
> import { api } from '@/app';
> ```

Another remove of api... yeah!
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 437 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106#-NxOvr0YCQ3k3NpuqJBM:-NxOvr0YCQ3k3NpuqJBN:bm6x2t0) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1e97d662ede24da83ced685d8136f913217adad/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L437)):*
> ```XML
>    * the feature.
>    */
>   private static countFieldOfTheSameValue(styleSettings: TypeUniqueValueStyleConfig): TypeFieldOfTheSameValue[][] {
> ```

Should we put private #?
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts` line 95 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106#-NxOwILD023hWwLcr2l_:-NxOwILD023hWwLcr2la:bcrv69f) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1e97d662ede24da83ced685d8136f913217adad/packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts#L95)):*
> ```XML
> export class OgcFeature extends AbstractGeoViewVector {
>   // private variable holding wfs version
>   // private version = '2.0.0';
> ```

If not use, should we remove or put a TODO?

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 85 of 86 files at r1, 5 of 5 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, 13 of 13 files at r5, 1 of 1 files at r6, 16 of 16 files at r7.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @jolevesq and @ychoquet)

___
*[`packages/geoview-core/src/api/config/uuid-config-reader.ts` line 117 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106#-NxOtus-1hYSECW4_cHL:-NxOzs3M2nCYWuV-UkD3:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1e97d662ede24da83ced685d8136f913217adad/packages/geoview-core/src/api/config/uuid-config-reader.ts#L117)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Like we discuss it should be called, we will update in a next PR
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/api/config/types/classes/sub-layer-config/config-base-class.ts` line 23 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106#-NxOu7lc5__LGl3B_phZ:-NxP-4lUCEJIxuehXQBw:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1e97d662ede24da83ced685d8136f913217adad/packages/geoview-core/src/api/config/types/classes/sub-layer-config/config-base-class.ts#L23)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Can we put a TODO so we do not loose dead code
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx` line 326 at r5](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106#-NxOurZp5cGOSB-7s0V7:-NxP-HvJ-OVpFW5NWm3U:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/8a4d29e002145d68100a57f52692e44972219897/packages/geoview-core/src/core/components/common/responsive-grid-layout.tsx#L326)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

replace all...
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx` line 6 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106#-NxOv-Dk1NyXSbDsslnZ:-NxP-JPy6kRULxkPCc1F:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/9c5f8b743dba45adc65fd2063496f67b717ff6de/packages/geoview-core/src/core/components/footer-bar/footer-bar.tsx#L6)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Another remove of api... yeah!
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts` line 437 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106#-NxOvr0YCQ3k3NpuqJBM:-NxP-Pl27E2illQXHW68:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1e97d662ede24da83ced685d8136f913217adad/packages/geoview-core/src/geo/layer/geoview-layers/raster/esri-dynamic.ts#L437)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

Should we put private #?
</blockquote></details>

Done.
___
*[`packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts` line 95 at r3](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106#-NxOwILD023hWwLcr2l_:-NxP-Zf62up1qgtxa8nc:b-896fix) ([raw file](https://github.com/Canadian-Geospatial-Platform/geoview/blob/e1e97d662ede24da83ced685d8136f913217adad/packages/geoview-core/src/geo/layer/geoview-layers/vector/ogc-feature.ts#L95)):*
<details><summary><i>Previously, jolevesq (Johann Levesque) wrote…</i></summary><blockquote>

If not use, should we remove or put a TODO?
</blockquote></details>

Done.

**Review by jolevesq — COMMENTED** [review]
> Reviewed 16 of 16 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> Reviewed 11 of 11 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by Alex-NRCan — COMMENTED** [review]
> Reviewed 11 of 11 files at r8, 11 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Review by jolevesq — APPROVED** [review]
> Reviewed 11 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/Canadian-Geospatial-Platform/geoview/2106)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ychoquet)

**Pull request merged**
